== Chapter I.

Preliminary Remarks on the State of the Society About the End of the Eighteenth Century.

The Society of Friends (commonly called Quakers) has been assailed,
during the present century, in a marvelous and unexampled manner,
by a series of convulsions arising not from without but from within;
from defections of its own members from its fundamental principles.
It is the aim of the following pages to trace the working of these convulsions,
and to endeavor to show the difference between true
Quakerism (so called) and false pretensions.

The beginning of the nineteenth century found the Society, as a whole,
a living and influential body, though in many of its parts,
and in some of its general features, in a languid condition.
A large proportion of its members were still sincerely attached
to its original and characteristic principles and discipline;
and not a few, both in Great Britain and in America,
were earnestly concerned to live in accordance therewith,
under the guidance and help of Him who promised to
be with His own to the end of the world,
and to lead and guide them by His Spirit into all truth.
And it is believed that at this time such a thing was entirely unknown in the Society,
as the sanctioning, by any meeting, greater or smaller,
of an open departure from its ancient faith and doctrine.

Nevertheless,
in many places--perhaps to some extent in all its quarters--the spirit of the world,
and the fascinations of affluence and ease, had made successful inroads;
and the love of many for its self-denying life had grown cold, and had given place,
especially in America, to great apathy and unconcern as to a religious life and conduct;
and in England to a weariness with the restrictions attendant on a real
conformity with the principles and discipline of their profession;
an unwillingness to wait on the Lord in all humility for
the fresh manifestations of his will to them individually;
and a disposition on the contrary to indulge, along with the world,
in many things by it considered lawful,
but which were certainly not expedient for the promotion of a self-denying life.
There was, however, as yet, no general and obvious intention manifested,
to discard or modify the primitive doctrines of the Society,
except perhaps that the great doctrine of perfect freedom
from sin was being gradually ignored or lost sight of.
There had been some local and limited departures from sound doctrine,
but these had not been of such magnitude as to unsettle the whole Society;
and indeed were of a nature not likely to attract any great number of adherents.

It may be well, here, to revert briefly to the solid,
substantial character of the religion of our early Friends--of those who
were instrumental in establishing the Society as a distinct people,
and also of those who came after them, to sustain it in the same faith.
When it pleased the most High to raise up, by means of our forefathers,
a people to stand as a visible gathered church,
professedly and practically on the foundation of His pure and unchangeable
truth--even primitive Christianity unmixed with human contrivances--it
was in great abasedness of self that they went forth,
and with a constant reliance on the putting forth and going before,
of Him who had called them into his especial service.
They had passed through many and deep trials in their heavenward journey,
and bought the truth at a price; having, according to their respective measures,
known what it was to be crucified with Christ, spiritually,
buried with Him by baptism unto death, and raised again, by his mighty power and love,
into newness of life, and communion with Him and his church militant.

They had fairly weighed the value of this world in the balance of the sanctuary,
and found it lighter than vanity.
And having left all for the sake of peace with God, and put on strength, in his name,
and in his power, not their own, to run all the ways of his requiring,
they were not to be prevailed upon, by the fascinations of worldly ease,
or the threatenings and actual sufferings inflicted by the enemies of truth,
to forsake the cross-bearing principles of primitive Christianity which
they felt themselves divinely called to profess before the world,
and to exemplify by a holy life and conduct;
nor to barter them away by any cowardly connivance with measures calculated,
although in a covert and hardly perceptible manner, to undermine their precious faith,
or destroy the vitality of their testimony for the truth and against error.
Indeed they were exceedingly alive to,
and jealous of anything which tended in the smallest degree in that direction;
and were constantly on the alert to sound an alarm of such dangers,
and to expose all such attempts; so that neither the flock should receive injury,
nor the cause of truth be subjected to reproach, by any supineness on their part.
Witness the vast multitude and variety of their controversial writings,
published during the first half century of the existence of the Society,
to repel attacks or insinuations of the enemies of truth from abroad,
or of no less hostile apostates from their own ranks.

Their successors, in the eighteenth century,
came into possession of a comparatively quiet and peaceable inheritance--an inheritance
not gained through their own sufferings--for the Society had outlived the rancorous
hostility by which at first it had been hoped to suppress it;
and there were now comparatively few calls upon the zeal of its members,
either to endure suffering for their testimony to the truth,
or to come forward in its defence against gainsayers through the press.
Nevertheless,
the comparatively few instances which did occur (during
this period) in which opponents came against the Society,
or false brethren arose to promote disorders within it, were promptly met,
and measures faithfully taken to answer the injurious allegations of the one,
or frustrate the dividing schemes of the other.
No such thing as an open attempt at modification of its
primitive doctrines was permitted to pass unchecked.
And many eminent instruments continued to be raised up, throughout that century,
to promulgate the ancient faith,
in a measure of the true zeal and faithfulness of their predecessors.

Yet, in looking over the body at large, about the close of the eighteenth century,
it is impossible to resist the conviction, that notwithstanding the original doctrines,
and to a considerable degree the characteristic practices of the Society had been sustained,
and many of its members were livingly concerned to walk worthy of its high vocation,
and moreover that some of its views of pure religion
and morality were making gradual headway in the world,
and ameliorating certain corruptions of public sentiment,
which had for centuries been blots upon the profession of Christianity;
and thus its principles were surely, though perhaps imperceptibly,
operating as a leaven in the community,
to improve the general condition of public feeling,
if not of professing Christian societies;
yet that a state of lethargy was coming over many of its members,
accompanied by sad ignorance of the vital principles of their profession;
a state of ease was eating out the good seed in the minds of others;
and a state of mere formality,
promoting a strict but lifeless maintenance of the outward forms and discipline,
was beginning to characterize the walk of some more
or less active members in various places;
altogether producing a condition of weakness,
in which the Body was ill prepared to continue the work of "`earnestly
contending for the faith once delivered to the saints,`" in case
of the arrival of any unexpected and general storm.

In short, it may safely be said of this period,
that only a small proportion of the members of the Society at large had really submitted,
in the school of Christ,
to those deep baptisms and thorough lessons which are needful to prepare the soul for
walking in that path which "`shines more and more unto perfect day,`" and which Stephen
Crisp has so well described in his graphic account of his own early experience;
but many had taken up with an easier way, the way of a more superficial learning,
through books and from one another.
Hence the Society was overrun with the results and influence of shallow experience.
And this condition of things increased continually
after the beginning of the nineteenth century.
A sense of this languid and lapsing condition of the Society
was acknowledged by the Yearly Meeting of London,
in its General Epistle of 1799, wherein they made use of the following language: "`Now,
turning our attention to the church in its more collected capacity,
of Monthly and Quarterly Meetings,
we perceive that weakness and languor continue to
pervade the deliberations of some of them,
on the important concerns of the Society;
and often prevent the due and timely support of that Christian discipline,
which we have long experienced to be, under Providence, as a wall of preservation.`"

As a result of this languor, and of the encroachments of an easy, worldly,
superficial spirit, it is believed to be unquestionable,
that for a considerable period of time, the exercise of the discipline had become,
in some places, increasingly relaxed and inefficient;
and in others it was maintained in a formal, legal, and lifeless manner;
equally unavailing to the preservation of the body,
"`without spot or wrinkle,`" as the church was designed to be,
or of the members as "`sons`" and daughters "`of God,
without rebuke,`" clean and blameless among men.
A relaxation of the wholesome obligations and restraints of the discipline,
long continued, must promote libertinism in the church,
and induce a corresponding increase of merely nominal members; while, on the other hand,
the mere legal and formal maintenance of disciplinary rules is
no less dangerously productive of lifelessness and hypocrisy.
In either class of members will be likely to accumulate,
ready for the influence of any plausible ism,
with which restless spirits may undertake to agitate the body.

To add to the dangers of this condition of the Society, it was exposed at that time,
in some degree, to its share of the pernicious influences afloat in the public mind,
arising from that reckless spirit of what was called "`free inquiry,`" but more
correctly was "`free unbelief`"--a presumptuous determination not to believe
what was not understood--which had insinuated itself among all classes of people,
both in Europe and America, since the outbreak of the French revolution.
For although very few if any members of the Society advocated
the open skepticism then so prevalent in many quarters,
yet the faith of many was more or less undermined
and unsettled by the tide of a loose public opinion,
and some of the deistical writings of Joseph Priestley,
if not also of that unscrupulous speculator Thomas Paine,
did undoubtedly find their way into some families in a hidden manner,
and worked as a poisonous leaven in the minds of the inexperienced and unwary,
who were taken with their boldness and novelty.

The journal of that honest and faithful servant of Christ,
Joseph Hoag (especially from chapter vii to chapter xi),
gives ample and unmistakable evidence that great
disorders had crept into many meetings in America,
about the period of which we are speaking;
so as to bring much reproach upon the precious truth of our profession.
Not only was there a sorrowful frequency of individual offences,
but it is very plainly manifest that a class had risen to such a pitch in some places,
as to form a party opposed to the faithful sustaining of the discipline,
or the testimony of Truth against offenders.
Among numerous instances to be found through his journal,
we may cite the following as nearest to the period of time under notice.
At one place, he says, in reference to them who ought to be the pillars of the church:^
footnote:[Journal of Joseph Hoag, Heston`'s edition, p. 59]
"`The consideration of this subject many times causes my heart to tremble,
when I look towards the gallery.
Oh, friends, were this class what they ought to be,
how would they hold up the standard of light and life to the people,
and the language of encouragement to the assemblies of the Lord!
Then would He bless his heritage and his standard-bearers with wisdom and sound judgment.
But, friends, it appears to me, there are among you those who have mounted Moses`' seat,
who sit in your galleries, whom the Lord has never placed there,
and whose conduct has been a reproach,`" etc.

Shortly afterwards, at another meeting, he says:
"`I found I had not been mistaken in regard to them... they were
the most reserved of any Friends in conduct that I ever saw;
strictly uniform in their dress--plain to a nicety.
Their select members were so particular,
that many of our little preachers hardly dare to peep out before them.
When I came to sit with them, I was almost amazed for one hour;
instead of finding all things in perfection,
I could think of little else than that when the sons of God met together,
Satan came also among them;`" and then opening to them this subject,
he went on to show them their condition,
as those "`who had been anointed with royal oil,`"
but "`had vilely fallen on the mountains of Gilboa.`"^
footnote:[Journal of Joseph Hoag, p. 64]
At another place he says: "`Though the business was conducted regularly,
the lack of concern to live up to our ancient and present principles was too obvious;
which caused deep exercises and painful labor; the aged buried in the earth;
the young on the wings of the wind,
embracing the customs of the world in their dress and address,`" etc.^
footnote:[Ibid, p. 100]

At another meeting, he remarks "`The last meeting I was at,
when all present were members, except one person.
The Lord showed me that the cause of the distress I felt in their meetings was,
that the heads of the people had drawn their swords
on their fellows who were better than themselves,
disordering the flock, and confusing the heritage of God;
and if there was not a stopping and a turning about, the Lord would arise,
and make bare His arm, and would turn and overturn till there should be a falling away,
and a cutting off to rise no more;
for the Lord would arise and support His dependent ones.
I had to deliver it in plain full terms; then felt my mind relieved,
and at liberty to depart.`"^
footnote:[Journal of Joseph Hoag, p. 150]
In reference to the painful condition of things in his own meeting, in the year 1800,^
footnote:[Ibid, p. 156]
he says: "`Those friends who opposed and complained of the discipline did,
in nearly every case, oppose calling to account any of our members,
for evil conduct of whatever description, even when brought to the Monthly Meeting.
The overseers were faithful and upright,
who with a few other Friends found it hard getting along.
Several honest-hearted Friends were drawn away to join and
sympathize with this libertine class to their hurt.
One who had a fine gift in the ministry, which was acceptable to his Friends,
was so wrought upon by their placid smoothness, sanctity of countenance,
and pitiful tales, affecting grief at home and abroad, that he sallied off with them:
his gift dwindled away, and he became a poor sleepy thing like the heath in the desert.`"

Nor was this weak condition confined to the Society in America.
A few years earlier, Sarah R. Grubb, of Clonmel, daughter of William Tuke, of York,
and a deeply experienced minister,
who travelled diligently in the ministry during the last quarter of the eighteenth century,
was often much cast down under a sense of the apathy and worldly-mindedness,
and consequent desolation,
appearing in many parts of the Society in Great Britain at that period.
In 1780, while visiting Lancashire, Yorkshire, and Cheshire,
she thus wrote on this sad subject: "`We are abundantly convinced,
that they who are sent out in this day,
to a people who have in a great measure forsaken the law and testimony, and,
what is still worse, see not their states, but are secure in themselves,
have not to eat much pleasant bread.
For I think I may say, it has often been our lot to go bowed down all the day long,
and to mourn in a deep sense of the great desolation which overspreads the Society;
insomuch, that we often admire that there should be any sent out to visit them,
and that the feet of those that are rightly shod,
should not more generally be turned to others;
for from these there are the greatest hopes, in this county (Cheshire), which is likely,
in many places, to be left desolate of Friends who keep their places.`"

In Scotland, she wrote still more strongly, after the Yearly Meeting at Edinburgh.
Speaking of some, for whom their minds were principally exercised, she says:
"`Through all, the sense of deep, hidden, as well as flagrant corruption,
so impressed my mind, that I was led to believe, truth will never prosper in this place,
nor the excellence of it appear unveiled,
till not only the branches of the corrupt tree are cut off, but the root so dug up,
that the remembrance thereof may rot.
And then there is reason to hope,`" etc.
And in the year 1786, while travelling through a great portion of England,
she wrote from the southwest thus:
"`In these western counties through which we have come, namely, Hampshire, Dorsetshire,
Somersetshire, and Devonshire, the Society,
as to the circulation of that life which we profess to be seeking the influence of,
is indeed lamentably low.
A worldly spirit, and a state that is neither hot nor cold, greatly prevails,
so that the few living members (for there is here and there
one) are scarcely able to lift the standard of truth,
or revive the remembrance of the law.`"

It is to be remembered,
that these descriptions are not from the pen of a superficial observer,
but from the openings of truth as manifested in the mind of a woman of uncommon qualifications,
both by nature and by divine grace, to form a just judgment of the state of the churches.
Mary Peisley, who afterwards married that eminent minister Samuel Neale,
is quoted by John Kendall, in his instructive collection of Letters of Friends,
as expressing herself in these words: "`God will divide in Jacob and scatter in Israel,
before that reformation is brought about which He designs.`"
Quotations might be indefinitely multiplied, from various writers of this period,
all concurring to evince the sorrowful truth, that a conformity to the world,
and great spiritual languor, had prevailed over many of the members of the Society,
and that a correspondent laxity in regard to the true maintenance of the
discipline was sapping the strength of the body in many places.
Job Otis, late of Scipio, in the State of New York,
and previously residing at New Bedford, Mass.,
who witnessed the devastating effects of this spirit,
and left a circumstantial manuscript history of the disturbances resulting from it,
in New Bedford, Lynn, and some other parts of New England,
from 1819 to 1825 (a work of more than six hundred closely written pages),
has judiciously traced the sorrowful circumstances occurring in the Society to certain
predisposing or preparing features which were apparent about the beginning of the century.
These features may be cited as follows,
condensed from his lucid and ample statement of them:

1st. Outward ease and prosperity, and worldly possessions and honors,
begetting pride and high-mindedness, and dwarfishness in religion,
with an increasing repugnance to the cross of Christ and its restraints.

2nd. Too great intimacy with the people of the world and enemies of the cross of Christ,
bringing in the spirit of the world and its attachments and associations.

3rd. A (so-called) liberality of sentiment, according to the world`'s estimate,
under pretense of Christian charity.

4th. Taking things on trust, and adopting the views of admired persons,
rather than seeking for the truth in the line of individual experience.

5th. Lack of a due engagement and exercise of mind to experience
preservation from day to day from the snares of the enemy,
and an advancement in the way of life and peace.

6th. Weakness in parents, in not properly restraining their children,
and bringing them up in subjection to the cross of Christ.

7th. Laxity in the administration of the discipline,
with false tenderness and a deceitful superficial healing of wounds,
till the whole body became diseased.

8th. A lack of real honesty and uprightness, and unreserved dedication of heart,
in many who ought to have been of clean hands for the Lord`'s work,
and submitted fully to the baptisms and sufferings necessary to qualify them for it.

9th. Self-exaltation and spiritual pride in some young ministers of promise, who,
through unwatchfulness were induced to plume themselves
with their gifts and supposed attainments,
and so soared above their level in the church, decked themselves with the Lord`'s jewels,
and lost their former humility and single dependence on His preserving and guiding hand.

10th. Thus they were led into a false estimate of
their abilities to do anything for the truth,
and becoming vain in their imaginations, their foolish hearts were darkened;
and they endeavored to comprehend the mysteries of Christ`'s
Kingdom in the will and understanding of man,
and gave a loose rein to that which feeds on knowledge,
and thus laid themselves open to dangerous notions and wild views.

Still another source of weakness had been for many years the baneful influence of slavery,
especially, but not exclusively, in the more southerly parts of the Society in America.
Job Scott, in travelling through Maryland and Virginia, in 1789,
wrote in the following terms respecting what came within his own observation:
"`Truth is at a very low ebb indeed among Friends; and various meetings,
formerly large and flourishing, exhibit scarce anything now but desolation.
When we are at meetings with Friends only, we suffer almost unto death;
and it then seems as if we could scarcely get along much further.
Negro slavery has almost ruined this country, both as to religion,
and the outward soil of the earth.
Friends`' children have been brought up in idleness.
From infancy, to settlement in families of their own,
they have spent much of their time in riding about for pleasure.
The consequence has been almost the extinction of the Society.`"^
footnote:[Journal and Works of Job Scott, vol.
Ii, p. 72; Comly`'s Edition.
See also vol.
I, p. 278]

I may be permitted to repeat here, as applicable to our present subject,
a remark made in another place.^
footnote:[Preface to the Journal of Joseph Hoag, D. Heston`'s Edition, p. v.]
"`Some may think that a veil should be drawn over
such a development for the credit of the Society;
but a due consideration of the subject will, it is thought, lead to the conclusion,
that the truth of history is precious,
that the cause of righteousness is promoted by honest Christian candor in the historian,
and that it is needful to vindicate the righteous
dealings of the Head of the church toward his people,
by a reference to the often-repeated warnings given
to the degenerate portions of His heritage.
It will thus also be seen,
that the enemy of truth did not succeed in planting his doctrinal errors,
until there was a departure in heart and in practice, from the true life of the Gospel;
so that gainsayers are deprived of their plea,
that our dependence on the '`Inspeaking Word of Divine
Grace`' is not sufficient to preserve from heresy,
without the aid of human learning and acquirements;
for that is shown to have been departed from by many,
before they were carried into doctrinal deviation.`"

In contemplating the foregoing delineation of the condition of the Society,
which I believe is by no means too darkly colored,
though there were doubtless many portions to which
the melancholy picture would not fully apply;
can we wonder that the arch enemy of all good,
who had in vain attempted to destroy it by sore persecutions from without,
in the times of its early zeal and strength,
now saw a fair opportunity for accomplishing the destruction
of the vitality of its testimony to pure Christianity,
by prompting the introduction one after another of successive
novelties and perversions of its precious principles,
by those professedly within its own borders?
The gates were left open, and he entered;
and wonderful was the devastation produced by schism after schism,
which followed during the next fifty years.

The following narrations,
first of the troubles in Ireland about the end of the last century,
and then of the kindred disturbances in New England some twenty-five years later,
although their perusal may appear like wading through a Dismal Swamp,
will not be found devoid of instruction,
and will in some degree further elucidate the weak and lax condition of the Society,
whereby it was laid open to the snares of the enemy,
and prepared for the great convulsion which soon ensued.
These disturbances were the forerunners,
or premature and premonitory outbreaks of the Hicksian convulsion,
as the Beacon schism was afterwards of the great devastation produced
by the prevalence of the doctrines of Joseph John Gurney and others.
