== Chapter II.

The Schism in Ireland, in Which Hannah Barnard Took a Conspicuous Part.

The grievous defection which sprang up in Ireland about the end of the eighteenth century,
and bore bitter fruit likewise among some in England and America,
was the first of a series of schisms which probably resulted
in great degree from the influences above spoken of.
Great unsettlement of principle showed itself in
various parts of the Society in that island,
about the year 1795,
assuming the plausible but hollow pretension of an aim for a higher state of reformation.
Many highly gifted ministers of the gospel from America,
were about that period led to visit Europe, including Samuel Emlen, George Dillwyn,
Job Scott, Richard Jordan, William Savery, Nicholas Wain, David Sands,
and Thomas Scattergood; several of whom were concerned to travel in Ireland.
It was soon made manifest to the understandings of these servants of Christ,
in the Divine instruction from time to time given them in relation to the condition
of the churches among which they travelled in the ministry of the gospel,
that a spirit was afloat in that island,
the tendency of which was to lead to a disbelief in some
of the fundamental points of our Christian faith;
and they were led into deep concern on this account,
and induced to labor faithfully as way opened, and as a qualification was witnessed,
for the safety and welfare of the flock, and the integrity of our holy profession.

Nicholas Wain, a minister from Philadelphia, while on his visit to Ireland in 1795,
attended the Province Meeting of Leinster, held at Mountmellick; where,
without any previous information,
he spoke of "`an intimation which had impressed his
mind with great exercise and painful concern;
showing that, however disguised and hidden,
there was a spirit at work that would divide and scatter,
and draw off many that were then in high stations,
into self-sufficiency and disbelief of the truths of the gospel.`"
This was such a surprise to some, that they were for passing a censure upon him;
but a few experienced minds fully united with him.
When William Savery came to the same place in 1798,
the same rending spirit was impressively felt and detected;
soon after which it showed itself more openly.^
footnote:[See Life of William Savery, in Friends`' Library, vol.
i, p. 437.]
But it does not appear that any clear and connected account
of this schism was preserved on the part of the Society;
so that in endeavoring to furnish such a statement,
we have no other resource than what can be collected together from scattered notices,
to be found in various journals or other writings of Friends,
compared with the statements of an elaborate but partial narrative of the events,
published soon afterwards by a partisan residing in Liverpool;
who appears to have had access to official documents, or copies of them;
but whose work has sunk into obscurity, and is now seldom to be met with.

About the year 1796, the National Half-Year`'s Meeting of Ireland,
which for two or three years had committees under appointment to
visit and endeavor to strengthen two of its Quarterly Meetings,
where the above-mentioned unsettlement particularly showed itself,
was brought under a renewed weighty consideration of the weakness
reported by these committees as being prevalent in the branches,
and appointed a joint-committee of men and women Friends,
to consider what further measures it might be best to take for the help of the body.
In this committee, the holding of joint-meetings for discipline,
composed of men and women unitedly, was proposed, and favorably looked upon by some,
as likely to be productive of greater strength;
but this being considered by others as rather a novel arrangement,
which had as yet only taken place in some very small meetings, it was not acceded to;^
footnote:[By Beck and Ball`'s account of the early London Meetings,
it appears that about the rise of the Society many meetings for discipline were so held.
See pp.
91, 92, 354.]
and all that appears to have resulted from the deliberations of the committee,
in the way of recommendation, was the suggestion,
"`that a more frequent interchange of visits between men`'s and women`'s meetings,
as Friends may find their minds influenced,
would be of advantage in the conducting of the discipline;`" with an encouragement
also to a more frequent visiting of other Monthly Meetings,
according to the pointings of duty.

The weakness and inadequacy of these suggestions seems to
indicate that the life of truth in the body was too low
to admit of any vigorous measures being pursued for a reformation.
Indeed the very language of a minute of the Half-Year`'s Meeting,
in appointing one of these committees, in 1794,
seems clearly to intimate a very low and unhealthy
condition even in that collective body itself;
and its condition had since certainly not been improving, but the contrary.
That minute required the committee "`to confer together,`" and "`report if any expedient
may occur to them as an attempt to remedy the many deficiencies obvious among us.`"
It seems difficult to believe that this was really the language
of a meeting of Friends--that the successors of Fox,
Penn, and Barclay, in their Half-yearly Convocation for Ireland,
should be blindly groping thus about after some "`expedient,`"
whereby to bring spiritual life again into the body!
Such an expression shows their aim to have been low indeed;
and all such "`attempts to remedy`" the evils pressing upon them might well prove abortive.
There seems to be no reason to doubt that members
occupying influential positions in that body,
but who had imbibed the spirit of the defection,
were cramping its energies and benumbing its right
sense of the state of things among them.

Indeed,
the disunity and disaffection had by this time so
extensively shown itself in various places,
under a high assumption of greater enlightenment,
and bold pretensions of a purer standard than the Society had yet attained--but
unhappily with the proofs from life and conduct that this was only a hollow pretense,
covering up the rapid advance of unbelief in some of the most important doctrines of
the Christian religion--that the body of the Society was for a time almost paralyzed,
and no united effort was practicable,
in the way of a general and living concern and zeal,
under which the National Meeting might have moved
in the authority and efficiency of the Truth.
Between unbelief, on the one hand, and flat formality on the other,
the life and efficiency of the body seemed almost gone.
Yet the Lord was not unmindful of his flock,
but from time to time vouchsafed support and strength to his humble dependent children,
who singly trusted in him,
and preserved a living remnant of these from being taken by the snares of the enemy.

The next year, 1797, the schism became painfully and openly manifest.
In the Select Monthly Meeting of Carlow, the clerk, Abraham Shackleton, an elder,
and son of that worthy elder, Richard Shackleton, of Ballitore, then deceased,
openly objected to the long-established practice of reading the
Advices attached to the Queries for Meetings of Ministers and Elders,
under the plea that it was "`limiting the operations of the Spirit,
and teaching for doctrines the commandments of men.`"^
footnote:[Rathbone`'s Narrative of Events in Ireland,
an unsound and partisan publication,
but considered to be correct in regard to documentary facts and quotations,
so far as it gives them.]
This was, in short,
the commencement of an open attack on the system of discipline itself;
and in venturing upon it,
Abraham Shackleton knew well that he represented the views of a numerous body,
both in and out of the Select Meetings,
of such as were disposed to support him in an attempt to discard
some of the long-cherished testimonies and usages of the Society.

This circumstance was almost immediately followed by similar objections
being made in the Select Monthly Meetings of Moate and Mountmellick.
All these belonged to the Quarterly or Province Meeting of Leinster;
and information of what had thus occurred was given
in the ensuing Select Quarterly Meeting.
But it does not appear that any step was taken by
that meeting to check the progress of the defection.
In the Quarterly Meeting for Discipline,
when the Answers to the Queries from the several Monthly Meetings were under consideration,
it was found that in the Answer from Carlow, respecting the Holy Scriptures,
the word "`holy`" had been omitted.
On inquiry as to the reason of this unusual departure from the expression of the Query,
a long reply was made,
objecting to the epithet of "`holy,`" as belonging to the Scriptures,
and alleging that "`many parts of the Scriptures are truly excellent and instructive;
but that there are other parts which cannot with propriety be regarded
as either authentic or instructive to the general class of readers;
that there are some passages, which it would be extremely difficult, if not impossible,
to reconcile or render consistent with each other;`" that
the character of the Almighty is in various parts misrepresented,
and "`attempted to be portrayed by injurious and degrading representations!`"

And when this was denied,
and the uniform belief of the Society in their divine harmony and excellency maintained,
and the epithet "`holy,`" as constantly applied to them by our worthy ancestors,
was clearly vindicated, the response was made,
that "`the setting up the opinions or conduct of our ancestors as limits,`" "`was
inconsistent with the liberty which belonged to the gospel;`" and that,
if Scripture were to be denominated "`holy,`" all other writings
proceeding from the same Spirit were entitled to the same appellation;
so that it must be considered either as having no appropriate meaning,
or merely a superstitious one.
These were bold assertions in the open meeting.
But it does not appear that any decided action was taken at that time.
Probably the sound members were astounded at the very boldness of the tone assumed,
and scarcely knew at once what course to take.

William Savery, one of the American ministers, travelling at that time in Ireland,
had an opportunity of conversing with Abraham Shackleton, at Waterford,
in the first month of 1798.
In his Journal he thus mentions the interview: "`At my lodgings, in the evening,
came Robert Greer and Abraham Shackleton; the latter from Ballitore,
who had come forty-two miles in order to see me.
He holds opinions of a singular nature; objects to the five books of Moses in particular,
but in general to the accounts of the Jews in the Old Testament,
and various parts of the New Testament;
professes to think there is little if any need of books of any kind on religious subjects;
that they only darken the mind, and keep it from turning itself wholly unto God,
the fountain of all light and life.
But of all books of a religious kind, he especially dislikes Friends`' Journals,
and has but a slight opinion of ministry and discipline,
and all secondary helps in general;
but is for having all people turned to the Divine Light in themselves alone.
Christ, he says,
was a good man--the leader of the people--because he was wholly obedient to this light,
which he was in an especial manner filled with.

He thinks the Evangelists are poor historians;
that Paul brought much of his epistles from the feet of Gamaliel,
and many parts of them are therefore rabbinical stuff;
that Christianity was the same to those who were obedient to the anointing,
before the coming of Christ in the flesh as since, etc.
I perceived all this was accompanied with a pretended looking towards a greater
state of perfection and redemption than our Society has yet arrived at.
For my part, I could not see as he did,
nor unite with him in his erroneous expressions and opinions;
and I feel a fear that they will produce much hurt,
if he and others in this nation are not brought into deep abasement;
his talents and morality making error in his hands more dangerous.`"
The next day, after the midweek meeting, he says:
"`Went with Abraham Shackleton to a Friend`'s house,
and opened to him more of my disapprobation than I had before.`"
^
footnote:[Friends`' Library, vol.
i, p. 440.]

The National Half-Year`'s Meeting, in 1797, had concluded to drop one of its sessions,
and from then on to hold but one meeting during the year; and accordingly it met,
the next year, in the city of Dublin, in the fourth month, 1798,
as the Yearly Meeting for Ireland; still, however,
acknowledging some degree of subordination to the Yearly Meeting of London,
by sending representatives, and Answers to the Queries.
Now came the more open outbreak of a party which had for
several years been more or less covertly sapping the vitality
and paralyzing the energies of the Society in that island.
It manifested itself in many places by undisguised declarations of unbelief
in the authenticity and divine authority of the Holy Scriptures,
and even a denial of the truthfulness of many parts of Scripture history;
a discarding of the doctrine of the atonement by our Lord and Saviour Jesus Christ;
a general spirit of speculation and unbelief;
a vaunting tone of self-importance in the assumption
of divine guidance as reformers of the Society,
without adequate marks of self-reform in their own life and conduct; and,
at the same time,
persistent attempts to do away with the comely order
of the discipline long established among Friends.

Abraham Shackleton, in a written communication to one of his fellow elders,
declared his disbelief that the Almighty ever countenanced
various things mentioned in the Books of Moses,
Joshua, Samuel, and others;
charging the original writers with "`muddying the fountain,`" and with "`pretending
to a divine revelation,`" alleged that the Scriptures contain a "`mass of impurity,`"
and "`resemble the cloud which conceals the sun from our eyes;`" and accused the Apostle
Paul of "`carrying much of his Rabbinical veneration for Jewish monuments of tradition,
into Christianity with him.`"
One Samuel Stephens openly and in writing denied the divinity of Christ,
looking on Him as a mere man, and saying, "`I cannot swallow down the absurd doctrine,
that He was God!`"
John Hancock, a minister of Lisburn, published a pamphlet, in which,
among other erroneous sentiments, and some plausible insinuations,
he denied a belief of the fall of Adam having had any effect upon himself,
and put forth his belief that Christ was merely a man,
but with the Spirit of God poured forth upon Him without measure.
Afterwards, in another pamphlet, he attacked the character of the Apostles,
and spoke of the Scriptures as being the origin of a large mass of errors,
by men taking them as unmixed truth.^
footnote:[Yet S. M. Janney (though admitting that
he held some particular doctrinal views,
without saying what they were) says that "`he appears
to have been an exemplary and conscientious man.`"
Janney`'s History of Friends, vol.
iv, p. 28.]

A very considerable number of the ministers and elders
had become infected with this spirit;
and, as a consequence of this, a still larger number of the general members,
both young and old.
It is impossible at the present time,
to know how much private labor may have been bestowed by faithful and
deeply concerned individuals for the restoration of the lapsed parties.
Doubtless this was very considerable; but it would seem that, for a time,
the preponderance of the unsound element, or at least its clamorous opposition,
rendered it impracticable, in several of the meetings, to make a firm, open,
and prompt stand, as a body, against the fearful defection.
The Yearly Meeting, however,
succeeded in 1798 in sending down advice to the subordinate meetings,
that those who manifested opinions contrary to the general sense of the body,
should be labored with to reclaim them; and if persisting in their errors,
after due labor and patience, they should be testified against.
And a committee was also appointed to visit the subordinate meetings.

David Sands, from the Yearly Meeting of New York,
was travelling in Ireland about this time in the service of the gospel;
and being very clear in his appreciation of these disorders,
and unflinchingly faithful in his public testimonies against them,
and the wild spirit of unbelief which was producing them,
he became a particular mark for the arrows of the disaffected.
They accused him of pretending to know their states by revelation,
and many would not openly unite with his offerings
in supplication by standing with heads uncovered.
One John Bewley went so far in his animosity against this highly gifted minister,
as to make an attack upon him in a scurrilous paper addressed to the Select Yearly Meeting;
mentioning him by name, and exclaiming, "`Search him, you elders, sift him,
bring him to the touch!
If too much alloy debases his composition,
do not by your certificate pass it further upon the public as sterling!`"
Of course the meeting declined to read such a paper.
Hannah Barnard, another minister from the Yearly Meeting of New York,
but of a very different spirit from David Sands, was also,
during part of this year and the two following, travelling in Ireland;
having through the weakness and false tenderness of her friends at home been at length,
after considerable reluctance and delay,
liberated by the Monthly Meeting of Hudson for a religious visit to Europe.
Soon developing sorrowful unsoundness of principle, she did much mischief in Ireland,
greatly encouraging the spirit of unbelief and disorder by her public declarations.

Hannah Jenkins was born about the year 1754,
of parents who were members of the Baptist Society;
but she joined Friends about the eighteenth year of her age,
and afterwards married Peter Barnard, of Hudson, in the State of New York.
Whether she had,
during the twenty years of her ministry before she left America for Europe,
manifested any of that unsoundness of doctrine, which, after that,
became so sorrowfully conspicuous, is not now clearly known.
If she had done so,
the members of her own Monthly Meeting must either
have participated to some extent in the same views,
or must have had very little capacity for judging what was, or what was not,
pure Christian doctrine; for in their Certificate liberating her for service in Europe,
they declared "`that her ministry is sound and edifying.`"
This Certificate was also sanctioned by the endorsement of her
concern on the part of the Quarterly Meeting of Nine Partners,
and by the Yearly Meeting of Ministers and Elders of New York.^
footnote:[By the following passage from the Journal of Henry Hull,
it would appear that she was in good and general esteem
for some years after coming forth in the ministry.
It seems probable that unwatchfulness gradually increased upon her,
and that in this condition going among the dissentients in Ireland,
she rapidly imbibed their views, and made them her own.
Henry Hull says that he travelled in 1793,
to some places in Connecticut in company with her; and adds:
"`She had passed through much exercise of mind to prepare her for the work of the ministry,
and evinced much love and zeal for the cause of religion.
She travelled some long journeys in the work of the gospel.
But after all her dedication to the Lord`'s cause,
she fell away and caused Friends much trouble,
imbibing and promulgating principles inconsistent
with what she had once so zealously propagated.
Several years before she fell away, I had fears on her account,
having frequently been in her company,
and had opportunity of seeing the temptation to which she was exposed.
Let him that thinks he stands, take heed lest he fall!`"
The Friend, Philadelphia, vol.
34, p. 89.]

She had, as companion, Elizabeth Coggeshall, a worthy minister from Rhode Island;
but it does not appear that there was any participation on her part,
in the unsound views of Hannah Barnard.
It seems not unlikely, that the latter, being of a bold and speculative nature,
through great unwatchfulness was caught by the spirit of infidelity then afloat in Ireland,
under the plausible pretense of reformation, and being at once taken by the hand,
caressed and flattered, by the disaffected there, that she gave herself away to them,
adopted their sentiments,
and so more fully developed any latent unsoundness that
may have been secretly insinuating itself into her mind,
before leaving her home.
She landed at Falmouth in the seventh month, 1798, and soon proceeded to Ireland,
where she greatly increased the trials by which the faithful members were almost overwhelmed.
Many had by this time become fully awake to the state of the Society,
and some were prepared to stand faithfully for the
maintenance of sound principles and practice.

We have seen that the Yearly Meeting of 1798 issued advice for the encouragement
of the members and meetings to put the discipline in practice against the schism.
After that Yearly Meeting, accordingly, Friends felt somewhat more animated to proceed;
and a large number of the most disorderly members were dealt
with by their Monthly Meetings and eventually disowned,
including many in the station of elders or overseers, and several acknowledged ministers.
The honest-hearted, having now to stem the tide of open schism,
were brought into many trials,
and had to wade through great difficulties for two or three years,
in their conscientious endeavors to sustain the testimonies and discipline of the Society.
In some meetings this could scarcely be accomplished.
The weakness in the body at large was great and obvious,
especially as so many of those who ought to have stood forward in defence of the truth,
in their positions as ministers, elders, or overseers of the flock,
had joined more or less in the defection.
Without taking this particular circumstance into view,
it would be difficult to account for the fact that the Select Yearly Meeting of Dublin,
in 1800, preparatory to Hannah Barnard`'s passing over to England,
was induced by some means to issue a clear returning minute on her behalf,
certifying that they believed "`it was her concern, by example and precept,
to inculcate the doctrines of the gospel,`" during her religious labors among them,
and that "`she had meetings with those of other Societies in several parts,`" they believed,
"`to general satisfaction.`"

Surely the meeting must have been borne down at this
time by the pressure of the spirit of opposition,
so that a true judgment could not be arrived at, but evil was called good.
Although many had been disowned, or had left the meetings of the Society,
yet it seems that enough had assembled on that occasion,
of the sympathizers with the schism, to control the Select Yearly Meeting,
at least so far as to turn judgment backward,
and prevent its right action against this popular preacher.
It is evident that many of the meetings for discipline,
and meetings of ministers and elders,
had become much crippled by the large proportion of dissentients.
In Ulster Province it seemed almost impracticable, for a time,
to sustain the discipline at all.
In that Quarterly Meeting, all the elders were eventually released from their station;
and in Leinster Quarter, all the elders of one of the Select Monthly Meetings.
We may imagine from this what devastation was the result among the members at large.

Abraham Shackleton, whose influence was very considerable as an elder,
and on account of the great veneration still felt for the memory of his father and grandfather,
was probably one engaged with others in turning aside
the judgment of the Select Yearly Meeting,
on that occasion, in the case of Hannah Barnard.
He appears to have had full swing for carrying on
his schismatic efforts until the year 1801,
when he was at length taken under dealing by the Monthly Meeting of Carlow,
of which he was a member.
He now addressed a paper to that Monthly Meeting, couched in grievously bitter language,
in which he manifested very erroneous and dangerous sentiments;
declaring his disunity with the Discipline,
and his belief that "`a distinct Society ought not to exist,`"
nor "`any book having particular dogmas of belief,
by which that Society is to be distinguished;`" and charging what he called
"`your Bibles`" with containing "`absurdities,`" which were "`sufficient
indication to any unprejudiced mind for their annihilation;
that religion may flow as freely as the light of day, from man to man,
from heaven to earth!`"
This letter was (it is hardly needful to say) deemed
unfit to be read in the Monthly Meeting,
and he was disowned from membership.

After many deeply trying circumstances, report was at length made,
at the Yearly Meeting in 1802,
by the committee previously appointed to aid Friends in supporting the discipline,
that visits had been paid by them to most of the meetings for discipline,
and many of the particular meetings for worship,
and that they had often been made sensible of the affecting
state of the Society under various causes for discouragement;
but were apprehensive nevertheless that "`several
well-disposed Friends give way too much thereto,
and instead of making use of the ability afforded,
seem too prone to sink under the present gloom.`"
It was, however, reported to the meeting at this time, especially from Ulster Province,
that the discipline had in a good degree been carried into effect,
so as to reach most of the cases of disorder.
The editor of the Journal of William Savery (the
late Jonathan Evans of Philadelphia) says,
respecting the parties engaged in this schism,
when alluding to some of William Savery`'s exercising labors while travelling among them,
that "`a great withering and falling away overtook nearly all of them,
and upon some of the principal promulgators of those unrighteous
doctrines an awful blast was evidently brought.`"
Many of these poor deluded people eventually lost ground greatly in their outward circumstances,
and even in their moral character,
some even so far as to excite the surprise and pity of their acquaintances.
Yet others, by taking timely warning,
and cooperating with the reproofs and instructions of divine mercy,
were enabled to retrace their steps to favor with the Most High,
and to a reunion with the faithful in Israel.

As to Hannah Barnard, she went over to England,
and attended the Yearly Meeting in London in 1800.
Here Elizabeth Coggeshall,
probably having become uneasy with her position as companion to
one who had proved herself not sound in the Christian faith,
proposed to part from her, and was liberated to travel on the continent of Europe.
Hannah Barnard hereupon proposed to accompany her;
but this was objected to in the Yearly Meeting of Ministers and Elders;
David Sands and Joseph Williams (an elder from Ireland) taking that occasion
to make known to Friends the deep exercise and trial which her unsound
sentiments had produced to faithful Friends in Ireland.
This brought the matter to a point that could not be evaded.
A committee was appointed in the Select Yearly Meeting
to confer with her on the subject of these complaints;
on whose report, as they found it impossible to clear her from the charge,
the case was referred to the "`Morning Meeting of Ministers and Elders.`"
This meeting found her expressed sentiments on various points of doctrine so objectionable,
that they advised her to forbear from any further exercising the function of a minister,
and to return as speedily as practicable to her home.
She declined to be governed by this advice,
on the ground that the "`Morning Meeting`" was not possessed of disciplinary powers.^
footnote:[See Beck and Ball`'s Account of London Friends`' Meetings, page 82. London,
1869.]
That meeting, therefore, transferred the case to the meeting in London,
within which she had been making her home,
by reporting her delinquency to the Monthly Meeting of Devonshire-house.
Here a committee was appointed,
and several opportunities were had with her on the subject, which, as before,
resulted in her being advised to refrain from travelling or appearing further as a minister,
and to return home.

She appealed against this advice, to the Quarterly Meeting of London and Middlesex.
Here she was patiently and fully heard,
in pleading her own cause with considerable ability.
Her declaration of faith or belief, delivered in the prosecution of her appeal,
was of a remarkably wary, vague, and delusive character,
covering up her true sentiments as she had often openly expressed them,
but not at all clearing herself from them as now expressly charged against her.
From the tenor of this document it is evident, cover it up as she would,
that she did not believe in the atoning sacrifice of Christ, or in the fall of man,
according to the belief of Friends.
And in regard to other doctrines,
on which she was accused of unsoundness in her ministry, it was her duty now,
as professing to hold so responsible a position in the church, to clear herself,
if possible, from the imputation; but this she signally failed to do,
and indeed does not appear to have even attempted.

The Quarterly Meeting confirmed the judgment of Devonshire-house Monthly Meeting;
and Hannah Barnard then appealed to London Yearly Meeting of 1801.
The Quarterly Meeting`'s Committee of Respondents, appointed to appear on its behalf,
was composed of six members of eminent ability, namely, William Forster, William Dillwyn,
Joseph G. Bevan, Frederick Smith, Sparks Moline, and Richard Phillips.
The committee appointed by the Yearly Meeting out of the different Quarters,
to hear the appeal, and report their judgment, went carefully into the subject,
as one of great importance both to the church and the individual implicated;
and finally reported to the Yearly Meeting, that "`it appears to us,
that the said Hannah Barnard does not unite with
our Society in its belief of the Holy Scriptures,
the truth of which, in several important instances, she does not acknowledge;
particularly those parts of the Old Testament which assert that
the Almighty commanded the Israelites to make war upon other nations;
and various parts of the New Testament, relating to miracles,
and the miraculous conception of Christ;`" and that they were, therefore,
unanimously of the judgment that the proceedings of the Monthly Meeting should be confirmed.

I have in my possession a letter of this date from my father,
who was attending the Yearly Meeting, to Thomas Scattergood,
under whose powerful ministry in some remarkable meetings
at Sheffield he had been convinced of the truth,
and induced to join in membership with Friends.
By this letter, which contains a circumstantial account of what passed,
it appears that on the 1st of sixth month the report of the Committee
on Hannah Barnard`'s Appeal was produced to the Yearly Meeting,
and read in her presence; that she objected to it, and, at considerable length,
urged to be heard before the Yearly Meeting at large; that this was,
with remarkable cogency, objected to, and shown to be improper and inadmissible,
by Joseph G. Bevan, on the part of the respondents of the Quarterly Meeting;
that the meeting sustained these views,
and informed her that she could not be allowed to reopen her case there,
after it had been fully and fairly heard in the committee;^
footnote:[The minute of the Yearly Meeting (as found in L. Howard`'s Yorkshireman, vol. v, p. 25)
says that "`the appellant having expressed dissatisfaction with the said report,
this meeting proceeded to read the Appeal,
and to hear what further the said Hannah Barnard was disposed to offer,
and also to hear the respondents thereon.
The appellant and respondents then withdrawing,
this meeting proceeded in further deliberation on the case, and is of the solid judgment,
that the said report ought to be confirmed;
and this meeting does hereby accordingly confirm the same.`"
The hearing of the appellant in the Yearly Meeting does not appear
to have been by any means a reopening of the case at large,
but merely a hearing what she had to say, why the report should not be confirmed.]
but the Yearly Meeting also decided, that in coming to a conclusion in this case,
it would be best for not only the members of the
Monthly and Quarterly Meetings appealed against,
but also for all ministers and elders, to abstain from giving a judgment.

This was probably on account of the case having been previously considered
and acted upon by the Select Yearly Meeting of the year previous,
and by the Morning Meeting of Ministers and Elders,
who might therefore be considered as having to some extent already adjudged the case,
and decided against her.
It was thus left to the judgment of the generality
of the members from the meetings in the country;
and my father`'s letter declares that it was soon decided,
without any opposing expression, to accept the judgment of the committee,
confirming the action of the Quarterly and Monthly Meetings.
Hannah Barnard was consequently, by the Yearly Meeting itself,
admonished to return to her own home.
Finding her way now shut up in Europe, she at length prepared to return to America.
The Meeting for Sufferings, by a committee appointed for the purpose,
offered to supply the expense of her voyage homewards;
but she refused to accept the offer;
and sailing from England near the end of the eighth month,
she reached her home early in the eleventh month, after a passage of sixty-three days.

London Yearly Meeting had directed that ample information of her unsoundness of principle,
and of the consequent proceedings had, in her case,
should be transmitted by Devonshire-house Monthly
Meeting without delay to the Monthly Meeting of Hudson,
where she belonged; and, owing to the delay in her departure,
and her subsequent very long voyage,
the documents containing this information had preceded her arrival at home,
and had indeed been read in the Monthly Meeting.
She attended the next Monthly Meeting after her arrival,
and attempted to vindicate herself;
but a committee was appointed to attend to the case as usual.
This committee is said to have had no less than six conferences with her,
to endeavor to reclaim her, previous to the Monthly Meeting in the first month, 1802,
when she was, by conclusion of the meeting,
displaced from her station as an acknowledged minister.

From this conclusion she appealed to the Quarterly Meeting,
which met at Stanford on the 13th of the second month;
and there she attempted to defend herself by the altogether unfounded allegation,
of views similar to her own having been expressed by some of our early Friends.
Her defence, however, abundantly confirmed the charges of unsound sentiments,
and the next Quarterly Meeting (in the fifth month)
confirmed the judgment of the Monthly Meeting.
Meantime, the Monthly Meeting,
without waiting for the decision of the Quarter on
her appeal from their displacement of her as a minister,
and finding that she still persisted in her errors,
had taken up the case with reference to her membership in the Society,
and appointed a committee to visit her as a transgressor;
and on the report of this committee, in the fourth month,
a testimony of disownment was issued against her.
In this they declared, that:

She has not only imbibed those erroneous and dangerous sentiments,
but is assiduous in disseminating them among others;
hence it evidently appears that she is not one with us, in principle nor in practice,
and she still continuing to promote the ideas she had formed,
and strenuously defend the ground she had taken,
and there appearing no prospect of advantage from further forbearance or labor; we,
therefore, for the support, etc. by bearing our testimony against a spirit of infidelity,
which appears evidently to have gained too great an ascendency in the present day,
hereby testify that we can no longer hold religious
fellowship with the said Hannah Barnard,
but disown her from being any longer a member of our Society, until, etc.

Signed by

Tiddeman Hull,

Hannah Jenkins,

Clerks.

Thus, the Monthly Meeting vindicated itself, as a body, from any complicity in her errors.
Hannah Barnard is said to have survived her separation
from Friends about twenty-six years;^
footnote:[Luke Howard`'s Yorkshireman, vol.
v, page 77.]
dying, in comparative obscurity, in the year 1828,
without ever having been reunited to the Society.

The Society in Ireland had become much diminished and weakened by this sorrowful schism;
and in England a few individuals became partisans of Hannah Barnard,
and advocated similar views to some extent.
William Eathbone, of Liverpool, published, in 1804, a Narrative of Events in Ireland,
etc., already alluded to,
giving his version of these sad occurrences in such a manner as
to show plainly that he was not himself one in faith with Friends.
He had, indeed,
been honestly and plainly labored with on these subjects by Job Scott while in Ireland,
in a letter dated eighth month, 31st, 1793, though with great apparent lack of candor,
his book insinuates as if he thought Job Scott was one with him in principle.
This appearing after Job Scott`'s decease,
ought to have been clearly contradicted by Friends,
as it was calculated to produce an erroneous impression respecting the
soundness of doctrine of that deeply experienced minister of the gospel.

There were not lacking some unsettled minds in and about London also,
to fan the flames of this spirit, and encourage Hannah Barnard`'s apostasy,
though these were but few.
The chief among them were G. H., a respectable lawyer of London,
who I think never left the Society, and Thomas Foster, of Bromley, a suburb of that city,
a man of considerable ability for disputation; who, a few years after,
openly favoring Unitarian sentiments,
and aiding the circulation of some of the books of that Society,
and likewise publishing attacks on the course of London Yearly Meeting
in such a way as to show that he was not united with Friends`' principles,
was disowned by Ratcliffe Monthly Meeting in London, of which he was a member.
He contended the matter before the Monthly Meeting for a long time,
with uncommon tenacity and litigiousness,
and then appealed to the Quarterly Meeting of London and Middlesex.

Here, notwithstanding his strenuous efforts,
the judgment of the Monthly Meeting was confirmed by the Quarter in the eleventh month,
1812.
Upon this he resorted to the press,
publishing his own version of the successive proceedings of the meetings,
and even detailing his own factious attempts to stumble the weak members of committees,
and giving in full (or professedly so) the various remarks made in the course
of the debates ensuing whenever the matter came up before the Monthly Meeting,
for a period of many months,
during which he had succeeded in baffling the exercise of the discipline.
But his octavo volume, now seldom heard of,
mainly evinced that the author had paraded himself before
the public as a troublesome mischief-making man,
and a very unsound member of the Society,
and had plainly shown that it would have been much better for the meeting,
if it could have cleared itself more promptly from the reproach of his inconsistencies,
by disowning him long before it did.

He now appealed to the Yearly Meeting; where, as usual in such cases,
a committee was appointed from all the Quarters except the one appealed against,
to hear the appellant and respondents,
and give their judgment thereon for the information and action of the Yearly Meeting.
This committee (of twenty-seven Friends) after a full investigation of the case,
reported their unanimous judgment, that the disownment ought to be confirmed.
The appellant, however, was not yet satisfied to give up the contention,
in which he seemed to take a particular satisfaction;
and as it was an appeal connected with faith and doctrine,
he claimed the right of being heard again, before the Yearly Meeting at large.^
footnote:[It appears probable,
from comparing the action of the Yearly Meeting in this case,
with its denial of the same demand made by Hannah Barnard, in 1801,
that the present regulation of the English Discipline,
to allow appeals on questions of faith and doctrine to be heard in the meeting at large,
instead of before a committee, must have been adopted in the interim.
L+++.+++ Howard, (Yorkshireman, vol.
v, p 134),
says it "`was the practice in 1802;`" but the later Books of Extracts or books of Discipline,
give no indication when the rule was established;
and there is no allusion to such a practice in the Book of Extracts of the Second Edition,
printed in 1802.]
It was a very trying occasion, he being a fluent man, and well calculated,
by his sophistical speeches, to catch and bewilder the inexperienced and unwatchful.
But there was no help for it,
and the whole case was opened at large in that great and mixed assembly of old and young,
experienced and flippant,
and the cause of Latitudinarianism (for it amounted to that in
fact--the Unitarian views being somewhat artfully covered up),
sustained by him in a long and insinuating speech, in his own defence.
This had, of course,
to be met on the part of the Monthly and Quarterly
Meetings by a considerable body of evidence,
to show the correct grounds of their procedure,
and to prove the uniform faith of the Society of Friends
in the divinity and atonement of our Lord Jesus Christ,
and the entire incongruity and inconsistency thereof with the views of the Unitarians,
whose publications Foster had for years actively promoted.

This statement of the respondents of the Quarterly Meeting
was read by Josiah Forster (probably written by him),
and contained the following instructive remarks towards the close:

The appellant has repeatedly alleged that he never denied the eternal divinity
of that power which dwelt in and acted by or through the Man Christ Jesus.
But in this we can discover no acknowledgment of the divinity of our Lord which would
imply that He differs (except in the degree or measure of the power conferred),
from eminently gifted servants, from the Prophets, and the Apostles.
How remote from this is the manner in which our ancient Friends,
the instruments under Providence in gathering and establishing our Society,
understood those passages in Scripture,
which speak of Christ as the Word which was in the beginning with God,
and was God--which make mention of the glory that
He had with the Father before the world was;
of the creation by Him of all things that are in heaven and that are in earth,
visible and invisible--which affirm that all things were created by Him and for Him,
that He is before all things,
and that by Him all things consist--which speak of His coming down from heaven;
of His being in the form of God, thinking it not robbery to be equal with God,
yet making Himself of no reputation,
and taking on Him the form of a servant--which designate Him as the Son,
whom God has appointed heir of all things, by whom also he made the worlds;
who being the brightness of His glory,
and the express image of His person (or substance), and upholding all things by the word,
of His power, when He had by Himself purged our sins,
sat down on the right hand of the Majesty on high; as the Lamb that was slain, to whom,
jointly with Him that sits on the throne, is ascribed blessing and honor,
and glory and power, forever and ever!

We might well say,
how different is this development of the divine character of our Lord Jesus Christ,
taken as it is from Holy Scripture, from the cold and evasive allusions to Him,
and even the glaring denials of His oneness with the Father,
often made by the appellant in common with the Unitarians, with the Barnardites,
the New England "`New Lights,`" and the disciples of Elias.

The Yearly Meeting had been occupied with the case on four successive days,
and on the 26th of the fifth month the appellant,
apparently expecting an adverse judgment,
requested that he might be furnished with "`an explanation
of the grounds of the committee`'s decision.`"
To this, however, the meeting replied,
that they did not think it necessary to call upon the committee
for any explanation of "`the grounds`" of their decision,
nor did it "`rest with either the appellant or respondents
to call for such explanation at any time.`"
Luke Howard`'s account of the transaction^
footnote:[Yorkshireman, vol.
v, p. 146.]
says that he attempted to sustain his views by quotations from the Scriptures; "`though,
as was justly urged by the respondents, the question was,
not whether he could prove his opinions by texts of Scripture;
but whether they were in accordance, or at variance,
with the acknowledged doctrine of the Society.`"

After both parties had been fully heard they withdrew,
leaving the meeting to come to its decision.
A solemn silence ensued for a considerable time,
under a prevailing sense of the weightiness of the subject,
as connected with the integrity of the church,
and the necessity of sustaining its testimony for the truth and against error.
At length, William Grover, a venerable and worthy elder, from Essex,
first broke this deep silence in a very few but impressive words, to the effect,
that he was of the mind that the judgment of the Monthly Meeting ought to be confirmed.
A general and uncommonly full expression now took place over the whole meeting,
extending from the older Friends to the middle-aged,
and even including the younger members; and it was remarkable that,
in that large assembly of probably more than one thousand Friends,
a unanimous voice was given (so far as anything at all was
expressed) for the confirmation of Thomas Foster`'s disownment,
and the clearing of the Society from the reproach of his unsound principles.

It appears by a letter from John Bevans, of London, to his friend Thomas Scattergood,
after his return home to Philadelphia, dated second month 1st, 1805,^
footnote:[Journal of Thomas Scattergood, stereotype edit+++.+++, p. 457.]
that Thomas Foster had been far otherwise than alone, in that city and its neighborhood,
in disaffection and a disposition to bring in unsound doctrines.
This letter says:

Trying times have been the portion of many brethren
on this side the water since you left us.
Yourself and others have had your perils by land and perils by water;
but ours have been by false brethren, who,
by fair speeches and great pretensions to liberality,
have deceived and misled some in many places.
But I hope the firmness of Friends, pretty generally on this side the water and on yours,
will in good measure put a stop to this delusive spirit Perhaps you may
know that some of the disaffected among us have been very active,
and have published several pieces,
greatly misrepresenting the conduct of Society in the case of H. B.; and also,
by mutilating the writings of our ancient Friends,
have made them to speak a language they neither intended nor thought of.
They have likewise endeavored to invalidate several parts
of the Scriptures of the Old and New Testaments.

The above publications have much tendency to turn
the feet of the unwary out of the right way,
making the offence of the cross to cease,
and the path wide enough for the old corrupt man to walk safely in,
without danger of alarm,
it being in their view sufficient to preserve a fair moral conduct before men,
without being shackled with the notions of a new birth from above,
and the necessity of an inward and vital change,
which the humble self-denying Christian considers essential to his eternal well-being.
They tell us our reason is the primary gift of God, and able to guide us safely along,
in all that is necessary to salvation,
rejecting the sacrifice and atonement of Christ as absurd.
