[quote.epigraph, , Jer. 48:32]
____
I will weep for thee with the weeping of Jazer, O vine of Sibmah!
The spoiler is fallen upon thy summer fruit, and upon thy vintage.
____

[quote.epigraph, John Barclay, ]
____
Yet the blessed Truth shall outlive it all, and emerge out of the very ruins,
if it must come to that.
____

== Preface

Defence of pure gospel truth, though not consistent with latitudinarianism,
is yet entirely compatible with true liberality of feeling and Christian charity.
The maintenance, too, of sound Christian doctrine,
is more intimately connected with the conduct of a holy life, than is by many,
in these days, duly appreciated.
Not that a holy life and divine acceptance may not be attained,
with nevertheless an ignorance, more or less,
of facts on which sound doctrine is declared,
or with an imperfect view of some of the great truths
of the gospel through defects of education,
or the influence of partial associations.
Far otherwise.
The grace of God is offered to all without respect of persons, to "`every kindred,
tongue, and nation,`" learned or ignorant as to this world`'s wisdom.
Yet few will deny that even "`the man of God`" may
be assisted in his path toward perfection of obedience,
and be more "`thoroughly furnished unto all good works,`"
while holding fast to the very truths of the gospel,
to the very "`form of sound words,`" as recorded for our "`instruction in righteousness`"
by the holy men of old who wrote as they were moved of the Holy Ghost.

And it is believed to be a truth beyond gainsaying,
that the nearer any man lives to the Source of all purity and holiness,
the further will he be from any willingness to deny, or to oppose,
or even to disparage the great and all-important
truths or doctrines of the Christian religion,
respecting matters connected with the salvation of the soul.
And on the other hand,
the further men depart from this "`form of sound
words,`" after having once known the way of truth,
the more (with few exceptions, if any) will laxity of life and coldness of spirit,
if not rebellion against the grace of God, characterize their walk;
unless indeed they are caught in the opposite and
by no means uncommon snare of inordinate activity,
in the will and imagination of the unregenerate man,
and are thus led by their soul`'s enemy into many
things tending to satisfy uncrucified self,
but not called for by the Lord of their best life,
and calculated to land them among the painted imitations of religion,
of which there is such plenty in and about Babylon.

This view will briefly explain the deeply settled conviction of the writer,
held in unison with many others, that those who, through the mercy of the Most High,
have been enabled to take hold of the fundamental truths of the gospel,
and to see and feel their beauty and excellency, are no more at liberty to deny them,
to part with them,
or even to appear to sanction the substitution of anything else for them,
than would be the holders of any the most important of earthly trusts,
to betray that trust and permit all manner of inroads upon it.
Nay, indeed, far more, if possible, are they bound to faithfulness herein,
inasmuch as heavenly values so far transcend those of a material nature.
Thus it has come to pass,
that in the convulsions which have assailed the Society
of Friends during the present century,
they who have remained bound to the law and the testimony through all,
faithful to the trust committed to their keeping, have felt no liberty whatever,
to compromise with or connive at departures from the truth of their profession;
but could do no other than oppose all innovations
upon the fundamental principles of the compact.
And in doing so, they cannot justly be charged with intolerance or illiberality,
inasmuch as they were endeavoring to defend no less a treasure
than the purity of the precious faith of the gospel.

The nature of these convulsions in the Society of Friends has been
very imperfectly understood by the community at large,
and even by great numbers of the members of the Society itself;
otherwise the devastation produced by them would have been small indeed,
compared with the actual results.
As years have rolled on,
and many of those concerned in them have passed away from earthly scenes,
the imperfect acquaintance with their nature seems to have increased,
rather than diminished;
and the momentous events which characterized their development are passing into oblivion,
while the results are as potent as ever in changing the character of the Christian
standard always previously held up to the world as that of the Society of Friends.
In a frequent consideration of this,
and of the fact that most of those who were familiar with the circumstances
characterizing the two principal and opposite defections of this
century among our people have already passed away,
and the rest are rapidly going, so that a generation is even now on the scene of action,
which has known nothing personally of the rise and early progress of those schisms,
it has appeared to the writer, for some years past,
that a religious duty rested upon him, to prepare to leave behind him,
for the information of successors, a succinct, and, so far as he might be enabled,
a truthful account of these eventful and sorrowful times.
Knowing the darkness of the picture, he shrunk for a while from the undertaking.
But the weight of the duty continuing to press upon him, he has done what he could,
and the result is in the ensuing volumes.

Some may be inclined to ask, Cui bono?
who or what can be benefited by thus exposing to the world the weaknesses
and sore afflictions of the highly favored Society of Friends?
Is it not uncalled for, unwise, and injurious to the great cause of Christian truth?
Why recall the bitterness of polemical disputes now settled, as some might say,
by separation of the parties?
Why stir up once more the slumbering embers, years after the blaze has gone down?
This is an important question, and claims a candid consideration.
The writer would, he trusts,
be among the last of men needlessly to expatiate on the faults of those who have
been eminent as preachers of righteousness or examples to the flock of Christ.
Yet there must be a limit to such forbearance,
or error may be insinuated and eventually stalk abroad under the garb of truth,
unchecked by those who perceive its falseness.
When radical errors are imbibed, and sanctioned or promoted by such eminent individuals,
their example and influence for evil may become tenfold
more potent than have been their previous precepts for good;
the multitude not perceiving their change,
and the course of error being a downward track, easy to the flesh,
and run with accelerative force.

Thus, through want of the never ceasing watch,
a whole people may be turned aside from the straight
and narrow way before they are aware of it,
and the character of their influence in the world
for the promotion of holiness entirely changed:
while yet they continue to retain the name,
and are looked upon superficially as the same people.
But the mere reputation of a Society should never be put in competition
for a moment with the maintenance of the pure principles of the gospel.
It becomes, therefore, a necessity for those who know the value of the primitive truth,
and understand the nature of the aberrations from it,
if they would still have it distinguished from the
falsifications which have taken its place,
if they would still desire to maintain it unsullied,
and see it held up before their fellow-men as the pure and unchangeable truth of Christ,
if they would not have their profession falsified,
and its name assumed before the world by those to whom it does not belong,
it becomes a necessary duty to endeavor to prevent their fellow-members and the world
at large from being deluded by incorrect statements and false pretensions.

Indeed,
their fellow-members and the professing Christian world
have a right to require this of the still faithful ones,
as professing to be set for the defence of the gospel.
And this cannot be done without bringing to light the real facts of the case,
and the essential nature and working of the schism.
But if it is faithfully done,
will it not tend to clear the way for those who remain steadfast,
still to hold up and cling to the true standard?
Will it not plainly point out to sincere and honest inquirers,
who are often greatly puzzled to know the difference between a true and a false profession,
marks whereby they may perceive where the truth lies,
and where error has taken its place?
And is not this of far more essential importance than any supposed injury to be done,
by exposure of personal lapses or corporate weaknesses?
Does it not indeed tend most convincingly to impress the salutary lesson,
that neither individuals nor the church can be safe from the snares of the devil,
any longer than they continue firmly to abide by
the primitive truth into which the Lord has led them,
and watch with unremitting vigilance against all attempts to turn them aside?

Was not this the chief aim of Hippolytus (who suffered martyrdom about the year 238),
in Writing his history of "`all the heresies "`which had, up to his time,
troubled the church?^
footnote:[See Bunsen`'s account of _Hippolytus and His Age_]
An account was given in this book, more or less minute,
of no less than thirty-two departures from pure doctrine in those early ages,
with the names of the parties mainly implicated;
and the author even spared not to expose the corrupt
conduct and views of the bishop of Rome.
He was not deterred by the consideration,
how unpopular such a development would be among the advocates of innovation.
He wrote this remarkable work, doubtless,
not for the sake of merely describing the heresies which had arisen
among them from the beginning of the Christian era,
which of itself alone would have been a barren topic;
but as a warning to succeeding ages,
and to elucidate the difference between sound doctrine and practice and unsound,
so that the fundamental truths of the gospel might continue to be maintained.

The course of public events in the history of the world, has shown a very frequent,
if not a continual conflict between right and wrong,
often illusory and bewildering to those whose knowledge of them is defective.
It is therefore eminently the duty of those who undertake to write history,
in ever so humble a line, to endeavor, by all means within their reach,
to present not merely the naked facts as they occurred,
but this in such a manner of elucidation of their bearing and character,
as to lead the reader to an appreciation of the right and a disapproval of the wrong.
Truthfulness must be the never ceasing aim.
And so far as the writer of history keeps simply to this straightforward course,
he cannot be properly charged with undue partiality
in evincing his own predilections for what is right.
The historian of the Reformation is not chargeable with improper one-sidedness,
in fully displaying the errors of the church of Rome,
and the greater truthfulness of the main positions of its opponents
(even though the latter may have made mistakes or false steps),
so long as he keeps to truth in his narration of the events and circumstances,
and in the tone of sentiment promoted,
not shrinking from a due acknowledgment where errors have marred the work of reform.
He would be culpably negligent of his duty, were he,
through a pusillanimous desire for the meed of impartiality,
to leave matters so evenly balanced,
as to bring his readers into difficulty to ascertain which of the
two great parties in that conflict was in or for the right,
and which was for the wrong.

The writer has had,
and still has dear and valued friends among both of the great classes
which are chiefly brought into view in the ensuing work;
and he would exceedingly regret that their personal feelings should
in any wise be hurt by the manner in which he has found it necessary
to treat of the actions of prominent individuals,
or of the respective parties, under the conviction, that if he undertook the task at all,
it was his duty to endeavor to give a plain unvarnished account of these momentous times.
The task has been a sad one,
partly in the consciousness that the truth thus plainly told could scarcely fail
of seeming harsh to the feelings or reminiscences of some such valued friends,
and to have, in their view,
the appearance of needless if not incorrect charges against some whom they have esteemed,
and whose course they have not looked upon in the same light.
It has however been his endeavor to avoid all unfavorable personal allusions,
unless where it seemed really needful for the elucidation of historical,
or still more of religious truth.
In such cases, he has felt that personal considerations, either of others or his own,
must give way to that great and all-important object.

Yet he trusts that no feeling has possessed his heart
in penning the narrative of the successive events,
like bitterness or personal hostility against any one,
whose public course nevertheless he has felt called upon to censure,
or to represent as productive or promotive of what was wrong.
He believes that he has in no case allowed himself a latitude in this respect,
which he would not he willing should be applied to himself,
should similar sorrowful occurrences render it necessary for the defence of the gospel.
To their own Master these have had to stand or fall.
It is not for us to presume to draw aside the veil which covers
the mercy-seat of inscrutable Wisdom and unbounded Goodness.
But their actions in the church were and are public property,
and of essential public interest,
inasmuch as they were of more or less powerful public influence for good or for evil,
and, so far as that influence existed,
are an unavoidable element in the history of our times.
Examples in Holy Scripture abundantly show that the public errors of influentially
eminent men are to be recorded as warnings to the church in after ages,
while their virtues are transmitted as animating examples.

An apology is perhaps here due to the feelings of some,
for the frequent use of the terminals isms and ites;
which may grate offensively on the ear, but which, as well as the word party,
the reader may be assured, are not used in any opprobrious sense,
or as a matter of inclination, but simply from necessity, for the purpose of perspicuity;
there appearing no other mode of clearly designating
classes so continually brought into view,
without inconvenient repetition,
or so frequent a circumlocution as would prove a serious
impediment to the interest and instructiveness of the narration.
There is no instance in which such epithets are used with an offensive intent,
nor perhaps any in which the writer would not have been
glad to avail himself of other expressions equally clear,
concise, and generally understood.
This should be borne in mind in the perusal of the whole work.

The writer has not felt at liberty to mince the truth, or, so far as he knew it,
in any way to evade the responsibility of giving
a clear and honest description of the real facts,
in every case under view.
His own predilections, no doubt, will appear to the reader; but this, again,
believing them to be founded on the truths of the gospel,
and of important hearing on the faithful discharge of the duty thus undertaken,
he has not felt any freedom to avoid.
Yet he trusts that these feelings have not been allowed to lead
him to suppress any statement needful to a just view of events,
or to overstate in any degree, the failings of individuals,
or dwell upon them beyond what was warranted or required by a pure
regard for the necessity of presenting clearly the causes and essential
circumstances of the successive inroads of schism.
Some apology may also be due to the reader,
for the occasional introduction of the author`'s personal knowledge of certain occurrences;
which he fears may appear like egotism;
but which has arisen from a sense of the necessity of verifying or elucidating,
as far as practicable, what was to be brought into view,
characterizing the course of events.
The first volume will carry the history to about the year 1840.
