== Chapter III.

The Outbreak of "`New Lights,`" or Ranters, in New England.

About the year 1817, in some parts of New England,
considerable unsettlement of a number of restless members
began to give trouble to the well-concerned in the Society.
This unsettlement, though at first somewhat latent in its character,
not being duly met and promptly checked by those whose province
it was to watch over one another for good,
and see to the welfare of the body, gradually gained strength, and, by the year 1820,
showed itself openly in various disorderly appearances, which,
for about four years longer, ceased not to render the solemn meetings of the Society,
in New Bedford, Salem, and Lynn, in the State of Massachusetts,
scenes of frequent reproachful disturbance by a party of ranting spirits,
who took advantage of the forbearance and weakness
of those who for a time tolerated their intrusion.

Most of these disturbers were at first members of the Society, who, on being admonished,
and at length disowned from the body,
still continued their unwarrantable imposition upon
the meetings both for worship and discipline,
countenanced, more or less, by weak and superficial individuals,
into whose favor they had insinuated themselves.
Our knowledge of the particular features of this schism, at the present day,
may be mainly derived from a manuscript account or diary left by Job Otis,
then of New Bedford,
which is the only connected narrative of it that I have any knowledge of.
It has been already referred to as a hook of more
than six hundred pages of closely written matter,
and must have been a work of no small labor and diligence.
The following chapter will be chiefly, though not exclusively,
a condensation of that account, and although of a deeply painful nature, will not,
it is believed, be found void of interest and instructive warning.
Religious history teaches us by its awful warnings, as well as by its animating examples,
as is plentifully evinced in the histories included in the Holy Scriptures.

One of the most influential instruments for mischief
among these dissentients was Mary Rotch,
of New Bedford, though not openly prominent therein quite so early as some of the others.
She occupied the station of an Elder,
and had been considered by discerning members as
a woman of fair promise for usefulness in the church.
But she possessed rank and influence in the world, and had considerable talents,
a lively imagination, a strong will and ardent disposition;
and from having shared largely in the privileges
of association with eminent members of the Society,
was well versed in its affairs,
and allowed these advantages to take too much the place
of an unreserved yielding of her heart and soul,
in humility and watchful obedience, to the divine will.
Mary Newhall, of Lynn,
was a more active and openly offensive partisan and promoter of disturbance.
She too possessed talents,
and had been a minister in good esteem as well gifted for the work of the gospel.
But giving way to exalted imaginations and a self-righteous spirit,
she began about this time to denounce the faithful Friends with much arrogance and bitterness,
and eventually became one of the greatest opponents of the way of truth and gospel order.

Perhaps, however,
the most active and mischievous among those who took an early part in these disorders,
was one Micah H. Ruggles, a man of about thirty years of age at that time.
Job Otis, who knew him well, says of him,
that "`his natural abilities were rather above mediocrity,`" "`his
disposition naturally active and forward,`" "`ardent and unstable
in his character,`" and "`had professed several forms of religion,
and manifested an intemperate zeal in the support
of them all,`" "`very impatient of restraint,
and fond of taking the lead in whatever he undertook.`"
While following the course and seeking the gratifications of the world,
this man it is added,
was preciously visited with a "`day-spring from on high,`" as was said,
whereby he became convinced of the reality of divine revelation,
and of the immediate work of God by his Spirit upon the soul of man.
Here his understanding became measurably opened,
like the man whose eyes had been anointed with clay,
and was yet to have the earthy part washed off, to see clearly.

He could see men as trees; he could see that the world of Christian professors,
with all their high pretensions to religion, were still strangers to the work of God,
by Christ, in the soul--that they were living as without God in the world,
without any realizing sense or true experience of Him,
and of his work in their hearts--that their religious creeds, ceremonies,
and outward performances, were of human invention,
and stood altogether in the will and wisdom of man.
He clearly saw a better way, and felt the call thereunto,
under a conviction that "`what was to be known of God,
was manifest in man,`" by the teachings of the Spirit of Grace.
As one suddenly waked up out of sleep, and hardly knowing where he is,
or what is about him, so he seemed confused and somewhat incoherent in his views,
and as though he thought he had already come to a
greater knowledge of the way of life and salvation,
than was possessed by anyone else.
He appeared to see some things with a degree of clearness,
and to manifest a degree of readiness to give up to the heavenly vision,
as it respected himself.

But, alas, for him! making haste to be rich in heavenly treasure,
and to be wise and knowing above what was made known to him,
and above what was written in the Scriptures of truth and in other writings of the saints,
and those of large experience;
and endeavoring to comprehend divine and spiritual things
(that are hid from the wise and prudent of this world,
and revealed unto babes) in the natural understanding;
he soon became vain in his imagination, and his foolish heart was darkened.
Instead of receiving the ingrafted word with meekness,
and settling down within himself to the grace and gift of God revealed
in him (whereby he might have experienced the work of sanctification
to be carried on to its thorough accomplishment,
viz., a death in the natural, and life in the spiritual creation),
he still retained a life in the natural unregenerate will.
And here, mistaking imagination for revelation,
the workings of the flesh for those of the Spirit of life,
he became self-righteous and exalted above measure;
and thus the innocent life in him was soon overborne and lost sight of.
Here he talked large, pretended to a great deal of revelation,
and to have divine impulses for everything, the most indifferent and trivial.

He soon became acquainted with some superficial members of the Society,
who were caught by his high pretensions;
and he followed this up by professing to have received
a command to request membership among Friends.
Through the influence of his new acquaintances,
Micah was at length--though with great reluctance on the part of some discerning ones--admitted
into membership "`out of condescension to the weak,`" as the above-quoted writer remarks,
"`and as an expedient to preserve the peace of the Society.`"
The effect of this "`expedient`" very soon became manifest.
Micah in a little time undertook to preach.
His discourses were such as might have been expected--an incoherent incongruous
medley of some things which he had really learned in his best condition,
when favored with a little anointing of the spiritual eye,
mixed with what he had gathered in the natural understanding from the writings of Friends,
and with the products and wild vagaries of an excited imagination,
and arrogant assumptions of divine authority.
And, as is usual in such cases,
he found it much easier to utter denunciations against his fellows,
than to preach the gospel of peace and good will to men.^
footnote:[John Comly in the journal of his life (p. 207) speaks of Micah Ruggles
as having been "`a military captain,`" and as "`a young man of uncommon activity
and energy of mind,`" as having been remarkably awakened about 1810,
and as then (1818) "`just coming forth in testimony in meetings,
in the simplicity of a little child`" (p. 208). He speaks of the troubles in New England
with an appearance of leaning towards those who produced the sad disturbances there,
and connects those disturbances with what subsequently
occurred in Pennsylvania and elsewhere (p. 303),
the cause being in his view, "`jealousy`" and "`stretch of arbitrary power.`"]

Mary Newhall soon became an active partisan of this man,
disturbing the meetings of Friends at Lynn with her unsavory and denunciatory harangues;
and Mary Botch likewise becoming captivated by his high-toned assumptions,
suffered her judgment to be bewildered,
and her imagination and affections to be excited in his favor,
to such a degree that she became completely estranged from her judicious friends,
and carried off the ground of truth and safety.
Micah Ruggles, early in the year 1820, undertook to travel through Providence, New York,
and Philadelphia to Washington; spreading at each place as he went,
his pernicious and reproachful sentiments.
In New York he was particularly abusive on Friends,
telling them that they knew no more than monkeys,
and charging them with all manner of immoralities.
His conduct in Washington City does not appear to have been recorded.
But respecting his stay in Philadelphia,
we have the following interesting and instructive letter from Jonathan Evans,
an elder of that city, to Moses Brown, of Providence, Rhode Island,
dated fourth month 3rd, 1820.

Beloved Friend:

Micah H. Ruggles having arrived in this city (my mind having been previously
exercised on account of the dangerous doctrines which certain persons
from the eastward have lately broached amongst us),
I felt so much sympathy with solid friends in New England,
that I had sat down to address a few lines to thee on the occasion,
that at least we might mingle our feelings and exercises together,
under the very serious and painful prospect of things
as they exist in our once highly favored Society;
but concluded it might be better to defer it until
an opportunity could be obtained with Micah.
It now appears incumbent on me to give thee what information I am possessed of,
in which a circumstantial detail will necessarily lead into some considerable length.

We received accounts of his attending a meeting for worship in New York,
wherein he spoke a long time, and used very unbecoming language towards Friends, and,
as to ministry, said that they were too corrupt to have any gospel ministry among them.
Pretty soon after his arrival here, he went to the Monthly Meeting of Philadelphia,
held at the Mulberry Street House, which I felt an inclination to attend.
There was, in the early part of the meeting, a remarkable quiet spread over us.
A woman friend from Ohio, on a religious visit to these parts,
appeared in humble reverential supplication, which, through divine goodness,
was attended with considerable solemnity.

Micah, as soon as friends had again taken their seats, pulled off his surtout and hat,
and by his gestures seemed as if he designed to make a pretty long speech;
but suddenly sat down, hanging his head, and, as I thought,
was in some degree of confusion.
And I had no doubt, there was that prevailing in the meeting,
that restrained him from disturbing it.
After friends had proceeded to the further business of the meeting,
he again attempted to say something; but, upon uttering a short sentence or two,
seeming unable to get on, again took his seat.
He attended their meeting on the first-day following; was silent in the morning,
but in the afternoon spoke a considerable time, took his seat,
and after a little space of silence, rose again;
at which many in the meeting became very uneasy.

He said a good deal, and then made a full stop.
Then Caleb Peirce, an Elder, and a friend of a very mild diffident disposition,
and well esteemed by Friends, seeing the meeting was much unsettled, said,
"`If the friend could now be easy to be quiet,
I believe it would tend to the quiet of the meeting.`"
Micah replied, "`Dost thou speak to me, or to Him that sent me?`"
But Caleb making no answer, he sat down, and the meeting broke up.
This account I have both from one of my sons who was there, and from C. Peirce also.
He has not been at their meeting since, but has attended ours at Pine Street,
and without giving interruption.
He afterwards called on C. Peirce,
and wanted to know whether he was authorized to speak to him in the meeting.
Caleb said, he did not wish to say much, but left it to his friends to judge.
My being confined with sickness prevented me from having conversation with him,
but Friends here being much concerned on account of the sentiments and views he entertained,
and has at times expressed in conversation,
it was thought most advisable that an interview should be had with him,
particularly as he intimated an intension of going to Washington.

He was accordingly notified that two friends had appointed
to meet him at my house at nine o`'clock the next day;
and he also told Dr. Moore in the afternoon,
that he was to meet friends at the time proposed.
But on the morning of the proposed meeting, he called upon Caleb Peirce,
and said he was going to Washington, and declined giving us the interview.
Caleb endeavored to prevail upon him to meet us, and put off his journey one day;
but Ruggles said he had been long enough in Philadelphia, and chose now to leave it.
He also asked if it was to be a religious opportunity.
Caleb told him that as he was a stranger, and was going to the seat of government,
Friends had a desire to speak with him;
that we did not incline to stamp our prospects so high as the effect of immediate revelation.
He then replied, "`But I do choose to stamp my impressions as of divine revelation.`"
He accordingly avoided us, and went in the steamboat for Baltimore.

Thus you may see, that so far from putting Friends to a non-plus,
there was no other conference than that which I have stated,
and that was with Caleb alone, as is before expressed.
After his return from Washington, as I was sitting in my son`'s shop, Ruggles came in,
and very freely entered into conversation with William respecting his visit to the metropolis,
of various incidents that turned up there and in his journey;
and likewise gave some account of his first coming among Friends,
the state of his mind in his early attending meetings in New Bedford,
and some of his prospects and experiences,
laying particular stress on what he calls his impressions.
Finding that he was much disposed for talking,
and full in relation to what he thought he had known,
and feeling that there was evidently a want of gravity and weightiness of spirit in him,
I sat silently hearing his various anecdotes;
and although none of them led to such a disclosure of his sentiments
as would exhibit a departure or difference from what we hold,
yet I was most easy just to say,
"`that I had always found it most safe to labor to have a little bread in my own house,
and not to talk about my own experience (if I had any),
unless particularly or unavoidably called upon for such an exposure.`"

After which he went away.
But still being under some concern, and not knowing but he might soon leave town, my son,
at my request, left word at his lodgings that I wished to see him;
and on the afternoon of seventh-day last, brought him to my house.
I mentioned that,
having heard of his having expressed sentiments to several of our young people,
which tended to lessen their esteem of the sacred writings,
and to lead them into doubts of their authenticity,
and that he had also said something that gave reason to
apprehend he did not believe in the divinity of Christ,
and that he esteemed the account of it no more than any other historical fact;
that the hearing of these things had occasioned me much distress and pain;
for it had always been our care and labor to impress upon the minds of our youth and
others the necessity of endeavoring to work out their own salvation with fear and trembling,
without seeking to pry into things which human wisdom could not fathom;
that as the principles and doctrines of our Society were published to the world,
and were well known, if he were not one with us in principle,
it would be candid in him to declare himself; for, as William Penn remarks,
we compel none to us,
but those who profess to be of us must walk conformably with our principles,
or be denied by us.

That we highly esteemed the offering and sacrifice of Christ as
an atonement or propitiation for the sins of the whole world;
most firmly believing in his divinity,
and also in the authenticity of the Holy Scriptures,
they being written by divine inspiration.
It was then mentioned to him,
that in the days of George Fox there were persons in our Society,
pretending to be so under the immediate direction of the light,
that they could not be subject to the care and oversight of their friends,
and thus thought to hold themselves clear of accountability to the body;
and by giving way to their imaginations had separated themselves,
and so far run out as to make opposition to the ministers and elders, even in public.
That the same spirit of division having frequently shown itself,
had appeared of late time in Ireland,
and under very specious professions of more enlightened views and knowledge,
had found fault with our order and discipline,
arraigned the establishment of our meetings,
and manifested hostility to our manner of worship.

But that as faithful Friends kept steadfast, these separatists came to nothing,
and confusion and misery swallowed many of them up.
I then opened to him the principles and judgment of our ancient Friends,
respecting the order and government which ever belongs to the church of Christ.
That as all the individuals of the body were members one of another, we must be subject;
but as for going about, or attempting to arraign the establishment of meetings,
or the ministry of those approved among us,
it was contrary to the order and rule instituted by the Head of the Church.
That if any were uneasy with what was delivered, or with anything among us,
there was an orderly way of proceeding towards a remedy.
He made no reply, though full time was given him;
nor did he ever attempt to deny the facts alleged.
And from what I can learn,
he endeavors to conceal his real sentiments from
those he thinks will investigate and reprove them,
but chooses to insinuate them into the minds of the incautious or inexperienced youth.

A woman Friend in the city informed me yesterday, that in conversation with him,
he expressed himself in such a manner as really to shock her with astonishment and disgust.
He spoke very lightly of Christ;
from which she understood that he had but little or no belief in his divinity; that,
as for the Scriptures, they were like the manna gathered yesterday, all worm-eaten!
And when she mentioned something about our being preserved from unbelief,
he treated it with ridicule, saying,
he supposed that if he was to believe the account of Adam, Eve, etc.,
and such-like nonsense, Friends would give him a passport to heaven!
Friends here have no unity with him or his doctrine.
And I told him, that however such opinions as his might do in New England,
they would not be received here; and advised him to return home;
which has also been repeatedly done by other Friends.
As to his pretending to an immediate impulse for whatever he does or says,
it can have very little effect with those who will not take everything from him implicitly,
but endeavor to feel the ground and foundation of every engagement;
for it will soon be perceived, that, whatever he may say about his commission,
very little weight, solidity, or real exercise of spirit, is to be felt about him.

I much desire that faithful Friends everywhere may stand firm against
the subtle insinuations and approaches of this spirit,
in its various transformations; for we have no doubt here,
that it is of the same origin with that which has troubled the church at different periods,
and tends to the dissolution of every bond of real union,
and the subversion of all that is truly good and comely in our religious Society.
There is no doubt but his mind has been enlightened;
and had he received the unfoldings of truth in the simplicity of a child,
and retained them quietly, appointed for his own real benefit,
until through divine wisdom they might be brought forth to profit,
it would have been well.
But, as our friend, Isaac Penington, says, "`Catching at them,
and taking them into the earthly part, a monstrous birth has been produced.`"
And he is, I believe, taking imagination for revelation,
and by making use of strong or severe terms,
would force upon Friends that which is of spurious origin.

With the feeling of brotherly love, I remain thy friend,

Jonathan Evans.

Although the above letter is somewhat long, yet it is so instructive,
that I have not felt free to do otherwise than give it here in full.
It portrays in some degree, and in an interesting manner, the character of its writer,
as a clear and prompt discerner of departures from
our ancient faith and from the order of the gospel,
and a vigilant watchman on the walls of Zion;
and evinces the earnestness and integrity of his concern for the safety of the church,
and his fitness for the duty which soon afterwards devolved upon him,
of withstanding prominently and with equal firmness,
the more formidable outbreak of the same spirit,
under the instrumentality of Elias Hicks and his coadjutors.

On Micah Ruggles`'s return home,
he was admonished by some of the elders and overseers respecting his disorderly course.
He appeared for the time to be considerably brought down, and denied holding sentiments,
respecting the divinity of Christ, different from those held by the Society.
But the same spirit of skepticism and disorder that actuated him
had now gained ascendency in the hearts of many others in New England,
and they encouraged one another to a continued repetition
of outrages on the good order of the Society.
It would require a large volume,
to delineate the whole course of their proceedings during the five years that they thus
broke in upon the solemn meetings of Friends with their ranting discourses and conduct.
Job Otis`'s manuscript history of these transactions,
and of the sore exercise thereby brought upon faithful Friends, details them minutely;
he having been a witness of the sad disorders,
and concerned firmly and openly to stand against them,
and to encourage others to greater faithfulness in doing what they could to check them.
We shall here have to be content with a succinct narrative of such portions of the whole,
as are of special importance,
in order to develop the awful workings of this spirit of anarchy.

Some or other of these deluded people made a frequent
practice of intruding into the meetings for worship,
and even into those for discipline after they had been disowned;
and would insist on taking the raised seats appropriated to the ministers and elders;
often dressed in gay and prominently unseemly clothing;
and would thence hold forth for a long time in a ranting manner,
to the great exercise and grief of friends, and to the reproach of the truth.
Not only were the principles and practices of these people, in regard to outward conduct,
very loose, and some of them quite disgraceful;
but many of their doctrines as to matters of faith were exceedingly unsound.
A pernicious periodical paper, entitled The Celestial Magnet,
published by one David B. Slack,^
footnote:[This paper was afterwards circulated, with expressions of approval,
by Elias Hicks.]
was freely circulated among them, and patronized by some of them;
thus instilling its infidel principles into their families,
and tending to the destruction of every tender green plant therein.

They soon began to speak lightly of the Holy Scriptures,
as we have seen in the case of M. H. Ruggles,
and to discredit the divinity and atonement of our Lord Jesus Christ.
Religious exercise of mind for the arising of divine life in the soul was set at naught,
as nothing but the restless workings of the natural mind,
under the fallacious plea that the Almighty is sufficient
of himself for his work in the salvation of mankind,
without our cooperation or any earnest concern of soul on our part,
and that we may leave it all to him.
That mere light of nature, and the vagaries of an excited imagination,
were confounded by them with the revelations of the Divine Spirit to the soul;
and this led them into many extravagancies,
in which they attempted to justify themselves with
the presumptuous notion that they were divine requisitions;
disregarding the admonitions at times administered, that God is a God of order,
and will have order in his church,
and that such proceedings tended to the breaking down of all order and church government.
Such admonitions were of no avail,
as they placed their own unbridled imaginations and wills far above
the religious concern and solicitude of their friends.

Heaven and hell they considered to be merely states of mind,
to be experienced here on earth, and to be continued hereafter in the same degree.
The existence of the devil as a distinct being was called in question;
and the necessity of repentance for past sins was discarded;
as they considered that with the past we have nothing to do,
and even the experience gathered by the past was to be set aside as useless,
so that the most recent and inexperienced in the religious life
and walk were to be regarded as of equal standing with those of
maturity in an acquaintance with the mysteries of the kingdom.
Mary Newhall, in her preaching, distinctly uttered the following pernicious sentiments:
That "`there is no devil, but that which is in man;`" that "`nothing can atone for sin,
but sin in the flesh;`" that "`belief is no virtue,
and unbelief no crime;`" and that "`we are not bound to believe what we cannot comprehend.`"
One young man, who, in after life,
was well known to the writer as a minister of the gospel,
hearing these assertions of hers in his immaturity,
and receiving them with a mistaken confidence in her integrity,
as the words of a professed servant of the Lord, was brought to the verge of infidelity.
But, after suffering unutterable distress,
he was mercifully rescued from the dreadful precipice,
and enabled to see the entire futility and wickedness of such views,
and was never afterwards, it is believed,
troubled with doubts respecting the great truths
of the Christian faith thus brought into question.
But how many may have utterly fallen down that awful precipice under the same influences,
we know not.

The tendency of their views and practices altogether was to the leveling of all distinctions,
by an assumption of liberality, or latitudinarianism,
and they constantly inveighed against "`judging,`" and against
the restrictions and obligations of the discipline,
as rigid and superstitious, and behind the enlightenment of this age.
It was very evident that in many things they were
one with the followers of Hannah Barnard in Ireland,
though perhaps advancing into greater extravagancies of conduct,
notwithstanding the advantages which some of them had enjoyed,
of good education and cultivated society.

One of the dissentients, Greely Hannaford, of Cape Elizabeth, in Maine,
came in the capacity of a minister to New Bedford, about the beginning of 1822;
and taking the head seat in the meeting,
proceeded to compare the Society to a company of "`Babel-builders;`" and
then addressed some whom he considered as "`an army whom the Lord was
raising up`"--"`who should make thorough work in the earth`"--adding,
that a reformation had already begun in the Society,
which would be the riches of the world,
and in its full accomplishment would break down the
partition-wall that separates us from the world,
the world over--that here there would be no need for any outward means of defence,
for that the law was added because of transgression--that
the Lord had shown him that this beautiful fabric (alluding,
as it would seem,
to the established order and discipline of the Society) which had been so long in building,
was to be pulled down and laid waste, so that one stone should not be left upon another.
"`Thus he went on,`" says the author of the manuscript before referred to,
"`casting abroad firebrands, arrows, and death.`"

When Friends undertook to put the discipline in practice against some of these gainsayers,
a great outcry was raised about persecution,
and several of them persisted in sitting in the meetings for discipline,
after they had been complained against as disorderly walkers,
and some even after they had been disowned.
Others, hoping to avoid the disagreeable result of being disowned,
offered to resign their membership;
and strenuous attempts were made to sustain them in the assumption
of a right to this mode of slipping out of responsibility,
and securing immunity to themselves in their defection.
In his relation of these circumstances,
Job Otis makes some pertinent and clear observations respecting this supposed right
of resigning membership in the Society--a claim often advocated in the present day.
Viewing the Society of Friends, as part, at least, of the visible church,
deriving its obligations, its trust, and its authority, from Christ, its spiritual Head,
he says,

The Society, we are bound to believe, according to our profession,
is not a mere human institution, subject to the will of man;
nor are its powers and obligations derived from man; for,
if it be any part of the true church, it is, as the apostle saith,
"`The pillar and ground of the truth,`" 1 Tim. 3:15.
Hence its obligations cannot be dispensed with by man,
at his will and pleasure.
They are all derived from, and to be exercised in, Christ its head.
And these obligations are not only to the great Head of the church,
as the Author of all good, but they extend to the members of the church,
in the relation they may respectively stand in and bear one to another,
as members of one body.
And from these obligations arise many duties, both civil and religious,
to God and to our fellow creatures, which no human power can exonerate us from;
for they are due unto God, and unto His church and people.

The duty of the body, in its collective capacity,
under the influence and direction of Christ its head,
is to watch over its members with a parental care and authority,
for their good and its own peace and welfare; and, as far as in it lies,
to restrain from evil.
It can neither countenance nor allow anything that
is injurious either to itself or to its members,
or that is dishonorable or undutiful, either to itself, or to its Head.
It cannot humor its refractory members, however stubborn they may prove,
to their own hurt or its own reproach and that of its acknowledged Head.
It cannot be accessory to any evil and wrong, for that would be to implicate itself,
and thus become accessory to its own degradation and shame.
While it is true to itself, to its spiritual Head, and to the cause of truth,
it will maintain its ascendency and its authority over its members,
derived from Christ its Head, and will neither temporize with offenders,
nor concede to any undutiful or wrong act in them.

If membership be a religious privilege and blessing, and the body be a church of Christ,
as we are bound to believe, and the natural guardian of its members; and,
on the other hand, if it be an evil,
and an outrage both to the church and the member in particular,
and an open violation of duty and of trust, in any one to separate himself from the body,
or to set himself in opposition and array against the church and her lawful authority,
then it must be equally wrong for the body,
whose duty it is to exercise a parental care and authority over its members,
to consent to, or be at all accessory to this evil and wrong.
Should a member be so lost to his own best interest, and to a sense of duty,
as to persist in separating himself from the Society,
disregarding its admonitions and contemning its authority,
then doubtless it will become necessary, for the clearing of truth and our profession,
to disown such, and testify against them.
A member persisting in a request to be discharged from the Society,
acting pursuant thereto, would from that moment withdraw himself from the Society,
and should then be treated with as a delinquent.
Taking upon himself to disown the Society,
he no longer manifests a dutiful subjection and allegiance to it,
and becomes an offender, etc.

A characteristic instance of the vulgar profanity of some of these deluded people,
even in our solemn meetings,
will serve to show the falsity of their pretensions
of being engaged for the reformation of the Society.
On one occasion, in a meeting at Salem,
some move being made in order to give an aged Friend her accustomed seat,
one B. Shaw cried out, "`Let the old +++_______+++ sit where she will!`"
And when he was disowned for his profane and disorderly conduct,
Mary Newhall undertook to plead his cause as an innocent man;
and another of the party compared the proceedings of the
meeting to the reign of Robespierre in the French revolution.
On one occasion, two of these men, Jonathan Buffum and D. Alley,
after acting in a very unbecoming manner in the men`'s monthly meeting room,
proceeded to intrude into the women`'s apartment,
where they disturbed the meeting by their unsavory and impertinent interference.
A letter from a friend of Lynn (E. Collins), dated second month 19th, 1822,
gives some account of another instance of their wildness and recklessness.

On fifth-day last was our Monthly Meeting--such a one, I believe,
as was never before witnessed in America.
B+++.+++ Shaw was carried out before the meeting was fully collected.
J+++.+++ Alley and J. Buffum took the high seat,
and compelled the Quarterly Meeting`'s Committee to take the left.
In the early part of the meeting, J. Buffum said: "`You who profess to be Quakers,
have shown the fruits of your hell-born principles this day!`"
And again:
"`This is spiritual cannibalism--you thirst for our blood--you wish to feed upon us!`"
M+++.+++ Newhall spoke of the Quarterly Meeting`'s Committee, and of the fruit of their advice,
and said to the meeting:
"`You are drunk with the blood of the saints--your garments have become loathsome!`" etc.
About 12 o`'clock the meeting became quietly settled under great solemnity.
The living part seemed to be dipped into a feeling one for another, and for the cause,
in a remarkable degree.
Soon after, the meeting proceeded to business.

One of the Quarterly Meeting`'s Committee spoke to business.
J+++.+++ Alley forbade him, and ordered him to sit down.
He declining, J. Alley persisted, and raised his voice, saying, "`Sit down,
Benjamin Folsom,`" and repeated it nearly twenty times,
with about as much extension of voice as he was capable of,
and caused a suspension of business in both meetings +++[+++being
heard through the partitions]. Some women were frightened,
and left the meeting.
Generally through the meeting,
when any of the committee attempted to express a sentiment,
J+++.+++ Alley would immediately rise, and exclaim against them,
extending his voice so as to drown theirs.
At intervals the meeting would proceed with as much firm deliberation, I believe,
as at any former period.
Sixth-day morning,
J+++.+++ Alley appeared publicly in the stores with a large sword by his side,
exclaiming against imposition, calling out,
"`Victory or death!`" and repeated it from place to place.

Seventh-day, he appeared without his sword, but said he would not be imposed upon,
he would carry his sword to meeting.
Friends concluded to warn and forbid J. Buffum and
B+++.+++ Shaw from going into our meeting to conduct,
as they had done in previous meetings; and accordingly drew up a paper,
setting forth their reasons for forbidding them.
Some Friends called to give them our reasons.
J+++.+++ Buffum would hear but a part, and left the room.
On first-day morning, J. Alley appeared, with his sword by his side.
At early meeting-time people began to collect about the meetinghouse.
Pretty soon,
those persons who had expressed themselves in such awful language came up to the door,
and halted a little.
Then J. Alley came forward with a quick and ready step,
and just as he was going up the gallery stairs +++[+++steps],
a Friend clasped him round his body and arms; other Friends assisted,
and soon took the sword from him by cutting the belt
and unclenching his hand from the hilt.

Such a scene, in a religious meeting,
seemed enough to shock every feeling we were capable of.
Friends thought best quietly to take them out, if they should persist in such conduct.
In the afternoon they came forward as usual,
and were publicly warned and forbidden to go into the ministers`' gallery,
to conduct as they had done.
But they treated Friends with contempt.
The meeting was then large,
I believe between two and three hundred of other societies present,
merely to see what passed.
The people were requested to keep their seats,
while those disorderly persons were removed.
Some Friends were then called upon to remove them; which was done,
though not without considerable disturbance; they refusing to go voluntarily,
were carried out.
An officer was called, who took charge of them,
in order to have them bound over for their good behavior.

Thus far the letter.
It is manifest that J. Alley was more or less affected with insanity;
but what shall we say of the conduct of those who encouraged him,
and promoted and aided these disorderly proceedings,
by which a peaceful congregation was thus outraged in their
lawful endeavor to wait publicly on the Lord their God?
The account given in a public paper of the date says,
that "`the justice found cause to order them to recognize for their appearance at court.`"
As they declined giving bonds,
which they seemed to consider would be an acknowledgment of guilt,
they were all committed, to await their trial.
It seems that four individuals were thus implicated,
all of whom had been disowned by Friends, except J. Alley;
and the removal was accomplished under the control of the overseers,
and by the advice of the Quarterly Meeting`'s committee.
A fifth participator made his escape from the meeting, and left the town.
The statements of various newspapers corroborate the foregoing narration,
with the additional information, that at the trial of the four prisoners, Buffum, Shaw,
and Sprague pleaded '`not guilty;`' when the clerk put the question to Alley,
he replied with energy, '`I am guilty, and I am not guilty.`' Before the trial commenced,
the county attorney entered a nolle prosequi as to Alley, who was deemed insane.
It may here be observed, that Friends had, some time before,
requested Alley`'s relations and friends to have the requisite care taken of him,
to prevent his repeating his outrages upon their meetings, but to no purpose.

The newspaper account goes on to say that the other three were then put upon their trial.
We need not pursue the details, further than to add,
from the same authority (the Salem Register),
that after much clear evidence to substantiate the facts on which they were arraigned,
the case was given to the jury;
and after a luminous statement of the facts and principles
of law on which the case depended,
delivered by Judge How, the jury retired,
and in about two hours returned with a verdict of guilty
on all counts against Jonathan Buffum and Preserved Sprague,
and an acquittal of B. S. by reason of insanity.
Buffum was, the next day, sentenced to pay a fine of one hundred and fifty dollars,
and Sprague seventy-five dollars--the court taking into
account the fact that they were almost destitute of property.

A Friend, then travelling in the ministry here, from England, George Withy,
was witness to some of the disturbances at Lynn during that year;
and in a public meeting held there in the eighth month,
when a number of the contentious individuals had
been acting in their usual disorderly manner,
he faithfully testified against them, informing the meeting,
that though he had been in the ministry nearly forty years,
and had travelled much in his own land and some thousands of miles in this,
and had held meetings with all grades of people, down to negroes and Indians,
yet he had never before witnessed such an outrage against the rules of decency,
common sense, reason, and religion, as his eyes had beheld in that place.
In the course of his communication he added,
with the firmness and boldness of speech which characterized him:

I am far from wishing to hurt the feelings of any one;
I pity these poor deluded individuals, who have been the cause of my sore anguish.
But who ever saw such an instance as took place in
the meeting I had here the other evening,
in the man that stood before me two hours and a half,
apparently for the purpose of disturbing?
But it did not move me any more than if he had been a post.
I thank God, I feel dominion of spirit over these things,
and move in a region above them all.

But many of more experience, and less confidence, or more diffidence than myself,
might have been so disturbed,
that the usefulness of the meeting might have been frustrated,
and all parties gone away dissatisfied.
And I bear my testimony against these things.
I am not ashamed to bear my testimony, in the name of the Lord,
against this desolating spirit, wherever I find it.
I feel much for the dear young people And I may now say,
that I believe the time has fully come, that patience has had its perfect work,
and it is now for the active members, both men and women,
to unite and stand against these things, that there may not be a repetition of them.

Mary Newhall, who had by this time been disowned, soon,
with the cooperation of several adherents, set up a separate meeting at Lynn;
which was for a time some relief to Friends there,
in withdrawing her attempts at disturbance from their meetings;
but this relief to the Society lasted only for a few months.
In the beginning of 1823, she again appeared, at New Bedford,
discoursing in Friends`' meetings in her accustomed unsavory manner.
It appears from the manuscript diary of Job Otis,
that a correspondence or intercourse was maintained between the dissentients in New
England and some discontented and restless spirits in Pennsylvania and New York,
who soon afterwards appeared openly as adherents of Elias Hicks.
The above writer, who was an acute observer,
has traced some features of similarity which would
naturally tend to produce a bond of union,
although the followers of Elias Hicks did not, generally,
by any means sanction such gross outrages upon the discipline and order of the Society,
as were perpetrated by that fanatical people in New England.

Their disorderly acts were temporary,
and under the excitement of a definite and in their view important aim, to wit,
the possession of the meetinghouses,
but not for the wanton purpose of disturbing meetings for divine worship,
as were those of New England.
Some of these features of agreement may be thus concisely stated:
A mistaking of the dictates of mere imagination for the leadings of the Spirit of Truth,
and then an undue exaltation of these supposed leadings of the Spirit over the
dictates of the same divine Spirit in the Scriptures and in holy men in all ages,
heretofore fully acknowledged:
a consequent disparagement of the authority of the Holy Scriptures:
defective views of the necessity of repentance for past sins,
leading to a disparagement of the value of the atoning
sacrifice made by Christ our Saviour,
and then to a denial of his glorious divinity and oneness with the Father:
a fallacious idea that the standard of divine truth is always susceptible of advancement,
so that we need not be bound by the experience of our forefathers,
but should look for higher developments,
different from what was revealed to them in the light of the unchangeable truth:
an incorrect view of man`'s duty to serve the Almighty,
discarding all motives founded on the hope of eternal reward,
and restricting them merely to the disinterested love of God;
thus diminishing the motives to a fear of "`the wrath to come`" for disobedience:
a denial of the individual existence of the devil,
any further than is found in our own carnal inclinations:
a disposition to tamper with the wholesome gospel order long established,
particularly in regard to the service of elders;
desiring to reduce it to an annual appointment: and, finally,
a constant inveighing against any settled statements of the faith of the Society,
calling them "`human creeds,`" framed in the will and wisdom of man,
and an unwarrantable obstruction of the liberty of individuals to believe as they please.

It may naturally be queried,
how was it that these gross disorders were allowed to go on so long without being suppressed?
The answer is found in the fact,
that a large proportion even of the well-disposed members,
who were not themselves participators in the corrupt
views and disorderly practices of these people,
were nevertheless more or less weak in their judgment of the depth of the evil,
entangled in a false tenderness for the individuals or their family connections,
and willing to give heed to any plausible extenuating suggestion,
looking towards a gradual healing of the sore by indefinite patience and forbearance;
thus forgetting the paramount duty of the church to maintain its purity and integrity,
relying on the helping hand of the Great Head in every time of need,
to enable it to sustain that authority which all
truly living churches of Christ are entrusted with.
The prevalency of this temporizing spirit, as it always will,
where it obtains the ascendency,
very greatly tied the hands of the few faithful and clear-sighted,
who were disposed to meet the defection with the requisite firmness and decision,
but found themselves almost borne down by the opposition,
and by the "`slack water,`" both of which combined
to discourage prompt and honest labor with the delinquents,
and the clearing of truth by bearing testimony against such as would not be reclaimed.

During this year, 1823,
the meetings of Friends at New Bedford were additionally disturbed
by the intrusion of two individuals from the State of New York,
viz., Hull Barton and Phebe Johnson,
who continued for some months to impose their ranting discourses upon Friends.
Phebe Johnson came into the meeting attired with a large red shawl, etc.,
and took the ministers`' seat.
On one occasion,
she and Benjamin Rodman undertook a sort of alternate
preaching by sentences in the style of a dialogue,
but addressed to the assembled company.
At another time, Philip Dunum, one of their adherents,
brought the Book of Discipline into the first-day morning meeting for worship,
and insisted on reading aloud a portion of it.

Content Breed, who had been disowned the previous year,
now took upon herself a course which seems to bespeak a mind rendered
insane (or else altogether taken possession of by the evil one)
through a constant indulgence in fanatical impulses and excitements,
and the stifling of conviction.
It appears from a long communication to the "`Salem Gazette,`" dated twelfth month 10th,
1823, that she intruded into the meeting for worship in Salem,
and disturbing the meeting with her disorderly harangue,
was at length removed from the meetinghouse.
On the next first-day she attended the meeting at Lynn,
a funeral taking place at that time, when the corpse was taken into the meeting.
She was clad in thin white apparel, though the weather was cold.
Pushing aside the persons who attempted to stop her,
and ascending into the ministers`' gallery, she soon rose, and exclaimed,
"`Behold the Lamb of God!
Behold the Lamb of God,
that taketh away the sin of the world!`" following this
up with sundry very disorderly expressions.

She then sat down, but soon after rose again,
and in a ranting manner interrupted a female minister who was preaching.
She was then removed from the house as quietly as practicable,
but laid herself down on the door-step till carefully taken away,
at the close of the meeting, to allow the coffin to be carried out.
Being conveyed in a carriage to the house of one of her associates,
she lay there from that day, the 23rd, to the 30th of the eleventh month,
appearing to be speechless and helpless,
except that a few times she wrote short sentences.
On the 29th, she pretended to prophesy her own death the next day.
The house became thronged, it is said, by hundreds of people, led thither by curiosity,
and about the time she had fixed, she actually put on an appearance of dying,
and lay as if dead for perhaps twenty-four hours, when, the crowd having dispersed,
she "`took a little wine,`" and soon disappeared from the town!

It should be added to this revolting account,
that some time afterwards she again made her appearance in the community,
and her mortified adherents endeavored to excuse her conduct on the plea of nervousness.
She had probably excited her mind beyond the bounds of sanity by her wild fanaticism,
and in this state may have really believed that she was about to die.
If so, her error, grave as it was, seems a pitiable one, in this stage of her course,
and less blamable than the conduct of those who were
encouraging and abetting her hallucinations and vagaries.
But the account furnishes an awful warning of the
consequences of giving way to a spirit of ranterism.
These circumstances are said to have occurred at the house of John Alley,
the man who had been acquitted by the court on the ground of insanity; and it is added,
that Alley, after this, went to the meetinghouse on the midweek meeting day,
with an axe in his hand, to demolish the raised seats;
but just as he was entering the house he was seized by some young men,
who saw him coming, and disarmed.
He was taken before two magistrates by a warrant;
but his friends interceded so earnestly for him,
that the Friends of the meeting were willing he should be released.
After this he was seen running up and down the streets with a buffalo`'s skin over him,
and shouting like a madman.
Yet in his outward concerns of business he appeared entirely rational.

It may be said that these are merely instances of the wild doings of crazy people,
and therefore unworthy of a place in sober history.
But there is a significance in them beyond that.
They were the product of associated efforts,
and one of the most sorrowful circumstances connected with them is,
that they were approved and sustained by the disaffected class in the Society,
who were acknowledged to be as sane as usual.
It is also highly probable that their insanity (if insanity it
was) was the ready result of the wild excitement into which they
had been thrown by giving way to such fallacious imaginations,
which the enemy of all good knew well how to take advantage of,
to his own account and their loss.
Yet some likewise who were not generally deemed insane,
acted at times in a manner indicating a great want
of even natural feelings of decency and propriety;
as we have seen also in later times in cases of more
or less giving way to the spirit of ranterism.
Benjamin Shaw, attending a funeral at Lynn, cried out,
"`The Lord hath taken this old man to Himself, and why all this fuss about it?`"
When the funeral procession was formed in the usual order, he exclaimed,
that "`if they had a fife and a drum, they would be ready for a march!`"
And after this, when he himself lost a young child by death,
and a friend called to offer to render any assistance in doing what might be needful,
he told him to "`begone, for he wanted none of his help!`"
And the funeral of this child was conducted in such a manner as seemed to evince
but little of natural affection or sense of the solemnity of the occasion.
So true it is, that where the heart is given up to unbelief,
the kindly affections even of our nature often wither and decay.

Benjamin Rodman, with some of his associates,
attended the ordination ceremonies of a Unitarian minister at New Bedford,
and during the course of them broke forth by way of thanksgiving for the
increase and spread of what he called gospel light in the world.
He also attended, with some others of them,
an "`Oratorio,`" or assembly for what is profanely styled "`sacred music;`" uniting
in the expressions of approbation given by the audience to certain portions of the performance.
Then, at the Monthly Meeting of Friends in the twelfth month,
the same man walked up to the head of the ministers`' seat,
with a volume of Isaac Penington`'s writings in his hand
(he had before done so with William Penn`'s works),
and, though tenderly desired to keep quiet,
persisted in reading aloud several garbled passages (without
the necessary context) respecting church government.

At the Monthly Meeting of New Bedford, in the second month, 1824, Isaac Stephenson,
a minister from England, brother to Elizabeth Robson,
and a man of an eminently meek and devout frame of spirit, was present;
and having spoken in the way of encouragement to faithful Friends,
Micah H. Ruggles attempted to do away the force of what he had said,
and was afterwards very clamorous in the meeting for business,
denying that the Society of Friends had any creed.
But Isaac Stephenson replied to him, that if, by creed, was meant a confession of faith,
he would refer him to one written by Robert Barclay, and also to his Apology;
and likewise to one written by William Penn and George Whitehead;
adding that our early Friends were always ready to give
a confession of their faith to those who asked it of them.
Micah was also reminded that the sort of "`liberty
of conscience`" demanded by him and his associates,
was a liberty entirely different from the views of the Society at any time,
and incompatible with the order and existence of religious society.

Isaac Stephenson tenderly sympathized with the honest-hearted members,
under their peculiar trials.
In the meeting the next first-day, amongst other remarks,
he expressed his feelings relative to the state of things there,
as follows (taken in short-hand by one not a Friend,
and afterwards furnished to J. Otis):

The path of the true Christian is one of suffering and tribulation;
although human nature recoils at the idea, and would gladly find out some easier way;
whilst the humble followers of a suffering Lord are only desirous
to be in company with their blessed and adored Master and Redeemer,
who does not fail to fulfill His own promises,
or to verify that precious declaration of His, "`If a man will serve me,
let him follow me; and where I am, there shall also my servant be.`"
Now, if we can sensibly feel that we are in company with the blessed Lord and Master,
surely this is enough whether it be in suffering or rejoicing.
The servant must not expect to be greater than his Lord.
It is enough for the Disciple to be as his Lord, and the servant as his Master.
We must not for a moment entertain the idea, that we are, in the present life,
to be exempt from suffering.

There are causes in ourselves, and there are causes in others whom we know and love,
and there are also causes in the world at large,
which cannot fail to be sources of suffering, of conflict,
and even of deep anguish of heart to those who are above all things
desirous of being what the Lord would have them to be,
and of sacrificing their all,
in order that they may feel something of peace and acceptance with Him.
These know what it is, like the Apostles of our blessed Saviour,
to bear about in their bodies the dying of the Lord Jesus,
that so the life may be made manifest in their mortal flesh; though often cast down,
but not destroyed; though at seasons in perplexity, but preserved from despair;
for the Lord`'s everlasting arm is underneath,
and in proportion as their tribulations abound for Christ`'s sake,
and for the promotion of His blessed cause in the earth,
their consolations will also abound by Him.

"`To lay the soul that loves Him low,

Becomes the Only Wise;

To hide beneath a veil of woe

The children of the skies.`"

This is the way, dear friends, that He is pleased to deal with the children of His people.
Now, it was foretold concerning our blessed Redeemer, by the evangelical prophet Isaiah,
that his face should be more "`marred than the face of any man`"--"`when we see Him,
there is no beauty in Him that we should desire Him`"--"`a man of sorrows and acquainted
with grief;`" and I fully believe that the true Christian`'s path is thus marred;
it is not beautiful to the eye of human wisdom; so that this eye must be closed,
and the spiritual eye opened by the Lord,
before the saint can be really beautiful in our eyes--before we
can see "`the beauty of Holiness;`" and walk in the path which
the Lord has cast up for His ransomed and redeemed to walk in.
Every faithful follower of our suffering Lord, wherever he is found,
in whatever station or situation in life,
and to whatever peculiar denomination he may belong,
is entitled to that legacy which the Lord left to all his followers without distinction:
"`My peace I leave with you, my peace I give unto you;
not as the world giveth give I unto you.`"
And, blessed forever be His name, He doth not give it and then take it away,
without it is our own fault, and we are disobedient to the divine law,
and turn aside from following Him in the strait and narrow way of the gospel.

Now, it is possible, even if we should unwisely do this,
that we may patch up to ourselves a peace; but it will not be a perfect one;
for there will be seasons when doubts and fears will spring up in our hearts,
and when the holy divine Witness, in spite of all we can do, will testify against this.
It will speak unto us even as the Lord formerly spoke unto Adam,
after he had tasted the forbidden fruit: "`Adam, Adam, where art thou?`"
And in this state,
a sense of the loss which the soul has sustained will from
time to time be as it were forced upon us;
but then it is possible to turn away from this state,
and to close the eye which the Lord has thus been pleased to open,
and thus to become blind again with regard to our real state and condition.
And in this way, it is to be feared,
many high professors of the Christian name do indeed
quench the Holy Spirit in their own souls,
and will not hearken to His voice when he pleads with them there,
setting their sins in order before them, giving them to see their polluted state,
and that they are utterly unfit to enter the kingdom of God.

Well, I believe the Lord is, from season to season,
renewedly extending his divine power to the disobedient and rebellious--unto those that
hitherto have refused to hearken to the divine voice--that have chosen their own delusions,
and have been sacrificing to other gods,
and not serving and worshipping the Lord their God with
all their hearts My very soul has been filled with fear,
that there is such a thing as spiritual idolatry--that of
idolizing the gifts and favors of the Lord--and this,
for want of coming down into the valley of deep humility,
for want of having the mind covered with the preserving fear of the Lord,
for want of feeling an inward trembling in order
that our souls may rest in the day of trouble.
Now we are exhorted to work out the salvation of the soul with fear and trembling;
for God worketh in us, both to "`will and to do of His own good pleasure.`"
And in proportion as our minds are covered with the filial
fear of God (not with the slavish fear of man,
bringing a snare with it), but with that fear of the Lord which is as a fountain of life,
to preserve from the snares of death,
all that is in us will be gradually prostrated before the Lord,
and our wills subjected before Him,
and thus we shall distinctly feel the Lord to work in us,
both to will and to do of his own good pleasure.

May we be concerned to weigh ourselves, and try ourselves, not in a false balance,
or with a bag of deceitful weights,
but in the balance of the sanctuary And if we find we have erred,
in a greater or less degree, from the just man`'s path, let us be willing,
under suffering, to submit to the revelation of the righteous judgment of God,
and that the rod may be laid upon the backsliding nature in us,
that so we may be brought back again into the right way of the Lord; for thus,
in his lovingkindness and mercy,
doth He deal with those that turn unto Him with full purpose of heart.

There is an unction to be felt, even in reading this discourse,
which must have reached the witness in the hearts of such of those who heard it delivered,
as were not abandoned to their own ways,
and hardened in their hearts against the reproofs of conviction.

Isaac Stephenson attended the ensuing Yearly Meeting in New England,
in the summer of 1824, along with William Forster, also from England;
and they are mentioned as being very helpful in their ministry,
laboring for the encouragement of the rightly exercised for a due
support of the discipline and of our various Christian testimonies.
The watchmen, both ministers, elders, and overseers,
in some places where the defection prevailed the most,
had become somewhat cast down and ready to give out,
by reason of the long-continued pressure of opposition;
so that they needed to be afresh stirred up to faithfulness.
Many of the leaders in the defection, it is true, had been by this time disowned;
yet they continued to disturb the meetings for worship,
and many of their more or less active partisans remained nominal members,
and made constant opposition to the measures necessary
for maintaining the good order of the Society,
in the meetings for discipline,
thereby often rendering them times of great discomfort to the well-concerned members.

William Forster also attended the Monthly Meeting at New Bedford in the sixth month,
and spoke to the state of the meeting in a very clear and pointed manner,
"`showing,`" as Job Otis says, "`on the one hand,
the delusive nature and tendency of the spirit of the world,
in all its various forms and appearances, warning all against it,
and particularly against the wisdom and friendship of the
world as well as against its follies and vanities;
and on the other hand, showing the unity, the consistency,
and the blessed effects of the Divine Spirit in all its operations and teachings--that
it never led any to build again that which it once led them to destroy.`"
He spoke of the Apostle Paul, both before and after his conversion;
in the first case as an example of man in the fall, governed by his own will and wisdom;
and in the latter, of one acting under the power of the cross of Christ.
He addressed some as being in a state of false peace,
having their waters smoothed as with a covering of oil,
that would be blown off when they should be troubled.
Such were warned of the danger they were in,
and exhorted and entreated to flee from the wrath to come.
Christ`'s words to the Jews,
after lamenting over them as about to have their house left unto them desolate,
for having; killed the prophets and stoned them who were sent unto them,
were feelingly revived: "`Ye shall not see me henceforth, till ye shall say,
'`Blessed is he that cometh in the name of the Lord.`'`"

One Priscilla Hunt, from the south,
who afterwards figured conspicuously among the followers of Elias Hicks,
and Benjamin Rodman before mentioned,
seem to have been the prominent disturbers during 1824.
The latter,
after producing much disturbance during a part of the sittings of the Yearly Meeting,
was kept out of the house for the rest of the meeting, and was soon afterwards disowned.
During the summer, Mary Newhall, with some of her companions,
attempted to impose her unsound ministry on Friends at Lynn;
and being ineffectually entreated to desist, she was, at a subsequent meeting,
kept out of the house.
She then stationed herself near the door outside, and beginning to speak,
a rabble assembled around, and began to make some disturbance.
Whereupon she, with two associates, was taken by a police officer before a magistrate,
and by him reprimanded, and threatened with the penalty of the law against rioters,
in case the offence should be repeated.
The Quarterly Meeting following was a time of trial to friends,
through the usual disorderly conduct of some of the contentious party;
but the meeting was sustained in patient endurance of their imposition,
and afterwards enabled to proceed with its business,
and friends were comfortably animated and encouraged to faithfulness,
through the ministry of Abel Collins, and John Wilbur, of South Kingston, Rhode Island.

About the end of this year, and beginning of 1825,
it became pretty evident that the bond of union among these
disaffected and disorderly people was giving way.
Dissensions among themselves became openly manifest.
On one occasion, in one of their separate meetings, which they had set up,
and held for awhile, the before-named Hull Barton while speaking,
happening to make a pause, one B. Worrell began to sing, to prevent him from proceeding;
and at another time,
Mary Newhall finding H. Barton not sufficiently heterodox to suit her views,
attempted to controvert what he had said, and enforce her own deistical sentiments.
This opposition so provoked Barton, that he openly attacked her,
saying there was death in all she said, and calling her a worker of iniquity.
Mary`'s husband hereupon came forward in great warmth,
and designated what Barton had advanced as "`a lie,`" and his conduct as "`insufferable.`"
The contention continued for some time, Hull`'s companion,
among other sayings of a like nature,
comparing Mary Newhall to a lamp that had become totally dark,
and plastered all over with mud by her admirers.
While this man was thus speaking unwelcome truths and pouring forth unsavory denunciations,
another individual attempted to drown his voice by singing; and so they went on,
in a disgraceful state of discord and disorder.

During the year 1825,
these deluded people had in great measure desisted from
further acts of disturbance in the meetings of Friends.
Job Otis remarks about this time:
"`The disaffected party generally have withdrawn from us, and left our meetings,
both for worship and discipline, quite undisturbed.
Some of them occasionally attend the Unitarian Congregational meeting;
while others entirely withdraw from public worship,
under pretense of not feeling it a duty incumbent on them.
But a withering evidently attends them all,
and their reputation as religious characters is very
much lost with all sober and reflecting people.
Most of them, even to Mary Rotch and Mary Newhall,
have thrown off all regard to plainness,
and the younger part attend places of music and dancing.
Much confusion, contradiction, and inconsistency appears among them in their principles,
professions, views, and reasonings; and but little else than vain speculations,
abstract reasonings, impiety, and unbelief.
Like the Babel builders of old, they seem confounded,
and their language unintelligible among themselves.
Some are saying one thing, and some another,
and all of them different things at different times.
Their faith is evidently that of the world, and not that which overcomes the world.
In their lives they are loose, and free from the restraints of the cross of Christ.
The bonds of union among them seem slight,
and evidently void of the cementing power of Truth.`"

This sorrowful defection from the Society in New England appears, as before remarked,
to have been the forerunning outbreak, in America,
of what was afterwards known as "`Hicksism;`" in like manner as we shall
see that the "`Beacon`" separation in England was the first,
premature,
and abortive offshoot of what soon afterwards became known as "`Gurneyism;`"
these designations not having been given to the respective parties
from Hicks or Gurney having been actually the originators,
but rather the ostensible developers and culminating agents, by their preaching,
their writings, and their great personal influence, of the respective departures.

We now approach the period of the greatest and most awful schism which had hitherto
been known in the Society--one which shook the whole body to its foundations,
carried many away into unbelief of some of the most
precious doctrines of the Christian religion,
and by the reaction of natural feeling which ensued in consequence of its dreadful errors,
was one means of developing the subsequent and opposite heresy,
of which our latter days are witnessing such sorrowful fruit.
This schism was brought to light and mainly promoted by Elias Hicks and his coadjutors,
and was confined in its career to the Society in America.
It was in its nature the Rationalism of Germany and France without its scientific basis,
and hardly covered by the thin veil of a pretended spirituality.
