== Chapter IV.

The Hicksian, Or Rationalistic Schism.

Elias Hicks was born at Hempstead, on Long Island, in the year 1748,
and was from his birth a member of the Society of Friends.
About a year after his marriage he settled at Jericho, on the same island,
and continued to reside there until his decease.
He came forth as a minister during the revolutionary war,
and it is not known but that for some years his ministry was sound and edifying.
He was largely engaged, and zealous in the work, often travelling abroad,
and became much admired.
He was esteemed as a good and kind neighbor, bore a good moral character,
and appears to have often been useful in his vicinity in works of charitable good will,
or in settling differences.
Of the latter, it would seem, there was a plentiful supply among his neighbors.

There is a sound and instructive letter of his extant, addressed, in 1793,
to Timothy Davis, who, with certain others,
had gone into some separation from the Society.
In this letter he tenderly expostulated with him,
showing the great danger to which those subject themselves
who run out into separation from the Lord`'s heritage,
and besought him to retrace his steps,
"`whilst the arm of mercy and immaculate love is open.`"
The individual addressed, it appears,
was eventually favored to see and condemn his error,
and was restored into unity with the Society.^
footnote:[See The Friend, Philadelphia, vol.
ii, p. 208.]
It is probable, however,
that the inward work of purification had stopped short of a going on to completion;
that there had been a tincture of self-righteousness remaining unslain; and that this,
fostered by the consciousness of being considered a great and eloquent preacher,
gained strength as his years advanced,
and furnished a door whereby the enemy entered and obtained sorrowful advantage,
leading him into lofty imaginations and random speculations,
at variance with the purity of the truth,
and finally drifting him into a confused and incoherent form of infidelity; into which,
through his popularity and influence as a bold, fluent, frequent, and extensive preacher,
he became a chief instrument of leading off great numbers of the members
of the Society in America from the sound Christian faith of our forefathers.
It has been said that, even very early in this century,
some Friends had great anxiety excited in their minds
in regard to his soundness of doctrine.

Daniel Haviland, a minister, of West Chester County, New York,
who undoubtedly manifested on several occasions the gift of prophecy,
foretold at Purchase Quarterly Meeting, in 1810, certain deep trials that were impending;
saying, "`You will be sifted from sieve to sieve.
You will be driven out of your meetinghouses.`"
And turning to those sitting in the gallery, he said, "`And you that occupy those seats,
must not expect to escape.
You will share with the rest.
You will be dragged from your seats.`"
We do not hear that he mentioned any names on that occasion,
but he lived to see the fulfillment in the outrageous conduct of
the followers of Elias Hicks there at the time of the separation.^
footnote:[See The Friend, vol.
ii, p. 134. In the Yearly Meeting of New York, in 1828,
after the separation had taken place, Daniel Haviland declared, that,
more than thirty years before that date, when the Yearly Meeting was held at Westbury,
two women Friends from Europe,
traveling in this country in the ministry (believed to be Mary Ridgway and Jane Watson),
sitting in a room in a Friend`'s house where he lodged, one of them,
seeing him go by the room-door, called him in, and pointing to Elias Hicks,
who was in another room, said to Daniel Haviland,
"`That man will some day be a troubler in Israel.`"
See Journal of T. Shillitoe, vol.
ii, p. 313.]
About the year 1817 the grounds for such anxiety became more apparent.
He displayed an unwholesome disposition to an assumption of high spiritual attainments,
a pertinacity of purpose,
and a degree of recklessness in his dogmatical assertions
touching some important articles of Christian faith,
which excited the fears of solid and spiritually discerning friends in various parts.

From some remarks in his Journal, under date of the 6th of seventh month, 1817,
I am led to apprehend that at least as early as that date (and probably earlier),
he was not clear of unsound views in regard to our Lord and Saviour Jesus Christ.
Though at that time acknowledging man`'s great need of a Saviour,
he used expressions calculated to restrict our faith
merely to a Saviour "`in the very centre of his +++[+++man`'s]
own soul;`" saying that it "`is a fatal mistake`" to look for a Saviour "`anywhere
else`"--that the Saviour needed "`cannot be one without Him,`" etc.
Although not very explicit, yet this mode of expression would hardly have been adopted,
if he had not begun to discard a reliance on the
Lord Jesus in His outward appearance in Judea,
in His sufferings and death for us, as being in any sense our Saviour.
One sound in the faith of Christ cannot separate Christ without (in that prepared
body) from Christ within (in his gracious operations in the soul of man).

The same exclusiveness in regard to the outward manifestation,
is to be found also in his remarks^
footnote:[See E. Hicks`'s Journal, pp.
304 and 329.]
dated 8th of third month, 1818;
where in speaking of the "`Lamb slain from the foundation of the world,`" he
restricts it to what took place at the fall of Adam and Eve in their own hearts,
slaying the Lamb there by their disobedience; and says that this expression,
as well as the terms "`Emanuel, Jesus, sent of God, great Prophet,
Christ our Lord,`" etc., mean "`nothing less nor more,
than the Spirit and power of God in the soul of man;`" thus ignoring
all that blessed manifestation of Christ in the flesh,
wherein He walked in holiness and divine goodness among men,
and "`gave His life`" on the cross, "`a ransom for many.`"
Such sentiments rapidly accumulated in his mind; In 1818,
he wrote a letter to Phebe Willis, in which,
among various other evidences of unsound views,
he said that the Scriptures appear "`to have been
the cause of fourfold more harm than good to Christendom,
since the apostles`' days;`" and compared Bible Societies
to the building of the tower of Babel.
And towards the conclusion, he said,
"`I well remember how oft my conscience has smote me,
when I have been endeavoring to support the Society`'s belief of the Scriptures,
that they so very far excelled all other writings.`"
This letter, and one to the same Friend in 1820 of a similar tenor,
and denying the atoning efficacy of Christ`'s death,
would have spread alarm over the whole length and breadth of the Society,
if their contents had been then made known.

After this, his unsoundness became more and more plainly developed.
Yet his great fluency of speech, the novelty of many of his ideas (crude, and coarse,
and really founded in ignorance, as many of them were),
and the boldness with which he enunciated them--fearing no contradiction,
and caring for no consequences--powerfully attracted
the admiration of ill-balanced minds,
especially among the youth;
a large proportion of whom had been suffered to grow up with but little mental cultivation,
discipline, or restraint,
and still less of an unremitting parental concern
for their nurture and admonition in the Lord.
Multitudes of these, and, sorrowful to say, many also of more mature years,
flocked around him with adulation, as a man of uncommon attainments in religion.
By rapid degrees he became more explicit in his avowal of doctrines
at variance with the Christian faith as always held by the Society;
and in every step of his progress towards infidelity,
his admirers more or less advanced with him, until,
in neighborhoods where his influence was chiefly felt,
the Society became almost overwhelmed by the pressure of those
who did not scruple to advocate deistical sentiments.

But at the same time that he feared no contradiction,
being so confident in his own position,
yet he knew well how to modify his speech according to the various
classes to whom he addressed himself in different places.
So that some of his unsound views were expressed in public with so much plausibility,
and so covered with other expressions familiar to Friends,
that many honest-hearted persons of no very deep experience,
who had perhaps only occasional and limited opportunities of hearing him for themselves,
and who were more or less caught by his sanctimonious appearance,
and profession of being a great reformer,
did not perceive the insidious poison which lurked beneath expressions
at times designed to cover up the glaring unsoundness of his sentiments.

In the year 1821, in a letter to Thomas Willis, of Jericho, L. I.,
which was some years afterwards printed,
he declared that a belief in the miraculous birth of our Saviour Jesus Christ,
as we have it plainly stated in Scripture,
was a "`historical and traditional belief,`" that "`according to his best
judgment`" there was "`considerable more Scripture evidence for his being
the son of Joseph than otherwise,`" and that he conceived "`this miraculous
birth was intended principally to induce the Israelites to believe he
was their promised Messiah`"--in other words (plain English),
that it was what is called a pious fraud,
got up to promote a certain belief among the populace!
For one who professed to be a minister of Christ, to come forth with such sentiments,
was indeed astonishing, and if this had been at that time publicly known,
the Society might have been better prepared to look for and meet
such a succession of wild and frightful doctrines as soon followed
each other in his public declarations.

It would be a dismal task to follow him during the next six years,
and trace the particular order of development of these sentiments from time to time.
He seemed to be floating on the wave of popular applause among his adherents,
and was perhaps thereby carried at times beyond what his
sober judgment under other circumstances might have dictated.
And this may account for his frequent contradictions.
But as many (perhaps most) of his sermons during
this period were taken down in short hand,
and printed and widely circulated by his friends,
and the correctness of the printed copies not only was never disavowed, but,
at least as regards a large proportion,
was distinctly acknowledged by him to be "`in general very correct;`"^
footnote:[See his letter to the stenographer, M. T. C. Gould, dated third month 28th,
1828: "`I have read most of the discourses which thou hast published,
and have found them in general very correct.`"
The Quaker, vol.
iv, p vii.]
there can be no reasonable ground for doubt as to the sentiments being his own,
as expressed; and especially as some,
the most distinctly subversive of the Christian faith,
were in various modes of speech repeated many times over,
and several of the very worst of them he undertook to defend in private interviews with
those who from time to time sought his conviction and return to the truth of the gospel.

It will be best now to allude to the various items of his unbelief,
as gathered from his Printed Sermons and Letters,
and to class them under distinct heads of doctrine,
in order to have a clearer view of their concatenation and general tendency,
than by merely following the dates of his successive utterances in various places.
His habit of speaking (judging from the generality
of his printed discourses) seems to have been desultory,
random, irreverent, and sometimes even profane in its terms;
and though often contradictory to what was expressed at other times and places,
and at times containing passages unobjectionable as to doctrine,
his sermons were as a whole, so full of unsound sentiments,
and of allusions tending to promote his favorite unsound dogmas,
that it is difficult to know what passages to select from among the mass of error,
without making the exhibit altogether too bulky, and we may say,
too nauseous for Christian readers to peruse with calmness.
How they could have been calmly listened to in Friends`' meetings, seems a mystery.

Respecting Our Lord Jesus Christ,
we may take the following out of many passages of similar tendency.
In a sermon preached at Fallsington, in Pennsylvania, on the 11th of twelfth month, 1824,
after speaking of our Lord Jesus Christ as the Son of man, he says:

Here now we learn as rational beings, by his own testimony,
what it is that makes a son of God.
We see that this flesh and blood never could have been, in a strict sense,
the Son of God, but a creature, created by God, by his power:
because spirit and matter cannot be united together and make a being,
nor make a son of God.
(Philadelphia Sermons, p. 251.)

Again, in a sermon preached at Arch Street Meeting, in Philadelphia,
on the 14th of eleventh month, 1824, he said:

Who was his Father?
He was begotten of God.
We cannot suppose that it was the outward body of flesh and blood,
that was begotten of God, but a birth of the spiritual life in the soul.
We must apply it internally and spiritually.
For nothing can be a son of God, but that which is spirit;
and nothing but the soul of man is a recipient for the light and Spirit of God.
Therefore, nothing can be a son of God, but that which is immortal and invisible.
Nothing visible can be a son of God.
By the analogy of reason, Spirit cannot beget a material body,
because the thing begotten must be of the same nature with its father.
Spirit cannot beget anything but spirit; it cannot beget flesh and blood.
No, my friends, it is impossible.
(Philadelphia Sermons, p. 10.)

Again, in his sermon at Fallsington, on the 11th of twelfth month, 1824, he said,
in reference to Christ,

Then it was not his grace,
but the grace of God communicated to him as it was
communicated to the rest of Abraham`'s children,
to every one in a sufficient degree to enable them
to come up to the law and commandments given them.
(Philadelphia Sermons, p. 253.)

Preaching at Staunton, Delaware, eleventh month 20th, 1826, he said:

Jesus Christ the Saviour of the soul, never was seen by the eyes of men,
and forever will be the same power of God,
and same divine anointing with which Jesus was anointed.
(The Quaker, vol.
iv, p. 84.)

Preaching at another time, he said,
in regard to the Spirit descending on Jesus at his baptism by John:

Here now we find, that having an additional power,
he had also additional trials to encounter;
he was brought to see the trials and temptations that awaited him,
arising from the propensities of his human nature;
for he stood in need of all things in the same manner as we do, to eat, to drink,
and to seek knowledge.
(New York Sermons, p. 85.)

Again, in the Fallsington sermon, already quoted from, he said:

Now, let us pause a little, and consider what is here meant.
Can it be supposed that he was driven into an outward wilderness?
Or shall we not suppose that he was brought, by the power of divine light,
to see the wilderness state of his own mind?
(Philadelphia Sermons, p. 256.)

In Philadelphia, on the 1st of twelfth month, 1824, at the Western Meetinghouse,
after speaking of Jesus as "`their Saviour,`" meaning the Jews, he said:

He it was that saved them from their outward sicknesses.
He was only an outward Saviour, that healed their outward diseases,
and gave them strength of body to enjoy that outward good land.
This was a figure of the great Comforter, which he would pray the Father to send them;
an inward one, that would heal all the diseases of their souls,
and cleanse them from all their inward pollutions; that thing of God,
that thing of eternal life.
It was the soul that wanted salvation; but this no outward Saviour could do,
no external Saviour could have any hand in it.
(Philadelphia Sermons, p. 50.)

Preaching at Trenton, on the 12th of twelfth month, 1824, he declared:

Not the name of Jesus Christ will save us.
No, but that light and life that was in Him--that was in the beginning with God,
by which the worlds were made, and that light, it is declared,
enlighteneth every man that cometh into the world.
Therefore, every one of us has the same light and life, according to his necessity,
as Jesus Christ had, in his proportion.
(Philadelphia Sermons, p. 295.)

In a printed reply to a letter of Thomas French,
detailing his unsound preaching at Purchase Quarterly Meeting, in 1828, Elias Hicks says,
in reply to one of the charges:

My declaration was this, that Jesus Christ, while in that outward manifestation,
walking up and down in Jewry, in the course of his outward ministry,
never made a Christian.

And a few sentences afterwards he acknowledges:

I also said,
there was no external mediator between God and his creature man under the gospel.

In the New York Sermons we are told that he said:

But it is not the righteousness of another that can save us.
It must be done by the individual himself, or he cannot be the elect of the Lord;
for he is of the elect who elects God.
Jesus elected his heavenly Father as his rule and guide.
So also must we, etc.
(New York Sermons, p. 16.)

In his sermon at Fallsington, again, on the 11th of twelfth month, 1824,
he said as follows:

Oh may we press forward to the mark for the prize of the high calling
(omitting "`in Christ Jesus our Lord`"). It is attainable to us;
as certainly as it was attainable by Jesus Christ,
so certainly it is attainable by every one of his faithful followers.
(Philadelphia Sermons, p. 266.)

At another time and place, he said:

This portion of his Spirit being given to us to profit with,
it will continue to operate till it leavens the whole lump.
Herein it was, that Jesus became the Son of God,
through the life and power of God in him, which leavened him into His own holy nature,
till he was swallowed up into the divinity of his heavenly Father.
Having been faithful to the Father in all things, His storehouse was opened to him,
because his Father could trust him with all His treasures.
He knew that he would not embezzle, or make a wrong use of these treasures;
but that he would wait to know his Father`'s will,
before he would dispose of the things which were opened to his view.
Now, here is the full and complete divinity of Jesus Christ.
From what Jesus himself said, he was not God! (New York Sermons, p. 96.)

At Trenton, on the 12th of twelfth month, 1824, in speaking of Moses and the prophets,
Jesus Christ and His apostles he added immediately:

He never can set any of these above us, because if he did, he would be partial.
(Philadelphia Sermons, p. 292.)

Preaching at Wilmington, Del+++.+++, on the 3rd of twelfth month, 1826,
he made use of the following unjustifiable insinuation against
the correctness of our translation of the New Testament,
in pursuance of his constant practice of separating Christ within
us from our Lord Jesus Christ who appeared in the prepared body.
He said:

Now don`'t let your attention be turned outward,
from the expression of these words +++[+++"`that Jesus Christ is in you,
except ye be reprobates`"],
for very probably the translators have not given it right to us.
Because the outward Christ never could be, or can be, in us.
(The Quaker, vol.
i, p. 222.)

How can we possibly doubt,
in reading the above extracts (which might be indefinitely multiplied),
that his purpose was a persistent one, to degrade our Blessed Lord Jesus Christ,
to the level of a mere man,
like any one of ourselves who might attain to perfect righteousness?
In like manner, respecting the Atonement, or Propitiatory Sacrifice on the Cross,
he thus expressed himself to Dr. N. Shoemaker, of Philadelphia, in a letter,
dated third mouth 31st, 1823, and afterwards printed:

Did God send Him into the world purposely to suffer death by the hands of wicked men?
By no means; but to live a righteous and godly life, etc.
If this be true, what becomes of the saying of the apostle Peter?
"`Him, being delivered by the determinate counsel and foreknowledge of God,
ye have taken,
and by wicked hands have crucified and slain;`" or of his own gracious declaration:
"`Even as the Son of man came, not to be ministered unto, but to minister,
and to give his life a ransom for many.`"

Again, in the same letter:

But I do not consider that the crucifixion of the outward body of flesh and blood of
Jesus on the cross was an atonement for any sins but the legal sins of the Jews;
for as their law was outward, so their legal sins and their penalties were outward,
and these could be atoned for by an outward sacrifice, etc.

And again, in the same letter, how awful the following expressions!

Surely, is it possible,
that any rational being that has any right sense of justice or mercy,
that would be willing to accept forgiveness of his sins on such terms?
Nay, was he so hardy as to acknowledge a willingness to be saved through such a medium,
would it not prove that he stood in direct opposition
to every principle of justice and honesty,
of mercy and love, and show himself to be a poor selfish creature,
and unworthy of notice?

At a meeting in Rose Street, New York, fifth month 25th, 1828, he thus expressed himself:

What life is it that is an atonement for the sins of mankind?
That very life and being that has committed sin, and opposed God.
(The Quaker, vol.
3, p. 192.)

Respecting The Holy Scriptures, in a sermon preached at Abington, Pa., twelfth month 6th,
1824, he thus expressed himself:

One would suppose that to a rational mind,
the hearing and reading of the instructive parables of Jesus
would have a tendency to reform and turn men about to truth,
and lead them on in it.
But they have no such effect.
(Philadelphia Sermons, p. 129.)

Again, he said, in the same sermon:

They have been so bound up in the letter, that they think they must attend to it,
to the exclusion of everything else.
Here is an abominable idol worship, of a thing without any life at all, a dead monument.
(Philadelphia Sermons, p. 139.)

And again, in the sermon at Trenton, twelfth month 12th, 1824:

But here we see that the people have been depending upon the letter.
Oh, what mischief has this done in Christendom!
What dreadful work has it made among the children of men!
It proves, itself, what it is; that it is nothing but a history of passing events,
which occurred eighteen hundred years ago, a great portion of which may be true;
a great deal was the immediate experience of the servants of the Lord,
and opened to them by his revealing Spirit, which they have written.
But look back at Christendom at its rise.
Here we see Jesus calling them to an account for attending to the Scriptures;
and we see in a short time after, that by application to these books contention entered,
and divided Christian professors.
(Philadelphia Sermons, p. 315.)

The expression in this passage,
of "`1800 years ago,`" refers of course to the New Testament history; of which he says,
"`a great portion may be true!`"
As to our Lord "`calling them to account for attending
to the Scriptures,`" it is utterly false.
He frequently referred to and quoted them himself.
In a meeting at Darby, in Pennsylvania, on the 7th of twelfth month, 1826, he said,
after alluding to certain "`non-essentials,`" held by religious professors,
"`And these are all stumbling-blocks,
and perhaps there is not a greater one than the Scriptures, called the Bible,
or the Old and New Testaments bound up in a book.`"
(The Quaker, vol.
iv, p. 138.)

Respecting what he called Religion,
we have in the following passage from a sermon preached at the Western meetinghouse,
in Philadelphia, on the 1st of twelfth month, 1824, a remarkable definition,
which sounds more like the effusion of a heathen philosopher than of a minister of Christ.
Though long, it will be best to present the whole passage, to show its deliberate aim.
He said:

All that we have to do, is to keep every desire regulated by the standard of truth;
and as we keep up this engagement, we are improving the moments as they pass.
Here our improvement is all entered for us upon the Credit side;
we are made creditors for our right improvement.
So, on the contrary, if we neglect the proper improvement,
it is placed to the Debtor side.
It is a common maxim, and a good one, that short reckonings make long friends.
If it was only our care every day of our lives, to look over the actions of the day,
and see how our accounts stand with our Creator,
how greatly should we be benefited by this self-examination.
Would not a prudent bookkeeper, if he did right,
bring up his debt and credit every night, that he might know how things stood?

Then how much more so, in the business of salvation,
ought we to endeavor to improve every moment of the passing time from day to day,
and never let an evening pass over, without looking over and turning over the leaf,
to see where the balance would strike, whether in favor or against.
If it be against us, let us double our diligence the succeeding day,
to retrieve our lost time.
Let us strive to have a balance in our favor from season to season, and from day to day.
If this were our concern,
although we were not joined in society with any profession of religion,
were these our engagements, all would be well; all these would become one,
and make that society, which is the only militant church on earth.
However scattered, they would feel for one another;
and whenever they passed by one another,
they would be impressed by the one Spirit to become one body,
and made to drink into the one Spirit.
This I call religion; but I consider no profession of religion to be religion at all.
(Philadelphia Sermons, p. 44.)

So by this we may go on sinning, even without repenting, only we must take care,
as "`prudent bookkeepers,`" to make it all up every
day by a counterbalance of good deeds,
to keep our credit right with the Almighty!
There is then no need of repentance or of forsaking sin,
if we can only manage to balance the account every night by something to our credit,
and so keep the Most High always in our debt!
And this is what Elias Hicks calls religion.
"`This I call religion,`" says he, with great apparent satisfaction.
Verily, it is the refuge, forlorn as it is, to which they are driven,
who reject the propitiatory sacrifice of our Lord Jesus Christ.

Preaching at Cherry Street meeting, Philadelphia, fourth month 13th, 1828, he said:

Now I do not consider faith and belief, merely, to be any part of religion;
because belief is not a voluntary act of the human mind.
(The Quaker, vol.
iii, p. 94.)

Respecting Heaven and Hell, he held as follows: In a letter from a Friend, of Ohio,
alluded to above, he had been charged with having said,
among many other unsound declarations,
at Purchase Quarterly Meeting on the 1st of fifth month, 1828:

All the heaven and hell there was,
was in us,--we received our rewards and punishments every day; our heaven and hell daily,
and all, he believed, we ever should.
To prove it, he said, the drunkard would get his bottle and get drunk;
this was his heaven; we saw him happy, he was then in heaven; and then he would,
when he got sober, feel miserable; this was his hell;
and if there was any heaven or hell hereafter,
it was something we could know nothing about.

In his printed reply, defending himself from some of the charges in that letter,
he does not deny having expressed himself as above, but, in degree at least, admits it,
by the following retort upon his accuser:

And as to what he says about heaven or hell,
I will ask him where he has found any heaven or hell without him?
I should like to hear him describe the shape and form of them,
and in what region or place they are situated?

And in a sermon given in the New York edition,
he declared that "`heaven is everywhere where God and his rational creatures are.
It is not a local place by any means.`"
(New York Sermons, p. 93.) He seems to have forgotten that our gracious Lord said,
"`I go to prepare a place for you.`"

Respecting the Devil, and fallen angels, his belief was expressed as follows:
In a sermon preached at Byberry, Pa., on the 8th of twelfth month, 1824, he said:

"`But people are too generally looking outwardly to find God,
and in this outward looking they are told about a devil--some monstrous
creature--some self-existing creature--that is terrible in power.
Now all this seeking to know God, and this devil, or the serpent without,
is the work of darkness, superstition, and tradition.
It hath no foundation; it is all breath and wind without the power.`"
(Philadelphia Sermons, p. 163.)

Again, in the same sermon, he said:

What is the devil?
It is that cunning,
twining wisdom--that serpentine wisdom of man It
is nothing but excess that makes the drunkard.
Here now we see where sin begins; here we see where devils are created--by man himself;
he is the author of them all, as he is the only fallen angel upon earth.
(Philadelphia Sermons, p. 166.)

In like manner, at Trenton, on the 12th of twelfth month, 1824, he said:

Who are the devils?
Apostate men and women who go contrary to God.
They are all devils.
Everything that is in opposition to the will of God is a devil.
(Philadelphia Sermons, p. 293.)

Of the same tenor is what he said at the Northern District Meetinghouse,
in Philadelphia, on the 16th of eleventh month, 1824, as follows:

We may remember what the apostle declared, that Satan,
the name given to that tempting disposition in us, which is the man of sin,
self and self-will in man; there is no other man of sin that I ever knew or found.
(Philadelphia Sermons, p. 37.)

Had he forgotten, while making these bold assertions,
the distinct account in the New Testament,
that even the blessed Jesus was tempted by the devil?
If we say that this was "`the serpentine wisdom of man,`" his own
"`self-will,`" the "`tempting disposition,`" in him,
do we not speak blasphemy?
For we know that the dear Son of God was "`holy, harmless, undefiled,
separate from sinners that he did no sin, neither was guile found in his mouth.`"
So that, if there is no devil but our own evil propensities,
the evangelist must have recorded a dreadful falsehood,
or else blasphemed his Lord and Master!

Respecting the Scripture account of the Garden of Eden: On the 5th of twelfth month,
1824, at a meeting at Germantown, he said:

What is Eden`'s Garden, my friends?
It is the place where the Lord God is pleased to commune with his creatures face to face,
and nowhere else.
It is everywhere where God is.
(Philadelphia Sermons, p. 113.)

In a sermon preached at Horsham, Pa., on the 16th of twelfth month, 1826, he said:

And what was that?
It was a state of communion with the Holy One.
It was no located spot, my friends: the Garden of Eden, so called,
was never located on earth.
(The Quaker, vol.
iv, p. 27.)

And at Middletown, on the 19th of twelfth month, 1826, he said:

I say there never was any such tree, nor any such garden, outwardly,
as is here represented, but it is a figure or allegory.
(The Quaker, vol.
iv, p. 203.)

And at Byberry, on the 8th of twelfth month, 1824, he said:

And what were the trees in the Garden of Eden?
They were the propensities of man in his animal body.
These are the trees that will grow if they are not kept down by pruning.
(Philadelphia Sermons, p. 167.)

In a sermon included in the New York edition, he spoke of:

The same covenant of light and life which he made with our
first parents when placed in the paradise of God;
which was no particular local spot, but a state and condition of the soul,
which was suitable to have communion with its Maker.
(New York Sermons, p. 88.)

And (marvelous confusion!) in preaching at Trenton, on the 12th of twelfth month, 1824,
he declared:

For God must be the tree of the knowledge of good and evil.
There was no tree of the knowledge of good and evil but God himself.
(Philadelphia Sermons, p. 317.)

Respecting the fall of man,
we may gather his views from the following assertion
made in a sermon preached at the Falls,
in Bucks County, Pa., twelfth month 20th, 1826:

I certainly know that I have never felt any loss from Adam`'s sin.
I have never felt anything to induce me to commit sin,
but a desire in myself to gratify my propensities beyond
the design of heaven in giving those propensities to me.
(The Quaker, vol.
ii, p. 266.)

Respecting reason, and its supremacy,
so much vaunted by the French revolutionary school of philosophers falsely so called,
he said, at a meeting at Newtown, Pa., on the 9th of twelfth month, 1824:

I say, if Antichrist brings anything up which has a counterfeit appearance,
our reason is a balancing principle.
(Philadelphia Sermons, p. 207.)

In a printed letter to Dr. Edwin A. Atlee, of Philadelphia,
defending himself against some charges of having expressed unsound views
in an interview which Anna Braithwaite had with him at his house in 1824
(whose statement of what occurred is much confirmed as to its main features
by his own letter defending himself against it),
he makes the following deliberate assertion;
a dogma which was caught up by his followers and echoed
throughout the land as if it were a fundamental truth:

I admit that I did assert, and have long done it,
that we cannot believe what we do not understand.

And yet, in preaching at the Western meetinghouse, Philadelphia,
on the 1st of twelfth month, 1824, he could so far forget his adulation of Reason,
as to utter the following indiscriminate fulmination against those who
are making the most constant efforts to improve and promote it by knowledge:

Oh, that men of science might be aware,
what a curse they are to the inhabitants of the earth!
what a great curse! (Philadelphia Sermons, p. 53.)

The foregoing exhibit of only a few of his own authenticated
words places it beyond any reasonable doubt,
that Elias Hicks did clearly and unequivocally deny the miraculous birth, divine Sonship,
and Mediatorship of our Lord Jesus Christ, and his atoning sacrifice on the cross, and,
often in terms almost contemptuous, endeavored to show Him forth as a mere man;
that he spoke of the Holy Scriptures in the same tone of contempt,
as "`nothing but a history of passing events which occurred 1800 years ago,
a great portion of which may be true;`" and asserted that they were one of the greatest,
stumbling-blocks to mankind; that he denied Heaven or Hell to have any place or being,
except in the soul of man; or the devil to be anything more than our evil propensities;
that the Garden of Eden was any particular place,
but a "`condition of the soul;`" and asserted, among many other fearful errors,
that Reason is the "`balancing principle,
to detect counterfeit`" presentations to the mind;
so that we are not to be expected to believe what we do not understand!`"
These views are in entire accordance with German rationalism.

Here the inquiry suggests itself,
whether Elias Hicks really knew what he was saying in these wild and deistical enunciations;
whether he really appreciated the scope of his expressions;
whether the sentiments as uttered were truly held by him,
or whether the utterances were the offspring of a momentary excitement while speaking.
I should be inclined charitably to believe the latter, if possible,
especially after comparing his sermons with the comparatively
sober remarks in his printed journal;
though we have no means of judging how far the latter was published,
complete and full as he left it.
But such a supposition seems forbidden by the fact,
that some of his worst sentiments are found confirmed by passages in his letters,
and even in those letters which were written in his own defence.
So that we are confined to the sorrowful conclusion,
that he really held those antichristian views which the foregoing extracts represent.

Another question,
naturally occurring after looking on the evidence of so wide a departure
from sound doctrine on the part of a professed minister of the gospel,
is this: Was Elias Hicks never checked in his career, or, at least,
were no attempts made to arrest his downward course, by faithful brethren and sisters,
who were aware of his dereliction,
and were concerned for his safety and that of the Society?
One who had good opportunities of knowing, has testified,^
footnote:[See Journal of Joseph Hoag (D. Hestori`'s edition), page 289.]
that "`much tender advice had been bestowed upon him from time to time,
to save him from running out to nothing, yea, worse than nothing, but without effect.
All this time he pretended great love and concern for the
cause of Truth and for the welfare of the church;
and in this way he was diffusing, in private, his deistical sentiments;
and by letters he spread his principles far and wide, before Friends were aware.`"

Samuel Parsons, of Flushing, on Long Island,
was aware of his unsoundness of doctrine as early as 1815; and, in his capacity as Elder,
he labored with him repeatedly on that account.
But this could go no further than private admonition, as Elias Hicks had such influence,
especially in his own meeting,
that his adherents would not listen to any complaint against him.
And when objections were offered to his traveling as a minister, they were overruled,
"`with threats that, if the objectors opposed his doctrines,
they should be taken up by the overseers.`"^
footnote:[See S. Parson`'s testimony in "`Foster`'s Report,`" vol I, page 176.]
It appears also that Thomas Willis, a minister of Jericho, L. I.,
was among those who honestly and plainly labored with him respecting his errors.
This was at various times between the years 1818 and 1821, by interviews and letters.
Elias indeed was the subject of admonition and care
on the part of a few of the elders of his own meeting,
for a long time; but most of the elders of that meeting being his adherents,
any attempt there to expose his unsoundness would
doubtless have led to the disownment of his accusers.

In the second month, 1819,
Elias Hicks travelled into the part of Vermont where that faithful minister, Joseph Hoag,
resided.
Here, preaching at Ferrisburg,
Joseph Hoag heard him express views which exceedingly alarmed him.
In a discourse of near two hours long,
Elias spoke of the placing of man in the garden of Eden,
and "`occupied a full half-hour,`" says Joseph Hoag,
"`to make it appear that there was no other evil in space,`"
than the tree of the knowledge of good and evil,
repeating this strange assertion three times over,
but without any other proof than his own statement.
"`To polish his discourse, he recommended a good deal of moral conduct.`"
He then took up the tree of life,
and for about another half hour attempted to show that this was
the Lord Almighty Himself--"`that it could not be otherwise!`"
This also he repeated three times,
"`but offered no proof,`" to support him in his wild idea.
As before, this also "`he dressed with the beauty and happiness of good moral conduct.`"
After this, he "`made a full stop`"--and then declared,
"`We have a right to choose good or choose evil, just as we please;
and take that right from me, and I would not value my being worth having.`"

He continued his discourse for nearly half an hour longer, laboring to support his views,
and then soon closed the meeting.
Joseph Hoag was greatly tried with what he had heard,
and concluded that if possible he must have a private interview with him.
This was obtained after some difficulty in a few days.
After some discourse on J. Hoag`'s dissatisfaction with his preaching,
and in particular with his absurd declarations regarding the tree of knowledge
of good and evil being "`the only evil in space,`" thus making the Almighty,
who, he had himself said, planted the tree, the author of all evil, Elias said,
"`What other evil is there then?`"

J+++.+++ Hoag.
"`The Bible tells of a serpent.`"

Elias.
"`What! a Snake?`"

J+++.+++ Hoag now endeavored to convince him, by appealing to his own experience,
of the existence of an evil spirit, tempting mankind to wrong.
His words came at length with so much cogency against the flimsy defences of Elias,
that he acknowledged,
"`I do not mean to discard the idea that there is an evil spirit which tempts us.`"

J+++.+++ Hoag.
"`What dost thou then mean to deny?
Thou certainly denied it in thy preaching.`"

Elias.
"`I mean to deny that there is a great mawking devil, with one oxfoot and one manfoot,
and five eyes, which appears to people to scare them!`"

J+++.+++ Hoag.
"`I am disappointed in Elias Hicks.
I always thought him to be a man of talents.
I did not expect to hear such words come out of his mouth.
I have no belief that there is a child in our country, twelve years old,
that has learned enough to read, that believes such an idea.
Matter does not inhabit the world of spirits.`"

Elias.
"`Many of our Quaker ministers believe it.`"

J+++.+++ Hoag here requested him to stop, and referring him to the Bible,
endeavored to show him how defective his ideas were,
and how contrary his language was to the plain Scripture account.
He made no further reply to this,
and Joseph Hoag reasoned plainly with him on the
broad ground of the unsoundness of his ministry;
telling him what uneasiness had to his knowledge been already
produced by it in various parts of the country,
and how he had been told by Friends,
that Elias "`would never make Quakers by his preaching, but would make infidels.`"
After Joseph had declared his entire disunity with such preaching and sentiments,
and Elias having nothing further to answer, they parted.
Joseph Hoag adds to his account of the interview, that after this,
"`he stayed hereaway some time, held meetings, and made social visits,
until he had enlisted every Elder in our Monthly Meeting,
and several influential members,
and went off and left me in as hot a furnace as he could prepare for me.`"

In the summer of 1822, Joseph Whitall, a minister of Woodbury, N. J.,
attended New York Yearly Meeting, and heard Elias Hicks declare,
"`that the same power that made Christ a Christian, must make us Christians,
and the same power that saved Him must save us.`"
Having never before heard such sentiments from any minister among Friends,
and being very much astonished at them,
Joseph felt it to be his religious duty to take a
private opportunity with him on the subject.
In this interview, J. Whitall tenderly entreated him,
as one for whom he had entertained a warm esteem,
and acknowledged that he would willingly, yes, gladly,
"`spend a year in travail and exercise, that his sun might go down in brightness.`"
E+++.+++ Hicks was brought to some feeling, and even to tears;
but he still maintained his belief that "`Christ was no more than
a man,`" and "`liable to fall like other men;`" and further asserted,
that "`it was an abomination to pray to Jesus Christ`"--that "`the Scriptures
were the cause of more bloodshed and confusion than any other thing`"--that
"`it was a pity the Epistles had ever been handed down to us,`" etc.
And when expostulated with upon the schism which such ideas, if persisted in,
must produce, he said, "`It was in vain to reason with him on the subject,
for his mind was made up--that he was determined to persevere,
let the consequences be what they might.`"
And in another interview with J. Whitall, six months afterwards, at Woodbury,
he still took similar ground,
stating his belief that "`Jesus Christ was no more than
an Israelite,`" and that "`he believed George Fox,
William Penn, and R. Barclay thought as he did, but they were afraid to come out!`"^
footnote:[See J. Whitall`'s Testimony, in Foster`'s Report, vol.
i, pp.
214, 215, and 246.]

One ancient and venerable friend, William Jackson, a minister, of London Grove,
in Pennsylvania,
was another of those who sought Elias Hicks`'s recovery by a private interview.
William Jackson had known something of Elias Hicks for about forty-three years,
without being aware of his unsoundness; when, being in New York,
in the summer of 1824 (then about seventy-eight years of age),
and being at a meeting where Elias Hicks preached,
he heard such sentiments from him in his public discourse,
as he had never before heard delivered, "`either by professor or profane.`"^
footnote:[See his Testimony given in Foster`'s Report, vol.
i, p. 100.]
He spoke of the Lord Jesus as "`having suffered as a martyr`"--as "`many others since
that time had done`"--and labored to bring him down to the level of a mere man.
William Jackson being greatly astonished and grieved, believed it to be his duty,
"`as a brother,`" to seek an interview with him, in order, if possible,
to convince him of his erroneous and dangerous views.
In his account of what occurred, he states that Elias Hicks asserted to him,
that "`there was as much scripture testimony to prove that he +++[+++Jesus]
was no more than the son of Joseph and Mary, as there was to prove the contrary.`"

William Jackson brought forward the testimony of Matthew and Luke;
but Elias Hicks said that "`they were no more than fables.`"
William Jackson expressed his astonishment at hearing such language,
but Elias declared that "`he was confident of what he said--that it was a thing
impossible--spirit could only beget spirit--it could not beget material matter.`"
To William Jackson`'s objections he retorted that he believed God was a spirit,
and repeated several times over,
that "`Spirit can only beget spirit,`" "`that he was as confident of it,
as that he was standing there.`"
William Jackson further reasoned with him then,
as to the creation of the world by Him who is a spirit.
His answer was, "`What of the creation?`"
And when William informed him that he alluded to the account we have in the Bible,
he replied, "`Why, that`'s only Moses`'s account and on William Jackson asking,
"`Whether it was not a sufficient account for us to believe,`" his answer was,
"`It is but an allegory`" William Jackson left him with a heavy heart.

But where were the anointed Elders, where were the overseers of the flock,
in the different places where, during this long succession of years,
Elias Hicks was occasionally traveling among them, or even once only,
and preaching as he did?
How can we reconcile it with duty--how can we believe it possible--for
deeply experienced servants of Christ--watchmen on the walls--to
sit and hear His holy name reviled by such blasphemous declarations,
and yet keep silence, and thus let the people, young and old, drink it all in,
under the pretense of gospel ministry,
and suffer such a preacher to go away to other places unrebuked?
One would have supposed that some, at least, would have been constrained to cry out,
in very grief and shame, "`Oh! no, friends, this is not our doctrine,
neither has the Society ever held such abominable
sentiments--be not deceived--God is not to be mocked!`"

How came it to pass, that with perhaps two or three solitary exceptions, in Philadelphia,
in Baltimore, and on Long Island, during the latter part of his career,^
footnote:[By Gideon Seaman, an elder, and Solomon Underbill, a minister.
See Foster`'s Report, vol.
i, p. 161.]
it does not appear that this was done;
unless we consider this to have been done when a minister was led, as sometimes occurred,
to preach sound doctrine as an antidote to his unsound?
Why was he not arrested in his course, or at least publicly rebuked and checked,
and the evil thus averted?^
footnote:[On the occasion alluded to in Baltimore, during the Yearly Meeting,
his doctrine was publicly denounced by Dr. Dicks, of Alexandria, who had himself,
in early life, been an avowed deist,
but having been favored to experience a change of heart,
had become a religious man and a member among Friends,
and eventually an approved minister.]
There were several causes for it.

First.
The Society in general had been lulled into a state of ease and apathy,
and nothing had occurred of recent years to bring prominently into view
the necessity of "`contending for the faith once delivered to the saints,`"
by strictly maintaining the purity and soundness of our doctrines;
so that many were almost forgetting the lines of distinction between truth and error.

Second.
If at any time uneasiness was aroused in individual minds,
they saw that popular feeling was greatly excited in his favor,
and that any open opposition to his dogmas would at once stir up a commotion,
the extent and result of which could not be foreseen.

Third.
His erroneous sentiments were generally so mixed up with familiar truths, or,
as Joseph Hoag said,
so "`polished and dressed with recommendations of the beauty of morality,`"
that the covering was weakly allowed to counterbalance the filth;
and, tender for themselves and for the delinquent preacher,
rather than valiant for the unchangeable truth of the gospel,
they put by the seemingly dangerous duty,
and satisfied themselves with secret lamentations,
or with the conclusion that "`the servant of the Lord must not strive;`" thus making
their sweeping construction of the apostle`'s injunction wide enough to cover their
own dereliction of one of their weightiest duties as watchmen over the flock.

The evil seeds sown so widely over the country were not scattered in vain,
but produced an abundant crop of unsettlement and unbelief,
of discord and bitter contention.
Sound Friends in various places at length became aroused to a sense of
the danger which threatened to sweep the Society from its ancient foundation,
and strand it on hopeless shoals.
Looking around them,
they perceived a formidable array of persons enlisted already for the
promotion of the ascendency of the various new notions in the Society.
This array was composed in the first place,
of open and avowed advocates of Elias Hicks and of his characteristic views; secondly,
of a large number of merely nominal members,
who knew or cared little for any doctrines of religion,
but were recklessly determined to support the cause of free thinking, free acting,
and free preaching; thirdly, and sorrowful to relate,
of a class of members of honest intentions,
but who knew not their right hand from their left,
and were entrapped by the plausible insinuations
or false representations of relatives or acquaintances,
who scrupled not to assert that Elias Hicks was opposed and persecuted because he stood
for the views of the early Friends--an assumption which caught very many,
though it was as palpably false as it was illusory.^
footnote:[See T. Evans`'s Exposition of the Faith of Friends;
and an anonymous book of 359 pages,
8vo. entitled A Defence of the Christian Principles of the Society of Friends,
in Reply to Charges of the Followers of E. Hicks; published in Philadelphia in 1825;
which was written by Thomas Evans, assisted by Edward Bettle and Joseph Roberts.
These works, and others,
completely refuted the unfounded claim of the disciples of Hicks,
that they were supported by the writings of our early Friends; yet Samuel M. Janney,
in the 4th vol.
of his "`History of Friends,`" has not hesitated
to bring forward again the same unfounded allegation,
as if it had never been contradicted.
Doubtless there were many mistakes made in the zeal of that conflict,
and perhaps more or less erroneous sentiments put forth in some
of the many pamphlets which fluttered for a time in the storm;
several of which were issued in opposition to Hicks
by persons not belonging to the Society.
And it is also to be conceded,
that certain individuals who put themselves forward in the Society at this time,
were not grounded and settled in the truth,
and consequently did more harm than good by their efforts in Truth`'s cause.
Yet there is no justification in all this for Janney`'s assertion,
that the controversy was between ancient Quakerism as advocated by Hicks and his party,
and modern Gurneyism as held by his opponents.
For some further remarks on these illusory statements
in regard to the doctrines involved in this convulsion,
the reader is referred to the second volume of this work.]

This array of partisanship soon rose up wherever Elias Hicks travelled,
after his unsoundness became publicly known; and his partisans plainly showed,
by their boldness and determination,
that no fear of consequences was likely to stop them from their purpose
to carry everything before them and obtain the control of the Society.
Meetings for the transaction of the discipline were
thus greatly disturbed by them in many places,
and made occasions of dispute and acrimonious debate,
altogether at variance with the solemnity and waiting on the Lord for wisdom and strength,
which ought to characterize them in common with those for divine worship.

In the autumn of 1822,
it became known in Philadelphia that E. Hicks was likely soon to be in the city,
to visit two of its Monthly Meetings.
Some of the elders were acquainted with the result
of the interview between him and Joseph Whitall,
mentioned above, by which his erroneous sentiments, expressed in public,
had been supported by him in private.
Besides this, he had recently, at the Southern Quarterly Meeting held at Little Creek,
in Delaware, expressed views of the same nature,
which had greatly alarmed Ezra Comfort and Isaiah Bell,
a minister and an elder of Abington Quarter, who were then present.
These Friends, on their return homeward,
mentioned the circumstance to some members of the Select Meeting in the city,
who convened at the close of the Meeting for Sufferings;
Ezra Comfort desiring an opportunity of speaking with Elias.
Joseph Whitall and Richard Jordan likewise informed the ministers and
elders of the unsound sentiments which they had themselves heard him utter.

Two of the elders (Samuel P. Griffitts and Ellis Yarnall)
accordingly called on E. Hicks when he came to the city,
and informed him of E. Comfort`'s concern on his account,
and his wish to have an interview with him.^
footnote:[See Thomas Evans`'s Testimony in Foster`'s Report, vol.
ii, p. 377.]
E+++.+++ Hicks twice declined to meet him on the occasion.
As he was about entering upon a family visit to Green Street Monthly Meeting,
the elders generally now believed it to be their duty to attend further to the matter,
and endeavor to arrest the evil consequences which they
foresaw from the continued dissemination of such sentiments.
They, therefore,
requested him to give them a private opportunity for opening to him their uneasiness,
and imparting such counsel as might be requisite.
But he denied in general terms the allegations,
and persisted in refusing to afford any satisfactory opportunity.
At length some of his own adherents advising him to submit to it, he consented,
and proposed the meetinghouse in Green Street as the place.

When the elders arrived, instead of a private opportunity with him and his companion,
as they had expected, they found a considerable company assembled with him,
not only from Green Street Meeting, but from Wilmington, Byberry, and Darby.
They informed him that what they had desired was to have
a select private interview with himself and his companion;
that such a mixed company would frustrate the object in view;
and that they could not proceed to open their concern with those persons present.
But he would not consent to any such thing,
and they had to leave him without entering upon the matter.
Soon afterwards, on the 19th of the twelfth month, they addressed a letter to him,
informing him of their painful concern on his account,
mentioning the nature of the charges brought against him,
and reasoning with him on the inconsistency and impropriety
of his conduct in refusing to meet them as proposed.
This letter was signed by ten of the elders of Philadelphia, viz.: Caleb Peirce,
Thomas Stewardson, Ellis Yarnall, Richard Humphreys, Samuel Powell Griffitts,
Thomas Wistar, Edward Randolph, Israel Maule, Leonard Snowden, and Joseph Scattergood.

To it E. Hicks replied on the 21st, vaguely denying Joseph Whitall`'s account,
as "`not literally true,`" though he did not say it was not substantially so;
but that it was "`founded on his own forced and improper constructions`" of his words;
stating also that Ezra Comfort`'s charges were "`in the general incorrect,`" and offering,
as proof of this, a certificate signed by three of his adherents in the Southern Quarter.
He sheltered himself also behind his certificates--charged Ezra Comfort with
irregularity in not opening his dissatisfaction to him in the first place--and
concluded by saying that he had refused compliance with their "`requisitions,
as considering them arbitrary, and contrary to the established order of our Society.`"
This letter elicited another from the elders, dated 4th of first month, 1823, wherein,
amongst other expressions of their deep concern on his account,
and the irregularity of his conduct, they say:

On a subject of such importance the most explicit candor and ingenuousness,
with a readiness to hear, and to give complete satisfaction, ought ever to be maintained.
This the gospel teaches, and the nature of the case imperiously demands it.
As to the certificate which accompanied thy letter,
made several weeks after the circumstances occurred,
it is in several respects both vague and ambiguous; and in others,
though in different terms, it corroborates the statement at first made.

Viewing the whole subject, they express their sorrowful but unavoidable conclusion,
that E. H. was holding and disseminating principles at variance with those of the Society;
and conclude by saying,
that he having thus closed the door against their
brotherly care and endeavors for his benefit,
and the clearing of our religious profession,
they think the matter ought to claim the weighty attention of his friends at home.
About the same time another matter, arising from the same causes,
was claiming the care of the Meeting for Sufferings in Philadelphia,
in the regular discharge of its duty to see that all publications by our
members be consistent with the well-established faith of the Society.
A newspaper discussion had been carried on for some months at Wilmington, Del+++.+++,
involving the views of Friends on some important points of doctrine,
between a Presbyterian minister,
who took the name of "`Paul,`" and a member among Friends (Benjamin Ferris),
who signed "`Amicus.`"
The latter professed to speak in defence of Friends`' principles; but,
as the discussion proceeded,
it became evident that he was one of those who had
imbibed more or less of Socinian doctrines,
or of Elias Hicks`'s views.
The editor of the newspaper, after awhile,
issued proposals to publish by subscription the whole discussion in the form of a book.

It seemed now to be full time to clear the Society from accountability
in regard to the sentiments expressed ostensibly on its account;
and the Meeting for Sufferings, deliberating on the subject,
felt it incumbent to step forward and do what they could to prevent
the public from being led to suppose that the erroneous views thus
advocated were really the sentiments of Friends,
or that the author was in any way authorized to speak on behalf of the Society.
With this view they prepared (by a committee consisting of John Cox, Jonathan Evans,
Samuel P. Griffitts, John Comly, Samuel Bettle, Thomas Wistar,
and Thomas Stewardson) some short,
clear extracts from the writings of our early Friends respecting
the Scriptures and the divinity and atonement of Christ,
etc., and also a minute respecting the correspondence,
and requested the editor of the paper (the Christian Repository)
to publish the latter in the intended book,
if that should be printed.

This he declined to do, on the ground of its not being agreeable to his subscribers;
but he offered to print in his newspaper the minute, disclaiming all responsibility,
on the part of the Society, for the views thus brought forward in its name.
The Meeting did not feel that its own duty would by that means be fully discharged,
and (at the suggestion of Samuel P. Griffitts,
who mentioned that it seemed a pity that the extracts should be lost) concluded to print,
in pamphlet form,
a sufficient number of the extracts to supply a large distribution of them.
They recorded the extracts in full among their minutes, so as to go up for sanction,
as usual with the rest of their transactions, to the Yearly Meeting.
It was entirely within their province to issue such a publication themselves;
and it seems to be a matter of regret that they did not at once pursue that course,
instead of letting the pamphlets remain locked up
for several months waiting for the Yearly Meeting.
It is also to be regretted,
that in preparing these extracts the names of the authors
from whose works they were taken were not appended,
as this would have given to the collection less of the appearance of a
"`creed`"--so odious to the followers of E. Hicks--and would have thus
disarmed a considerable part at least of the factious opposition to them.
The following is a copy of these celebrated extracts,
so obnoxious to the followers of E. Hicks.
They were extracted from the writings of George Fox, William Penn, R. Barclay,
R+++.+++ Claridge, and from the Declaration of Friends in 1693.^
footnote:[See William Evans`'s Testimony in Foster`'s Report, vol.
ii, pp.
328 and 470.]

Extracts From the Writings of Primitive Friends,
Concerning the Divinity of Our Lord and Saviour, Jesus Christ.

At a Meeting for Sufferings held in Philadelphia, the 17th of the first month, 1823:

An essay, containing a few brief extracts from the writings of our primitive Friends,
on several of the doctrines of the Christian religion, which have been always held,
and are most surely believed by us, being produced and read; on solid consideration,
they appeared so likely to be productive of benefit,
if a publication thereof was made and spread among our members generally,
that the committee appointed on the printing and distribution of religious books,
are directed to have a sufficient number of them struck off, and distributed accordingly;
being as follows:

We have always believed that the Holy Scriptures were written by divine inspiration,
that they are able to make wise unto salvation, through faith which is in Christ Jesus:
for, as holy men of God spake as they were moved by the Holy Ghost,
they are therefore profitable for doctrine, for reproof, for correction,
for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works.
But they are not or can not be subjected to the fallen, corrupt reason of man.
We have always asserted our willingness, that all our doctrines be tried by them;
and admit it as a positive maxim.
That whatsoever any do (pretending to the Spirit) which "`is contrary to the Scriptures,
be accounted and judged a delusion of the devil.

We receive and believe in the testimony of the Scriptures,
simply as it stands in the text--There are three that bear record in heaven, the Father,
the Word, and the Holy Ghost, and these three are one.
We believe in the only wise, omnipotent, and everlasting God,
the creator of all things in heaven, and earth,
and the preserver of all that He hath made, who is God over all blessed forever.
The infinite and most wise God, who is the foundation, root, and spring of all operation,
hath wrought all things by His eternal Word and Son.
This is that Word that was in the beginning with God, and was God;
by whom all things were made, and without whom was not any thing made that was made.
Jesus Christ is the beloved and only begotten Son of God, who, in the fulness of time,
through the Holy Ghost,
was conceived and born of the virgin Mary--in Him we have redemption through His blood,
even the forgiveness of sins.
We believe that He was made a sacrifice for sin, who knew no sin;
that He was crucified for us in the flesh,
was buried and rose again the third day by the power of His Father for our justification,
ascended up into heaven, and now sitteth at the right hand of God.

As then that infinite and incomprehensible Fountain of life and motion,
operateth in the creatures by His own eternal word and power,
so no creature has access again unto Him but in and by the Son,
according to His own blessed declaration, "`No man knoweth the Father but the Son,
and he to whom the Son will reveal Him.`"
Again, "`I am the way, the truth and the life:
no man cometh unto the Father but by Me.`" Hence
He is the only Mediator between God and man:
for having been with God from all eternity, being Himself God,
and also in time partaking of the nature of man;
through Him is the goodness and love of God conveyed to mankind,
and by Him again man receiveth and partaketh of these mercies.

We acknowledge, that of ourselves we are not able to do anything that is good;
neither can we procure remission of sins or justification by any act of our own;
but acknowledge all to be of and from His love,
which is the original and fundamental cause of our acceptance.
"`For God so loved the world, that He gave His only begotten Son,
that whosoever believeth in Him should not perish, but have everlasting life.`"
We firmly believe it was necessary that Christ should come, that,
by His death and sufferings, He might offer up Himself a sacrifice to God for our sins,
who His own self bare our sins in His own body on the tree;
so we believe that the remission of sins which any partake of,
is only in and by virtue of that most satisfactory sacrifice, and no otherwise.
For it is by the obedience of that one,
that the free gift is come upon all to justification.
Thus Christ by His death and sufferings hath reconciled us to God,
even while we are enemies; that is, He offers reconciliation to us;
and we are thereby put into a capacity of being reconciled.
God is willing to be reconciled unto us, and ready to remit the sins that are past,
if we repent.

Jesus Christ is the intercessor and advocate with the Father in heaven,
appearing in the presence of God for us, being touched with a feeling of our infirmities,
sufferings, and sorrows; and also by His Spirit in our hearts,
He maketh intercession according to the will of God, crying Abba, Father.
He tasted death for every man, shed His blood for all men,
and is the propitiation for our sins; and not for ours only,
but also for the sins of the whole world.
He alone is our Redeemer and Saviour, the captain of our salvation, the promised seed,
who bruises the serpent`'s head; the alpha and omega, the first and the last.
He is our wisdom, righteousness, justification, and redemption;
neither is there salvation in any other; for there is no other name under heaven,
given among men, whereby we may be saved.
As He ascended far above all heavens, that He might fill all things,
his fulness cannot be comprehended or contained in any finite creature,
but in some measure known and experienced in us, as we are prepared to receive the same;
as of His fulness we have received grace for grace.
He is both the word of faith and a quickening spirit in us,
whereby He is the immediate cause, author, object,
and strength of our living faith in His name and power,
and of the work of our salvation from sin and bondage of corruption.

The Son of God cannot be divided from the least or lowest
appearance of His own divine light or life in us,
no more than the sun from its own light:
nor is the sufficiency of His light within set up or mentioned in opposition to Him,
or to His fulness considered as in Himself or without us;
nor can any measure or degree of light received from Christ,
be properly called the fulness of Christ, or Christ as in fulness,
nor exclude Him from being our complete Saviour.
And where the least degree or measure of this light and life of Christ within,
is sincerely waited in, followed, and obeyed,
there is a blessed increase of light and grace known and felt; as the path of the just,
it shines more and more until the perfect day: and thereby a growing in grace,
and in the knowledge of God, and of our Lord and Saviour Jesus Christ,
hath been and is truly experienced.

Wherefore we say, that whatever Christ then did, both living and dying,
was of great benefit to the salvation of all that have believed, and now do,
and that hereafter shall believe in Him unto justification and acceptance with God:
but the way to come to that faith,
is to receive and obey the manifestation of His divine Light and grace in the conscience,
which leads men to believe and value, and not to disown or undervalue Christ,
as the common sacrifice and mediator.
For we do affirm, that to follow this holy light in the conscience,
and to turn our minds, and bring all our deeds and thoughts to it, is the readiest,
nay the only right way, to have true, living, and sanctifying faith in Christ,
as he appeared in the flesh; and to discern the Lord`'s Body, coming,
and sufferings aright,
and to receive any real benefit by Him as our only sacrifice and mediator;
according to the beloved disciple`'s emphatical testimony, "`If we walk in the light,
as He (God) is in the light, we have fellowship one with another,
and the blood of Jesus Christ His Son cleanseth us from all sin.`"

By the propitiatory sacrifice of Christ without us, we, truly repenting and believing,
are, through the mercy of God,
justified from the imputation of sins and transgressions that are past,
as though they had never been committed: and by the mighty work of Christ within us,
the power, nature, and habits of sin are destroyed; that as sin once reigned unto death,
even so now grace reigneth through righteousness unto eternal life,
by Jesus Christ our Lord.

Signed on behalf of the Meeting,

Jonathan Evans, Clerk.

When the minutes of the Meeting for Sufferings came in due
course to be read in the Yearly Meeting of 1823,
the fact of these Extracts forming a part of them,
and thus being proposed for the sanction of the Yearly Meeting,
raised a great storm against them on the part of Elias Hicks`'s adherents.
Several of them disapproved of the doctrines as stated in the Extracts,^
footnote:[See S. Bettle`'s Testimony, in Foster`'s Report, vol.
i, p. 72.]
but the main ostensible ground of the opposition to them was,
that this was an attempt on the part of the Meeting
for Sufferings to "`impose a creed`" on the Society,
and that by and by every member would be compelled to subscribe to it.
The excitement was such that the meeting adjourned till the next morning.
A proposal was then made by the opponents of the Extracts,
that they should be expunged or stricken from the minutes of the Meeting for Sufferings.
But this was firmly objected to,
as it would have the appearance and effect of a disavowal of the doctrines therein mentioned,
which were no other than those of the ancient Friends
who were concerned in the establishment of the Society.
The opposition continuing very vociferous, Samuel Bettie,
the clerk of the Yearly Meeting, in order, in some way, to settle the question,
at length proposed, "`to avoid both difficulties by simply suspending the publication,
not taking it off the minutes, and not circulating the pamphlets,
but leaving the subject.`"

This compromise was acquiesced in, and the matter so settled.
But the advantage gained by this important concession tended to
encourage the promoters of the new views to further assaults,
not only on the Meeting for Sufferings, but also on the meetings of ministers and elders;
and the next three or four years exhibited various attempts made
by them to alter the constitution of each of those meetings,
by urging arbitrary changes of the representation in the former,
and likewise in the appointments to the station of Elder,
in a manner believed to be hitherto unknown in the discipline or practice of Friends.
This was in the hope of obtaining for their party a controlling
influence in those departments of the Society.^
footnote:[The adherents of this party endeavored in various ways
to stir up popular feeling against the Elders of Philadelphia,
and the members of the Meeting for Sufferings; publishing scurrilous pamphlets,
with caricatures; one, for instance, representing Samuel Bettle,
the clerk of the Yearly Meeting, with a balance in his hand,
taking the weight of Jonathan Evans in one scale,
against a dozen or so of Hicksites in the other;
one representing a "`hole in the wall`" (Ezekiel 8:7-12),
disclosing what the Elders were doing in the dark;
and one representing Jonathan Evans (clerk of the Meeting for Sufferings),
sitting at a desk preparing "`the Creed,`" with a yoke and fetters hanging near him,
etc.]
In Monthly Meetings, where they had the control, they went to great lengths.
Thus, Ezra Comfort and Isaiah Bell were disowned by them for the part they had
taken in making known to the elders in Philadelphia the unsound doctrines
preached by Elias Hicks at the Southern Quarterly Meeting in 1822.

These Friends, however, were afterwards restored by appeal.
Leonard Snowden and Joseph Scattergood (son of Thomas Scattergood, the minister),
elders of Green Street Monthly Meeting, in Philadelphia, were, in 1824,
declared out of unity by that meeting,
on account of their opposition to the doctrines and course of Elias Hicks.
The subject was carried to the Select Quarterly Meeting,
and several months were spent by a committee in vainly endeavoring to settle the difficulty;
during which time Joseph Scattergood was taken away by death.
The Monthly Meeting persisted in its position, and,
finding that the committee was about to counsel them
adversely to their action in the case,
undertook summarily to displace the survivor, Leonard Snowden,
from his station as an Elder.
On the committee reporting this to the Select Quarterly Meeting,
the case appeared to have assumed a form in which the consideration
of the Quarterly Meeting for discipline became needful,
and the Select Meeting accordingly referred the matter to its care.
Leonard Snowden also appealed to the Quarterly Meeting,
believing that the due maintenance of our Christian
principles and discipline were involved in the case;
that it was unprecedented, and likely to prove a dangerous example,
subversive of the peace and well-being of the Society.

His right of appeal was denied by the Green Street members,
on the ground that though they had by minute declared him to be in such
a degree of disunity as to have lost his service in the select meeting,
yet they had not actually disowned him from membership.
They seemed to lose sight of the fact,
that the discipline gives the right of appeal to members who may apprehend
themselves "`aggrieved,`" without limiting it to cases of disownment;
and according to the general understanding among Friends,
to declare a person out of unity by a minute of the meeting,
has been considered nearly if not quite equivalent to a disownment.
It deprives him at least of the liberty of being employed in any service of the church,
or of his sentiment in meetings for discipline being received as having any weight.
When the appeal came to be considered in the Quarterly Meeting,
the members of Green Street Meeting clamorously opposed it, some of them speaking,
during one sitting, fifteen times or more to the case,
and one man was known to speak as many as thirty-two times;
so that the sittings of the Quarterly Meetings were
often greatly protracted by their clamorous harangues.^
footnote:[Thomas Evans`'s testimony in Foster`'s Report, vol.
ii, p. 381]

After much discussion from quarter to quarter, for seven Quarterly Meetings,
it was concluded in the fifth month, 1826,
to carry up the question to the Yearly Meeting, for its advice and assistance,
as a case of difficulty; and as the Yearly Meeting for that year had then just passed,
the matter was thus delayed for another year.
But the disturbances in the Yearly Meeting of 1827 were such,
that the case could not receive careful and deliberate adjustment,
and it was referred back to Philadelphia Quarterly Meeting.
That meeting accordingly appointed a committee for the deliberate
examination and consideration of the case;
and at the next Quarterly Meeting (in the eighth month) this committee reported,
clearing Leonard Snowden from any just cause of disunity
or want of qualification for service in the church,
and charging Green Street Monthly Meeting (which had, however,
in the meantime gone off in the separation) with acting in the
case inconsistently with the provisions of the discipline.
L+++.+++ Snowden was of course now restored to his place in the church,
and confirmed in the station which he had faithfully occupied for many years.

The same Monthly Meeting of Green Street, in 1826,
summarily displaced two of their female elders, Mary Taylor and Ann Scattergood,
on the same ground as they had against L. Snowden and J. Scattergood.
But these friends appealing to the Quarterly Meeting,
the action of the Monthly Meeting was, in the second month, 1827,
declared irregular and annulled.
The withstanding of an assault upon the regular permanent constitution
of the Meeting for Sufferings made by the Southern Quarterly Meeting
(in which the adherents of E. Hicks had the control),
tended afresh to fan the embers of confusion and discord into flames.
In 1826, that Quarterly Meeting, at the instigation of Abraham Lower, of Philadelphia,
undertook to change its representatives in the Meeting for Sufferings,
who were mainly opposed to the new views,
and therefore not satisfactory to the controlling party.
The discipline recognized no such practice as changing the representation,
unless on account of death, resignation, or continued absence from the meetings;
and arbitrary changes had not been known since that
meeting was established on its then present basis,
especially without any disqualifying cause assigned.

The Yearly Meeting had already, in 1825,
refused to accede to a proposal from Bucks Quarterly Meeting,
to alter the discipline so that all important appointments (by
which they meant chiefly elders and members of the Meeting for
Sufferings) should be made only for a limited time.
But in this instance a new set of representatives was peremptorily appointed,
without alleging any cause for dismissing the old ones,
and even without informing all of them (if any of them) of their dismissal.
When the new representatives presented themselves,
the meeting declined to recognize them,
considering the matter altogether unexampled and out of order;
but after considering the case for three months,
a committee was appointed to confer with the Southern Quarterly Meeting on the subject,
and inform them of the reasons for their not consenting to the new nomination.
The disaffected in that Quarterly Meeting were highly offended.

At the Meeting for Sufferings in the third month, 1827, this committee reported,
that they had attended the Quarterly Meeting held at Little Creek, Delaware,
and opened to them the difficulty of the case,
as it was viewed in the Meeting for Sufferings;
assuring the Quarterly Meeting that the Meeting for Sufferings did not assume the privilege
of interfering with the appointment of representatives--that the right of the Quarterly
Meeting to select such friends as they might deem suitable for the service,
and also to fill all vacancies that might from time to time occur, was not questioned.
The Meeting for Sufferings never had attempted to interfere on this subject--the difficulty
that presented on the present occasion arose from a belief that no vacancy had occurred.
The discipline establishing the Meeting for Sufferings directs,
that twelve friends shall be appointed by the Yearly Meeting,
and four out of each of the quarters; the only cases which constitute a vacancy,
and which call for a reappointment are death, resignation, or neglect of attendance;
and the uniform practice of society for seventy years,^
footnote:[In the very early times of the Meeting for Sufferings in Pennsylvania,
it is believed there were instances of changes made by Quarterly Meetings.
See Foster`'s Report, vol.
ii, p. 49.]
has been in accordance with the discipline,
which could only be altered by the Yearly Meeting;
for we apprehended it must appear manifest,
that some fixed general rule was indispensable,
or otherwise each of the Quarterly Meetings might change the discipline or practice,
as from time to time, circumstances might induce them to think a change desirable.

After some further observations,
the committee concluded with the information that the Quarterly
Meeting was informed that the Meeting for Sufferings,
in view of the difficulty,
and yet desirous of avoiding any collision with a Quarterly Meeting,
had appointed this Committee,
if they should think proper to separate a committee for the purpose,
to enter into a full consideration of the whole subject,
with a hope that such a conference might result in
some conclusion which would be to mutual satisfaction.
The Quarterly Meeting, however, say they, declined appointing a committee,
or in any way explaining their views of the subject.
This report being entered on the minutes,
the matter thus stood at the time of the Yearly Meeting in the fourth month, 1827.

Elias Hicks made another visit to Philadelphia in the winter of 1826,
and fully confirmed the apprehensions which his previous visits had excited.
His presence also doubtless tended to animate his adherents in the pursuit
of those measures which a few months afterwards resulted in the separation.
The spring of 1827 found the elements for this work actively in operation.
The Society was like a volcano, smoking and inwardly thundering,
and almost ready to burst forth into flame.
Bucks Quarterly Meeting, in which the Hicks party predominated,
prepared a proposal to go to the Yearly Meeting, for a change in the discipline,
so that Elders might be removed by Monthly Meetings "`whenever
it might appear that their service in that station has ceased to
promote the best interests of the Society;--`" in other words,
whenever a Monthly Meeting might, with or without just cause, be desirous of a change.
And Abington Quarter, in which the same influence prevailed, prepared a similar proposal,
relative to the appointment of Elders, and members of the Meeting for Sufferings,
with a view that such appointments be made for a limited time.

John Comly, a minister of Byberry, near Philadelphia,
and occupying the position of assistant clerk to the Yearly Meeting,
travelled over a great portion of the country within the limits of the Yearly Meeting,
under the profession of ministerial service,
and in various places held private meetings with certain of the members,
in order to bring about a division of the Society.
He himself acknowledged afterwards to Samuel Bettle,^
footnote:[See S. Bettle`'s Testimony, in Foster`'s Report, vol.
i, p. 68.]
that he had held about forty such meetings, and with that intent^
footnote:[John Comly, in his journal,
mentions a considerable number of these conferences, the object of which, he says,
was for the purpose of making "`a quiet retreat,`" and "`becoming
distinct and separate as a society`" (p. 314) and (p. 316),
"`a separation of the contending parties into two distinct religious bodies.`"
He speaks of the disturbance in the Society as having been caused
and promoted by a "`spirit or image of jealousy`" and "`stretch
of arbitrary power,`" first developed in New England (p. 303),
and "`denunciations against infidelity and other imagined
absurdities,`" and fully acknowledges a difference of doctrine,
but nowhere attempts to refute the charges brought against him and his associates,
of a departure from the faith of the gospel.
He speaks of his partisans as "`little lambs`" (p. 335),
and "`afflicted lambs of Christ`" (p. 336),
but acknowledges (p. 335) that at the ensuing Quarterly Meeting of Abington,
held at Horsham,
there was "`a scene of apparent disorder--when many voices
simultaneously resounded from all parts of the house,
in vindication of rights and privileges dear to every friend of peace, of truth,
and of order.`"
Of course, these "`many simultaneous voices`" were bleatings from the "`little lambs!`"]

It was deemed by the party highly desirable to take measures
to secure the choice of a clerk to the coming Yearly Meeting,
of their own sentiments,
so as to enable them to control the action of the
meeting in accordance with the new views.
If this could be accomplished,
they trusted that they would have gained the wide road to success.
But if not, many of the leaders at least were resolved on a separation,
in accordance with John Comly`'s contrivances.
As the nomination of a clerk would devolve, according to custom,
on the representatives as a body, it was seen that an important point would be,
that their party should preponderate in numbers when the representatives should meet,
respecting the nomination.
Abington and Bucks Quarters accordingly each doubled their usual number of representatives,
and the Southern Quarter increased theirs by one half;
while the Quarters where the party did not control affairs, made no such increase.
This was the condition of things on the approach
of the Yearly Meeting of Philadelphia in 1827.

The Select Yearly Meeting, or Yearly Meeting of Ministers and Elders,
assembled as usual on the seventh-day of the week
immediately preceding the General Yearly Meeting,
viz., on the 14th of the fourth month.
On attending to the Answers to the Queries addressed to Meetings of Ministers and Elders,
it was found that Philadelphia Quarter,
in its answer to the second query--"`Are ministers sound in word and doctrine,
and careful to minister in the ability which God gives?`"--had
mentioned that unsoundness existed in the ministry among them,
and that one of its branches had stated "`that much pain and exercise
had been experienced on account of persons coming among them,
promulgating sentiments or doctrines,
tending to lay waste a belief in our Lord and Saviour Jesus Christ.`"
The meeting being brought under much concern on this account, it was,
at the suggestion of William Jackson, after solid consideration,
concluded to appoint a committee, to visit the Select Quarterly and Preparative Meetings,
and endeavor "`to extend such advice and assistance as might conduce
to the health of the body and the welfare of individuals.`"

There was opposition made to this appointment by some;
but it settled as the mature and genuine judgment of the meeting.
At the adjourned meeting, however, on the next fourth-day, the 18th,
John Comly made an effort to have the appointment rescinded,
and finding that his attends were of no avail,
he rose soon after the subject was dismissed,
and bade the meeting "`an affectionate farewell.`"^
footnote:[William Evans`'s Testimony, in Foster`'s Report, vol.
ii, p. 331.]
The Yearly Meeting assembled, in due course, on second-day morning,
the 16th of the month, and entered on its business as usual,
Samuel Bettle and John Comly being at the table as
the clerk and assistant clerk of the previous year.
At the close of the morning sitting, the representatives, according to custom,
remained together in the same house as a committee
to consider of a choice for clerk and assistant clerk,
to propose to the Yearly Meeting in the afternoon.
There were one hundred and sixty-three representatives appointed,
and they were nearly all present, being thirty-three more than the usual number,
on account of the additions made by the three Quarterly
Meetings where the Hicks party predominated.

It was usual, after a pause, to deliberate first on the question,
whether it were desirable to make any change, by releasing the former clerk.
But almost as soon as the representatives had got together,
and before they were quietly settled,
some one of the party promptly proposed the name of John Comly for clerk.
This was objected to by others, as being premature,
before they had decided whether any change should be proposed.
John Comly`'s name, however, was urged by a number with great earnestness,
while others expressed their preference for the former clerk,
as no objections had been stated against Samuel Bottle,
who had been nominated the previous year, without dissent;
and especially as it was well known that John Comly had been going up and down the country,
holding private meetings to prepare the way for a separation;
a course which formed an insuperable objection to
him for that service in the minds of many friends.
The advocates of John Comly clamorously asserted that they were the majority,
and therefore ought to sway the choice of the committee.

The others doubted the assertion,
but insisted that it had never been the practice of Friends
to be governed by mere majorities in religious matters,
and that in this case there would be a particular injustice
in being urged to that unusual mode of choice,
inasmuch as several of the Quarterly Meetings had so largely increased their representation,
while the rest had no more than usual.
The party urged, however, that it should be settled by a vote, and Abraham Lower,
who had been throughout very active on behalf of John Comly,
soon called on a certain John Watson to go to the table,
and draw up a minute proposing him for the service.
John, feeling somewhat discouraged at the strength of the opposition to such a course,
did not seem disposed to obey the summons,
and excused himself from so serious an undertaking.
Abraham then, still bent upon his purpose,
proposed that those who were in favor of John Comly
should go over to the eastern side of the house.
He rose, and took a few steps in that direction, and a few others rose also.

But the measure was so decidedly opposed by a considerable number of Friends,
that this effort also failed.
One member urging the manifest injustice of it under the
present circumstances of increased numbers from Abington,
Bucks, and the Southern Quarter, and intimating that if they were to be urged to vote,
they ought, in the first place, to decide which of them had a right to vote,
and who had not; this excited some of them from those three Quarterly Meetings,
and especially one Cephas Ross, of Bucks Quarter; who made a pretty long harangue,
and cried out, more than once, in an irreverent manner,
that "`he had his commission from God Almighty, and would give it up to no man!`"
Friends were shocked at these and other such declarations, and John Cox, of Burlington,
rose and remarked,
that "`there was a degree of decency and respect due to one another on all occasions,
both in civil and religious society,
and it ought to be observed;`" adding further remarks
on the impropriety of disregarding this duty.
Abraham Lower became greatly roused at finding that Friends were
neither to be led nor driven into a compliance with his measures,
and began to reflect on those opposed to him,
as "`the few who wished to rule over the many.`"
Several hours were thus exhausted in altercation,
and it became very evident that no united agreement could be arrived at.
It was at length proposed that John Cox should report to the Yearly Meeting,
"`that way did not open in the minds of the representatives to release Samuel Bettle.`"

But this was objected to,
several of John Comly`'s advocates saying that in their minds way did open for it.
The proposal was therefore modified, so that John Cox should simply report,
"`that the representatives could not agree on any name to offer to the meeting as clerk.`"
This proposition gaining approval even from some of John Comly`'s friends,
Abraham Lower became alarmed, and twice called out to them,
"`to take care what they were about; for if no name was proposed to the Yearly Meeting,
Samuel Bettle would be the clerk as a matter of course.`"
This, however, seemed to be all the report that could be made,
and John Cox was requested to convey it on behalf of the representatives.
They were about to disperse, when Abraham Lower a third time represented to his party,
"`that if no name was reported,
S+++.+++ Bettle would be the clerk;`" and called upon all those
who were favorable to the appointment of John Comly,
to come up to the clerk`'s table and sign a report to that effect.
He with perhaps eight or ten others^
footnote:[See Foster`'s Report.
Cephas Ross said about twenty.]
went up accordingly to the table, and a certain Marden Wilson began to write.
But it was a little too late.
The representatives were then dispersing.
The hour for the afternoon sitting of the Yearly
Meeting had very nearly if not quite arrived,
and many were waiting to come in;
and as some of the representatives opened the door to go out,
the members began to flow into the house,
so that those who were usurping the clerk`'s table quickly withdrew,
and this scheme also was baffled.^
footnote:[For this whole proceeding, see Testimony of William Evans and John Paul,
in Foster`'s Report, vol.
ii, pp.
332 and 339.]

Soon after the Yearly Meeting became settled for the afternoon sitting,
John Cox reported, on behalf of the representatives,
that they had not been able to agree on any name to propose to the meeting as clerk.
Several proposals followed this announcement,
but William Jackson rose and mentioned that he had attended
Yearly Meetings since the year 1767 (now sixty years),
and the practice had been that the old clerks continued in service
until new names were brought forward and agreed to.
Many friends expressed approval of such a course in the present instance;
but others opposed it,
and some of these suggested that the present clerks should merely serve for that afternoon,
and the representatives should be directed to meet again,
and determine the question by the majority.
This of course was firmly objected to,
and no probability appeared of the representatives coming
nearer to agreement than they had already done.
The proposal for the old clerks to continue to act for the meeting was largely approved,
and was at length acquiesced in even by some of John Comly`'s advocates.

A short pause at length occurring,
Samuel Bettle made a minute desiring the former clerks to continue to serve the meeting.
As soon, however, as it was read, it was strongly opposed by the Hicks party;
but at length the opposition ceased, and John Comly expressed his willingness,
"`in condescension to the views of his friends,`" to act as assistant clerk.
The usual business then went on for a short time,
and the meeting adjourned to the next morning; when John Comly rose,
and declared that there were two irreconcilable parties,
and that he could not conscientiously serve a meeting so circumstanced as its organ.
He then proposed an adjournment of the Yearly Meeting,
without any time mentioned for its ever reassembling.
So strange and extreme a measure met with but feeble support,
and John Comly finally acquiesced in the desire, expressed by many,
that he should resume his seat at the table.
After this, he acted as assistant clerk without further difficulty,
and the business of the meeting went on as usual,
his adherents taking part in some of the matters that came before it,
especially in promoting a subscription to be raised through the subordinate meetings
to supply funds for the removal of several hundred colored people from Carolina,
where they were in danger of being sold as slaves unless speedily removed from the State.

On third-day afternoon Ann Jones, of Stockport, England,
came into the men`'s meeting by permission, and, after a solemn pause,
kneeled in supplication, commencing with the words of the eightieth Psalm: "`Give ear,
O Shepherd of Israel, thou that leadest Joseph like a flock,
thou that dwellest between the cherubim,
shine forth!`" and interceded with much earnestness
for the ancient and honorable fathers in the Church,
for the strong men in Christ Jesus, for the young men in our Israel,
and for the children in the Lord`'s house--then on behalf of such as had
been in some degree beguiled by the great adversary of their souls,
and in measure entangled in his snares,
but as regarded whom a door of mercy still remained open--that
such might be prevailed on to close in with the offered salvation,
before it might be too late, and every avenue closed up.
Soon afterward, standing up, she was largely engaged in testimony,
addressing the state last alluded to in her prayer, with much weight,
and solemnly warning them to flee from the temptation; to flee for their very lives;
to beware of the stratagem of the emissaries of Satan,
those who were endeavoring to persuade them that there was no devil,
while at the same time he was holding fast in his embrace
many of those who were thus denying his existence.
After many other observations, she said,
that leaving those who were rebellious and hardening
the heart and stiffening the neck against God,
to their own delusions and vain imaginations,
and to the just judgment of a righteous God,
she wished to address herself to the faithful followers of Jesus Christ,
those who loved Him and his cause more than their own lives,
and who desired above all things to be found faithful to Him, standing in their lot,
and filling up with holy diligence the appointed measure of duty and suffering.

She addressed also the fearful and the faint with sweet encouragement,
exhorting them to trust in the Lord, and cast all their care on him, who cared for them,
and whom they would find all-sufficient for his own cause in every storm and conflict.
To the worthy heads of the tribes who were standing in the forefront of the battle,
and who had to endure revilings and reproaches for the name of
Christ and for their faithfulness and uprightness to Him,
she spoke in a very consoling manner, reciting the beautiful passage from Genesis,
where Jacob pronounced this blessing on his son Joseph: "`Joseph is a fruitful bough,
even a fruitful bough by a well, whose branches run over the wall.
The archers have sorely grieved him, and shot at him, and hated him;
but his bow abode in strength,
and the arms of his hands were made strong by the hands
of the mighty God of Jacob--(from thence is the Shepherd,
the Stone of Israel)--even by the God of thy father, who shall help thee,
and by the Almighty, who shall bless thee.`"
She then addressed some who had known what it was to be separated from their brethren,
assuring them of her faith and belief that they would,
as they stood fast in their fidelity to Christ Jesus and his holy cause,
experience that blessing to be fulfilled which was poured "`on the head of Joseph,
and on the crown of the head of Him that was separate from his brethren.`"
To the humble, faithful disciples of every class,
she had much of a precious and consoling nature to hand forth,
and concluded with a recital of some sublime passages of Holy Scripture,
strikingly portraying the care and protection of the Almighty over his Church and people.
Almost as soon as she had taken her seat, one of the Hicks party, in a taunting manner,
exclaimed: "`Resist the devil, and he will flee from thee!`"
And another called out: "`Friends, beware of the leaven of the Pharisees!`"
She sat very quietly for a few moments, and then withdrew.^
footnote:[The above account of Ann Jones`'s communication
is taken from a manuscript which,
there is reason to believe, was written originally by Thomas Evans.]

The Hicks party held several private meetings among themselves during that week,
and matured their plans for a separation.
On the evening of sixth-day, the 20th,
they held a large assemblage in Green Street meetinghouse,
and agreed on an address to the members of the Yearly Meeting.
This address contained plausible professions of admiration
of the faithfulness of our early Friends,
and of their noble stand for "`the glorious truth,
that God alone is the sovereign Lord of conscience.`"
Then, coming to our own days,
they thus expressed their idea of the grievances they were subjected to:

We are constrained to declare, that the unity of this body +++[+++the Yearly Meeting]
is interrupted; that a division exists among us,
developing in its progress views which appear incompatible with each other,
and feelings averse to a reconciliation.
Doctrines held by one part of society, and which we believe to be sound and edifying,
are pronounced by the other part to be unsound and spurious.
From this has resulted a state of things that has proved destructive of peace and tranquillity,
and in which the fruits of love and condescension have been blasted,
and the comforts and enjoyments even of social intercourse greatly diminished.
Measures have been pursued which we deem oppressive,
and in their nature and tendency calculated to undermine and destroy those benefits,
to establish and perpetuate which should be the purpose of every religious association.

After some further remarks, respecting order, discipline, and forbearance,
which (if they had but known it) reflected back with double force upon their own conduct,
they said:
"`It is under a solemn and deliberate view of this painful
state of our affairs that we feel bound to express to you,
under a settled conviction of mind, that the period has fully come,
in which we ought to look towards making a quiet retreat from this scene of confusion;
and we therefore recommend to you deeply to weigh the momentous subject,
and to adopt such a course as truth, under solid and solemn deliberation, may point to,
in furtherance of this object,
that our Society may again enjoy the free exercise of its rights and privileges,`" etc.
This paper was signed on behalf of the meeting by John Comly^
footnote:[What were the views entertained by John Comly in regard to the "`divinity
of Christ,`" and the atoning efficacy of his "`blood,`" may be gathered from
what he has himself acknowledged in the Journal of his Life,
printed since his decease (page 350),
in relating his answers to certain questions put to him
at the close of a meeting in New Jersey in 1827:
"`At the close a person advanced forward to speak to us, and, with apparent diffidence,
said, he wished to ask a question, which he did, thus addressing himself to me:
'`Do you believe that Christ was the Son of Joseph or the Son of God?`' I answered:
'`The latter, undoubtedly.
I never had a doubt of the Divinity of Christ.
I have no idea of a Christ that is the son of Joseph.`' He replied:
'`Then you believe that we have access to God through his blood,
do you?`' '`Certainly,`' said I. '`Very well,`' said he,
'`I am fully satisfied.`' He was called +++[+++adds John Comly+++]+++ a Methodist minister,
and when he went out, he told others he was perfectly satisfied.
Whatever external or material ideas he attached to the terms of his question,
the answers were given with reference to the spirituality of Christ,
and the blood that cleanseth from all sin, which cannot be material blood,
because matter cannot cleanse spirit,
and the soul that is defiled by sin needs a spiritual cleansing,
through which it finds access to God.`"
Thus Comly allowed this serious inquirer to go away imposed upon by an insidious answer
according to his own confession!
{footnote-paragraph-split}
On another occasion (Journal, p. 395), in answer to another inquirer,
he discarded any confidence in the "`outward blood;`"
and in reference to the atonement said,
"`I told him I could not find the term '`propitiatory sacrifice`' in the Scriptures,
and the application of such a term to the death of
Jesus on the cross I thought unwarrantable,`" etc.
On page 400, etc. is found an elaborate attempt to reason away a belief
in the existence of "`the Devil;`" and on page 424 he says,
"`Whenever the laws of animal nature, or the lusts of the flesh,
prompt to the pursuit of animal happiness,
beyond the limitations of this superior law of the mind or soul,
its restraining or controlling power is felt by the obedient mind;
and a cross or death is known to the first inclination
or motion of desire for what is beyond this boundary.
This is the death of Jesus to sin, which man is called to imitate.`"
Might not such doctrines as these, with the more open avowals of Elias Hicks,
sanctioned by the same John Comly and by the party generally,
rightly be "`denounced as unsound and spurious`" by all true Christians?]
and nine others.
It places the ground of difference distinctly on doctrines--"`doctrines,
which we believe to be sound and edifying,
are pronounced by the other part to be unsound and spurious.
From this has resulted a state of things,`" etc.

At the meeting on sixth-day evening, when they agreed on the above document,
Charles Evans, then a young man, son of Jonathan Evans,
was present with a view to see for himself what they were about.
His presence, it appears, was not much noticed in the dusk of evening,
and in such a crowd as was then assembled, according to J. Comly`'s estimate
(Journal, p. 333) about seven or eight hundred.
At the sitting on seventh-day morning,^
footnote:[That morning I attended the Yearly Meeting for the first time,
having landed from Liverpool the previous evening.
It was the last sitting,
and made a memorable impression on a mind unaccustomed to such scenes as then presented.
It was the first time I had ever heard the divinity
of Christ called in question in a Friends`' meeting,
and this was by Abraham Lower.]
I think after attending to the epistles addressed to other Yearly Meetings,
a proposal was brought in from the Women`'s Meeting,
suggesting for the consideration of the Men`'s Meeting the appointment
of a committee to visit the Quarterly and Monthly Meetings,
for their strength and encouragement.
This proposal greatly roused again the heated feelings of the Hicks party,
who saw in it a thwarting, to some extent at least, of their sweeping prospects.
They came out clamorously against it,
several of them often on their feet speaking simultaneously,
and seemed bent on bearing down all advocacy of it by noise and tumult.
Instead of being willing to hear those on the other side of the question
with the same forbearance that was exercised toward themselves,
they would endeavor to drown the voices of Friends by clamor, coughing,
and other needless or rude noises.

Many Friends became much discouraged,
and were almost ready to give up the proposed appointment, however desirable,
seeing the tumultuous state the meeting was in.
But after the Hicks party had nearly exhausted themselves, Charles Evans rose,
and mentioned to the meeting what had occurred the previous evening,
and that many of those who had now opposed the appointment of the
committee were among the company who had held this private meeting,
and drawn up an Address, complaining of their pretended grievances,
and inciting the members to separation.
This development soon put another face on the deliberation,
and Friends came forth clearly and decidedly for the appointment,
seeing the imperative necessity for it under such circumstances.
Some one of the Hicks party attempted to deny the truth of C. Evans`'s account;
but he appealed to John Comly to say if what he had stated was not correct,
and John Comly remained silent.^
footnote:[John Comly, in his journal, p. 331, calls him "`a spy,`" and adds,
"`His statement being denied by a conspicuous Friend,
he called on me by name to clear him of the charge of falsehood, or correct him.
But I saw and felt the spirit he was in,
and in perfect composure and calmness remained silent,
as knowing that I was professedly in a Yearly Meeting,
where no such altercations and disputations should be allowed,
and therefore answered him not a word.`"]

Several of the party candidly acknowledged the general
accuracy of his relation of the facts.
They seemed stumbled, and brought to a stand,
and knew not what further to do to arrest the measure,
and a large and general expression of approval of
the appointment took place over the meeting,
leaving no reasonable ground for doubt that such was the solid
judgment of the truly concerned and faithful members generally,
and consequently the judgment of the meeting.
The Hicksian party then determined to take no part in the nomination.
A committee was accordingly appointed, consisting of Hinchman Haines, Thomas Wistar,
Joseph Whitall, Thomas Stewardson, Jonathan Evans, Samuel Bettle, Edward Temple,
Christopher Healy, Benjamin Cooper, John Comfort of Solebury, Abraham Pennell,
and William Newbold; to unite with a similar appointment of the women`'s meeting.
During this last sitting,
the minutes were all read over as usual towards the close of the Yearly Meeting.
No objection was made to them; and the concluding minute,
adjourning the meeting to the usual time and place the next year, if the Lord permit,
was also read without a single objection.^
footnote:[S. Bettle`'s Testimony, in Foster`'s Report, vol.
i, p. 70.]
The Hicks party thus acquiesced in the authority and regularity of all the transactions.

Near the close, after a silence of great solemnity,
Christopher Healy revived the passage from the Revelation (chapter 15:3),
"`Great and marvelous are thy works, Lord God Almighty; just and true are thy ways,
thou King of saints!
Who shall not fear thee, and glorify thy name?`"
As the members were leaving the house, John Comly said to Samuel Bettle,
in reply to a remark of the latter respecting the
two classes into which the meeting was now divided,
"`You will be sustained, but what will become of us, I do not know!`"
Thus ended this memorable Yearly Meeting,
so fraught with consequences of a very serious nature to many poor unsuspecting souls,
blinded and drawn into a fearful vortex by false brethren.
But the acquiescence of the party, if it may be called so, was merely temporary.
Their leaders at least had not abandoned their designs of
establishing a Society in which they could have the control,
and do as they pleased, having, as they expressed it in one of their Epistles,
"`a ministry unshackled by human authority.`"
They went to work at once and in earnest with their plans for dividing the Society,
after the Yearly Meeting was over,
and met again in the Green Street meetinghouse according to their adjournment,
on the 4th and 5th of the ensuing sixth month, with William Gibbons and B. Ferris,
for clerk and assistant,
the one editor of the "`Berean,`" and the other the
writer of the letters under the name of Amicus,
in the "`Christian Repository.`"^
footnote:["`It was thought upwards of a thousand were in attendance.`"
John Comly`'s Journal, p. 338.]

They now issued another Address,
reiterating their own views of the causes of the state of
things in the Society--undisciplinary combinations,
interruptions of ministers traveling,
unjust and "`unfounded`" charges of holding "`infidel doctrines`"--the imposition
of a clerk on the Yearly Meeting contrary to the sense of "`the greater part`"
of the Representatives--the appointment of a committee to visit the meetings
contrary to the judgment of the "`larger number`" then present--that,
contrary to their hopes, the spirit of discord had gained strength,
and that there now appeared no way to regain the harmony and tranquillity of the body,
but by withdrawing (not from the Society of Friends and its discipline,
but) from religious communion with those who have introduced,
"`and seem disposed to continue such disorders.`"
They therefore proposed the "`holding of a Yearly Meeting
for Friends in unity with us,`" and encouraged such Quarterly
and Monthly Meetings as may be prepared for such a measure,
to appoint representatives,
to meet in Philadelphia on the third second-day of the 10th month ensuing.

Meantime they took all possible measures to increase their numbers by
misrepresentation and the promotion of prejudices and animosities,
and to seize the meetinghouses; and the latter they did with such success,
that in Pennsylvania there were very few meetinghouses left to the Society,
except four of the five in the city.
It would be extremely irksome, and unprofitable too,
here to detail the many acts of disorder and rude outrage,
by which they accomplished their purposes in this respect.
Let them rest in oblivion.^
footnote:[If any should desire further to pursue this branch of the sad subject,
they may find ample details of disorder and wrong, even to satiety,
in the first and second volumes of The Friend, Philadelphia, 1827 and 1828.
But I apprehend that in many of these cases, both classes were too hasty and determined,
though the acts of outrage were principally on the part of the Hicksites.]
But it is needful, as an essential part of history,
to allude to some further transactions by which the separation
was made complete over the several Yearly Meetings.
For the same causes operated, and produced similar fruits,
wherever Elias Hicks`'s influence extended.

The party met again, as proposed, on the 15th of the tenth month, 1827;
and this time they assumed for their assembly the name of "`the Yearly Meeting of Friends,
held in Philadelphia,`" irrespective of the fact that they
knew there was already a Yearly Meeting of that name,
which they had never disowned as not being a Yearly Meeting of the Society of Friends.
They had, it is true,
separated themselves from its jurisdiction in a way which they undertook to support;
but they had never shown gospel order in manifesting a justifying cause for such a separation,
nor had they taken upon them to disown those who adhered to it,
as being engaged in supporting a false position.
Their title, therefore, amounted to the assumption,
that there could be two Yearly Meetings of the same Society, in one place,
but independent of, and even antagonistic to one another.
Here again they issued an address, or "`Epistle to the Quarterly,
Monthly and Particular Meetings,`" signed by Benjamin Ferris and Rebecca B. Comly,
as clerks of the men`'s and women`'s meetings.
It contained many truisms plausibly stated, and considerable salutary advice,
deprecating "`the influence of party feeling`"--"`airy speculations
on religious subjects`"--the "`seizing of the discipline as a sword,
in the spirit of violence,`"--and with remarkable adaptation to the propensities
so frequently manifested by a considerable number of their own active members,
they exhorted,
"`that our religious testimonies may never be wounded
by contending for property and asserting our rights.`"

I am far from believing that there were not in that assembly men and women
who participated in sending forth that advice to their members,
with a sincere, or at least an honest belief,
that they were promoting the true cause of the Society.
The most industrious efforts had been used and were being used, to gain over all such as,
through any weakness of judgment or affection,
might slide unwarily within their influence; and many thus joined them,
who at the time had no idea of sanctioning and encouraging,
as their presence and accord undoubtedly did, the latitudinarian views,
if not the infidel principles, and the disorderly practices,
of the leaders in this schism.
But having given away their spiritual strength,
by joining in with some of the measures of this wild spirit,
at first perhaps covered over with smooth words and fine speech,
they became involved in the vortex, lost their power of escape from it,
and incurred a fearful responsibility with and for
the body to which they had united themselves.

The same causes which led to these deplorable events within Philadelphia Yearly Meeting,
were producing similar results in those of New York, Ohio, Baltimore, and Indiana;
and we must briefly glance at them, to show the completion of the schism.
I attended the Yearly Meeting of New York of 1827,
which occurred a few weeks after that of Philadelphia;
but the separation of the Hicks party,
though commenced in some of the subordinate meetings,
did not occur in the Yearly Meeting itself till 1828.
At the Yearly Meeting held in New York in 1827,
the meetings for worship were greatly disturbed by unsound preaching,
especially by one Phebe Johnson,
whom we have already met with as connected with the ranterism about New Bedford, Lynn,
etc., four or five years before, and who had now joined the Hicks party.
Thomas Shillitoe (who, with George and Ann Jones and E. Robson,
attended this meeting from England) zealously exposed,
and opposed with sound doctrine the dreadful unsoundness of her sentiments,
and called on the faithful members of the Society to put a stop to such utterances.
Elias Hicks was present as usual,
and I thought the darkness of his spirit and that of others of
their leaders was sensibly to be felt in the several sittings.
But as to the actual enunciation of unsound doctrine on that occasion,
Elias kept somewhat moderate;
enough probably having been said for him on those subjects by others of his party,
and he knowing that he was then under the eye of
men and women who were not slow to detect such errors,
nor wanting in a preparation to testify against them faithfully before the people.

His party made several attempts by clamor to obtain
control of the proceedings of the meeting;
but many friends from the country parts,
and some also from the city and its neighborhood,
standing firm for the testimonies of the Society,
they failed at that time in their attempts to revolutionize the Yearly Meeting;
though they came forth at intervals with much determination,
vociferating their sentiments two or three at a time,
and expressing their aversion to hearing those opposed to their plans, by coughing,
scraping with their feet, stamping with their canes, and other rude noises,
such as characterize popular assemblies rather than the meetings of Friends.
In the women`'s meeting also, I was informed there was much dissension,
during which Sarah Hicks, a niece of Elias Hicks by marriage,
was said to have been on her feet more than one hundred times in two sittings!

The autumn of 1827 saw the formation, in Philadelphia,
of an association of a number of members, mostly rather young men,
and ardent opponents of Hicksism, for the publication of a weekly paper,
entitled The Friend, a Religious and Literary Journal.
Its intent was to promote within the Society the
circulation of literary and scientific information,
free from objectionable matter,
and also to defend the Society from the misrepresentations of the seceders,
and to furnish wholesome religious and other reading for the youth,
suited to the tastes of Friends.
The object aimed at appeared desirable,
and the paper seemed for many years to give general satisfaction in the Society.
Yet some Friends have often had fears,
that divine wisdom was not enough consulted in its establishment,
and that its course in regard to religious matters was at
times not entirely consistent with our well-known principle,
that the cause of Truth must be promoted or sustained
by such efforts only as are in the ordering of Truth,
and not by the mere wisdom, will, and activity of the natural mind.
The paper however became, in the course of time,
a great receptacle of information in regard to what was passing in the Society,
particularly in America.
But in their zeal against Hicksism,
and in many of their literary attempts to maintain
what they thought to be Christian doctrine,
it is certain (and easily perceived by the careful examiner of even the first
volumes) that there was an edging toward the world`'s systems and modes of thought,
and that the wholesome limits of the true doctrines of Friends were at times overstepped,
and sentiments introduced (unconsciously doubtless on the part of the worthy editor,
and perhaps of many or most of the readers),
the natural tendency of which was to smooth the way for the reception of sentiments
by no means consistent with those entertained by the early members of the Society.^
footnote:[The writer cannot exempt himself from some portion of this censure,
having been in those early days,
unaware of the danger and inconsistency of some of the modern views.
The first editor, Robert Smith, deceased in 1851,
and the paper has since that time become more obviously
the organ of the "`middle`" or compromising system,
and disposed to ignore the very existence of the
"`smaller bodies,`" which were endeavoring to stand,
under much weakness and many discouragements, for the faith once delivered to the saints.
There has, however, of latter time,
been some evidence in its columns of a salutary alarm
at the overwhelming progress of innovation.]

For some time previous to the New York Yearly Meeting of 1828,
proposals for making the appointment of elders temporary,
similar to those made in the Yearly Meeting of Philadelphia,
had been forwarded to that of New York, but after much difficulty had been rejected.^
footnote:[See Samuel Parsons`'s Testimony in Foster`'s Report, vol.
i, p. 174.]
And in the spring of 1828,
measures similar to those taken in Pennsylvania for increasing
the number of representatives favorable to the party,
were resorted to in several of the Quarterly Meetings.
In Westbury Quarter (to which Elias Hicks belonged) double the usual number were appointed.
Six of the most useful members, not of the party, though named, were rejected,
and none were permitted on the appointment who were known to be unfavorable to his views.
In Cornwall Quarterly Meeting, in like manner, though several were named,
only one person opposed to his views was suffered to be appointed.

During the latter part of 1827, and the spring of 1828,
many of those who in Pennsylvania and New Jersey had gone off in this schism,
had been treated with by the Monthly Meetings in the regular order of the discipline,
and being irreclaimable, had been disowned,
as having separated themselves from fellowship among Friends.
When the Yearly Meeting of New York assembled in the fifth month, 1828,
it was found that a large number of these separatists from Philadelphia Yearly Meeting,
who had either been already disowned or were then under the care of their Monthly Meetings,
had obtruded their presence into the Yearly Meeting.
This circumstance precipitated the separation there,
as it was well known to be contrary to the practice and order of the Society,
to proceed with disciplinary business, while persons not in membership,
or members under dealing as delinquents, were present.

Thomas Shillitoe rose soon after the clerk had read the opening minute,
reminded Friends that through his certificates for religious service
which had been minuted on their books the previous year,
he had become during his stay among them a member of that body;
and then mentioned the fact of there being a large number of disowned persons present,
who had gone off in the schism,
and whose presence was incompatible with the meeting`'s proceeding with its business.
The intruders were urged to withdraw,
but were strenuously encouraged to remain by E. Hicks and his party.
Elias Hicks said he had himself attended their meeting in Green Street, Philadelphia,
that its members were "`the cream of the Society,`" and
their meetings the only legitimate ones in that part;
and he insisted on their right to sit in that meeting.
He said further, that "`if there were a dozen or more Presbyterians present,
the meeting ought to go on with its business.`"
Many of his adherents advocated the same views, and much noise and confusion soon ensued.
They ordered the clerk in a peremptory manner to go on with the business,
and seemed disposed to compel him to do so.

At this juncture, as there was no prospect of the intruders withdrawing,
or of the meeting being allowed peaceably to proceed,
surrounded by such a crowd of opponents of the principles and discipline of the Society,
a proposal was made,
that Friends who were concerned for the preservation of the Society in right order,
should remove the sitting to the basement story of that building.
This was freely united with by a large number of Friends,
but violently opposed by the Hicks party.
At length,
seeing that the clerk was preparing to read a minute which he had written to that effect,
they raised a great outcry, calling aloud, "`Don`'t let him read it,`" "`Pull him down.`"
Others said, "`He is no clerk of the meeting,`" "`We have a clerk of our own,`" etc.
Elias Hicks was requested to speak to them to suffer the clerk to read the minute,
and it is thought that he then did say something to that effect;
but the storm had risen to such a height, in hissing,^
footnote:[S. Parsons`'s Testimony, in Foster`'s Report, vol.
i, p. 181.]
shouting, stamping, striking the floor and benches with canes and umbrellas, etc.,
that there seemed to be no possibility of calming the uproar so as to be heard.

Before the clerk had read very far, Elias Hicks shared in the excitement,
and said to him, "`Thee is not the clerk of the meeting;
thee shall not be allowed to read;`" and turning to the audience, added,
"`Do not let him read.`"
They promptly obeyed his watchword, and called upon one John Barrow to act as clerk,
saying it was the choice of the representatives; whereas this being the morning session,
the representatives had not been directed to meet as yet,
and if any of them did meet on the subject of nominating a clerk,
it was only a party action, entirely unauthorized.
The disturbance was now at its height.
Forty or fifty of the party were, it is said, on their feet at one time.^
footnote:[Joseph Hoag`'s Journal, Heston`'s edition, p. 291.]
Elias Hicks then called on their new clerk to come forward to the table;
which he approached by climbing over the backs of the benches,
and heads and shoulders of elderly Friends.
When he thus arrived in front of the table,
Elias put out his hand to assist him to gain access to it;
but by some means he failed in his aim at it,
and some of his party turned him into the clerk`'s seat heels foremost!^
footnote:[Journal of T. Shillitoe, vol.
ii, p. 311.]
The regular clerk and assistant were at the same
time violently pressed away from their place,
to make room for him;^
footnote:[Testimony of S. Parsons, Foster`'s Report, vol.
i, p. 186.]
and attempts were made to wrest the minute from the clerk`'s hands.
But notwithstanding all their uproar, he succeeded in reading it,
while they hooted and hissed,
and the noise sounded through the open windows to the street, like distant thunder.

Friends then went to continue the sitting in the basement story,
but found it locked against them,
and were threatened with legal proceedings if they attempted to open it.
Under these circumstances, the Hall of Rutgers Medical College being offered to them,
it was concluded to adjourn to that building.
It was a solemn procession through the streets of that busy and worldly city--many weeping
as they walked silently along--and must have had a very striking effect upon the bystanders,
though few were aware of the occasion of it.
On reaching the hall, a time of solemn silence ensued,
after which vocal praises ascended to the Shepherd of Israel,
for His signal deliverance of His people.
Among others, Daniel Haviland, who was then very old and blind, broke forth,
says T. Shillitoe, in a melodious manner,
acknowledging that his spirit was now set at liberty, and his lips unsealed,
to speak of what he had seen for nearly forty years,
and who it should be that would introduce such disorder and confusion into the Society.
He mentioned the foresight also of the two English Friends respecting E. Hicks,
thirty-five years previously (as related on page 102);
and added that the scene they had just passed through was
clearly unfolded to his view before he came to the city.
"`But,`" said he, "`dear Friends, there will yet something come to pass,
if my feelings have not deceived me, that will more fully try our foundation!`"^
footnote:[Thomas Shillitoe`'s Journal, vol.
ii, p. 313.]
And he exhorted Friends to get so deep in their spirits, that they might be able to stand.
Would that this solemn admonition had been more deeply heeded
than it appears to have been by subsequent events,
which proved the truth of the prophecy and the great need of the warning.

Two Friends were now appointed to inform the Women`'s Meeting of what had occurred;
but they were not permitted even to enter the yard.
At their request, two women Friends were called out from the meeting,
who were under the necessity of going into the street to receive the message,
in the midst of a crowd of people who thronged the gateway.^
footnote:[See Epistle and Testimony of New York Yearly Meeting, 1828, p. 10.]
The Women`'s Yearly Meeting, which had been similarly intruded upon,
was afterwards separated,
and Friends met the next day in the African Methodist Meetinghouse.
Thus the Yearly Meeting was sustained, and continued several days in session,
issued an Address to the members in relation to these sorrowful occurrences,
and appointed a committee to visit the subordinate meetings.
Among other subjects which engaged attention,
was a complaint against the unsound doctrines of Elias Hicks,
sent to them by the Yearly Meeting of Philadelphia.
The Monthly Meetings of Philadelphia for the Southern and Western Districts had,
early in 1827, sent a complaint to Jericho Monthly Meeting on Long Island,
respecting the unsound and pernicious utterances of Elias Hicks,
especially in one of the meetings in the Pine Street house, during the winter of 1826-7.

This complaint, when at length it was suffered to be read in Jericho Monthly Meeting,
was treated as unworthy of further notice, and its allegations were denied as false,
although fully borne out by the account taken on the occasion by
the stenographer who printed so many of E. Hicks`'s discourses,^
footnote:[See The Friend, Philadelphia, vol.
ii, p. 152.]
The Southern District Monthly Meeting, after waiting a reasonable time,
represented the case to Philadelphia Quarterly Meeting; which then sent the complaint,
by a delegation of three members, to Westbury Quarterly Meeting,
of which Jericho Monthly Meeting formed a part.
Elias Hicks`'s adherents having here also the control, refused to read it,
and clamorously heaped abuse on Friends of Philadelphia.
They, however, referred the paper to a committee for three months,
and then the whole thing was set aside.
Philadelphia Yearly Meeting of 1828 then took up the case,
and sent the complaint by a committee to the Yearly Meeting of New York;
which receiving it for action after the separation had taken place there,
was now free to place the matter in a proper train for disciplinary action.
Accordingly it sent the complaint to Westbury Quarterly Meeting of Friends,
with directions that the Monthly Meeting concerned should
take the requisite measures in reference to it.
The Monthly Meeting of Westbury and Jericho (formed by the union
of two Monthly Meetings after the separation) promptly responded
by sending a communication dated eighth month 21st,
to Elias Hicks, who was then gone to Ohio,
stating to him the very serious nature of the charges against him,
and requiring him at once to return home.
This communication was handed to him after his arrival
at Mount Pleasant to attend Ohio Yearly Meeting.
He evinced great agitation.

Elias had been traveling about in various sections
of Ohio Yearly Meeting previous to its convening,
preparing his partisans for the event.
I should be glad to draw the veil of silence over the disgraceful
scenes that were the result of his harangues,
and of those of his prominent coadjutors; but the truth must be told.
Thomas Shillitoe had crossed his path at various
places within a few weeks of the Yearly Meeting,
in the western parts of Pennsylvania, and the eastern border of Ohio,
and arduous service had devolved upon him,
in the necessity of exposing the unsoundness of Elias`'s doctrines to the people,
at such times as they happened to meet at the same place.
The Select Yearly Meeting of Ohio assembled at Mount Pleasant, on seventh-day,
the 6th of ninth month, as usual.
Elias Hicks and some of his followers attempted to attend it,
but as they were palpably engaged in efforts to extend in Ohio the separation
which had already taken place from the Society to the eastward,
they were informed at the gate that they would not be allowed to enter the house.
On this,
to the number of twenty-two (eight or ten of whom were from other Yearly Meetings),
including, it has been thought, only one minister belonging to Ohio Yearly Meeting,
they held their meeting near the gate, then adjourned to a building not far off,
and finished their pretended "`Select Yearly Meeting`" at Israel French`'s house.

On first-day, the 7th, the meetings for worship were much crowded,
and greatly disturbed by these people.
A large concourse assembled at the Mount Pleasant house in the morning,
to whom Elias Hicks preached as usual at considerable length;
but his position as a schismatic, and the unsoundness of his doctrines,
were clearly exposed by Elisha Bates, who was then a minister in unity with Friends;
and Elias could make no adequate reply, but said,
that was not the place for entering into discussion; which indeed was true.
He made his home at the house of Israel French, and several of his partisans,
including Amos Peisley, Elisha Dawson, and Halliday Jackson, put up at the same house.^
footnote:[The Friend, vol.
I, p. 407]
It is supposed, from various circumstances,
that the plan for seizing the meetinghouse on second-day,
was considered and agreed on among them in that house,
as it had been previously considered by many of them in a certain school-house^
footnote:[Ibid, p. 414]
on seventh-day afternoon previous.

However that may have been,
Elias Hicks evidently deemed it most prudent for himself
to stay away from the opening sitting on second-day.
In his Journal, he gives no reason for staying away,
but touches the subject very lightly, saying: "`Not being present at this sitting,
I was informed that great confusion and disorder took place.`"
Halliday Jackson afterwards gave as a reason for the absence of his friend,
that he was "`engaged in writing to his friends at home,`"
in regard to some "`novel communications from Long Island.`"
This was a singular excuse to give for the absence of one who had come between
four and five hundred miles with a certificate to attend Ohio Yearly Meeting.
But it appears that he was actually engaged that day (as
he deemed it best to stay away from the meeting),
in writing an angry reply to the letter of his once dear friend Gideon Seaman,
conveying to him the requisition of Westbury and
Jericho Monthly Meeting for his return home forthwith.
He began his reply with the words, "`My poor deluded friend,
Gideon Seaman,`" and went on to declare in vague terms that the charges against
him were "`founded altogether in falsehood;`" but said nothing to clear himself
from the false doctrines which were not only in those charges,
but also in the report of his sermon taken down in short hand,
which he here acknowledged to have been "`taken verbatim as delivered.`"

Charging his accusers with having left their first love,
and "`turned away to fables and false reports,`" he applied to
them the language partly addressed by Christ Jesus to Saul:
"`Friends, friends, why persecute ye me?
It is hard for you to kick against the pricks,`"--and declared,
with a remarkable want of attention to accuracy of statement,
that Philadelphia Yearly Meeting ("`orthodox "`) was "`but the gleanings of Society,
being little more than a sixth part of the whole
body of friends that constitute that Yearly Meeting.`"
This was a singular estimate,
when it was generally admitted that in that Yearly Meeting the numbers were nearly
equally divided--a small preponderance only being attached to the Hicksites.
He asked his accusers, "`how they could feel themselves, in their folly,
so consequential as to send an order for him to return immediately home,`" etc.,
and concluded by saying that if he were to comply with their order,
he should be acknowledging the reign of Antichrist.
Such was his temper,
while his partisans were following out their newly invented declaration,
"`that there was no law against the press,`"--i. e., bodily pressure!

At 8 o`'clock on second-day morning,
the Committee on Indian Concerns met as usual in the Yearly
Meetinghouse for the transaction of their business;
but had not proceeded much more than an hour,
when it was announced to them that the crowd outside
was so great and so anxious to enter,
that the doors would have to be opened for the Yearly Meeting.
The Friends appointed by the several Quarterly Meetings
to preserve order about the entrances to the Yearly Meetinghouse,
had also met about 8 o`'clock, and in view of the extraordinary state of things,
and the imminent danger of violence on the part of the seceders,
they had agreed together that all peaceable means should be resorted to,
to induce them to refrain from intruding upon the meeting,
but in no case to repel force by force.
The weather was extremely wet, and long before 10 o`'clock the doors were opened,
and the crowd began to rush into the house.

There were among them a large number of separatists,
and also various persons of the vicinity,
attracted probably by curiosity or an idle desire for excitement.
The separatists at once evinced their determination to enter the house,
either peaceably or forcibly,
and the doorkeepers soon found it useless to attempt to
keep out even those among them who had been disowned.
Many rushed violently through the doors in solid masses,
enveloping in their midst those whom they knew to be the most obnoxious,
and having gained an entrance for these,
either remained inside to pull in those whom their comrades
outside were pushing through the committee of doorkeepers,
or went out to form new solid masses round other disowned persons,
and perform their feats over again.
After the house was nearly filled up, and somewhat of a pause took place,
Thomas Shillitoe was engaged in supplication;
but the solemnity ensuing was interrupted by one of the most formidable
of these solid masses of wild young men rushing into the house,^
footnote:[The Friend, vol.
I p. 391.]
having Amos Peisley and Elisha Dawson in their midst.
They burst through the crowd of Friends, exclaiming to one another, "`Move on, Friends;
move on, Friends!`" and seemed determined to take possession of the house.

Soon Israel French rose and said,
that "`it devolved on him`" to declare that the present
clerk had disqualified himself for acting,
and another one ought to be appointed; and immediately some one else called out,
"`I nominate David Hilles.`"
This was responded to by shouts of approbation.
The clerk meantime was engaged in calling the names of the representatives,
and reading their credentials from the several Quarterly Meetings.
David Hilles being loudly urged by his party,
strove to make his way to the table through the dense crowd of Friends,
but found it no easy matter,
as they were particularly closely packed about the galleries where the table was situated,
and were by no means disposed needlessly to make room for a posse of intruders.
His party therefore now made a desperate rush toward the galleries, evincing,
by the angry expression of their countenances, and vehement gestures,
their determination to effect their object.
One of them getting on some eminence,
precipitated himself headlong upon the body of Friends,
in order to throw them into confusion and make them give way.
In his first attempt he rolled over, and fell prostrate among them, but trying it again,
with assistance,
he pushed himself over the rail into the gallery among the elderly Friends.
Here putting his feet against the railing of the gallery,
to obtain purchase in pulling a comrade also up, some of the woodwork gave way,
which increased the noise and alarm.

Friends attempted to remonstrate against such riotous proceedings,
and even some of their own party endeavored to allay the tumult.
But the others cried out, "`Move on,
move on!`" and remonstrance and rebuke were alike unheeded.
One man mounted the large stove, and urged them on,
shouting that they were going to restore the God of love to the galleries!
Their new clerk had not yet succeeded in reaching the table.
Suddenly a cry was raised, that the youth`'s gallery,
or the sounding-board over the ministers`' gallery, was breaking down,
and the house falling; and a crash was now heard upstairs,
which seemed to give probability to the alarm.
It arose, however, from some one there breaking a piece of wood,
probably with the intent of raising a panic.
Many had no means of knowing how false was the alarm,
but jumped or tumbled down from the youth`'s galleries;
others rushed impetuously down the stairs and out at the doors;
and many were seriously crushed and hurt in the press.
The sudden rush loosened some plaster from the ceiling,^
footnote:[Thomas Shillitoe`'s Journal, vol.
ii, p. 345.]
and this falling increased the alarm.
The glass of several windows was broken away,
and one window sash kicked and broken to pieces.
The leading rioters meanwhile kept what they had gained,
without being involved in the alarm, as if they knew all about it,
and held themselves in readiness to seize any advantage offered by it.
But Friends generally about the table remained also at their posts.

But at length the party gained their point.
While the clerk was endeavoring to write down the names of the chief rioters,
one of them threw open a door behind the table;
others then made a push at the table itself, to move it from its place,
and to force those sitting behind it through the open door.
But this was not easily effected.
Then one of them seizing a leg of the table, another a part of the top,
a third the drawer, and so on, they pulled the table to pieces;
and rushed so furiously on Jonathan Taylor, the clerk,
who was a delicate man and in slender health,
that he was in danger of being "`pressed`" to death.
Some one outside at this juncture seeing his perilous situation,
laid hold of him and rescued him through the open doorway.
Having thus taken possession of the table literally by storm, they raised a hurrah!
Their newly nominated clerk was talking and tittering at
the elbow of the seat near where the table had been.
Several plain-looking men seemed to be taking the lead,
and one of them cried out that it would soon be time
to clear the house for their new clerk.
Some one handed to the latter the drawer of the shattered table, to serve as a desk,
and he soon read something by way of a minute under the new order of things.
Friends seeing that the control of the meeting was thus usurped by a mob,
it was now proposed to adjourn to the next day, and this being approved,
they quietly withdrew from the house.
The Hicks party proceeded in holding what they called Ohio Yearly Meeting.

Even the Women`'s Meeting did not escape being invaded by some of the mob.
A company of them rushed violently into their apartment,
and threw open one of the outer doors,
as if they wished either to induce other rude men to enter,
or to suggest to some of the female friends to make their escape.
The alarm respecting the house falling was quickly communicated to them,
and a young man ran in among them, jumped into one of the windows,
and began to kick it to pieces with all his force.^
footnote:[See The Friend, Philadelphia, vol.
i, p. 392.]
They adjourned in accordance with the action of the Men`'s Meeting.
At ten o`'clock the next morning,
the Yearly Meeting reassembled according to adjournment,
but were not allowed to occupy the house.
Elias Hicks and his party had collected an hour before that.
After ineffectually demanding the use of the house to hold the Yearly Meeting,
and being tauntingly answered that the Yearly Meeting
was now sitting and did not wish to be disturbed,
Friends collected for a time in the yard, and adjourned to the Short Creek Meetinghouse,
not far distant, where the rest of the sittings of the Yearly Meeting were held.
It was supposed by Friends of that meeting,
that not more than one-third of the members originally present to attend
the Yearly Meeting consorted with Elias Hicks and his party;
and their outrageous conduct evinced how little they regarded their own favorite dogma
of "`the right of the majority to rule,`" except when it suited their own purposes.

The Yearly Meeting of Indiana was peaceably held, as usual, at White Water,
near Richmond, in that State, commencing on the 6th of the tenth month;
the Hicksites in that section having already seceded, and, much to their credit,
held their Yearly Meeting separately, about a week previous, at Waynesville, in Ohio;
thus avoiding such disgraceful scenes as had taken place at Mount Pleasant.
Elias Hicks was there also, and it is probable that but for his presence,
his party would scarcely have had strength to take the step
they did in professing to hold Indiana Yearly Meeting.
Baltimore Yearly Meeting was the only remaining body of that character,
in which the Hicks party effected a separation.
It convened in the city of Baltimore on the 27th of tenth month, 1828.
Many individuals who had been disowned were suffered to attend it,
and the credentials of some of them from the separate meetings were read.
The Yearly Meeting of 1827 had already shown its preference for the schismatics,
by reading and answering an Epistle from the separate meeting in Green Street,
Philadelphia,
while it sent also a cold and almost rebuking reply to one
sent to it by the Yearly Meeting of Friends of that year.
But on this occasion, in 1828,
it received and read Epistles not only from the regular Yearly Meetings of Friends,
but also from the Hicks Meetings of Philadelphia, New York, and Indiana,
and accepted and answered these, while they left the others unnoticed.

In narrating the subsequent proceedings,
as they seem to have an important bearing on other cases somewhat similar,
and especially as they were stated and remarked upon soon after, in a very lucid manner,
in the periodical paper published in Philadelphia,
entitled "`The Friend,`" I prefer to quote certain
portions of the statements made in that paper,
rather than to give my own.
To copy the whole account and remarks,
would inconveniently and uselessly extend these pages;
but we will take such portions as are required to give a
clear view of the subject as treated in that periodical.^
footnote:[The Friend, Philadelphia, vol.
ii, p. 37.]

Epistles were produced from meetings of the seceders, styled Yearly Meetings,
which were read and minuted,
while little other notice was taken of those from
the ancient and regularly established Yearly Meetings,
except to censure their contents in harsh terms.
It was also proposed that the assembly should then distinctly
declare whether it would recognize and unite with the meetings
of those who have separated themselves from the society,
or continue its connection and fellowship with the
long-established Yearly Meetings of Friends.
The former proposition was warmly supported by the advocates of the new doctrines,
and a minute was made recognizing such a conclusion.^
footnote:[A committee was also appointed to essay replies to the three bodies of separatists,
of Philadelphia, New York, and Indiana.
See The Friend, vol.
ii, p. 53]
It "`is evident that this measure completely identified all those who promoted it,
not only with the different bodies of separatists scattered over this country,
and with the erroneous notions which they hold on important points of Christian faith,
but also severed them from communion with the ancient Society.
By this act, therefore,
the assembly ceased to be the Yearly Meeting of Friends of Baltimore,
and became a Yearly Meeting of the newly established sect.
Those individuals who conscientiously dissented from the doctrines held by the separatists,
and who felt no wish to become a part of their Society,
had no alternative left but to meet apart from the others,
and endeavor to continue their connection with their brethren in other Yearly Meetings,
as the Yearly Meeting of Friends in Baltimore, etc.

Page 53: It will probably be said,
that comparatively a few only of the members of Baltimore Yearly Meeting,
who joined themselves to the new sect,
actually hold the unsound principles of Elias Hicks.
We sincerely hope this is the fact; but it does not change the state of the case.
Whether they themselves hold the principles or not,
if they unite in a Society capacity with those who do hold and openly avow them,
they lend their influence in support of those principles,
and sanction them by the language of conduct and example.
They show their approbation of them by the strongest evidence which can be given, viz.,
social unity and church fellowship.

Page 54: The Society, the ministers, and the doctrines,
are all identified and associated with each other;
and every member who evinces his unity with the sect,
is accountable for the principles which are thus promulgated,
as completely as are the members of any other religious
communion for the doctrines held by it.

Again, page 54: It matters not how large the number may be who violate the compact,
break down the established constitution,
and disregard the terms on which a right of membership
in the Society of Friends can only be held.
If it be nine-tenths, nineteen-twentieths, or ninety-nine-hundredths,
the principle remains the same.
Membership can only be enjoyed so long as the prescribed terms of it are complied with:
the moment an individual violates those conditions, he voluntarily forfeits his right,^
footnote:[These expressions seem to need some qualification.
A deliberate and persistent violation of the constitution of the
Society does of itself deprive the offender of his right of membership,
or rightful claim to membership;
though his actual membership in fact continues to some extent, until,
after gospel order has been duly and ineffectually exercised by the church,
or assembly of the faithful, this membership is declared to be forfeited.
The true fellowship having been broken,
the technical or merely outward membership is as it were held in suspense ad interim,
for his recovery.
Yet, as R. Barclay says, he cast himself out, by his transgression; which in due time,
if persisted in, the church has to declare.]
and if the whole number of persons constituting a meeting act thus,
they as fully and completely cease to be members of the Society
as any one of them would if regularly disowned by the rest.
Numbers have no modifying influence upon the terms and principles
of the Association It is not the same Society it was before,
if the fundamental principles of its union are altered.

Page 61: The statements we have already made,
show in the clearest manner that in order to retain their connection with the Society,
and to support its doctrines and discipline,
Friends of Baltimore Yearly Meeting had no alternative left but
to meet apart from those who had seceded from its communion,
and attached themselves to the new Society of Hicksites.
Accordingly, near the close of the sitting on fourth-day afternoon,
notice was given to such persons as were dissatisfied
with the irregular proceedings of the separatists,
to meet at nine o`'clock on the following morning, at the McKendrean school-house,
for the purpose of holding Baltimore Yearly Meeting of Friends,
in connection with the ancient and regularly instituted
Yearly Meetings of our religious Society.
Two Friends went to communicate this information to the women`'s meeting;
but when they attempted to enter, they were denied admittance by two of the Hicksites,
who had anticipated the movement, and placed themselves at the doors to guard them.
They, however, obtained admission by a side-door,
which had escaped the vigilance of the sentinels,
and informed the assembly of the proposed meeting.

The number of Friends who convened on fifth-day was about one hundred and fifty,
of whom sixty-six were men, and eighty-four women.
It is true the company was small; yet we can thankfully acknowledge,
that He who has promised to be with the two or three that are met in His name,
owned the meeting by His sacred presence,
the evidence of which more than compensated for the sacrifice that many had made,
and the derision they met with,
in thus openly acknowledging their attachment to His name and cause.
The meeting closed on seventh-day evening,
and Friends parted from each other under a grateful and humbling
sense of the unmerited favor they had been permitted to enjoy.

There can be but one Society of Friends;
and that one Society must adhere to those doctrines which are the
basis of the compact on which the association was originally formed.
Each Yearly Meeting has its peculiar and exclusive rights,
relating to its own government and internal regulations;
and these it holds in dependency of all other Yearly Meetings; provided always,
that they do not extend to the rejection of any acknowledged doctrine or testimony.
But if either of the Yearly Meetings, or any number of them,
alter the principles which form the outward bond of union in the Society,
forsake the ancient and established organization, and join a new association,
holding different principles,
they cease to be a constituent part of the Society of Friends.

Page 39: By uniting that meeting to the separatists, in New York, Philadelphia, Ohio,
and Indiana,
they countenanced and sanctioned not only the violent and unchristian
conduct of which the party in some of those places had been guilty,
but they actually avowed unity with the pernicious
doctrines which they are known to hold;
and every member of Baltimore Yearly Meeting,
who continued to meet with the party after they had
thus fully identified themselves with the new sect,
was lending his influence and according his assent to those practices and doctrines.^
footnote:[See also in the same article,
at page 69 of the same volume of The Friend a lucid development of the fallacy
of the Hicksites`' denial of the charge of not owning the divinity of Christ,
and how they attempt to distinguish between Jesus and "`the Christ.`"]

The reader will please to bear in mind that the above
arguments and conclusions of The Friend,
unanswerably clear as they are,
are equally applicable to cases which we may meet with in the sequel of this history.
It may be proper to add, that although, in this separation from Baltimore Yearly Meeting,
the Hicksites had all the technical advantages of numbers, organization,
and apparent regularity of proceedings as to the routine and order of business,
yet the one fundamental point,
the maintenance of sound doctrine against attempted innovations,
was a far counterbalancing one in the view of Friends;
and this small body of that epoch was received,
without any question as to numbers or technicalities,
and immediately owned in the brotherhood of the Society, by every sound Yearly Meeting.

It remains now,
in bringing towards a conclusion our account of this great schism in the Society,
to relate the facts of the disownment of Elias Hicks.
We have seen that he disregarded the requisition
of the Monthly Meeting of Westbury and Jericho,^
footnote:[The two Monthly Meetings having been united into one,
after the separation of the Hicksian party,
E+++.+++ Hicks`'s membership of course was now in the joint meeting.]
sent to him in Ohio,
for his immediate return home to answer the charges which had been brought against him.
We have seen, too,
that he wrote an angry reply to his old and faithful friend Gideon
Seaman`'s earnest and brotherly expostulation with him.
He returned from his western journey in the twelfth month,
and as he persisted in disregarding the advice of Friends,
and continued to impose himself on the community
as an acknowledged minister in the Society,
it became incumbent on the meeting to which he was amenable as a member (the
one he was now consorted with being altogether irregular and schismatic,
and established for the support and promotion of his innovations),
to take measures for the clearing of truth from so great
a reproach as his preaching had brought on the Society.
He was accordingly waited on in the regular order of the discipline,
by the overseers of Westbury and Jericho Monthly Meeting;
and as no satisfaction was received by them,
his case was reported to the Preparative Meeting, and thence transmitted,
for further dealing, to the Monthly Meeting.
Here a committee was appointed, as usual, to treat with him;
but he pertinaciously rejected the care and labors of Friends,^
footnote:[See The Friend, vol.
ii, p. 318.]
and persisted in his erroneous opinions.
There was therefore no way left for the meeting but to proceed
to issue a Testimony of disownment against him,
and thus clear the Society from all responsibility for his sentiments and course.

The Testimony is an important historic document, taking a view of the whole case.
It is therefore here transcribed.

Testimony of the Monthly Meeting of Friends of Westbury and Jericho,
Against Elias Hicks and his Doctrines.

Elias Hicks has been, for many years,
in the station of a minister in our religious Society,
and formerly well approved amongst us; in which character he has travelled extensively,
and obtained great influence with the members of the Society;
but for want of abiding in a state of humble watchfulness, in which,
by the power of divine grace, he would have been preserved in the truth,
he has become exalted in his mind, and giving way to a disposition of reasoning,
has indulged in speculative opinions,
asserting that we must always take things rationally;
and that we are not bound to believe anything we do not understand.
Thus declining to be restricted within the limits of the Christian faith,
he has refused to yield his assent to religious truths which he cannot comprehend;
and has imbibed and adopted opinions at variance with some
of the fundamental doctrines of the Christian religion,
always believed in and maintained by the Society of Friends;
denied the existence or influence of an evil spirit on the mind of man,
distinct from his natural propensities; and has, in this state,
entertained doubts of many of the important truths declared in the Holy Scriptures;
especially as relates to the fall of man, and his redemption by Christ; and,
in consequence,
to call in question the divine authority of a great portion of the sacred writings,
and even the authenticity of some parts thereof.

He has extensively promulgated his views in conversation, in writing,
and in his public communications,
endeavoring to destroy a belief in the miraculous
conception of our Lord and Saviour Jesus Christ;
undervaluing the miracles wrought by Him; and asserting that He was but a man,
as liable to fall into sin, and lose his condition, as the rest of mankind;
that He was on a level, and in a state of equality with them;
an Israelite endued with a measure of divine grace,
in common with the children of Abraham,
and that the principal end of His coming was limited to the Jews.
And as he has denied the divinity of our Lord and Saviour Jesus Christ,
he has totally rejected a belief in His holy offices,
His propitiatory offering for the redemption of mankind;
and has denied His resurrection and ascension into heaven,
asserting that His body returned to the earth,
where it will rest with our bodies to all eternity, and moulder into its mother dust.
He has also denied His mediation and intercession with the Father,
as plainly set forth in Holy Writ.

Under the specious and captivating pretense of increased spirituality,
and advancement in light and knowledge beyond our primitive Friends,
and even beyond the apostles of our Lord,
he has insinuated his unsound opinions into the minds
of many of the members of our Society,
particularly within the limits of our own Yearly Meeting, and that of Philadelphia;
and having gradually prepared them to receive his views,
he has induced great numbers to embrace them;
and has at length become the leader of a sect, distinguished by his name,
yet unjustly assuming the character of Friends;
which first separated from the Yearly Meeting of Friends in Philadelphia,
in the fourth month, 1827, on the ground of difference in doctrine,
as they state in their printed Address.
They held a separate meeting in that month, and in the sixth and tenth months following,
and also in the fourth month, 1828, which last meeting Elias Hicks attended,
gave it his countenance, and received a minute of its unity with him and his services.

In the Yearly Meeting of Friends in New York in the fifth month following,
he encouraged and supported a large number of those
separatists in their intrusion into said meeting;
many of whom had been regularly disowned from the Society;
yet he manifested his full unity with them, and with their meetings;
and also took an active part with his followers in their disorderly and tumultuous proceedings;
and continued in connection with those of similar views, in holding a separate meeting,
which they called a Yearly Meeting.
Since that time he has travelled into Ohio, Indiana, and elsewhere,
encouraging his followers in holding meetings in different parts,
in opposition to the order of our Society.
His erroneous opinions published to the world under his own signature,
and also in his printed sermons, which he has acknowledged to be generally correct,
are recited and testified against,
in the Epistle and Testimony of our last Yearly Meeting held in New York,
and in the declarations and testimonies of the Yearly Meetings of Friends in Philadelphia,
Virginia, North Carolina, Ohio, and Indiana;
who are also supported therein by the testimony of the Yearly Meeting of Rhode Island,
and the minutes of the Yearly Meeting of London; hence it is evident,
that Friends of all these Yearly Meetings remain united
together in the faith and fellowship of the gospel.

For a number of years past,
many of his friends have been deeply exercised on his account;
and have been concerned from time to time tenderly to admonish and warn him;
but he being in a confident state of mind,
their admonitions have not had the desired effect;
and the support which he received from many of his adherents,
prevented the timely exercise of the discipline in his case,
especially in the Monthly and Quarterly Meetings of which he was a member;
but the separation taking place at our last Yearly Meeting,
and this Monthly Meeting being now in a situation to extend the necessary care therein,
the same has been duly attended to, according to the order of our Society,
to convince him of his errors; which having been in like manner rejected by him,
it becomes our incumbent duty,
for the clearing of Truth and our religious Society
from the imputation of his unsound opinions,
and the reproach thereby brought upon it, to testify and declare, that they are not,
nor ever have been, the doctrines of the Society of Friends;
and as we can have no unity with them, nor fellowship with him therein,
we do hereby disown him, the said Elias Hicks,
from being a member of the religious Society of Friends: desiring, nevertheless,
that through the convictions produced by the operation of the Holy Spirit,
he may be brought to a sense of his errors; and through sincere repentance,
may obtain that salvation which is freely offered
through our Lord and Saviour Jesus Christ.

Signed on behalf and by direction of the Monthly
Meeting of Friends of Westbury and Jericho,
held at Westbury the 29th of the fourth month, 1829.

By Valentine Willets, Clerk.

After all this, viz., on the 16th of eleventh month, 1829,
Elias Hicks wrote (or at least signed) a letter to one of his adherents (Hugh Judge),
giving answers to Six Queries respecting his doctrines;
which queries had been artfully drawn up, and the answers no less carefully contrived,
so as, apparently, to endeavor to cover up,
for those of his disciples more or less weak in their confidence in him,
his own gross errors,
and to make people believe that he had never said certain
things which the world well knew that he had often repeated,
and the printed statements of which utterances he had acknowledged to be correct.
As there was then a bill already filed for a suit between the Hicksian
party and Friends in the Court of Chancery of New Jersey,
it seems probable that one purpose may have been
to have it used to advantage in that suit.
George Wood, counsel for Friends, in pleading on the appeal, said, in reference to it,
"`a more artful piece of invention was never exhibited in a court of justice.
It was manufactured after this controversy had arisen.`"^
footnote:[See Foster`'s Report, vol.
ii, p. 433; and Full Report of the Pleadings, etc.; Philadelphia, 1834, p. 430.]
However this may have been, and however cautiously it was worded,
either by him or for him, it is altogether inadequate to cancel his monstrous errors,
uttered year after year, in various ways, before the public and in private.

The first query was in regard to the miraculous conception of Christ.
To which he replied, that from his youth up he had had as full a belief in it,
as it was possible for the history to give belief,
and that he never thought or said that he believed Joseph was his father;
whereas he had distinctly said to W. Jackson, that there was as much, and to T. Willis,
that there was considerable more Scripture testimony (that is, of course,
history) against it than for it,
and had often in public uttered his doubts on that subject!

The second query, on the Divinity of Christ, he answered ambiguously and insidiously,
evidently with a mental reservation bearing on the construction of his words.

The third query was on the Holy Scriptures; of which, in his answer,
he professed high esteem from his youth,
and to have confirmed his doctrine abundantly from their testimony,
and endeavored to place them in their true place and station.
But even here there was a catch,
for he went on to declare that when the Scriptures
have directed and pointed us to this light within,
or spirit of truth,
there they must stop--it is their ultimatum--the top-stone of what they can do.
Of course the meaning of this is, that they are of no further use! not even for comfort,
or for correction and instruction in righteousness!

The fourth query was in regard to a state of rewards and punishments;
which he answered as if he had never denied it.

The fifth query was respecting our coming up to a level with the man Christ Jesus;
desiring him to explain his own words in regard to it; which he does very imperfectly,
the reply being exceedingly misty and ambiguous, followed by a few texts of Scripture,
which by no means throw any light on the alleged level; but, by his application of them,
show his desire to bring Christ down to the level of a good man.

The sixth query, respecting the relation of the body of Jesus to the Saviour of men,
and regarding the crucifixion of that body as an atonement for our sins,
he answered evidently with great care, quoting Isaac Penington and George Whitehead,
without naming them.
In quoting from Isaac Penington,
it is remarkable that he begins immediately after a very full, and clear,
and emphatic acknowledgment, by that author, of the efficacy of that sacrifice for sin;
which would have been very much to his purpose if he had been really sound on this point.
But he leaves it all out, giving what may fairly be called a garbled quotation,
which does not fully express what Isaac Penington had in view.^
footnote:[See I. Penington`'s Works, 4to, vol. ii, p. 7;
or Amer. edit+++.+++, vol. iii, p. 31.
The unfairness of this partial and fallacious quotation may he clearly
perceived by a reference to the passages immediately preceding it in the original.]
If Elias Hicks`'s words in this answer are taken
strictly as a reply to the question of the atonement,
they will be found to be very ambiguous and unsatisfactory.
He winds up with a reference to his printed sermons,
as taken down by Gould the stenographer;
mentioning them as containing answers to all objections
in regard to his belief and doctrine;
hereby endorsing the sentiments to be found in those sermons,
if plain English words have any unmistakable meaning.
The baneful seed had been sown, and had germinated abundantly,
and it was not in his power, by such a document as this, even if so disposed,
to avert the consequences of the growth of that seed.

The last act in the life of Elias Hicks,
say the editors of his "`Journal,`" was the writing of another letter to Hugh Judge.
This letter had many declarations respecting the inward law and light,
which might have been well, if this inward law and light had been acknowledged,
in any one of the frequent allusions to it, as being the purchase of Christ`'s death,
who tasted death for every man.
But no such thing,
nor any approach to a recognition of Christ Jesus as the author of our salvation,
or of our redemption having anything to do with what
he did and suffered for us in the prepared body,
is to be found in this long letter.
He frequently speaks in it of Jesus, but never calls him the Lord Jesus, or our Saviour.
In the early part of it--after saying that the blessed Jesus,
our holy and perfect pattern and example assured his disciples,
that by walking in the same pathway of self-denial and the cross,
which he trod to blessedness, they might also overcome the world;
as nothing has ever enabled any rational being, in any age of the world,
to overcome the spirit of the world, which lieth in wickedness,
but the cross of Christ--he gives his definition of the cross of Christ, as follows:
"`Some may query, what is the cross of Christ?
To these I answer, it is the perfect law of God written on the tablet of the heart,
and in the heart of every rational creature, in such indelible characters,
that all the power of mortals cannot erase or obliterate.
Neither is there any power or means given or dispensed to the children of men,
but this inward law and light,
by which the true and saving knowledge of God can be obtained.`"^
footnote:[Journal of E. Hicks, Appendix, p. 439.]

This letter was written on the 14th of the second month, 1830,
and the "`Memorial`" of his friends respecting him states,
that after writing it he returned to the room occupied by the family,
apparently just attacked by a paralytic affection,
which nearly deprived him of the use of his right side, and of the power of speech.
Being assisted to a chair near the fire,
he manifested by signs that the letter which he had just finished,
and which had been dropped by the way, should be taken care of.
After this, he continued gradually to decline, until the evening of the 27th,
when he quietly passed away.^
footnote:[Ibid, p. 450.]

The various Yearly Meetings in America promptly issued declarations against this secession,
showing the antichristian ground of it,
and the inconsistent and disorderly measures by which its accomplishment was attended.
In the summer of 1829, a joint Committee, appointed by each of these Yearly Meetings,
assembled in Philadelphia, and prepared an extensive document,
bearing the character of a united testimony to those great truths
which the Society of Friends has ever most surely believed.
This document, being subsequently presented to the respective Yearly Meetings,
was adopted by each of them, and published in 1830,
as The Testimony of the Society of Friends on the Continent of America.
It stated briefly the fact of the schism having taken place
within the limits of the Yearly Meetings of New York,
Philadelphia, Baltimore, Ohio, and Indiana; adding, however,
"`It is cause of thankfulness that the Yearly Meetings
of Friends in all these places have been sustained,
and hold religious fellowship with one another,
and with the ancient Yearly Meetings of New England, Virginia, North Carolina, London,
and Dublin, in which there is no schism.`"

The bulk of the document consisted of declarations on various
points of doctrine involved in this unhappy schism,
chiefly quoted from Robert Barclay, George Fox, and other standard authors.
London Yearly Meeting likewise issued, in 1829,
a brief testimony against the Hicks schism,
citing various Scripture doctrines appropriate to the occasion.
Towards the close, in allusion to these doctrines, it declares:
"`We do not acknowledge "`as in fellowship with us, as a Christian community,
"`any body of religious professors which does not accept them,
or which openly receives and accredits as ministers,
those who attempt to invalidate any of these doctrines,
which we esteem as essential parts of the Christian religion.`"

Would that London Yearly Meeting had been equally careful, a few years afterwards,
to disavow fellowship with those "`ministers`" who did not hesitate to "`attempt
to invalidate`" other doctrines equally "`essential`" to the Christian religion.
