== Chapter V.

[.blurb]
=== The Suits At Law, Consequent On The Hicksian Secession.

There were some results of the Hicksian controversy,
which I would gladly pass by in silence,
were it not that their notoriety and importance in regard to a development of facts,
have made them a necessary feature of the history of these times.
It is a grievous and sorrowful thing,
for religious disputes to be dragged into the arena of courts of law.
When we consider the scope and weight of that doctrine,
that "`the things of God knoweth no man but the Spirit of God,`"
and the fact that the great majority of men of the law are by no
means adequately led and limited by the guidance of that Holy Spirit,
which alone gives true discernment in spiritual things,
how can we expect that (unless overruled by the special providence of the Most High),
they will be able to decide such matters as are connected
with the mysteries of the Heavenly Kingdom,
according to divine wisdom or immutable truth?
Might we not as reasonably look for a satisfactory result,
in sending an abstruse problem of metaphysics to a band of musicians to decide,
or a question of the proper treatment of an occult disease
which had baffled the science of the College of Physicians,
to be determined by the wisdom of a naval court martial?
But so it was, that in the warmth of controversial antagonism,
and the anxiety of trustees to legalize their own position
to advantage of the parties for whom they acted,
several cases occurred in which the disputes in regard to property,
naturally arising from this schism, found their way into the courts,
to the great regret of many Friends,
who looked back upon them in cooler times with sorrow,
lamenting the increase of alienated feeling thus occasioned,
with but little if any result of good.

The first case of appeal to the law after the separation, occurred in Philadelphia,
in the summer of 1828, and was of a very painful nature.
Repeated instances had occurred,
of the Hicksites of Green Street Meeting refusing to accept orders for
the interment of their deceased members from the committee of the Northern
District Monthly Meeting having charge of the Western Burial-ground.
Instead thereof they broke the lock of the gate and made forcible entry.
They alleged that they had their own committee--that the
ground belonged in part to Green Street Monthly Meeting,
which in their view still existed--and that the orders which were offered to them by
those who had possession on behalf of the four other Monthly Meetings of the city,
did not recognize their deceased as members.

No resistance was made to their thus breaking the lock, time after time;
but becoming tired of this mode of entrance, they resolved to have a gate of their own;
and doubtless it would have been better if they had been quietly permitted to proceed,
after a protest against their trespass.
On the 31st of the fifth month, three members of the Green Street Meeting,
with a few laborers,
broke down a part of the high brick wall on the western side of the burial-ground,
and prepared to put up a large gate,
and also erected a small wooden building in the yard.
Being asked, by whose authority they were acting, one of them replied,
"`The best in the world; that of the rightful owners.`"
They were desired to desist, but proceeded in their work.
The mayor of the city being informed of what was going on,
issued warrants for the arrest of the parties,
for having committed a breach of the public peace.

On the hearing,
he required each of them to give their own personal
recognizance in the sum of five hundred dollars,
to keep the peace until the next mayor`'s court.
As they refused to do this, they were committed to prison; but by writ of _habeas corpus,_
were soon afterwards brought before Judge King, of the County Court,
whose political aspirations were supposed to be fostered
by a party opposed to that of the mayor,
and courting the favor of the Hicksites for the sake of their votes.
Several days were occupied in the hearing of testimony.
On the 21st of sixth month, the judge, in a long and labored adjudication of the case,^
footnote:[See [.book-title]#The Friend,# Philadelphia, vol.
i, pp.
292, 293, 295.]
assuming the continued de facto existence of Green Street Monthly Meeting,
notwithstanding its having been laid down by the Quarterly Meeting,
with erroneous explanations of what constitutes a forcible entry or breach of the peace,
and much argument intended to show that important "`assumptions`"
on the part of the prosecutors had not been proved,
and that it was not for him, but for a court and jury, or the Supreme Court of the State,
to pronounce on the guilt or otherwise of the prisoners,
released them from any further security to keep the peace (alleging
that there was no proof of their having broken it),
and discharged them from custody.
The case (I think) was afterwards carried to the Supreme Court,
but abandoned without coming to trial.

During the autumn of the same year, 1828,
complaint was made against David Hilles and Israel
James (the former the Clerk of the Hicksites),
for disturbing Ohio Yearly Meeting.
The trial commenced on the 15th of the tenth month,
and after an investigation during ten days,
on the 25th Judge Hallock delivered his opinion,
and the accused were sentenced to a fine of five dollars each.^
footnote:[See [.book-title]#The Friend,# Philadelphia, vol.
ii, p. 219. Taken from [.book-title]#Bates`'s Miscellaneous Repository.#]
In the similar case of J. Pierce and others,
indicted for producing a riot on the same occasion,
the accused were by the jury found guilty before the court at Steubenville,
after several days consumed in examining witnesses,
and sentenced by Judge Sutherland to a merely nominal penalty--Friends having through
their counsel intimated their wish only for the protection afforded by the law,
and recommended the defendants to the clemency of the Court.
The sentence accordingly was imprisonment for thirty minutes,
and a fine of six cents each, with costs of the prosecution.^
footnote:[See [.book-title]#The Friend,# vol.
ii, p. 294, etc.
The account of the trial published by M. T. C. Gould
is evidently very defective and fallacious.
A full account may be seen in [.book-title]#Bates`'s Miscellaneous Repository.#]
Notwithstanding the lenity of the penalty, this case was carried, on writ of error,
to the Supreme Court of the State of Ohio,
and there the judgment of the court below was reversed as irregular,
"`for the reason that there was no legal endorsement
upon said indictment by the prosecutor +++[+++B. W. Ladd]
as security for the costs,`" his name having been "`endorsed`" on the back of the instrument,
instead of "`at the foot thereof,`" as directed, in very bad English, by the law.^
footnote:[[.book-title]#The Friend,# vol.
iii, p. 15.]
It is to be feared that Elisha Bates weakened himself,
and increased the tendency to an eventual falling
away from the truth which he had once known,
by the great activity of zeal with which he pursued these judicial contests.
The next cases, requiring a brief notice, were within the State of New York.

Although the Hicksites had taken possession of more than three-fourths
of the meetinghouses within Philadelphia Yearly Meeting,
and most of those in the eastern part of the State of New York,
including ten out of the eleven meetinghouses in West Chester County;
and although they already had possession of the principal
portion of a large school fund there,
yet they were not satisfied without going to law for more.
They instituted a suit to obtain possession of the Yearly
Meeting`'s boarding-school at Nine Partners in Duchess County,
and seized fifty-five acres of the farm belonging to it.
But they did not succeed in obtaining possession of the school.^
footnote:[[.book-title]#Foster`'s Report,# vol.
i, p. 189.]
In the Court of Oyer and Terminer of the County of West Chester,
they brought suit to recover the amount of a loan of five hundred dollars, with interest,
which had been loaned by the treasurer of the school-fund above-mentioned (James Field,
who was one of their party) to Charles Field, who remained with Friends.
Much testimony was offered by the defendant on the various features of the separation,
to show that the Hicks party had really separated from the Society of Friends.
But the Court ruled out as irrelevant, all testimony regarding doctrines.
The judge, "`in his charge to the jury,
cleared the whole question of everything but the
facts of the case,`" and gave it as his opinion,
that the plaintiff must recover,
on the ground of his always having acted as the treasurer of the fund,
and the fact that he was supported in his claim by the majority of the owners of it!
The jury, coinciding with the judge, gave a verdict accordingly for the plaintiff.

But of all the suits at law on these questions, none were so important,
in an historical point of view,
as the one instituted in the Court of Chancery of New Jersey,
respecting a school-fund belonging to Chesterfield Preparative Meeting at Crosswicks.
The examinations, cross-examinations, and pleadings in this suit were published,
occupying three large octavo volumes,
and developing a great amount of information respecting the history, doctrines,
and discipline of the Society from early times.
In this case suit was brought by J. Hendrickson,
the treasurer before the separation (who remained with Friends), against T. L. Shotwell,
one of the Hicks party,
for the amount of a mortgage belonging to the school-fund of that Preparative Meeting;
and Stacy Decow,
who had been appointed as treasurer by the Hicksite meeting subsequent to the separation,
interpleaded with a claim for their right to the fund, and consequently to the mortgage.

After the reading of the pleadings was completed,
the depositions of witnesses on each side were taken at Camden,
opposite to the city of Philadelphia, before J. J. Foster,
an Examiner in the Court of Chancery of New Jersey, commencing on the 2nd of sixth month,
1830.
It soon became manifest that a wide field was opened for a development of all
the circumstances throwing light on the causes and various features of the separation.
Many witnesses were examined at great length on both sides,
and subjected to close and rigid cross-examination by astute lawyers,
aided by vigilant and active partisans on the respective sides.
The most prominent of these witnesses on the part of Friends, were Samuel Bettle,
William Jackson, Thomas Evans, Samuel Parsons, Thomas Willis, Joseph Whitall,
and William Evans; and on the part of the Hicksites, were Abraham Lower,
Halliday Jackson, Cephas Ross, John Barrow, and Josiah Gaskill.
The taking of their evidence was continued, with sundry intervals,
from the date above-mentioned till the 13th of fourth month, 1831,
when it was completed.^
footnote:[See the testimony in full, in [.book-title]#Foster`'s Report of the Examination at Camden,#
two volumes, Philadelphia, 1831;
also the [.book-title]#Arguments of Counsel and Decision of Court
of Chancery of New Jersey# in same case,
1834.]
The first witness examined was Samuel Bettle, of Philadelphia, whose testimony,
from the position he held as clerk of the Yearly Meeting,
and his long experience in the affairs of the Society,
with a mind of great acuteness of observation, took a wide range,
developing the doctrines of Friends, and the causes tending to produce the separation,
with the immediate facts of the separation itself,
with which he was personally familiar.^
footnote:[If there was a weak point in his testimony,
it seems to have been in too much timidity as to an avowal of official approval,
by the Society, of the writings of William Penn.
He was probably led into this timidity by observing the
handle so constantly and insidiously made by the Hicksites,
of William Penn`'s [.book-title]#Sandy Foundation Shaken.#
See [.book-title]#Foster`'s Report,# vol.
i, p. 77.]

It was a favorite dogma of the Hicksites, at that time,
that each Yearly Meeting was a perfectly independent and irresponsible body;
a dogma which has been revived in later times by some who were
equally engaged in revolutionizing the doctrines of the Society,
though in an opposite direction.
In the course of Samuel Bettle`'s cross-examination,
he was asked by the counsel of the Hicksites,
"`Is not every Yearly Meeting independent of all other Yearly Meetings?`"
His answer was comprehensive, thus: "`I do not conceive that they are; and if desired,
I will explain my reasons.
The Society is one general body, holding one common faith,
and my rights are not confined to the Yearly Meeting at Philadelphia;
but if I was to go into any other Yearly Meeting, I have claims and rights there.
So it may be perceived, I am a member of the great body of the Society of Friends,
and have general rights.
But if I depart from the generally accepted faith of that body of Christians,
or if I violate its church government, I forfeit those rights.
And I consider, what is true of one is true of many, call themselves what they may;
hence, Yearly Meetings are not isolated, wholly independent bodies.`"

The next witness was William Jackson, of London Grove, in Pennsylvania,
then nearly eighty-four years of age;
and I can hardly forbear to record the unusual solemnity which his entrance
into the court produced upon that mixed assemblage of lawyers,
Friends, and people of all sorts.
One and all seemed struck into solemn silence by his venerable patriarchal appearance,
and the weight that was evidently upon his spirit,
and convinced that he was no common character.
He gave his testimony with great seriousness; and when,
in the tedious cross-examination by which the adverse party tried to entangle him,
the lawyer insidiously and profanely asked him:
"`Has the Society of Friends ever held that the world was begotten of
God?`"--he seemed almost to electrify the audience by his indignant reply:
"`It is astonishing to me, that, at this time of day,
such a question should be put to any individual!
Have we all turned unbelievers?`"
In reply to other questions he testified,
that if this suit had been merely on a question of property,
he thought he should not have appeared there; but that his main inducement had been,
that he should be clearly understood on the subject of doctrines--that
our doctrines might in a solemn manner be placed before the public.
And in another portion of his evidence he said that,
"`if a minister of the Society of Friends should, in his public testimony,
depart from the principles or doctrines recognized and held by the Society,
it would be justifiable, under the discipline,
for a Friend to speak of it even in the meeting, at the time of its occurrence.`"^
footnote:[[.book-title]#Foster`'s Report,# vol.
i, p. 107.]

Thomas Willis, of Long Island,
testified to the evidences of doctrinal error given by Elias Hicks as early as 1818,
and subsequently at different times further developed, and of his own endeavors,
at various periods, to reclaim him.
He also went into a detail of subsequent events of the controversy,
and testified to E. Hicks circulating the "`Celestial Magnet,`"
and offering to him a work of Dr. Joseph Priestley.
He was subjected to a very rigid cross-examination,
which occupied between three and four days.
The testimony of Samuel Parsons, also of Long Island,
was mainly in regard to discipline and historical circumstances.
He spoke of having himself labored with Elias Hicks
for his recovery from his unsoundness of doctrine,
as much as fifteen years before that time, and at various times since;
and he testified to the "`hissing, shouting, stamping,
striking the floor and benches with their canes and umbrellas,`"
which took place on the part of the disciples of Elias Hicks,
in the New York Yearly Meeting of 1828, when he (the witness), as clerk of the meeting,
was endeavoring to read his minute, and when Elias,
after having at first said something to appease the tumult, turning to the assembly,
desired them not to let him read it.
This witness was closely cross-examined respecting
facts which had occurred during the controversy,
and also in regard to disciplinary questions,
and the doctrines of early Friends as bearing on the sentiments of Elias Hicks.

Joseph Whitall, of Woodbury, New Jersey, followed,
with a lengthy examination and cross-examination.
He testified to E. Hicks having declared to him, in 1822,
his belief that Jesus Christ was only a man, the son of Joseph and Mary,
and that to pray to Him was "`an abomination;`" also,
that at a subsequent interview he had declared his sentiment,
that "`Christ was no more than an Israelite.`"
The circumstances of the separation were pretty fully gone into.
The cross-examination was protracted and intricate,
with a determined effort to entangle him in regard to the doctrines of the Society;
but being preserved inwardly watchful,
he proved himself more than a match for the counsel`'s ensnaring stratagems.
His testimony, as recorded, is even now exceedingly interesting and instructive,
showing how the true principles of Friends will bear
the closest scrutiny of unregenerate men.
Many of his answers eminently tend to confound their subtlety,
and put to shame their attempts to justify infidelity.
His cross-examination extends over thirty-four large and closely printed pages.

Thomas Evans was the next witness examined;
who went into an elaborate description of the circumstances of the separation.
His cross-examination, chiefly regarding the discipline and doctrines of the Society,
occupied about three days.
He was called a second time, and reexamined, toward the close of the proceedings.
His testimony was very close upon the conduct of the Hicksite party.
He averred, among other such things,
that while the case of the appeal of Leonard Snowden against the action
of Green Street Monthly Meeting was before the Quarterly Meeting,
some of the members of the Monthly Meeting would
speak from fifteen to thirty-two times in one sitting,
to the great interruption and protraction of the business.
He declared his belief that if a Yearly Meeting should reject
and deny the doctrines held by the Society of Friends,
it would of course, cease to have a just right to the property.^
footnote:[[.book-title]#Foster`'s Report,# vol.
ii, p. 401.]
It seems needless to further specify the distinct
features of the testimony of each of the witnesses;
but it may be well to add, that William Evans,
who (as well as John Paul) was examined toward the close of the proceedings,
testified respecting the transactions of the Meeting for
Sufferings in regard to what was called "`the Creed,`" etc.,
and related the occurrences in the meeting of representatives in 1827,
respecting the nomination of a clerk for the Yearly Meeting,
besides various other circumstances and features of the separation.
The cross-examination of this witness aimed at discovering
the name of the individual who originally drew up the extracts
called a "`Creed;`" but did not succeed in obtaining it.

On the part of the Hicksites, the first witness was Abraham Lower of Philadelphia;
who testified respecting the circumstances, which, according to his view,
caused and characterized the separation.
His testimony was of such a description as to induce a very long and close cross-examination,
which lasted thirteen days,
and of which the printed statement occupies one hundred and three pages.^
footnote:[_Ibid.,_ vol.
i, pp 375 to 478.]
Personal invective, mere hearsay, and harsh epithets and charges upon Friends,
with wandering, incoherent, impulsive harangues,
were so frequent a feature in his answers,
and they were often so totally unconnected with the queries put to him by the counsel,
that he had to be several times reminded that he was there as a witness,
and not as an advocate, and desired to keep to the questions put to him,
but to very little purpose.
The most simple questions would be answered with evasion and prevarication;
and he persisted in an entire refusal to answer any questions on doctrines,
or what he called spiritual matters,
alleging that they were things which a temporal court had no business to meddle with,
and thus shielding himself from being drawn into any avowal
of what he or his friends did or did not believe.

Cephas Ross, of Bucks County, Pennsylvania, was the second witness for the Hicksites.
His testimony was mainly a statement of his view of the transactions of the Yearly
Meeting of 1827 (which he had then attended for the first time in his life,
as he said), and of the separation in Bucks Quarterly Meeting;
but he declined answering questions respecting the discipline,
as his predecessor had done in regard to doctrines.
Indeed he evidently felt himself very ignorant on such subjects,
or on the common usages of the Society;
and voluntarily acknowledged that he had twice married out of the order of the Society,
and that on one occasion,
having been provoked by one whom he called "`a bully
in the neighborhood,`" he had "`fought`" him;
and had to make condemnation thereof to his Monthly Meeting!
The third witness on the part of the Hicksites was Halliday Jackson, of Delaware County,
Pennsylvania;
who testified at considerable length respecting what he considered a series
of oppressive transactions on the part of the Elders of Philadelphia.
In a much more intelligible and plausible manner than either of the two preceding witnesses,
he detailed, from his own standpoint, the occurrences in the Meeting for Sufferings,
the Select Yearly Meeting of 1827, and the general Yearly Meeting of the same year.
According to his statement,
out of about 26,000 members of Philadelphia Yearly Meeting before the separation,
about 18,500 went with the Hicks party.
But this statement was contradicted by Thomas Evans,
who showed that it was erroneous in several particulars.

The testimony of this witness contained much that was merely hearsay evidence,
and he was particularly harsh on Ann Jones and other English ministers.
The measures taken by Friends to retain possession
of the Asylum for the Insane near Frankford,
were particularly animadverted on.
His testimony in vindication of the action of the Hicksites in separating,
and his allegations against the validity of the proceedings of Friends,
evinced very considerable ability,
as he steadily kept out of view the all-important subject of doctrines,
refusing to answer any questions of that nature.
He candidly acknowledged that various acts of his party were unauthorized by the Discipline,
but alleged that they were justified by the necessity of the case,
a revolution existing in the Society.
He spoke largely respecting this alleged necessity (and perhaps with reason,
if such necessity had existed), but failed to prove a necessity,
against the strongly contradictory allegations of the other side,
including the all-important matter of doctrines.

Indeed, if no unsound doctrines had been at the very basis of the question,
and the statements of this witness were all to be taken for granted,
notwithstanding the rebutting testimony of the opposite party,
it might well be supposed that the Hicksites were
not without justification in separating as they did.
But the determined silence of all these witnesses
in regard to the doctrines manifestly at issue,
doctrines fairly proved to have been fundamental in the Society of Friends,
threw a dark veil over the whole of their testimony,
as it was justly and easily understood to imply that they were not willing to
own the sound principles which were abundantly testified to by our ancient Friends.
This witness several times voluntarily expressed that it was for the Court of Chancery
to decide which was the Society of Friends--a very unsafe avowal under any circumstances.

Charles Stokes, of New Jersey,
was examined and cross-examined with reference to local
circumstances within Burlington Quarterly Meeting,
and regarding the appointment of clerk in the Yearly Meeting of 1827.
His answers seemed very evasive and illusory,
and he appeared to advocate the decision of matters by majorities.
John Barrow, of New York, the clerk of the Select Yearly Meeting of the Hicksites there,
testified principally respecting the transactions at that Yearly Meeting in 1828,
and on some points of discipline.
According to his testimony,
the institution of the two suits at law within that Yearly Meeting
had been discountenanced by the authorities of the Hicksite body.^
footnote:[See [.book-title]#Foster`'s Report,# vol.
ii, pp.
265 and 279.]
They had, however, already obtained possession, as before mentioned,
of most of the property of the Society within that Yearly Meeting.
George H. Burr, of Philadelphia, was their next witness,
who had taken the pains to count the relative numbers of the male
attendants at the respective Yearly Meetings in Philadelphia,
in 1828, the year after the separation.
His testimony was confined to this subject;
and according to it there were of those attending at Green Street an average of 1150,
and of those attending at Arch Street from 750 to 831.

Then followed Josiah Gaskill of New Jersey,
whose testimony was chiefly relative to local circumstances in
Burlington Quarterly Meeting and Chesterfield Preparative Meeting.
His cross-examination showed much ignorance of the usages of the Society of Friends.
He advocated a judgment by majorities,
thought that the clerk of a meeting had the liberty to "`decide as he thought right,`"
and expressed his opinion that "`every member`" has "`equal right to a voice.`"^
footnote:[See his ignorance of the practices of Friends animadverted
upon by the counsel, p. 313, vol. ii, [.book-title]#Foster`'s Report.#]
He was succeeded by James Brown, also of New Jersey,
whose testimony was of no great importance;
chiefly of local disciplinary and numerical matters,
and his answers generally quite brief.
These were the whole of the witnesses produced on the part of the Hicksites.
How that party could suppose that their evidence, defective as it was,
could go any way with the Court of Chancery towards counteracting
the powerful and copious testimony on the other side,
or towards the convincing of thoughtful and reasonable men that
they were occupying the true ground of the Society of Friends,
is only to be accounted for by the power of party spirit to blind men`'s judgments.

The examination of witnesses closed on the 13th of the fourth month, 1831.
The newly elected governor of the State, and ex-officio Chancellor, who,
before his election as governor,
had been of the counsel of one of the parties in this cause,
now called in to his assistance, agreeably to the practice of the court,
the chief justice and one of the associate judges of the Supreme Court of New Jersey,
viz., Chief Justice Ewing and Judge Drake, before whom the cause was heard.
They held the matter under advisement until the seventh month, 1832,
and then gave separate opinions in favor of Hendrickson,
the treasurer on the part of Friends.
Chief Justice Ewing, in his opinion,
chiefly dwelt upon the historical facts and disciplinary features of the case;
and the following sentence towards the close, briefly sums up his judgment:
"`Upon the whole, I am brought, by the most careful, faithful,
and minute investigation of which I am capable, to the result,
that the Arch Street Meeting was, and the Green Street Meeting was not,
the Philadelphia Yearly Meeting of the Society of Friends.`"
He added, as the necessary consequence,
that the Hicksite Preparative Meeting of Chesterfield,
"`was not the Chesterfield Preparative Meeting of Friends at Crosswicks,
meant and mentioned in the establishment of the school-fund;`" and therefore
concluded by recommending the Chancellor to decree in favor of Joseph Hendrickson.

Judge Drake reviewed the evidence as to facts and discipline,
but dwelt more largely on the doctrines involved in the case..
He brought into view the persistent vagueness and evasiveness of
the Hicksian evidence in regard to their religious belief,
and justly remarked:
"`There is nothing characteristic in '`a belief in
the Christian religion as contained in the New Testament.
All sects of Christians, however widely separated, unite in professing this.`"
After speaking of the doctrines of the divinity of Christ,
and the authenticity of the Scriptures, he said: "`Upon reviewing the testimony,
I am satisfied that the Society of Friends regard these doctrines as essential,
and that they have the power, by their discipline,
to disown those who openly call them in question.`"
Toward the close, he says,
in reference to the reticence of the Hicksites on their doctrines, "`It is enough,
that it is not made to appear that they correspond with the religious faith of Friends.`"
And he concludes, as Chief Justice Ewing did,
with a recommendation to the Chancellor to decree that the
said bond is due and payable to Joseph Hendrickson.
The Chancellor issued his decree accordingly, on the 10th of the seventh month, 1832.

From this decision the Hicksites appealed to the Court of Errors and Appeals;
and before this court the case came on for a hearing on the 17th of the seventh month,
1833.
About two weeks were occupied in reading the evidence,
after which the counsel of the respective parties occupied between
two and three weeks in delivering their speeches before the court.^
footnote:[The opinions of the judges and the speeches of the counsel,
are given in full in [.book-title]#A Full Report of the Case of Decow and Hendrickson v. Shotwell,
in the Court of Appeals at Trenton, 1833.#
Philadelphia: P. J. Gray, 1834.]
G+++.+++ D. Wall, counsel for the Hicksites,
commenced his arguments with an insidious attempt to show
that "`this court is the great Areopagus of the State,
sitting, not merely in a judicial capacity, tied down by the strict rules of the law,
but as a legislative body,
which has full power to act according to its own wisdom;`" alleging
that in this respect it was like the English House of Lords;
a position which, however flattering to the court, was very illusory and unsafe.
After this, he labored greatly to prove that ancient Friends not only had no creed,
or fixed declarations of faith, but that they varied in faith one from the other,
respecting the Father, Son, and Holy Ghost, the doctrine of the atonement,
and the authority of the Scriptures,
not even expecting or looking for any uniform belief in these respects.
But his arguments were fallacious and overstrained,
with entirely erroneous deductions from the writings of early Friends.
He pretended a contrariety where there was none,
and assumed a latitude which did not exist.
He greatly eulogized Elias Hicks,
but kept his erroneous sentiments as much as possible out of sight.

George Wood, one of the counsel for Hendrickson, on the part of Friends, followed,
refuting Wall`'s specious misrepresentations in regard to doctrines,
as well as the law of the case,
proving that Friends had often put forth declarations of faith,
and showing what was their faith on the three points mainly involved.
He animadverted pretty strongly on the persistent refusal
of the Hicksite witnesses to state their doctrines,
while those of Hendrickson had clearly developed what were the doctrines
held by the early Friends and the Society from the beginning to that day.
He opened out the fallacy of the pretense that the Society had no creed or belief;
and fastened upon the Hicksites as a society,
the responsibility for the erroneous sentiments enunciated by Elias Hicks.^
footnote:[See p. 422 of the [.book-title]#Trenton Report of Pleadings before the Court of Appeals.#]
He then went on to show that property of religious societies belongs to the true society,
and not being private property,
is not divisible on the occasion of schisms--that the courts of law had
in many instances (some of which he cited) protected the portion of a
church or religious body which adhered to the original basis,
even though a minority--vindicated the disciplinary proceedings of the elders in Philadelphia
in regard to Elias Hicks--and showed clearly that the support given to him was the prominent
cause of all the measures of that party resulting in the separation.

Theodore Frelinghuysen, also counsel for Friends, followed Wood in argument,
commencing by demolishing Wall`'s assertion that this court,
like the House of Lords in England, is not tied down to certain rules,
but can act as a legislative body, according to its own wisdom.
He went on to show that the allegations of the Hicksian
witnesses respecting the belief of early Friends,
were similar to the imputations cast upon them in
their own day by the adversaries of the Society,
but that our ancient writers were in reality consistent with each other,
and their doctrines in harmony with Holy Scripture.
After proving them sound in the three doctrines mainly in question,
he proceeded to show that these doctrines were considered among their fundamental ones,
and that the difference concerning these doctrines was the real cause of the separation,
not the frivolous things that the Hicksites attempted to show had caused it.
Frelinghuysen however was not quite as clear in his
apprehension of the true doctrines of Friends,
as his colleague George Wood had been; making use of some unguarded expressions,
calling the Bible the Word of God,
and implying that Friends held the doctrine of original sin the same as other societies.

These matters however were not brought forward prominently,
and perhaps had not claimed much of his attention.
He eloquently defended the course of the Philadelphia
Elders in their treatment of Elias Hicks,
showing that they did their duty as faithful watchmen over the safety of the church.
He asserted that by the secession the Hicksites lost all claim to be the Society,
but did not invalidate the rights of those who remained,
and that the property of the Society is not of personal or individual ownership,
but belongs to the Society as such, for certain purposes,
and cannot be alienated to the advantage of seceding parties.
"`The Society of Friends,`" said he,
"`acknowledge certain great principles of religious faith to be essential and fundamental.
Therefore, if a community of members depart in a body from these principles,
they possess not the traits of membership, and belong not to the Society of Friends.
That which would lawfully cut off individual members,
will bar the door effectually to the fellowship of any body, however large,
advancing pretensions to the Society of Friends, and denying their faith.`"

Samuel L. Southard, counsel for the Hicksites, wound up the arguments by a closing speech.
He argued that the Hicksites were a majority,
and ought to have the property on that account, leaving out of view the fact,
that they were greatly in the minority of the whole Society.
He claimed that they were not bound to disclose their faith or doctrines,
and tried to make it appear that the light within was the whole of Friends`' fundamental
doctrines--nothing else of much account--that the Society was a pure democracy,
and that in extreme cases majorities must rule.
"`We profess,`" said he, "`to be Christians, and to revere the Scriptures,
and no earthly tribunal should require more.
We profess to be Friends, and beyond that, no cognizance can be taken of our sentiments.
We profess to act in the order of the Society, and nothing more can be demanded of us.`"
Empty declamation and false assumptions characterized much of his argument,
in which he abused the Philadelphia Elders with the old
story of irregular partisan oppression of E. Hicks,
but studiously avoided noticing the charges of gross errors of doctrine,
publicly uttered, on which their treatment of him was based.
He endeavored to make it appear that the "`Orthodox`" now were like George Keith formerly,
advocating the same errors; and toward the close he said,
"`Our opinions are not to be inferred from those of Elias Hicks;`" but
omitted to notice how clearly it had been proved that all the disturbances
of the secession had arisen from their adherence to E. Hicks when he was
repeatedly charged with gross unsoundness in the Christian faith.

Southard completed his argument on the morning of the 14th of eighth month, 1833,
and in the afternoon of the same day the Court resumed the consideration of the cause,
and by a vote of seven against four, determined to affirm the decree of the Chancellor.
The document affirming the decree and dismissing the appeal, was issued the next day,
Governor Williamson appending thereto, by permission of the court,
his individual solicitude for an amicable settlement of all matters in dispute.
I have deemed it right to go somewhat at large into a description
of the main features of this famous suit,
not as approving of the inception of it, but under a view of its wide scope,
and the belief that in its progress, through the overruling hand of Divine Providence,
important developments were made respecting the history, doctrines,
and discipline of the Society, which are fraught with interest and instruction;
though they can only be imperfectly indicated by a sketch like that I have here attempted,
referring the reader to the official documents alluded to, for further information.

In this legal controversy,
statements were produced of the relative numbers of members on each side, which, however,
differed very considerably.
The account submitted by Halliday Jackson on the part of the Hicksites made it appear
that the whole number of members of both parties in Philadelphia Yearly Meeting in 1829,
was 26,258, of whom 18,485 were Hicksites, 7344 were "`Orthodox,`" and 429 "`neutral.`"
The statement exhibited by Thomas Evans on the other side, was not a complete one,
including only six of the eleven Quarterly Meetings.
In these six, the aggregate number appears to be 7241 Friends called Orthodox,
and 6123 of the Hicksian party.
But in the five other Quarterly Meetings the Hicksites probably had a considerable majority.
So that there is not much ground to doubt that in the whole Yearly Meeting of Philadelphia,
the Hicksian party was somewhat the larger number.
In the Yearly Meeting of New York, the case was probably similar,
though with a rather larger preponderance of the Hicks party.
The statement exhibited by one of their witnesses, John Barrow,
makes the total number of members of New York Yearly Meeting
19,302 (exclusive of three small meetings not reported);
of which the Hicksites claimed to have 12,532,
leaving 5913 for the "`Orthodox,`" and 857 "`neutrals.`"
But all these enumerations are unreliable.

In Baltimore Yearly Meeting the Hicks party had a large preponderance;
but in Ohio they seem to have only had a proportion
of from one-third to one-half of the whole;
while in the large Yearly Meeting of Indiana they were comparatively but few;
and in those of Virginia, Carolina, and New England there were scarcely any.
They must have been decidedly a minority of the whole Society even in the United States,
and still more so in a computation including the
members in Europe at the epoch of the separation.
The whole Society in Europe and America then probably fell little short of 95,000,
from which the Hicksian separation may have taken off about one-third.
