== Chapter VI.

[.blurb]
=== The "`Beacon`" Schism.

Well might the ways of Zion mourn,
in a contemplation of the desolating scourge which
had swept so many away from the faith of the gospel,
and led them to unite with those who were denying "`the Lord that bought them.`"
But we have henceforward to contemplate the more plausible,
though equally disastrous working of an opposite spirit,
or rather of the opposite workings of the same spirit in another form.
As early as 1818, and perhaps for some few years even before that,
there had plainly appeared in the Society in England,
an increasing tendency to promote an outward superficial system of religion,
based on human learning and research, rather than inward spiritual experience.
This tendency, I believe,
was unconsciously or unwatchfully promoted by that honorable and worthy man, Henry Tuke,
of York, some years before the above date,
in publishing his well-known treatise on the principles of Friends
without any recognition of the great doctrine of the Holy Spirit`'s
immediate teachings being the primary rule of faith and practice,
but deducing all our testimonies exclusively from the Holy Scriptures.
His object doubtless was to show the agreement of our profession with Scripture;
which was well;
but he does not appear to have perceived the danger
of excluding that all-important spiritual groundwork,
or of tacitly leaving it out of view.
His unwary example was wonderfully followed and enlarged upon by many in after years.

Accordingly,
about the year 1818 there was proposed for the Yearly
Meeting`'s boarding-school at Ackworth,
the introduction of a systematic easy method of teaching and expounding Holy Scripture,
and catechizing thereupon, as the basis of religious instruction,
after the practice pursued in other communities,
and altogether different from what Friends had formerly been accustomed to,
or had thought it safe to depend upon.
Joseph John Gurney is said to have been the chief promoter of this change.
Many friends became alarmed.
John Barclay, though then quite a young man, and but recently escaped, himself,
from the allurements of the world and the entangling
results of worldly education and associations,
saw with pain the nature and dangerous tendency of this innovation.
Under the pressure of solicitude for the safety of the Society,
he addressed three letters on the subject to two influential
members of the committee having charge of the school,
which were published after his decease.
They bore a noble testimony to the superior efficacy of that divine knowledge which
results from faithful obedience to "`the word nigh in the heart`"--"`the engrafted word,
able to save the soul`"--over all the product of intellectual
study and mere literal acquaintance with the Scriptures;
and advocated that kind of instruction which is founded
on a real living concern for the welfare of the children,
and has the immediate leading and prompting of the Spirit of Christ,
to give it authority and efficacy.

In one of these letters, he brought forward by way of illustration,
the instance of his worthy ancestor Robert Barclay; who declared,
"`that he did not come to receive the truth by strength of argument,
or by a particular disquisition of each doctrine,
and convincement of his understanding thereby,
but by being secretly reached by the life,`" having his
heart touched by that "`secret power,`" even in silence;
and so finding the evil weakening in him, and the good raised up,
he came to hunger more and more after its increase, and perfect redemption;
adding his testimony,
that "`indeed this is the surest way to become a Christian;`"
and that afterwards the needful knowledge would not be withheld.
John Barclay saw plainly that there was great deficiency among the youth,
in regard to an acquaintance with the principles of our profession;
but in looking at the proposed plans,
he declared that he "`lamented the remedy more than the disease; because,`" said he,
"`then we stand in danger of having a set of young formalists rise about us,
whose heads are more likely to be filled with notions,
than with that nothingness of self,
which is as truly the introduction to all right knowledge on these subjects,
as the other is a snare and a stumbling-block in the way of it.`"

This seems like a truly prophetic view of what was coming,
and has since so manifestly come, like a sweeping flood over all parts of the Society.
In one of the letters,
after earnestly expostulating against the new project
of learning religion "`by rote,`" he exclaimed,
"`Oh, what will all this come to?
Can I call this anything better than an apostasy from the
Life and Power of the substantial eternal Truth,
as it was revealed to our forefathers in the silence of all flesh,
as they waited on the Lord?
Can I say anything less of these devices,
than that they strike at the very root and ground and foundation thereof?`"
He lived to see this "`apostasy`" still more sadly developed,
and the "`root and ground`" of our faith still more clearly and fearfully "`struck at.`"
But the sentiments and warnings of such Friends as John Barclay, and Sarah L. Grubb,
Thomas Shillitoe, and George and Ann Jones,
were already beginning to be by no means acceptable
to some who would be leaders of the people,
and were designated by such,
as "`peculiar views,`" and "`narrow-minded,`" though they only went to
sustain the ancient and well-known faith and practice of the Society.

In England the influence of increased wealth and luxury and ease,
was producing the natural result, through unwatchfulness on the part of individuals,
and the unfaithfulness of many of those set as watchmen over the flock.
No positive unsoundness of principle was hitherto officially sanctioned;
yet it is not to be denied,
that for many years the great distinguishing doctrine of our early Friends,
respecting the necessity of holiness and the possibility
of freedom from sin in this life,
known amongst us as the doctrine of Perfection,
as advocated by Robert Barclay and others of that day,
had been gradually disappearing from view,
and had now become practically very much ignored by the great bulk of the members;
as well as our testimony to the paramount authority of the
Holy Spirit as the primary guide in the way of salvation.
Thus the platform of the Society was lowered,
and a downward step taken towards placing it on a
level with other denominations of professors,
yet without any open official advocacy of novel doctrines.
On some other points, too,
there was a prevalent siding or edging towards affinity with the popular forms of religion;
a meeting the world half-way; by which fleshly desires for popularity were gratified,
but at the expense of leanness of soul, and oppression of the seed of life there.
Dwarfishness as to religious attainments had indeed
become a general feature over the Society.

The storm of the Hicksite contention had, however,
roused some from their couches of ease; but, unhappily,
it had also given an opportunity for the arising of a spirit,
through the wiles of the cunning adversary, ostensibly antagonistic to Hicksism,
and loudly declaiming against its dangers, but going to an opposite extreme,
and equally deriving its doctrines from something
else than a true learning in the school of Christ,
through the inward manifestations of His Spirit.
Many, in their horror of Hicksism, were caught with this spirit,
and led into views equally successful in drawing them aside
from really following Christ in the way of His leading.
Hicksism had undertaken to discard all reliance on what Christ
Jesus our Lord did for us outwardly in that blessed atoning sacrifice;
and now the tendency was, on the other hand,
to instill the belief that our early Friends had gone too far,
in making so much of the inward work of Christ,
and that their course therein had laid the groundwork of the errors of Hicksism.
The Hicksites, too, had denied the divine authority of Holy Scripture;
but now the tendency appeared to flow with a high tide to
set the Scriptures up as the primary rule of faith and practice,
and to allege that even the teachings of the Holy Spirit
were to come only through the medium of "`the Written Word.`"

About the time when Elias Hicks`'s course was advancing to its culmination,
J+++.+++ J. Gurney began to publish a series of professedly religious works,
by which this tendency to the opposite errors was rapidly extended
and greatly encouraged over the Society in Great Britain.
Between the years 1820 and 1826, he had published edition after edition of several books,
including his Letter (to Dr. Alderson, father of Amelia Opie) on Christianity,
his Peculiarities (afterwards styled Distinguishing Views), of the Society of Friends,
and his Essays on the Evidences, Doctrines, and Practical Operation of Christianity;
whole editions of some or all of which were gratuitously
distributed among the members and others;
and thus sown broadcast over the land they seemed
likely to pervade every family among Friends,
and vast numbers among others.
The last-named work particularly, first issued in 1825,
and his "`Portable Evidence,`" in 1832,^
footnote:[See [.book-title]#An Examination of the Memoirs and Writings of J. J. Gurney,#
by W. H. Philadelphia, 1856.]
contained many sentiments and modes of thought and expression,
manifestly at variance with the hitherto acknowledged
views and modes of expression in the Society,
and ought to have effectually alarmed the faithful members.

But many were lulled asleep,
and others were afraid to place themselves in an
attitude of conflict with a champion of such wealth,
learning, power, and influence.
Others felt as if the Society was flattered by the approbation
which his works elicited from the world at large.
Whatever may have been his own intentions in this early part of his career,
or however honest he may have been in a belief that he was doing good,
it is certain that the tendency of his writings (proceeding
as they did mainly from an intellectual study of theology,
so-called), was to lead off the Society from the ancient ground,
that Christ within by his Spirit is the great Teacher of his people,
and that a true and saving knowledge of God can be obtained
only through obedience to the successive unfoldings and
purifying operations of that inspeaking Word of Divine Grace;
and on the other hand,
to inculcate the necessity of studying religion by the powers of the human mind.

But the popularity of the writer being very great,
as the brother and coadjutor of Elizabeth Fry,
and the novelty of such writings in the Society being much admired,
the books found ready entrance into Friends`' families, and were greedily perused,
and implicitly believed by many; and a great impulse was thus given to a superficial,
self-active, and self-pleasing form of religion;
and all this was welcomed as an antidote to Hicksism.
Only a few saw through the flimsy veil of learning,
and perceived that unsound sentiments lurked beneath,
and even reared their heads openly to view in the sight
of those whose eyes truly abode under the anointing;
and still fewer were honest and faithful enough to
express their dissatisfaction to the author,
and warn their fellow-members of the danger.
Thus the system of an intellectual study of religion rapidly spread,
and naturally led to great activity of the unregenerate
mind in things belonging to the safety of the soul,
very different from the deep and self-denying views promulgated by our forefathers;
and many soon began to throw off all the trammels of primitive doctrines and testimonies,
and came out boldly against our ancient Friends, in print and in public declarations.

The following warning testimony on the other hand, is quoted by Daniel Wheeler^
footnote:[[.book-title]#Memoirs of Daniel Wheeler,# London, 1842, p. 200.]
as having been delivered by a female minister (supposed to have been Sarah L. Grubb),
in the Yearly Meeting of 1832, viz.: "`In a striking and awful manner,`" he says,
she "`adverted to the permitted visitation of the pestilence (cholera) in this country;
and afterwards she had a very close and powerful testimony to the meeting,
on the present state of our religious Society,
by way of solemn warning of the approaching judgments
of the Lord upon us for the neglect of those things,
which in a peculiar manner, were given us to bear in the early times of our Society,
when Friends were called out from the world to be a separate people.
Her concern was, that we should return to first principles;
but her more especial warning was,
that if there were not a coming down from the heights to which many have climbed,
there were those amongst us who might be compared to the golden vessels of the temple,
such as had really stood the fire, and had not only been rightly filled,
but employed by the Lord to communicate to the people,
who would be permitted to be carried away captives to Babylon.

That there was and is amongst us, a Babel now building,
whose top is intended to reach unto Heaven, which must and will come down;
that there is (though not clearly seen by ourselves),
a peeling and scattering amongst us,
which is clearly shown in the vision and light of the Lord;
and that if we did not repent and return, we should be left very few in number.
But that the Lord would not leave himself without a people, etc.
She spoke farther in reference to some,
who had been rightly gifted to speak the word of the Lord as from the mouth of the Lord;
but who, for want of dwelling low and deep enough, had had their brightness dimmed;
adding, '`when Ephraim spake trembling, he exalted himself in Israel,
but when he offended in Baal, he died.`"`' Daniel Wheeler added,
addressing his family in Russia,
"`If we consider the hundreds who are busily engaged
in turning the attention of the people to the letter,
to the traditions and ordinances of man, '`after the rudiments of the world,
and not after Christ,`' what must be the end thereof?`"

John Wilbur, a minister of Rhode Island,
visited Great Britain in the service of the gospel, in 1831 and 1832,
spending most of the time in England until his return in the beginning of 1833.
Whilst there, very unexpectedly to himself,
his mind was brought into deep exercise and distress by the discovery
of the spirit at work among some influential members,
at variance with the well-known doctrines of Friends.
As he advanced in his religious engagements,
more and more of its insidious workings was brought to his view,
to such a degree that he was led to fear, either a general lapse as a body,
or otherwise a great rent or division.^
footnote:[[.book-title]#John Wilbur`'s Journal and Correspondence,# p. 270.]
Finding this departure so formidable,
on account of the talents and station of many of those engaged in it,
he was brought into great mourning over the flock of God,
even in that land where the pure standard of truth had been
so eminently supported in the days of our forefathers.
He was deeply afflicted in seeing the subtlety of the enemy,
in taking advantage of the Hicksian heresy,
by leading many into the opposite extreme--thus plunging them into
a lapse as fatal on the other side--both these errors being insidiously
defective in relation to the true faith in Christ,
in all his gracious offices for our salvation.
Under the pressure of these apprehensions,
while in London at the time of the Yearly Meeting,
he took an opportunity of opening his uneasiness to J. J. Gurney,
in company with Jonathan Hutchinson, and George and Ann Jones.
But he received no satisfaction from him.

To show his feelings under these circumstances more clearly,
we will quote a few passages from his own account.
In speaking of his attendance of London Yearly Meeting in 1832,
after mentioning that with the exception of having visited the women`'s meeting,
he had been silent through all the meetings for business,
being greatly exercised therein, he says:

[.embedded-content-document]
--

In this meeting,
great professions of faith in the mediation and atonement of Jesus Christ our Lord,
were made, and this profession was abundantly reiterated;
but still I mournfully felt a great want of that precious sweetness and savor of life,
which gives weight and solidity, as well as power, to a meeting;
and without which all the professions of faith, however high and glowing as to words,
are but as sounding brass and a tinkling cymbal.
And I am more and more confirmed in the belief,
that the most full and literally sound acknowledgment may be made,
of faith in the blood and sacrifice of Jesus Christ, our blessed Redeemer,
and without any reserve too,
but still it may be no more than in the oldness of the letter; and that,
for want of believing fully in,
and of being really and practically quickened by the living power of the gospel,
that calls to, and enables to keep the commandments of Christ our Lord,
by whose Spirit and grace we are sanctified, through obedience.

On account of overwhelming afflictions, and weakness of body,
I was not able to attend the concluding sitting of
the Select Yearly Meeting on seventh-day evening;
for my mental grief was such, that I could not refrain from excessive weeping,
after the conclusion of the meetings for discipline; so,
under the kind superintendence of my dear friend George Crosfield,
I went immediately to my lodgings, and retired to my chamber;
where my head was as waters, and mine eyes as fountains of tears,
in weeping for the backsliding of the sons and daughters of my people,
occasioning the face of the beloved to be so turned from us,
in the day of our great necessity.
(Page 124.)

--

Again, after attending the Half-Yearly Meeting for Wales, which was, he says,
a painful meeting to him throughout, he remarks:

[.embedded-content-document]
--

I kept to my chamber +++[+++in the evening],
and there mourned over the state of things in this land;
being fully aware that there are many in the station of ministers, who are,
in great measure, lost, as to the times and seasons,
the openings and the shuttings of the blessed Spirit of the Gospel;
and whose minds seem to be so beclouded and darkened,
that the true shining is not seen to go forth with brightness as in primitive times,
nor as a lamp that should burn through the whole gospel day.

And it is greatly to be feared that there are some
who are leaning too much to their own understanding,
instead of waiting, in patience and meekness, on Jesus Christ, the great minister,
who always keeps the key in his own hands, and openeth only when he will,
and to whom he will So I continue to mourn,
and to feel like adopting the prophet`'s language of grief, as I pass through this land,
"`How is the gold become dim?
How is the most fine gold changed?
The stones of the sanctuary are poured out in the top of every street!
The precious sons of Zion, comparable to fine gold,
how are they esteemed as earthen pitchers, the work of the hands of the potter?`"
For lo! some who have shone apparently as stars of the first magnitude,
seem to be in danger of a total eclipse!
The outward standing and influence of some is such,
that the case seems almost if not entirely irremediable,
and what the result of things will be, is difficult to foresee.
But many there are among this people,
who are truly awakened to serious and fearful apprehensions,
lest this Society should be shaken from its foundation.
(Page 137.)

--

[.offset]
A few months afterwards, he remarks:

[.embedded-content-document]
--

A disposition is making its appearance in divers places in this nation,
and among Friends, to think very little of the cross of Christ, practically,
and to plead for liberality, both of faith and practice;
the perceptible influence of the Holy Spirit is mournfully
deprecated by many members of our Society;
some of them in conspicuous standing,
are now disposed to put the Scriptures in the place of the Spirit;
and seem ready to hold them as the only rule of faith and practice,
or guidance of Christians and notwithstanding they
fully acknowledge the propitiatory sacrifice,
with its blessed effects for the remission of sins, and place great dependence upon it,
yet at the same time, Christ crucified is to them, as to the Jews and Greeks formerly,
to the one a stumbling-block, and to the other foolishness.
And there is much reason to fear, that these wise and learned professors under our name,
who seem disposed to look down rather contemptuously upon the old sort of Friends,
are designing to bring about a change in some of
the prominent and essential doctrines of our Society.
(Page 150.)

--

At London and Middlesex Quarterly Meeting, which was "`very full and large,`" he says:

[.embedded-content-document]
--

Dear Ann Jones was exercised in solemn supplication,
and William Allen and Daniel Wheeler, in testimony, acceptably; but as for me,
I sat silently, under a sorrowful sense of the state of things in this land;
for it is clearly to be felt and seen, that among this people under our name,
there are two armies arrayed, army against army,
lifting up their weapons one against the other;
and great struggles are plainly to be felt and seen,
by those whose eyes are happily anointed by the finger of Jesus.
It is seen also, that instead of one Lord, one faith,
and one baptism there is a diversity of faith,
as it regards the ministration of Him who is one, by his holy spiritual baptism,
and as to the worship of the true tabernacle.
And it is greatly to be feared that this strife will
not always be kept within the secret chamber,
and subdued, without the exposure of Antichrist, and his kingdom,
and without a storm of the elements in which he worketh.
And much commotion, and thunderings, and lightnings,
and earthquakes will be seen and heard in divers places;
and the tabernacle of those who have slidden from the sure foundation, the Rock of Ages,
however lofty and beautiful to look upon, will be thrown down,
and removed out of the way,
and their place will be known no more in the heritage of the Lord`'s spiritual Israel.
(Page 157.)

--

Under these sorrowful apprehensions,
and in deep solicitude for the safety of the Society,
John Wilbur addressed a series of letters, six in number, to his friend George Crosfield,
an Elder of Liverpool,
for the purpose of developing the grounds of his exercises and concern,
and with a desire that the danger which threatened might be averted.
George Crosfield afterwards published those letters on his
own responsibility (though with John Wilbur`'s knowledge),
believing with many other friends who had seen the manuscripts,
that they were eminently adapted to the state of the Society at that date.
A letter from Margaret Crosfield to John Wilbur,
written while the letters were in process of being printed,
contains the following development of their motives
in thus undertaking the publication of them.

[.embedded-content-document.letter]
--

My mind is very well, and resolute in carrying forward the publication of these letters,
believing the very fulness of time is come for something of the kind to be given forth,
for the comfort and encouragement of many faithful Friends,
the strengthening of the weak and wavering, and the instruction of the ignorant;
and I am satisfied, in that it has in any degree,
fallen to our lot to assist in raising again the ancient standard of Truth in this country,
where George Fox so faithfully labored; and that which it will expose us to,
from loose and careless professors, we are willing to bear for Jesus Christ`'s sake.

--

These six letters to George Crosfield appear to have been
published by him while John Wilbur was absent in Ireland,
in the autumn of 1832.
The first letter gives a general view of the importance of steadfastness
on the part of Friends to the testimonies entrusted to them,
with the expression of his earnest desire that the Society might hold on its way,
and continue faithful in bearing testimony to the
spiritual nature and design of the gospel.
The second letter was in regard to the fall of man,
and his redemption through the atoning sacrifice of Christ,
and man`'s cooperation with the offers of his grace,
by repentance and submission to the sanctifying and regenerating efficacy of his Spirit;
and concluded with the following salutary expressions:

[.embedded-content-document.letter]
--

Then how needful it is to have a full belief in the doctrines of Scripture,
and in every part of them; not merely assenting to some and passing slightly over others,
for fear that a practical and living belief in them
should lead us to much pain and conflict of spirit,
and to the mortifying of the will of the flesh.
Then let everyone come down and prove himself, and examine by the light of Christ,
all the hidden and dark avenues of his heart,
remembering that every secret thing must be opened
and brought to judgment in the day of Jesus Christ.
And oh, how desirable, that when that day shall come upon every one of us,
we may submit to it, while there is yet tenderness in our hearts,
so that a spirit of unbelief in any one of these great doctrines
of life and salvation may never be entertained;
that none of the great truths of the gospel may be looked upon with indifference,
but that every one of us may be so quickened and made alive unto God,
by the resurrection power of Jesus Christ,
as to be furnished and blessed with the perceptive and all-instructive
guidance and influence of his Holy Spirit.

--

The third letter showed the frequent tendency there
had been in the professing Christian Church,
to go off the straight track of the doctrine of the gospel, on one side, or on the other,
through the artful wiles of the enemy;
how George Fox and his contemporaries were instrumental in the Lord`'s
hand for the revival of the pure gospel covenant and doctrines,
and, having Christ their captain with them,
were enabled to stand against all the fury of the adversary,
striving to lay waste and paralyze their testimony; yet that some,
even in those early days, giving way to spiritual pride and the will of unslain self,
were carried away into by-paths; and again many in modern times had been,
through the same subtlety of Satan, deceived, and even led to suppose,
or to profess that they supposed,
that our first Friends did not believe in the true divinity
and reconciling sacrifice of our Lord Jesus Christ;
than which a greater perversion can hardly be imagined.
He entirely contradicts such assertions of the Hicksites,
showing their utter groundlessness, and declares his belief,
"`that the more true spiritual Christianity a man has,
the better will he be qualified rightly to see and to estimate the doctrines of Scripture,
relative to the outward coming and offices of Jesus Christ.`"

The fourth letter discourses more at large on the Hicks secession in America,
showing how the devil,
anxious to make an inroad upon a people whom he knew to
be tenacious of their great principle of the Light of Christ,
artfully contrived a kind of compromise with them,
so as to allow them to retain this distinguishing article,
if he could but induce them to deny the proper divinity and atonement of Christ;
knowing that, thus drawn aside, they would not then, in the very nature of things,
be sharers in the true light of Christ within them, and walk in it,
whatever their profession of it;
but would be rendered liable to mistake his false radiance for the real light.
And succeeding in this scheme with very many,
he filled their mouths with the cry of "`the light! the Spirit!
the Spirit of the Lord!`"--and this partly for the purpose,
that thereby others might be brought even to loathe
the very name of Christ within the hope of glory,
or Christ in spirit, by witnessing His name, in this part of the covenant,
so continually brought forward and taken in vain by those well known to be autichristians.
Because, therefore,
the Socinian or Hicksite has sinfully denied the divinity and atonement of Christ,
shall we unnecessarily, and sinfully too,
abandon everything else relative to God`'s salvation,
that so we may establish what they deny;
as if it were possible for us to obtain salvation by the one, without the other?
And will any be driven, through cowardice from a practical faith in divine grace,
and the light and spirit of the gospel,
because these seceders have illusively pretended thereto?
Will any man be deterred from naming and believing in the Holy Name,
because the atheist chaunts it off with scorn?
Not the true Christian, no;
for if the very worst of men deceptively profess the best of things,
that will never occasion the true believer to abandon them;
nor if the unfaithful abandon one part of the covenant, professing to support the other,
it will never induce the former to reverse it,
for in so doing he would be a covenant breaker as much as the other.

Now, in conclusion, I would ask, if it is not alike dangerous to man,
and dishonorable to God, to deny that Jesus Christ has done anything for our salvation,
without us; and to deny that he is doing anything for us, within us,
for the same purpose: seeing that, if we reject either of these provisions,
we cannot be saved, for we cannot so much as begin a good life,
without the application of that great sacrifice of his body, once made for all men.
Nor, in the second place,
can we advance a single day of our lives in the Christian way and warfare against sin,
without his presence and help continually extended to us.

The fifth letter takes the ground of Robert Barclay and all our early Friends,
that the Spirit of Christ, and not the Holy Scriptures,
is "`the first and best leader and controller of
the Christian`'s life and practice,`" or,
as they called it, "`the primary rule;`" and shows conclusively that this doctrine,
which is indeed the true doctrine of the Bible,
by no means derogates from the excellency of those writings of holy men of God,
written as they were moved by the Holy Ghost.
Nor can there be any dishonor brought to the sacred writings,
by placing the all-manifesting Spirit, and light, and grace of God,
through our Lord Jesus Christ,
over and above them in the rightful order of God`'s manifestations
and provisions for the children of men.
Nay, truly, it cannot be derogatory to the Scriptures,
nor to any other creature here below, to place the second Adam, the Lord from heaven,
the quickening Spirit, above them.

He then fully admits them "`to stand above all other writings,`" and "`to
be the only outward fit rule and standard by which all the professors
of Christianity may prove and try their doctrines;`" yet adds,
that, inasmuch as the various denominations have different confessions of faith,
all founded as they suppose on a right understanding of Scripture,
whenever a member of a religious body thinks he has found important
errors in the fundamental doctrines of his own people,
it becomes him to be candid and leave them, rather than,
like the leaders of the late Seceders of America,
secretly and artfully endeavor to gain over the unwary to their new views.
He might have carried this view a little further, by showing that though,
on the one hand,
the Scriptures are the test of doctrine between those of different professions,
to try which comes the nearest to the Gospel standard; yet, on the other hand,
when once a religious Society has settled for itself its own standard as being
in accordance with what it believes to be a correct understanding of Scripture;
then,
in order to try the consistency or inconsistency of its own members with its profession,
the appeal must be, not merely to the Scriptures (which are variously interpreted),
but to those interpretations of Scripture which have always been received
and acknowledged as characterizing the faith of that particular people.
Otherwise, no society, or gathered visible church,
can be said to have any settled religious faith and belief, as belonging to itself,
and not liable to be constantly disturbed with impunity
by innovators within its own borders.

The sixth letter contained an earnest appeal for the continued faithful
maintenance of the testimonies of Friends to plainness and self-denial,
so little appreciated by the advocates of the new views.
I have thought it necessary thus to show at some length the tenor of these letters,
inasmuch as, although highly approved by sound Friends,
who saw their salutary applicability to the state of the Society at that time,
yet on the other hand, they brought on their author an abundant share of obloquy,
from those who favored the modern innovations,
and afterwards became one of the chief pleas for
the persecutions which assailed him in his own country.
John Wilbur had, however, pursued the straight path of gospel order.
He had, while in England,
taken an opportunity of privately opening his uneasiness
to at least one of the main instigators of the new doctrines,
Joseph John Gurney, and probably also to others;
and had been faithful in his testimonies against these errors in his public declarations,
before the issue of these letters;
and though some influential members in New England would have gladly put
him to trouble in consequence of his open and firm stand for the truth,
they could make no progress against him as long as Moses Brown lived;
for that honest man and venerable patriarch frustrated their attempts,^
footnote:[See two letters from Moses Brown, in [.book-title]#J. Wilbur`'s Journal,# pp.
176 and 177.]
knowing they were out of the truth.

Elisha Bates, a minister of Mount Pleasant, Ohio,
through unwatchfulness was caught with the new views,
and going to England in the year 1833, and again in 1836,
greatly strengthened this innovating spirit,
by joining with those who were openly repudiating some of our fundamental principles.
And being of a fluent pen as well as speech, Isaac Crewdson, William Boulton,
and other leaders in the schism,
gladly associated him with themselves in their attempts to subvert
the characteristic doctrines and testimonies of the Society.
In the year 1835, Isaac Crewdson of Manchester, published a small book, entitled,
A Beacon to the Society of Friends,
ostensibly warning the members against the awful errors of Elias Hicks,
on the assumption that many of the writings of our earliest authors tended in that direction,
and calling the Society in this day to sentiments supposed
by him to be more evangelical than those of our forefathers,
as the only way to avoid the spread of Hicksism through the Society in Great Britain.
This book, soon after its appearance,
was followed by a shower of pamphlets in the same direction,
many of which were very crude and frothy,
but all tending to raise a commotion and kindle unhallowed fire.

The Beacon by Isaac Crewdson,
and the Bible studying meetings held at the house of William Boulton,
were indeed nothing more than a genuine fruit of the views which had been advocated
for about ten years in the successive publications of Joseph John Gurney.
The difference between J. J. Gurney`'s writings and the Beacon, was simply this,
that the former laid the groundwork, and the latter the superstructure;
that the former used comparatively cautious language, while the latter spoke plain out;
that the former upheld the Scriptures as the source of divine knowledge,
paramount to the Spirit, or as if the Spirit taught only through them, thus necessarily,
although at first secretly, undermining the opposite doctrine held by Friends;
while the latter writer, besides doing this in full, with regard to the Scriptures,
also came forth boldly and more distinctly in a denunciation of our great
distinguishing testimony to the Light of Christ in the heart,
as the primary teacher or rule, and the universality of Saving Grace,
as held by Barclay and all our ancient writers.

J+++.+++ J. Gurney had limited "`revelation`" to what is written in the Scriptures; which,
he declared, were sufficient "`to direct our faith,
and regulate our conduct,`" were "`the only authorized record of divine truth,`"
the only medium by which to obtain a knowledge of the nature of sin,
or of "`a call to repentance extended to the whole human race,`" and that
they "`unfold the law of God in all its strength and spirituality,
in all the glorious variety of its details.`"^
footnote:[See J. J. Gurney`'s [.book-title]#Portable Evidence,# English edition, pp.
69, 91, 114,
etc.]
The Beacon discarded the universal and saving efficacy of the light of Christ,
inwardly revealed; and denied any true knowledge of God, or of his salvation,
except through the Scriptures--taught that it was a "`pernicious
theory`" to speak of the Scriptures as secondary,
and the Spirit as a higher rule--declared that it was "`presumptuous`" to assert
the sufficiency of "`the inward light,`" calling it a "`delusive notion`"--designated
the belief that "`the inward light is the primary rule of faith and practice,`"
as a "`dangerous error`"--and asserted that "`setting up a light within,
above the revelation of the Spirit of God by Holy Scripture, has led, step by step,
into the deadly gulf of deism.`"^
footnote:[See the [.book-title]#Beacon,# all through the volume.]

On the doctrine of Imputative Righteousness, too, they held the same ground.
J+++.+++ J. Gurney had said, "`Our only claim on the heavenly inheritance, therefore,
consists in this, that God is pleased to impute to those who believe,
the perfect righteousness of our Lord Jesus Christ; "`^
footnote:[[.book-title]#Gurney`'s Essays on Christianity,# Amer. edit+++.+++, p. 390.]
and that faith "`is a reliance of the soul on the incarnate
Son`" thus limiting it to the incarnation alone.
In like manner, the Beacon said:
"`Our immense debt is cancelled by the precious blood of Christ, if, by faith,
we lay hold on Him as our surety.`"
Do not both these statements equally overstrain the precious doctrine
of the atonement to such an extent as to exclude the divine declaration,
that "`without holiness no man shall see the Lord?`"J.
J+++.+++ Gurney had repeatedly designated the Scriptures,
as "`the written word,`" "`the word of the Lord,`" thus coming as near as he could,
and opening the door, towards calling them the Word of God;^
footnote:[__Ibid., __pp. 88, 350, etc.]
and had declared that from them "`we derive our hopes of the immortal crown of righteousness.`"
The author of the Beacon, in like manner, though more openly,
styled them "`the Word,`" "`the Word of God;`" argued to prove
the correctness of the term as applied to them as well as to Christ;
and (page 92) restricted the possession of the "`law written in the heart,`"
to "`true believers,`" and (page 119) "`the manifestation of the Spirit
given to every man,`" to the Corinthian believers only!

It is also well known, that the two authors coincided in their views respecting Prayer,
the calling of the first-day of the week the Christian Sabbath,
and styling the four narrative accounts of the Evangelists "`the Gospel,`"
in obvious contradiction of the views of true Friends from the beginning.
In one particular, Isaac Crewdson appears to have gone further than J. J. Gurney.
In order to bring our silent worship into discredit,
he branded the system as "`Quietism`"--making a parade of this epithet,
as if he thought it an excellent handle against us--and also,
as "`a religion of feelings,`" evidently implying of mere enthusiasm--and said (page
96) that "`to imagine that silence and stillness are essential to true worship,
would be a great error.`"
In most of these attacks, it is true, he professed to be aiming at Hicksism;
but in reality the blow was manifestly meant for ancient Quakerism.

We have thus seen how far these two writers really worked together,
in pulling down the old landmarks of our profession.
It may indeed be safely said,
that the works of J. J. Gurney were far more efficient
in bringing "`Beaconism`" upon the Society,
than the writings of the author of the Beacon;
and that the latter never could have accomplished the schism it promoted,
had not the ground been prepared for it beforehand,
by the general acceptance of the books published by J. J. Gurney.
How was it then, that the one involved himself in the censure of the Society,
while the other entirely escaped?
It was because J. J. Gurney was wary, and capable of so smoothing his mode of expression,
and so salving over any sore place among such as might begin to feel uneasy,
that he retained his position of great influence;
while Isaac Crewdson was of a bold and straightforward temperament,
came plainly out with his denunciations of our ancient faith,
and being quite capable of maintaining the position
he had taken by confusing the views of his opposers,
preferred to pursue his course openly,
rather than either to modify his expressions for the sake of making peace,
or to suffer himself to be persuaded that he was in error,
by men whom he plainly saw to be weakly inconsistent with their own expressed convictions.
J+++.+++ J. Gurney also seems to have perceived that the rapid course
of the advocates of the Beacon was likely to drift them quickly
into a separation from the main body of the Society;
and not being prepared for that step himself,
but aiming to carry the whole Society into an acceptance
of his own views through his great popularity and tact,
he preferred to abandon these his too ardent pupils, and let them drift, if they must,
rather than launch himself with them on so desperate a venture.

There were several attempts soon made, through the press,
to counteract the pernicious tendency of the opinions advanced in the Beacon.
The first of these was a short letter, addressed to its author by Thomas Thompson,
an Elder of Liverpool Meeting.
Then followed a more elaborate Defence of the Doctrine of
Immediate Revelation and Universal and Saving Light,
by Thomas Hancock, M. D., another elder of Liverpool;
which showed in a clear and firm manner, but with a mild and moderate tone of argument,
the reasonableness of the true doctrine of Friends on these subjects,
their accordance with Scripture truth,
and their incongruity with the views advocated in the Beacon.
After this came a fiery attack on the Beacon,
and its coadjutors both in and outside of the Society, entitled, Truth Vindicated, etc.,
a book of 224 pages, published anonymously,
but soon afterwards known to be written by Henry Martin, a young and ardent man,
zealously attached to Friends`' principles as advocated by our early writers.

This was a powerful and crushing rebuke of the Beacon; but the writer indulged, perhaps,
in too much of a taunting harshness of expression,
calculated to produce irritation among those whom he so recklessly lashed; and, moreover,
launched into a very bold and aggressive mode of warfare,
in which he did not always carefully guard his own lines from assault,
or at least from being charged with overstraining
the positions of those whom he was opposing,
or with leaving out views which ought to have been introduced,
in order to avoid an appearance of more or less randomness or irreverence of manner,
in his mode of treating principles of momentous importance.
The main tendency and intent of the work, however,
was to sustain the ancient doctrines of Friends against these insidious attacks,
and to expose to view the utter want of solid ground which the latter had to stand upon;
but it is to be regretted that his intent was not
carried out with more discretion and caution,
that the pure truth might not suffer reproach by his unguarded style of writing.

As an instance, we may refer to the circumstance,
that his advocacy of the Holy Spirit being the primary rule,
instead of the Scriptures given forth by that Spirit,
would have been far more satisfactory and clear from cavil,
if he had simply added his own adhesion to what Friends have always acknowledged,
that the Scriptures are also a rule, though a secondary rule,
subordinate to the Spirit from which they derive their authority,
and that whatever is contrary to their testimony, is to be rejected as false.
But in the warmth of his zeal against these modern
revivors of the calumnies put forth by the Buggs,
Owens, and Keiths of former days,
he did not condescend to stop to make all his own modes of expression secure from attack,
or to tell the whole truth, further than appeared to him needful for his own purpose,
in crushing the position of his antagonists.
A very different antidote to the doctrines of the Beacon appeared also in 1835,
under the title of The Light of Christ exalted,
or the More Excellent Way Briefly Set Forth, a small book of about sixty-eight pages,
by Joseph Sutton, of Manchester.
Though this little work was not ostensibly aimed at the Beacon,
but was addressed to the Methodists,
with whom the writer had formerly been in connection,
yet it furnished a good practical refutation of the fallacious
and backsliding views of the author of the Beacon,
was written in a spirit of piety and tenderness,
and supported the true doctrines of Friends.

John Harrison, another member of Manchester Meeting, zealous against all innovations,
and firm in "`contending for the faith once delivered
to the saints,`" came forth the next year (1836),
with A Lamp for the Beacon Showing by Many Parallel Passages,
that its Erroneous Sentiments were but the Reiteration of What had in
Old Time been Abundantly Cast as Mire and Dirt Against Our Early Friends,
by Sundry Opposers of the Truth,
and had been Again and Again Refuted by George Fox and Others.
In 1836 also, J. J. Gurney entered the list of writers in this controversy,
not by opposing the Beacon, but by attacking the author of Truth Vindicated.
This he did with a portion at least of the same acrimony
as the latter had used towards the Beacon and its eulogists,
and with much more unfairness.
His Strictures on Truth Vindicated,
while professing to support what he called the doctrines of the Society,
did great injustice to the author of Truth Vindicated,
and rather materially promoted than in any wise damaged, the cause of the Beacon;
inasmuch as he therein showed that he was himself sorrowfully defective
in his appreciation of some of the fundamental doctrines of Friends,
especially with regard to immediate revelation,
and the relative authority of the Scriptures and of the Spirit which gave them forth.

Great disturbance was the result of this controversy throughout the Society in England;
and a considerable proportion of the members in Manchester, a very large meeting,
being carried away with the new views,
formed so powerful a party in that Monthly Meeting, that no effectual check could,
for a time, be applied to it by the sound portion of the members.
The subject was accordingly brought before the Quarterly Meeting of Lancashire in 1835;
which appointed a committee to visit and aid the Monthly Meeting of Hardshaw East,
in which Manchester was situated,
with a view to the due support of the discipline and testimonies of the Society,
and the restoration of unity.
Meantime the controversy spread far beyond the limits of Lancashire Quarterly Meeting,
and went on as warmly as ever.
Elisha Bates had, during his visit to England in 1833 and 1834,
unmistakably shown his adherence to the novel views, and disposition to promote them;
and such was the uneasiness with regard to his proceedings and declarations,
on the part of not a few Friends at that time,
that the Yearly Meeting of Ministers and Elders declined
to grant him the usual clear returning:
minute, on his leaving for his own country.
At the Yearly Meeting in 1835, this fact was brought to notice by John Hodgkin;
and so great an outcry arose among his partisans, or sympathizers, that,
in order to satisfy them,
Josiah Forster proposed that the Select Yearly Meeting
should be directed to reconsider the subject.
This was done, and under the popular pressure,
that meeting was actually induced to transmit to America a clear returning certificate,
in contravention of its previous judgment!

In the spring of 1836, Elisha Bates again appeared in England;
this time without any credentials, and professedly on the ground of outward business;
but in reality with the intent of helping forward
the "`Beacon`" party to the best of his ability.
With this view,
he almost immediately commenced the publication of his Miscellaneous Repository in England,
and continued it for several numbers,
as a vehicle for his attacks on the ancient landmarks;
and in the autumn he went so far in the practical exemplification
of his departure from our original principles,
as to submit to the ceremony of water-baptism,
performed by a certain J. Pye Smith (called "`Reverend`"), in the neighborhood of London,
probably the first instance of the kind in one at the time
occupying the station of a minister among Friends.
He afterwards,
with the egotism which now became a prominent characteristic of his writings,
published several pamphlets in support of his own conduct,
and one endeavoring to destroy the religious standing of our early Friends;^
footnote:[This was well answered in 1837 by Samuel Tuke,
in [.book-title]#A Plea on behalf of George Fox and the Early Friends.#]
and soon left England again for America,
having probably found his advocacy of the party more largely drawing
on his pecuniary resources than the remuneration warranted.

John Wilkinson and Luke Howard were two other sorrowful
instances of ministers who had stood in good esteem,
becoming beguiled and carried away in these byways and crooked paths,
and through their influence helping forward greatly the sad defection from ancient principles.
Both had been conspicuous members of the Society, very much respected by all,
and beloved by many,
and the former had acted for several years in time past as clerk of London Yearly Meeting.
Luke Howard, an eminent chemist and natural philosopher,
and for many years head of the well-known firm of manufacturing chemists, Howard,
Jewell and Gibson, near London, was, particularly in his latter days, an eccentric man,
though highly esteemed in the community,
for his scientific attainments and his general moral worth.
Having relinquished business, and retired into Yorkshire,
he published for several years (as an employment for his
leisure) a periodical entitled The Yorkshireman,
which furnished a vehicle for some valuable information,
and an outlet for some of his strange ideas.
When the "`Beacon`" controversy broke out,
he earnestly joined with it in some of its features,
published several attacks on the views and practices of Friends, and in 1837,
after an erratic course, became water-baptized, and was disowned from the Society.

John Wilkinson was in fact one of the earliest and
most efficient instruments in stirring up this schism.
For several years before it broke out,
he had been dissatisfied with some of the doctrines of early Friends,
and anxious to bring about a change.
This disaffection manifested itself openly in 1832,
when he was one of the Committee of Conference on the alterations in the Discipline.
Being of an open and candid temperament as a man,
not given to evading his real sentiments,
and bold in advocating the views he had embraced,
particularly against the doctrine of the inward light
of Christ as the primary rule of faith and practice,
and the Scriptures as a secondary rule--that of the universality and saving efficacy
of Divine Grace--the necessity and possibility of freedom from sin in this life,
as treated by Barclay and others under the name of Christian
Perfection--and also against our well-known principle,
that in order to avail ourselves of the precious
efficacy of the atoning sacrifice of Christ,
we must submit to the purifying operations of his Spirit in our hearts--his ministry
became very unsound and burdensome to the living discerning members.

Yet for some years much tender forbearance was exercised towards him,
and only private admonition extended to him,
though of this there appears to have been no little.
It is indeed astonishing, that so much forbearance was used,
that he was allowed to go on as a minister,
spreading abroad views in direct contravention of the fundamental doctrines of the Society,
for five or six years, before anything was really done to put a stop to it,
otherwise than by private admonition.
Even in 1831, he had excited uneasiness; in 1832 he had explicitly and openly objected,
in the Meeting for Sufferings,
to some of the doctrines of William Penn and Robert Barclay;
and in the Yearly Meeting of 1834,
he had expressed his desire that the Scriptures "`might be acknowledged
among Friends as the only rule of faith and practice.`"
This of course produced at the time some alarm, and elicited some opposition,
but nothing further was done.
Going to Manchester in the autumn of that year,
and coming forth as usual in his preaching with some of his views,
George Jones and John Harrison, and other friends,
expressed to him in letters their dissatisfaction with his ministry.

In the twelfth month of 1835, in a meeting at Tottenham, near London,
he declared distinctly against the "`belief in Christ as
an inward principle,`" designating such a belief as deceptive.
On this occasion that worthy minister Thomas Shillitoe, then far advanced in life,
and quite infirm, could not remain silent,
but is said to have expressed himself as follows: "`I feel constrained to say,
that if by an '`inward principle,`' is meant the
inshining of the light of Christ in the heart,
which is his second coming without sin unto salvation,
and this is not to be believed in and depended upon,
then I am in a most deplorable state!
Now, at my advanced age, at this solemn period,
and in the prospect of being soon called to stand before the judgment seat of God,
to receive the reward of my works, then where shall I be?
And if there is no '`inward principle,`' then, for sixty years past,
I have been following a '`Jack o`' the lantern,`' a '`Will o`' the wisp!`' For it is
now more than sixty years since I became acquainted with the principles of this Society.
Oh, no! my friends, the evidence in my mind at this time is,
that as I have followed the leading and guidance of this inward principle,
this inshining of the light of Christ,
it has led me safely along through all the dangers and perils of the way,
and will continue to lead me to the end.
And it is the chief corner-stone on which I build all my hopes,
and shall do to the end of my days; and I crave that during the remainder of my life,
nothing I may ever hear, nothing I may ever read, nothing any man may say,
may jostle me from off this foundation.
And I warn you, to take heed how you receive any other doctrine than this.`"

A few days afterwards, Thomas Shillitoe, as a true watchman not sleeping at his post,
introduced the case into the Quarterly Meeting of Ministers and Elders in London,
as it was within that quarter that the unsound views had been uttered.
The result was that J. Wilkinson received a letter from one of the elders,
expostulating with him on the inconsistency of his course as a minister among Friends;
and a few days afterwards, as he continued to speak in the same manner,
he was requested by four of the elders to keep silence,
and a complaint was sent to Friends of his own Monthly Meeting.
John now seeing Friends in earnest,
and that the course just entered upon was likely to bring matters to a narrow pass,
concluded to anticipate the regular action of discipline,
and accordingly sent in to his Monthly Meeting a
letter resigning his membership in the Society.
The next year he published his reasons for leaving Friends,
in a scurrilous attack on the Society (containing
many oft refuted charges brought up anew),
in a work of about 500 pages, entitled, Quakerism Examined.

The author of Truth Vindicated was not to be so easily
silenced by the authority of name or rank,
or by the self-assumed weight of "`magister ipse dixit,`" without the support of truth,
as J. J. Gurney seemed to have imagined.
He soon published a reply to J. J. Gurney`'s Strictures,
entitled Early Friends and Modern Professors, a book of about 150 pages, 12mo.,
in which he brought clear argument and ample evidence,
from the writings of our early Friends, to sustain his own positions,
and to fasten upon J. J. Gurney, in an incontestable manner,
the charge of unfair misrepresentation of his former work,
and of palpable unsoundness in regard to some of the fundamental doctrines of the Society.
He also cleared himself from imputations to which certain lax modes
of expression in the Truth Vindicated had somewhat exposed him;
and showed beyond reasonable dispute,
that if J. J. Gurney had truly charged his book with "`infidelity`"
our most cherished writers were no less liable to the awful charge.^
footnote:[The same writer (Henry Martin) also published, in 1835 and 1837, two pamphlets,
entitled, [.book-title]#A Defence of the Original Principles of the Society of Friends,#
No. 1 and No. 2; and, in 1836, [.book-title]#A Letter to John Wilkinson.#]
This reply indeed sent forth a fatal stroke against J. J. Gurney`'s
pretensions to soundness in the principles of Friends,
and it seems that he was never able to gainsay or parry the scorching allegations.
He remained silent, at least, so far as the press was concerned.

In the Yearly Meeting of London, in the fifth month, 1835,
the disunity in Lancashire Quarterly Meeting was brought into view;
and Josiah Forster proposed the appointment of a committee to extend care and assistance,
alleging that the publication of the Beacon was the origin of the disunity existing.
A committee was already under appointment by that Quarterly Meeting, on the same subject.
Luke Howard now opposed the appointment of any committee by the Yearly Meeting.
Joseph John Gurney expressed his approval of the
sentiments of the Beacon on the subject of the atonement,
but believed it was defective and incorrect respecting
the universality of the Light of Christ,
and the influence of the Spirit;
but he "`still more highly disapproved of Dr. Hancock`'s reply`" +++[+++Defence],
and objected to this author having made "`references to Barclay,
rather than to the Holy Scriptures.`"
In the discussion which ensued,
it appeared that the Monthly Meeting of Hardshaw East (Manchester,
etc.) had not taken any steps against the author of the Beacon;
but the appointment of the above-mentioned committee by the Quarterly
Meeting was considered as having this purpose in view,
and was therefore looked upon by some as improperly
overstepping the functions of the Monthly Meeting,
although its object in reality was to assist the sound members
of that meeting in the maintenance of the discipline.

J+++.+++ J. Gurney "`raised a point of discipline`" on this,
"`in favor of his dear friend,`" the author of the Beacon,
and proposed that Lancashire Quarterly Meeting should
be directed to discharge their committee,
"`and to suspend all further proceedings against`" the book or its author,
in order to prevent "`incalculable mischief`" by the proceedings being allowed to go on.
He repeated his desire that "`for the cause of harmony
alone`" all further proceedings should be stopped;
apparently ignoring the fact,
that the fundamental doctrines of the Society were at stake in allowing that book and
others of the same stamp to continue to circulate among its members unrebuked.
In what Josiah Forster afterwards said on the subject,
he appeared to urge the appointment of a committee,
as much with a view to stop Thomas Hancock`'s Defence,
as to check the circulation of the Beacon.^
footnote:[See a [.book-title]#Report of the Proceedings of London Yearly Meeting,# 1835.
Published by John Stephens, Fleet Street; pages 6 and 7.]
The discussion of the subject, being resumed the next day,
resulted in the appointment of a committee of thirteen members, viz.: Barnard Dickinson,
Edward Pease, George Richardson, Samuel Tuke, Edward Ash, Josiah Forster,
William Forster, George Stacey, Joseph Tatham, Joseph Marriage, William Allen,
Peter Bedford, and Joseph John Gurney.

Looking over these eminent names, we can scarcely fail to perceive,
that in regard to the all-important matter of doctrines,
the committee was composed of very discordant materials;
but we may also apprehend that two men such as J. J. Gurney and Edward Ash,
who must have known that if the doctrines of the Beacon were censured,
their own writings would share the same blame,
would be likely at least to neutralize any attempt to come forth
openly and unreservedly in support of our ancient principles.
There were some men upon that nomination warmly attached to the primitive faith,
so far as their education and associations had made them acquainted with it,
and some who went deeper than education or association;
but who could not bring their minds to a resolution openly to encounter
the overwhelming influence of J. J. Gurney and his many admirers.
So that when we consider his well-known position,
and that of Edward Ash in the same direction,
and add to this the shrewdness and sophistry of Isaac Crewdson,
we may easily account for the very weak, inconsistent,
and faltering manner in which the whole subject proved to be treated by the committee,
and the great damage thus done to the Society by their means.
J+++.+++ J. Gurney at once took the helm,
and directed and controlled their proceedings in such a way as to shield
himself from the censure which must have fallen upon him,
if the Beacon`'s doctrines had been openly and clearly denounced.

The whole committee met in Lancashire at the Quarterly Meeting in the sixth month, 1835,
and began a long series of blunders by acceding,
under certain unworthy restrictions upon Isaac Crewdson,
to his demand that all their observations to him
respecting the Beacon should be in writing,
after coming to a deliberate joint conclusion on its various parts.
They furnished him, accordingly, with a statement of objections to the work,
but desired him to take no copy, keep the document strictly in his own possession,
and return it to them at their next meeting.
According to his desire also (for he seems to have dictated to
the committee his own terms for their treatment of the case),
they confined themselves to what were termed "`Scriptural`" objections;
thus opening a wide field for controversy, instead of going at once to the mark,
and showing that his publication was palpably at variance,
on certain fundamental subjects,
with the always acknowledged doctrines of the body of which he was a member and a minister.

This would have been the strong ground, and clear of controversy; but in abandoning it,
they laid themselves open to great difficulties,
and gave him many opportunities of sophistical reasoning, in a discussion,
the end of which none could foresee.
Such a thing as the supposition of a discordance between
the acknowledged doctrines of the Society and those of Scripture,
ought not to have been allowed to be considered or treated as an open question,
between members of that Society.
Between the Society and other professors, it would have been the reverse.
All professing Christian sects bring Scripture, as they understand it,
to prove the correctness of their tenets;
but to prove that any one of their members is sound
or unsound in his doctrines as a member of any Society,
he must be judged by the Scriptures as always accepted and interpreted by that Society.
The committee thus at once gave away the ground on which
they ought to have taken a firm and immovable stand;
which could afterwards have been amply sustained from Holy Scripture.^
footnote:[Edward Ash, the only surviving member of that committee in 1870,
published in the London [.book-title]#Friend# of the ninth month, that year,
a statement of their proceedings in regard to the Beacon,
as a record of the case according to his view of it.
He says (p. 208),
"`A Friend in the station of Minister made an earnest appeal to the committee,
to judge the [.book-title]#Beacon# by [.book-title]#Barclay`'s Apology.#
After a very brief interchange of opinion,
it was unanimously resolved to do no such thing,
but to try it by the Holy Scriptures alone.`"
The individual here alluded to, is believed, on satisfactory evidence,
to have been that worthy man, Alexander Dirkin, formerly of Wilmington, Delaware,
who died in England.]

The committee commenced their statement by an earnest endeavor
to prove to Is. Crewdson that they were not Hicksites;
and in their zeal to do this, they overstepped the mark of Quakerism,
by adopting one of J. J. Gurney`'s expressions respecting the Holy Scriptures;
declaring that they "`are the appointed instrument for making known to mankind
that divine plan of grace and salvation through Jesus Christ and Him crucified,
to which they bear so clear a testimony.`"
Here was a mode of speech, which, being susceptible of a double meaning,
was outwardly true, but inwardly and essentially false;
and appears to have been employed by those who in the committee secured its adoption,
to cover up the truth, that grace and salvation by Christ come to mankind immediately,
from the Most High,
although the mere outward "`knowledge of the plan`"
may be said to be made known through the Scriptures.
But, is it possible,
that there were no men in that committee who could see and
withstand the illusory nature of these expressions,
knowing that the literal "`knowledge of the plan`" is one thing,
but the practical experience of the inward efficacy
of true religion is quite another thing;
and that though the former, when rightly applied to us by the Spirit, is to our help,
comfort, and instruction,
yet the latter is what the soul must depend upon for life and salvation?

This was a giving way in a fundamental point,
of which Isaac Crewdson did not fail afterwards freely to take advantage.
If they had said "`an appointed instrument,`" no inconsistency would have attended it;
but to call the Bible "`the appointed instrument,`"
surely implies that there is no other.
And though the word "`plan`" is artfully introduced to save the phrase,
the idea intended to be conveyed undoubtedly was,
that the Bible was the appointed means of grace and salvation through Christ;
to the setting aside of the great doctrine of our early Friends,
that the inward Light of the Lord Jesus by the work of His Spirit in the soul,
is the great teacher and leader to the true and saving knowledge of God,
and that the Scriptures are subordinate, though a blessed and very important adjunct,
or co-agent in the work of instruction, that the man of God may be perfect,
thoroughly furnished to all good works.

After this,
they took pains to discard any "`overstrained views
of the precious doctrine of the inward light,
as if this light was to be expected to bring men to a knowledge of the
incarnation and sacrifice of Christ;`" but they entirely omitted to state,
that salvation may be obtained even without the advantage
of that outward knowledge of facts,
by an inward experience of the efficacy thereof.
It is true that afterwards they speak of the Scriptures not being "`the
only channel through which He operates for the conversion and salvation
of men;`" but they speak of it as men who were afraid to speak out,
hinting at "`divine visitations`" and "`gracious impressions,`" but by no means
advocating the great doctrine of the Universal and Saving Light of Christ,
as stated by our primitive writers, and owned since by all faithful Friends.
And in the very next article, they adopt the actual words of the Beacon,
acknowledging that, "`We willingly accede to the proposition,
that through the Scriptures '`we obtain the knowledge of God`'s holy law`'
(Beacon, p. 42),
because that law is plainly declared and unfolded, in all its particulars,
in the volume of inspiration.`"

This, however, which is nearly J. J. Gurney`'s own words elsewhere,
they here somewhat qualify, by adding, "`Yet we wish to remark,
that the law of God is not made known to us by the written revelation alone.`"
Their whole advocacy, however, of this point, is exceedingly faltering and vacillating,
and though in some parts of it they endeavor to make
an appearance of not being willing to abandon it,
yet in their summing up of the objections to the Beacon near the close of their statement,
they again speak of the Scriptures as "`the great
appointed channel of the Christian revelation.`"
While they charge the author of the Beacon with speaking of the "`Inward
Light`" as a "`delusive notion,`" and say that he denounces it "`as the
theory of an infidel,`" and alludes to the doctrine of the "`anointing`"
in "`disrespectful terms,`" and show that he is herein entirely in error,
yet soon afterwards they say,
"`We entirely acquit the author of the Beacon of
any intention to speak against the Holy Ghost.`"
And though besides all this,
they plainly show that his remarks tend to depreciate our views
respecting silent worship and the gift of gospel ministry,
yet they conclude their statement with this remarkable avowal:
"`We would not have him sacrifice one particle of his testimony to the Truth as it is
in Jesus;`" as if he was still really bearing a living testimony to that truth,
while promulgating views directly tending to undermine it!

If we consider the wavering nature of this statement of the committee altogether,
we need not be surprised to find, that in their subsequent proceedings,
when pressed by Isaac Crewdson`'s exposure of their weakness,
and by the sophistical attacks wherewith he strove to turn it to his own account,
they were put to their wits`' end to contrive ground to
stand upon without further compromising their own position.
In saying this,
I do not wish by any means to deny that many of their objections
and arguments against the Beacon were undoubtedly sound and good;
(the better element gaining at times a temporary ascendency in the committee);
and I can cordially indorse the following expressions,
with a regret that they had not more fully sustained them throughout:
"`When we remember that the influence of God`'s Holy Spirit on the mind
of man is the source of all saving knowledge of divine truth,
the spring of faith and holiness, of life and immortality,
we ought surely to refrain from restricting its true extent as it relates to others,
and to cherish it for ourselves with humble gratitude as our dearest treasure.`"

At their second visit, in the eighth month,
Is. Crewdson presented a reply to their statement,
in which he made a general plausible defence of the Beacon,
congratulating the committee on their very scriptural views,
and artfully expressing his satisfaction that there was "`so much accordance`"
between their statements of Christian doctrines and his own sentiments.
He endeavored to explain away his attack on the doctrine of the "`inward
light,`" by alleging that it was leveled at Hicks`'s view of the doctrine;
but he made no attempt to show what were the views
of faithful Friends on that great subject,
in contradistinction with those expressed by Elias Hicks;
and though he cannot have been ignorant that "`the inward light`"
is a term constantly used by Friends to designate the enlightening
operations of the Spirit of Christ in the soul,
he denied that his aspersions thereon had any application
to the "`Scripture doctrine`" of the Holy Spirit.
But what he had in view by what he called the "`Scripture doctrine of the Holy Spirit,`"
as he explained it in three brief paragraphs specially introduced for the purpose,
seems to be very far short of that doctrine as always held in the Society,
and indicates the Scriptures, after all,
as the source of what the Holy Spirit is to apply.
His reply, as a whole, was an affectionately couched appeal to their feelings,
and while firmly holding his own position,
was well calculated to convey an impression that
there was but little difference between them.

To this reply the committee answered in writing, and with good reason, that,
in issuing such a warning as the Beacon against the errors of Elias Hicks,
the author ought to have made clear distinctions, for the reader,
as to what dangers he was aiming at,
by showing wherein the doctrines of Friends were
departed from or misrepresented by Hicks.
But while they still exhorted the author to suppress the circulation of the Beacon,
on account of its manifest tendency,
they yet avowed themselves considerably relieved by the explanation which
he had given them of his views on some points of Christian doctrine.
It would be tedious and unprofitable to follow in
detail the desultory controversy which ensued.
The committee, as a body,
do not appear to have known clearly the difference between
really sound doctrine and his sophistical representations.
They again attended Lancashire Quarterly Meeting, held at Liverpool,
in the twelfth month; and it appears,
by a printed account of what occurred at that meeting,^
footnote:[See the [.book-title]#Christian Advocate;# London, twelfth month 28th, 1835, page 414.]
that more was said by the committee against Truth Vindicated, than against the Beacon.
Josiah Forster designated the former as "`a very pernicious work,`" and even
Samuel Tuke (if the account is to be trusted) spoke of its "`dangerous tendency.`"

On the 12th of that month,
Isaac Crewdson presented to the committee at Manchester a document of considerable length.
He now with great acuteness took up the committee`'s own words and admissions,
and made use of them to his own advantage to such a degree,
that the committee must have felt as if enwrapped by a web of their
own materials--their own weak statements and needless concessions.
He quoted also a part of a letter written to him by one of their number (J. J. Gurney),
speaking with much approbation and satisfaction of certain features in the Beacon,
especially on the Atonement and Justification,
as "`excellent,`" and many of the author`'s remarks as "`in accordance
with the sentiments of every sound and enlightened Christian.`"
After this,
Isaac Crewdson reasoned with the committee on the supposed
consequences of suppressing such a book as the Beacon;
and, professing to have satisfied all their objections,
demanded that they should either come forward with
whatever they had further to object to,
or give him a clear acquittal.

The committee must have been in a pitiable strait
to know how to get out of such an entanglement.
But at the Monthly Meeting, held on the 24th of the twelfth month,
they made a report of their proceedings.
In this report they informed the meeting of their labors with the author of the Beacon,
and his various replies to their objections;
quoting many of his professions of unity with their views,
as if they really did believe that in the main he was sound in the faith of Friends.
They expressed their "`satisfaction in the evidence`" thus afforded, hollow as it was,
of his "`general accordance of sentiment in matters of doctrine`" with the Society.
But still thinking that his "`mode of writing`" regarding the "`inward
light`" was calculated to unsettle the minds of the young and inexperienced,
and that "`the bearing and tendency of the work`" were opposed
to our views of the spirituality of the gospel,
and finding that he had not complied with their advice
to suppress the further circulation of the Beacon,
they gave their judgment,
that "`the publication of the Beacon did furnish a ground of disunity with its author,
on the part of the Meeting of Ministers and Elders of this Monthly Meeting;`" but added,
that they did "`not feel called upon, with reference to the doctrinal question,
to recommend to the Monthly Meeting to take any proceedings in the case!`"

A day or two afterwards, they delivered a note to Isaac Crewdson,
recommending him to refrain from speaking "`in meetings for worship,
and to discontinue his attendance of meetings for ministers and elders.`"
Where they obtained by the discipline any authority thus to usurp the
functions of the Monthly Meeting and Meeting of Ministers and Elders,
has, so far as I know, never been shown.
But the Monthly Meeting advised him to comply with the admonition.
He was thus displaced as a minister.
For a few months he remained pretty much silent,
and further proceedings in his case seem to have been suspended,
the Beacon nevertheless circulating as freely as ever.
But during the summer of 1836,
it appears that he frequently spoke again in the line of ministry,
being probably encouraged to it by his adherents.
Whereupon in the ninth month, 1836,
the committee thought it their duty to inform the
Monthly Meeting of the state of the case.
At the Monthly Meeting in the tenth month,
Isaac Crewdson complained sorely of the injustice
which he thought had been exercised towards him,
and presented a written protest,
desiring that it should be entered on the records of the meeting.
During the discussion which ensued, much excitement was manifested,
insomuch that it is said that at one time thirteen
individuals were endeavoring to speak simultaneously.
In view of the novel and irregular nature of such a proceeding,
after great difficulty and much time spent,
it was finally concluded not to record the protest.

The proceedings of the committee in this case from first to last,
appear to have been of an extraordinary character,
and but poorly calculated either to heal the breach,
or to enable the church to clear itself,
by a decided testimony against the new views circulated by the Beacon and otherwise.
And to make the matter worse,
and compromise the whole body still more in a departure from ancient principles,
the Yearly Meeting of London, during this year, 1836, had issued an epistle,
containing expressions respecting the Scriptures,
well known to have been indited by J. J. Gurney,
and probably intended to meet the adherents of the Beacon,
on one important point at least, on their own terms.
This epistle designated the "`sacred volume,
as the only divinely authorized record of the doctrines of true religion;`"
and declared that "`there can be no appeal from them +++[+++the Scriptures]
to any other authority whatever,`" they "`being the appointed means of making
known to us the blessed truths of Christianity,`" and "`the only divinely authorized
record of the doctrines which we are bound as Christians to believe,
and of the moral principles which are to regulate our actions.`"

But the conduct of the case of Isaac Crewdson in the hands of this committee,
in various particulars throughout,
can scarcely be said to have been in accordance with the discipline of the Society.
Passing by their having entirely refrained from an open and unmistakable
advocacy of the real doctrines of Friends which were involved,
thus placing themselves in a wrong position and weakening all their proceedings,
the regularity of their mode of procedure in dealing
with Isaac Crewdson is open to much question.
If the question in regard to him as an individual had been primarily,
whether his ministry was sound or unsound, the matter ought to have been opened,
and if possible settled, in his own meeting of ministers and elders--if necessary,
with the assistance of the committee (or rather perhaps
of the committee of the Quarterly Meeting,
whose functions this committee had suspended)--and
thence taken to the Monthly Meeting for its conclusion,
as to the suspension of his ministry.

But this was not the question in a primary sense.
The question rightly before the committee was the alleged unsoundness of the Beacon,
producing disunity in the meeting.
On this subject, strange to tell, they gave their judgment to the Monthly Meeting,
acknowledging that they had no charge to bring against its author, respecting doctrines,
claiming any action by the meeting.
Yet they held on to him, nevertheless, as a delinquent in some way,
from his mode of writing, and the main tendency of his book;
and without any other given ground for it, recommended his suspension from the ministry!
No doubt he ought to have been suspended from the ministry;
but this should have been done in a manner authorized
by the discipline and practice of the Society.
And his case should have been introduced to the Preparative Meeting,
and thence to the Monthly Meeting, as in all other cases of delinquency,
on the ground of his publishing, and persisting in the circulation of a book,
at variance with the acknowledged doctrines of the Society,
and calculated to lay them waste.

Isaac Crewdson had already presented to the committee, early in the ninth month,
a supplement to his reply to their objections,
or as he entitled it when printed as a pamphlet, his Defence of the Beacon;
a paper of considerable length, making about sixty printed 12mo. pages.
In this paper he came forth more boldly than before with evidences
of his divergence from the doctrines of early Friends;
and while firmly holding his former position, he spoke in the tone of an injured man,
closely expostulating with the committee on the very inadequate grounds on which,
as he thought, they had condemned him.
Making constant use of the committee`'s weak and erroneous admission
that the Bible is "`the appointed instrument,`" etc.,
by which they had placed themselves in a false position,
and which had now been endorsed by the Yearly Meeting, in terms, if anything,
rather stronger, he worked upon it in various ways,
to show that his own statements were in accordance with it; rejoicing, as he said,
"`to find that,
upon this cardinal point,`" his own views and those
of the committee were "`so entirely alike.`"

Yet he did not hesitate to show them that their mutual views
were entirely at variance with the doctrines of Robert Barclay,
which he designated as an "`unscriptural and mischievous
theory,`" and "`in the highest degree delusive.`"
He spoke of "`the written word`" as "`the Gospel,`" and of this
being identical with "`the ingrafted word`" (James 1:21),
which he ought to have remembered the apostle says "`is able to save your souls.`"
He declared that this Gospel (written or preached) is "`the power of God unto
salvation,`" tauntingly adding that it was "`as it is well expressed by the committee,
'`the appointed instrument,`' or as it is equally well expressed
by the Society in its last Yearly Epistle,
'`The appointed means,`'`" etc.,
thus locking their fetters with the keys which they themselves had put in his hands.
After this he reminded them,
that he had been "`informed in full committee (at least when twelve +++[+++of thirteen]
were present),
that your sentiments--were not in accordance with Barclay`'s unscriptural theory,
the Vehioulum Dei.`"^
footnote:[Why should any be so alarmed at these two Latin words,
used by Barclay out of condescension to the schoolmen, and simply meaning the vehicle,
or entrance into the soul of the Spirit of the Lord.]
How could some of the committee sit still and let
such a declaration be made in their name?
He called "`the inward light`"--without any Hicks this time to
hang an excuse upon--a "`mischievous phraseology,`" and afterwards
"`the fallacious theory,`" and "`the root of Hicksism.`"

He called the committee to account for venturing in a few instances to
hint very gently at what our ancient Friends had or had not held,
reminding them again of the declaration of the Yearly Meeting,
respecting the Bible being the only record and test.
Indeed, he never seemed to have had enough,
in making his own use of these admissions of the committee and of the Yearly Meeting.
They appear to have been devised especially to help him to stand his ground.
In defending his application of 1 John 5:10,
"`because he believed not the record that God gave of his Son,`"
he seemed to be unaware that the word rendered record in this place,
// lint-disable invalid-characters
is  (testimony), and the verb translated gave is  (hath testified),
so that the expression by no means necessarily implies a written record.
He objected to the "`scruple which +++[+++he said]
many friends have had,
to calling the Scriptures the word of God,`" and repeatedly
applied that term to the Bible in this document.
He reminded them again of the commendations of the Beacon,
which he had received in a letter from "`one of the most
distinguished members of your own body`" (Joseph J. Gurney),
quoting it freely and ostentatiously;
and concluded by closely appealing to the committee, now to determine whether they had,
"`in any one instance,`" proved from Scripture that he had "`infringed on Divine Truth,
the truth of the Bible.`"

To this remarkable document, a short note was sent in reply by the committee,
without signature;
saying that they did "`not consider it to be incumbent upon
them to enter into any detailed notice`" of the manuscript,
but that they did "`not consider their scriptural objections to the Beacon
to be removed;`" and complaining of certain unfair "`insinuations`" which
they thought the author had advanced against them.
They endeavored to show their own soundness on the points involved in these insinuations;
and concluded by asserting that they felt it to be "`a sacred duty,
steadfastly to maintain those truly scriptural views
of the spirituality of the Christian religion,
which appear more peculiarly to distinguish our religious body in the church of Christ;
views which, in the present day, are in evident danger of being grievously undermined.`"
If they saw this in reality,
why had they not once come forth with a clear statement and defence of those views,
which were in such "`evident danger of being undermined,`" and
which were in fact then being undermined by some of their own number,
if not by their own joint pusillanimity in pretending
to defend them and yet frittering them away?
Would that they had more faithfully acted up to this "`sacred
duty,`" in their treatment of this extraordinary case!
The Society might thus have been spared many a bitter pang since that day,
in the wholesale departure of its meetings and members from
its original and fundamental principles and practices.^
footnote:[The views here brought forward,
relative to the position and action of the committee,
and the results on the whole Society consequent on their vacillating course,
have since been greatly confirmed by statements of
Edward Ash in an article in the London [.book-title]#Friend,#
of ninth month, 1870, above alluded to, and a reply thereto, signed D.,
in the British [.book-title]#Friend# of eleventh month 1st, 1870.]

In addition to the case of the Beacon,
the committee had also under its care that of William Boulton,
an appointed Elder of Manchester Monthly Meeting,
but who at times spoke in the line of ministry.
He had been for several years prominent in the way
of holding bible-studying meetings in his house,
and in various other measures promoting the views advocated in the Beacon.
In the treatment of his case,
the committee manifested the same weakness as in that of Is. Crewdson,
and an unwarrantable evasiveness in regard to the true reasons for their action.
They promptly desired him to desist from speaking as a minister, but without,
as far as appears by the accounts,
showing how this was connected with his bible-teachings;
afterwards they recommended him to refrain from attending
the meetings of ministers and elders,
of which he was assistant clerk;
and then to withdraw his membership in that Select Meeting;
and all this (as he told them himself without apparent contradiction),
without giving him any clear reason for such important advice.
There may have been in private,
extenuating circumstances to explain this reticence of the committee, but if so,
they ought to have been made known.

But it is time to hasten to the conclusion of this unhappy affair.
I believe it is safe to say,
that never before was a schism so terribly mismanaged in the Society of Friends.
The very measures which they took to suppress or to heal it,
served but to fasten the seeds of it firmly within the body at large,
to break forth with accumulated force at a future day.
It would seem that the Monthly Meeting`'s straight
course of action in the support of the discipline,
was at this time impeded, if not entirely frustrated,
by having those under the appointment of Overseers
who were mainly favorable to the new views.
In the tenth month, the subject was taken up for consideration,
whether the time had not arrived for a new nomination,
many years having elapsed since the last appointment.
Great opposition was made to it by the party of the "`Beacon,`" who,
as the committee of the Yearly Meeting, incorporated into the Monthly Meeting,
might have a controlling influence in the nomination,
saw in the measure a blast to their hopes of carrying
the whole meeting to their own purposes,
and instead of this a probability of being themselves
before long brought under the action of the discipline.
Feelings ran high, and the meeting was greatly disturbed;
but a committee was eventually appointed to consider of a new nomination.

As mentioned before,
Isaac Crewdson had delivered to the Monthly Meeting a protest against their proceedings,
and after much discussion the meeting declined to enter such a paper on its records.
This gave his party great offence, and at an adjourned meeting on the 28th of the month,
forty-eight male members produced another protest, against this decision of the meeting.
The reading of this protest was of course strongly opposed,
as irregular and contrary to all former practice in the Society,
and a dangerous precedent for the future administration of the discipline.
William Nield, who had this paper in charge to read to the meeting,
showed a fixed determination not to be defeated in his intention.
After much time spent in the discussion, he changed his ground to some extent,
in order to get it in one shape or other before the meeting;
saying that he would read it as his own, leaving out the names of the other signers.
This also was strenuously opposed,
but at length J. J. Gurney suggested that the question should
be left for the clerk and the friend to settle between them!
This amounted to a consent,
for the clerk had already shown himself favorable to its being read.

But as J. J. Gurney was the author of the suggestion, it met with but slight obstruction,
and Nield soon proceeded to read the protest,
changing the plural pronouns for the first person singular.
As this paper protested against the proceedings of
the previous Monthly Meeting in the case of Is. Crewdson,
alleging that those proceedings were-oppressive and not according
to the regular order of the discipline (which the weakness of the
committee had given too much ground for asserting),
the whole subject was thereby reopened to debate,
without any hope of profit to either party;
and J. J. Gurney came forward with a long but lame apology
for the manner in which the committee had acted throughout.
The Monthly Meeting was then adjourned to the 31st,
when William Boulton introduced his own case,
in order to show the injustice of his being advised by the committee
to withdraw from the meeting of ministers and elders,
without any specific charge brought against him,
but only on the broad assertion by the committee,
that as there was disunity in that meeting, it would be advisable for him to withdraw,
and to refrain from speaking in the line of ministry!

From the documents which he produced,
it did not appear that any attempt had been made to convince him that his own inconsistency
with the ancient principles and practices of the Society was one cause of the disunity;
though verbal attempts of this kind in private conversation may have been made,
without appearing in the written advice given to him from time to time.
He now demanded the true reasons for their course towards him,
saying that he was utterly ignorant of them.
Great discussions ensued, and several adjournments were consumed in empty debate.
The committee not only displayed the same weakness as in the case of Is. Crewdson,
in regard to a firm and clear advocacy of our essential doctrines,
but in order to avoid this,
and the necessity of a plain statement of the real facts of the case,
their conduct was characterized by a degree of shuffling and evasiveness
entirely unworthy of their characters as men,
and reproachful to the cause which they professed to be sustaining.^
footnote:[See [.book-title]#Crisis of the Quaker Contest in Manchester,# 1837, throughout.]

When the meeting finally decided to accept William
Boulton`'s withdrawal from the station of an Elder,
he came forth with an elaborate address to the Monthly Meeting,
in which he certainly expressed many undeniable truths,
but without appearing to be aware that they turned most palpably against himself.
One very especial truth he uttered,
which the committee might well apply to their own action:
"`Every effort to conceal the real character of this evil,
only prevents the application of the remedy.`"
Alas, he apprehended not truly either the evil or the remedy,
but (whatever may have been his candor) his own words evinced
that he was far from the standard of true Quakerism.
The committee must have known, that in his expressed sentiments,
as well as in practical conduct, he was not in accordance with true Friends;
but they dared not to advance on that ground,
being conscious that some of their own body were
at least equally liable to be called to account.

At the adjourned Monthly Meeting held eleventh month 1st,
the committee undertook to restore to their functions
the committee of the Quarterly Meeting,
by introducing it formally into the Monthly Meeting.
They had apparently been afraid to trust it with the case of the Beacon,
or with that of William Boulton;
but now they were willing it should do what it might be able to do,
to stop the disunity which they had so inefficiently attempted to check.
To this, however, the clerk strenuously objected,
alleging that such an "`interposition`" of the Quarterly Meeting`'s committee
would "`effectually destroy the independence of the Monthly Meeting,`"
and declaring that he could not conscientiously remain as clerk,
"`to record the edicts of that body.`"
Much opposition being made to the measure, the committee consented,
not to "`introduce`" the Quarterly Meeting`'s committee
until the other business of this month should be gone through.
The meeting then proceeded to the appointment of fresh overseers,
as nominated by a committee previously appointed.
This also met with great opposition.

At the adjournment on the 2nd of eleventh month, two female elders,
the wives of Is. Crewdson and William Boulton,
resigned their stations in the Select Meeting, which was accepted.
It would appear by various statements in the printed accounts
of this memorable Monthly Meeting (accounts which,
though published by the Beacon party, have, so far as I know,
never had their veracity as a narrative of the facts brought in question),
that the business was very far from being conducted in that weighty and
waiting frame of spirit which has always been considered necessary,
in regard to the business of the church, as well as in our meetings for divine worship.
At the next adjournment,
the clerk "`announced that George Stacey was in possession of the meeting.`"
George Stacey accordingly came forward,
and read a document from the committee of the Yearly Meeting,
in reference to the meetings held in Manchester,
for Scripture reading in connection with vocal exercises in the way of exhortation and
prayer which being unauthorized were considered by the committee an unsafe innovation.
The members of the Beacon party opposed this document with much warmth.
They were evidently preparing for a separation,
and allowed themselves greater liberty of expression against the committee than heretofore.
The document was received, but does not seem to have elicited any action at that time.
At the conclusion of this sitting, Joseph Crosfield resigned his position as clerk,
and then the Quarterly Meeting`'s committee was formally introduced.

The separation of the Beacon party began in earnest at the next Monthly Meeting,
the 10th of eleventh month,
by letters of resignation of membership tendered by twenty-eight members.
A month afterwards twenty others pursued the same course.
These were held under consideration,
and at the Monthly Meeting held on the 8th of twelfth month,
a committee was appointed to visit those who had resigned their membership.
On the 15th of the same month, this committee made a feeling report of their labors;
and the resignations, with a few exceptions, were then accepted, including Is. Crewdson,
William Boulton, and their connections and adherents.
Thus the Society allowed the author of the Beacon to depart,
without issuing any testimony to clear the church from his errors.^
footnote:[Even in his letter of resignation, accepted by the meeting,
he charged Robert Barclay with unsoundness of doctrine,
and George Fox with "`assumptions`" of a "`blasphemous character!`"]
These persons set up a separate association,
styling themselves "`Evangelical Friends;`" and being joined by
others of the same views about Bristol and in other parts of England,
they held a meeting in London in 1837, and issued a public Address,
after the manner of a Yearly Meeting Epistle.

But they did not stop there.
Many of them submitted to water-baptism, after the example set by Elisha Bates.
Some partook of the bread and wine and joined the Episcopalians;
some went to the "`Plymouth Brethren`" or to other societies;
and in a few years their organization as a distinct body disappeared.
The leaven, however, which had promoted this effervescence in the Society,
still continued to work.
No check was put to the numerous publications of J. J. Gurney, Edward Ash,
and others of kindred opinions,
notwithstanding the earnest expostulations of the Meeting for Sufferings in Philadelphia,
warning Friends in England of the dangers to be apprehended from
allowing unsound works to be freely circulated through the Society,
written by its own members.
Beaconism, as such, and before the arrival of J. J. Gurney in this land,
did not make much open headway in America.
It showed itself a little in New England, but though the leaven remained,
its spread there received a check, for the time, in a remarkable manner.
I believe the following account to be substantially correct,
having heard the circumstance related by divers friends of New England,
who appeared to be perfectly familiar therewith,
and were intimately acquainted with the parties concerned.

Seth and Mary Davis had for some time the superintendence
of the Yearly Meeting`'s boarding-school at Providence,
in Rhode Island.
William Almy, of that city, a very wealthy and influential man,
in the station of a minister, had great control of the school,
as a prominent member of the committee charged with its management.
He had been endeavoring to promote the introduction of the
doctrines of the "`Beacon`" party into New England,
and was now engaged in an attempt to bring the book into the library of the school.
This attempt, Seth and Mary Davis, sound in the ancient faith of the Society,
firmly withstood;
and as William Almy could brook no opposition to what he had undertaken,
he determined on compassing their dismissal.
One morning his worthy father-in-law, Moses Brown,
a well-known and faithful elder of many years`' standing for the truth,
then very far advanced in age (aged about ninety-seven at that time),
and much crippled in body, though clear and firm in his mental and spiritual faculties,
and thoroughly alive to his son`'s unsoundness, came to the school,
and informed the superintendents, with great grief,
of William Almy`'s determination with regard to them; adding that,
in order to accomplish his intention of getting rid of them,
he had called a special meeting of the committee for that morning,
and that with the view of avoiding the presence of his father-in-law,
who he knew would oppose such a scheme,
he had appointed it to be held in the third story of the building.

"`Now,`" said the worthy old man, "`I see not how I am to attend the committee,
for I cannot walk up those stairs.`"
"`But we will help thee up,`" replied Seth Davis and his wife; and accordingly,
placing their valued ancient friend in a chair, they carried him up to the third story,
and there he sat until the appointed hour.
The members of the committee assembled according to the call;
but William Almy did not appear among them.
After sitting for some time, a message came for Dr. Toby, one of the committee,
to the effect that his presence was required, as William Almy had been taken sick.
Some time afterwards, William Jenkins, son-in-law to William Almy,
received a similar summons; and finally, another message came to Moses Brown,
that William Almy was very ill.
He died, I believe, that day.
The object of the committee`'s meeting was thus frustrated
by this sudden and awful dispensation.
This was in the second month, 1836.

Elisha Bates also, of Ohio, as we have already seen,
had imbibed the views of the Beacon party,
after having for many years been an acceptable and well-qualified minister among Friends.
But it does not appear that he succeeded to any great extent in imbuing
the minds of Friends in his own Yearly Meeting with the same sentiments.
He had been an eloquent preacher,
and very serviceable while he abode in humility and the true fear of the Lord;
but of later time becoming exalted in his estimate of his own powers,
he often launched forth into flowery and showy discourses,
delighting much in the facility with which he could bring forward
the most beautiful and sublime passages of Holy Scripture,
especially in regard to our Lord Jesus Christ;
but the deeply spiritual views of our Society respecting the inward work
of the Spirit of Christ for our sanctification and daily instruction,
became more and more lost sight of in his discourses.
He let into his mind also feelings of jealousy in regard to certain friends,
who did not unite with some of his favorite plans; so that when he went to England,
his mind was in a state of preparation to receive
readily the insinuations of the Beacon party.
But after this,
his course became so rapid and unmistakable in its tendency out from Friends,
that his influence in America sunk almost at once
upon the fact of his water-baptism becoming known;
and eventually he went among the Methodists.

The floating unsettlement of mind which these novel
views produced in many of the members in England,
was very great and disastrous.
It is well exemplified in the following narration.^
footnote:[See [.book-title]#The Friend,# Philadelphia, second month 1st, 1873.
Taken from the British Friend.]

[.embedded-content-document]
--

To subvert the orthodox doctrines, as held by George Fox and his contemporaries,
was the object of Isaac Crewdson and his adherents; and to achieve it,
Friends in many meetings were weekly furnished with
printed extracts from the early writers of the Society.
Some of these were garbled--a word, or words, being left out, or added in parenthesis,
materially altering the sense.
One of these was sent to me, directed by the hand of a Friend of our meeting at Exeter,
beloved by very many of his friends for his kindliness
of disposition and practical benevolence.
Not content with sending these extracts weekly into almost
every house of Friends belonging to Exeter particular meeting,
he made visits to denounce the early Friends as fanatics.
A visit from this dear friend to me lasted three-quarters of an hour;
when he inveighed most vehemently against the early Friends and their doctrines,
finishing by these awful and remarkable words, viz.:
"`I hesitate not to say that the doctrines of the early
Friends are nothing short of the delusions of the devil!`"

A pause of several minutes ensued,
doubtless to give me an opportunity of replying or making a remark,
either in favor of his assertions or the reverse.
I could have said something; much, for my heart was full and sorely grieved;
but the restraining power was put upon me by the Lord`'s Holy Spirit.
I was not permitted to utter one syllable.
I sat silent; and then this dear friend again addressed me, fearing he had offended me;
told me his motive was to rescue me from spiritual death and consequent ruin of my soul.
I simply told him I was not offended; he took hold of my hand,
and bade me an affectionate farewell.
The next day he called again,
and evidently was much dissatisfied with himself on calmly reflecting on all he had said.
I did not feel forbidden to say something to him then.
The substance of my words was, as well as I can recollect: "`My friend,
I believe thou did not mean to offend me by thy language yesterday;
thou hast not offended me; but I am grieved indeed,
that one naturally so kind should express himself as thou
hast done towards the worthies of a brighter day than this,
and call in question what thou wast taught in thy youth, and professed until lately,
whether thou believed it or not.`"

We ever after remained and met in social good will, but the religious bond was severed.
I watched him for years, straying from one mountain to another.
He left, as might be expected, the Society of Friends,
and joined the "`Plymouth brethren,`" having unity with
them for a good while--met them in breaking of bread,
preached among them,
and seemed to have found an ark of refuge in communion with the "`saints.`"
But eventually he became dissatisfied, and went to the Wesleyan body,
to find food for his unsatisfied soul.
For a time he rested +++[+++there], but here he did not remain.
Strange to say, he who proclaimed in town and in the country,
by wayside and on the seashore,
"`the unsearchable riches of Christ,`"--told of the great atonement on Calvary,
of the Lamb slain for the sins of mankind,
of the efficacy of that blood to cleanse sinners from all defilement,--should,
by some new light he thought he had received,
go to the Unitarians and receive their doctrine--to what extent I cannot say,
for there are degrees even in this way--but in this profession of religious belief
he was found when the angel of death was sent to hover over his dwelling,
and in the fluttering of his wing to tell him his earthly race was nearly run,
the sands of time would soon be run out.

I went to his house to inquire how he was, hearing he was ill.
I sent up my name to his chamber, and was immediately invited to go to him.
I found him in an agony of soul--his arms beseechingly uplifted.
He gave me his hand, saying: "`Pray for me; oh, pray earnestly for me!`"
My sympathy and distress were so great that I could not reply for some time.
I then said, "`Oh, pray thyself;
the door is open for all to come boldly to the throne of Grace!`"
He turned quickly upon me with a fixed gaze, saying: "`Hear me; mark what I say,
and tell it; tell it as my dying testimony.
The Society of Friends hold the truth, the very truth;
their doctrines are the very truth of God; if they are only carried out.`"
This he repeated twice, "`if they are only carried out.`"
He paused, and then, with a loud voice, said: "`O God, look down in thy wonted mercy,
and pardon, or receive me!`"
He then signified to his wife that I might leave the room few a short time,
but to come back to him again.
I parted from him in agonized silence,
with a warm pressure of his hand and a look of deep sympathy.

I was asked to sit in the parlor; but I went home to my own house, and to my bedchamber,
where, on bended knees, I supplicated for him as if for my own life.
Suddenly, like a flash of lightning, all access of words or spirit was withdrawn,
and I rose from my prostrate position and sat down amazed at my feelings.
Not long was I left in uncertainty.
A knock at my door by a servant revealed to me that the
spirit of my friend had left its earthly tabernacle;
which accounted to me the cause of my strange position when pleading for my friend.
It has ever appeared to me a most remarkable thing,
that on his deathbed he should so solemnly revoke his assertions
respecting the Society of Friends and their doctrines,
and to the very person to whom his words of deprecation were addressed

[.signed-section-signature]
Elizabeth Knott.

[.signed-section-context-close]
Rathangan, sixth mo.
21st, 1807.

--

The individual alluded to in the foregoing account
is understood to have been Henry Treffry,
a man well known in the city of Exeter for his exertions in behalf of the poor.
He died in the early part of the ninth month, 1846,
and is believed to have renounced his reliance on his own intellectual abilities,
and to have again declared his faith in our Lord Jesus Christ.
His widow has recently confirmed the account, adding this testimony:
"`Well do I remember his words: '`Had I my time to live over again,
I would endeavor to hold fast the doctrines I had been taught,
and which are the very truth, provided they are carried out.`'`"
