== Chapter VII.

[.blurb]
=== The Rise And Progress Of The "`Gurney`" Controversy And Schism, To The Year 1840.

One storm had scarcely seemed to pass away,
before the thunderings of another alarmed those who
had ears to hear through the apparent lull.
And yet not another,
for before the body or outward form of what was called
"`Beaconism`" had entirely gone out at the back door,
its spirit, in a far more insidious and fascinating manner,
and with tenfold power to insnare and entice away the unwary,
had made an entrance at the front, had gained many of the upper seats, and was prepared,
not only to maintain its position there,
but to take measures calculated gradually and almost imperceptibly to
gain over nearly the whole Society to the very same fundamental changes,
the suggestion of which had been the foundation of the Beacon schism.
It soon became evident,
that but a small portion of the disaffection against our well-known principles
had already been cleared away by that schism--that the unsound leaven still remained,
and had even spread to a wider extent during the late difficulties--and
that the portion of the Society really concerned,
openly and unreservedly to maintain the ancient landmarks,
was becoming comparatively small.

The Yearly Meeting of London, in 1836,
had taken one very important step in lowering the standard;
and had thus unhappily opened a wide door for the influx of error,
of which the enemy failed not to take advantage;
and the ultimate results of which we are sorrowfully witnessing at the present day.
Thousands, nay, tens of thousands,
might have been subsequently preserved from lapsing into
the "`beggarly elements`" from which the Society was,
in early days, mercifully redeemed,
had it not been for this false step taken by that Yearly Meeting.
We must, therefore, turn back a little to the proceedings in London, of that year.
The Yearly Meeting from first to last was a memorable occasion
of conflict between ancient truth and modern error.
But a small part only of its transactions, bearing more particularly on this subject,
need engage our attention.

At one of the early sittings,
Sarah Lynes Grubb came into the men`'s meeting with a gospel message,
encouraging to faithfulness,
and solemnly warning the "`Babel builders,`" who were advancing to confusion of tongues.
The following is the substance of her address, written shortly afterwards from memory,
by a friend who was present:^
footnote:[See [.book-title]#S. Alexander`'s Voice from the Wilderness,# pages 40 to 43; also, [.book-title]#Life of Sarah Grubb, Late Lynes,# Eng. edit+++.+++, p. 333.]

[.embedded-content-document]
--

I am come among you, a poor weak creature, laden with a burden,
the weight of which cannot be expressed, even by the tongue of the eloquent,
much less by mine; but I must endeavor to lay it down.
The time is now come, often foretold, when the Lord would descend amongst this people,
as the rain, the storm, and the overflowing flood.
It must indeed be acknowledged, that a mighty shaking has come upon us.
There are among you those who have been as fruitful branches;
but for want of abiding in the root, and retaining the sap, they are withering,
and will wither.

The foundation of every individual in this Society will be discovered,
whether it be upon the rock or upon the sand.
"`Whosoever heareth my sayings,`" said our blessed Saviour, "`and doeth them,
I will show you to whom he is like.
He is like a man which built an house, and dug deep`" (Friends,
you do not like the trouble of digging deep), "`and laid the foundation on a rock.`"
The Jews heard this saying of Christ with their outward ears, but,
having their inward ears closed, they would not build on Him the Rock;
and when the rain descended, the floods came, and the winds blew, they fell.
How painful were the sufferings of our forefathers, in coming to this foundation!
Their opponents were strong in the words of the Scripture,
like those formerly who thought that in them they had eternal life;
to whom our dear Saviour addressed these words: "`Ye search the Scriptures,
for in them ye think ye have eternal life, and they are they which testify of me;
and ye will not come to me that ye might have life.`'`"

Thus, though they studied the Scriptures,
and imagined they were skilled in the knowledge of them, yet,
resting in their outward knowledge, they would not come unto Him of whom they testified,
and in whom alone there is life.
You, too, study the Scriptures,
by the strength of your rational and intellectual faculties,
and doubt not you comprehend their meaning; and here you stop:
you refuse to come unto Christ, in His inward and spiritual appearance;
you will not hear His voice speaking in your hearts, and are therefore rejecting Him.
Man is a dark, benighted creature.
By his natural powers he cannot know himself; he cannot discover his way out of the fall,
into a lasting union with his Maker.
His heart is deceitful above all things,
he must therefore come unto Him who searcheth the heart.
And how doth He search the heart?
By His Spirit; for "`the Spirit searcheth all things; yea, the deep things of God.
For what man knoweth the things of a man, save the spirit of man which is in him?`"
Even so the things of God knoweth no man, but the Spirit of God.
The light of Christ is imparted to each of us--a measure
of the same Spirit that gave forth the Scriptures.
When Adam had transgressed the commands of his Maker,
he lost the divine image in which he was created;
he died to the heavenly life he had in God.
But our Lord Jesus Christ, in His infinite mercy, entered into his +++[+++man`'s]
heart, as the true light, wisdom, and power;
and it is only in His light that we can see light.

Oh, my friends! there were some in ancient days who said one to another, "`Go to,
let us make brick, and burn them thoroughly; let us build us a city and a tower,
whose top may reach unto heaven.`"
Some of you are laying hand to hand, and shoulder to shoulder,
to erect a tower whose top may reach unto heaven; beautiful indeed to the eye,
and of fair proportions; and you are saying to others, "`Come,
and behold what we are doing; join yourselves unto us,
and we will show you the gospel path unto heaven; a path full of charity and love;
an easy and a comfortable path, wherein ye may avoid the cross.`"
But "`say ye not, a confederacy, to all them to whom this people shall say,
a confederacy.`"
Oh! beware of that subtle spirit,
which would lead you from the pure truth under such delusive pretensions;
for though these talk of the unity of the Spirit,
it is not the cementing influence with which Christ
unites his disciples in precious fellowship.
And I am commanded to tell you, that, as in the instance of the tower of Babel,
the Lord came down, and confounded their language;
so it will be with the Babel-builders amongst us.
For, when they come together, they will not understand each other`'s speech;
and their building on the sand will crumble to pieces, and they themselves will wither,
wither, wither! and be scattered to the north and to the south,
to the east and to the west.^
footnote:[This was, a few years afterwards, obviously in part verified,
in the scattering of the Beacon party.]

And, oh! let me earnestly entreat you of this description, in the love of the gospel,
to stand still, and see what you are doing.
I believe there have been times, when some of you have seen, in the true light,
that you were wrong; but the pride of your hearts would not suffer you to acknowledge it.
But remember, it is an awful thing, to tempt the Lord your God!
You know not how long these convictions may be granted you;
and if the light that is in you become darkness, how great is that darkness?
And now, my beloved young people,--you, dear children,
on whose account I have often raised the secret petition in my chamber,
and the more public one in the assemblies of our
people,--be not dismayed at the prospect before you;
for I have to tell you (and I wish you to take notice of it, and to write it down),
that all this that now causes so much stumbling and perplexity,
and produces such a sensation, will fade away,
and the authors of it will go back to the world and the beggarly elements; and,
on looking round, you will wonder, and say:
"`What is become of that great work that was doing, and where are the authors of it?`"

What became of those who, in former days, caused divisions in this Society?
Were they not all blighted and scattered?
And ye faithful ones, to whom the principles of truth are yet precious;
who love the pure cause, and are often bowed down in spirit on its behalf:
you have no cause to fear; for,
though you be left as the gleanings of the grapes of the vintage,
yet shall you be planted on a very fruitful hill; not one of self-exaltation,
but a hill above the level of the spirit of this world; and you shall spread abroad,
and increase, and flourish.
For this society was planted a noble vine,
wholly a right seed and it is not the will of the Almighty,
that this people should ever cease to be a people.
I brought nothing with me into this meeting;
for I remembered our Saviour`'s command to his disciples,
not to take thought how they might speak, for "`it shall be given you in that hour,
what ye shall speak.`"

--

At a later sitting, Ann Jones, of Stockport, likewise visited the men`'s meeting,
and is said to have expressed herself nearly as follows.^
footnote:[See a [.book-title]#Report of the Proceedings of London Yearly Meeting of Friends,# 1836,
published by John Stephens, 153 Fleet Street, pages 13 and 14.]

[.embedded-content-document]
--

I can truly say,
I came into this Meeting not knowing whether I should have anything to communicate;
but my mind has been impressed, as I have sat for a short season amongst you,
and I was willing to become a fool amongst you, for the sake of the Lord Jesus Christ.
Would that there were more among you, who were willing to become fools for his sake!
There are those among us who are encouraging a carnal wisdom, a head knowledge,
an outward learning, which exalteth itself, and is ever endeavoring, in its own strength,
to find out the way of salvation by the study of Scripture.
This spirit has spread even among those who are making
a very high profession--men who are robbing Christ.
They talk much of a belief in the atoning sacrifice,
but are setting at naught and despising Christ in his inward and spiritual appearance.
It is an awful thing, my friends, to take the name of the Lord in vain!
These take the words of the prophets, and apply them in a carnal sense.
Such was not the way in which our worthy predecessors acted;
the Lord raised our predecessors in the truth to be a light in a dark and degenerate age;
and through their instrumentality,
he was pleased to reprove the carnal professors of the outward letter of their day.

But there are some amongst you,
who are holding up to scorn the acts and writings of these our worthy predecessors,
and are endeavoring to cast disrespect upon them.^
footnote:[Elisha Bates was endeavoring, in print,
to prove G. Fox and our early Friends mere enthusiasts.]
Take care!
As you will have to give account in the awful day of righteous retribution,
I charge you to take care how you hold up them and their writings to derision.
They are resting from their labors, far beyond the reach of your derision.
Your bitter cunning shafts will turn against your own heads.
Beware, then, how, with unhallowed foot, you trample on their ashes,
or attempt to cast a shadow over the brightness of their character.
These expressions may appear strong; but I cannot choose my own words,
as a minister of the Gospel.
I always desire to be the instrument through which the Lord shall speak,
and not a word more than He shall give me,
and to declare to you the whole counsel of God, so that I may be clear of your blood.

The Lord hath a controversy with the spirit which hath crept into this Society,
and which is sitting in the judgment seat.
The Lord, I say, hath a controversy with these; but He hath, if possible,
a still greater controversy with those who are seeking
to please both parties--to pursue a middle course!
What concord hath Christ with Belial?
What union between the temple of God and idols?
But I have a word of comfort for the little remnant,
whom the Lord hath yet among his people.
May He grant you His Spirit to discern and to avoid the grievous errors which abound;
and the Lord God Almighty will show himself valiant on your side,
and will arise for your signal deliverance.

--

We may mark here her especial testimony against pursuing "`a middle course,`" and "`seeking
to please both parties;`" inasmuch as that "`middle course`" proved afterwards,
in the cunning craftiness of the enemy,
the great lever for aiding the schism to a wonderful degree in England and America,
carrying many into the ranks of innovation, who,
but for its plausible pleadings for peace and quietness at any price,
would not have been led into the temptation of throwing their influence into that scale.
After Ann Jones retired,
the meeting was occupied in considering the following
proposition from Westmoreland Quarterly Meeting,
which was prominently advocated by Isaac Braithwaite, viz.:

[.embedded-content-document]
--

A difference of opinion having arisen in the Society as to the
authority of Holy Scripture in matters of faith and doctrine,
this meeting requests the Yearly Meeting to take the subject into its serious consideration,
and clearly to define what are, in its estimation, the authority, place,
and office of the Holy Scriptures, as the rule of faith and practice.

--

The meeting was much divided in sentiment in regard
to the disposal of this insidious proposition;
the declared members of the Beacon party not being by any means
the only advocates of a definitive minute sustaining their views.
Great discussion ensued,
in which J. J. Gurney is represented as expressing his views as follows:^
footnote:[Vide Stephens`'s [.book-title]#Report of the London Yearly Meeting,# 1836.]
That "`he felt considerable difficulty in regard to the preamble of the proposition,
because he considered that the Society, from the earliest period of its existence,
had held the paramount authority of Holy Scripture,
and he hoped they would never depart from it.
Could he unite in the charges some had made,
he should be compel ed to turn his back on this beloved Society.
"`No, my friends,`" said he, "`we are, we always have been,
and by the grace of God we always will be, a Christian body;
but when once we shall have admitted the principle,
that impressions made upon our own minds can be superior to Scripture,
that moment we cease to be Christians.
We have ever acknowledged the direct authority of
Holy Scripture in determining religious controversy,
and not only in regard to the great doctrines of religion,
but we have had no other standard as to any conclusion
or practices connected with religion.`"

In continuation, he said,
he thought the degree of difference which existed among
them might be materially relieved by a little explanation,
and especially with regard to the use of the word rule,
which he considered an objectionable term.
The early writers of our Society instituted a comparison between the influence
of the Holy Spirit (as he supposed) and the Holy Scriptures,
calling the first a primary rule, and the latter a secondary.
It was certain that the influence of the Holy Spirit was the fountain of the Scriptures,
and in that case it was primary; also,
that the influence of the Holy Spirit existed before the Scriptures,
and in that sense also it was primary;
the mistake had ensued from making the Scriptures secondary, as it regarded authority.
He trusted that Friends would never give up their distinguishing
views of the free and independent operations of the Holy Spirit.
But with respect to authority, they had nothing to appeal to besides the Scriptures,
and they most be the ultimate standard and test of all religions truth.

Without controversy, the Gospel +++[+++meaning the Bible]
was given them for the purpose of their salvation, and, when applied to the heart,
was the power of God unto salvation.
Whatever mistakes individuals in the Society might have made,
he was confident that the body was sound,
and that it would never recognize the principle,
that the Holy Scriptures were to be subordinated to impressions made upon our own minds.
He could not doubt that every person in the meeting would unite in the following propositions:

[.numbered-group]
====

[.numbered]
_1st._ That the Holy Scriptures were given by inspiration.

[.numbered]
_2nd._ That the declaration being of divine authority, there can be no higher authority.

[.numbered]
_3rd._ That they are able to make wise unto salvation,
through faith which is in Christ Jesus.

[.numbered]
_4th._ That they are the only authorized record from
which we can learn whatever may be taught,
or required of Christian men to believe; and that whatever is contrary to Holy Scripture,
is to be esteemed a delusion of the devil.

[.numbered]
_Finally,_ that no other standard of religious belief is recognized by this Society.

====

He could not but believe,
that if Friends would allow their minds to sink into a state of calmness,
they might come to a satisfactory conclusion in this matter;
for he contended that the Society (as a Society) had always
been clear in its views of the authority of Holy Scripture.
But although such was his opinion, founded on close and deliberate investigation,
justice and truth required him to confess, that many writers and individuals,
both in the early and latter ages of this Society,
in their great zeal to uphold their own views,
had sadly committed themselves on this subject; and he regretted to acknowledge it.
They had advocated principles which he did not hesitate to declare, if carried out,
were completely subversive of Christianity.
But, in regard to the earlier writers at least,
this must be ascribed to excess of zeal for some particular truth,
and to that inaccuracy of thinking and writing,
of which all of them were sometimes guilty.

But though, from these causes,
he could not deny that they had sometimes overshot the mark,
he for one stoutly maintained their general Christian integrity.
The objectionable passages in their writings had of late
been brought into prominence by two opposite parties,
and with very different intentions.
While one party had adduced them for the purpose of exposing
the Society to an unmerited degree of odium,
the other had brought them forward to advocate them,
and the principles which might be deduced from them.
On the subject which particularly agitated the Society at the present time,
he did not hesitate to declare,
that he was a middle man--the Lord forbid that he should be any other!--and this not,
as some had asserted, from indecision,
but from a clear conviction that there was great danger, while they were avoiding Scylla,
of falling into Charybdis.
He would affectionately exhort his dear friends to take this middle course,
for he believed it to be the right one--to choose the middle of the river Jordan,
for that was the deepest.

He would not compromise one jot of true Christianity, nor yet of sound Quakerism,
for he asserted them to be +++[+++identical?--word obscure]. The distinguishing +++[+++tenet?]
of the Society had always been, the free and independent influence of the Holy Spirit;
and to this he would always hold.
The Society had compromised nothing which could be found in Holy Scripture,
and the expression, Christianity without compromise,
conveyed his notion of what Quakerism was.
In conclusion, he repeated,
that he was confident the Society had always been
quite sound in its estimation of Holy Scripture;
but he did hope, before this Yearly Meeting was over, that,
for the relief of the minds of some Friends,
it would again send forth a very decided and explicit statement on this important subject.`"

In these remarks (which I have believed it right to give entire,
as we find them in the before-mentioned reports,
and the general correctness of which report of them,
I have never heard to have been questioned or denied by him or his advocates)
he not only plainly evinced his erroneous position with regard to the Scriptures--a
position utterly and palpably at variance with the views of Robert Barclay,
and all our other early writers--and grossly misrepresented
what he called the sound tenets of the Society thereupon,
construing them to have believed what he believed himself,
and therefore averring that their belief was always sound; but also,
in the very same sitting in which that deeply experienced minister, Ann Jones,
had so solemnly testified against a "`middle course,`"
he announced himself as "`a middle man,`" adding,
"`the Lord forbid that he should be any other!`"--and
then exhorted his hearers to the same "`middle course.`"

Many Friends, nevertheless, opposed any action on the subject;
among whom were William Allen, George Jones, James Richardson, Samuel Rundell,
William Rickman, and Josiah Forster;
believing that the views of the Society were already sufficiently clear,
and some of them fearing that any fresh declaration respecting
it would but weaken their well-known and fundamental testimony.
But the meeting at length decided that the Committee on the General
Epistle should be directed to prepare and introduce a paragraph,
fully and explicitly confirmatory of the well-known and
previously recorded sentiments of the Society on the subject.`"^
footnote:[[.book-title]#Stephens`'s Report of London Yearly Meeting.# 1836, page 18.]
The committee, however, appear to have transcended the terms of their instructions,
and at a subsequent sitting brought in a form for the paragraph,
which after some slight changes stood as follows:^
footnote:[_Ibid.,_ page 30.]

[quote]
____

Often as our religious Society has declared its belief
in the divine authority of the Holy Scriptures,
and upheld the sacred volume as the only divinely
authorized record of the doctrines of true religion,
we believe it right at this time to revive some important
declarations of Scripture itself on the subject.
(Then, quoting 2 Peter 1:21; John 20:31; 2 Tim. 3:15-17; Rom. 15:4;
and John 10:35; none, certainly, of which,
texts do anything at all to sustain them in their assertion of
the Scriptures being "`the only divinely authorized record,`" etc.,
they proceed thus): Although most of these passages relate to the Old Testament,
our Society has always freely acknowledged that the principles developed in them
are equally applicable to the writings of the Evangelists and Apostles.
In conformity with these principles, it has ever been, and still is,
the belief of the Society of Friends,
that the Holy Scriptures of the Old and New Testament were written by inspiration of God;
that, therefore, the declarations contained in them rest on the authority of God himself;
and there can be no appeal from them to any other authority whatsoever:
that they are able to make us wise unto salvation through faith which is in Christ Jesus;
being the appointed means of making known to us the blessed truths of Christianity:
that they are the only divinely authorized record of the
doctrines which we are bound as Christians to believe,
and of the moral principles which are to regulate our actions:
that no doctrine which is not contained in the Holy Scriptures
can be required of any one to be believed as an article of faith:
that whatsoever any man says or does which is contrary to the Scriptures,
though under profession of the immediate guidance of the Spirit,
must be reckoned and accounted a mere delusion.

We trust, however,
that none of our members will content themselves
with merely entertaining a sound view on this subject,
but will remember that the Holy Scriptures are given
to us that they may be diligently used,
and that we may obtain a right understanding of them in the fear of the Lord.
Let us never forget that their true purpose is, under the influence of the Holy Spirit,
to bring us to our Lord Jesus Christ, that, by a living operative faith in Him,
we may obtain reconciliation with the Father, and be made partakers of everlasting life.
____

Though some of this was true, yet in its intent and aim it was false and insidious.
It would be difficult to explain where the committee found
anything in the prominent features of this paragraph,
explicitly confirmatory of the well-known sentiments of the Society,
or even in accordance with the well-known sentiments of
a single acknowledged writer among our early Friends,
in conformity with their instructions.
It is on the contrary a direct abandonment of the
principle always promulgated in their writings,
that the appointed means for the soul of man to obtain a saving knowledge of God,
is a being taught in the school of Christ,
through obedience to the "`Inspeaking Word,`" and faith in the
revelations of His Holy Spirit immediately in the heart;
which will always be consistent with Scripture.
Its intent moreover in designating the Scriptures as "`the only
record "`appears to have been to exclude the idea of any divine
authority in the writings of such men as George Fox,
Robert Barclay, or Isaac Penington,
or in the excellent code of discipline and confessions of faith established
and acknowledged by Friends under the pointings of wisdom from on high;
and thus by bartering away one of our fundamental principles,
of unspeakable practical importance, the vain hope was entertained,
of conciliating and staying the secession of those
who did not believe in the doctrines of the gospel,
held by our ancient Friends.

This document was read twice over as a whole, and then considered by sentences,
so that the meeting had its sense clearly and fully before it.
Several friends objected to the words,
"`the only authorized record;`" and William Southall, of Leominster,
declared that the admission of that expression went
to the subversion of the very foundation of Quakerism.
But J. J. Gurney promptly replied that he considered
the expression perfectly correct and safe.
Notwithstanding considerable opposition therefore, the paragraph was adopted,
and thus the Yearly Meeting of London placed itself foremost in a clearly defined official
departure from at least one of the fundamental and characteristic tenets of true Quakerism,
and opened a wide door for other innovations.

In the year 1834, Samuel Rundell, a friend residing in the southwestern part of England,
had published a small treatise on Redemption, Divine Worship,
and partaking of the flesh and blood of Christ;
a work entirely consonant with the views of true Friends from the beginning of the Society,
and consequently calculated to operate in some degree as an antidote to the new opinions.
But a second edition being called for, early in 1836,
he submitted it to the consideration of the "`Morning
Meeting of Ministers and Elders`" in London;
the body to which appertained, according to the practice in England,
the function of examining all works on doctrinal subjects,
proposed for publication by members of that Yearly Meeting.
That meeting was mainly composed of the ministers and elders residing in and near London.
After reading Samuel Rundell`'s treatise, the meeting referred it to a committee.
This committee kept it shut up for twenty months.^
footnote:[See [.book-title]#Letter of Lydia A. Barclay,# in [.book-title]#J. Wilbur`'s Journal and Correspondence,# p. 240;
and [.book-title]#Letter of John Barclay,# in same work, p. 226.]
At length, in the eleventh month, 1837, the matter was roused up by John Barclay;
when it appeared that the treatise was not approved by some,
as inculcating views which most of the committee thought objectionable.

John Barclay then came forward in a firm defence of the tract,
confuting all the objections,
and closely expostulating with several of the members on their tendency outward.
But William Allen alone stood openly by John Barclay, in support of the work;
so that the objectors, having the control in their own hands,
ordered a letter to be written to the author,
strongly advising his withdrawing the treatise from publication.
Thus they thought to have suppressed it, and it was soon given out,
that the author had withdrawn it.
But in consequence of the decided encouragement given to its publication,
notwithstanding all this, by Daniel Wheeler,^
footnote:[[.book-title]#J. Wilbur`'s Journal and Correspondence,# p. 241.]
who knew it to be sound as to true Christian doctrine, and applicable to the times,
S+++.+++ Rundell, who had requested and been refused a conference with the committee,
concluded to take the responsibility of publishing it,
and obtained the assistance of Abraham Rawlinson Barclay in passing it through the press.
Here was another instance of serious dereliction from our
ancient principles on the part of the leaders of the people,
now manifested in an endeavor to suppress the publication
of the fundamental doctrines of the Society.

Still another evidence of the tone of feeling prevalent
among the influential members at that time,
to discountenance all public avowals of some of our true and indeed distinguishing doctrines,
was furnished by the action of the Meeting for Sufferings,
in printing extracts from the Journal of Daniel Wheeler,
while engaged in his visit to the islands of the Pacific Ocean;
by which the accounts which he sent to England were mutilated
and shorn of some of the most important portions.
Daniel Wheeler himself, when in Philadelphia, told the writer of this work,
that portions of his manuscript which he was the most anxious to have published,
if any should be published at all during; his life,
(of which he was himself inclined to doubt the propriety), that these portions,
developing his true position in relation to the missionaries in those islands,
and his plain advocacy to them, of the spiritual nature of the gospel dispensation,
and the necessity of primary attention to "`the inspeaking
Word,`" nigh in the hearts of all men,
had been to a large extent suppressed in putting
his accounts in print during his absence.

He was especially grieved at this injustice,
because it placed him permanently before the public in a defective,
if not actually in a false light.
Many paragraphs thus omitted were of great doctrinal significance,
and were restored in the edition of his Life and Gospel Labors,
printed after his decease by his children, with the aid of Abraham Rawlinson Barclay.
These omissions may be easily recognized by comparing pages 324, 344, 362, 365, 367, 417,
549, 551, 568, 570, 571, 575, and the _Address to the Missionaries,_ of eight pages,
commencing at page 652, of the last-named work,
with the corresponding parts of his Journal as at
first published by the Meeting for Sufferings.
These omitted passages represented Daniel Wheeler as inculcating
to the natives of those islands and to his hearers generally,
on various occasions,
the necessity of obedience to "`the witness in the heart of every man`"--that
there was "`no necessity to look to this minister or that minister,
but to Christ,
the true minister of ministers,`"--turning their attention primarily to their
Heavenly Teacher--that "`the grace of God that bringeth salvation hath appeared
unto all men`"--that "`that which made them sensible of sin,
was the gospel,
which was preached in and unto every creature under heaven`"--showing them the
distinction between the word that "`was in the beginning with God and was God,`"
and the Bible--affirming that the Holy Spirit was greater than the Scriptures--desiring
"`that Christ might dwell in their hearts by faith`"--and opening to them the
coming of his Holy Spirit into their hearts,
and the great truth of the Universality of the grace of God.

The _Address to the Missionaries_ was entirely omitted.
It was a touching and earnest farewell appeal to them,
written under a deep feeling of concern and exercise;
recommending close attention to the "`still small voice,`" in "`the silence of
all flesh`"--reminding them that "`as a stream cannot rise higher than its fountain,
so it is impossible for any to instruct others further than they themselves have
learned in the school of Christ`"--and that "`a historical or traditional faith,
or one that admits of a continuance in sin,
is dead and unavailing`"--and finally commending them to God and the Word of his grace,
"`even that eternal Word, which liveth and abideth forever.`"
What true Friend could venture to allege that such
sentiments were not fit to be spread before the public?
And what but a culpable want of faith in the genuine principles of Quakerism,
can have induced the attempted suppression of them?

A few days after the close of the Yearly Meeting of 1836, viz.,
on the 12th of the sixth month, died at Tottenham near London,
that honest laborer in the Lord`'s vineyard, Thomas Shillitoe, aged about 82 years.
He had only been able, from great debility of body,
to attend a very small portion of the Yearly Meeting; perhaps the last sitting,
and one sitting of the Select Meeting.
But his mind was still livingly concerned for the welfare of the Lord`'s heritage.
His last sickness was a short and suffering one,
but attended sensibly by the merciful presence of the Master
whom he had long endeavored faithfully to serve;
and who now sustained his spirit in great calmness and peace,
through all the conflict of bodily dissolution.
He uttered, during these few days, many sweet expressions,
evincing his comfortable hope and trust in Christ his Saviour.
Three days before his decease, his neighbor John Hodgkin coming into his room,
he requested him to take down in writing the following testimony of his dying sentiments,
in regard to the Episcopalian tenets of Joseph John Gurney.

[.embedded-content-document.testimony]
--

This testimony rested on his mind, and he must have it committed to paper,
as he found his peace consisted in so doing.
+++[+++Then addressing J. H.]
Thou wilt want a great deal of time and patience, to hear what I have got to say,
and it must be faithfully delivered, for I am afraid, at a future day,
it will devolve heavy upon thy shoulders.
It is extraordinary that thou shouldst have come in at this juncture,
for I have been wanting my son-in-law to come in,
and put down what I am now better satisfied should be received by thee from my mouth.
And I therefore declare, unequivocally,
against the generality of the writings of Joseph John Gurney,
as being non-Quaker principles, not sound Quaker principles, but Episcopalian ones;
and they have done great mischief in our Society; and the Society will go gradually down,
if it yields to the further circulation of that part of
his works which they have in their power to suppress.
This is my firm belief.
I have labored under the weight of it for the last twelve months,
beyond what human nature is able to support.

And the committee of the Morning Meeting which passed that
last work (Gurney`'s '`Peculiarities with a new title),
must be willing to come forward, to be sufficiently humble to acknowledge their error.
And the Meeting for Sufferings must also be willing to remove its
authority in allowing it to be given away to those not of our Society.
I declare the author is an Episcopalian, not a Quaker.
I apprehend J. J. Gurney is no Quaker in principle.
Episcopalian views were imbibed from his education, and still remain with him.
I love the man, for the work`'s sake, so far as it goes;
but he has never been emptied from vessel to vessel, and from sieve to sieve,
nor known the baptism of the Holy Ghost and of fire,
to cleanse the floor of his heart from his Episcopalian notions.
He has spread a linsey woolsey garment over our members;
but in a future day it will be stripped off; it will be too short for them,
as they will be without Jesus Christ the Lord.

This is my dying testimony, and I must sign it.
If I had been faithful,
I should have expressed it in the last Yearly Meeting of Ministers and Elders;
but I hope I shall be forgiven.
O Lord! accept me with the best I have!
I have letters from America,
which confirm me in the truth of every part of what I now state.
I believe there is not an individual member of our Society, in England, Scotland,
or Ireland, more willing to do good, than J. J. Gurney.
But willingness is no qualification.
This is my dying testimony to Quaker views, especially as to the ministry.
What was antichrist in George Fox`'s days, is antichrist now.
The clergy of this country, to a man, every one of them,
are antichrist so long as they wear the gowns and receive the pay,
and continue building up the people in the relics of Popery,
which the church of England left behind +++[+++retained]. It will not
do to speak of a man doing a great deal for a little pay,
and call him a minister of Christ.
It is a grievous thing, that any minister in our Society should so speak.
They are antichrist still, since they lead the people from Christ.
And yet I love some of them for the work`'s sake, so far as they go.

--

Towards the close of the pamphlet controversy in regard to the [.book-title]#Beacon,#
J+++.+++ J. Gurney prepared for publication,
as an appendix to his [.book-title]#Strictures on Truth Vindicated,#
a tract entitled _Brief Remarks on Impartiality in the Interpretation of Scripture;_
but on submitting both these together to the Morning Meeting of Ministers and Elders,
that meeting avoided the responsibility of sanctioning the _Brief Remarks,_ and,
separating the two, only approved of his publishing the Strictures.
Yet he afterwards issued the Brief Remarks, printed for private circulation only,
and distributed them among the ministers and elders.
This, however, made them all the more sought after,
and before long the tract was reprinted by other parties,
for publication without his sanction.
It thus obtained a wide distribution, and although not published ostensibly by himself,
yet it showed his real sentiments, and what he would have published, had he not for once,
been prudently restrained by the Morning Meeting.

No wonder, that even this meeting could hardly venture to sanction it;
for in this work he came forward more distinctly than ever before,
against the authority and judgment of our early writers on points of doctrine.
Indeed this brief production could scarcely be looked upon by any unbiased mind,
as other than a direct attempt to undermine the authority of our ancient authors,
as exponents of our true principles.
It had the appearance of being a specification of the charge
of "`serious errors,`" stated by him in general terms,
in the Yearly Meeting of 1836.
It contained twelve specific instances of what he
considered erroneous interpretations of Scripture,
on the part of "`some persons,`" and "`several writers;`"
by which a "`fictitious and spurious support`" had been,
as he thought, given to "`genuine Quakerism;`" and he declared his conviction,
"`that the sooner such errors are rectified,
the better for the growth and prosperity of our little section of the
Christian Church;`" inasmuch as "`they are the stepping-stones,
by which unwary persons may be, in no small degree,
assisted in an actual descent into heresy.`"

His first instance was the interpretation put upon
"`the more sure word of prophecy`" (2 Peter 1:19-21);
which he thought referred to the Scriptures,
in direct contradiction of the testimony of George Fox, William Penn, Robert Barclay,
George Whitehead, Francis Howgill, Samuel Fisher, James Parnell,
and indeed the unanimous voice of all our early writers.^
footnote:[These objections are more fully described in [.book-title]#An
Examination of the Memoirs and Writings of J. J. Gurney,#
pp.
109 to 124. Philadelphia, 1806.]
His second objection was to the interpretation put "`by some persons
under our name,`" upon the word Gospel (as Rom. 1:16),
which he thought ought not to be described as "`the power of God unto
salvation,`" but confined to the "`glad tidings`" of the "`incarnation,
crucifixion, and resurrection,`" of our blessed Lord Jesus Christ.
Here again he ran directly against George Fox, R. Barclay, Edward Burrough, etc.,
designated here by him as "`some persons under our name.`"
His third objection was similar,
in which he construed the apostle (Col. 1:21-23) in saying
that the gospel was "`preached to (or in) every creature under
heaven,`" merely to mean that the glad tidings of the incarnation,
etc., of Christ had then "`reached every province`" of the Roman Empire or known world!

His fourth was in reference to John 1: 9, "`The true light,
which lighteth every man that cometh into the world;`" objecting to the view of "`several
writers,`" that "`the light of the Spirit of God in the heart of man,
is itself actually Christ:`" whereas Barclay says that "`forasmuch
as Christ is called that light that enlightens every man,
the light of the world, therefore the light is taken for Christ;`" and again,
"`the light of Christ is sometimes called Christ, i. e. that in which Christ is,
and from which he is never separated.`"
His fifth instance was of the same import, objecting to the practice,
common among Friends,
of designating Christ as "`the anointing,`" as he considered that
this was "`identifying Him with the influence of the Holy Spirit,`"
His sixth instance was in reference to the expression,
"`Christ in you the hope of glory,`" which, he said, was "`often recited by mistake,
as Christ within.`"
His objection here showed his outward and carnal views,
and his practical discarding of the doctrine of Christ, by his Spirit,
dwelling in the hearts of the faithful.
What he here alleged was palpably contradictory of Robert Barclay,
and the whole scope of early Friends`' writings.

His seventh objection was to the use made by George Fox and many others,
of the word "`seed,`" in applying it to the inward appearance of Christ in the soul;
alleging that "`these mistakes,`" and particularly in reference to "`Christ the
light,`" and "`Christ within,`" have "`aided that tremendous process of heresy,`"
by which the "`Son of God is gradually converted into a mere influence,
and finally becomes nothing at all but a seed sown in the hearts of all men.`"
He expressed disapprobation of the manner in which the term was used by George Fox,
in saying, during his last sickness, "`Though I am weak in body,
yet the power of God is over all, and the Seed reigns over all disorderly spirits.`"
Isaac Penington and Robert Barclay also frequently made use of the expression;
and in a famous dispute at Aberdeen, between R. Barclay and George Keith,
and some students of theology,
George Keith in sustaining the propriety of the use made of the term by Friends,
quoted Clemens Alexandrinus, as having said,
"`that Christ compared himself to a grain of mustard-seed,
in his inward appearance in the heart.`"

His eighth instance was in regard to the saying of our Saviour to Peter,
"`Upon this Rock will I build my church,`" etc.
(Matt. 16:15-18),--alluding to the immediate
revelation of Himself to the mind of that apostle,
from the Father, by which he was enabled livingly to confess, from a blessed conviction,
"`Thou art the Christ, the Son of the living God.`"
It seems extraordinary to find J. J. Gurney here intimating the sentiment,
that "`this Rock`" was intended by our Lord to refer
to the mere fact acknowledged by Peter,
of Jesus being "`the Christ, the Son of God.`"
George Fox is very clear on the subject, in his [.book-title]#Doctrinal Works,# pp.
999 and 1000. His ninth and tenth objections were in regard to
"`the name`" of God or of Christ being considered by Friends,
in many instances, to refer to his power (as Acts 4:9; John 16:23,
etc.). And he goes so far as to say that to pray in the
name of Christ is merely to ask "`on the authority of Jesus,
and to plead his interest with the Father; or, in other words,
to pray in sole dependence on his all-availing mediation;`" rejecting
the idea of its referring to prayer "`under the influence of the Spirit
of Christ;`" and saying that "`to ask a favor of A. in the name of B.,
is to make use of the authority or interest which B. has with A.,
in order to obtain that favor.`"
And he implied that the belief,
that "`prayers which contain no reference to the mediation of Christ,`"
are "`nevertheless acceptable,`" is merely a "`notion.`"

This is not the place for it, or many extracts from our early writers might be adduced,
evincing that they were entirely agreed in considering the power
of God to be often implied in the Holy Scripture by the expression,
of his "`name.`"
Robert Barclay`'s testimony on this point is very clear,
that "`the name of the Lord is often "`taken, in Scripture,
for something else than a bare sound of words, or literal expression,
even for his virtue and power.
That the apostles were by their ministry to baptize the nations into this name, virtue,
and power, and that they did so, is evident by these testimonies,`" etc.
His eleventh instance of apprehended misinterpretation on the part of our early Friends,
was in respect to the view they have always taken of the "`body and blood of Christ.`"
Believing as he did that "`the flesh always means his human body,`" and that
"`his blood always means his very blood,`" he stumbled sadly in striving to explain,
according to human learning and wisdom, that "`the metaphor lies--not in the blood,
but in the drinking, sprinkling, washing, etc.`"
Truly did Barclay say, and Gurney exemplify,
that the "`communion of the body and blood of Christ
is a mystery hid from all natural men,
in their first, fallen, and degenerate state, neither, as they there are,
can they be partakers of it, nor yet are they able to discern the Lord`'s body.`"

The twelfth of these objections was against the interpretation always given by Friends,
to the text (Heb. 9:27-28) concerning the coming of Christ "`the second time,
without sin, unto salvation.`"
He asserted,
in direct opposition to the uniformly expressed views
of sound Friends from the beginning of the Society,
that this second coming "`is nothing more nor less than his future coming in glory,
to judge the quick and the dead;`" and thought it a "`mistaken impression,`"
which has led "`some persons,`" to "`apply this passage to the coming of Christ,
by his Spirit, for the refreshment and edification of his church.`"
After all these objections to our early writers,
he seemed to desire still one more sweep,
to do away entirely with any confidence in them as exponents of true Quakerism;
concluding with the following words: "`Were I required to define Quakerism,
I would not describe it as the system so elaborately wrought out by a Barclay,
or as the doctrine and maxims of a Penn, or as the deep and refined views of a Penington;
for all these authors have their defects, as well as their excellencies;
I should call it, the religion of the New Testament of our Lord and Saviour Jesus Christ,
without diminution, without addition, and without compromise.`"

It were strange, indeed,
if he did not know that this would be no definition to satisfy others,
inasmuch as every Protestant community would say the same of their own profession.^
footnote:[Judge Drake, in arguing against the Hicksites,
in the famous New Jersey suit in 1832, alluded to a similar statement of theirs,
justly remarking:
"`There is nothing characteristic in '`a belief in the Christian
religion as contained in the New Testament.`' All sects of Christians,
however widely separated, unite in professing this.`"]
Yet few of their members would be found disposed so to run down their standard authors,
as if they were very mistaken men.
J+++.+++ J. Gurney had by this time manifested,
in his numerous publications (irrespective of the last named _Brief Remarks on Interpretation_),
the following points of variance from the settled characteristic doctrines of Friends.

[.syllogism]
* He considered that the saving knowledge of God was to be obtained only through the Scriptures--though granting the need of the aid of the Holy Spirit in applying them.
* That for this end, the Scriptures are to be studied, with such helps as can be obtained from commentaries, and the plain laws of criticism, "`familiar to every scholar.`"
* That the Scriptures are the primary rule of faith and practice--not the Spirit--though granting the latter to be prior to them in point of "`order and dignity.`"
* That the Bible is "`the only authorized record of divine truth,`" "`the divinely appointed means of conversion,`" the "`only means whereby to obtain a knowledge of sin,`" or of a "`call to repentance,`" or of the "`attributes of our Heavenly Father,`" or of our "`moral duties,`" and that the evangelical narratives therein are "`the Gospel;`" thus practically discarding our great fundamental doctrine of Immediate Revelation and Universal and Saving Light, as stated by Barclay and others.
* That faith is a "`reliance of the soul on the incarnate Son,`" yet that it is a "`natural faculty,`" and confounding it with Belief.
* That the righteousness of Christ is imputed to believers in Him--to "`whosoever places his reliance on him as the atonement for sin,`" even though "`vile and polluted`" with sin; thus saving men in their sins, not from them--therefore that "`justification precedes sanctification.`"
* That the Father is a person--the Son a person--and the Holy Spirit a person--also speaking of them as "`plurality in unity,`" and "`plurality in essence,`" terms quite as objectionable and unscriptural as "`Trinity in unity,`" if not more so.
* That there is a "`separate state,`" a "`mansion of separate spirits,`" between this life and the one of eternal duration. That these same bodies will rise in the resurrection, as spiritual bodies.
* That the first-day of the week is "`the Christian Sabbath`"--a "`hallowed day.`"
* That daily prayer in words and on the knees, ought to be taught to children as a "`habit.`"
* That all mankind are in "`punishable guilt`" in consequence of the transgression of our first parents; "`inheriting a nature injected with sin,`" and are "`from birth vile and polluted essentially, the common doctrine of original sin.`"^
footnote:[For proofs of his advocating those sentiments
see _An Examination of His Life and Writings,_
Philadelphia, 1856; also the [.book-title]#Appeal for the Ancient Doctrines,#
and [.book-title]#John Wilbur`'s Exposition.#]

Besides the writings of J. J. Gurney,
which exerted a powerful influence in modifying the views and practices
of many who did not follow the "`Beacon`" party in their precipitate movement,
Edward Ash, a physician of Bristol, issued several books of a kindred tendency,
and evidently aiming with the former, to bring about, in the Society at large,
without any open schism, an essential modification of some of its fundamental doctrines.
He, too,
insidiously endeavored to destroy the confidence of Friends in our early writers,
as exponents of divine truth,
although professing great esteem for their practical faithfulness and dedication.
But, while similarly insidious,
his works were not of equal importance with those of J. J. Gurney,
being not nearly so numerous, nor so extensively received.
Nor was the personal influence of the one to be at all compared with that of the other;
received and welcomed, as was J. J. Gurney, by all ranks of the community,
as a learned and philanthropic man,
and cherished and applauded as the brother and earnest coadjutor of Elizabeth Fry.

Joseph John Gurney, in 1836, had declared himself "`a middle man,`" doubtless,
with a view to compromise, and to reconcile the contending parties,
and thus to continue to hold a powerful influence, if not a controlling one,
over the whole.
But when he saw that he had been unable to prevent the secession of the Beaconites,
and that all his efforts towards it only threatened to recoil upon himself,
he apparently threw himself back into the ranks of those,
then numerous in the Yearly Meeting,
who professed to be standing for the doctrines of the Society, though in reality,
by that time, much mixed and entangled with modern views.
Having studiously kept himself in the main current through the preceding difficulties,
he found it practicable for him to remain in it,
without giving up any part of the novel views which
characterized his writings and public declarations,
and without going any further than he had hitherto done,
towards founding his doctrines on the only sure basis,
the inward teachings of the Spirit of truth--the light of Christ in the
soul--which will never contradict the testimony of Holy Scripture.

Many Friends were far from being satisfied that he was sound in the faith,
even when he came round and professed his adherence
to what he deemed the proper doctrines of the Society;
and some of them clearly saw that the late schism of the Beaconites had
resulted from the very sentiments advocated in his published works.
But as he now opposed the secession,
and used strenuous endeavors to keep the Society together,
many of these were willing to hope that he was drawing nearer to the truth;
and the bulk of the members in England, who greatly admired his popularity,
and looked up to him as a man of extraordinary qualifications, clung round him in a body,
and frowned down the open expression of suspicion that all was not right with him.
It is wonderful,
with what a fascination he held control of the sentiments of nearly all the members,
and turned them to the promotion of what he had in view--the establishment,
in the whole Society,
of a more popular way of religion than that which
was revealed to and promulgated by our early Friends.
It is true that this purpose was not confined to him,
but was shared by many others in common with him.
Yet it is equally true and manifest,
that J. J. Gurney was the chiefly prominent developer of the new system,
the one whose writings had given it an open and free start and impetus in the Society.

And here, inasmuch as his name necessarily appears, and must still necessarily appear,
in much prominence in this account of the sad things
that have happened to us in these latter days,
I believe I must, once for all,
disavow--as I do earnestly repudiate--any motives of personal
animosity or ill-feeling towards him as a man,
in the freedom with which I have believed it my duty thus to treat
his published sentiments and the public tendency of his course.
My early prepossessions, from association and otherwise, were decidedly favorable to him,
being ignorant of his divergence from our ancient principles.
And when at length the conviction was fastened on my mind,
that there really was this divergence, and even contrariety,
it was (and has ever since remained, so far as I know my own heart),
without any personal feeling, or the least willingness to injure him or do him injustice,
that I was constrained to stand, with others,
in an attitude of opposition to his declared sentiments,
and the revolutionary tendency of his course.

In the spring of 1837, J. J. Gurney,
having been liberated by his Monthly and Quarterly
Meetings to pay a religious visit to America,
opened his prospect in the Yearly Meeting of Ministers and Elders in London,
for its sanction.
Such a proposal on his part brought some Friends into a narrow place.
They apprehended danger, from the novelty of some of his views;
they could not feel that the prospect was really owned by the Shepherd of the sheep,
as being of His own putting forth;
but they knew the powerful influence that was around him,
and a slavish fear took hold of some, lest more harm might arise from opposing it,
than by allowing it to proceed.
Some, however, were faithful to their convictions of duty, and firmly opposed it.
Among these, none appear to have spoken more clearly than Sarah L. Grubb; who,
in the fear of her divine Master, expressed her apprehension,
notwithstanding J. J. Gurney`'s talents, learning, and desire to do good,
that he needed a submission to more humbling baptisms of spirit than he had yet had,
to qualify him for the service; adding that,
in feeling after a right sense in regard to the proposal,
restraint had been the impression upon her mind;
and she believed the language that ought to go forth, was:
"`The Spirit suffereth it not now;`" repeating this expression three times over.

Ann Jones expressed her cordial unity with S. Grubb`'s remarks;
and similar views were expressed by George Jones, John Grubb, Abram Fisher,
Joshua Treffry, and several other men and women Friends.
An attempt was then made by Josiah Forster and Hannah C. Backhouse,^
footnote:[See [.book-title]#Proceedings of London Yearly Meeting of Friends,# 1837.
London: James Dinnis, 62 Paternoster Row.
The writer, in quoting from this and other similar publications,
only takes them as containing statements of facts, now become matter of history,
and of important bearing;
but would by no means be understood as approving of the publications.]
to take off from the weight of these objections,
by implying that the speakers had objected merely to this being the rigid time; and,
if the printed accounts of what passed are at all reliable, the former,
taking advantage of a weak point in some of the objections, went so far as to intimate,
that for Friends to object, as they had done, to the time,
was entering into human reasoning; that they had simply to look at the thing itself,
and what was the mind of Truth upon it: but that to judge about the time,
was a departure from our spiritual views!
Hannah C. Backhouse likewise, it seems,
considered that they had nothing to do with the time;
that times and seasons were not at their command,
but in the Lord`'s hands (as if the simple sending forth of the servants,
irrespective of time, was not quite as much so);
adding that she had been distressed and surprised, and thought Friends,
in objecting to the time, had lost sight of the main object;
spoke much of her sympathy with J. J. Gurney in his conflicts of spirit;
and warned those who were opposing the concern,
that it was very easy to be led by the cunning enemy to mistake our own
imaginations and prepossessions for the impressions of the Lord`'s Spirit.
All which was very plausible.
She said she believed that "`the reasoner`" was uppermost with some present; and that,
under what she herself conceived to be the true anointing,
she believed their dear brother ought to go to America.

Sarah Grubb desired that friends should understand,
that what she had said was not grounded on any reasoning about the time;
neither was it given her to see that this concern would be right at any future time.
In what she had said,
she had simply in view to give the message from the Lord in this matter,
and what she believed to be the mind of the Spirit.
In doing this, she well knew that she must be given up to reproach,
which she desired to be enabled to bear.
The language sounded in her spiritual ear, was,
"`The Spirit suffereth it not now;`" and it was not
given to her on this occasion to see into futurity.
Elizabeth Dudley spoke warmly in support of the proposed visit.
So did E. Fry, E. J. Fry, Samuel Gurney, and William Forster.
Several on the other hand objected to it; others again spoke in approbation;
but the opposition is said to have continued to the last.^
footnote:[[.book-title]#Proceedings of London Yearly Meeting,# 1837, Dinnis, p. 11.]

After considerable time it was proposed by Jonathan Backhouse and Josiah Forster,
that a committee should be appointed, to draw up a certificate;
which was accordingly done; the purport of the minute being,
"`that the subject had obtained deliberate consideration,
and it was concluded to appoint a few Friends,`" etc., naming them.
Josiah Forster suggested a small addition to the minute,
that Friends had been united in desire to come to a right conclusion.
But the clerk, William Allen, replied, that he thought,
after all they had witnessed that morning, the less said, the better.
At the adjourned meeting, on the 3rd of the sixth month,
to which the committee presented their essay of a certificate,
so great was the difficulty in coming to a conclusion,
that it is said the meeting continued for nearly five hours,
mainly occupied with this matter.^
footnote:[[.book-title]#Proceedings,# published by Dinnis, p. 73.]
Charlotte Burgess, of Leicester, early in the sitting,
solemnly warned those who were learned and rich as to this world,
to submit to the sword of the Lord,
lest they should be swept away by the besom of the Most High,
which she had seen to be in store towards this portion of the Lord`'s heritage;
and testified that the Almighty required perfect obedience from his servants,
in the exercise of their gifts;
which was only to be attained by deep indwelling with the pure seed of life, light,
and salvation,
and by submission to those baptisms which would refine
and make us as vessels of pure gold,
fit for the Master`'s use.

The proposed certificate being read,
several Friends who had objected to the concern at the former meeting,
now expressed that their views had not changed.
John Barclay, Jacob Green, Catherine Abbot, Sarah Harris, Abigail Dockray,
and several others, expressed decided objections.
The subject of J. J. Gurney`'s writings was again and again brought forward,
as an obstacle, and a conference with him on that subject was proposed.^
footnote:[[.book-title]#Proceedings,# published by Dinnis, p. 74.]
Jonathan Backhouse, however, turned this aside,
by alleging that this was not the subject before the meeting.
A number of members approved of his being set at liberty; among whom John Allen,
of Liskeard,
said that he had taken a private opportunity of conversing with J. J. Gurney,
who had cleared up several of his doubts.
Charlotte Burgess now said, that she had left the former meeting greatly burdened;
and now that Sarah Grubb was absent (prevented by sickness),
she dared not but state to the meeting, that before S. Grubb opened her mouth,
she had herself received the very same words in the secret of her soul,
and she believed it to be the will of the Most High,
that "`The Spirit suffereth it not now.`"

The same parties, generally, who had urged on the proposal at the former sitting,
with some others, gave at this time their approval of the certificate;
but the opposition to the concern is said to have been unabated to the last.^
footnote:[_Ibid,_ p. 75.]
It has been said that as many as twenty members of that
meeting manifested their objection to the proposal;
and it is undeniable that a number more were exceedingly tried and afflicted with it,
but were afraid to speak their sentiments.
Lydia A. Barclay, for one, felt condemned on this account for a long time,
as she acknowledged very feelingly in a letter to the author several years afterwards,
adding, however, that she believed she had experienced forgiveness.
At length the clerk informed the meeting,
that he had never felt equal conflict about any subject that had come before that meeting;
but he thought, on the whole,
it was the mind of the greater part of those who had spoken,
that J. J. Gurney should be liberated; and he should therefore sign the certificate.
Jonathan Backhouse expressed a hope that Friends would be careful, in writing to America,
not to mention what had passed in that meeting.

I have been informed (though my own memory does not serve me in regard to it)
that the certificate did not mention that the meeting united with the concern;
but that, after much unity had been expressed, it was concluded to liberate, etc.,
or words equivalent.
I have believed it right to enter into the above particulars of this important event,
in order to show that there really was so large, so weighty,
and so persistent an opposition to the concern,
that nothing like unity with it on the part of the meeting, as such, could be assumed;
so much so, that most friends in the ministry, we may suppose,
would have declined to pursue their prospect (one of so great importance)
under such a manifestation of uneasiness with it.
When Joseph John Gurney arrived in America, in the autumn of that year (1837),
he found us, to all appearance, a united body.
But a very different appearance presented itself at his departure,
after a visit of nearly three years.

The same fascination attended his course, and opened his way among Friends here,
that had captivated the minds of so many in England.
Even many who had professed, before his arrival,
to have no confidence at all in his soundness as a Friend, now,
dazzled with his character and outward attractions,
gave themselves up to an implicit adherence to him as a minister,
and to a persistent and earnest advocacy of his claim to fulfill his mission here,
without obstruction on account of anything he might
have written or published before coming.
The plausible but shallow and untenable ground was assumed,
that it would be unwarrantable to "`go behind his certificate,`"
in calling him to account for views expressed or published previously;
that his certificate entirely cleared his way,
unless he should spread unsound views in this country;
that we had nothing to do with his printed books,
or with questions of disciplinary action belonging to London Yearly Meeting;
but that it was our duty to receive him in the character of a minister of the gospel,
according to his certificate.^
footnote:[The same flimsy objection,
to "`going behind his certificate,`" had been strongly urged, years before,
in the case of Elias Hicks.
Yet the case of John Hewlett, of Rhode Island,
mentioned in [.book-title]#Beck and Ball`'s Account of London Friends`' Meetings,# page 81,
as having occurred in the early part of the eighteenth century,
shows that such a practice (where a certificate was wrongfully given,
or did not set forth the case correctly) was then considered right.
It is there mentioned that Friends in Philadelphia
endorsed on the back of J. Hewlett`'s certificate,
when presented to them on his visiting that city,
the fact of his friends at home having erroneously
stated him to be clear of marriage engagements,
and their opinion that he ought to have told them of the circumstance, that he had,
many years before (before he became a Friend), separated from his wife, in England.]
This plea shut the mouths of very many,
who found it more comfortable to hide their own feelings of uneasiness under it,
than to expose themselves to showers of obloquy by attempting to withstand his claims.
And although many stood aloof and avoided committing themselves to his support,
and a few here and there openly showed their want of unity with him,
yet he was at once taken by the hand and helped forward by influential individuals,
as if all had been unquestionably clear.

Thomas Evans, who had been so well qualified for usefulness in the Hicksian troubles,
and who, some time previously to J. J. Gurney`'s arrival,
had seriously expressed to the writer of this,
his apprehension "`that a very small inducement would suffice to lead him to
accept a bishop`'s mitre,`" now proposed to accompany him on his travels,
and was only deterred from pursuing his wish, by the resolute opposition of his father,
Jonathan Evans.
John Meader, of New England, in a season of sickness,
said that he had some writings of J. J. Gurney in his possession,
which he should keep as a testimony against him if he should ever come to this country,
which he expected he would do.
Yet he soon became one of his most earnest advocates.
Stephen Grellet, who had been so favored and qualified an instrument in his earlier life,
but who had some time before this returned from England with a cherished
persuasion (as he assured the writer with great satisfaction and confidence,
as he walked from the ship immediately on his return),
that J. J. Gurney was now on the right side, having repudiated the Beacon party,
henceforth became his most influential advocate within Philadelphia Yearly Meeting.
Many besides,
of whom better things might have been expected from their former professions and standing,
soon gave away their strength, and succumbed to his extraordinary influence.

If the Society had been in a healthy condition,
measures would undoubtedly have been at once taken, to advise him to return home,
unless he could have satisfied Friends here that
he was really in unity with our ancient principles.
But great weakness now manifested itself among the
members of the Select Quarterly Meeting in Philadelphia,
who had been so valiant against the opposite errors of Elias Hicks;
and who ought now once more to have stood in the gap, without fear, favor, or affection,
acting on the principle,
that the maintenance of the pure truth in the church was paramount to any personal consideration,
either for themselves or any other man.
Instead of this,
Jonathan Evans and Caleb Peirce stood almost alone among the male Elders,
in desiring that prompt and efficient measures might be taken for that purpose.
His travels in the United States and the West Indies were extensive and protracted,
he not returning home until the seventh month of 1840.
It is by no means needful here to go into a detail
of his journeyings during those three years,
and the various engagements which characterized his visit;
nor yet of the different occasions in which he showed
plainly that he was not one with true Friends,
nor his mind baptized into a true sense of the awful weight of the work
of gospel ministry in which he professed to be engaged.

He appeared to be aware of the slippery nature of the ground
on which he stood in the Society in this land,
and that many eyes were upon him;
and was accordingly very cautious as to the enunciation of his novel views.
These would however at times escape him, notwithstanding all his care.
I may mention one instance coming very unexpectedly under my own notice,
which indeed had a particular effect in directing my attention
to the fact (not clearly known to me previously),
that some at least of his sentiments were at variance
with the doctrines of our ancient Friends.
In a long discourse one evening to a crowded meeting in the Arch Street house in Philadelphia,
in the spring of 1838, he distinctly declared,
that "`we are not to look to anything that we can experience within ourselves,
for salvation, but we must look to Jesus,`" etc.,
following this with considerable dilating on what our blessed Saviour
had done outwardly for us in that prepared body on the cross,
but leaving his inward work almost if not entirely out of view.
The writer was greatly startled, pondered over his words again,
to see whether he had mistaken him, or whether the context, before or after,
altered the one-sided tendency of the statement; but found, to his alarm,
that if J. J. Gurney were right in this,
then were all our early writers grievously wrong!
The conviction of his unsoundness was soon afterwards abundantly confirmed.

His ministry, generally, during his stay here, appeared to be superficial, flowery,
and ostentatious,
with here and there an affectation of something like the doctrine of Friends;
and this apparently graduated according to the supposed degree
of acceptableness of a sprinkling of such doctrine to the audience.
His sermons, for instance, in Philadelphia, and in some parts of New England, etc.,
were much less tinctured with modernizations than in many other places.
At times they were calculated to attract the admiration,
or affect the emotional feelings,
of minds particularly susceptible to natural impressions; though by no means eloquent;
but they were always and entirely (I believe) lacking the unction of the Holy Spirit,
or the baptizing authority and efficacy of the genuine flow
of the gospel stream through rightly qualified instruments.
I think it may be said,
that to the anointed ear (which can "`try words as the mouth tasteth meat`"),
his declarations in the line of either preaching or supplication, were formal, dry,
and lifeless, though by many who heard them they were thought to be beautiful.

It seemed as if, with but little exception,
the delegated watchmen had either been won over to connive at the approaching danger,
and even to help it forward, or had become benumbed at their posts,
and like the dumb watch-dogs of old, "`could not bark,`" even to sound an alarm.
Yet there were exceptions, chiefly among those somewhat young in life,
or not in very prominent positions.
Of these,
there were a few in different parts of Philadelphia and New York Yearly Meetings,
who could not hold their peace,
being deeply affected with a sense of what was impending upon the Society.
In New England also, a considerable number saw the danger,
and prepared to oppose its progress;
among the foremost of whom were John Wilbur and Thomas B. Gould, of Rhode Island,
Seth Davis, Prince Gardner, and quite a company of Friends on the island of Nantucket.

J+++.+++ J. Gurney attended the Yearly Meeting of New England,
held at Newport in the summer of 1838.
A report had been put in circulation,
that he had made satisfaction to his friends in England
in regard to the exceptionable sentiments in his books.
John Wilbur however knew that this was not the case;
and soon took an opportunity with him;
in which he plainly informed him of the apprehensions
of many Friends in regard to such published sentiments,
so extensively spread abroad in the Society,
"`and suggested the desirableness of his satisfying Friends in relation
to such of his doctrines as were not in conformity with our acknowledged
principles;`" so as to open his way among friends in this land.
"`But instead of giving any encouragement of doing so,
he entered into a prompt defence and justification of all his writings,
without exception.`"^
footnote:[[.book-title]#Journal and Correspondence of John Wilbur,# p. 276.]
In consequence of this result of the interview,
J+++.+++ Wilbur believed it to be his religious duty, as way opened for it,
to caution his fellow members against the unsound doctrines to be found in those publications.

Thomas B. Gould, then quite young, but zealous for the truth, felt it his duty also,
at that time,
openly to testify against the unsoundness of J. J. Gurney`'s published works,
and to warn Friends of what he clearly saw to be departures
from the ancient groundwork of the Society`'s faith.
This drew upon him abundance of obloquy and persecution.
About the time of the Yearly Meeting,
J+++.+++ J. Gurney came to his father`'s house in Newport;
and Thomas took the opportunity thus afforded,
to declare to him his dissatisfaction with his writings.
The following is the substance of what passed between them,
after T. B. Gould had opened the subject, ^
footnote:[[.book-title]#Life and Letters of T. B. Gould,# p. 91, etc.]

[.discourse-part]
_J+++.+++ J. Gurney:_ Oh, my dear friend, I did not come here on that account at all;
I only came to manifest my love for thee and the family.

[.offset]
Referring to his writings,

T+++.+++ B. Gould said, "`There are many sentiments in them,
contrary to our acknowledged principles and testimonies.
I am exceedingly dissatisfied with them.
Wilt thou acknowledge that there is unsoundness in them,
and by so doing remove the obstructions to thy service, that exist in my mind?`"

[.discourse-part]
_J+++.+++ J. Gurney:_ All that I have to say to thee, my dear friend, is,
that I have nothing to say on the subject of my writings.
I do not consider it to be my present business; I am here on another concern,
and my mind is very much exercised with it.

[.discourse-part]
_T+++.+++ B. Gould:_
The minds of Friends in this country are very uneasy in
relation to much which thou hast written--as well as myself--and
it is a very serious obstruction to thy work and service.
If thou wilt acknowledge that there is unsoundness in them, and so remove the offence,
I believe there are those who would receive thee with open arms.

[.discourse-part]
_J+++.+++ J. Gurney:_ My dear, I feel a great deal of love for thee,
and I did when thou spoke in meeting the other day.
I admire thy candor and uprightness;
but I must decline entering upon the subject of my writings; they are very extensive;
and all I have to say to thee is, that it is none of my business, and,
to tell thee the truth, I do not consider it to be thine.

[.discourse-part]
_T+++.+++ B. Gould:_ If thou bring thy gift to the altar, etc.
+++[+++quoting the text]. Thou ought to conform to this precept,
and deny such parts of thy writings as have given
uneasiness to me and a multitude of other Friends.
I do consider it thy duty to satisfy both me and them.

[.small-break]
'''

J+++.+++ J. Gurney again made large professions of love for him, put one arm around him,
and laid the other hand on his knee, in a fondling manner, and said, "`All I can say is,
to recommend thee to the Master,
to whom thou must leave me;`" and commenced some remarks by way of preaching to him.

[.discourse-part]
_T+++.+++ B. Gould:_ It has been required of me to do what I have done.
My mind has been very deeply exercised on the subject of
the unsound doctrines promulgated by thy books amongst us.
It has deprived me of much sleep, and even affected my health.

[.small-break]
'''

He then appealed tenderly to him to take away the ground of offence,
and thus open the way, which was now entirely closed.
But J. J. G. utterly refused, again and again, to enter into any discussion,
as he chose to call it, upon the soundness of his writings,
or to acknowledge unsoundness in them.

T+++.+++ B. Gould replied to this: "`I wish no discussion; I have asked for no such thing,
but only for thee to condemn such parts of them as
are contrary to our acknowledged principles,
and have given Friends so much uneasiness.`"

J+++.+++ J. Gurney now manifested considerable disturbance of mind,
and again refused to make any concession.

T+++.+++ B. Gould, after a short pause: "`I must say to thee,
that I am not satisfied with thy manner of preaching.
Thou puttest the cart before the horse;
thou laborest to induce a belief in the doctrines testified of in the Scriptures,
by the mere force of reason and argument, and the bare reading or hearing of them;
and then speakest of the gift of the Spirit as a consequence of that belief or acceptance.
This is contrary to that Scripture doctrine, '`For what man knoweth the things of a man,
save the spirit of man which is in him?
Even so, the things of God knoweth no man, but the Spirit of God.`' Now,
it was because of the absolute necessity for men and women to come to this Spirit,
to have their understandings opened, and their hearts quickened by its power,
that our ancient Friends labored to exalt the testimony to the true Teacher,
and to bring them under his power and teaching;
and they well knew that when people come to this ground and foundation,
there is no danger of their undervaluing the Scriptures, for it is impossible;
the manifestation of the Spirit now,
will not contradict the revelation of the same Spirit in days that are past.
They knew it; and I know it; but thou,
instead of laboring to bring the minds of the people to the true Teacher,
who promised to teach His people Himself those great doctrines and fundamental truths
of the gospel,--bringing in the Scriptures as a collateral evidence and testimony to
the truth of them,--thou goest about to persuade people to accept them in '`simple faith,`'
or to convince them merely by thy own powers of reasoning and argument;
and holdest forth that the gift of the Spirit is
consequent upon that kind of belief or acceptance.
Now this is contrary to the principles of truth as professed by Friends.`"

J+++.+++ J. G. appears to have been here brought to a stand, by this plain and earnest appeal;
and could not deny it; but merely replied:
"`I am satisfied of thy sincerity and faithfulness,
and am willing to be further instructed, as a Christian should be.`"

Would that this moment of openness,
when the spirit of this man of learning was somewhat brought
down and reached by the power of Truth in a stripling,
might have been extended; and that there had been then present, Priscillas or Aquilas,
faithful and deeply experienced fathers and elders of the church,
qualified to have improved the opportunity, and "`further instructed`" him,
while he could have received their admonitions,
as to the byways in which his feet were entangled, and in which he was entangling others!
But he had his own adherents with him,
and at this juncture others of the same tendencies came into the room.
J+++.+++ J. Gurney put on his hat,
and seemed unwilling for any continuance of the conversation on these subjects;
and thus T. B. Gould was prevented from fully relieving
his mind of the concern on his account.

I have dwelt the more largely on what passed at this interview,
inasmuch as it unfolds the manner in which J. J. Gurney
baffled any attempt to bring his doctrines into question,
and displays the persistence with which he declined to give any satisfaction
to those who felt deeply concerned in regard to his erroneous published sentiments;
who certainly had a right to apply to him for satisfaction,
or for a correction of what they deemed a departure from our characteristic principles,
on the part of one assuming the position of a "`messenger of the churches,`"
if not of an "`apostle of Christ,`" and undeniably occupying a place of
great influence for good or evil among our people.
Since the spring of 1838,
the mind of the writer had been much and unexpectedly exercised with grief and concern,
on finding, as before related,
that the views held forth by J. J. Gurney in his
ministry were not such as he could unite with,
or reconcile with the doctrines of our ancient Friends.
The minds of many members of Philadelphia Yearly Meeting, and of some others,
had likewise become greatly disturbed;
much excitement was already the result of his presence among us;
many were exceedingly uneasy with him; and others equally glad of his company,
and offering him much adulation; without clearly knowing, on the one part,
the particular features of his disagreement with the settled principles of the Society,
nor, on the other, what those settled principles really were.

The writer`'s attention was now turned to the very serious nature of the question,
and the necessity of knowing more distinctly, not only the ground,
but also the distinct points of difference, and whether his writings (which, of course,
were the public communication of his real sentiments--public property--and
of great public influence) were in reality so greatly at variance,
as was alleged,
with the doctrines of our early and hitherto uniformly acknowledged authors.
Under this view, a close examination of his various books was undertaken,
with an earnest desire to be rightly assisted and directed,
in so important an investigation,
by the needful supply of that wisdom which is profitable to direct and qualify for judgment.
The result of several months`' attention to the subject was a clear and entire conviction,
not only that on several fundamental points of doctrine his views (as
expressed) were irreconcilable with the principles of the gospel,
held by Friends;
but that his starting point (so to speak) was one
which Friends had always earnestly testified against,
as an inadequate basis for the knowledge of divine truth,
being evidently a mere intellectual deduction, from study and human reasoning.

The matter appearing to be thus clear and undeniable,
and yet not generally very clearly understood;
and knowing that J. J. Gurney was well aware of the
uneasiness of many Friends both in England and America,
and also of the ground of it, especially as regarded his published writings;
the author believed it to be his place (with the advice and concurrence
of a minister and an elder with whom he was intimate),^
footnote:[Viz.: Alexander Dirkin and Samuel Hilles, of Wilmington, Delaware,
both of whom, at that time, earnestly participated in the concern.]
to prepare, in manuscript, a series of extracts from those publications,
on certain points of doctrine,
contrasting them with extracts from standard works
of the early Friends on the same subjects.
This Contrast was divided into twelve main subjects, viz.:
1+++.+++ The True Source of all Divine Knowledge; 2. Faith; 3. The Universal and Saving Light;
4+++.+++ The Gospel; 5. The Scriptures and the Holy Spirit; 6. Justification;
7+++.+++ Imputative Righteousness; 8. The Sabbath; 9. Prayer; 10. Worship;
11+++.+++ The Resurrection of these Bodies; 12. The Atonement;
on all which topics there appeared, more or less distinctly visible,
a divergence from the well-known and recognized views of the Society from the beginning.

This Contrast, becoming somewhat spoken of, was circulated, in manuscript,
among various Friends in and about the city of Philadelphia; many of whom approved of it,
while others were much disturbed, and greatly censured, the writer, ^
footnote:[This manuscript was made a plea for two
attempts to procure the disownment of its author.
One of these was promptly met by the late Henry Cope, who said, at once, "`Tell him that,
if they disown thee, they may disown me also;
for I will go hand-in-hand with thee in the matter.`"
The other was set aside by Thomas Stewardson, an elder of Arch Street Meeting,
on the ground of its hasty irregularity.
It was also made a plea for turning aside the intention of Daniel Wheeler,
in compliance with an invitation given him at the
suggestion of the above-named Thomas Stewardson,
to make his home at the house of the author during his stay in Philadelphia--a change,
whereby he became encompassed by the supporters of J. J. Gurney.
Yet he afterwards assured the writer, that, in his opinion,
the issuing of that manuscript was entirely justifiable,
and could not be called in question with safety to
the Society.] It appeared eventually in print,
without the writer`'s knowledge, having been incorporated, with a few additions,
as an Appendix, in John Wilbur`'s "`Narrative and Exposition.`"
On the 1st of the first month, 1839, Daniel Wheeler,
having spent about four years in visiting the islands of the Pacific,
and various parts of the Southern Ocean, arrived at New York,
on a visit to Friends in North America.^
footnote:[[.book-title]#Memoirs of D. Wheeler,# London, 1842, p. 691.]
Although he had, during his absence in the South Seas,
had a sense that this journey would be required of him when the other was accomplished,
and of course at that time knew nothing of the intended visit of J. J. Gurney to America,
I have believed that a main purpose of the Great Shepherd of the sheep,
in sending him to us at that juncture,
may have been to counteract in some degree the injurious effects
likely to ensue from the visit of J. J. Gurney.

How far, however, this purpose was fulfilled,
or how far it may have been frustrated by the circumstances by
which D. Wheeler was surrounded immediately on his arrival,
and by which he was entangled, is matter of serious question.
Whilst here, his ministry was sound in doctrine,
and often accompanied by an evidence of the true unction of the gospel.
But he was caught hold of, and claimed, from his first arrival,
by those who were active in support of J. J. Gurney,
and who seemed determined to encompass him themselves,
and to interpose every possible obstacle to other association.
This I know was at times oppressively felt by him,
but by submitting to their constant pressure upon him, I have had sorrowfully to believe,
that his service here, which might have been eminently beneficial,
became more or less marred,
and the full efficacy of his testimony for the ancient truth in some degree diminished.
To my certain knowledge, he had no unity with the novel views and practices,
and his mind was burdened with the "`leading strings`" of
the party by which he was temporarily trammelled.

But he had uncommonly warm personal attachments,
and was slow to believe unfavorably in regard to any,
particularly when plausible appearances of outward consistency were assumed;
and he had not the resolution to make an open breach through the entanglements.
He saw and understood the obstructions in the way of J. J. Gurney`'s being admitted,
among Friends of sound views, as one in unity with the Society; and advised him candidly,
while they were together in Philadelphia, that if he were so situated,
he would seek the advice of the Elders collectively.^
footnote:[This he told me himself, only a few minutes afterwards.]
But this advice J. J. Gurney was not prepared to submit to.
Daniel Wheeler had evinced his sympathy with John Wilbur, of Rhode Island, in 1835,
in a long and confidential letter from the island of Tahiti;
in which letter he referred to some of the trials which had attended himself,
near the time of his departure from England in the _Henry Freeling,_
from the censure of some "`in our Society,`" who were rejecting an acquaintance
for themselves with "`the Master`'s voice`" inwardly revealed,
and who, as he said,
were "`such as highly disapproved of John Wilbur`'s letters published by G. Crosfield.`"^
footnote:[[.book-title]#Journal and Correspondence of John Wilbur,# p. 204. See p. 240, of this volume.]

And in 1839, just a month after his arrival in America,
he wrote to John Wilbur affectionately from Philadelphia,
speaking of the trials of the present day, "`when those things which make truly desolate,
and destitute of the Divine presence, stand where they ought not,
in the place which should be holy,
instead of pure vital religion;`" and lamenting the condition of "`many at this day,`"
who were contenting themselves with "`a mere outward declaration of the glad tidings--without
coming to the heartfelt knowledge of this very gospel within themselves`"--"`finding
it more palatable to the creature to be fed with pleasant food from the tree of knowledge,
than to have the attention turned to that holy principle
of gospel light which shines in every heart.`"^
footnote:[[.book-title]#J. Wilbur`'s Journal,# etc., p. 244.]

Daniel Wheeler was taken sick during his return voyage from England,
in the spring of 1840, whither he had gone from America, the previous autumn,
to attend upon his dying son Charles.
He was confined in New York by illness about six weeks,
and died there on the 13th of the sixth month, in the 69th year of his age.
Joseph John Gurney attended the Yearly Meeting of New York in the fifth month, 1840;
at which time Jacob Green, a minister from Ireland, was also present.
The latter was exceedingly tried on account of the state of things in this land,
brought about by J. J. Gurney`'s visit,
and felt constrained to seek an interview with him on the subject before leaving America.
At this interview,
which occurred at the house of the late W. Birdsail in the city of New York,
in the presence of two other English Friends,
Jacob Green opened his uneasiness to J. J. Gurney;
and is said to have spoken so plainly to him,
that the latter at length intimated to him his desire,
that he would mind his own business.
This circumstance was related to the author by a Friend who was staying, at the time,
at the same house.
Jacob Green returned to Ireland almost directly, saying to some Friends,
that he was fleeing for his life.
J+++.+++ J. Gurney left America on his return home, in the seventh month.

By the time that J. J. Gurney had finished his travels in the United States,
it had become evident that a great breach had been made in the harmony of the body;
that the Society was divided into two opposing classes;
one earnestly advocating his claims to acceptance as a minister in unity,
and disposed to adopt his sentiments and to fraternize with his adherents in England;
the other equally earnest in denouncing his opinions
and the general character of his ministerial course,
as tending to produce a fundamental departure from the ancient track;
and indignant at the course of London Yearly Meeting,
in giving its sanction to these novelties, and throwing such a firebrand amongst us,
as his presence on this side of the Atlantic had proved to be.
It may be said,
that it was the London Yearly Meeting of Ministers
and Elders that was directly accountable for this,
rather than the Yearly Meeting at large;
inasmuch as it was that Select body which issued
J+++.+++ J. Gurney`'s certificate for service in this land,
notwithstanding the weighty objections made at the time,
mainly based on the erroneous nature of his published sentiments.

But London Yearly Meeting itself had, in 1836,
opened the way for his passing with facility;
and made a beginning in the line of discarding the ancient principles of the Society;
when it adopted in its General Epistle his favorite dogma,
that the Bible is "`the only authorized record`" of divine truth or duty,
"`the appointed means of a knowledge of the blessed truths of Christianity.`"
Moreover, in 1847, it officially identified itself with his erroneous system,
by adopting and issuing the Memorial concerning him,
which declared that from his twenty-fourth year,^
footnote:[His "`first book "`was published, according to his own statement,
when he was thirty years of age,
so that the above declaration must include all his books.
See his [.book-title]#Memoirs,# vol.
i p. 101.]
he "`maintained, with holy boldness, the principles and testimonies of the Society,
through the remainder of his life and that in all his undertakings
"`he was actuated by a sincere desire to maintain,
with unflinching integrity, the truth as it is in Jesus.`"
These words had indeed the appearance of being introduced
for the very purpose of giving to his writings,
to which they have especial reference, the official sanction of the body.

The Yearly Meetings of Indiana and Carolina appeared to be wholly
under the influence of the spirit of adulation of the man,
and admiration of his ministry and ways;
and many bitter reflections were cast upon those friends of Philadelphia and elsewhere,
who could not join in with the popular current.
Baltimore Yearly Meeting had a few,
and New York and New England each a rather larger number of friends,
who stood opposed to the new views and the claims of their author.
But in Ohio, Pennsylvania, and New Jersey,
there was a very considerable proportion of the members, at that time,
who were by no means prepared to follow the dangerous and delusive track;
many of them being clearly convinced that, if followed generally,
it would lead away the Society from its original foundation.
In the country districts of Philadelphia Yearly Meeting, particularly,
there were still preserved many friends of solid religious experience,
as well as some in the city, who were firm and decided in opposing the coming danger.
Among these were then to be found most of the ministers and elders of that Yearly Meeting,
and likewise of the members of the Meeting for Sufferings;
although some lamentable instances to the contrary were already apparent.

In the succeeding volume, it is the intention of the author,
if spared and enabled for the work, to show how the party of innovation,
among those who had escaped the devastations of the Hicksian defection,
recklessly inaugurated and carried on the work of an opposite schism,
in practice as well as in doctrine,
by the persecutions and disorderly excommunications pursued by them in New England;
and how this course (by which they tore the Society to pieces there) unavoidably
spread schism and separation in other parts;--to develop afterwards the
sad effects of the rise and progress of a Laodicean spirit of compromise,
conniving at that which was opposing the truth and revolutionizing the Society;
a spirit which, conservative in its professions,
and declaiming indiscriminately against all separations as wrong under any circumstances,
was in reality disposed for "`peace at any price,`" and thus produced
weakness and dimness of vision among its own advocates,
and discouragement and scattering among many of those who
were at first more or less valiant for the ancient faith,
and had begun to stand against the innovations;--and finally,
with a brief review of the lapsed condition of those who
have adhered either to the Hicksian system on the one hand,
or to the more modern or Gurney system on the other,
to endeavor to indicate to the reader the grounds for the conviction,
that although honest-hearted individuals may be found on one side or the other,
through weakness or ignorance of the true state of the case,
clinging to each of the two great schismatic bodies whose origin has been here portrayed;
yet that in so far as any may sanction, by cooperation or connivance,
the standing of either of those bodies, or recognize them as bodies of Friends,
they are sanctioning and promoting that which is not of the Truth,
but a system more or less directly, but really and vitally,
opposed to the religion of our forefathers; that thus, in short,
they are united in profession, not with true Friends,
or "`the people called Quakers,`" but with a schismatic body.

[.the-end]
End of First Volume
