== Prefatory Note to the Second Volume

In the first volume of this history,
we have reviewed the rise and progress of the Hicksian schism in America,
with its precursors in Ireland and in New England,
and afterwards the occurrence of the Beacon Schism in England,
as the premature outbreak of the more insidious and far more extensive
defection from the original principles of the Society,
introduced mainly by the writings and teachings of Joseph John Gurney and his associates.
This latter schism is therein narrated as far as the year 1840.
The present volume will be mainly occupied with a development of the sad
consequences of the spread of this doctrinal revolution in the Society--of
the disastrous effects of a treacherous spirit of connivance and compromise,
which arose among those who for a time opposed its progress--and of the preservation,
nevertheless,
of a remnant concerned to stand through all for the
ancient faith of the people called Quakers.

In commencing this second volume,
the author particularly desires his readers to keep in memory
the remarks made on page 8 of the preface in the first volume,
respecting unavoidable and unfavorable personal allusions in the
narration of the sad events which enter into its pages.
These have been exclusively in relation to actions or expressed sentiments
of a public bearing in connection with the fundamental and vital changes
attempted to be introduced into our most holy faith;
and no motives unfriendly to individuals have, consciously at least,
incited such allusions.
Should any feel themselves aggrieved by what they may deem incorrect statements,
the author would request them, candidly and in a Christian spirit,
to bring any supposed wrong specifically to his own attention, rather than,
as has sometimes been the case, by secret insinuations,
which may only accidentally or never come to his knowledge,
to endeavor to detract from the reliable truthfulness of the work.
These may rely upon his openness to receive suggestions
conscientiously made of any real error,
and to give them due weight,
with an earnest desire to do that justice to others which he would have done to himself.

Again, in introducing this work to the attention of his fellow-professors,
there is one thing against which the author deems it his duty earnestly to protest.
That is, the mistaken policy of many otherwise well-concerned parents,
by which great numbers of sensible young persons have been kept in entire ignorance
of the real nature of the troubles in the Society of which they are members.
There is no soundness in the argument that it is not safe to trust the youth with a
knowledge of subjects brought by false brethren into controversy in the church,
and producing disunity and weakness.
On the contrary,
an acquaintance with the afflicted state of the Society has often cherished serious
thoughtfulness and real heartfelt interest in the minds of young persons;
while the ignorance of it promoted by this false idea of danger on the part of parents,
has tended to precipitate hundreds of hopeful youth into the snares of the enemy.
Such young people have a right to know,
and surely it is the duty of honest-hearted parents
to place them in the way of knowing for themselves,
not only the true principles of the Society, but the manner in which, in our own day,
those principles have been and are assailed,
and the devices by which the adversary of truth has succeeded
in supplanting them to a wide extent by a false faith.
