== Chapter VIII.

[.chapter-synopsis]
* The Antislavery Secession in Indiana Yearly Meeting.

The order of events requires us now to go a little
out of the beaten track of doctrinal schism,
to notice briefly a secession of a local and practical character,
which meantime very unexpectedly made its appearance
within the limits of Indiana Yearly Meeting,
developing itself by separation early in the year 1843.
It was indeed a strange and almost incredible thing, that within the Society of Friends,
a body so long characterized by an uncompromising testimony against slavery,
an actual secession should take place on the ground
of zeal against that great national crime.

Yet so it was; and the circumstances were such as might well suggest the query, whether,
while one party was alleged to have been actuated by excess
of zeal for that particular duty of opposing slavery,
so as to place it in an undue prominence compared with other Christian duties,
to the disparagement of the great obligation resting upon all the members of the Society,
to maintain, as far as could be done without unfaithfulness to divine requirement,
the oneness of the body, "`the unity of the Spirit in the bond of peace;`" whether,
on the other hand, their opponents, who controlled the proceedings of the Yearly Meeting,
were adequately alive to the faithful maintenance of that great testimony of the Society;
whether they were sufficiently on the watch to be preserved from undue
influences by which the efficacy of the testimony might be frittered away;
and whether,
in their opposition to what they considered the undue zeal of their antislavery brethren,
they did not allow themselves (having the power of the organization in their
hands) an unwarrantable liberty of encroaching upon the conscientious convictions,
and violating the disciplinary rights of many of their fellow-members,
in attempting to restrain their action,
and to put down all efforts against slavery which seemed
to be in advance of their own uncertain and faltering steps.

But first, let us bear in mind, that the testimony of Friends against slavery had,
in the healthy days of the Society, always been held on religious grounds,
equally with their testimonies against other prominent evils;
and no disposition had been cherished by them to excite
popular feelings either on this subject or any other,
further than the Truth led them to discountenance and denounce every kind of wickedness.
They knew that the heart of man must be regenerated,
or he could not be reliably redeemed from moral depravity;
and therefore their chief concern was to promote that thorough regeneration of soul
which would lead out of all moral evil and establish in all truth and righteousness.
They were sensible that lopping the branches would not kill the root of corruption,
but that if the root could be effectually struck, the branches could not live.
So that while they were careful to strike, as occasion required, at the evil branches,
yet their main aim was unremittingly against the root.

The Society in America had carefully avoided commingling
their zeal in behalf of their testimony against slavery,
with the highly wrought passions of political parties, and had, on that account,
and aware also of the manner in which things are often managed in popular assemblages,
generally refrained from taking part in public meetings
or political demonstrations on the subject;
which were felt to be of an entangling nature,
and calculated to leaven those thus engaged into worldly and hasty modes of action,
to weaken the hold of pure religious feeling, and to draw away the soul,
imperceptibly perhaps, from that humble waiting, at every step,
for divine direction and help, under which the faithful have always found safety.
At the same time it was always understood that an individual liberty
existed for the watchful performance of our social duties,
under conscientious conviction, and in accordance with our principles and profession.

In entertaining the question, whether, of latter time,
the testimony against slavery had really been faithfully maintained,
or whether this salutary caution just spoken of had not been carried too far,
and even right exertions against this great iniquity
thereby more or less crippled or discouraged;
we must bear in mind the general condition of the Society
as described in the first chapter of this work (Vol.
I),
and give due weight to the fact that the Yearly Meeting of Indiana
partook of at least an equal share with other portions of the body,
in the general languor and lack of primitive zeal
and faithfulness to the testimonies of truth.
A living concern and zeal for the ancient faith must have been giving way either
to the inroads of formality or to outward views of supposed duty and policy,
and inordinate dependence on the dicta and authority of leading men,
or they could not have so suddenly changed about, as they did about this time,
and given the undivided countenance of the Yearly Meeting to the innovations of Gurneyism.
It is needful also to bear in mind the undeniable fact,
that many influential members of the Society, both there and elsewhere,
had allowed their sentiments in regard to slavery to be more or less modified
by popular outcries against immediate abolition and its advocates,
by the supposed interests of trade and commerce,
by the influence of the Colonization Society as a palliative and protracting agency,
and by the plausible but fallacious plea that we must be careful
to "`keep our way open to the ear of the rulers of the land,`"
and even of the slaveholders who controlled those rulers,
by an appearance of moderation,
and of standing aloof from the so much dreaded "`abolitionists.`"^
footnote:[It has even been said that one of the American Yearly Meetings (that
of North Carolina) issued a document condemning the act of giving shelter,
in any way, to a fellow creature escaping from slavery!
See [.book-title]#Edgerton`'s History,# p. 306.]

In the secession which is about to be brought into view,
Daniel Puckett and Charles Osborn were conspicuous,
from their position as aged and well-esteemed ministers,
who had travelled much in the service of truth.
The latter had, in 1832 and 1833, travelled extensively in Great Britain, France,
and Germany, and, while in England, had clearly seen the approach of the Beacon schism,
and faithfully testified, on various occasions,
against the departures from our true principles which
were then making their appearance in that country.^
footnote:[See the [.book-title]#Journal of Charles Osborn,# Cincinnati, 1854, pp.
292, 293, 340, 343 and 345.]

In the year 1840,
he travelled in the ministry through some parts of New England and New York,
and after attending the Yearly Meeting in the city of New York,
he made the following statement in his Journal:

[quote]
____

After the meeting closed, I felt a portion of suffering still on my mind.
The state of Society here is such as cannot fail to cause mourning
to those who do prefer Jerusalem above their chief joy.
After meeting I went with Thomas and Elizabeth Robson, to Mott`'s, to tea,
where I had an interview with J. J. G., in the presence of T. and E. R.;
in which I was favored to relieve my mind,
in the discharge of a Christian duty toward him,
in relation to his departure from the Christian doctrine of our Society on Justification,
and that on the Sabbath.
He appeared to be in a disposition to contend that what
he had written and published to the world on those points,
was in accordance with the doctrines of our Society; which, I think,
can but be cause of astonishment to all those who read his books on those points.
It was truly so to me; for the departure is so evident,
that it needs only to be seen by the understanding reader,
to know that what he has published on these subjects is a departure from our doctrines,
which we have held ever since we have been a people,
and a return into those things out of which we were gathered.^
footnote:[_Ibid,_ p. 411.]
____

During his visit to Great Britain,
various inquiries were made of him respecting the American Colonization Society,
which gave him opportunities of explaining to Friends his conviction,
that this Association, founded as it was mainly by slaveholders and their sympathizers,
was by no means to be relied upon as a means for
the extinguishment of slavery in the United States,
as its aim seemed to be practically the expatriation of the free
colored people from what had become the land of their birth,
and where they had "`as good a right to live, as he had himself.`"^
footnote:[[.book-title]#Journal of Charles Osborn,# p. 276.]
After his return home, and especially after his journey in New England and New York,
he and many other Friends within the Yearly Meeting of Indiana believed
it right for them to take a decided stand against the idea,
which seemed to be increasing in prevalency, even within the Society of Friends,
that a gradual or procrastinating policy in regard to the
emancipation of the slaves was all that was really practicable;
and, therefore, all that was to be decidedly advocated--that immediate emancipation,
without previous preparation of the slaves for the change,
would be highly dangerous--an idea which seemed to be in some measure
contemporaneous with the rise and progress of the Colonization Society,
or was at least promoted and spread by the delusive
claim of that Association to popular support,
on the ground of its looking towards abolition by preparing an
asylum for the colored people in the land of their forefathers.

The more these Friends contemplated the whole bearing of the subject,
and the prevailing tone of feeling, as they believed,
in the Society and in the community at large at that time,
the more fully they were convinced that many were
lapsing into the popular opinions and fallacies,
and relaxing their hold on the great testimony of Friends against this national crime,
and that it was their duty firmly to withstand whatever
was calculated to fritter that testimony away.
They therefore boldly declared themselves for immediate emancipation,
as for immediate departure from any other crying wickedness;
for an avoiding to deal in or use the known products of slave toil,
as they would avoid using or dealing in goods dishonestly obtained,
and refrain from that which kept slavery alive;
and for a clear and fearless exposure of the false claims of the Colonization
Society to be relied upon as the means of eradicating slavery.

Since about the year 1835,
various portions of the community in the Eastern and Northern States had been
more or less agitated by the exertions of the newly forming antislavery societies;
and this agitation appears to have had some influence among many Friends in Indiana,
inciting them to take a more open and public stand
on the subject than they had hitherto done.^
footnote:[In 1836, Indiana Yearly Meeting issued an epistle to its members,
warning them against aiding the Colonization Society and its schemes of expatriation,
and expressing their "`affectionate desire`" that they might
all be so alive to the testimony against slavery,
"`that none may, through prejudice or otherwise,
cast any discouragements in the way of such as are
faithfully laboring to promote universal emancipation,
whether such laborers be found within or without the pale of our Society.`"
And in 1837, it renewed its advice,
exhorting to an individual examination and endeavor
to be found doing all that was required of them,
in "`publicly or privately pleading the cause of the oppressed.`"]
Among these, Charles Osborn,
who had previously disapproved of our members joining
with others not governed by the same principles,
in public agitation of the subject, now, about the latter part of 1839,
changed his opinion in that respect,
and began to earnestly advocate their aiding the
antislavery associations in their respective neighborhoods.
It is possible that some of the members, about this time and shortly afterwards,
were in danger of being carried too fast and too far in commingling with public orators,
and perhaps even with political agitators, on this important but exciting subject.
This may have been the case to some extent.
There is, however, no evidence that Charles Osborn was one of these,
or indeed (so far as is known to the writer) that the discipline of the Society
was really transgressed by those who were associated with him in feeling.

They certainly were thoroughly awake to the enormities of the system of slavery,
and boldly avowed a conviction of duty, practically to oppose it in all its features,
to the best of their ability, as citizens concerned for the safety of their country.
And so far as appears, there was nothing in the constitution of the Society of Friends,
by which they could rightly be brought under the censure of the church,
for following out their conscientious convictions of individual duty as they did.
There had always been a liberty allowed for each member to walk
in accordance with his conscientious convictions or scruples,
so long as these did not contravene the well-known
and established testimonies of the Society;
a liberty, it is true, subject to brotherly admonition and advice,
for the safety of individuals and the honor of Truth,
but not to coercion and authoritative limitation.
If, however,
evidence should appear of transgressions of the discipline or testimonies of the Society,
then the church would rightly intervene with its authority,
and gospel order must be maintained.

During Charles Osborn`'s visit to the Eastern States,
he had met with considerable opposition to his firm testimony for unconditional emancipation.
Before his return (in the sixth month, 1840),
the Meeting for Sufferings of Indiana issued a document advising
the members against joining in the antislavery enterprise,
which their Yearly Meeting had aforetime approved,
and likewise against acting with the Colonization Society,
which they had already condemned.
This document, being sent to the Quarterly Meetings,
elicited much disapprobation from the antislavery portion of the members,
as interfering with the testimony against slavery;
and one Quarterly Meeting is said to have actually returned it to the Meeting for Sufferings.
Here was an evidence of the strength of feeling on the subject,
which might well have warned the leaders of the Yearly Meeting
not to proceed to uncalled for extremities of opposition.

It is evident that the minds of many on both sides
of these questions had become greatly excited.
In a professed narrative of this secession,
published anonymously in the Philadelphia Friend, vol.
17, pages 85 and 93 (which account,
when confronted with the various documents issued by both parties,
seems to be extremely one-sided and unfair),
it is stated that "`at a meeting of the African Committee of Indiana Yearly Meeting,
held in the tenth month, 1840, it was supposed that nearly one thousand persons attended;
a very small part of whom belonged to it.`"
No reason is there given for this, and it is left as a stigma upon their zeal.
It is, however,
most probable that the large number then in attendance was to be accounted for
by the fact of their being then assembled at Richmond to attend the Yearly Meeting,
and that Friends interested had been encouraged to sit with the committee.
Their presence does not appear to have been then objected to,
and it is stated that they silently witnessed the transactions of the committee.
At all events,
the excitement was doubtless partly due to the great opposition
made under certain influences to what they considered a rightful
liberty of action according to their conscientious convictions.
There was indeed great danger of natural feelings
on both sides becoming unduly wrought up,
to the loss of the spiritual life on the one side,
and to the setting aside of divine wisdom and heavenly charity on the other.

The above-mentioned account in The Friend, speaking of the African Committee,
goes on to say: "`At the sitting above alluded to,
subjects entirely foreign to its duties,
and with which the Yearly Meeting had not entrusted it,
were brought forward for discussion--articles produced under slave
labor were denounced as '`prize goods,`' and those who used them
charged with being the abettors of slavery and the slave trade.
The committee was at length compelled to exclude
those matters which were foreign to their appointment;
and while they spoke respectfully and tenderly of the conscientious
scruples which any might feel on this subject,
and admitted their right to conform to them,
they could not admit the propriety of representing those who felt no such scruple,
as violators of the discipline and testimonies of the Society.`"

The friends of the antislavery cause gave a somewhat different account of the circumstances.^
footnote:[See Walter Edgerton`'s [.book-title]#History of the
Separation in Indiana Yearly Meeting of Friends,
on the Antislavery Question.#
Cincinnati, 1856, p. 43.]
Speaking of the formation of free-labor associations,
they say that this committee had the subject before them in 1840,
and recommended friends of the different branches of the committee to endeavor
to ascertain what facilities existed for obtaining free-labor goods,
and report to the next general meeting of the committee.
This, to some extent, was attended to in one of the Quarterly Meetings,
and a communication was produced to the committee the next year (1841),
from Abraham L. But the change in the ruling influence, already alluded to, was such,
that even the reading of this document, produced according to instruction,
was obtained with difficulty,
and the whole movement on the subject endeavored to be quashed.
A document was produced to this meeting of the committee, from one of its branches,
showing, in a forcible manner,
the necessity of Friends avoiding the purchase and
consumption of articles produced by slaves.
Its being introduced, and read in that body,
produced a most astonishing state of excitement therein.

The Yearly Meeting in 1841 adopted and issued another minute of advice,
prepared by the Meeting for Sufferings,
discouraging the joining of mixed associations and the opening
of meetinghouses for antislavery meetings or lectures,
as being "`of hurtful tendency to the members.`"^
footnote:[When this minute was under consideration in the Meeting for Sufferings,
Charles Osborn opposed it; and being apprehensive that the Society would, by such action,
seem to be identified with the opponents of the antislavery cause,
he requested that the meeting would issue to the public a declaration
what plan of emancipation they did approve of;
seeing there was so much diversity, some advocating colonization,
some gradual emancipation, and others immediate and unconditional freedom.
But the meeting refused to say anything on the subject.
See [.book-title]#Edgerton`'s History,# p. 234.]
This action of the Yearly Meeting,
and the great preponderance of feeling which now appeared in that body
to discountenance active participation in the antislavery cause,
much disappointed its advocates.
They had fondly hoped,
from the large numbers of Friends who had recently attended a convention on the subject,
held at the time of Spiceland Quarterly Meeting,
and the interest manifested by many in the concern, that they might obtain,
during the time of the Yearly Meeting,
a powerful demonstration in favor of free-labor produce,
by holding a second such convention then at Richmond.
But this was frowned down entirely.
Some who had been very zealous for it,
now when they saw the amount of influence arrayed against the cause,
turned immediately round, and joined its opponents.
Many others staggered, faltered, and finally stumbled over on to the same ground,
or at best into a state of acquiescence.`"^
footnote:[Walter Edgerton`'s [.book-title]#History of the Separation,# p. 48.]

The Yearly Meeting also, in this document,
though without mentioning the name of the writer, censured the circulation,
by its members, of an address, by Joseph Sturge, of England,
to Friends in the United States,
inciting them to greater consistency and earnestness
in maintaining the testimony against slavery.
This address had greatly encouraged the antislavery advocates,
and they were accordingly much displeased at the disapprobation
of it thus published by the Yearly Meeting.
It was a perfectly temperate and somewhat affectionately couched address,
and there does not appear to be anything in it, of itself,
inconsistent with our religious principles or testimonies;
so that it seems to have been a very uncalled for and unwise
act in the controlling parties of the Yearly Meeting,
thus publicly to have denounced it,
though some of it was doubtless construed by them as calling them to account for their
very questionable attitude in regard to the righteous testimony against slavery.
Some associations had been formed among the members exclusively,
with a view to avoid going contrary to the advice against mixing with others; but,
to their astonishment, this was also now objected to by leading members,
who took the ground that "`meetings for discipline were the places
to labor in this cause;`" which might have had some force,
if those meetings for discipline had retained sufficient life and faith to enable
them to move forward according to the pointings of best wisdom in this concern.

Some of the more ardent advocates of the cause soon prepared to act on their own responsibility,
where they had control of meetinghouses,
in disregard of the advice of the Yearly Meeting, considering, as they said,
that such advice was "`contrary to the usage of the Society,`"
and would be "`of hurtful tendency to the members.`"
They were told, however, by some,
that unconditional submission was absolutely necessary
to the existence of religious society;
by others, that "`even if the meeting was wrong in its advice, we must submit,
and throw the responsibility on the body;`" by another class, that the advice was right,
and that submission to the Spirit of Truth would lead to submission to it;
and again by others, with considerable pertinacity,
that they "`had no right to move in advance of the
body--that even admitting them to be in the right,
individuals ought not to move in the matter till the Yearly Meeting was prepared for
it--that abstinence from slave-toil products should not even be named as necessary,
because the Yearly Meeting had not yet taken it up.`"

By the time that the Yearly Meeting assembled in the tenth month, 1842,
the state of feeling on both sides seemed to be arriving at its culminating point.
Soon after the meeting opened,
it became apparent that an understanding had been come to among some,
that the antislavery members should be, as much as practicable,
shut out from serving on appointments during the sittings.
A proposal was made, and sanctioned by those who had the control,
that names offered on committees should receive the approval
of several Friends before being taken by the clerk.^
footnote:[[.book-title]#W. Edgerton`'s History of the Separation,# p. 58.]
But now came the most aggravating of all the acts of the ruling party in the Yearly
Meeting--an act altogether irregular and unsanctioned by discipline or usage--and which
unhappily drove the antislavery portion of the members to the extreme measure of a separation.
The Meeting for Sufferings reported eight of its members by name,
as disqualified to fill the stations they occupied in that body,
without assigning any cause of disqualification;
but it was well understood to be on account of their disapproval
of the advices against antislavery meetings.

The Yearly Meeting approved the dismissal of these
eight members from the Meeting for Sufferings,
and directed the appointment of others;
though their Discipline recognized no such course, unless for death or removal,
or delinquency in attendance of the meetings.
It refused also the earnest and reasonable request of Charles Osborn,
one of the members thus dismissed from service,
that the cause of a course so extraordinary and injurious should be added to the record.^
footnote:[C. Osborn declares in his journal (p. 448),
that he had never been informed that he was about to be dismissed,
nor been requested to ask to be released, until the deed was done.]
His remarks were as follows: "`I have but one request to make of the meeting.
I am here reported, and several of my brethren with me,
as disqualified members of the Meeting for Sufferings.
My request is, that the cause of disqualification may be put upon minute,
that wherever it may come, there the cause may also appear.
It is our due; justice demands it; the cause of truth and righteousness demands it;
and the cause of suffering, bleeding humanity demands it.
I have no wish to cast reflections on anybody, but in my opinion,
the proceedings are unjust, oppressive, cruel, and unauthorized by the Discipline.`"^
footnote:[[.book-title]#Edgerton`'s History,# p. 235.]

If any of his friends feared that C. Osborn was in danger of losing ground through
allowing his mind to be unduly engrossed with the contemplation of one particular
form of human wrongs and the means of remedy (which is a possible supposition),
this was not the way to rescue him from that danger.
In the absence of any overt act of disunity or disorder, it was a cruel injustice.
What would have been thought,
if the Yearly Meeting of Philadelphia had undertaken publicly
to censure and put out of all qualification for service,
merely on this account, such men as Abraham L. Pennock or Enoch Lewis,
whose testimony against slavery and slave products was equally marked and decided?
The Yearly Meeting likewise issued an Epistle of Advice
to Subordinate Meetings and Friends Individually,
warning them against the zeal of the antislavery societies,
and the "`pernicious effects`" of those "`books and papers,
which have the tendency to set one part of Society against another.`"
This epistle contained the following remarkable advice:

[.embedded-content-document.epistle]
--

Friends are advised to be weighty and deliberate in making appointments
to any of the important stations and committees in Society,
so that faithful and trusty Friends may be chosen;
as we believe that those who have distinguished themselves by opposition
or disregard to the advices and travail of the body,
are manifestly unsuitable for important services in it,
while they remain in that situation.

--

A committee of twenty-two men and women was appointed to see that
the above advice was attended to in the subordinate meetings;
that is,
to enforce the setting aside of all such of their
fellow-members who believed it incumbent upon them,
for a faithful and efficient maintenance of one of the Society`'s well-established testimonies,
openly to join with the rest of their fellow-citizens
in protesting against the sin of slavery,
and that course of conduct which kept it alive.
During the course of this Yearly Meeting, Henry Clay, of Kentucky,
who was then a candidate for nomination by one of the national
parties for the office of President of the United States,
was staying a few days at Richmond; and,
doubtless with a view to gain favor among so numerous a body of voters,
announced his intention of attending the Friends`' meeting for worship on First-day.
No objection could, of course, be properly made to such attendance.
But the antislavery party,
who knew that his example as a slaveholder and a duelist
was by no means one for Friends consistently to sanction,
were additionally grieved by observing the great attentions,
nay the unbecoming adulation paid by a large number of the
members to such a man on that conspicuous occasion,
under all the circumstances.

A petition had been presented to him the previous day,
signed by nearly two thousand individuals, requesting him to grant liberty to his slaves.
In his reply he had said, "`I own about fifty slaves.
I consider them as my property.
We have an idea that whatever the law secures as property, is property.`"
He owned that slavery was an evil,
but said that "`the slaves must be prepared for freedom
before they can receive that great boon;
they must have moral cultivation:`" adding,
in confirmation of this procrastinating policy,
"`The Society of Friends take the right stand in relation to this subject!`"^
footnote:[[.book-title]#Edgerton`'s History of the Separation,# p. 85.]
After this, on First-day,
he was conveyed to the meeting by the clerk of the Yearly Meeting in his carriage,
and placed in one of the most conspicuous places in the house,
and at the close of the meeting was as conspicuously
saluted by great numbers of the members.^
footnote:[_Ibid.,_ p. 300.]
All this was particularly aggravating to the antislavery party,
who considered it as an additional evidence that the faithful
testimony against this enormous evil had fallen in the streets;
for the poor man in vile raiment, who should have come into their assembly, they thought,
would not have been thus caressed; and they remembered with wounded feelings,
how an antislavery advocate from the East,
"`a man of irreproachable character,`" which could not be said of Henry Clay,
had recently been treated with utter contempt,
and their meetinghouse doors closed against him.

They "`gathered round him in an almost impenetrable crowd,`" and "`one or more
women mounted over the backs of the benches,`" in order to get to him.
The Free Labor Advocate, a paper published by some of the antislavery members,
thus described the issue:^
footnote:[[.book-title]#Edgerton`'s History,# p. 61.]

[.embedded-content-document.paper]
--

Antislavery Friends being thus proscribed,
and feeling themselves virtually cut off from all the benefits of religious society,
found themselves in a very tried and painful situation.
Thus circumstanced,
it was perfectly natural and entirely reasonable that they should desire to confer together
for the purpose of arriving at some conclusion as to the proper course for them to pursue.
With this view, a Friend arose during the last sitting of the Yearly Meeting,
and proposed that those Friends who were favorable to the antislavery cause,
and who felt aggrieved with the proceedings of the Yearly Meeting,
should remain in the house at the rise of the meeting,
for the purpose of having such a conference.
A considerable expression of unity with the proposition was made,
and not one dissenting voice was heard.

After the conclusion of the meeting, a large company assembled inside the house,
many others having stepped out and not yet returned.
Before any opportunity was had for conference, walked into the minister`'s gallery, and,
in the name of the Trustees, demanded of those present,
an immediate evacuation of the house.
He first called them Friends; then, as if correcting himself,
he said he did not know whether they were Friends or not--he would call them people.
A Friend immediately proposed,
that as they were arbitrarily forbidden the use of
the house for the purpose of conferring together,
those favorable to such a conference, meet at Newport (ten miles north),
at 9 o`'clock next morning.
The proposition was united with, and the people retired.
Next morning, notwithstanding many had from necessity started for home,
a large assembly convened at Newport, and continued in conference till 11 o`'clock,
when it adjourned till 2 o`'clock p.m., to give place to the regular weekday meeting.
From 2 o`'clock the conference continued till near sunset.
Entire harmony prevailed, etc.
If some of our opposers had been there, and heard what we heard, and felt what we felt,
they would surely have been ashamed of the charge so often made against us,
of working in our own strength.
At the above conference, it was the conclusion of those present,
to wait until it was known whether the committees from the Yearly Meeting, etc.,
would really carry out the prescriptive measures as enjoined upon them,
in removing from their stations the antislavery part of Society,
before any further action should be taken.

--

Thus far they had a right to go, as members of the Society of Friends,
and of Indiana Yearly Meeting;
and the refusal of the use of the house to them for such a purpose seems unjustifiable.
In regard to their further stoppings,
we must bear in mind that though they were deeply aggrieved,
arbitrarily thrust aside by their brethren under the plea of having disqualified themselves,
and assailed by attempts to deprive them of their liberty of conscientious action in
a matter involving the welfare of millions of their fellow-countrymen and women;
yet none of them had as yet been actually disowned from membership,
nor had they made use of the right of appeal,
the ordinary course guaranteed by the Discipline in cases of apprehended grievance.^
footnote:[It is worthy of note that in all the documents of the
Yearly Meeting and its advocates in controversy with the Antislavery
Friends (so far as has come under notice of the author),
there is no charge made against any of the latter, of having,
in their efforts in that cause, transgressed the order of the discipline;
though here and there something like an insinuation to that effect is hinted;
which seems to show that if they could have brought
such a charge they would not have failed to do so.
The accusation against them was their opposition to the advice of the Yearly Meeting.
The Yearly Meeting, if led and qualified for it by divine wisdom (and not otherwise),
had a right to issue such advice;
but it had no power to enforce obedience to it until such
advice was regularly established as a rule of discipline.]
The Yearly Meeting had not yet taken the course which it did take a very few years afterwards,
in giving its undivided sanction, as a body,
to the secession produced by the Gurneyites in New England,
and consequently its adherence to that schism which resulted over the whole Society.
The antislavery party made no charge that the Yearly
Meeting had departed in doctrine or in general practice,
but only in regard to this one testimony, which, important as it was,
was in its nature only temporary,
depending on the uncertain existence of that great evil against which it contended,
as subsequent events have shown.
This, therefore,
does not appear to have been adequate ground on which to found
a religious society or church of Christ distinct from others,
for on the success of their cause their distinct
ground of union would of course no longer exist,
and they would find themselves without a distinguishing standard.

The Yearly Meeting was wrong in its measures,
and at that time seemed inexorably fixed in its determination to restrain them from
following the course which they believed they were required by duty to pursue.
Yet they knew not but that a little longer patience and willingness to
suffer obloquy and persecution in the performance of clearly defined duty
(and none other than this could be required of them) might gradually have
brought about a different state of feeling among their fellow-members,
and induced the Yearly Meeting to restore that liberty,
of which the late restrictive measures had unjustly deprived them.
We may at least suppose that their confidence in the goodness
of their cause might have induced a trust,
that with continued faithfulness, with a single eye to divine direction and help,
the truth would eventually prevail.
After waiting till the close of the year,
and finding that the prescriptive measures still went on,
with a manifestation on the part of the Yearly Meeting`'s committee
"`to carry out their instructions to the very letter,`"^
footnote:[[.book-title]#Edgerton`'s History,# p. 62.]
those of the party residing at and near Newport, in Wayne County, Indiana,
met in convention on the fourth of first month, 1843,
to "`take into consideration their peculiarly tried situation,`"
with a view to adopt "`such measures as,
in the openings of Truth,
might appear productive of unity and harmony in their proceedings
for the promotion of the antislavery cause,
and the security of the privileges of religious society.`"

This meeting, as the result of its deliberations,
issued a call for a more general convention of the members of Indiana Yearly Meeting,
to be held at Newport, on the 6th of the second month,
with the avowed object of "`deliberating upon the propriety of reorganizing
the Yearly Meeting of Indiana upon the true principles and in accordance
with the discipline and usages of the Society of Friends,
and in unity with the practice of the Yearly Meeting of London and Dublin.`"
In this call,
they complain bitterly of the prescriptive measures put in force against them,
declaring that "`measures have been set on foot, and are being carried out in practice,
to exclude us from participating in the affairs of Society; to remove all clerks,
overseers, members of committees, and ministers and elders from their stations,
and to place us before the public under the character of offenders,
lying under the censure of the church.`"
Charles Osborn, who was then residing at Young`'s Prairie, in Michigan,
now sent for publication in the Free Labor Advocate,
a declaration of his sentiments and position on the subject of slavery,
earnestly deprecating "`this great iniquity,`" as "`utterly irreconcilable
with the gospel,`" and quoting some of the Society`'s standing declarations
on the subject in the Discipline of Indiana Yearly Meeting,
with the view to show "`that he was engaged in carrying
out the very principles the Society adopted in former days.`"

The convention met at the time and place proposed,
a considerable number of Friends being present.
After two days`' deliberation, they made a minute, in which they said:
"`In consequence of the departure of Indiana Yearly Meeting, etc.,
it was the unanimous conclusion that the circumstances under which we are now placed,
render it indispensably necessary to separate ourselves therefrom.
We, therefore, now, the 7th day of second month, 1843,
associate ourselves together as a religious society in the capacity of a Yearly Meeting,
under the title of Indiana Yearly Meeting of Antislavery Friends,`" etc.
Sundry arrangements were then made in the way of organizing the body anew;
epistles were addressed to the various Yearly Meetings of Friends;
a declaration respecting their position was adopted for publication;
and a conclusion come to, to meet again in the ninth month,
and so continue as a Yearly Meeting for the future.

Here was undeniably a launching forth as a new and distinct religious community.
Was not this a great mistake?
In making their claim on London and Dublin Yearly Meetings for recognition,
on the ground of sympathy of feeling and similarity of action in regard to slavery,
they were overstepping the bounds of ordinary probability,
inasmuch as they might have known beforehand,
that Dublin would do nothing new without the example of London,
and that London (whose emissary, J. J. Gurney,
had so recently been received with open arms by the whole Yearly
Meeting of Indiana) was too wise in its own generation to cast
away from its communion the largest Yearly Meeting in the world,
supposed to number at that time about 25,000 members,
for the sake of a small company who had separated from it,
no matter for how grave a cause.
The various Yearly Meetings in the United States were decidedly
in favor of the Yearly Meeting of Indiana,
and disposed to sanction its course, either from ignorance or prejudice,
or various other reasons, from which they were not likely to be turned away,
in favor of a movement the necessity of which appeared to them so questionable.
They were thus left to find their own way as a distinct body.

It will not be needful to follow minutely the proceedings of either party after this,
except so far as to show what became of the antislavery organization.
Their declaration was followed by a reply from the
Meeting for Sufferings of Indiana Yearly Meeting;
and a succession of controversial essays ensued, one after another for many months,
in which it is due to the antislavery party to say
that in argument they had greatly the advantage.
Their opponents said many things well calculated to persuade
strangers that they had taken a right course,
and were still faithfully concerned in regard to slavery,
until their statements were exposed as palpably fallacious and incorrect,
by the lucid replies which were plentifully showered upon them.^
footnote:[As an exemplification of this,
the attention of such readers as may have access to [.book-title]#Edgerton`'s History#
of this separation is particularly commended to _An Expostulation,_ etc.
(page 242, etc.), signed by George Evans,
and "`a reply`" thereto by Walter Edgerton (page 257, etc.),
in which the plausible statements and reasonings of the former are totally demolished,
and proved to be fallacious and untrustworthy.]
As the respective grounds of action have already been described,
it is not needful here to rehearse the contents of these numerous documents,
which may be seen by those interested,
as published in full in the History of these transactions
which we have so often referred to.

But, while the advocates of the Yearly Meeting continued the controversy,
the members and subordinate meetings,
when they found that the secession had resulted in a regularly organized body,
and that many more might on that account be induced to join its ranks,
changed their course in regard to the proscriptive advices of the Yearly Meeting,
and allowed them to remain a dead letter.
This may have been from motives of policy with some,
or a sincere relenting on the part of others;
but the Yearly Meeting never rescinded its irregular action.
The Antislavery Yearly Meeting was now composed of four Quarterly and ten Monthly Meetings,
and probably consisted of about two thousand members.
The anonymous account in the Philadelphia Friend,
before alluded to (which was evidently indited by an opponent),
represents them as being "`nearly seven hundred adults,`" which is perhaps a small estimate.
The reports sent up to their Yearly Meeting, in the year 1847,
stated that there were 755 children of their members of suitable age to go to school.^
footnote:[See the manuscript [.book-title]#Records of the Yearly Meeting of Antislavery Friends,#
page 200.]
How many there were between this and adult age,
and also of infants and children too young for schooling,
does not appear in the accounts, but probably amounted to several hundreds;
so that it may not be unreasonable to suppose that
the whole number was about the above amount.

In the ninth month of 1843, their Yearly Meeting issued a Declaration of Sentiment,
in justification of their views and position; which is, even at this day,
well worthy of attentive perusal,
as a vindication of their course from the insinuation that
they were discarding the primitive doctrine of Friends,
in regard to immediate revelation by the Holy Spirit.^
footnote:[The whole document may be seen in [.book-title]#Edgerton`'s History,# page 186, etc.]
In 1841, their Meeting for Sufferings addressed that of London,
and subsequently their Yearly Meeting issued a document
addressed to the members of London Yearly Meeting individually,
seeing that their communications to the body were not accepted.
While the Yearly Meeting took no notice of their appeals to its sympathy,
grounded on a similarity of action in regard to slavery,
it is not improbable that many of the individual members felt that
something was due to their transatlantic former brethren.
However that may have been, the Yearly Meeting of London, in 1845,
had the subject under consideration, and, as the result of their deliberations,
adopted an address "`to those who have recently withdrawn from
Indiana Yearly Meeting of Friends,`" and appointed a delegation,
consisting of William Forster, Josiah Forster, George Stacey, John Allen,
and Joseph Bewley, to present it in person.

The Antislavery Friends, hearing of this action of London Yearly Meeting,
entertained hopes that now at length English Friends were about to do them justice,
or at least to search out the real merits of the case,
and perhaps act as mediators to produce a different state of things.
How great then was their disappointment,
when they found that this delegation came not as mediators at all,
nor with any purpose of going into an investigation, or seeking to know,
or even opening their ears to hear what they might have to say in their own behalf;
but simply to exhort them to go back to the meetings of "`the body.`"
With what feelings must they have read the culminating exhortation of the whole address,
enforced as it was by no adequate argument or convincing reason:--"`Accept,
we beseech you, our earnest and affectionate entreaty,
that you will relinquish your separate meetings for this
purpose (divine worship),--will wholly discontinue them,
and again assemble for the public worship of Almighty God
with those with whom you have been accustomed thus to meet.`"

Four of the delegation arrived at Richmond, Indiana,
in time to attend the Yearly Meeting in the tenth month; attended that meeting,
and produced to it their minute of appointment.
Making some remarks afterwards on the object of their mission,
they requested the appointment of a committee,
to give them such information as they might need; which was done,
the Yearly Meeting "`taking the precaution to have every name approved,
before it was taken down by the clerk.`"^
footnote:[[.book-title]#Edgerton`'s History,#
page 330.]

The delegation had several interviews with this committee,
and attended the Yearly Meeting throughout,
but do not appear to have indicated to it anything like a doubt of its
entire faithfulness in regard to the testimony against slavery,
or any desire to have the variant parties together, face to face,
as gospel order would have suggested, to find out the truth,
and reconcile the difference.

They asked for no committee from the Antislavery Friends.
They consulted with the adherents of the Yearly Meeting, and with them alone;
and after its close, went to Newport, attended the "`body`" meeting for worship there,
and paid a social visit of perhaps half an hour to Charles Osborn,
who was then staying at the house of Levi Coffin.
They do not appear to have sought out any other of the Antislavery Friends on that occasion--some,
however,
were present at this half hour`'s interview--but returned the same evening to Richmond,
with the intention of leaving for White Lick the next day.
On learning this,
several Friends of the antislavery meeting felt that it would be best
to communicate their views to them before their departure for the West,
and accordingly drew up the following letter,
which was presented to the delegation the next day, signed by fourteen of their number.

[.embedded-content-document.letter]
--

[.salutation]
William Forster, Josiah Forster, George Stacey, and John Allen--Esteemed Friends:

Being solemnly "`impressed with the importance of your mission to this country,
and duly appreciating the arduous nature of the undertaking,
we cannot but express our earnest desire and hope that your labors
maybe blessed to the promotion of the cause of truth and righteousness,
and that when you return to your own land,
you may bear with you the consoling reflection that, through the Divine aid,
you have been instrumental in uniting Friends in this country,
in a hearty and efficient cooperation in their endeavors to undo the heavy burdens,
and to let the oppressed millions in this land of boasted liberty go free.
As you must be sensible that we, as Antislavery Friends,
feel a deep interest in the progress and final result of your labors,
we hope you will duly appreciate our motives, and at least give us credit for candor,
in making to you the following suggestions:

We understand that your object is to endeavor to reunite Friends of Indiana Yearly Meeting,
who have been separated in consequence of different sentiments
as to their proper course on the antislavery question,
and of the measures which resulted from this difference of opinion.
We are now two Yearly Meetings, and we have understood the object of your visit to be,
to act as mediators between us, that we may become united again.
Need we suggest to you the propriety of endeavoring to stand, as much as possible,
uncommitted to either side, and so far as information may be wanted,
to endeavor to procure it in that way which shall
be least likely to lead you to partial conclusions,
or to give either party room to distrust your impartiality?
Now, so far as we have understood your course,
since entering upon the object of your mission, and your plans for the future,
we feel bound to say we cannot view them in a light that is satisfactory.

You have thrown yourselves, as it were, into the bosom of one of the parties,
to the neglect almost entirety of the other; the only exception, that we know of,
being a visit of a few minutes to Charles Osborn.
You attended their Yearly Meeting throughout,
and requested the appointment of a committee of information, with which committee,
we understand, you have consulted as to your future operations;
thus giving strength to the idea that you are altogether on their side.
The result of your councils, so far as we understand your plan of future operations,
appears to us exceptionable in several particulars.
We understand that you expect to call Antislavery
Friends together in their respective neighborhoods,
beginning with some of the remote and small meetings,
and to read to them the address from the London Yearly Meeting.

Our objection to this course will suggest itself to your minds without our naming it.
It may be a master stroke of policy to attack our outposts,
for the purpose of weakening our forces, in an attempt to destroy our organization,
if that is the object aimed at;
but we very much doubt whether it is the course that
can be reconciled with the object of your mission,
as generally understood.
Here, or at least in this vicinity,
is the great body of Antislavery Friends--here our Yearly Meeting
is held--here it was expected you would meet us in council,
and for this purpose our aged Friend Charles Osborn is here,
not doubting that if you had anything for us, here would be the place to receive it.
And here, still seems to us, is at least the place to begin.
We do not presume to dictate,
but we take the liberty to ask you to reconsider your proposed plan.
Whatever course you may see proper to pursue toward Antislavery Friends,
or whatever advice you may have to give them, or propositions to make to them,
we think it reasonable that they should be commenced here,
instead of at our remote and small meetings.
And especially, if you intend to convene Antislavery Friends to hear the address,
we would request you to commence here.

In conclusion, dear Friends, we would suggest to you,
that if you persist in that course which evidently implies a design to weaken us,
by operating upon our remote meetings or outposts,
we shall feel ourselves justifiable in taking such measures as may appear to be advisable,
to guard our Friends against any improper influence.
Now we will just add, that if we are under wrong impressions, we hope to be set right;
for it is painful to us to harbor an unfavorable thought respecting Friends for whom
we have long entertained so high a regard as we have for those whom we are now addressing.
We expected you would take steps to inquire into the particulars of our difficulty,
see where the wrong was, and endeavor to remove it.
But if this is not your intention, then we have been mistaken in the object of your visit.
We have spoken plainly, but not in an unfriendly feeling,
and hope you will attribute it to no other motive than a desire that the right may prosper.

With the salutation of our love, we remain your sincere Friends.

--

It would seem by the above firm but temperate and respectful letter,
that the London Address had hitherto been withheld
from the Antislavery Friends by the delegation.
They informed those who presented the letter to them,
that they had no advice to give them as to how they
should return to those by whom they had been disowned,
but simply "`to return to the meetings for worship,`" which
they well knew would result in their entire disorganization.
George Stacey said that "`he could conceive of no
possible circumstances in which he could be placed,
that would justify him in suffering himself to be alienated from the body of
Society;`" apparently forgetting that he belonged to a community which had never
assumed to itself the attribute of infallibility (any longer than it might be
led and qualified by the infallible Spirit of the Lord Jesus),
and to a branch of it which had of late years manifested sad evidences of going astray.

The delegation were distinctly offered an interview within a few days, at Newport,
with a larger number of the objects of their solicitude
than they would be likely to see at any other place;
but they preferred to visit the remote sections first, and at once proceeded into Iowa.
Arriving at Salem, they invited the Antislavery Friends to meet them in conference;
when the London Address was read to them,
and they were exhorted to discontinue their meetings for worship,
and again attend those of "`the body.`"
The delegation were informed that "`they did not know what they were asking of them,
in requiring their return, without a removal of the causes of the separation.`"
But they manifested no inclination to enter into the causes.
They expressed a desire to visit the families residing there, which was acceded to;
but after the delegation retired,
those who had met them continued in conference on the subject,
and drew up a reply to their advice, showing them in respectful but earnest terms,
that they could not conscientiously abandon the position which they had taken
for the sake of being able to do what they believed to be their duty,
and return to those they had left, except on the distinct understanding of full unity,
and the privilege to continue their usual exertions for the abolition of slavery,
"`as Truth might dictate,`" being accountable to
the Society only for violations of the Discipline.

At the suggestion of the Antislavery Friends,
another conference was had with the delegation a few days afterwards;
but with a similar result, they having previously stated to those who made the request,
that "`they had no liberty to enter into an examination or discussion of the causes
of difference,`" and "`should not feel bound to answer questions that would commit them.`"
Their conduct throughout manifested to those whom they were visiting,
that their main aim and desire was to break up the organization.
They went next to Nettle Creek, where they had a similar conference, read the address,
and exhorted the members to abandon the course they were taking.
"`They were repeatedly asked,`" says an account of this conference,^
footnote:[[.book-title]#W. Edgerton`'s History of the Separation,# p. 345.]
"`if they had investigated the difficulty between us and those we had left;
to which they gave no answer.
But when they were told how one-sided they were,
in giving judgment before hearing both parties,
they said they knew nothing of the cause of separation,
and they had no privilege from their Yearly Meeting
to investigate the difference between us;
and they did not come here to discuss the matter,
but were messengers to expostulate with us.`"

Various other places were visited by the delegation in the same way;
and "`to read the address, and urge submission to its advice,
seemed to be the sole business.`"
At length, in returning after most of their labors were accomplished,
they reached Newport in Indiana early in the year 1846.
At the conclusion of the conference there,
they were asked if they would carry back to their Yearly Meeting
a response to its address which they had brought over.
They replied that "`they could see no propriety in sending
such a communication,`" and declined to take it.
A document of that nature was, however,
prepared by the Meeting for Sufferings of Antislavery Friends,
addressed to London Yearly Meeting, and to the Quarterly and Monthly Meetings,
and the members individually, which was sent independently of the delegation.
This response contained a clear exposure of the fallacies put forth in
the London Address (fallacies in the application of salutary truths),
and among other pertinent observations contained the following remarks:^
footnote:[[.book-title]#W. Edgerton`'s History,# pages 349, 350, and 352.]

[.embedded-content-document]
--

This doctrine of implicit, unconditional,
and unqualified submission to the powers that be, in religious Society,
which is so prevalent among Friends both in this country and in England,
is a most conclusive evidence of a lamentable defection from first principles We regard
the doctrine of individual responsibility and accountability to be one of vital importance,
and that the difference between us and those who contend
for implicit obedience to the mandates of the church,
however contrary they may be to our individual convictions of duty, is essential;
and we can have no fellowship with the sentiment
repeatedly put forth by members of the London deputation,
that no conceivable circumstances can justify a separation from the body.

Unless we shall become convinced that slavery is not that
great evil which we have long believed it to be,
we should consider ourselves traitors to the cause of Truth,
which we believe ourselves called to advocate,
were we to accede to the advice of your Yearly Meeting and its committee.
And should the labors of that committee prove effectual
in the accomplishment of their designs,
we have no doubt but the damage done to the antislavery cause would be incalculable.
But, thanks be to Him who controls the elements,
we believe their course has had a powerful tendency
to strengthen the minds of Antislavery Friends generally,
in the confidence of the rectitude of our position.

And now, in coming to a conclusion, permit us to state that,
with our present convictions of duty,
we cannot look towards a reunion with those whom we have left,
upon any other terms than a total recantation of all their proscriptive measures,
and an unconditional restoration to all the rights
and privileges which we formerly enjoyed in the Society,
with unrestrained liberty to pursue our antislavery
labors according to the dictates of our own consciences;
being responsible to the church only for violations of the Discipline.
We shall rejoice to hail such a proposition, made in good faith,
and upon a thorough conviction of its propriety,
by our Friends of Indiana Yearly Meeting.

--

The delegation returned through Washington and Philadelphia,
attended Philadelphia Yearly Meeting, and then embarked for England.
In their Report to the ensuing Yearly Meeting in London,
they mention having visited all the companies of this description,
thirty-three in number,
except one remotely situated--that their plan had
been to call them together in their neighborhoods,
to read to them the address,
and exhort them affectionately to give up their separate meetings,
giving them such explanation as seemed called for by any remarks that
were made by those who were thus convened--that on all occasions a willingness
to meet them was manifested--and that they had felt much love and sympathy
for them in the circumstances in which they found them.
But their Report is entirely silent as to the great
dissatisfaction with their course of proceeding,
so repeatedly expressed to the delegation by the Antislavery Friends,
nor does it hint at any doubt on their part that Indiana Yearly
Meeting had acted throughout with entire correctness.

If, in their various meetings with the members of that Yearly Meeting,
they had in reality given them any counsel to alter
their course toward their seceded brethren,
or had even allowed themselves to suspect that all had not been done in the best way,
they kept it most profoundly secret,
and allowed all the impression of blame to rest upon those who charged
the Yearly Meeting with having compelled them to the secession.
There is nothing in the published Life of William Forster,
in giving an account of their labors in this concern,
which appears at all to conflict with the recital
I have here given of their mode of procedure.
The editor of that work, in closing his statement of it,
makes the following remark respecting it and its results.
There may be, however, two different sentiments on that subject.
He says,
"`It may be truly said that few offices of love have ever been undertaken
by one portion of a Christian community on behalf of another,
which have been more signally attended with the divine blessing,
or which furnish a more beautiful illustration of
the right mode of bearing one another`'s burdens,
and so fulfilling the law of Christ.`"^
footnote:[[.book-title]#Seebohm`'s Life of W. Forster,# p. 206.]

In reviewing the action of this delegation,
as delineated by the Antislavery Friends who were the objects of it,
it seems strange that men so eminent as leaders of the people in London Yearly Meeting,
men so long and intimately versed in the affairs of the whole Society,
men of so extensive a knowledge of the world,
and men so ardent in advocacy of African liberty,
should have been satisfied to spend their time and energies in this business,
without managing it better.
They appear to have persuaded themselves that the
subjects of their visit were either docile children,
who could be persuaded by affectionate solicitude,
and appeals in behalf of unity at any price, into any course,
or men and women who did not know what they had been about,
and what was the value of the liberty to act according to their
conscience when such action did not contravene the discipline and
testimonies of the Society of which they were or had been members,
and to whose principles they still declared their warm adhesion.

The marvel, however, is less,
when we remember that three of them had been prominent members of the
London Yearly Meeting`'s committee of 1835 on the "`Beacon`" controversy,
and had (no doubt against their better judgment at times)
been induced by those who actually controlled that committee,
to sanction, tacitly at least,
the various temporizing blunders which it committed in the treatment of that schism.^
footnote:[See Volume 1, Chapter 6.]
In neither case did they dare to go down to the actual root of the matter,
being afraid of the consequences which might ensue.
Their labors in Indiana do not appear to have had much convincing efficacy,
nor much immediate or manifest influence in drawing back many to "`the
body;`" though it is probable that from that time a gradual weakening
of the ranks of the Antislavery Friends may have to be dated.
Their organization as a Yearly Meeting continued for fourteen years,
and their manuscript Records and many printed documents, during that time,
give evidence of much industry, and indicate an earnest concern,
not only on the subject of slavery and the help of the people of color,
but for the religious welfare and advancement of their own members.
They appear to have been indefatigable in the defence of their position,
and of the cause which they had so warmly at heart,
issuing many successive documents addressed to Friends or other Christian professors,
to Congress and Legislatures, some of them of marked cogency.

The manuscript records of their Yearly Meeting are voluminous,
embracing the usual business of Yearly Meetings, answers to the queries, etc.,
mainly in accordance with the discipline of Indiana Yearly Meeting,
besides many of the above documents recorded in full,
and eight Memorials of deceased members, including three ministers, viz., Abel Roberts,
Daniel Puckett, and Charles Osborn.
But various circumstances wrought their disintegration and final scattering.
In addition to the feature already alluded to,
that their standard as a separate organization was necessarily a temporary one;
and in addition to the influence, whatever it was, of the London delegation of 1845;
they were constantly assailed by the discouraging consciousness that they
were a small body compared with the old Yearly Meeting of Indiana,
with no prospect of increase of numbers;
for the prescriptive decrees of the Yearly Meeting had been
practically set aside by the subordinate meetings;
and,
while the Yearly Meeting itself complacently assumed the attitude--"`I
have done no evil`"--yet some of its leading characters would often
insinuate that "`if it were to do over again,
the meeting would not act as it did;`" others would say to them,
"`Do come back and help us,
for we need just such as you are to aid us;`" and promises were made by others,
that "`if they would only come back, they might have all the privilege they desired,
to labor in the antislavery cause,`" and that "`the Yearly Meeting
was now as true to that cause as they were themselves.`"

All this, and much more like it, had considerable effect,
especially as some of their older and influential members had been taken away by death,
and many of their younger ones had not been personally
subjected to the restrictive measures,
and therefore did not feel the necessity of standing
against edicts whose practical force had passed away,
while they probably longed to be once more associated with the larger number.
Thus there was for some years a gradual diminution
of numbers and strength as an organized body,
and when once the tide was seen to set that way,
it was natural that it should increase in the power of its depressing flow.
Many left their ranks, and, without making any acknowledgment of error,
slipped back quietly into those of "`the body;`" while some
others lost their way on one dark mountain or another,
and but a few were left at their Yearly Meeting in 1857,
scarcely sufficient to keep up one Monthly or one Quarterly Meeting.
So that finding it then out of their power to continue to hold their Society
together as became their profession and in accordance with the Discipline,
they took such measures as were needful to secure
their corporate property under direction of trustees,
finished up all their business,
commended their remaining members to wait upon the Lord for strength and preservation,
and came to "`a solemn conclusion.`"

The minutes of this their last Yearly Meeting are really touching in their tenor,
as compared with the buoyancy of their earlier records.
Yet nothing appears like an acknowledgment of a doubt of the rectitude of their proceedings.
Before they disbanded, they issued a final document, entitled,
Some Observations and Explanations,
Touching the Situation of Antislavery Friends as an Organization,
and What Wrought its Overthrow.
We may extract the two following paragraphs:

[.embedded-content-document]
--

We declared, when taking our independent position,
that we did not separate from the principles of the Society of Friends,
nor from its testimonies and discipline;
but from that body of members who had departed from our testimony against slavery,
and from a due respect for the discipline;
wishing it distinctly understood that we adopted no new doctrine,
nor any new system of church government; that we claimed to be,
in the strictest sense of the word, a Society of Friends,
with no other nominal distinction in the title we adopted than that which
was necessary to distinguish us from those from whom we separated,
and to express our adherence to our well-known testimony against slavery.^
footnote:[[.book-title]#Manuscript Records of the Yearly Meeting of Antislavery Friends,# p. 369.]

And now, what shall we say?
Our object in reorganizing the Society has, to a considerable degree, been frustrated.
It is true that our sufferings in the cause, and the secession that ensued,
purchased liberty for the antislavery portion of Friends that remained
with "`the body,`" to labor in the cause of the slave,
and stemmed the torrent of opposition to antislavery
action of Friends in other Yearly Meetings,
and in this way much good was effected; yet it was forced; the liberty was extorted,
and not granted from any congeniality of feeling in its favor.^
footnote:[_Ibid,_ p. 371.]

--

Thus was brought to a close a secession,
the inception of which appears not to have had fully
adequate ground for so momentous a step,
but for which the lapsing condition of Indiana Yearly Meeting,
with its arbitrary and unauthorized encroachments
on the rights of conscience and individual liberty,
was mainly accountable.
