== Chapter IX.

The Persecution of John Wilbur and Others,
and the Separation Effected by the Gurney Party in New England.

We must now resume the sad narrative of the troubles which resulted from
the spread of the modernizing principles in the United States--principles
which never could have obtained so sweeping an influence in the Society,
had it not been for the unwatchfulness,
and consequent unfaithfulness of many of the leading men,
who suffered themselves to be dazzled and led astray
by plausible outward appearances and worldly motives.
The wide and rapid flow of sentiment which had been developed, as we have seen,
in favor of Joseph John Gurney,
soon encouraged those leaders in New England who
had generally consorted with him since his arrival,
to endeavor to suppress all attempts to oppose his doctrines,
and especially to stop the influence of one whom they regarded
as the main obstacle to their success herein.

And now came on an astonishing instance of ecclesiastical
oppression by the mere force of arbitrary power,
previously unknown in the annals of the Society,
and worthy only of the dark precincts of papal tyranny.
This was the protracted persecution and irregular disownment of an aged, worthy,
and hitherto highly esteemed minister,
for no other cause than that he had firmly stood his ground,
on the basis of ancient Quakerism,
warning his fellow-members of the subversive tendency of the new doctrines;
this arbitrary procedure involving also the precipitate, groundless,
and unauthorized dissolution of the Monthly Meeting of which he was a member,
and disownment of various other individuals, in order to compass their end;
violating their own discipline in several important particulars,
for the accomplishment of these outrages on the rights
and precious privileges of the members;
and all for the purpose of sustaining the claims
of J. J. Gurney and the prevalency of his views.

From the time of the decease of Moses Brown, of Providence, Rhode Island,
who firmly opposed and checked these tendencies,
certain individuals of considerable influence in New England Yearly Meeting,
chiefly in and about Providence, had been aiming at John Wilbur, of Hopkinton,
on account of his known hostility first to Beaconism,
and afterwards to the same spirit as it had since more insidiously manifested itself;
and in the spring of 1840, while J. J. Gurney was yet on this side of the ocean,
these leaders of the party had the machinery ready for stopping
his open testimony or suppressing him altogether.
They had a standing committee of the Yearly Meeting,
composed principally of these very party leaders and their pliant instruments,
and possessing by their appointment the questionable, vague, and extensive authority,
"`to extend a general care on behalf of the Yearly Meeting for
the maintenance of our Christian principles and testimonies,
the preservation of love and unity,
and to assist and advise such meetings and members as circumstances
may require and way open for,`" throughout the whole Yearly Meeting.
Here one might suppose was authority ample and vague enough to enable
them to take hold of anything whatever that they might desire,
to the utter prostration of all individual rights.

Nevertheless it seems to have been early perceived,
that they had no express authority to interfere with meetings of ministers and elders,
and that this might present a difficulty.
Accordingly,
a committee was appointed likewise in Rhode Island
Quarterly Meeting of Ministers and Elders,
containing several of the same individuals,
ostensibly on the ground that two of the Select Meetings within its limits
had sent up exceptions to the query respecting love and unity.
Neither, however, of these two Select Meetings was the one to which John Wilbur belonged,
which was South Kingston.
But after getting the committee, it was easy to turn it in that direction,
however unwarranted by the ostensible ground of its appointment;
and in their haste to accomplish their purpose,
John Wilbur was cited to appear before it the very next morning.
Thus began a series of arbitrary and despotic transactions,
disgraceful to the character of a Christian society.
It is a long and forlorn story,
and we shall be obliged to confine ourselves to the prominent and essential features.

The object at first seemed to be,
to entrap him unwarily by questions into some admission
which they might use to his disadvantage;
but this being seen and avoided, they then brought against him sundry complaints,
such as that he had made a visit to Philadelphia,
when he must have known that they did not wish him to go thither,
although he had gone with a minute of unity from his Monthly Meeting,
to attend Philadelphia Yearly Meeting;
that he kept company with young men (who did not approve
of the new views and measures) such as T. B. Gould,
George F. Read, etc.; that he had written and spoken against J. J. Gurney,
and spread long lists of Extracts from his doctrines.
He denied having spoken against J. J. Gurney otherwise
than in regard to his unsound doctrines,
and proposed to prove the correctness of this course by reading
to them the Extracts which they charged him with spreading.
But they refused to listen to them, and gave him scarcely any time to vindicate himself,
heaping abundance of censure upon him, demanding immediate concession,
and advising him to "`stay at home and be quiet.`"

Being thus debarred from offering anything by way of showing the
committee that he had done nothing but what it was his right,
and indeed, by the Discipline of that Yearly Meeting, his express duty to do;
he soon after wrote a long letter to the member first named on the committee,
showing the utter inconsistency of their action,
and the groundless and frivolous nature of their charges against him,
and adverting to some of the errors of J. J. Gurney`'s sentiments
against which he had been constrained to bear testimony.
This letter^
footnote:[For the whole letter, see his Journal and Correspondence, p. 279.]
was eagerly seized upon by the committee,
who endeavored to make out from it fresh accusations against him.
They had many interviews with him,
requiring him to attend upon them at various places
and times for a space of about two years;
continually changing and adding to their complaints against him,
but always declining to give him their charges plainly and explicitly in writing,
and utterly refusing to allow him to prove the correctness of his conduct by adducing
evidence of the erroneous nature of J. J. Gurney`'s published doctrines.

This they would by no means listen to,
although on that circumstance depended the question whether
they had any cause or right whatever to call him to account.
After treating with him thus for about twelve months,
the Select Quarterly Meeting`'s committee enlisted
in the service the committee of the Yearly Meeting,
and John Wilbur was called upon to meet nine of the
former committee and six of the latter.
The mode of treatment of the case by both committees was sorrowfully
characterized by abundance of unjust reproaches cast upon him,
and by quibbling, shuffling, and prevarication, and even direct falsehood,
to a disgraceful extent; bearing down upon him also by numbers and assumed authority,
and never allowing him a fair opportunity to show his entire innocency.^
footnote:[Journal and Correspondence of John Wilbur, pp.
277 to 308.]
They alleged that he was guilty of detraction,
but would never listen to his proofs of the truth of what he had testified,
and of its importance to the safety of the Society;
nor yet would they at all consent to give him a written
statement of their objections against his conduct,
though he repeatedly urged it upon them,
in order to have their floating and vacillating accusations
brought to a clear and distinct charge,
which they would not be able afterwards to change,
and which it would be easy for him to meet.

In the spring of 1841 the Select Quarterly Meeting`'s committee professed
to resign their care of the case to the committee of the Yearly Meeting,
of which, however, all but two of them were members;
so that with these two exceptions all the members continued (though nominally
on another committee) to exercise their authority in the case,
and by acting upon it in the last named committee they could
bring the Discipline to bear on it more readily than through
the committee of the Meeting of Ministers and Elders merely.
Accordingly, in the sixth month, 1841,
John Wilbur was called upon to meet about thirty members^
footnote:[The Narrative of Facts and Circumstances,
published by the Gurney Warly Meeting, says twenty-seven.]
of this committee, who resorted, in turn, to persuasion, exhortation, and denunciation,
in order to obtain concessions from him.
Finding, however, that, numerous as they were, they gained nothing,
the next opportunity was concluded to be with five or six of their number,
who importuned him earnestly to make even this small concession, "`If I have done wrong,
I am sorry for it;`" knowing well that if they could bring him to such an avowal,
they could spread the report that he had recanted,
and could still hold him subject to their authority.

But he calmly told them that this was by no means
a proper way for satisfaction to be made.
He afterwards again met the committee at large,
who professed to have other complaints against him, of which they had not yet told him!
He demanded to know the whole distinctly;
to which he was told "`they had many others,`" evidently
in the hope of at length intimidating him;
but they would not specify them, or verify their declaration,
and continued to urge concession,
which he plainly informed them he could not conscientiously make.
There were some men on that committee,
from whom such conduct as what we have now witnessed might not be very surprising,
if needful to accomplish a favorite object;
but there were others who must have unconsciously and unwarily suffered their sense
of justice and right to be grievously blinded by their confidence in the leaders,
and who, having thus given up their independence of judgment,
saw no other way than to follow on in the track marked out for them.

In the spring of 1842,
fifteen members of the committee attended South Kingston Monthly Meeting,
and produced to it a long written complaint against John Wilbur, signed by them all;
thus overstepping the constant usage and good order of the Society,
that eases of offence must first be brought to the
Preparative Meeting (where there is one) by the overseers,
after proper consideration and endeavors for reclaiming and convincing the offender,
before they are introduced to the notice of the Monthly Meeting.
This complaint charged John Wilbur with departing from the order and discipline
of our religious Society in circulating an anonymous pamphlet,
purporting to contain an account of the proceedings
of London Yearly Meeting of Ministers and Elders,
when a Friend was liberated to visit this country,
whose certificate had been received and united with by New England Yearly Meeting;
that he had also circulated divers letters,
intended to show that this Friend was not in unity with his Friends at home,
and designed to close his way here; that he had indulged in a spirit of detraction,
misrepresenting the religious character of divers
Friends in their own and other Yearly Meetings;
that he had made divers assertions tending to induce dissatisfaction among Friends,
and with the proceedings of the Yearly Meeting,
and calculated to produce division therein,
to disturb the unity of different Yearly Meetings,
and alienate the feelings of the members;
that he had written a letter to one of the committee,
in which he made unjust insinuations, and preferred charges against them,
which they deny in point of fact;
and concluded by saying that the Select Quarterly Meeting`'s committee,
having labored with him till the fifth month, 1841,
the Yearly Meeting`'s committee had then, at their request, extended care in the case,
and endeavored to convince him of his errors,
in repeated opportunities for several months, without any change in his mind; and,
therefore,
they now believed it their duty to recommend his case to the immediate
notice and care of South Kingston Monthly Meeting.

The above is briefly the substance of this complaint.
Why it was signed by fifteen, and not by all the members of the committee,
does not appear.
The objection was urged in the meeting,
that it was introduced in a manner inconsistent with the uniform practice of the Society;
but notwithstanding its irregularity,
the committee urged its being attended to at that time,
saying that the authority with which they were clothed by the Yearly
Meeting obviated the necessity of such preliminary proceedings.
The members of the Monthly Meeting,
seeing that this was a case not only very trying to their feelings,
but of great general importance,
and that owing to several concurring circumstances
a smaller number of Friends were present than usual,
proposed a delay of one month.
But the committee insisted on their immediately proceeding
to appoint a committee to attend to the case,
saying that if the meeting desired it,
an addition could be made to that committee at a future time.
They even threatened to complain to the Quarterly Meeting against them,
if the meeting did not comply with their desire.
The clerk at length concluded, in accordance with their advice,
to take the names of a committee, and four Friends were appointed.

At the next Monthly Meeting,
the year of the clerk`'s appointment to service having expired,
a new clerk was appointed; and one of the committee appointed on John Wilbur`'s case,
proposing an addition to that committee, five other Friends were added to it,
as had been suggested by the Yearly Meeting`'s committee the month before.
But at the Monthly Meeting in the sixth month,
several of the Yearly Meeting`'s committee attended,
and objecting to the appointment made the month before, of a new clerk,
proposed that he should resign his post to the former one,
alleging that this would tend to restore unity and harmony in the Monthly Meeting!
This, however, was not acceded to by the meeting.
The former clerk, who was under the influence of the Yearly Meeting`'s committee,
on being applied to for the books and papers of the Monthly Meeting,
declined to deliver them to the new clerk,
and afterwards had them conveyed beyond the limits of the Monthly Meeting;
and the Yearly Meeting`'s committee acknowledged that they had advised him to that course,
from an apprehension that the Monthly Meeting contemplated a separation!
This, of course, was disclaimed on the part of the meeting,
and the committee adduced no evidence to sustain their unwarrantable surmise.

In the seventh month,
the committee in the case of John Wilbur met for the investigation of that case.
Six of the Yearly Meeting`'s committee (also) attended.
Before the examination of the case was commenced,
J+++.+++ Wilbur desired to have one or two of his friends to sit with him and assist him;
and after some discussion,
in which the Yearly Meeting`'s committee made objection to his having this privilege,
the respective parties withdrew,
submitting the matter to the Monthly Meeting`'s committee,
who unanimously decided to allow J. Wilbur the assistance of two of his friends.
Upon their return the Yearly Meeting`'s committee still objected,
and again retired a short time for consultation among themselves.
On again coming in,
they took decided ground that the decision of the
Monthly Meeting`'s committee must be reversed,
or they should not proceed with the opening of the case, but should leave.

The Monthly Meeting`'s committee, on being again appealed to,
declined to take from J. Wilbur the privilege they had granted,
unless he should consent thereto.
John Wilbur subsequently did consent to proceed without the help of his friends, as,
from the determination of the Yearly Meeting`'s committee,
no other way appeared to go forward with the case with said committee present,
which was to him desirable.
During the discussion of this question of allowing him assistance,
which occupied the whole of the first day,
the Yearly Meeting`'s committee claimed that it was their province,
after representing the case on their part,
to join the Monthly Meeting`'s committee in judging the same,
a position which the Monthly Meeting`'s committee were not ready to allow.
The Yearly Meeting`'s committee also, during the same discussion,
denied that they were complainants in this case; and when, the next morning,
they were asked by J. Wilbur whether they still persisted in this denial,
notwithstanding their names were attached to the complaint, they made no reply!^
footnote:[Journal and Correspondence of J. Wilbur, p. 810.]

After the Yearly Meeting`'s committee had gone through
with the evidence in support of their complaint,
J+++.+++ Wilbur, in his own defence,
proposed to adduce certain fundamental doctrines of the Society,
and to show the inconsistency of J. J. Gurney`'s doctrines therewith,
"`because it was on account of his objection to the latter that he was complained of.`"
But this was objected to by the Yearly Meeting`'s committee,
they alleging that the Monthly Meeting`'s committee had no authority
to judge of doctrines--that this belonged to the Yearly Meeting
and the Meeting for Sufferings alone--that if they went into doctrines,
they would assume authority to decide that the great
body of the Yearly Meeting was unsound,
seeing its great unanimity in granting to J. J. Gurney a returning certificate.
J+++.+++ Wilbur adduced the provisions of the Discipline in his justification,
and the Monthly Meeting`'s committee decided to allow him to proceed as proposed,
"`introducing such evidence and documents on these subjects as shall appear essentially
to relate to the same,`" inasmuch as "`the merits of the case essentially depend
on the doctrines called in question by J. Wilbur.`"

They gave also additional reasons for this conclusion,
in that the Discipline enjoins upon "`Quarterly and Monthly Meetings,
and all faithful Friends,`" to be watchful against unsound doctrines among the
members--that Monthly Meetings are often required to judge respecting doctrines,
as in receiving or disowning members,
as well as by the above injunction on Quarterly and Monthly Meetings and all
the faithful members--and that subordinate meetings and members cannot be thus
debarred from the right and duty of judging for themselves in so vital a matter,
and bearing their testimony against manifest unsoundness.
These arguments were unanswerable, but nevertheless the Yearly Meeting`'s committee,
on being informed of this conclusion,
immediately collected together their documents and withdrew;
clearly showing that justice was not what they aimed at,
but the accomplishment of a predetermined purpose.
The matter was thus left in the hands of the Monthly Meeting`'s committee,
who continued their sittings to the conclusion of the investigation.

At the Monthly Meeting in the seventh month,
a number of the Yearly Meeting`'s committee attended,
and again accused the meeting of an intention to make a separation.
The committee in the case of John Wilbur stated that
they were not at present prepared to report,
whereupon one of the Yearly Meeting`'s committee inquired whether
no part of the committee were ready--a question which indicated
more than it expressed--to which one of them replied,
that two of the committee had a report in readiness!
The seven other members of the committee had not been consulted about it,
and knew nothing of such a report.
But the Yearly Meeting`'s committee advocated the reading of it.
To this, however, the meeting,
astonished at the boldness and irregularity of the proceeding, would not consent.
Now at length it came out,
who they were who were aiming to bring about a "`separation;`" for the
same member of the committee who had offered the report of the two,
proposed "`that those who were in unity with the Yearly Meeting and with its committee,
should stop in the house for a short time, at the close of the meeting.`"
The former clerk united with this,^
footnote:[Address of Rhode Island Quarterly Meeting, 1845, page 11.]
and wished the Women`'s Meeting informed of it;
and the Yearly Meeting`'s committee encouraged it.
The meeting generally, however, objected to the proposal,
and showed that it appeared to be a plan for separation.
This insidious project was thus frustrated.

At the Quarterly Meeting of Rhode Island in the eighth month,
the Yearly Meeting`'s committee reported South Kingston
Monthly Meeting to be in a state of disunity,
disorder, and insubordination;
and consequently another committee was then appointed
to unite with them in visiting that Monthly Meeting,
although no report had yet been made in John Wilbur`'s case.
The two committees were in attendance at the ensuing Monthly
Meeting held near the close of the eighth month,
and claimed for the Quarterly Meeting`'s committee not only
the right to act as members of the Monthly Meeting,
but that the meeting was bound to take their advice,
even to the abrogation of its recorded acts for months past;
a proceeding before unheard of in the Society.
The Monthly Meeting expressed its willingness to hear and
consider whatever advice the committee might offer,
and give it all proper weight, but claimed the right to exercise its own judgment;
at the same time acknowledging itself responsible to the Quarterly and Yearly Meetings,
according to the Discipline, for any breach of the order of the Society.

The committee in J. Wilbur`'s case now made a report, signed by seven of the nine,
to the effect that, on a full and deliberate investigation, their judgment was,
that the charges against J. Wilbur had not been sustained,
but that his defence was sufficient to exonerate him from them;
as it appeared from the evidence before them,
that the complaint had originated from his labors, under apprehension of religious duty,
and in conformity with the Discipline, against the introduction of defective principles,
and for the preservation of those ancient testimonies
of Truth committed to us as a people.
They therefore recommended that the complaint against him be dismissed.
Two of the committee presented their counter report.
The report of the seven, however,
notwithstanding the opposition of the Quarterly Meeting`'s committee,
was adopted by the meeting,
with a very large expression of approval on the part of the members.

The Monthly Meeting had appointed a committee to treat with the former clerk,
on account of his disorderly conduct in withholding the
books and papers of the meeting from the new clerk.
At the Monthly Meeting in the tenth month,
four of the Quarterly Meeting`'s committee of fifteen,^
footnote:[J. Wilbur`'s Narrative and Imposition, p. 156.]
presented a document signed by themselves only,
advising the Monthly Meeting to restore the former clerk,
to dismiss the committee in his case, to annul the records in regard to it,
and to set aside and make void the decision in the eighth month in relation to J. Wilbur,
as entered on their minutes.
The four who signed this advice being asked whether the other (eleven) members
of the Quarterly Meeting`'s committee had been consulted in regard to it,
acknowledged that they had not!
The meeting, taking into view the great importance of the matter,
and that such a case was entirely unprecedented in the Society,
and feeling the necessity for deliberation and care,
concluded to postpone the further consideration of the advice till the next month.

But meantime, about ten days after this, the Quarterly Meeting again occurred,
and the committee reported the Monthly Meeting to be still in a state of insubordination,
and not in a suitable condition to transact business in conformity with the Discipline,
nor consistently with our Christian profession; and recommended that it be dissolved,
and its members joined to Greenwich Monthly Meeting.
This elicited much discussion,
and it was clearly shown that such a course would be a direct violation
of the Discipline on the part of the Quarterly Meeting.
But some of the Yearly Meeting`'s committee asserted
that this was a wrong construction of the Discipline.
The members of South Kingston Monthly Meeting requested
to be allowed to be heard before a committee,
or in some way enabled to justify themselves,
before the Quarterly Meeting should proceed to such
an extreme measure as the dissolution of the meeting.
But this was denied.
And on one of the representatives attempting, as a last resort,
to plead their cause before the Quarterly Meeting,
he was told by the clerk (one of the Yearly Meeting`'s committee) to take his seat;
and the latter soon read the minute dissolving South Kingston Monthly Meeting,
attaching its members to Greenwich Monthly Meeting,
devolving on the latter all its unfinished business,
and declaring null and void the proceedings clearing John Wilbur,
and all that had been done respecting the records
kept back from the meeting by the former clerk!

When this decision was communicated to the Monthly
Meeting of South Kingston two or three weeks afterwards,
by some of the Quarterly Meeting`'s committee,
a copy of the minute was requested by the Monthly Meeting; but this was refused,
and the committee retired, accompanied by a few members of the meeting.
The bulk of the members remained together to take measures to appeal
to the Yearly Meeting against this arbitrary and irregular measure;
and then agreed to suspend all further sittings as
a Monthly Meeting until their appeal should be decided.
The Discipline of New England Yearly Meeting provides that in cases where it is considered
necessary by a Quarterly Meeting to advise a Monthly Meeting to any course,
if that Monthly Meeting is dissatisfied with the advice,
it "`may appeal to the Yearly Meeting against the judgment of the Quarterly Meeting.`"
But if it will not appeal,
and yet will not submit to the judgment of the Quarterly Meeting,
the latter shall be at liberty to dissolve the Monthly Meeting,
or bring the subject before the next or succeeding Yearly Meeting.
But when the dissolution is decided on by the Quarterly Meeting,
"`the dissolved Monthly Meeting, or any part thereof in the name of the said meeting,
shall be at liberty to appeal to the next or succeeding Yearly Meeting,
against such dissolution.`"

Yet if it will not appeal,
then the Quarterly Meeting may proceed to join its members to another Monthly Meeting;
"`and until such time,
shall take care that no inconvenience doth thereby
ensue to any of the members of such dissolved meeting,
respecting any branch of our Discipline.`"
From this it is clear that all sudden and arbitrary
action is carefully prohibited to Quarterly Meetings,
and the Monthly Meetings are fully and clearly guaranteed the right of appealing, first,
against the advice or judgment of the Quarterly Meeting, and secondly,
against the dissolution;
and the Quarterly Meeting cannot proceed to consummate their action,
until time has been given to the Monthly Meeting to decide whether to appeal or not.
But here was an instance of the Quarterly Meeting summarily dissolving the Monthly Meeting,
and at the same time annulling its proceedings,
and transferring its members and unfinished business to another,
while they were deliberating concerning taking the
advice--not of the Quarterly Meeting itself,
as provided by the Discipline--but of a small part of its committee!
As to the assumption to annul the proceedings of the Monthly
Meeting in this summary and arbitrary manner,
certainly no such power could be delegated to a Quarterly
Meeting by the Discipline of any Yearly Meeting in the Society.
These transactions can admit of no justification except in Rome itself.

Greenwich Monthly Meeting, to which the members had been thus attached,
now became the instrument for the prompt consummation of this business.
John Wilbur`'s case of course formed a principal feature of the proceedings
against which the Monthly Meeting had concluded to appeal,
and ought therefore to have been considered as essentially
included in and belonging to that appeal;
but this view of it was disregarded in the haste to have him disowned.
At Greenwich Monthly Meeting the Yearly Meeting`'s committee urged,
that as the addition to the committee in J. Wilbur`'s case had
been by the Quarterly Meeting annulled with the other proceedings,
it now became the duty of the original committee of four to make report to that meeting.
This was opposed,
on the ground that the appeal ought to suspend all further proceedings in that case;
but this objection was overruled,
and that committee was directed to report to a future meeting.

At the next Greenwich Monthly Meeting, viz., first month 30th, 1843,
the report of the two members of the committee of South Kingston Monthly Meeting,
dated six months before, viz., seventh month 23rd, 1842, without consultation,
as it appeared, with the others, was presented by them,
declaring that in their judgment all the charges against J. Wilbur had been substantiated,
and that he was not in a situation to be continued in membership.
But here it was discovered that those charges had never been read in that Monthly Meeting!
The meeting waited until the paper of complaint could be sent for,
which on the messenger`'s return was read,
the report of the two was united with by the members of
the Yearly and Quarterly Meetings`' committees present,
and by two others, members of the meeting; and though objected to by several friends,
the clerk, a member of the Yearly Meeting`'s committee, made a minute adopting it;
and in this hasty, arbitrary, and disorderly manner,
unparalleled in the annals of the Society, John Wilbur was disowned!
In violation of an express provision of the Discipline,
guaranteeing to the members on all proper occasions the use of the records of the meetings,
the Quarterly Meeting refused the request made to
it on behalf of South Kingston Monthly Meeting,
for a copy of the minute dissolving it, against which it was preparing to appeal;
and the attempt was made more than once, by raising frivolous obstacles,
to baffle and prevent the appeal from going forward.

It seems needless to swell these recitals of repeated and disgraceful wrongs,
by further details in regard to the proceedings respecting the appeal.
Let it suffice to say that the same party influences impelled
the Yearly Meeting to reject the allegations of the appeal,
when presented, and to confirm the action of Rhode Island Quarterly Meeting;
and in like manner, the next year, 1844,
to reject the individual appeal of John Wilbur against the action of Greenwich
Monthly Meeting and Rhode Island Quarterly Meeting in his own case,
and to confirm their disownment of him contrary to
all rules of discipline and all former usage,
and obviously for the purpose of upholding a new and overwhelming party,
founded upon novel views.
In short,
these transactions respecting the two appeals were characterized
by the same injustice and overbearing oppression by which
the original measures appealed against had been accomplished,
and were managed by the same parties.
When the appointment of a committee in the Yearly Meeting, to hear J. Wilbur`'s appeal,
was completed, he requested to be allowed some one to assist him before the committee,
inasmuch as, from his age (then about 70 years) and infirmity,
it would be a hard task for him to perform the necessary labor in prosecuting his appeal.
Many expressed themselves in favor of granting this reasonable request,
but the meeting decided against it.^
footnote:[Journal and Correspondence of J. W., p. 333.]

I have endeavored to present these grievous events unbroken by other matter,
so that the reader may more clearly see and understand the whole case.
Much has been omitted for the sake of this clear view, and for brevity itself,
but I believe the narrative is not distorted in any way by partiality,
nor anything omitted by which its truthfulness would suffer,
or the true complexion of the transactions be altered.
But for this desire to keep the account unbroken, much might have been added, to show,
on the one hand,
that John Wilbur remained firm and unwavering in his testimony against those erroneous
sentiments which he clearly saw were making so baneful an inroad in the Society;
and on the other hand,
that he was by no means without the sympathy and
encouragement of many experienced and worthy Friends,
both in this land and in England,
who endeavored by affectionate epistles to uphold his hands and
animate his spirit to continued constancy through his deep trials.
Among these were such as Ann Jones, Lydia A. Barclay, George and Margaret Crosfield,
Ezra Comfort, and Ann Coning; whose warm sympathizing letters,
in addition to those from various other friends nearer home,
were particularly cordial to his mind.
In one of Ann Jones`'s letters,
she quoted for his encouragement a characteristic expression of Daniel Wheeler`'s, when,
lying off the Mother Bank in the Henry Freeling,
and "`suffering from the same spirit,`" he briefly said
to a friend in reply to an expression of sympathy,
"`The sun can shine in the Inquisition!`"
And truly during this time of oppression by the spirit of darkness,
there were many occasions when John Wilbur was mercifully given to witness
that the sun of righteousness did renewedly shine forth with healing virtue,
confirming his faith,
and renewing his strength for the war against spiritual wickedness in high places.

In the second month, 1842,
while still under the treatment of the Yearly Meeting`'s committee,
he sent an address to the Meeting for Sufferings,
accompanied by extracts from J. J. Gurney`'s writings, desiring them to examine these,
and decide touching their soundness,
and then lay the result of their labors before the Society; hoping that if rightly done,
it would contribute to the safety of the body and the restoration of harmony.
This address was referred to a committee for three months, and then nothing came of it.
The same tacit suppression was given to a similar application from the ministers, elders,
and overseers of the Island of Nantucket,
signed by fifteen of the members in those stations,
all that were present at the time the document was adopted.
An application of the same kind from South Kingston Monthly Meeting, in 1841,
had already been disposed of with the same negation.^
footnote:[Depositions, etc., in Fall River Suit, Earle v. Wood, p. 156. Boston,
T+++.+++ R. Marvin, 1850.]

A number of Friends known to be opposed to the new views were now brought under censure
by the same party management by which J. Wilbur`'s case had been laid hold of.
It was not to be expected that so open and clear a testimony against J.
J+++.+++ Gurney`'s unsound doctrines as was maintained by Thomas B. Gould,
of Newport, would escape the efforts of the leaders to suppress it.^
footnote:[In 1840,
when the Yearly Meeting of New England granted a return certificate to J. J. Gurney,
T+++.+++ B. Gould was among those who openly opposed the measure.
His testimony given to the Supreme Court in the Fall River Suit (Depositions, etc., pp.
201 to 225) is the most lucid and valuable of any in the volume.]
But for some years,
the overseers of Newport Preparative Meeting being
opposed to the new doctrines and measures,
nothing could be openly done towards the accomplishment of what some of the active
members of the party were known to have expressed as their fixed desire,
his disownment.
From the year 1840, T. B. Gould had spoken a few times in the ministry.
In 1843,
after an irregular attempt to deal with him by the meeting of ministers and elders,
to which he did not at that time belong,
and subsequently by the overseers of another Preparative Meeting,
the party succeeded in appointing two overseers for Newport, of their own sort,
one of them clerk of the Monthly Meeting of Rhode Island
and an influential member of the Yearly Meeting`'s committee,
and the other so completely subjugated to that influence,
that in one of the interviews soon afterwards had with T. B. Gould,
he avowed to the latter,
"`that if some of the leaders (naming two or three)
were to order him to do what he knew to be wrong,
he would do it,
and let them take the responsibility;`" adding that
he thought T. B. Gould ought to do in like manner,
and act according to the desire of those who wished him
to give up his testimony against J. J. Gurney`'s doctrines;^
footnote:[Letters and Memoirs of T. B. Gould, Philadelphia, 1860, p. 187.]
and advising him to "`stick to the body, right or wrong!`"

These overseers, after several interviews,
brought a complaint against him into Rhode Island Monthly Meeting,
without going first through the Preparative Meeting,
according to former usage and the uniform good order of the Society,
and pressed it upon the meeting for prompt action,
T+++.+++ B. Gould having been unexpectedly prevented from being present that day.
The irregularity of its introduction was the occasion of much remark in the meeting,
shared even by some of the Gurney party; but D. B.,
one of the overseers who brought in the complaint, urged its being then attended to,
as such an opportunity might not soon again occur!
This overseer being also the clerk, made it all the more easy,
and a committee was accordingly appointed, of three men and two women,
to treat with him on the complaint.
This committee had repeated interviews with him during a space of nine months.
At the first two of these, they not only produced no copy of the complaint,
but seemed really not to know what the charge was against him.
But as he insisted on his right to be informed of the nature of it,
at the third opportunity they brought what they said was a copy of it,
but would by no means allow him to have it in his own hand.
To his appeal against such behavior,
they replied by disavowing any lack of confidence in his honor or integrity;
but the one who had it said that they had been strictly
enjoined by D. B. the overseer and clerk,
not to let T. B. Gould have it by any means!^
footnote:[Letters and Memoirs of T. B. Gould, p. 184.]

Thomas reminded one of these men of what he had some time previously said to him,
while standing together in the meetinghouse yard,
that the greatest desire he had was to have him disowned,
for his intimacy with J. Wilbur, and his opposition to J. J. Gurney.
But on this being now mentioned to him in presence of the rest, he vehemently denied it,
declaring, "`God Almighty knows that I never said so!`"
Thomas told him that it really was as he had said,
and cautioned him in regard to his awful denial of it;
but he persisted in his appeals to the Almighty, in a manner very painful to listen to.
T+++.+++ B. Gould afterwards understood, from his wife,
that the complaint charged him with manifesting himself
out of unity with Friends in their meetings for discipline,
and with having accused the overseers of being actuated by a spirit of envy and malice.
The latter clause was merely founded on his having objected
to one of their members being brought under dealing,
by alleging that one of the overseers had admitted to him that the other overseer
had been actuated by an envious and malicious spirit against the Friend,
and was resolved to have him disowned.

At one of their last interviews with him,
the committee manifested an arbitrary and bitter spirit,
still declining to furnish him with a copy of the complaint,
but telling him that their business with him was,
"`to get an acknowledgment from him--that was their business;`" that he knew
well enough what his offence was--there was no need of talking about it,
or of his seeing the complaint; that they had forgotten to bring it;
and justifying the charge of disunity,
by referring to certain occasions when he had objected
to proposed action on the part of the Monthly Meeting,
saying, this was the foundation of that part of the charge.
They also accused him of writing letters, and showing other letters,
to produce a schism in the Society.
This he denied,
saying that the great object and end of his labors had been to prevent a schism,
and appealed to the committee to produce or specify such letters as were spoken of.
But this they could not do.
Various other frivolous charges were alleged against him,
and shown by him to be groundless.
Towards the close of the opportunity, after a time of silence of his suggesting,
he was constrained to open his mouth among them, in brokenness and fear,
appealing to the Searcher of hearts, "`who knoweth what is in man,
and needeth not that any man should testify unto him of man;
with the expression of a fervent desire, that He would be pleased to furnish with wisdom,
to guide amidst the storm, and strength to endure and stand firm,
that so His name might not be dishonored.`"
A feeling of solemnity spread over them,
so that one of the women could do no less than respond to what he had expressed.^
footnote:[Letters and Memoirs of T. B. G., p. 226.]

After nine months of this treatment by the committee,
during a part of which T. B. Gould was very ill,
he was one day informed by a person who happened to meet him in the street,
that their last Monthly Meeting had disowned him.
But as the separation to be presently mentioned had then taken place in
several of the Monthly Meetings of Rhode Island Quarterly Meeting,
T+++.+++ B. Gould`'s disownment was only consummated by a separate and schismatic meeting.
His own Monthly Meeting, on the separation taking place,
had dismissed the complaint as groundless and false,
and restored him to his standing as a member in unity.
The first knowledge that he obtained of any written testimony of disownment
having been issued against him by the Gurney Meeting was ten years afterwards,
while attending the stormy Yearly Meeting of Ohio
(at the time of the Gurney separation there),
when one Zadok Street held up a paper, in much excitement,
declaring it was a testimony of disownment of T. B. Gould.

The momentous sequel of these transactions must now be told.
The year 1845 was rendered sorrowfully memorable by the accomplishment,
on the part of the adherents of J. J. Gurney,
of an open schism in the Yearly Meeting of New England,
for the purpose of sustaining the standing of that author,
and consequently also the prevalent influence of his novel doctrines and practices.
In Swanzey Monthly Meeting, a branch of Rhode Island Quarterly Meeting,
great diversity of sentiment had existed for a considerable
time on the subjects now dividing the Society,
insomuch that committees appointed for the selection of fresh overseers and clerks were,
for about two years, unable to agree.
A principal cause of this difficulty arose from the circumstance that
several members of the Committee on Overseers were persistently in favor
of nominating an individual whom others did not consider at all eligible,
on account of an unsettled difference between him and another Friend,
and also that he had aided in the circulation of a pamphlet of J. J. Gurney`'s,
containing unsound sentiments, and would make no concessions.
This individual took offence at being thus objected to,
repeatedly endeavored to get his supposed grievance before the Monthly Meeting, and,
with a few other members,
frustrated all attempts therein to come to an agreement
or united appointment of overseers or clerks.

In the eighth month, 1842, on account, as was alleged,
of deficiencies in the answers to the queries,
the Quarterly Meeting appointed a committee to visit
South Kingston and Swanzey Monthly Meetings.
This committee, along with that of the Yearly Meeting,
took the same overbearing measures,
in attempting to coerce the proceedings of Swanzey Monthly Meeting,
as we have already seen they did with that of South Kingston.
They cited before them the Monthly Meeting`'s Committees on Overseers and Clerks,
in the seventh month, 1844, and desired them to come to an agreement,
and report their proceedings to them.
The Committee on Overseers then agreed on five names,
several giving up their objections for the sake of coming to some definite conclusion;
but a sixth name being urged on behalf of the party,
prevented four of the committee from signing the report,
as they could not conscientiously unite with that name.
On learning this,
the Yearly Meeting`'s committee assumed authority to add the sixth name themselves,
which was that of the individual before spoken of as having formerly been objected to,
and who had also been instrumental in defeating other nominations
on the ground that they were not signed by all the committee.
This name, therefore,
could not go forward with the approbation of the four members above mentioned.
The Committee on Clerks also had not been able to agree.

At the next Monthly Meeting the Yearly Meeting`'s committee was in attendance,
and a report was presented, signed by three, of the Committee of seven on Clerks;
and about the same time a document was handed in from the Yearly Meeting`'s committee,
declaring their judgment of the innocence of the individual before alluded to,
and advising his appointment as overseer, along with the five others.
They also advised that as the Committee on Clerks had not agreed on any names to propose,
the meeting should appoint two,
whom they named (and who were the same as named in the report of the three above mentioned),
as clerk and assistant clerk.
This being urged by them upon the meeting, its right, secured by the Discipline,
to appeal against the advice,
was shown by reading the provisions to that effect in the Book of Discipline;
but notwithstanding much objection made to these arbitrary proceedings,
the Yearly Meeting`'s committee pressed their advice upon the meeting.
At length the clerk made a minute, referring the subject to the next Monthly Meeting;
basing the minute, as he said, when inquired of,
on the expression of the most substantial and exemplary members of the meeting,
on the fact that the nomination for clerks was made
by three only out of a committee of seven members,
and on the usage of the Monthly Meeting, when so greatly divided in sentiment,
to wait for more unity before proceeding.

Two out of a Committee of seven on Overseers,
then nominated six members for that station, all belonging to the Gurney party,
and including the above-mentioned objectionable individual.
Several of the committee said they would have signed the report,
but for the retention on it of this last name;
and offered their reasons for not doing so,
including the fact of his having the well-known unsettled
difference with another member still pending,
and likely before long to claim the notice of the Monthly Meeting.
Yet the Yearly Meeting`'s committee still urged his appointment as one of the overseers.
Much objection being made to this, it was proposed by some, by way of compromise,
that the five others should be appointed, leaving out the sixth for the present;
but this was refused, unless the whole report was adopted.
The clerk afterwards inquired if the Yearly Meeting`'s committee
would consent to the substitution of a certain other member
(also one of their own party) instead of this individual.
But one of the Yearly Meeting`'s committee (John Meader) promptly replied,
"`The committee have all agreed; it`'s fixed; we can make no compromise!`"

The clerk then collected the sense of the meeting,
and made a minute referring the subject for one month for further consideration.
The usual answers to the queries were adopted,
and directed to the ensuing Quarterly Meeting.
Representatives thereto were appointed,
and after a sitting of six hours the meeting concluded as usual.
The ensuing Quarterly Meeting received and recognized the
representatives and answers to the queries thus sent,
with the signature of Thomas Wilbur as clerk.
But at the subsequent Monthly Meeting, in the eighth month,
after the clerk had taken his seat at the table,
but before he had read the opening minute, John Meader,
who was not a member of that Monthly Meeting,
rose and informed the meeting that the Quarterly Meeting had released its former committee,
and had appointed a number of Friends to attend that meeting,
and assist in transacting the business, in appointing its officers,
and in the due organization of the same;
and closed his remarks by proposing that Thomas Wilbur should now leave the table,
and David Shove should take his seat as clerk.

This outrageous proposal was promptly united with by a number of strangers then present,
who, however,
had given no evidence of their right to meddle with the business of the meeting,
and presented no credentials,
though repeatedly urged to show their authority for thus interfering.
The change of clerk was persistently pressed by John Meader,
and also by some of the members of the Monthly Meeting
who belonged to the innovating party,
though objected to by others.
The object of their desiring the proposed change
was clearly seen to be to obtain control of the meeting,
and thus to procure the disownment of those who stood
opposed to the introduction of the spurious doctrines;
and the character of those doctrines was alluded to,
with the design entertained by some to obtain their establishment in the Society.
The important fact was also noticed,
that the first prominent manifestation of disunity in that
Monthly Meeting had been an attempt to have a Friend dealt
with for speaking against the circulation of unsound doctrines.

After some further discussion, at the request of several friends, the clerk,
Thomas Wilbur, proceeded to open the Monthly Meeting;
whereupon John Meader repeated his desire for D. Shove to go to the table.
This person accordingly approached it, aided by two of the strangers,
one of whom took him by the arm and led him forward;
but finding no room made for him there, he paused a moment,
and at J. Meader`'s suggestion took another seat, where he soon began to write.
Meantime the regular clerk had read the opening minute,
and the meeting was proceeding with its usual business.
But in the midst of this, the usurping clerk began to read from several papers,
greatly to the disturbance of the meeting.
After this, John Meader,
who seemed to take the lead throughout in these disorderly proceedings,
proposed to adjourn;
which was united with by some of the strangers and by two or three members of the meeting.
Soon afterwards,
while the regular clerk was reading something of the business of the meeting,
John Meader again urged an adjournment, with an appearance of impatience;
whereupon several others rising from their seats, the Gurney party`'s clerk said,
"`The meeting is adjourned to 3 o`'clock.`"
John Meader said that all those who should remain sitting after this,
would be considered out of unity with the Yearly and Quarterly Meetings.

Most of the strangers and many of the members then left the house.
But the regular clerk notified Friends that the meeting had not adjourned;
and about thirty members of the meeting remained to finish
the business which necessarily came before it,
including the appointment of overseers, and then quietly concluded.
The strangers present were probably the new committee
of the Quarterly Meeting alluded to by J. Meader.
But if so, they ought to have produced their authority before interfering,
and then limited their interference within their authority.
They could have no legitimate authority to compel a Monthly
Meeting to act contrary to its conscientious convictions.
They may probably have withheld the presenting of
their credentials till they got their own clerk;
but it was clearly irregular in them to assume authority in that meeting,
until their credentials were presented;
and as the Quarterly Meeting had accepted the answers to the queries,
and the representatives appointed under the action of the old clerk,
they could have no claim now to pretend that he was not the clerk of the meeting,
and refuse to hand him their credentials, if they had any.
Two of them were the very same men who had endeavored already,
as we have seen previously,
to bring about a similar disorderly separation in South Kingston Monthly Meeting.
In the afternoon, the schismatic party with their new clerk,
and the Quarterly Meeting`'s committee,
returned to the house to hold their separate meeting, styling it, nevertheless,
Swanzey Monthly Meeting,
and appointed their own overseers and representatives to the Quarterly Meeting.
Thus commenced the memorable disruption of New England Yearly Meeting.

At the Quarterly Meeting, in the eleventh month, the clerk and other leading members,
many of whom had been active in promoting these disorderly proceedings,
refused to receive the representatives or the usual account sent by the
true Swanzey Monthly Meeting with the signature of its old clerk,
but accepted those from the schismatic Monthly Meeting, of their own party`'s setting up;
thereby identifying themselves with the schism,
and with the principles on account of which it was undertaken.
Thus a necessity devolved upon those who would remain
faithful to the true principles of the Society,
to endeavor to sustain the Quarterly Meeting and its branches on the ancient foundation.
These latter, therefore, after warning and entreating the others to no purpose,
and waiting till they had finished their business, remained together, appointed a clerk,
received the accounts and representatives sent by the true Swanzey Monthly Meeting,
and transacted the other business as the Quarterly Meeting of Rhode Island.^
footnote:[Address of Rhode Island Quarterly Meeting of Friends, 1845.
New York, Piercy and Reid.]
"`This,`" says the author of Considerations Addressed to
the Members of the Yearly Meeting of Philadelphia (1846,
page 80), "`was analogous with the transaction in Baltimore Yearly Meeting,
when Friends left that body as soon as it had identified itself with the Hicksites,
by the reception of their Epistle, and the rejection of that from Friends.`"^
footnote:[See Volume I, chapter 4.]

Those acting with and for the Yearly and Quarterly Meetings`' committees,
having thus undertaken to inaugurate a separation,
and this separation having now been carried through
the Quarterly Meeting itself by the same parties,
the subordinate meetings of Rhode Island Quarter were soon afterwards divided,
both as to discipline and worship.

The Meeting for Sufferings +++[+++says the above-quoted author of the Considerations,
in his lucid review of these transactions],
composed principally of the same Friends who were on the Yearly Meeting`'s committee,
without waiting for the judgment of the Yearly Meeting in the case,
issued a Circular to the Preparative, Monthly, and Quarterly Meetings,
giving their version of the separation and the causes leading to it,
and denouncing those as Separatists who believed
they were obliged to take the steps they did,
for the preservation of the order and discipline of the Society,
and the maintenance of the faith it had been raised up to support.
The Quarterly Meeting,
which had simply refused to join in with those who separated from it,
was represented as having acted from a spirit of disaffection,
and desire for individual liberty,
that is not willing to submit to the subordination recognized in our Discipline, etc.
The Meeting for Sufferings having thus stepped out of its proper sphere,
and held up their fellow-members for censure and rejection by the Society at large,
it rendered it necessary for the Quarterly Meeting to publish their account of the proceedings
which terminated in the secession of those who left Swanzey Monthly Meeting,
and set up a meeting for themselves,
and the course it had had to pursue in order to preserve
Rhode Island Quarterly Meeting on its original foundation.^
footnote:[From Considerations Addressed to the Members of Philadelphia Yearly Meeting;
by Charles Evans, Philadelphia, 1846, page 81.]

Previous to the ensuing Yearly Meeting, a contrivance was resorted to,
somewhat similar to that of the Hicks party in anticipation
of the separation in Philadelphia Yearly Meeting of 1827.
But instead of increasing the numbers of their representatives,
as had been done by the Hicksites,
the leaders in New England proscribed those who were opposed to their proceedings,
and prevented their appointment in several of the meetings.
Thus they succeeded to a great extent (in view of what was to occur)
in making the body of representatives as it were a packed jury.
Such was the state of things when New England Yearly
Meeting convened at Newport in the sixth month,
1845.
As the transactions were peculiar, and of great importance,
they may be best described in the language used by our Friends of that Yearly Meeting,
in the document which they issued on the occasion for the
information of their own members and of the Society at large.
The facts, as stated, have never, to the writer`'s knowledge, been called in question,
and substantially agree in all essential points with the very superficial statement
of this transaction in the Narrative put forth by the Gurney body.

At the first sitting of the Yearly Meeting, the report from the spurious +++[+++or Gurney]
Quarterly Meeting +++[+++of Rhode Island]
was read, together with those from the other quarters,
and the representatives`' names entered upon the minutes.
The report from the genuine Rhode Island Quarterly Meeting was
afterwards read and minuted as purporting to come from that meeting,
and the representatives`' names recorded,
whereupon a member of the Standing Committee +++[+++of the Yearly Meeting]
proposed a reference of the subject to the representatives
from all the Quarterly Meetings except Rhode Island,
for them to report which of the two meetings and sets of
representatives should be acknowledged by the Yearly Meeting.

The representatives from Rhode Island Quarterly Meeting^
footnote:[In these quotation,
where "`the representatives from Rhode Island Quarterly Meeting`" are spoken of,
allusion is of course made to that Quarterly Meeting which the leaders of the
Yearly Meeting in these transactions were endeavoring to scatter and divide.]
objected to this proposition,
upon the ground that several of the representatives from
the different quarters were members of the Standing Committee,
already implicated in the separation within their limits,
and in the support of the unsound doctrines and disorderly practices before alluded to;
and moreover,
that unfair and prescriptive measures had been resorted
to in the appointment of some of the representatives,
with a special view to the existing controversy among us.
In one Quarterly Meeting all who were suspected of being
opposed to the previous proceedings within this Yearly Meeting,
were excluded from appointment as representatives,
and the members of one Monthly Meeting belonging to that quarter were wholly excluded,
both from being appointed, and from nominating others for representatives.
At another Quarterly Meeting, members of the Standing Committee attended,
and advised against the appointment of such as had not unity with their proceedings.

The repeated and fruitless efforts heretofore made to obtain justice through
the intervention of committees of the Yearly Meeting were fully brought to view.
Allusion was also made to the evidence abundantly afforded, that such committees,
appointed in the partial and unfair manner they ever have been,
in cases involving the conduct of the Standing Committee,
are always greatly under the control of a few influential individuals,
mostly members of that committee.
And it was further declared that the sufferings of faithful Friends,
in their endeavors to stand for the precious cause of truth,
were mainly to be attributed to the proceedings of that committee,
and that the sad difficulties by which this Yearly Meeting is now encompassed,
lie at their door.
The representatives from Rhode Island Quarterly Meeting proposed that
the matter should be investigated and decided by the Yearly Meeting,
without reference to a committee,
that all might have a fair opportunity to hear and judge for themselves.^
footnote:[This would have been in accordance with the practice
during the past forty years in London Yearly Meeting,
of hearing appeals in reference to faith and doctrine in the Yearly Meeting at large.
See Vol.
I, chapter 2.]

There was much expression in favor of this proposal
by Friends from different Quarterly Meetings;
but many continued to urge the reference to the representatives.
Those from Rhode Island informed the Yearly Meeting that
they could not consent to such a disposition of the case,
for the reasons which had been given.
The clerk, notwithstanding, made a minute giving it that direction.
It was now proposed by Abraham Shearman, Jr., the acting clerk,
to suspend that ride of our Discipline which requires the representatives
to meet at the conclusion of the sitting on Second-day morning,
and agree upon a clerk for the year, and report the same to the adjournment.
A minute was made to this effect,
although objected to on the part of the representatives from Rhode Island;
and no time being specified, it was thus left in the discretion of the representatives,
when they would attend to the service.
The meeting soon after adjourned to the fourth hour on Second day, afternoon.

Previous to the adjournment,
one of the representatives from Rhode Island distinctly
proposed and requested that Friends of that Quarterly Meeting,
and such others as might be disposed to join them therein,
should take a solid opportunity of conferring together in that house,
at the conclusion of that sitting,
in order that they (the representatives) might be further
ascertained of the sense and judgment of Friends,
whether they should appear before the representatives from the different Quarterly Meetings,
and defend the case which had been referred to them in the manner above stated;
and if not,
to endeavor to see what steps it might seem proper in the wisdom of truth
for them to take under this very peculiar and trying state of things.
This request was extended to all who desired to maintain the ancient principles of Friends,
and that the Yearly Meeting should be sustained and held upon its original foundation.
No objection was made to it,
but the clerk said the representatives would meet in that room,
on the case referred to them from Rhode Island; whereupon another of that party,
who afterward seceded, signified that we might meet in the committee room.
At the conclusion, many Friends accordingly remained in the house,
but finding it impossible to confer together there
freely and without interruption from others,
they agreed upon another time and place of meeting, and then quietly withdrew.

Friends were introduced into deep exercise and travail of spirit,
wherein living desires were raised in the breasts of many for best help and direction;
and when they again assembled, free from interruption,
under an awful sense of the importance of moving only in the line of divine appointment,
they were united in judgment that it would not be right to appear with their
case before the representatives who were then sitting in our meetinghouse,
and who were immediately informed of this conclusion.
It was also the united sense and judgment of Friends,
that in order to sustain the Yearly Meeting in conformity
with its long-established Discipline,
and upon its original ground,
with the ancient doctrines and testimonies of the Society unimpaired,
it was in dispensable that the representatives should meet,
and agree upon and propose a clerk to the next sitting,
as by Discipline and former usage is required.

The Yearly Meeting having again convened in the afternoon,
soon after the opening minute was read, Prince Gardner +++[+++of Nantucket]
on behalf of the Representatives who met on clerks (which
included all those from Rhode Island +++[+++Smaller Body],
and some from Sandwich Quarterly Meetings),
reported that they were united in proposing the names of Thomas B. Gould for clerk,
and Charles Perry for assistant clerk, for the ensuing year.
This proposal was united with by many, but a large number opposed it,
and the former clerks continued to sit at the table.
Whereupon, those agreed to and proposed by the representatives,
were requested to take their seats at a table in a part of the house where
most of the Friends who had united in their appointment were sitting.^
footnote:[This was a part of the meetinghouse,
at one side of the portion occupied by the bulk of the assembly,
and capable of being divided from it by a sliding partition; which, however,
was at this time left open.]
After making a minute of the appointment of clerks, etc.,
the names of the representatives from Rhode Island
Quarterly Meeting of Friends were called,
and all responded thereto.

The clerk then proceeded to read the report from that meeting,
in which he was greatly interrupted by many in different parts of the house.
Abraham Shearman, Jr. (the former clerk), left his seat,
and passing along the ministers`' gallery towards
that part of it where the clerk was standing,
called upon him to desist; but after a short pause,
the reading was calmly proceeded in until finished.
After appointing a committee to prepare and produce
to a future sitting a more extended minute,
to be entered on our records,
embracing the very trying circumstances in which we were placed,
with the ground and cause thereof, it did not appear proper,
on account of the great interruption Friends met with,
to introduce any further business at that sitting.
The Yearly Meeting concluded to adjourn, to meet on Third-day morning at the tenth hour;
of which the women`'s meeting was informed, and adjourned accordingly.
This fact being reported to the separate meeting by their messengers,
they adjourned to meet at the same place, at the ninth hour.

Among other interruptions during this sitting, Abraham Shearman, Jr.,
called upon the representatives, except those from Rhode Island,
to express their dissent from the appointment of clerks;
which was done by thirty-eight of them;^
footnote:[The Narrative of the Gurney party says "`forty-one`"--perhaps
inadvertently including the absentees.]
four were in unity with the appointment, and three were absent.
Friends assembled on Third-day morning,
and found our meetinghouse already occupied by the separate meeting.
Whereupon, the Yearly Meeting gathered and was opened in the yard;
the men`'s meeting near one end of the house, and the women`'s at the other.
Each meeting appointed a committee to apply to those
in the house for the vacation of the clerks`' tables,
for the use of the Yearly Meeting and its clerks,
and also for the transfer of the books and papers thereof;
which application having been made, and unconditionally refused,
we were deprived of the reports from all our Quarterly Meetings except Rhode Island.
One representative from Salem, and three from Sandwich Quarterly Meetings,
uniting with us, were recognized as such by the meeting; which,
with those from Rhode Island, make thirteen representatives to the men`'s meeting,
who have remained with Friends.

After being thus obliged to hold our meeting, both of men and women Friends,
standing in the open air for nearly two hours,
it was concluded to adjourn the Yearly Meeting to
the Baptist meetinghouse in Clarke Street,
which was kindly opened for that purpose.
Friends having removed from our meetinghouse yard in a body,
convened again immediately at the place proposed; and sitting for a time together,
our hearts were tendered and united under the cementing
influence of the Great Head of the church;
who, as we feel bound reverently to acknowledge, has been pleased,
in his unmerited mercy, and in a remarkable manner, to own us in the way which we go,
to manifest himself among us by his Spirit, to uphold and preserve by his power,
amid the varied conflicts which we have had to pass through for his great name`'s sake.
Under feelings of deep sorrow and concern for those
who have been drawn aside from the Truth,
and of thankfulness to the Lord our preserver,
such was the solemnity and the preciousness of the covering
which in adorable mercy was spread over us,
that it was concluded to adjourn without introducing any business at that time.

The subsequent sittings of the Yearly Meeting have been regularly held at the same place;
and although greatly reduced in numbers,
Friends have been mercifully favored during these several sittings,
to experience renewed and abundant evidence,
that he who leadeth the blind by a way which they know not,
and in paths which they have not seen, is not unmindful of his people; and that while,
in the counsels of his own will,
he hath permitted them to be thus sifted and very closely tried, yet that he will,
in his own good time, gather the outcasts of Israel, and the dispersed of Judah,
raising up judges as at the first, and counsellors as at the beginning,
who shall not err in vision or stumble in judgment, but who shall be enabled,
by his holy help, to lay judgment to the line, and righteousness to the plummet.
For Zion was to be redeemed through judgment, and her converts with righteousness;
and we are persuaded that he who reigneth King in the midst of Zion,
will verify his ancient promise, "`I will restore health unto thee,
and I will heal thee of thy wounds, saith the Lord, because they called thee an outcast,
saying, this is Zion, whom no man seeketh after.
Behold, I will bring again the captivity of Jacob`'s tents,
and have mercy on his dwelling-places; and the city shall be builded upon her own heap,
and the palace shall remain after the manner thereof.
And out of them shall proceed thanksgiving, and the voice of them that make merry:
and I will multiply them, and they shall not be few; I will also glorify them,
and they shall not be small.
Their children also shall be as aforetime,
and their congregation shall be established before me,
and I will punish all that oppress them.`"

The sad consequences which have necessarily followed such
a departure from sound principles and a wholesome discipline,
on the part of the "`leaders of the people,`" through their assuming,
and until the present time,
retaining an arbitrary and controlling influence in the transaction
of the affairs of the church in this Yearly Meeting,
have been made sorrowfully apparent.
It is equally clear and undeniable that those who maintain
their integrity and allegiance to the sound principles,
Christian doctrines, and long-established discipline of our religious Society,
as originally held and supported by the first Friends, are the Society,
whether it be composed of less or more numbers.
Neither can the highest professions of an adherence to first
principles be availing to those who have so departed,
until the offences which they have committed, by introducing, supporting,
and defending such adverse principles, be done away,
and their undisciplinary proceedings and oppressive acts reversed.
We say, that until such have manifested a sincere repentance,
by fruits meet for the same,
they must and will be accounted as Separatists from the true body and Society of Friends.^
footnote:[Epistolary Declaration and Testimony of
the Yearly Meeting of Friends for New England,
1845, page 8 to 18.]

The representatives of the Gurney party meantime met according to their instructions,
and agreed to report in favor of acknowledging those appointed
as representatives by the separate Quarterly Meeting of Rhode Island,
which, as we have seen,
was identified with the schismatic and disorderly Monthly Meeting of Swanzey.
Their Yearly Meeting united with their report, and recognized those representatives,
to the exclusion of the friends of sound doctrine and discipline;
and thus identified themselves with the irregular
and despotic acts which have been narrated,
and with the unsound doctrines which those transactions went to fasten upon the Society.
This "`Larger Body`" of the Yearly Meeting, which,
under a blind confidence in its leading men, had now launched headlong into schism,
put forth a statement containing their own version of what had occurred among them,
entitled a Narrative of Facts and Circumstances That Have Tended to Produce
a Separation From the Society of Friends in New England Yearly Meeting.
The same circumstances that have been here related were gone over therein,
with their own interpretations and assertions of intents and purposes,
thus differing mainly from the statement of the "`Smaller
Body`" by covering up the matter of doctrines,
and attributing all to a spirit of insubordination and detraction, under which,
as they alleged,
their own characters had been defamed as supporters of unsound doctrines.

This allegation of a spirit, of detraction and defamation, if true,
would at once have been sufficient to condemn the party
who would persist in measures having so guilty a foundation;
and the leaders of the Gurney party doubtless hoped that their official and confident
assertion of the fact would lead to its being taken for granted that it was so.
For they uniformly and most carefully avoided to touch the
question on which they admitted themselves accused,
or to admit of its being investigated, by searching into those doctrines,
and showing that they did not countenance them.
They knew that, if brought to the point, they could not clear themselves;
therefore they refused to listen, and stood on their bare assertion,
that the accusation was defamation, and brought in a spirit of detraction.
Most honest men, when accused of holding or promoting dangerous doctrines,
would demand to be informed, what doctrines,
and in what manner they had evinced any adhesion to them.
But these men, while avowing that the accusation was brought against them,
would never in any instance listen to the specification (often pressed upon them),
or be candid enough to face the charge,
but flinched and walked away as soon as it was attempted.

The oft-reiterated plea of the leaders in these transactions,
that "`doctrines were not involved in the case,`" was manifestly false and unjust.
Indeed, as sane men, they must have known that it was false.
For John Wilbur`'s course in the matter was, from beginning to end,
founded solely upon the unsoundness and dangerous tendency of J. J. Gurney`'s doctrines,
as he often testified to them, and offered to prove by the clearest evidence.
And it is well known that they always refused to listen to his evidence of it,
in order to shut it out from their transactions.
But some, at least, of their number knew already, or had known,
that these doctrines were at variance with the doctrines of Quakerism,
and in their better days had openly testified against them on that ground!
It is true, they issued,
along with the above mentioned Narrative of Facts and Circumstances,
a Declaration on Various Christian Doctrines,
with solemn protestations of its "`embracing the doctrines of the gospel,
as they ever have been and are now most assuredly believed by the Society of
Friends,`" and that it "`was fully united with and adopted by the meeting,
and declared to be its Faith upon the subjects on which it treats.`"

But what, are the subjects on which it treats?
Does it go into the matter of which they had been accused, and sift it to the bottom,
as honest men would have done--even that certain very important departures
from our ancient faith had received encouragement at their hands,
by the measures in which they had for years persisted?
Not at all.
It is mainly composed of quotations from Robert Barclay, George Fox, and Joseph Phipps,
and from the Testimony of the Society of Friends in America,
which was issued in 1830 against the doctrines of Elias Hicks and his adherents,
and signed by Elisha Bates, as clerk of the joint committee who prepared it.
These quotations are good and sound, as far as they go on the subjects selected;
but as a whole they appear quite as well adapted to prove that they were not Hicksites,
as for any other purpose, if not rather more so.
Some of the quotations are on topics concerning which J. J. Gurney
was never charged with diverging from the doctrines of the Society.
Others contain sentiments which, on comparison,
would be found at variance with those of J. J. Gurney;
but the writers of the declaration seem to have been unaware
that they were thereby proving their own inconsistency,
in having so strenuously supported this author,
as to have recklessly torn the Society to pieces in his defence.

Even if this declaration of faith, as a whole,
could be said to be an antidote to the doctrines of J. J. Gurney, or a disavowal of them,
which can by no means be candidly said of it,
it would go no further to exonerate the party issuing it,
from responsibility for the sorrowful nature and consequences of their late transactions,
than the high-sounding professions made by the Council of Constance,
of being assembled and governed by "`the influence of the Holy Spirit,`" of being "`convoked
with the inspiration of God,`" and of "`having God alone before their eyes,`"^
footnote:[The Lives, Sentiments,
and Sufferings of Some Reformers Before and After Luther; by W. Hodgson, Philadelphia,
1867, p. 160.]
could exonerate those "`holy fathers,`" as they called themselves,
from the guilt incurred by their sacrifice of that eminent martyr, John Huss,
when they so solemnly and sanctimoniously delivered him
up to the secular arm for consignment to the flames.

But, as said above, it cannot be sustained, that this declaration covers the ground,
by any means satisfactorily,
of the allegations of unsoundness against J. J. Gurney
and those who persisted in supporting him.
We must bear in mind, that while the tenor of J. J. Gurney`'s system, as a whole,
was to subvert true Quakerism,
yet his mode of procedure was to undermine it by gradations not easily
perceived by those who did not look deeper than the surface of things,
rather than to alarm by a direct attack.
He professed, and doubtless felt,
an attachment to what he considered the proper doctrines of the Society;
modifying and superseding some of the most characteristic
and fundamental by representations of his own,
according to what he thought they ought to be;
professing at the same time great esteem for early Friends,
while thus superseding the cherished products of their convictions.
Several of their quotations from Barclay are not by any means verbally correct,
and one concluding at the top of page 15 is quite imperfect,
the sentence not being completed.
On comparison with the passage in the Apology (Prop, iii, Sec.
ii), it appears that where Barclay has put a semicolon, they have put a period,
concluding without completing the sense!
Barclay says, "`Though then we do acknowledge`" etc., (as quoted by them);
"`yet we may not call them +++[+++the Scriptures]
the principal fountain of all truth and knowledge,
nor yet the first adequate rule of faith and manners;
because the principal fountain of truth must be the truth itself; i. e.,
that whose certainty and authority depends not upon another.`"
Perhaps they may have thought that the latter part of the sentence (beginning
at "`yet`") was not particularly convenient to the object they had in view;
but their leaving off thus in the middle of such a sentence,
at least renders their candor liable to be called in question.

Their Declaration opens with the expression of earnest desires
that love and charity may prevail among the members;
deplores the uncharitable accusations of a dividing spirit,
by which they had been assailed, and which had filled them with astonishment and sorrow;
and exhorts all to "`that fervent charity which suffereth long and is kind!`"
And they conclude with the assertion,--"`We entirely disclaim,
and have invariably disclaimed all views and doctrines
inconsistent therewith`" +++[+++this declaration of faith],
"`from whatever source they may come,
or by whomsoever they may be promulgated;`"..."`nor do we countenance the receiving
of any sentiments which are at variance with those contained in our approved writers.`"^
footnote:[Declaration on Various Christian Doctrines; by the Larger Body of New England, p. 22.]
We might suppose that the writers of this passage believed that
their deeds for the past five years had all been buried in oblivion,
when they had the boldness to present such an assertion
to be sanctioned by the Yearly Meeting!
Surely none could believe it to be true,
but those who knew nothing of the nature of what had been passing,
or who did not comprehend the meaning of such assertions,
or who had given themselves up implicitly to the fascination and bondage of party spirit.

Yet by the mass of the members composing the assembly
which issued this declaration of faith,
it was doubtless considered to be a true statement of the doctrines
still sustained by those who controlled their affairs.
A large proportion of them still believed, or rather did not disbelieve,
in the ancient tenets of the Society;
but they had been so long accustomed to look with unlimited confidence to the
members of the Meeting for Sufferings and the Yearly Meeting`'s Standing Committee,
and their habitual instruments,
who together had been the main promoters of the late extraordinary measures,
that they scarcely permitted themselves seriously to question
the rectitude of anything whatever proposed by them.
And as the quotations were principally from the writings of early Friends, they took it,
of course, for granted, that they were not only correct in themselves,
which they probably were, in substance, so far as they went;
but that they were also adequate to the point desired, which they certainly were not;
unless indeed that desired point were to show,
that while theoretically acknowledging one system
of doctrines for effect in the Yearly Meeting,
this combination of its functionaries could for years, in practice, uphold and promote,
even to the tearing asunder of the body,
what was fundamentally and diametrically opposite.

The next year, 1846, saw a similar attempt, on the part of J. J. Gurney himself,
to make an appearance of being sound in the doctrines of Friends.
He also put forth a declaration of faith,^
footnote:[This proceeding may remind the reader, of a similar action of E. Hicks,
in 1829, in writing a letter to Hugh Judge,
containing answers to six queries respecting his doctrines.
See Vol.
I, end of chapter 4.]
to suit a particular legal occasion coming on in New England;
which he affirmed before the Mayor of Norwich and two justices of the peace,
and then sent it over to America.
It embraced several subjects, couched in very general terms,
which did not meet the points at issue;
was altogether silent on a number of others in which his writings
had been proved to conflict with the views of early Friends;
and on some the observations made were even confirmatory of the charges of divergence.

There were in it six distinct topics, viz.: 1. On the Holy Scriptures;
2+++.+++ Immediate and perceptible guidance of the Holy Spirit; 3. Justification;
4+++.+++ The "`Trinity;`" 5. The resurrection; 6. The Sabbath.
In speaking of the Holy Scriptures,
he quoted with approbation the unsound paragraph inserted at his
own instigation in the London General Epistle of 1836,
respecting their being "`the appointed means,`" etc.,
which of itself evinced that he was in opposition to ancient Friends.
Respecting "`the Trinity,`" he said that he had never
thought it right to make use of that term;
but he did not say how many times he had used terms
on that subject equally if not more objectionable,
such as "`Plurality in Unity,`" "`Plurality in Essence,`" "`Personality of the Father,
of the Son, and of the Holy Spirit.`"
There is a curious coincidence between this declaration and that put forth
by the Larger Body of New England which we have just been considering;
that while they stop at a semicolon in quoting from Robert Barclay,
he stops at a semicolon in quoting from Edward Burrough--both, apparently,
to avoid a fatal plunge into self-contradiction.^
footnote:[Not but that any one may stop, if he pleases, at a semicolon, or at a comma,
or even without one, if he has got what he wanted;
but if he leaves out a part of a sentence especially
essential to represent his author fairly,
he lays himself open to a question as to his reason or motive for rejecting the context.]

In the latter case,
the part thus omitted was doubtless felt to be incompatible
with his known objection to the doctrine of "`Christ within,
the hope of glory.`"
His purpose in quoting E. Burrough was to attempt to show that
he united with him in a certain passage respecting justification;
but, stopping at the semicolon,
he left out an important part of E. Burrough`'s declaration, viz.:
"`which faith hath received Christ to dwell in us.`"
He omitted, also, any allusion to E. Burrough`'s declaration in the same treatise,
that none can be justified by Christ`'s death,
"`but who witness Christ within them;`" "`that have not Christ in them.`"
In short,
in no single point does this declaration defend him from the alleged discrepancies
between his published sentiments and those of true Friends.
On several subjects, such as Faith, Original Sin, the Body and Blood of Christ, Prayer,
and "`the Gospel,`" it is almost entirely silent;
as well as on the various points on which, in his Brief Remarks,
he accused our early and most cherished writers of "`serious mistakes.`"
But as I have elsewhere^
footnote:[Examination of the Memoirs and Writing of J. J. Gurney, page 129, etc.]
treated somewhat more largely on the fallacy of this declaration of faith,
it is only needful here thus briefly to refer to it.

Some extracts from a letter, said to have been written by J. J. Gurney,
were published in the Friend`'s Review, of first month 20th, 1872,
which were evidently brought forward in order to
prove his soundness on certain points of doctrine.
There is no date given to this letter, nor any information to whom it was addressed,
or under what circumstances it was written.
It cannot be denied that it contains sound doctrine,
and was probably written for the same purpose as the Declaration above mentioned;
and if the writer had confined himself within these views,
much harm would have been spared to the Society.
It should be recollected that the opponents of J. J. Gurney`'s unsound
views never denied that he had written much that was verbally sound;
but their objections were aimed at very prominent, fundamental, and dangerous errors,
new among Friends, appearing in many thousand copies of his books,
and which he never would retract or condemn.
So did Elias Hicks at times preach apparently sound doctrine;
yet he too never would condemn or retract the unsound, which, alas,
was prominent in poisoning the minds of the people.

The two declarations of faith above alluded to were used (and probably
drawn up with that special intent) as evidence in a suit before
the Supreme Judicial Court for the counties of Bristol,
Plymouth, etc., sitting at Plymouth, Mass., being a suit in equity,
brought by Earle and others, plaintiffs, in behalf of the Gurney party,
against Wood and others, defendants,
on behalf of Friends of the "`Smaller Body,`" for possession
of the meetinghouse and lot of ground at Fall River,
belonging to Swanzey Monthly Meeting; the Overseers of the meeting being,
by the law of Massachusetts, ex-officio trustees of the property.
At the time of the separation,
Friends had possession or charge of the premises in question;
but the party claiming to be overseers on the part of the Gurneyites took forcible
possession of the property (as the Hicksites had done before in Pennsylvania,
etc.), taking off the locks and substituting others.
Not desiring to be involved in a contest of this sort,
Friends brought an action at law in the first place.
Subsequently Oliver Earle and others filed a bill in equity, as plaintiffs,
in the Supreme Court, thus superseding the action at law,
and reversing the position of the parties.

It is much to be regretted that Friends had anything to do with bringing on this suit,
which, as usual, although appearing to be a very clear case,
ended in no benefit to the cause of Truth.
During the trial it was amply testified by various witnesses,^
footnote:[The evidence on the part of the defendants was
afterwards printed in an octavo volume of 392 pages,
entitled Depositions, etc., Earle, etc., v. Wood, etc., Supreme Court of Massachusetts.
Boston, T. R. Marvin, 1850.
The writer has not succeeded in ascertaining whether the
evidence on behalf of the plaintiffs was ever printed.
Owing to all the testimony having been taken by way
of affidavit at the homes of the respective witnesses,
the case is by no means so clearly developed as it might
have been by viva voce examinations in open court;
and from the constant repetition of the same points by nearly all the
witnesses in reply to long monotonous lists of written interrogatories,
the perusal is exceedingly dry and tedious,
and it would not be surprising if this were one cause of
the Court having paid so little attention to the testimony.
The case appears to have suffered from ill management of counsel,
as well as carelessness and one-sidedness of the Court.]
that novel doctrines, contrary to the faith of the Society,
and the persistent efforts to sustain them and their main author,
by arbitrarily suppressing all opposition to them, had been the basis of the schism;
and likewise that the actual separation had been brought
about by these efforts of the advocates of J. J. Gurney,
in an irregular, disorderly, and oppressive series of transactions,
totally unauthorized by the Discipline of that Yearly Meeting, or of any other.
These circumstances were plainly brought to view
also in the pleading of the counsel for Friends.
But the result clearly showed the unfitness of judicial
tribunals to undertake to decide momentous religious questions,
or to say which of two opposing bodies is the true Society of Friends.

The case was delayed for a considerable time,
and was at length decided by the court in the year 1852.
Judge Shaw, who pronounced the decision,
displayed great ignorance (as might have been expected)
of the constitution and regulations of the Society,
and seemed to flounder about, with all his legal learning,
like a man who had fallen into the river,
and scarcely knew how to contrive his endeavors so
as to be sure to come out on one particular shore,
where were the greatest number of spectators.
His expressions indicate that he took but little pains for
accuracy of statement of various matters in the evidence,
and that he took many things for granted not at all
warranted by the principles or usages of the Society;
such as that "`each Yearly Meeting is independent of all others`"--that the "`Committee
of Sufferings`" has "`a general supervising and advisory jurisdiction`"--that
"`the Yearly Meeting has a final and controlling jurisdiction in all matters
of faith and religious duty`"--"`final and conclusive`"--that though the Scriptures
are believed to be "`the unerring guide to Christian truth,`" yet that "`new
truths may be discovered`" from them,
so as to "`add something to existing faith`"--that therefore
"`some modification of their creed may be allowable,
if only it is united in by the Yearly Meeting, whose decisions are final and infallible,
as well in matters of faith as of conduct`"--displaying herein
a most labored attempt to claim a broad latitude of doctrine,
and papal infallibility,
for the Yearly Meetings in the Society of Friends!`" "`But,`" said the judge,
with wonderful inattention to the facts and bearing of the testimony,
"`we have no evidence that any organized meeting, monthly, quarterly, or yearly,
took any step as a body to promote or establish any opinion or tenet of
belief not entirely correct!`" "`The charge on the part of J. Wilbur and
his friends,`" of promoting the tenets of J. J. Gurney,
"`they denied,`" (as if their simple denial rebutted all the evidence)
and "`a Narrative and Declaration was put forth,
in which they state their belief satisfactory to those who
affix the imputation of heresy to that same meeting!`"
Where he got such an idea as that it was "`satisfactory`" to these, does not appear,
and is merely his own assertion.

With the same persistent and unwarrantable one-sidedness,
the judge goes on to give the reasons inducing the court to decide that the Gurney Monthly,
Quarterly,
and Yearly Meetings are the legitimate meetings of the Society and entitled to the property;
for that in the Monthly Meeting, David Shove, "`whether regularly or irregularly,
was declared, and proceeded to act,
as clerk,`" and that "`without recapitulating the evidence, which is very voluminous,
we should be inclined to the opinion`" that "`Shove must
be taken to be the authorized clerk,`" etc.--in other words,
that a pretended appointment,
"`whether regular or irregular,`" is to be sanctioned
by the highest judicial tribunal of the State!
The judge acknowledges that evidence had been given that changes
of doctrine were complained of as being connected with the difficulty,
but he passes over them very lightly, as scarcely worthy of notice.
Throughout the document, the reasoning is sophistical and exceedingly superficial,
giving no weight to the evidence or arguments of the defendants,
and showing a manifest bias to the majority, or "`the Yearly Meeting.`"
The decision concludes thus: "`On the whole case, the Court are of the opinion,
that the plaintiffs are entitled to a decree for the establishment
of their title to the land and meetinghouse,
as prayed for in their bill.`"

After the publication of this decision,
the Meeting for Sufferings of the "`Smaller Body,`" believing that
it set forth erroneous positions in relation to the internal polity
and long-established usages and principles of the Society,
published A Review of the Opinion of the Supreme
Judicial Court of Massachusetts in the case,
in which they luminously exposed the gross errors and mistakes made by the judge,
and the false and flimsy reasoning on which the decision was founded.
The importance of the subject as a matter of history is such,
that it seems best to introduce here a few detached extracts from this review,
so as to set the matter in its true light.

In the first place we may remark, that doctrines grounded upon plain Scripture testimony,
as are those of the Society of Friends,
have never been admitted by them to be speculative, a term which implies ideal,
theoretical only, not practical.
The doctrines of the Society of Friends are not only practical,
but they are also definite and tangible.
Whatever degree of firmness or decision the court
may have arrived at in relation to other principles,
they appear to have had so little conception of the stability
and definiteness of the faith of the Society of Friends,
as to suppose their principles might be very elastic and accommodating,
susceptible of being bended this way or that way to suit occasions.
But will it do to bend the Christian faith and doctrines,
so as to meet the caprice of mere speculative reasoners?

George Fox could be neither flattered nor driven from his unbending rule,
either by Oliver Cromwell or by Charles II, etc.
Well aware of what has been attempted,
the judge actually advocates the right of a Yearly
Meeting to modify the creed of the Society,
or in other words to change its principles;
and asserts that such a step taken by a Yearly Meeting should
be binding upon all its subordinate meetings and its members!
That a Yearly Meeting should have the power to change the principles of the Society,
and to compel the subordinate meetings and members to follow them in that change,
or be deprived of their meetinghouses,
are doctrines new and strange to old-fashioned Quakers, and would be, we conceive,
to others, upon any other ground than the papal dogma that the Church cannot err.
After this elaborate attempt to prove that a change of principles does
not alter the character or affect the identity of a religious body,
the judge declares that this "`unhappy controversy arose out of a jealousy or apprehension,
on the part of some of the Quaker body,
that another part were covertly circulating and endeavoring
to promote false doctrines,`" etc.,
"`which, however, they (the Gurneyite party) denied!`"

But does the denial of a fact so well known invalidate
a volume of testimony clearly going to prove it?
Is a denial or negative of more force in a court of law than an affirmative?
And should not so much testimony as was adduced, clearly proving the Gurney party,
in all its capacities,
to have acted in support of J. J. Gurney and his doctrines (inasmuch as a man`'s
acts are stronger evidence than his words) have more force than a mere denial?
Can we suppose that the court could have overlooked this important fact--that
divers consistent Friends were disowned by the Gurney party for openly
expressing their dissent from J. J. Gurney`'s doctrines?
There can be no stronger proof of their attachment to Gurneyism than this.
Moreover, it was proved to the court,
that New England Yearly Meeting gave to J. J. Gurney a returning certificate,
declaring their full unity with him, although it was objected to at the time,
by those with whom these defendants are in unity,
that such certificate would be an endorsement of his doctrines:
a view which none offered to gainsay.
Still the Supreme Court of Massachusetts think that, in very deed,
this controversy arose from a mere jealousy.

Again:

The court say that the Narrative and Declaration
put forth in 1845 by the Gurney Yearly Meeting,
was satisfactory +++[+++as regards their belief]
to those who affix the imputation of heresy to that same meeting.
What foundation there is for this assertion we know not;
certain it is that those who affix that imputation have not expressed
themselves satisfied with the declaration of faith,
but the contrary;
holding it to be defective because it does not comprehend
the whole of the Quaker confession of faith,
nor does it discard a single article of Gurney`'s unsound doctrines,
which the Gurneyite body were charged with having adopted; and having been so charged,
it was indispensable, in order to prove them true Quakers,
that they should have specially acquitted themselves from those heretical opinions.
So far was this Narrative and Declaration from being satisfactory to the sound body,
that they immediately put forth Strictures and comments upon it,
setting forth their dissatisfaction, etc.

The fact was fully proved to the court,
though it seems not to have been regarded by them,
that the Meeting for Sufferings took measures to spread Gurney`'s doctrines,
and reported their having done so to the Yearly Meeting,
and that the Yearly Meeting acknowledged its satisfaction therewith,
and so recorded it on their book.
Thus it is proved that meetings of the highest order in the Society,
if they have not promulgated unsound doctrines of their own,
have taken effectual means to spread those of Gurney, etc.

In reference to the disorderly appointment of Shove as clerk
of Swauzey Monthly Meeting in the eighth month,
which the Judge had acknowledged to have been proposed
before the meeting was opened by the clerk,
they say:

To appoint a new clerk before the meeting was opened by the former, when present,
is clearly an infraction upon the order and usages of New England Yearly Meeting,
which was never before attempted; and manifested not only a spirit of disorder,
but also of domination and tyranny.
For it was a person not belonging to that meeting who named David Shove for clerk before
the meeting was opened or organized for the transaction of any business whatever;
in fact, before the session had legally commenced.
And, as if to render the disorder more complete,
those attending from other parts produced no minute of appointment,
or any evidence or credentials to certify in what capacity they were present.

Well may the Judge say that D. Shove was declared
clerk regularly or irregularly,`' and we think,
with the facts here stated, few will be at a loss to decide which.
Yet in the next paragraph the Court say.
"`We should be inclined to the opinion that at the August meeting,
Shove must be taken to be the authorized clerk;
that those who remained after the adjournment was announced +++[+++by him], acted irregularly,
and became seceders!`"
The Judge adds, "`and if Shove was improperly elected,
they should have sought their remedy by an appeal to the Quarterly
Meeting`"--a proposition wholly irrelevant to the case.
Their duty clearly was to maintain the Monthly Meeting inviolable, and they did so,
forwarding their usual account to the Quarterly Meeting.

And they go on to show what the powers of committees are, and are not,
according to discipline and usage.
In allusion to the Yearly Meeting, they quote the words of the Court, viz.:
"`But at this time the Yearly Meeting had done no act,
refused no application for redress, declared no heretical opinion,
nor taken any step to be complained of.`"
On which they make the following remarks:

It seems hardly credible that the Court could have been so ignorant of the history
of New England Yearly Meeting for the four or five years prior to the separation,
as to make this assertion.
As already stated,
they had given to J. J. Gurney a full certificate of unity and approval,
without regard to the objection made at the time,
that it would be an endorsement of his unsound views.
They had approved of the circulation of Gurney`'s books by the Meeting for Sufferings,
containing some of those unsound views.
They had approved and confirmed the laying down of South Kingston Monthly Meeting,
which was done in defence and for the support of those unsound views,
in a manner plainly contrary to the provisions of the Discipline.
They had also confirmed the disownment of John Wilbur,
which was effected by the direct influence and action of the Yearly and
Quarterly Meetings`' committees in a manner unprecedented in the Society,
after he had been fully and honorably acquitted by his own Monthly Meeting,
and all because of his conscientious testimony against those unsound doctrines.

The Yearly Meeting had also now referred this whole
matter in controversy to men ex parte,
many of whom had prejudged it in a public manner, and thus become a direct party to it,
so that this reference--made as it was against the
consent and under the protest of the other party,
with the representatives selected as we have already shown--was at best
but a poor caricature of the administration of justice and right.
In doing all this, had the Yearly Meeting taken, no step to be complained of?
The circumstance that it was a minority of the representatives who proposed the clerks,
and a minority of the body who united with them therein,
we cannot but think must have had a strong,
if not a controlling influence in bringing the Court to this conclusion.
"`Those who depart from the principles of a Society, which are the bond of its union,
however anxious they may be for it,
can have no rightful authority to control those who have kept to first principles,
be their disparity of numbers what it may.`"
The apparent inability of the Court to appreciate this doctrine,
that those who hold to the original principles of the Society in the Truth,
must be accounted the genuine Society without regard to numbers,
seems to have led to the (in our apprehension) erroneous judgment which they have rendered.

Nor can a doctrinal question, such as now exists,
be decided and settled by a Yearly Meeting itself, if one-half or more of that body,
or perhaps if the controlling and influential members,
become irreclaimably apostate in the doctrines at issue;
in such case the body can only be purged by a sifting or separation,
so that the sound may be disencumbered of the unsound, and enabled,
by the help of the Lord, through faithfulness and singleness of heart,
to continue to support their original doctrines and testimonies.
But for the civil tribunal to take the meetinghouses and lots
from those who have always held to the Society`'s original principles,
and for whose use they were intended,
and give them to those who have brought in and adopted new doctrines,
and this too upon the plea that our doctrines may
he thus modified and changed with impunity,
is a greater departure from sound principles and just proceedings than we were
prepared to expect at the hands of the Supreme Judicial Court of Massachusetts;
and we trust we have shown that the opinion of the Court is not justly entitled to become
an authority or precedent in regard to matters similar to those at issue in this case.

Beside this review,
one of the Counsel likewise issued some close strictures
on the glaring errors of the decision of the Court.
The following are a few of his remarks, treating the case in a legal point of view:

In the investigation of this question,
the usages of the Society of Friends were proved
by numerous witnesses and the Book of Discipline;
all the transactions of the Meeting were clearly proved,
and the legal authorities applicable to the case were also cited and read;
all of which were victorious for the defendants;
and their counsel relied and still relies that there was full proof
that Thomas Wilbur was the true and legal clerk of that meeting,
and that his records and minutes (confirmed by the testimony) were conclusive evidence
of the appointment of the defendants as the true and only overseers of the meeting.
How could there be a doubt?
The facts were clear, uncontroverted, and incontrovertible; and, as Judge Twisden said,
"`The law was on their side.`"
Here are all the facts: +++[+++citing in brief from the testimony.]
Who will stand up for the orderly appointment of the plaintiffs?
Here was the very height of disorder.
Here is John Meader, with half a dozen others, not members of the meeting,
making motions and speeches before the meeting is opened, and when called to order,
claiming to be committee-men from a superior meeting,
and when called upon for the minute of their appointment, refusing to produce it, etc., etc.
Was it ever known, that a meeting, and an election of this sort,
has been sustained by any court of law in Christendom?
But they say that they were committee-men of a superior meeting.
And what of that?
The evidence in the case does not show that such, by Quaker usages,
could do anything more than advise.
But they are stripped of this pretence by not producing, or handing in,
the minute of their appointment.
Such is the law in all analogous cases.

They (John Meader and the committee,
if they were such) had no right to make the motion
which they did make and assist to consummate;
it was disorderly and void;
because it was made and consummated before any minute opening
the meeting had been made by the standing clerk,
or any minute from the Quarterly Meeting was produced.
+++[+++Authorities cited.]
Beyond all controversy, according to unquestionable law and the evidence,
Thomas Wilbur rightfully held the +++[+++clerk`'s]
chair, did not leave it, proceeded with the business of the meeting,
and that meeting chose or appointed the defendants the true and legitimate overseers;
and the assembly which afterwards came in with David Shove,
and undertook to appoint the plaintiffs overseers, was a disorderly meeting,
a meeting in every legal point of view so entirely void of authority, that no body,
politic or ecclesiastical, could make it good, short of legislative action;
and even that could not divest the defendants of the right and title, as trustees,
which vested in them at the moment of their election.

So well satisfied was Mr. +++[+++Daniel]
Webster of this, he being one of defendants`' counsel,
but prevented from pleading by his absorbing public duties as Secretary of State,
that he was not willing that the case should be argued on any other point.
But that which could not make him for a moment doubtful,
has affected the Court in a very different manner.
The evidence was very full and extensive, and the argument thereon astute,
and it was very convenient to get over it per saltum,
and to place the whole matter on the transcendent jurisdiction of the Yearly Meeting.
But the palpable, transparent, and flagrant wrong, and which is not only void in law,
but very astounding to sound Friends, and reprehensible in the highest degree,
remained to be consummated.
The Court say,
"`At the same meeting`" (by its subsequent order) "`a Narrative was put
forth as the official and authoritative judgment of the meeting,
adopted by them, and ordered to be authenticated as their act,
in which the plaintiffs are recognized and declared
as the rightful overseers of Swanzey Monthly Meeting,
appointed in August, 1844.`"

We have looked into that Narrative, referred to by the Court,
and cannot find that there is any such recognition and declaration;
cannot find that the Yearly Meeting have decided that the plaintiffs
were the rightful overseers of the Swanzey Monthly Meeting.
And on inquiring of the opposite party, they do not say that such a declaration was made.
If none such was in the case, all the reasoning of the Court falls to the ground.
To say that, after their election, a disorderly meeting may choose others,
and that a superior meeting may waive the disorder and confirm the election,
and in that way,
deprive the overseers first chosen of their office
and the property vested in them as a corporation,
is to accord to the Yearly Meeting greater power than any legislative
body in the United States possesses under its Constitution.

+++[+++The Court say:]
"`But there was no question here, as to the rights of the Swanzey Monthly Meeting;
but as to the claims of certain individuals, to be the rightful overseers,
representatives, and officers of the Swanzey Monthly Meeting!`"
Here is an enigma to all Friends concerned, and not much less to their counsel.
The argument is, that the defendants are a corporation, and cannot be deprived,
but by due process, according to common right and justice.
The Court say, "`it was intimated`" in the argument,
that the meeting could be no otherwise deprived;
but that this is a question as to the claim of certain persons to be overseers.
Certainly that was the question; and the argument was,
that the defendants were duly chosen overseers by that meeting,
and that a superior meeting could not deprive them of their office or estate merely
by pronouncing in favor of others afterwards chosen at a disorderly meeting.
That the Court should think they had answered this argument, in this summary manner,
is a mystery.
It would seem they either misapprehended the argument, or were not fully,
or at least not consciously possessed of the facts.

Here is the whole case.
The opinion is not well received by the bar,
and cannot heal the division in the Society of Friends.
The appeal is to the gentlemen of the bar,
that the decision ought not to stand as a precedent,
to be relied on in cases hereafter to be tried.`"

The occurrence of this disruption of New England Yearly Meeting,
in the outrageous manner in which it was brought
about by the leaders of the Gurney party,
and sustained by the bulk of the members,
plainly evinced that by a large portion of the latter, as well as by the former,
our great principle of the necessity of waiting on the Lord himself,
in the secret of the soul, for the enlightening directions of his Holy Spirit,
had been practically laid aside--the genuine result of the novel teachings--and
that an overweening confidence in certain influential men had taken its place.
The result was indeed deplorable,
in the blinding of the eyes of many who had formerly
seen and known and walked in the way of Truth,
and in the success thereby given to the efforts of the great enemy of all good,
to scatter that goodly heritage which had been so
highly favored as a flock of the Lord`'s own pasture.
