== Chapter XII.

Development of the Gurney Schism Within Ohio and Baltimore Yearly Meetings.

For several years, within the compass of the Yearly Meeting of Ohio,
the state of feeling between the advocates of the new views on the one hand,
and the adherents of the ancient principles of the Society on the other,
had been so decidedly antagonistic,
that a separation would undoubtedly have been the result, much earlier than was the case,
had it not been for the earnest endeavors of the clerk of that Yearly Meeting,
aided by some others, disciples of the middle party of Pennsylvania and New Jersey,
to keep all together and patch up a false peace.
These endeavors, however, not being corrective of the disease, but merely palliative,
though successful in retarding the outbreak,
bore no convincing power effectually to allay the excitement,
or alter the determination of the innovating party
to accomplish their purpose of obtaining control,
whenever a favorable opportunity should occur.

Their avowed grievance was, that the main body of the Yearly Meeting (or,
as they termed it,
the clerk and his party) resisted their wishes for Ohio Yearly
Meeting to identify itself with the "`Larger Body`" in New England.
On this account, their favorite measure involved a change of the clerk; as they hoped,
if they could accomplish that, to have power,
either to carry over the whole body with them to the desired recognition,
as had been done in Indiana and North Carolina,
or to produce such a separation as should, by the fallacious plea of having the clerk,
etc., on their side,
assume an appearance which would insure for them
a prompt acknowledgment by other Yearly Meetings.
They therefore, for several years,
stoutly opposed the reappointment of Benjamin Hoyle as clerk,
paying little regard to his endeavors to pacify and
conciliate them by a vacillating half-way course,
so long as he resisted their call for a definitive
recognition of the Gurneyites of New England.
The result was, that for a period of eight years,
there were only two instances in which the representatives were
able to make a united nomination for clerk of the Yearly Meeting.
They were under the necessity of reporting that they could not agree;
and the Yearly Meeting, by common consent of all parties,
uniformly pursued the practice which had previously obtained in the Yearly
Meeting of Philadelphia under like circumstances during the Hicksite separation,
of continuing the old clerks at their post until
others could be regularly nominated and appointed.
The Women`'s Yearly Meeting, during this time,
had a clerk of opposite sentiments to those of the clerk of the men`'s meeting,
who retained her position on the same principle under similar difficulties.

In the Yearly Meeting of 1845, both the epistles coming from New England,
where the separation had recently taken place, were read;
but no further step was then taken towards a recognition of either body.
In 1846, no epistles were read from either of them,
and two Friends from the "`Smaller Body "`were even requested to leave
the meeting--"`for the purpose of avoiding discussion`"--as was alleged.
The clerk on that occasion expressing that "`he was willing`" they should do so,
they absented themselves from the meeting,
rather than be the apparent cause of great dissension.
In 1853, a member of the "`Smaller Body`" being again present,
four sittings of the Yearly Meeting were consumed in debating whether he should be excluded;
but he retained his seat, in accordance with the wishes of a large number of Friends.
We see by this, what a sorrowfully divided condition the meeting presented.
The clerk meanwhile held the controlling power,
and would do nothing to recognize the "`Smaller Body`" of New England,
nor yet to satisfy the Gurney party, whom he knew well to be innovators and seceders.
He would only endeavor to coax them by apparently insincere or compromising professions.

On the fourth of the ninth month, 1854, the Yearly Meeting assembled, as usual,
in the great meetinghouse at Mount Pleasant.
William and Charles Evans from Philadelphia, and Eliza P. Gurney,
widow of Joseph John Gurney, were present; as was also Thomas B. Gould, a minister,
from Newport, Rhode Island, with his companion,
members of the "`Smaller Body`" of New England.
T+++.+++ B. Gould had presented his minute or certificate to the
Meeting of Ministers and Elders on the previous Seventh-day,
where it was thought best not to read it, the clerk, Joseph Edgerton,
more or less under the influence of the temporizing party,
proposing and favoring this course.
The minute of T. B. Gould`'s companion, who was not a member of the Select Meeting,
was placed upon the clerk`'s table of the Yearly Meeting
while the meeting was engaged on the subject of credentials,
but no notice was taken of it by the clerk.
The Gurney party soon raised objections to these two Friends sitting in the meeting;
and after saying a great deal with a view of excluding them,
they commenced to call upon them to produce their credentials, or, if they had none,
to make a verbal statement of the cause of their being present.
T+++.+++ B. Gould upon this rose and said,
"`that he had come amongst them under a solemn and convincing sense of religious duty,
the concern having long rested with much weight upon his mind,
and this time having been clearly pointed out as the proper one for coming,
after having turned the fleece again and again,
and proved the religious rectitude of the concern.

And not only so,
but that his concern had been fully united with by Rhode Island Monthly Meeting of Friends,
of which he had always been a member; and he had been furnished with its certificate,
and the endorsement of Rhode Island Quarterly Meeting, duly signed by the clerks;
which Quarterly Meeting, after a careful investigation of the whole subject,
had been decided by Philadelphia Yearly Meeting to be the true
and regularly established Rhode Island Quarterly Meeting of Friends.
That these certificates had been duly presented to
the Select Yearly Meeting the day before yesterday,
but that owing to the manifestation of a similar
spirit of opposition to what had been seen here,
and, as he supposed,
from a feeling of tenderness in the clerk toward those of opposing sentiments,
they were neither read there nor introduced here.
However, "`Friends,`" said he, "`you may rely upon it, that,
after what has been said here, I would not remain in this house another moment,
if I had not felt it my duty, in the first place, to come,
and in the next place to remain in this meeting,
and if I did not also know that I have a right so to do.
So that I wish it to be distinctly understood,
that I do not consider myself as an intruder,
neither did I ever intrude myself into any place where I had not a right to go.
I do not ask for the privilege of sitting here as a favor, I claim it as a right.`"

He went on to show that the Monthly Meeting of Swanzey,
which had issued the minute for his companion,
was the genuine meeting of Friends at that place, and that the others separated from it,
as they did also from the Yearly Meeting; adding: "`But, Friends,
they +++[+++the "`Larger Body]
are a body of separatists from the order and discipline,
as well as from the principles and doctrines of Friends.
By these I freely acknowledge that I have been disowned; but I never was, in any manner,
out of unity with or disowned by Friends, as so often stated in this meeting,
nor until after the separation had occurred from Rhode Island Quarterly Meeting.`"
Hereupon the most clamorous of the Gurney party began to say,
in different parts of the house,
that they were fully satisfied that it would never
do to discuss this question in that public manner.
"`Friends,`" said they, "`we are losing ground; let us say less,
and act more firmly;`" and at once they turned upon the clerk,
urging him to make the meeting select,
and rebuking him sharply for going on with the business as far as he had done,
with those strangers present.
Whereupon the clerk attempted to clear himself from the alleged accountability,
plainly showing that he did not desire their presence at all;
but the Gurney party would not accept his excuses,
and cried out that he had previously and wholly disqualified
himself for acting as clerk.

The clerk endeavored further to clear himself, and said again and again: "`Friends,
you can make the meeting as select as you please, and I will not object to it,
provided you do so consistently with our principles,
and do not appeal to the civil magistrate.`"^
footnote:[Letters and Memoirs of T. B. Gould,
page 366. How the clerk expected this to be accomplished, does not appear,
unless it was an invitation to them to take T. B. Gould out of the meetinghouse.]
This was contemptuously rejected, and he was vehemently charged with treachery,
in favoring or allowing the presence of the two strangers.
T+++.+++ B. Gould now thought it right to say,
"`that the clerk was in no way responsible for their presence;
that he had been scrupulously careful not to give them the least encouragement;
and that it would be great injustice to him to charge him there with;
that as regarded himself, he had no wish to deceive any one,`" etc.
The clerk then said: "`Friends,
you must see how that the individual has assumed
the whole responsibility of his being here to himself.`"
This, however, was by no means correct;
for T. B. Gould had expressly referred the responsibility
to Him who had laid upon him the concern to come thither,
and who, he believed, required him to remain,
and made him willing to suffer all this obloquy for
the sake of His precious name and cause.
After a time, the representatives were directed, as usual, to meet, and, if way opened,
agree upon names to propose to the next sitting for clerk and assistant;
and the meeting then adjourned to the next morning.
During the interval, nothing was said to T. B. Gould by any one,
to induce him to absent himself from the future sittings.
But on the contrary,
many Friends manifested their unity with him in an unmistakable manner.

After the close of this first sitting, the representatives convened as usual;
but it soon appeared that twelve out of the forty-two were resolutely
bent on proposing new names for clerk and assistant clerk.
Two others were understood to be of the same party,
though not at first openly uniting in the measure.
The remaining twenty-eight, who did not approve of the change, nor of the names proposed,
resisted this disorganizing step,
knowing it would give the control to the Gurney faction; but they were unable,
as on previous occasions, to carry forward any united nomination,
the fourteen others declining to join them therein.
There was no way left, but, as before,
to report to the Yearly Meeting their inability to
agree on any names to offer for its consideration.
The next day, after the opening of the meeting by the acting clerk,
one of the twelve Gurney representatives arose and said,
that the representatives had conferred together,
and a portion of them had agreed to propose the name of Jonathan Binns for clerk.
Whereupon another Friend (Nathan Hall) informed the meeting that he had been directed,
on behalf of the representatives,
to report that they were unable to agree in bringing
forward any name for clerk or assistant.

A clamorous expression of approval of the nomination
of Jonathan Binns now took the place,
for awhile, of any solid consideration of the regular report.
The acting clerk informed the party that their proceeding was altogether out of order,
contrary to the discipline and usage of the Society,
and to the course pursued by that Yearly Meeting for several years past.
Much noise and confusion were made by these persons, who urged Jonathan Binns,
and another proposed by them as assistant, to go to the table and take seats;
all which was decidedly objected to by a large number of Friends.
The clerk, in conformity with former usage, though perhaps somewhat hastily,
without waiting the direction of the meeting, made a minute,
stating that the representatives not having been able to agree,
the former clerk and assistant were continued in their respective stations.
This minute was sustained by a large expression of unity;
while the nomination of J. Binns was considered by
many as not regularly before the meeting,
and therefore not entitled to receive consideration.
Those advocating this disorderly proceeding were warned even by some of their own party,
that such a measure, if persisted in, was an act of separation from the Society,
and were earnestly entreated to desist therefrom.
But they persisted in their attempt to divide the Yearly Meeting;
and eventually their nominees were induced to proceed to the table,
obtrude themselves into the yet vacant seat of the assistant clerk,
and make a minute of their own fictitious appointment.
By this time the afternoon was considerably advanced, and the Yearly Meeting adjourned,
by a regular minute made by the clerk, to 10 o`'clock the next morning.

The separatists remained behind in the house, professing, with their new clerk,
to hold Ohio Yearly Meeting; and after a time adjourned to 8 o`'clock in the morning.
The women who were of the same party met at the same hour,
their clerk having made the minute of adjournment to such
hour as the men`'s meeting might adjourn to.
As it happened, this suited both parties;
for those who were desirous of adhering to the ancient
principles and practices assembled at ten o`'clock,
according to the adjournment of the Men`'s Yearly Meeting;
and finding that their clerk was among the separatists, they appointed another,
and went on with the regular business of the Women`'s Yearly Meeting.
Eliza P. Gurney had identified herself with the separatists,
and William and Charles Evans were uniting with and encouraging B. Hoyle`'s measures.^
footnote:[The printed Journal of William Evans (p.
609-10) gives an account of this Yearly Meeting.
A stranger would rise from its perusal,
totally ignorant of the ground of the dispute respecting clerks,
on which the separation turned.
Indeed, in the whole of that voluminous work,
though many things are mentioned respecting the Hicksian secession,
yet in regard to the more modern schism,
far more extensive and insidious in its spread over the Society,
no distinct details are given,
nor does the name of J. J. Gurney or of John Wilbur appear in any of its 700 pages.
His remarks on separations (pp. 489, 547, and 585) are exceedingly weak and untenable,
implying that the members would not be justified in endeavoring
to sustain by separation the true Society of Friends,
however corrupt the nominal body might become.]
It was supposed by some present,
that about one-third of the members in attendance seceded from the men`'s meeting.

This meeting, after the secession, proceeded with its usual business,
and adopted a document,
explanatory of the extraordinary circumstances which had occurred,
for circulation among its members and in other parts of the Society.
In the last sitting, toward the close, Thomas B. Gould rose,
and after some remarks respecting the Epistles which
had been addressed to other Yearly Meetings,
and the probability that some of them might be rejected
by the bodies to which they were addressed,--which,
however, would be no necessary cause of discouragement,
considering the state of those bodies--he went on to remark,
"`that we were living in a dark and cloudy day;
that the spirit of the world and of the age had so blinded the eyes and
hardened the hearts of many up and down amongst Friends as a people,
that it seemed as if they would not or could not believe,
although a man should declare the Truth unto them; that this was a spirit of unbelief in,
and departure from the Truth; that such was the blindness which had happened unto Israel,
that it seemed to him there was great need,
even for some who had been eminently gifted and deeply experienced,
to be so humbled under the mighty hand of the Lord,
as to availingly put up the petition for an increase of faith;
that so they might be able to adopt the language, '`Lord, I believe,
help thou mine unbelief!`' and that their eyes might be opened
to see the way and work of the Lord in this our day and time,
which was a dark and stormy time.

"`But the darkness and the light were, in a sense, alike unto him;
he had his way in the sea, and his path in the deep waters,
and his footsteps were not known,
except to such as were made willing to follow him even to prison and to judgment;
that clouds and darkness were round about him,
but righteousness and judgment were the habitation of his throne.
He did verily believe that it was at least by His permission,
that things were being so shaken; and if he was not mistaken in his feelings,
the language was applicable, '`Yet once more I shake not the earth only,
but also heaven;`' and that everything that could be shaken would be shaken,
that that which was immovable might remain; yea, that He would overturn, overturn,
overturn, until He shall come whose right it is to rule and reign over all;
whose power was in itself over all the powers of darkness, and who would yet,
he firmly and renewedly believed, be magnified in the sight of those who had,
in different degrees, become forgetful and distrustful of his power.
But it was better to trust in the name and power of the Lord,
than to put confidence in princes;
for the Lamb and his believing followers would have the victory in the end,
and such as rejected Him, and turned back from following him,
would be confounded and brought to naught.`"

He added some further weighty expressions of the same character,
and a quiet solemnity afterwards pervaded the meeting.
It is evident from the foregoing statement, that though this separation^
footnote:[The Letters of T. B. Gould, from page 353 to page 373,
give a graphic and interesting account of the circumstances attending that separation.]
had cleared out from Ohio Yearly Meeting the main
body of the original Gurney party there,
yet a prevailing element of weakness was left--an element which,
through the influence of the clerk,
and a few other prominent members more or less attached to the "`middle party,`" rapidly
increased and prevented it from assuming its right position in the Truth--prevented
it from bearing a practical testimony on behalf of those its brethren who were suffering
for "`the same testimonies`" that itself was professing and many of its members sincerely
endeavoring to uphold--prevented it from pursuing the straightforward and manly (not
to say Christian) course,
of holding forth the right hand of fellowship toward those in New
England and New York Yearly Meetings who had given up their names
to reproach for the cause of the ancient faith of the Society.
It was owing to this influence--greatly promoted as it was by an inordinate
confidence in certain leading individuals in Philadelphia--that thenceforth,
although the original and open Gurneyites had now left them,
Ohio Yearly Meeting (like that of Philadelphia) proved itself entirely inadequate,
as a body, to the exigencies of the times,
or the duties which its profession of sound doctrine entailed upon it,
for the sustaining of the ark of the Lord`'s testimony in a day of deep revolt.
It had not the courage to take any effectual steps towards the
practical or disciplinary suppression of the doctrinal heresy,
or towards the recognition of the "`Smaller Bodies,`" either of New England or New York,
and gradually drifted into open opposition to any such course.
Yet it is very clear,
that if Philadelphia Yearly Meeting had set the example in such a course,
Ohio would undoubtedly have followed it.

On the other hand,
those engaged in making this secession promptly identified
themselves with the "`Larger Body`" of New England,
and with the promoters of innovation in other parts of the Society,
and were at once acknowledged as Ohio Yearly Meeting
by all the other bodies controlled by the same party;
including even the Yearly Meeting of London,
notwithstanding the irregularity of their proceedings
and the comparative smallness of their numbers.
In the case of New England,
London had ostensibly decided to own those who had the old
clerk and the preponderance in respect to numbers;
but as this rule would not be found to answer the
purpose of the party with whom they fraternized,
in the case of Ohio, the criterion was changed, and practically,
though not for the same purpose, the language of Jehu was adopted, "`Who is on my side?
Who?`" Indiana Yearly Meeting soon took into consideration
the weakness and small numbers of their brethren in Ohio,
and turned over to them one of their Quarterly Meetings,--that of Alum Creek.
The Yearly Meeting of Baltimore was one of the three bodies which, as we have seen,
were prompt to recognize the Gurney party of New England in the autumn of 1845;
which they did without any investigation into the real merits of the case.
Baltimore Yearly Meeting at that time consisted of the three Quarterly Meetings of Baltimore,
Nottingham, and Dunning`'s Creek, and the Half-year`'s Meeting of Virginia.
It had been very small since the Hicksite secession of 1828,
but had been recognized by the other Yearly Meetings at that crisis,
on the ground of principle, without any regard to the smallness of its numbers.
Unhappily most of the members had, since that time,
been drawn in with the multitude to sanction the views and ways, and promote the success,
of J. J. Gurney`'s party; yet in Nottingham Quarter there was quite a number of Friends,
who were aware of the schismatic nature of the new movements, and religiously concerned,
according to their measure of ability, to withstand them.

When the two epistles from New England were presented
to Baltimore Yearly Meeting in the autumn of 1845,
the clerk read to the meeting the one from the "`Larger Body`"
(which had the usual signatures of clerk and correspondent),
along with those coming from other places.
He afterwards informed the meeting that there was another paper,
purporting to be an epistle from New England Yearly Meeting, with another signature;
whereupon a committee was verbally appointed to examine the paper,
and report whether it was suitable to be read.
This committee withdrew, and shortly returned,
reporting that it contained certain charges against individuals and the Society,
and was unsuitable to be read;
adding that as the regular epistle from New England had already been read in the meeting,
the document in question, in their opinion, ought not to be read.

Thus they took upon themselves to settle the whole question; and the Yearly Meeting,
with a large preponderance of voices, adopted their view of the case,
and set aside the "`Smaller Body`" as if it had been
clearly convicted of a secession from the Society.
Some expression was made of an opposite sentiment,
and it did appear that the committee had laid the meeting
under an additional obligation to read the epistle,
from having disclosed, or professed to represent, a portion only of its contents,
and this in their own way.
But the general sentiment of the meeting was in favor of the report,
and the Yearly Meeting was carried over to the ranks of the new party;
and in order to rivet their action on the component parts of the Yearly Meeting,
a committee of thirteen men and fifteen women was
appointed to visit the subordinate meetings,
and "`render them such advice and assistance as necessity may require,
and ability be afforded to impart.`"

Thus the individual members, as integral parts of the Yearly Meeting,
became of course complicated in the connection established
with the "`Larger Body`" of New England,
and in its support in the departure from primitive Quakerism,
and its efforts to set aside and disown all those who saw their sandy foundation,
and were concerned to point it out, and to adhere to first principles.
The main opposition to this course of the Yearly Meeting
was from members of Nottingham Quarterly Meeting,
in which there was a strong feeling adverse to the degenerate
tendency so quickly spreading over the Society.
A watchful care was now maintained in that quarter,
to keep their own minutes at least clear of entries indicative of unity with those measures,
or of owning the "`Larger Body`" of New England in the way
of accepting certificates or other documents issued by them.
And in maintaining this care,
it seemed to them that at times a hand unseen was at work to help them.

But these were trying times,
and great watchfulness was required on the part of clerks and others,
to move along with due care and circumspection;
for there was still an element in the meeting that
was aiming to lead it into the popular current.
For this purpose, on one occasion when the Yearly Meeting`'s committee was present,
an effort was made by a portion of the members to
change the clerks of the Quarterly Meeting,
so as to obtain the control for that party; but it met with no success;
for after the nomination was made,
there was so evident an absence of approval--such a silence over
the meeting at large--that even one of the nominees declared that
it was very evident they were not acceptable to the meeting;
whereupon the subject was referred back to the committee with an addition,
and at the next meeting the old clerk and assistant were reappointed.
Thus Nottingham Quarterly Meeting travelled on, in trial and conflict, for some years,
the sound Friends having the ascendency,
but with a considerable mixture of such as were disposed to favor the new views,
and under a pressing sense of endeavors made from time to time
for their subjugation to the course pursued by the Yearly Meeting.
It seemed to some of these that they were almost surrounded by snares,
and they saw no way of escape as yet,
nor any presentation of deliverance which they could
recognize as of the ordering of Truth.
They continued to attend their Yearly Meetings, though in much heaviness,
and returned home without relief.
But Israel`'s unslumbering Shepherd was still watching
over those who truly confided in Him,
and in his own time he opened a way for their deliverance.

As the time of holding the Yearly Meeting of 1854 approached,
these Friends became renewedly sensible of the perilous
position in which the Society was placed,
more prominently so from the recent occurrences in Ohio.
Under such circumstances,
the prospect of again attending the Yearly Meeting was fraught with solicitude,
and a concern was felt lest any might, through zeal,
put forth a hand unbidden to stay the tottering ark,
or lest there might not be that patient waiting, quiet enduring,
and firm adherence to a right course,
which might bring peace to the mind in the retrospect.
They did not feel at liberty to lay plans or make contrivances beforehand,
as to the course to be pursued,
but felt that they must leave the result to Him who is the way, the truth, and the life,
trusting that if it should please him to open a way for them,
he would show it to them and go before them.

The Yearly Meeting convened in Baltimore on the 23rd of the tenth month, 1854.
Several epistles were read from corresponding Yearly Meetings,
and a committee was appointed to prepare essays of epistles in return.
The clerk then informed the meeting that he had received
two epistles purporting to be from Ohio Yearly Meeting,
one signed by Benjamin Hoyle, as clerk, and the other by Jonathan Binns;
whereupon a committee of twelve was appointed to read the papers,
examine such evidence as might appear, and report to a future sitting what course,
in their judgment,
the Yearly Meeting should pursue in regard to those
epistles and the bodies from which they issued.
This committee was joined by thirteen women under similar appointment from their meeting.
The committee had two sittings, and prepared a written report,
in which fellowship was professed with that body
of which Jonathan Binns was clerk (the Gurney meeting),
and disunity with that of which B. Hoyle was clerk;
proceeding to charge the members of the latter meeting with being promoters of disorder,
in opposing correspondence with another "`Yearly Meeting`" (viz.,
the Larger Body of New England),
and in encouraging "`disowned persons`" (members
of the Smaller Body) to sit in Ohio Yearly Meeting.
This report was signed by nineteen of the twenty-five members of the joint committee.
Six expressed disunity with it, but their voices were of no avail,
and it was laid before the Yearly Meeting on Third-day afternoon,
after the London general epistle had been read and disposed of.
The consideration of the subject occupied the meeting until dusk, when the clerk,
overruling the opposition to the measure, read a minute adopting the report.

Several voices were still raised against it, but a larger number in its favor,
and it was sent into the women`'s meeting.
The clerk of the men`'s meeting then read the epistle from the Gurney body of Ohio,
and it was referred to the Epistle Committee to be replied to.
Samuel Cope, from Pennsylvania, who was present, then rose,
and expressed himself in the following emphatic words: "`Well, Friends,
you have joined yourselves to that spurious body in Ohio,
of which Jonathan Binns is clerk.
I have no unity with it.
I believe it may be said of you, as it was said of some of old,
Ephraim hath joined himself unto idols; let him alone.
But Judah shall cleave unto her King.`"
A short pause ensued of deep silence,
after which the clerk soon read a minute of adjournment.
When he sat down, William Waring rose and said:
"`Are there those in this Yearly Meeting who feel bound to the law and to the testimony?
Can these do otherwise than remain on their seats?
Can these do otherwise than sit together and feel together?`"

The clerk, and those on whose part he was acting, then withdrew,
and a small number remained quietly in the house until the Committee on Epistles,
which had remained for a time, also withdrew; when, after a little pause,
it was thought best to ask the women Friends, similarly circumstanced,
to come in and sit with their brethren.
A Friend going accordingly to see how they were faring,
found six female Friends sitting in profound silence, who, on being invited,
joined the men in solid deliberation.
A precious covering of good was felt to spread over this little company,
and they were reminded of the saying of our Saviour to his disciples,
"`Ye are they who have continued with me in my temptations,`" etc.
In the sweet owning which seemed to be unmistakably evidenced,
it was deliberately and unitedly concluded that it would be right to endeavor
to sustain Baltimore Yearly Meeting on its ancient ground,
irrespective of those who had now joined the schismatic bodies.
This conclusion was united in by all present,
including four friends from Philadelphia Yearly Meeting, viz., Samuel Cope, Moses Bailey,
Cyrus Simmons, and David Heston.

The clerk, and those identified with him, having withdrawn with the books and papers,
it became necessary to appoint another clerk,
and William Waring was requested to act in that service
for the remainder of the Yearly Meeting.
The women retired to their own apartment, and likewise appointed a clerk,
and both meetings adjourned to the next morning, to meet in a private house,
as the meetinghouse would be occupied by the seceded body.
At subsequent sittings, they addressed epistles to several Yearly Meetings, and,
in consideration of the smallness of their number
and the responsibilities thus devolving upon them,
it was concluded to invite the Yearly Meetings of Philadelphia and Ohio to appoint committees,
if way should open for it, "`to sit with this Yearly Meeting next year,
and join us in considering the propriety of discontinuing it,
and joining the members to Philadelphia Yearly Meeting.`"

A minute was also adopted,
explanatory of the extraordinary circumstances in which the Yearly Meeting was now placed,
through the schismatic course of false brethren;
which minute contained the following expressions, among other remarks on this crisis:

The particulars of the lamentable difficulties in which the various parts
of our Society have been involved during a past series of years,
are so generally known,
that we need only briefly to refer to them to make our present
position understood by the Society at large,
and by coming generations.
During a series of years,
doctrines and practices have obtained currency in parts of the Society of Friends,
that are an obvious departure from what they have held and observed in ancient times;
and there has been a diversity of sentiment among concerned members,
as to the proper course to be pursued by meetings and individuals
towards those who may have introduced or promoted those innovations.
In different places the dissension growing out of this state
of things has resulted in the separation of Yearly,
Quarterly, and other subordinate meetings of Friends.
Throughout these separations, it may be observed, there is one portion who are generally,
if not uniformly,
identified with an adherence to the ancient doctrines and usages of +++[+++the]
Society.
And finding the body claiming to be Ohio Yearly Meeting, with B. Hoyle as clerk,
in this connection, we own it, have fellowship with it,
and with it continue our correspondence.

They did not at that time suppose that either Philadelphia or Ohio Yearly Meeting would
become so thoroughly weakened by submission to the temporizing measures of the "`middle
party,`" as to decline correspondence with them from motives of slavish fear.
The meeting, having finished its business, adjourned on Fifth-day, the 26th of the month,
to meet again at the usual time the next year, at Nottingham, if so permitted.
This assembly, it must be acknowledged,
was unprecedentedly small for holding a Yearly Meeting;
there being only six men and six women, members thereof, in attendance,
besides the four friends above mentioned from Philadelphia Yearly Meeting.^
footnote:[It must, however,
be borne in mind that this small number present at that time in Baltimore,
was acting on behalf of many Friends who had remained at their homes,
composing a large portion of the members of Nottingham Quarterly Meeting;
of whose four representatives, three were associated in these transactions.
It was thought that about one hundred friends attended
the Yearly Meeting the next year at Nottingham.]
If they had been engaged in organizing or instituting a new Yearly Meeting,
it would have been obvious that their numbers were not sufficient
to entitle them to act in so responsible a capacity.
But this was not the case.
They were only engaged, under a solemn conviction of duty,
in endeavoring to sustain Baltimore Yearly Meeting of Friends on its original ground,
against the great defection into which most of its members had been carried,
and thus to raise a standard there for the primitive principles,
round which the honest-hearted might rally,
who cherished a concern not to be swept along with that defection.
And they confidently looked towards being united, in a short time,
to Philadelphia Yearly Meeting, as one of its constituent branches.

This was under the impression that, should way open for such a course,
before it could be consummated,
Philadelphia Yearly Meeting would probably be relieved
from the confusion in which it was then involved.
Both this and that would undoubtedly have occurred,
if Philadelphia Yearly Meeting had continued to maintain a firm and consistent attitude,
in living faith, as the Truth required at its hands.
But, though "`armed and carrying bows,`" it "`turned back in the day of battle,`"
and left all the small bodies of Friends to get along as they could.
Samuel Cope afterwards acknowledged in Philadelphia Yearly Meeting,
with reference to this little company in Baltimore,
that "`he did not know that he had ever attended a meeting,
where the owning presence of the Head of the church
was more eminently manifested,`" or to that effect.
He also attended the Yearly Meeting held at Nottingham three years afterwards,
in company with his wife.
It would thus appear that at that time he owned them.
But how sorrowful, that some such eminently gifted servants of the Lord,
after seeing so clearly the apostasy, and testifying so valiantly against it, as he did,
should eventually, under the specious delusions of the middle system,
which they once saw clearly through,
and under the weakening influences of a continuance in its mixed atmosphere,
have lost their testimony for the Truth, and the power of standing upright against error!

Yet Philadelphia Yearly Meeting, in 1855,
overlooking the principles on which it had acted in the case of
the Hicksian separation in Baltimore in 1828 (see Vol.
I, chap.
4) and under the pressure of the Gurney and middle parties,
with the clerk at the head of the latter,
and threats of a separation on the part of the former,
declined to accept a correspondence with this small company,
or to accede to their request of a committee to consider of their brotherly proposal,
or to own them in any way whatever.
So palpable was the inconsistency of the middle party
in thus casting away this little company in Maryland,
that they were even taunted with it in the Yearly Meeting by some on the Gurney side.
It was firmly opposed by many sound Friends,
who could not bow the knee to the new system--some
of whom have since gone to their everlasting rest.

Epistles had been addressed to Philadelphia Yearly Meeting
by each of the bodies in Ohio and also in Maryland,
claiming its recognition.
The question produced much excitement, and very long and painful discussions,
in the Yearly Meeting of Philadelphia of 1855.
The clerk, William Evans, having already identified himself,
at the time of the separation in Ohio, with that body of which Benjamin Hoyle was clerk,
composed of the sound members mixed with and largely
controlled by the compromising party,
he was of course resolute against any recognition of the Binns Meeting;
and in this way the same compromising party united with the sound members of
Philadelphia Yearly Meeting in sustaining the position of that body in Ohio,
which was still standing professedly, though falteringly, for the ancient doctrines;
and thus the Gurney party were put to a disadvantage in their strenuous efforts
to prevent the recognition of the Hoyle body by Philadelphia Yearly Meeting.
But when the question came up afterwards respecting the separation in Baltimore,
no such element of weakness or disadvantage for the Gurney party appeared;
inasmuch as the middle party were then willing to sacrifice the "`Small
Body`" there (with which the clerk had not already identified himself)
as a peace-offering to the highly excited feelings of the Gurney members.
The following very careful account of the deliberations
in each of these two cases on that occasion,
was given in The Friend.^
footnote:[Vol.
28, p. 262.]

The epistles from London, Dublin, and New York having been read,
the clerk informed the meeting there were two epistles on the table,
each purporting to come from Ohio Yearly Meeting,
and it would be necessary for it to decide which should be read.
After a short time of silence,
a very general expression in favor of reading the epistle signed by B. Hoyle took place.
There were several, numbering, as we are informed, between twenty-six and thirty,
who opposed the reading of that epistle; only one, however,
expressing the desire to have the one signed by Jonathan Binns +++[+++the Gurney epistle]
read,
and five expressing the belief that the meeting for which J. Binns
acted as clerk was the true Yearly Meeting of Ohio.

The main objection urged by the greater part of those who
opposed the reading of the epistle signed by B. Hoyle,
was, that a decision in favor of the meeting for which he acted,
would cut Philadelphia Yearly Meeting oft from the great body of the Society,
and therefore the whole subject ought to be postponed,
and the meeting defer coming to any conclusion on it.
Some of those who objected to the reading of this epistle, stated their belief,
that the meeting of which B. Hoyle was clerk, was the legitimate Yearly Meeting,
but they were in favor of a postponement.
Three times the judgment of the meeting was clearly manifested,
that the epistle signed by B. Hoyle should be read;
and each time the clerk rose to read it, when, as he began, he was interrupted,
and he patiently waited until all had the opportunity of relieving their minds.
It was a trying circumstance that all the members
could not see alike on this important subject;
but the dissent from the judgment of the great body
of the meeting was by comparatively few,
and there appeared no probability of delay producing any good effect,
as the circumstances of the separation in Ohio could not be changed by time,^
footnote:[How did this reasoning accord with the
clerk`'s position in the Yearly Meeting of 1850,
when he so earnestly exhorted Friends to a delay of judgment in regard to New England?
And how can we reconcile it with the readiness manifested by him in the afternoon sitting,
to recognize that body in Baltimore which he knew
had united with the schismatic meeting in Ohio,
rather than do anything to encourage the little company in Maryland
who were endeavoring to sustain that Yearly Meeting on the ancient
ground until they could be incorporated with Philadelphia?
It is well remembered by many, how contemptuously he designated this small company.]
and it was incumbent on the meeting, under right authority,
to come to a decision for itself,
without reference to the action of other co-ordinate bodies,
to acknowledge the true Yearly Meeting of Ohio, and so far show its sympathy with it,
in its peculiar trials,
and to express its disapprobation of the course pursued by those who separated from it.
The clerk having stated it to be the judgment of the meeting
to have the epistle signed by B. Hoyle read at that time,
after a sitting of near five hours, it was read, and the meeting adjourned.

+++[+++Afternoon sitting]
The meeting being informed there were two epistles,
each purporting to come from Baltimore Yearly Meeting, one of which,
coming from a small number, contained a minute,
suggesting the consideration of their being united to Philadelphia Yearly Meeting,
the question arose, which should be read.
Considerable contrariety of sentiment was manifested,
some expressing the conviction that,
as Baltimore Yearly Meeting had acknowledged unity
with those who had separated from Ohio,
it was identified with them,
and its epistles should be in like manner as theirs rejected,
especially as some of its members had left it on that account;
while others were of the judgment that the course pursued by Baltimore
did not invalidate its character as a Yearly Meeting;
that the separation of a part of the members from a Yearly Meeting ought not to be encouraged,
and therefore the epistle +++[+++of the Larger Body]
ought to be read.^
footnote:[It was afterwards conceded by an active member of the Gurney party,
that "`a large majority of those who spoke "`favored
the reading of the epistle from the Smaller Body;
but that the clerk was evidently determined that it should not be done.]
The latter course was finally adopted, the epistle being read,
and after reading that from North Carolina (none having come to hand from Indiana),
the meeting adjourned.
^
footnote:[The reader will please compare the above weak reasoning
(which appears to have been the ground on which The Friend reconciled
the rejection of the epistle of the "`Smaller Body "`of Baltimore,
in 1855) with the ground on which the Yearly Meeting acted in a similar case in 1828;
see Vol.
I, chap.
4]

Third-day morning, the 17th. The printed General Epistle from London was read.
The subject of preparing epistles to other Yearly Meetings was brought before the meeting,
and some Friends expressed the belief,
that under the trying circumstances in which the Society was at present involved,
it would be right not to address those Yearly Meetings that had
come to a different conclusion relative to the separation in Ohio,
from that of this Yearly Meeting.
The meeting, however, settled in the conclusion,
to address as usual the Yearly Meetings of London, Dublin, New York +++[+++Larger Body],
and Ohio; also, if way should open for it, those of Baltimore, North Carolina,
and Indiana; the latter epistles, if prepared,
to contain an affectionate remonstrance with those meetings respectively,
for the course pursued by them in relation to the separation in Ohio.
A committee to carry out this decision was then appointed.

Sixth-day morning, the 20th. Essays of epistles to London, Dublin, New York, Ohio,
North Carolina, and Indiana, being produced from the committee, they were read, adopted,
and directed to be signed and transmitted to the
meetings to which they were respectively addressed.
The committee reported that they were not united in preparing
an epistle to Baltimore Yearly Meeting at this time.
A few friends,
who had on Second-day objected to the reception of the epistle signed by B. Hoyle,
now objected to forwarding that prepared for Ohio Yearly Meeting;
and two or three expressed their dissent from the purport of part
of those epistles which were addressed to North Carolina and Indiana.
As the meeting was drawing to a quiet close, a friend,
who had repeatedly expressed his opposition to the
course pursued by it in respect to Ohio,
proposed that those who united with him in sentiment
should stop at the rise of the meeting,
and sit down in silence to feel together.
His friends, however, did not unite with him in the adoption of such a measure,
and at their urgent solicitation he withdrew his proposition.

The above quotation is characteristic of the cautions and calculating manner in which
The Friend was at this time accustomed to treat the subject of the difficulties.
The reader of it,
if ignorant beforehand of the cause of all that occurred
in the Yearly Meeting on this occasion,
would rise from its perusal with no better understanding of it than before,
and would need to be further informed that the contest
was not about mere names and clerks,
nor originally or exclusively in Ohio,
but had reference to some of the vital principles of our profession,
as held by our primitive worthies,
the continued maintenance of which was endangered throughout the Society.
Another prominent and characteristic feature of this editorial,
is that it cautiously abstains from anything which would indicate truly the strength,
either of the Gurney portion of the meeting,
or of those who advocated a firm and uncompromising course,
in opposition to the inconsistent, vacillating,
and time-serving policy of the clerk and middle party.
Both of those sections were at this time very formidable in Philadelphia Yearly Meeting,
but the clerk and his adherents held the control.

On the part of the Gurney members there was great earnestness,
and a degree of honesty of purpose according to their opinions, though in a wrong cause.
The friends who stood firm for the ancient faith and right order,
were at least equally earnest and honest in support of their conscientious convictions.
Both were sensible that the party which controlled the meeting
was not actuated by pure integrity of principle,
but by the policy of compromise, which had no convincing efficacy,
and was therefore submitted to only under a sense of oppression or compulsion.
In the spring of that year, Benjamin Cadwallader, of Bucks County, Pa., had issued,
in pamphlet form, A Letter to Friends of Philadelphia Yearly Meeting;
in which an affectionate and earnest appeal was made to his fellow-members
against the half-way course pursued of late by the Yearly Meeting;
showing its inconsistency with the truth,
and the dereliction of imperative duty which it involved.
He reminded Friends that,
though repeatedly importuned by other Yearly Meetings to
resume correspondence with the Larger Body of New England,
yet "`in our returning epistles +++[+++to those Yearly Meetings]
we have not at any time informed them why we discontinued it,
nor why we do not resume it.`"
And, on the other hand, he earnestly asked them:
"`Have we faithfully and conscientiously offered the salutation of Christian love,
and extended the right hand of gospel fellowship to those
who have been standing for the cause of their Divine Master,
but whose difficulties and discouragements have been such as, at times,
almost to cause their hands to hang down?`"
But such appeals had now but little influence with the leaders of the party of compromise.

The two next succeeding Yearly Meetings in Philadelphia presented
very much the same scenes of conflict without decision.
In that of 1856,
the reading of the epistles from the New York and Baltimore "`larger body`" meetings,
especially the latter, was objected to by many Friends;
but Samuel Bettle urged the reading of them all,
saying that it would be no compromise of principle to read them,
and that the question would afterwards come before us,
when the subject of replying to them should be brought before the meeting.
The Gurney party began to threaten separation if they were not read;
saying that the meeting would separate itself from the great body of the Society,
if we persisted in this course; and that if what was done last year (viz.,
the recognition of the meeting in Ohio, of which B. Hoyle was clerk) was not undone,
they would be compelled to sustain Philadelphia Yearly Meeting
in connection with the other yearly meetings of Friends.
The clerk then, after a time,
read the epistle from the New York city Meeting (the Gurney meeting),
and expressed his own willingness to have that from Baltimore city also read,
but that he believed the mind of the meeting was against it.
The meeting then adjourned.

In the afternoon, Samuel Bettle, to the surprise of many Friends,
who thought the matter settled, expressed his sentiment,
that the epistle from Baltimore city ought now to be read.
Many of the Gurney party promptly urged that this should be done.
But Friends stood firm to their previously stated objections,
and though many of the "`middle`" party wished it to be read,
the mind of Truth prevailed at that time, and it was again decided not to read it.
Several of the epistles from the Gurney Yearly Meetings had exhorted Philadelphia
Yearly Meeting to reconsider its course before it was too late,
and we should be cut off from the "`great body of the Society.`"
This furnished a handle for the party here to urge the annulling
of what had been done in reference to Ohio,
and the "`resumption`" of correspondence with the Larger Body of New England.
After a time the clerk proposed to refer the subject to the representatives for reconsideration.
This course, however, was not adopted.

On Fourth-day morning, Samuel Bettle rose and said,
he wished to relieve his mind of a burden he had borne for many years; adding,
in substance, as follows: "`That he was opposed to all separations and divisions;
he believed that all that had taken place,
from the days of the apostles to the present time, were caused by the evil one;
that he was opposed to the Hicksite separation,
and believed that patient labor and suffering would have been better;
that he was opposed to cutting off,`" etc.
A friend replied to him,
"`that so far as our aged friend was opposed to separations from the Truth,
he could fully unite with him;
but as his remarks would allow of a very different construction,
he believed it right they should be corrected;
that if such views as we had now heard had been carried out in former days,
there would have been no reformation from Popery,
neither would our early Friends have come out from among the professors of their day.`"

In the afternoon sitting, a document was read from London Yearly Meeting,
giving a statement of their having acknowledged fellowship with the meeting in Ohio,
of which Jonathan Binns was clerk (Gurney meeting),
accompanied with a declaration of doctrines,
made in the time of the Hicksian difficulties; which,
as was plainly stated in the meeting by Morris Cope,
did not cover the present ground at all,
especially as London Yearly Meeting had since that time
practically endorsed the unsound doctrines of J. J. Gurney,
in their printed memorial of him.
It was proposed by the Gurney party to send the London document into the women`'s meeting;
but this was objected to, and was not done.
On Sixth-day morning,
when the essays of epistles in reply to other Yearly Meetings were read,
the Gurney members in quick succession proposed the erasing of all allusions,
in our epistles, to Ohio Yearly Meeting,
and urged the meeting not to send any epistle to that meeting.
After they had spent themselves in these efforts, Friends united with the epistles,
and desired to have them signed and forwarded.
Samuel Bettle, Jr., then proposed that no epistles at all be sent this year;
which was supported by the Gurney party and many "`middle`" men;
but it was concluded to adopt the epistles and send them.

The meeting was now told that by this course we had cut
ourselves off from most of the Yearly Meetings in the world,
and those who wished to retain their rights in the Society at large,
were called upon by Israel W. Morris, and several others of that party,
after the clerk had read the closing minute, to come forward and sit together,
to feel after what would be best for them to do.
It was thought that about two hundred remained together,
who appointed a committee to propose a plan of action,
and then adjourned to meet in the Twelfth Street Meetinghouse the next morning.
The committee in the morning had no plan to propose,
and the assembly came to the conclusion,
that inasmuch as Philadelphia Yearly Meeting had regularly
adjourned for this year before any action on their part,
it was too late for them to attempt to sustain the Yearly Meeting,
and there was no probability that London Yearly Meeting
would sanction such a measure under those defective circumstances.
They, therefore, dispersed without taking any further steps.

In the year 1856, finding the increasing tendency among many to take a superficial view,
or rest in a voluntary ignorance of the errors of doctrine
propounded in the works and course of Joseph John Gurney,
and to insinuate that the objections to his sentiments were overstrained,
or without just foundation,
and the objectors actuated by a partisan or detracting spirit,
and needlessly disturbing the Society`'s peace,
the author of this work published in Philadelphia,
An Examination of the Memoirs and Writings of Joseph J. Gurney, in 145 pages,
8vo. Herein he endeavored to draw the reader`'s attention to the
substantial character of the principles of true religion,
as held and declared by our ancient Friends,
with various brief passages from their writings; and then,
by copious extracts from J. J. Gurney`'s publications, and from the Memoirs of his Life,
confronted with ample quotations from our early authors,
the proof was given of the great and fundamental difference between his
principles and the primitive and characteristic faith of the Society.
The work was widely disseminated,
but by this time such developments met with few ears to hear the truth of the matter,
and fewer hearts prepared to endure hardship and obloquy in the maintenance of it.
The path of error under popular leaders was more smooth and easy, and,
as in the days of the prophet, "`the people loved to have it so.`"

At the next Yearly Meeting (1857),
strenuous efforts were made by the Gurney party to accomplish
their purpose of changing the course of the meeting;
and they were partially successful,
probably owing in some degree to their formidable demonstration of the previous spring.
Great opposition was now made by them to the reception of the epistle from Ohio,
and a proposal was made to drop all the epistolary correspondence.
After much discussion, it was proposed by Samuel Bettle,
to leave the whole subject to a large committee,
"`to take time,`" and report to a future Yearly Meeting.
He urged the view, that "`time would do a great deal,`" forgetting that,
in stemming the current of schismatic error,
the more time is wasted in a neglect of known duty,
the more weakness is likely to increase, whether with individuals or the church.
A great deal was said on all sides,
but after two very trying sittings mainly occupied with the discussion,
with threats again made of separation on the part of the Gurney members,
the epistle from Ohio was finally read.
A committee was afterwards appointed,
to prepare replies to the three epistles which had been read, viz., London, Dublin,
and Ohio.
Israel W. Morris then called upon his friends to stop at the rise of this meeting,
cautioning them not to take any further part in the business of the meeting,
as it had identified itself with the Separatists (as he thought) in Ohio,
and had cut itself off from all the Yearly Meetings in the world,
the great body of the Society.

Quite a number of the party united with this proposal,
but Samuel Bettle and others earnestly exhorted him to withdraw it.
This he declined to do,
unless the meeting would consent to appoint a committee to unite with committees
of other Yearly Meetings in conference on the whole subject of our difficulties.
Friends could see no safety in such reference of the matter to
parties already implicated in bringing the schism upon the Society,
especially as we should be, in such a case, entirely overwhelmed by numbers,
and have no prospect even of a fair hearing of the true nature of the difficulties.
A long and earnest discussion ensued, some proposing one expedient and some another;
among which were the dropping of the correspondence not only with London and Dublin,
but with Ohio also, and the appointing of the representatives as a committee,
to consider and report to the next Yearly Meeting,
what could be done to harmonize and reconcile Friends in our own and other Yearly Meetings.
These two proposals were finally adopted, with the proviso,
that the committee should not interfere to unsettle
the conclusions already come to by the Yearly Meeting.
After a sitting of six hours, the meeting adjourned.
The minute made on the occasion was as follows:

Epistles from our brethren at their Yearly Meetings
in London and Dublin were received and now read,
as was also the printed London General Epistle.
In consideration of our present condition,
and the disunity that has appeared on some points,
particularly respecting our epistolary correspondence, after much time spent thereon,
and the general expression of sentiment by Friends, it was concluded to suspend,
for this year, an epistolary correspondence with all the Yearly Meetings;
and the subject of the great importance and the desirableness
of the restoration of unity and harmony,
both amongst the members of this Yearly Meeting and in the Society at large,
being brought into view, it was, under +++[+++after?]
solid deliberation,
concluded to refer its present condition to the representatives
of the Quarterly Meetings in this meeting,
as a committee, now appointed weightily to deliberate thereon, and, if way opens,
to propose any measures for this meeting to adopt,
which they may hope will contribute to the increase of unity;
to make a Report to this meeting next year; it being clearly understood,
that they are not to interfere with, or unsettle,
any of the previous decisions which this meeting has come to.

This Committee of Representatives,
after a whole year`'s time for consideration of the difficulties
which were the weighty subject of their appointment,
were not able to agree on any measure, except to report to the next Yearly Meeting,
that "`the way did not open to recommend the resumption of our
correspondence with other Yearly Meetings at the present time.`"
Thus did Philadelphia Yearly Meeting,
in order to avoid a separation threatened by those who had adopted the new principles,
weakly drift away,
not only from any epistolary correspondence with the "`smaller bodies`" of New England,
New York, and Maryland, but also from the "`larger body`" of Ohio,
which professed to be upholding the ancient doctrines,
and whose position the clerk had sanctioned by his
presence and cooperation at the time of the separation.
It has seemed to be right to relate these circumstances somewhat in detail,
that a clear understanding may be had of the entangled condition
of Philadelphia Yearly Meeting at this time,
and of the gradually increasing weight of unsoundness pressing upon it,
under which it eventually gave way,
and yielded to the temporizing measures of the middle party.
