== Chapter XIII.

[.chapter-synopsis]
* The Separation in Iowa, and the Mischief Effected There by the Middle Party.

We have already seen that Indiana Yearly Meeting, as a body,
promptly avowed its fellowship with the "`Larger Body,`" or Gurney Meeting of New England,
soon after the occurrence of the separation there in 1845.
Since that time,
constant efforts had been made to shut out from the members
of that very large Yearly Meeting the means of obtaining
correct information relative to the true causes of the schism.
But a small portion of the members residing in Iowa, in and near Cedar County,
who had gone thither within a few years from other parts of the Society,
and who had already more or less of a correct understanding
of the circumstances in which the Society was now placed,
were disposed to adhere to the ancient faith,
and to own fellowship with those who were suffering in New England
and elsewhere for their testimony to that ancient faith.

In the spring of 1853, a minister from Ohio settled in that vicinity, who had,
some years before,
expressed publicly in Ohio Yearly Meeting his unity
with the "`Smaller Body`" of New England;
and although, after his removal into Iowa, he kept himself very quiet on the subject,
yet this expression had been treasured up against him,
and circulated about where he went,
and it was determined by some in assumed authority in Indiana Yearly
Meeting (to which at that time Iowa was attached) to have him disowned.
One of the members making a social visit at his house,
entered freely into conversation with him on the affairs of the Society,
and after a while inquired of him what he would do,
in case a separation should occur in Ohio Yearly Meeting,
on the ground of the New England difficulty.
To this he replied that he should maintain the position he had taken,
even if he should stand alone.
This avowal was reported afterwards to the members of the Select Meeting,
and was by them considered and treated as a declaration
of disunity with Indiana Yearly Meeting.
He was visited on the subject, as a delinquent,
and though he was able to show them that what he
had said was by no means what they charged him with,
and was enabled to clear himself to such a degree that he
did not know but that they had dropped the matter,
yet some months afterwards they brought a charge against
him into the Select Preparative Meeting of Red Cedar,
without his being informed of the continuance of any uneasiness with him;
the tenor of which complaint was,
that he had manifested disunity with the body of Friends.

At Red Cedar Monthly Meeting, held in the sixth month, 1854,
he mentioned the course which the Select Preparative Meeting was taking against him,
and his own innocence in regard to the charge;
advising the members to endeavor to obtain a correct
knowledge of the difficulties in the Society,
and particularly mentioning the Philadelphia _Appeal for the Ancient Doctrines,_
and the _Report on the Division in New England,_ as setting forth the matter,
according to his apprehension, in its true light.
This was probably looked upon as an aggravation of his offence;
for at the next Preparative Meeting for discipline, held at Linn,
of which he was a member, a complaint was brought against him by the Overseers,
charging him with manifesting disunity with the body of Friends,
and owning fellowship with the Smaller Body in New England, whose meetings, they said,
were set up contrary to the order and discipline of the Society.
The subject being unexpected,
the Preparative Meeting was not prepared at once
to forward the complaint to the Monthly Meeting,
or to take it on minute, but verbally referred it to a committee of four Friends,
to investigate the cause of complaint and report to the next meeting.

At the Preparative Meeting in the eighth month, this committee made the following report,
viz.:

[.embedded-content-document]
--

We have given close attention to the subject,
have heard the Overseers in all they alleged against him,
and after conferring together were united in judgment,
that there is no just cause for such complaint,
or ground on which such charge can be sustained.
We find that he is firmly attached to the principles, the doctrines,
and testimonies of our Society, as upheld by Fox, Penn, Barclay,
and others of our standard writers,
and closely united to all our members in the different
Yearly Meetings who are concerned to support them.
We therefore think it best and right to dismiss the subject.

--

This report being satisfactory to the meeting, the subject was accordingly dismissed.
Yet, notwithstanding this decision of the Preparative Meeting,
that there was no just cause for the complaint,
the Overseers carried it to the next Monthly Meeting thus arbitrarily assuming the power
to set aside one of the very purposes for which Preparative Meetings were instituted,
and showing that the attainment of a predetermined purpose,
and not justice or gospel order, was what they aimed at.
In the Monthly Meeting,
notwithstanding the disorderly manner in which the complaint was introduced,
overstepping the rights both of the individual and of the Preparative Meeting,
three members of a committee of the Yearly Meeting being present,
undertook to approve of its reception,
alleging that extraordinary cases required extraordinary treatment,
and that sometimes it was needful, under peculiar circumstances,
to step aside from the well-known and beaten track of the Discipline!

A few members of Red Cedar Monthly Meeting united with them in support of the complaint,
yet the clearly expressed judgment of the meeting was against so irregular a proceeding;
but the clerk, under the influence of the new views,
and of the Yearly Meeting`'s committee,
recorded the complaint and made a minute appointing
a committee to treat with the friend thereon.
At this juncture the reception of the name of any friend for the appointment,
who was known to have sympathy for the individual, or was of his way of thinking,
was openly objected to,
and the committee was thus "`packed`" in accordance with
the wishes of the instigators of these irregular proceedings.
This minute appointing the committee was objected to by Friends,
as not being an act of the meeting, or according to its judgment;
but the clerk retained it, and proceeded with other business.
When the committee came to visit the friend, they were asked by him,
whether they were willing to hear the truth, and give due place to it;
to which they replied, "`Oh, yes, certainly we are.`"

He then declared that the charges brought against him were not correct,
and asked them whether,
in case he should prove to them that they were incorrect and false,
they would inform the Monthly Meeting so?
They answered promptly and decidedly, "`No, we will not; that is not our business;
we were appointed to find out thy disposition of mind,
and not whether the charges are correct or not!`"
And one of them added,
"`We admit thee has been quiet in regard to the New England difficulty,
but there is a heavy undercurrent running, which must be stopped!`"
At the next Monthly Meeting,
the friend thus complained against was requested to withdraw,
after the meeting was opened for business; but several of the members,
knowing that the case was before the meeting in a disorderly manner,
objected to his withdrawal,
under the consideration that if the meeting allowed him to withdraw,
it would in effect give countenance to this irregular proceeding.
They took the ground that the clearly expressed sense and judgment of
the Monthly Meeting had been against the charge being placed on minute,
and therefore they could not consent to his leaving the meeting.^
footnote:[This is to be regretted, inasmuch as,
whether irregularly introduced and pressed, or not,
the complaint had been recorded on the minutes of the Monthly Meeting,
and a committee appointed to visit him, which he had received.]

The Friend, however, himself proposed to leave the meeting,
after the clerk should have read the minute in his case,
and the committee should have reported, in case their report did not exonerate him,
and propose the dismissal of the complaint;
for he was willing that the meeting should have an
opportunity to decide the matter in his absence,
as usual.
But while he waited for the meeting to decide upon this proposal,
one in the station of a minister proposed that the meeting should adjourn.
This was united with by one or two, and though objected to by several others,
the clerk soon prepared a minute, and stated that he had it in readiness,
if Friends could agree on a time and place to adjourn to.
It being now manifest that he was determined not
to act in unison with the solid sense of the meeting,
but to thwart it under the influence of a party, for a corrupt, and irregular,
and oppressive purpose,
those holding the ancient doctrines took the matter into their own hands,
and before he finished his minute of adjournment,
appointed another member to serve the meeting as clerk in his place.
The new clerk soon read a minute,
stating in a few words the disqualification of the former clerk, and his own appointment;
after which the former clerk read his minute of adjournment,
and taking his books and papers, withdrew from the house,
with a considerable portion of the members (several of whom
had nevertheless opposed his minuting of the complaint),
leaving the rest to transact the business of the Monthly Meeting in quietness.^
footnote:[[.book-title]#Exposition of Proceedings Which Led to a Separation
in Red Cedar Monthly and Salem Quarterly Meetings.#
Marion, Iowa, 1855; page 8, etc.]

In regard to this extraordinary transaction,
it appears that the hasty adjournment of the meeting by the clerk and a few others,
can have had only one object, to provoke a separation,
and thereby obtain for themselves the power to accomplish
their purpose of disowning the minister in question,
who was not of their way of thinking.
Whether it was wise in those who opposed the clerk`'s disorderly course,
to act so promptly as they did,
or whether it would not have been better to have let the matter go on,
with a prospect of appealing, is a question which may admit of some doubt.
They knew that this whole transaction was instituted, as implied by one of the committee,
to stop the "`heavy undercurrent`" of opposition
to the unsound doctrines introduced into the Society;
and that Indiana Yearly Meeting having already identified itself
with the promotion of these unsound doctrines and practices,
any appeal to it would assuredly only confirm the oppressive measures.
They were fully persuaded from what had already occurred,
and from the state of things in Indiana Yearly Meeting,
that their case was hopeless of any favorable countenance
from those who controlled the proceedings of that body;
and they believed themselves imperatively called upon (regardless
of the painful consequences that must ensue,
and that would ensue indeed in either case, if they remained firm to their convictions),
to endeavor to sustain the ancient principles and practices of the Society,
and to testify against the promoters of these disorderly measures,
as seceders from the faith and discipline of Friends.

The most questionable act, on their part, if it was really questionable,
was the summary displacement of the clerk who so palpably abused his office,
and appointment of a new one who would truly serve the meeting,
instead of thwarting its judgment for party purposes.
This was an extreme measure.
Was it an unjustifiable one?
According to the mere letter of the Discipline, perhaps it might be so considered.
But we must remember that the clerk was manifestly and persistently acting,
not for the meeting that appointed him, but for a party,
which had the entire control of Indiana Yearly Meeting,
and was now engaged in promoting a schism through the whole Society;
that this transaction on the part of the clerk was
obviously a part of that schismatic course;
and that those who dissented from it,
were actuated by a conscientious conviction of its schismatic character,
and a sense of the obligation which lay upon them to stand for the ancient faith.
Herein, it seems to the writer,
rests their justification in acting so promptly (instead
of waiting to displace the clerk in a more regular manner,
which they certainly had a right to do), and not taking the usual course of an appeal,
which in this case would have been to a body implicated already in the schism.

The remaining steps of this separation, involving its extension to the Quarterly Meeting,
may be told in a few words.
Both the bodies claiming to be Red Cedar Monthly Meeting
sent up reports and representatives to the Quarterly Meeting;
the report from the Gurney party including a proposal
for the laying down of Linn Preparative Meeting,
as insubordinate to the Monthly Meeting.
A committee was appointed to examine both reports,
who suggested to the Quarterly Meeting to read the one from the Gurney party.
Friends of the ancient views urged that the Quarterly Meeting
should itself examine into the merits of the case,
saying that they were willing that the whole matter should be investigated.
The meeting appeared to be about to take that course,
when a member of a committee of the Yearly Meeting
to visit Salem Quarterly Meeting interfered,
saying, "`Take care, Friends, mind what you are about;
it may be you will get into difficulty.`"
The others, feeling confident that the matter was not understood,
still urged that the meeting should not proceed without giving them a hearing.
The Yearly Meeting`'s committee then proposed that
the Linn Preparative Meeting might be laid down,
and a committee should be appointed to visit Red Cedar Monthly Meeting.
This was accordingly done.

But this committee declined to attend any other than the
Monthly Meeting of Red Cedar belonging to the Gurney party.
They, however, appointed a conference, at which Friends of the other Meeting attended,
and gave an account of the reasons which had induced their present position.
This account, and the discussion which ensued, seem to have had some convincing effect;
for though one or two of the committee advised them to "`return
to the body,`" and "`endeavor to right it,
if it had erred;`" yet another remarked, "`If I understand this people aright,
they regard themselves as the legitimate Monthly Meeting,
and say they have peace of mind in the course they have pursued.
Now, to what shall we urge them to return--to disorder and confusion?`"
And another said,
"`No doubt but that the Monthly and Quarterly Meetings had acted too hasty.`"
The committee, however, made no proposition to the next Quarterly Meeting,
in the fifth month, for the relief of these Friends,
and the Quarterly Meeting again refused to receive their representatives and report.
They, therefore, quietly sat until the innovating party had finished its business,
and then appointed a fresh clerk,
held Salem Quarterly Meeting on the ground of the ancient principles of the Society,
and adjourned to meet at the meetinghouse at Red Cedar.

For some time afterwards this company of Friends in Iowa,
notwithstanding some sources of weakness,
went on in a good degree of harmony and circumspection, and increased in numbers.
They appeared to bid fair to take a satisfactory place among
the remnants concerned to stand for the ancient faith,
scattered in different portions of this land.
Considerable additions to the Quarterly Meeting were experienced
by immigration of Friends`' families from Ohio,
though this was not always an element of increase of strength.
Salem Quarterly Meeting then contained the three Monthly Meetings of Red Cedar, Linn,
and Hesper; Linn Monthly Meeting having a branch at Prairie Ridge.
Their position as fellow testimony-bearers in the Western country was
hailed with satisfaction and comfort by the smaller bodies to the eastward,
who trusted that a standard was now at length raised within Indiana Yearly Meeting,
to which the honest-hearted might rally for the defence of the Truth.
But, alas, the devices of the enemy of all righteousness are unceasing,
and especially dangerous when they work in a mystery, assuming the appearance of good.

If they who controlled the proceedings of Philadelphia and Ohio Yearly
Meetings had faithfully stood to the ground which they had at first taken,
they would have been led, as a matter of plain and indispensable duty,
to own fellowship with the Smaller Bodies in other places,
and would thus have been eminently instrumental to
their encouragement and growth in the Truth;
and there is no reasonable ground for doubt that, under such circumstances,
a large body of sound Friends might have been preserved and strengthened in the faith,
whose united testimony and example would have had
a powerful influence over the Society at large,
in checking, if not in frustrating to a great extent,
the endeavors of the advocates of innovation.
But instead of this, the course of those two Yearly Meetings,
under the paralyzing influence of fear, and of the half-way system,
tended greatly to the discouragement and dismemberment of all the Smaller Bodies;
and on some of the members of these,
who were not deeply grounded in religious experience,
the effects thereof were particularly disastrous.
The "`middle party`" in Ohio perceived that not a
few of their members were emigrating to Iowa,
and likely to join the meetings of this small company there,
rather than connect themselves with the Gurney party.

They, therefore, set themselves to work,
not merely to avoid strengthening the hands of this small body of Friends,
but even to weaken and scatter them,
by furnishing another method by which the emigrant
families from Ohio might be organized into meetings,
without joining those which the leaders of that party
chose to consider as separate meetings.
Some of those already members of Salem Quarterly Meeting were, besides,
known to be more or less weak in the faith, and easily discouraged,
and this device would be a trap into which they would readily fall,
and thus diminish the unity as well as the numbers of those
who should stand too firm to be taken by that bait.
Accordingly,
regardless of the fact that Iowa was within the compass of Indiana Yearly Meeting
(which Philadelphia still recognized by the interchange of certificates),
and that a Quarterly Meeting of Friends sound in
the faith had already been sustained there,
they undertook to establish meetings of their own within its boundaries,
to be considered as belonging at first to Stillwater Quarterly Meeting, Ohio,
of which Benjamin Hoyle, the leader of the Ohio middle party, was a member.

Among those who had taken the stand above described in Salem Quarterly Meeting,
there were some who were somewhat favorable already to the half-way system,
and others too ready with self-active schemes for
sustaining the cause in which they were engaged.
On the establishment of meetings in their neighborhoods,
owned and assisted by Ohio Yearly Meeting,
these were easily enticed away from the isolated and comparatively
unowned "`smaller body;`" or if not enticed entirely away,
were more or less loosened from their moorings,
and readily gave an ear to things tending still further to alienate them.
Thus disunity and disintegration began to creep in,
to the great danger of that "`smaller body,`" as many of their members left them,
to join what they thought were more regularly organized meetings.
The more honest-hearted portion of the members, meanwhile,
endeavored to struggle against the strong tide brought to bear upon them.
But nearly all the members of Red Cedar Monthly Meeting
going into the snare thus laid for them,
left the others very few and weak.
That Monthly Meeting was therefore laid down by Salem Quarter in 1860,
and the remaining members were attached to Linn Monthly Meeting;
and the meeting at Prairie Ridge was likewise laid down, all its members,
except one family, having joined the new meetings set up by Ohio.
Thus, the Quarterly Meeting was now sustained by only the two small Monthly
Meetings of Linn (without Prairie Ridge) and Hesper.

If, however,
the few that remained had continued single-eyed and watchful to the Lord their helper,
they would doubtless have been strengthened to stand through all.
But there were still some active members among them, not deeply grounded in the Truth,
who let in a spirit of jealousy and bitterness against
the rightly exercised and honestly concerned ones;
thus causing disunity and weakness in the meetings; and not being founded on the Rock,
and some others also depending too much on man,
instead of looking with a single eye to their, holy head, Christ Jesus,
their vision was clouded,
and they were not able to discern between the true and the false,
the living and the dead child.
So that when the additional difficulty,
caused by the separation of the King party at Poplar Ridge, in 1859,^
footnote:[To be narrated in the next chapter.]
came upon them, the storm was too strong for them, as a body, to stand against,
and in 1861 they eventually gave in to a recognition of the plausible
pretensions of the New York separatists under John King.
This was in fact but another insidious form of the middle system,
and they were thus swallowed up almost bodily by that vortex.

One of these Friends has, in a letter to the writer of this work,
acknowledged that after this they seemed to have no life
left to enable them to conduct the affairs of the church,
or even to worship aright,
and that they groped their way along without comfort or unity among themselves.
In the fifth month, 1862, a few of them,
being convinced that they had done wrong in acknowledging the King party,
could not feel at liberty any longer to meet with them.
After many trials and difficulties, arising from their scattered condition, a few,
residing near Viola, in Linn County,
began to meet together for divine worship in one of their houses;
and continuing to look to the Shepherd of Israel,
who followeth his lost sheep even into the wilderness, they were mercifully sustained,
and gradually strengthened to look toward reunion
with their Friends of the "`smaller bodies`" elsewhere,
who had remained faithful to the testimonies of Truth.
That worthy man, Ebenezer Austin, who had maintained his integrity,
was taken away by death, and his family became scattered;
but the rest of those residing near Viola made application, in 1873,
to the General Meeting for Pennsylvania, etc., for the extension of care over them,
and they were accordingly received (though far distant
and much isolated) as members of Salem Monthly Meeting,
Ohio, one of the branches of that General Meeting.
