== Chapter XV.

Establishment of the General Meeting for Pennsylvania, Etc.,
Independent of Philadelphia Yearly Meeting.

What was now the condition of affairs in the Yearly Meeting of Philadelphia?
Was it not involved in isolation and confusion,
through its own timidity and unwarrantable tampering with the inconsistencies--nay,
with the sorrowful secessions from the faith of Friends--which
prevailed around it and in its midst?
There was not one Yearly Meeting now,
with which it dared to resume epistolary correspondence,
for fear of a separation within its own borders, either of one class or the other.
Yet a far more powerful instrument of communion with
the bodies lapsed into the modern views,
than any epistolary correspondence could possibly be, was left open,
in the unrestricted interchange of membership by certificates,
in cases of a removal from one section of the nominal Society to another.
By this means all the Gurney meetings in England and America
could be recognized as if they were meetings of Friends,
and the members were constantly recommended to the "`Christian
care and oversight`" of those who were well known to have departed
from all but the outside form and name of Quakerism.

This was a palpable element of complete amalgamation,
as well as a frustration of all the testimonies hitherto
borne by Philadelphia Yearly Meeting against this heresy.
It was, in effect,
binding back again all the Gurney Separatists into one body with Philadelphia,
and practically declaring that they were no separatists after all.
Under this system the most decided advocates of schismatic doctrines and practices,
coming from the most palpably schismatic Yearly Meetings,
if intending to reside or marry within a meeting which perhaps
demurred at directly receiving a certificate from some of the Gurney
meetings (for there were for a time a few that so demurred),
needed but to stay, for a short time,
within another Monthly Meeting which had no such scruple,
and then by a transfer could have their membership recognized wherever they desired.
Such cases were not wanting.

Although Gurneyism had been declared by some of the most influential
country members of the Yearly Meeting to be of equal danger with
Hicksism to the true principles of Friends (see page 245),
yet no disciplinary measures were taken by which
to attempt to stop its currency among the members.
Many were the instances of active and influential members
attending the yearly and other meetings of the Separatists,
in contravention of a direct rule of the Discipline,^
footnote:[Discipline of Philadelphia Yearly Meeting, p. 70 and 71 of old edition.]
forbidding such attendance.
Yet they not only escaped disciplinary censure,
but retained their positions of influence in the body, either as ministers, elders,
overseers, or in other stations of importance; although,
if they had done the same in regard to the Hicksian meetings,
they would have been promptly dealt with, and, if not brought to a sense of their error,
unquestionably disowned.
The assistant clerk of Philadelphia Yearly Meeting for many years (a man
long dearly beloved by the author) was one who exemplified this;
having been present with John Pease at the separation in New England, in 1845,
and participated with the Separatists there,
and subsequently cast in his lot openly and influentially with the Gurney party;
though formerly a valuable elder,
and clearsighted in regard to the unsoundness of J. J. Gurney`'s writings,
while the latter was in this land.
Nevertheless he retained his position at the clerk`'s
table of the Yearly Meeting for many years afterwards,
and his station as an elder until his decease.

Eliza P. Gurney, occupying the station of a recognized minister, was another instance,
equally glaring, having taken part openly in the Ohio Gurney Separation,
and joined in with the others of the same class throughout the United States,
without at all losing her position in Philadelphia Yearly Meeting.
These cases are mentioned merely as obvious evidence
of the truth of the remark above made,
that the provisions of the Discipline were totally ignored in all such instances,
which were a great multitude indeed.
In the Yearly Meeting itself, the Discipline was constantly and openly violated,
not only by making use, on important services of the Society,
of such as had joined the Separatists by attending their separate meetings,
and constantly advocating their cause;
but also in its reception of individuals coming as ministers with credentials
from the Gurney meetings in Great Britain or any part of America.
They were allowed to sit in the Yearly Meeting, and take a part in its business,
as if they were members in unity; and even in the Yearly Meeting of Ministers and Elders;
yet when they presented their credentials,
they were not allowed to be read in the meeting,
contrary to an express rule of the Discipline,
which declares that "`the Certificates of such Friends, members of other Yearly Meetings,
who from a religious concern are drawn to attend this, are to be read herein.`"^
footnote:[Discipline of Philadelphia Yearly Meeting, page 160, old edition.]

If we look back to the former troubles from the opposite secession, in 1828,
we may readily perceive that persons so circumstanced would
not have been acknowledged as having the rights of members,
and would, therefore, not have been allowed to attend meetings for discipline,
or to go through the various settlements of Friends within our limits,
in the line of the ministry, without let or hindrance, or even rebuke.
These should have been checked in like manner,
being equally engaged in pulling down the ancient landmarks of the Society; and then,
if they ventured to attend the Yearly Meeting,
they might properly have been informed that we could not recognize them as fellow-members,
nor their meetings as meetings of Friends, and, therefore,
we could not accept or read their credentials.
But to treat them as members and ministers, and yet refuse to read their certificates,
was a plain transgression of the Discipline by the Yearly Meeting itself,
for which the "`middle party`" was manifestly accountable.
The result was, that a succession of unsound persons,
claiming to be ministers of the gospel, but very unfit for that weighty service,
were constantly coming from various quarters,
and travelling in that capacity within our limits, unchecked by the body,
to the great bewilderment of the youth and others, and the reproach of the Truth.

At the time of the Hicksian defection,
which was no more palpable as to doctrine than this one,
though more unpopular and more repulsive in some of its features,
the Yearly Meeting of Philadelphia took common ground with all the other Yearly
Meetings which were then concerned to maintain the principles of the Society,
that meetings or individuals implicated manifestly or professedly in unity with
the seceded party were to be treated as having left the Society of Friends.
This was a sound position, and indispensable for the purity and integrity of the church.
Then why abandon it now?
The "`middle party`" alleged that they were all still Friends,
though involved in some errors of doctrine and practice,
and that they had some sound members among them.
Yet the aberration of the Yearly Meetings in acknowledging fellowship
with the Gurneyites of New England who had inaugurated a schism for the
purpose of sustaining the influence and principles of J. J. Gurney,
and also with the Yearly Meeting of London,
which had sanctioned his principles and liberated him to
go forth to propagate them in the Society and in the world,
was quite as palpable as the aberration of the Hicksites
in supporting the doctrines and influence of Elias Hicks.
And those departures of the Yearly Meetings involved
the meetings and members subordinate to them,
as clearly in one case as in the other.

In 1859, Joseph E. Maule published in Philadelphia,
Remarks on Acknowledging Meetings of Separatists as Though They Were Meetings of Friends;
detailing the manner in which the official acts of the Yearly Meetings of Indiana
and North Carolina proved them to have gone off bodily in the schism,
identifying themselves with the seceded Gurney party in Ohio,
and with the same departure in New England and Great Britain.
This pamphlet was extensively circulated,
so as to leave the members of Philadelphia Yearly Meeting without
the excuse of not knowing the official actions of those bodies,
or without a brotherly warning of the consequences of so weakly
compromising the testimony for the truth and against error,
which had been faithfully sustained by that Yearly Meeting in former years.

The Yearly Meeting, in.
1859,
was exhorted to attend to the very serious subject of the
interchange of membership by certificates of removal,
by which some of the Monthly Meetings were already
thus identifying themselves with the seceded bodies,
contrary to the Discipline.^
footnote:[Discipline of Philadelphia Yearly Meeting, pages 70, 71.]
The rule of discipline in question, is substantially as follows:

If any of our members should attend the meetings of those who have separated from us,
and who have set up meetings contrary to the order and discipline of our Religious Society,
as it is giving countenance to, and acknowledging those meetings,
as though they were the meetings of Friends,
this meeting declares that such conduct is of evil tendency,
and where such instances occur, Friends are desired to extend brotherly care and labor,
that the individuals may be instructed and reclaimed;
and if those endeavors prove ineffectual, Monthly Meetings should testify against them.

If, as appears here,
the members are not to be allowed to attend the meetings of Separatists,
on pain of being considered disownable, and dealt with accordingly,
how could the Monthly Meetings be at liberty to send
their members to such meetings by certificate,
recommending them to their "`Christian care and oversight?`"
Yet such was now becoming a frequent practice, under the influences of the middle system.
The Yearly Meeting was reminded that one of the Monthly Meetings in Philadelphia,
had laid the subject before the Quarterly Meeting as a case of difficulty,
asking its advice and counsel, but could obtain no satisfaction, and was now,
to the great grief of a number of Friends,
on the point of recommending some of its members by certificate
to a Monthly Meeting of Indiana Yearly Meeting,
which had joined the Separatists.
But the meeting declined to take any action on the subject.
This Yearly Meeting was attended by Robert Lindsay, a minister from England,
who was allowed to attend the sittings, and took part in the concerns of the meeting,
although he had previously been attending the seceded Yearly Meetings of Ohio and Indiana,
and the Western, a new one established from a portion of the latter.

Of his attendance of these separate meetings, the Yearly Meeting was informed.
When it was proposed to read his certificate,
the measure was opposed by a number of friends; and the meeting was distinctly told,
that as London Yearly Meeting, from which he came,
had entirely identified itself with the Seceders, and was, indeed,
the very quarter whence the difficulties originated,
the reading of his certificate by this Yearly Meeting would
be (practically) an act of separation from the Society.
The temporizing party, with the clerk of the Yearly Meeting,
alleged that as the Select Yearly Meeting had concluded not to read his certificate,
it would not be best to read it here.
But, as the periodical paper of the Gurney party afterwards said in narrating the circumstance,
the Yearly Meeting of Ministers and Elders "`has no right
to interfere in the business of the Yearly Meeting;`"^
footnote:[Friends`' Review, vol.
xii, p. 536.]
and consequently it was not proper to bring their action, or non-action,
as a rule to govern the Yearly Meeting.

It was merely a subterfuge.
The rule of Discipline, however, on the subject of certificates of strangers,
being called for, was read; and the clerk declared that under the circumstances,
he was willing the certificate should be read,
alleging that he was not previously aware that the rule was as it was!
In this willingness he was supported by several of the "`middle`" class;
yet the current of opposition to the reading of the certificate at that time prevailed,
and the measure was not carried.
But thus the Yearly Meeting became again involved, by its half-way course,
in a double violation of its own Discipline,
in allowing one to sit as a member and minister who was palpably implicated in the schism,
and yet rejecting his certificate; an example plentifully followed in subsequent years.
The year 1860, however, found many friends,
both in Philadelphia and the country districts,
disposed to submit to the influence of the half-way or middle party,
and thus to allow those of the Gurney class to have their own way, practically,
without let or hindrance,
except in the comparatively insignificant matter
of the yearly epistolary correspondence.

Many were tired of the contention.
An influential female minister (E. E.) had preached
earnestly on the words of the prophet Jeremiah (47:6):
"`O thou sword of the Lord, how long will it be ere thou be quiet?
Put up thyself into thy scabbard, rest, and be still.`"
Others saw no hope.
And especially was all hope given up by many, when the dogma was freely received,
launched as it were on high authority,
that "`separations were no remedy,`" and therefore all, sound in the faith or unsound,
or even opponents and innovators, must, by some means or other, be kept together.
This keeping of all together was to be done by compromising
some of the very fundamental features of our compact,
both in doctrine and discipline.
For the open and frequent avowal and promulgation of the new doctrines,
especially through the press, was now connived at as if it were no breach upon the body;
and the discipline was prostrated,
by allowing an equalization of schismatical persons with sound
Friends as eligible for the services and control of the Society.

The Gurney portion of the members were pretty well
contented with this system for the present,
for it gave them full scope to carry on their measures without contending for them,
though without the direct and open sanction of the body.
Certificates for foreign ministers, though rejected by the Yearly Meeting,
could be read in some one of the meetings under the control of the party,
and all the novelties deemed desirable could be encouraged to the full,
and with entire impunity.
They were willing, therefore, to wait, in patience and hope,
for a time when they would be able to take control of the Yearly Meeting themselves,
being satisfied that the tendency of things was to that result.
Yet there were those, in various portions of Philadelphia Yearly Meeting,
who could not unite with these compromising measures, seeing their entire inconsistency,
and their inadequacy to the crisis; and feeling that the precious truths of the gospel,
committed to our trust as a people,
were not to be safely bartered away for a false peace--a mere fallacious
truce with those who were engaged in substituting a new system,
fundamentally at variance with the unchangeable truth as held by our worthy forefathers.

This sentiment indeed was cherished by a considerable
portion of the members in various parts;
and a few here and there were prepared to act in accordance with the conviction;
though many others,
whose whole heart and soul should have been engaged to sustain the Lord`'s cause,
when the day of trial came were found to flinch, and, under a cowardly fear,
to plead the necessity of submission to the sense of the body.
Though "`armed and carrying bows,`" they "`turned back in the day of battle.`"
Thus the numbers of those who through all were truly concerned
to be found standing as it were with their lives in their hands,
firm for the ancient standard,
without calculating consequences by carnal reasonings and pleas,
were reduced to so small a remnant that they were even fewer
than those who lapped water in the army of Gideon,
who were selected as the instruments for executing the counsel of the Most High.
The interchange of membership by certificates to and from the seceded bodies,
at length became so frequent a practice among the several Monthly Meetings,
that its inconsistency and danger engaged the solid attention of Bucks Quarterly Meeting;
many of the members thereof being convinced that it was carrying
the meetings rapidly into complication with the schism.
The result was that Bucks Quarter sent up in its report to the Yearly Meeting,
in the spring of 1860, a request that the subject might claim its consideration,
so that the Monthly Meetings might be instructed as to what course they should pursue.

The Northern District Monthly Meeting in Philadelphia had already
sent up to Philadelphia Quarterly Meeting a proposition for referring
this important subject to the Yearly Meeting for its consideration,
so that the Monthly Meetings might be instructed how to act.
But the Quarterly Meeting declined to take any steps in regard to it;
one influential elder remarking that the carrying of it to the
Yearly Meeting "`would only cause trouble,`" and that "`the Monthly
Meetings certainly had a discretionary power.`"
Poor ground this for refusing to open the way to a safe decision of so vital a matter,
on which so much diversity existed.
In the eleventh month, 1859,
an Appeal had been presented to Philadelphia Quarterly Meeting,
signed by some of the members of the Northern District Monthly Meeting in that city,
on the same subject.
The Quarterly Meeting refused to hear this appeal,
and the appellants therefore notified the ensuing Quarter, in the second month, 1860,
of their intention to carry up their appeal to the Yearly Meeting.
The Quarterly Meeting declined to recognize their right of appeal,
or to appoint respondents on its part, as usual, to the Yearly Meeting.
Meantime the Monthly Meeting went on,
recommending several of its members to one or more
separate meetings within the limits of Indiana.
This constrained the appellants to carry their appeal to the Yearly Meeting of 1860.
It was as follows:

To The Yearly Meeting.

As members of the Religious Society of Friends,
truly concerned for the support of its Discipline and ancient testimonies,
we feel constrained to appeal to the Yearly Meeting against the course pursued by some
of the members of the Monthly Meeting of Friends of Philadelphia for the Northern District,
who have violated the Discipline of our Yearly Meeting,
by sending certificates of membership to meetings of separatists;
thus giving countenance to,
and acknowledging those meetings as though they were meetings of Friend +++[+++of]
which our Yearly Meeting declares that such conduct is of evil tendency,
and repugnant to the harmony and well-being of our Religious Society;
and which we have found to be sorrowfully true in every particular.
And we apprehend that our rights of membership in religious
Society have been endangered by such proceedings.

And we also feel constrained to appeal against Philadelphia Quarterly Meeting,
for refusing to hear our appeal against those disorderly acts,
as it still further jeopardizes our rights of membership.

Had these three members the right of appeal on this subject, or had they not?
The subject was a momentous one, affecting the whole constitution of the Society.
The Discipline guarantees to every member who thinks himself aggrieved
by the judgment of his Monthly Meeting in his case,
the right of appeal.
This wording of the rule--in his case--which was probably intended rather
as an explanation than as a limitation,--was taken advantage of,
against the appellants,
by the allegation that no judgment had been issued by the Monthly Meeting against them,
individually,
that in short they had had no case pending in the Monthly
Meeting--not having been dealt with at all as delinquents,
or offenders against the Discipline--that the right of appeal was here confined to those
who had been testified against by their Monthly Meeting--that the present matter was
a mere difference of sentiment respecting the action of the Monthly Meeting,
and therefore that it was not a proper subject for an appeal.

This, however, was an unworthy quibble,
for the purpose of setting the matter easily aside without a hearing.
The subject of the appeal was well known to be of a highly important character,
and it was also known that appeals more or less similar in circumstances
had on various occasions in former years been presented and entertained,
for the cause of justice, by the superior meetings,
especially during the troubles with the disciples of Elias Hicks.^
footnote:[See Vol.
1, chap.
4.]
If not as an appeal, yet at least as a remonstrance against a supposed great wrong,
endangering, in their apprehension, the rights of membership of those presenting it,
and also of many others, as well as the safety of the Society, and its proper identity,
it ought surely to have been heard, both by the Quarterly, and, if needed,
by the Yearly Meeting.
The Yearly Meeting of 1860 came in due course, on the 16th of the fourth month.
After it was opened for business on Second-day morning,
the clerk mentioned that he found on the table a paper endorsed,
Appeal to Philadelphia Yearly Meeting;
but that none of the reports from the Quarters alluded to any appeal.
He inquired what disposal should be made of it.
After some time, he rose again, and added that, on looking into the paper,
it appeared to be signed by three persons,
and to be an appeal against their Monthly Meeting`'s action in
sending certificates to Monthly Meetings of other Yearly Meetings;
and, as this subject would come up from the minutes of Bucks Quarter,
he inquired whether it would not be better to postpone
the consideration of it till that time.
To this the appellants consented, in the full confidence that they would then be heard.

On Fourth-day afternoon,
the subject as brought up by Bucks Quarterly Meeting came under consideration.
After a great deal had been said for and against the practice in question,
some of it savory and pertinent, and much of it quite the contrary,
and not needful to be repeated here;
and many of those who had formerly been relied upon
as opposed to this inconsistency had given way,
under the plea that way did not open to do anything, and therefore it was best to submit,
the clerk made a minute,
stating in substance that the subject had been "`deliberately considered,
and way did not open to take any step;
but that the Monthly Meetings were directed to keep
to our Discipline in relation to that subject.`"
One of those who had been really valiant for the truth, but,
under the paralyzing influence of an attachment to some of the half-way leaders,
had previously stated his opinion that way did not open to do anything,
immediately rose and said that he thought the latter part of the minute
(respecting keeping to the Discipline) had better be stricken out.
Solomon Lukens, an elder, who sat near the table, turned round and said, "`I hope not!`"
But the clerk, without waiting for further expression,
immediately ran his pen through that part of the minute, remarking,
"`It don`'t change the Discipline;`" apparently regardless of the manifest fact,
that though it did not change the Discipline,
yet it changed the position of the Yearly Meeting in relation to the Discipline,
as it showed that the meeting was afraid to recommend a strict compliance therewith,
which would have necessarily resulted in the disownment of all who should persist
in adhering to the apostatizing course which was the cause of all this trouble.

At the next sitting,
one of the appellants called the attention of the meeting to the appeal,
reminding Friends that the understanding was,
that it was to be attended to when the subject from Bucks Quarter was considered;
which had now been done,
and the meeting appeared to be drawing towards its closing business.
The clerk now attempted to check any further opening of the case;
saying that "`he had expected it was understood that this matter was settled
when the report from Bucks Quarter was read and disposed of,
as the subject in each was similar.`"
This was exceedingly unjust,
as the appellants had confided in his own proposition to hear their appeal at that time,
and they had had no full and fair opportunity of opening
and explaining the nature and extent of their grievance,
as they would have had before a committee appointed
for the purpose of hearing their appeal.
The clerk, moreover, as a member of the Quarter appealed against,
had no right to a voice in the question, according to our Discipline.
But several other members of the same Quarterly Meeting
now assumed to object to any reopening of the subject,
notwithstanding this plain previous understanding.

One influential member of Philadelphia Quarterly Meeting
stated that he had seen the appeal addressed to that Quarter,
and that it was not an appeal,
but a remonstrance against sending certificates to certain meetings.
Another member of the same Quarter said, he likewise had seen the appeal,
and he designated it as wrong, or disorderly,
for persons to come before the Yearly Meeting in this way!
Another member of it said,
there ought to have been a committee appointed early in the Yearly Meeting,
to examine the paper, and then they should have reported that it was a wrong thing, etc.
Indeed,
it seemed as if the members of the very Quarterly
Meeting against which the appeal was presented,
were the main opponents now to its being heard,
in direct contravention of the Discipline.
They were, however, followed by members from other Quarters,
opposing any hearing of the appeal,
and censuring the appellants for coming thus before the Yearly Meeting.
Some then proposed that the meeting should go on with other business--which
was done--and thus the appeal was rejected without being heard,
in violation of the express understanding given in the early part of the meeting!
Friends who deeply felt and mourned over these departures,
now lost all hope of Philadelphia Yearly Meeting doing anything effective to
stay the progress of the secession from the true principles of the Society.
They had done what they could to avert the downward course,
but all their efforts had been rejected, and appeared now to be of no avail.

These saw with distress,
that not only was Philadelphia Yearly Meeting entirely failing to withstand
the advances of the schism in any practical and effective way,
but that it was officially permitting such a series of measures in the
subordinate meetings as must eventuate in a complete amalgamation with
those who had openly joined the secession in other places.
It had now refused to interfere with this amalgamation,
had stricken out from its minute even a recommendation to keep to the Discipline,
and was, in its own constant practice, setting an example of placing the avowed,
and active, and influential Gurneyites on an equality with any other members,^
footnote:[See chap.
15.]
when they ought to have had disciplinary measures extended to them,
to convince them of their errors, and if not reclaimed, to have been disowned.
They saw, too, that for themselves as individuals, and for their families,
there was no safety from being swallowed up in this vortex,
but in firmly and openly withstanding it;
although a faithful stand against it might involve the very painful necessity
of calling in question the continued authority in the truth,
of the Yearly Meeting itself,
and clearing themselves from its now lapsed and apparently hopeless position.

It appeared to them that the time had fully come, for them to flee each one for his life;
or, in accordance with the words of John Justice, a minister from Bucks County,
spoken prophetically in the Northern District Meeting in the year 1838,
two weeks before his decease; when,
testifying of his sense of the coming of something "`even more
awful than anything we have ever yet had to pass through,`" he
predicted that "`those who are preserved in this time,
it will be as it were upon the broken pieces of the ship.`"^
footnote:[The Friend, 1845, page 196; and J. E. Maule`'s Serious Review, page 9.]
Not that all who at that time saw and mourned over the lapsed condition
of Philadelphia Yearly Meeting were alike prepared to act firmly and openly,
when the time came for an individual standing as in "`the valley of decision.`"
This was indeed found now to be a low place--too low for
the pride of man to find satisfaction in it.
Many were soaring above it, and saying to themselves or others,
that when something might occur, in which they would be joined by considerable numbers,
and by such and such eminent members,
so as to make a "`respectable`" body in their estimation,
then they would be willing to unite in opposing Gurneyism.
Others earnestly cried out that "`separations were no remedy,`"
and "`not to be resorted to under any circumstances;`" forgetting,
or ignoring the fact, that the schism was already upon them,
and the Yearly Meeting was falling into it!
Still others, like a portion of Gideon`'s host,
were "`fearful and afraid,`" and were therefore not prepared
for this warfare with "`principalities and powers.`"^
footnote:[Some who then made one plea or another
for remaining "`in the body,`" lapsing as it was,
found, after awhile, the entangled state they were in,
with all the innovations pressing upon them, yet with no power now to withstand them;
and began to charge those who had taken a firm stand in the day of decision,
with having increased their inability to oppose the inroads of Gurneyism,
by leaving them to themselves, instead of staying to help them.
These would now acknowledge that they wanted their aid.
But they seemed to forget the repeated warnings that
had been given them by those Friends while with them,
that the departure was a fundamental one;
and that they themselves had quietly looked on and allowed
the testimony of such to be treated with scorn and reproach,
and their efforts to sustain the cause frowned down.
Some of these now attempting to excuse their remaining with the lapsed body,
would allege that they continued to testify against the palpable innovations,
and therefore considered themselves clear of the responsibility.
Yet they still held their positions as active members of the meetings
which allowed the inroads to go on without effectually checking them;
and the old saying, quoted by Robert Barclay,
was applicable to them--"`Quod facit per alium, facit per se.`"]

Many Friends left the city for their homes on the same day that the meeting closed.
A few who were communing together early the next
day on the sorrowful condition of the church,
and the danger, which threatened all the members,
of being inextricably entangled in the secession,
believed it right to call together such as could be found still in the city,
who were opposed to the course taken by the Yearly Meeting,
inviting them to meet at the house of a friend at a later hour in the morning.
Twenty-two Friends accordingly assembled,
who sat together in silent waiting on the Wonderful Counsellor,
for his direction and help.
A solemn covering of good was sensibly felt over this little assembly,
with a ray of hope for safety to those who,
in simple reliance on the Master`'s guidance and protection,
would be willing to follow whithersoever his divine wisdom should lead them,
even though it might be through the deeps,
as escaping on boards and broken pieces from the stranded vessel.

A sweet feeling of sympathy and unity prevailed;
but as their numbers were felt to be small, it was thought best,
before coming to any conclusion as to further proceedings in so weighty a matter,
to invite Friends more generally throughout the Yearly Meeting,
who might feel prepared for it, to meet together in Conference, at Fallsington,
in Bucks County, Pennsylvania, on the thirty-first day of the fifth month,
after the close of Bucks Quarterly Meeting.
Notices were accordingly circulated of the proposed Conference,
and a considerable number of Friends attended at the time and place appointed.
It was supposed that about one hundred, of both sexes,
from various portions of the Yearly Meeting, were in attendance,
who sat together in solemn waiting on the Lord,
that he might condescend to show them a right way for themselves and their little ones,
acceptable in his holy sight.
It was felt to be a season of divine favor,
and they were encouraged to stand firm and vigilant against the
wiles of that insidious spirit which was laying waste the precious
testimonies entrusted to our religious Society to uphold,
for the maintenance of the purity of the Christian religion.
It was concluded to meet again at the same place in the ensuing ninth month.

Steps were taken one by one, as the stepping-stones could be clearly discerned.
At the next Conference meeting it was concluded to appoint a clerk,
and to keep records of their proceedings.
This measure startled a few, who became alarmed on looking ahead,
and contemplating the smallness of their numbers compared
with those still adhering to the Yearly Meeting;
and some of these now concluded that it would be safest
for them to "`walk no more with`" this little company.
So the few became for awhile fewer.
But they were sustained in the faith that their path was cast up for them,
not of themselves, but by Him whose ways are higher than our ways,
and whose counsels are inscrutable, but who will unfailingly sustain his children,
be they few or many, who hold out to the end in faithful obedience,
having none in heaven but him, nor in all the earth in comparison of him.
It was now agreed to appoint a committee to draw up, during the interim,
an essay of an epistle to the members of Philadelphia Yearly Meeting,
explanatory of the causes of our present position,
and inviting the honest-hearted to unite in measures for the sustaining
of a body of Friends here on the ancient foundation--this essay
to be presented for consideration at the next Conference meeting,
which was agreed to be held at Fallsington, in the ensuing twelfth month.

Here, then, was a position taken in direct opposition to the Yearly Meeting.
But it was a position in which a deeply concerned
and tribulated remnant felt called upon to stand,
in a sincere endeavor to sustain the ancient standard,
which the Yearly Meeting was allowing to fall to the ground.
In doing this they were taking no new position,
as the Yearly Meeting was tacitly yet obviously falling into the ranks of schism,
and their concern was to remain firm to the original ground and compact of the Society.
That which may be looked upon as a separation from a Yearly Meeting which has
through unfaithfulness lost its rightful position and authority as a living Church,
is not a separation from the true Society,
even though it may involve a disownment of the great majority of the professing members.
Indeed it may be a means of preservation within the true Society.
They are the true Society who stand by its vital principles and practice.
Yet a separation is an extreme measure,
and can only be justified when full evidence is shown
of its necessity for the great duty of sustaining,
in their purity and vitality,
the precious principles of Christianity with which the people called Quakers were entrusted,
and of preserving the members from otherwise inevitable
entanglement in fundamental error of faith or practice.
It must, in short, be founded on a fundamental emergency.

Was this the emergency to which faithful Friends were now brought,
within the Yearly Meeting of Philadelphia,
a Yearly Meeting which had stood so firmly against
the errors of Elias Hicks and his followers,
and, for a time,
against the more recent and opposite attacks upon its ancient
faith by the advocates of the Gurney system?
Deplorable as such a conclusion must be, and incredible to many,
it has always appeared to the writer, that here was such an emergency.
The fundamental principles distinguishing our ancient faith,
and the true life of the body, were at stake in this matter.
The Yearly Meeting,
after having repeatedly warned that of London of the unsound nature and disintegrating
tendency of the changes in doctrine which it was permitting to be sent forth
into the Society and the world at large--after having cherished and nourished,
if not in some degree commenced,
the stand taken in New England and other places against the defection--after
having publicly testified to the fundamental nature of this stand,
and its conviction that it was taken in New England for the defence
of the truths always professed by faithful Friends--after all this,
it gave way to the popular clamor for a hollow peace even at the sacrifice of principle.

But did it sacrifice principle?
Certainly not, as a body, by any official and open avowal of unsound doctrines;
neither perhaps did the Hicksian meetings in 1828.
But, as it was in their case, actions speak a more potent language than words.
The Hicksites upheld those who did avow unsound doctrines.
Philadelphia Yearly Meeting retained in service members occupying influential positions,
who were thoroughly and openly identified with the
Gurney schism in doctrine and in practice.
It rejected all the claims of its New England brethren and others,
who were standing and suffering for the ancient faith,
to be recognized by it as the true and legitimate Society;
and saw them almost struggling for life under the
discouragements brought upon them by its neglect,
without reaching forth a hand to help them in their distressed, persecuted,
and weak condition.
On the other hand, it had practically encouraged those engaged in the defection,
by allowing complete amalgamation of membership with
such as had openly and bodily lapsed into the schism;
thus introducing floods of unsoundness within its own borders,
as well as sending its own members into the dangers
inseparable from fellowship with schismatic meetings.
It had entirely and repeatedly, and in the most pointed manner,
declined to interfere to stop these apostatizing measures;
and compromising and conniving at them had become the rule
of action with those who controlled its proceedings.
And in order to maintain its temporizing position,
it was constantly violating its own Discipline in relation to Separatists; and finally,
it had refused to listen to the earnest appeal of some of
its members for a rectification of these abuses;
so that the friends of right order and ancient principles were left without
hope of any favorable action to remedy the lapsing condition of the body.
They simply stood still in their testimony for the ancient compact,
while the Yearly Meeting was drifting into confusion and entanglement with schism.

The next meeting for Conference was a time of encouragement
to Friends to hold on their way,
trusting in the care of the Shepherd of Israel,
when all outward helps and reliances seemed to have failed.
The committee appointed at the previous meeting produced
an essay of an Epistle to the Members of the Yearly Meeting,
showing the causes of our extraordinary position; which was read and adopted,
and ordered to be printed for general circulation among the members of the Yearly Meeting.
This document, containing important information officially stated,
with serious charges of delinquency against Philadelphia Yearly Meeting,
was extensively circulated in a printed form, but never elicited any reply,
either from Philadelphia Yearly Meeting, the Meeting for Sufferings,
or individual members.
It appears to have been thought that the safest plan would be to take no notice of it.
The Yearly Meeting issued in 1861 a long epistle to its members,
chiefly reminding them of the value of various testimonies always held by the Society,
such as respected silent worship, ministry, plainness of dress and language,
inward retirement of mind, love and gentleness, etc.,
and against unsettlement and reasoning on religious truths, pride,
and worldly-mindedness, outward rites and ceremonies, political and party spirit,
etc.--with sentiments true and salutary in themselves,
but which had been many times over expressed in the same terms by the same parties.
But it is observable that in that long epistle there was no word
of warning against the series of unsound doctrines that were producing
such wide devastation--the great snare by which the enemy,
in this particular period,
was turning aside whole multitudes from the unity
of the faith once delivered to our forefathers.
Nor was there the slightest attempt to clear themselves from those very serious
charges which had been publicly and conscientiously brought against their course,
or even to allude to them or to the existence of the body which brought them;
thus evincing that they were not able to meet those charges,
or to defend the course they were pursuing.

The adjourned Conference Meeting at Fallsington, in the fifth month, 1861,
which now assumed the appellation of a "`General Meeting of Friends for Pennsylvania,
New Jersey, Delaware,
etc.,`" was engaged in an earnest travail and concern
for the faithful walking of its members,
in accordance with our high profession;
and was favored with renewed evidence that the Great Head
of the church condescended to own its deliberations;
and especially during the last sitting was the canopy of His love spread over the assembly,
to the contriting of many hearts before Him.
Subsequently it was agreed to hold the meetings quarterly.
At the ensuing General Meeting in the ninth month,
a concern arose and spread weightily over the meeting,
in regard to the true support of the discipline in
the scattered local condition of its members;
and resulted in the preparation and adoption of the following minute,
which was directed to be forwarded to each of the Yearly Meetings of Friends owned by it,
viz.:

This meeting issued last year an Epistle to our fellow members,
showing that the Yearly Meeting of Philadelphia, as controlled of late years,
has not only connived at, but practically promoted,
the great departure from the ancient ground of our profession,
connected with the unsound doctrines of Joseph John Gurney and his adherents.
Since that time, not only has that Yearly Meeting persisted in its course,
as therein represented by us,
but the Quarterly and Monthly Meetings subordinate thereto have
identified themselves with it by representation and otherwise;
thus partaking of the responsibility of identification with schism;
so that we can no longer conscientiously own them,
as meetings of the religious Society of Friends.

Under these circumstances,
and until Monthly and Quarterly Meetings can be again
held in a measure of the life and power of Truth,
which is the only authority for meetings of discipline,
we believe it will be right to advise Friends intending removal,
to make application to this meeting for its certificate;
so that after proper inquiry has been made, and no obstruction appearing,
they may be rightly joined in membership with such
meetings as may be held on the ancient foundation,
and clear of the defection which so sorrowfully prevails.
And it is our request,
that all certificates for Friends coming to reside
within our limits be presented to this meeting.

It is also directed that Friends intending marriage apply to this
meeting for its advice and assistance in the accomplishment thereof;
that all things may be done therein,
in the comely order which Friends were led into in the beginning,
and to the honor of Truth.
It is also our concern, that Friends who may feel their minds drawn,
in the love of the Gospel, to visit other portions of the Lord`'s heritage,
should lay such concern before this meeting, and receive its certificate of unity,
before engaging therein.
And Friends coming amongst us in like manner, from meetings beyond our limits,
are encouraged to lay their certificates before this meeting, as opportunity offers.
And, for the present,
all cases requiring disciplinary attention should be laid before this meeting,
for its judgment and care.

Subsequent to this,
the establishment of several small meetings for divine worship in different
places engaged the attention of successive General Meetings;
which series of needful measures for the preservation
of the order and integrity of the body,
it is not necessary here to detail.
On this subject, a minute adopted by the meeting held in the eighth month, 1862,
holds the following language:

An exercise spread over this meeting,
that the small companies who meet together may be concerned
faithfully to labor for the arising of life in their meetings,
that so they may indeed realize the declaration of the blessed Master,
"`Where two or three are gathered together in my name, there am I in the midst of them.`"

A travail was also felt on account of our dear brethren and sisters,
who have not yet given up to meet together in their respective neighborhoods
for the purpose of waiting upon the Lord for a renewal of their strength;
with desires that such may remember the language of David,
"`I will not offer a sacrifice to the Lord, of that which costs me nothing.`"
And we believe that Friends who thus give up will experience that our
Heavenly Father is a rich rewarder of those who diligently seek him.^
footnote:[In accordance with the concern of the General Meeting,
a meeting for worship had been held for some time in Friends`' Meetinghouse at Fallsington,
and one at Bristol;
and afterwards one was reported to the General Meeting as having been opened in Philadelphia,
twelfth month 22nd, in a house rented in Coates Street,
after having been previously held for awhile in the
dwelling of one of the members--one at Horsham,
in Friends`' meetinghouse, fourth month 1st, 1862--one at Germantown,
in a Friend`'s house, eighth month 21st, 1862--one in Fallowfield, Pa., sixth month 7th,
1863, in a room granted for that use by a Friend;
having been previously held in his own dwelling near Ercildoun.
A meeting also was held at London Britain, in a Friend`'s house,
which was afterwards moved, sixth month 10th, 1866,
to the basement of a schoolhouse hired near Strickersville.
Various other meetings were afterwards added, as required in different places,
including one at Elklands, in Sullivan County, Pa.]

In the ninth month, 1863,
the General Meeting issued regulations for the accomplishment of marriages,
in order that the requisitions of the Discipline, in that important matter,
might be complied with, as nearly as possible, in our scattered condition;
and at this time, likewise,
a meeting of ministers and elders was directed to be held once in three months.
The reestablishment of Monthly Meetings for Discipline engaged
at various times the attention of the General Meetings;
Friends desiring to move in so important a concern under the pointings of best wisdom,
and a sense of the right time having come for it.
For awhile, the members were encouraged to meet together once a month,
according to their convenience of distance from certain central points,
but without engaging in any further disciplinary business than
the reading and consideration of the Queries and Advices;
and even this was found to be of a salutary tendency, promotive of true love and unity,
and reanimating to the solitary ones in their tribulated walk.
But it was still felt that something further was needed in the same direction,
that the Church might be "`builded as a city that is compact together.`"

A few here and there objected to the reestablishment of Monthly Meetings,
fearing we were becoming too formal, and depending too much on disciplinary arrangements;
and some declined, on a similar ground,
to have their names and their children`'s names entered in the list of members,
alleging that they wished their names entered in the "`Lamb`'s book of
life,`" and hinting as if they thought the two were incompatible.
These eventually lost their standing in the Truth and wandered away;
but the church was preserved from being shaken by their departure.
At length, in the ninth month, 1866, a Committee,
having in charge the subject of the right holding of the subordinate meetings,
made a report of their sense, in regard to holding Monthly Meetings for Discipline;
which was united with by the General Meeting, and is as follows:

To the General-Meeting

The Committee appointed to consider the subject of
the right holding of our religious meetings,
and what additional steps it might be right to take
to promote the due support of the discipline,
report: That they have all met,
and were enabled solidly to deliberate on the subject of their appointment.
The right sustaining of true gospel order among the
small remnants of the Society in these parts,
was felt to be a subject of great weight and importance,
early after the first holding of the Conferences which resulted
in the establishment of our General Meeting;
and in order that no loss might be sustained in that
respect in our weak and scattered situation,
it was concluded that the General Meeting should exercise
the disciplinary functions of Monthly and Quarterly Meetings,
until such time as Friends might be enabled again to hold
Monthly Meetings for discipline to the honor of truth.

We have sensibly felt, that "`except the Lord build the house,
they labor in vain that build it; except the Lord keep the city,
the watchman waketh but in vain;`" and surely,
vain will be all attempts made in our own strength or wisdom, to sustain his cause.
But we believe the time has come when it would be right to endeavor
to promote the more efficient exercise of the discipline,
and likewise to relieve the General Meeting from accumulating business,
by the holding of two Monthly Meetings for discipline within our limits,
in accordance with the provisions of our Discipline;
to be held jointly of men and women Friends.
We therefore propose that Friends of Fallsington and Bristol Meetings,
together with the scattered members in Bucks County, Pa., and in Burlington County,
N+++.+++ J., should form one Monthly Meeting, to be called Falls Monthly Meeting of Friends;
and that Friends residing in other places within the limits of this General Meeting,
should, for the present, compose another Monthly Meeting,
to be called the Monthly Meeting of Friends, held in Philadelphia.

The two Monthly Meetings, thus directed to be established,
were opened in the ninth month, 1866;
both being attended by a committee of the General Meeting, appointed for the purpose.
They have since increased to four in number,
through the annexation of Salem Monthly Meeting, in Ohio,
and Nottingham and Little Britain Monthly Meeting, in Maryland.^
footnote:[Since the erection of a new meetinghouse by Friends of Philadelphia,
on Olive Street, west of North Eleventh Street,
it has been agreed to hold the General Meetings in the sixth and ninth months as before,
at Fallsington, and those in the twelfth and third months in Philadelphia.]
Thus Friends went gradually but steadily onward, taking one step after another,
as they were enabled, towards rebuilding the walls that had been broken down;
quietly leaving the Yearly Meeting to take its own course, in tampering with the schism.
But they were not, meantime, nor had they expected to be,
free from their share of trials from false brethren;
or superficial ones not truly baptized for this warfare,
who had joined them from various motives; or those who, through unwatchfulness,
fell from a measure of grace formerly known,
and became alienated from the way of truth which they had once
advocated and clearly seen to be the way for them to walk in.
Here and there was one who became entangled in high notions of spiritual attainment,
and thus indulged in strange imaginations,
which not being sanctioned by Friends generally, such an one struck off from the track,
and walked no more with them.

A few others, equally unwatchful, being caught by a spirit of self-righteousness,
began to blame their brethren and sisters who did not see exactly as they saw, and,
because they could not have their own way,
they also went off with a feeling of alienation.
Still another class, entangled in the snare of over-weening personal attachment,
and thinking of some "`more highly than they ought to think`"--like the women who helped
to delude James Nayler in former days--became strangely impetuous in their ways,
contemning the order of truth and the tender advice of Friends
deeply concerned for their safety and the welfare of the church,
and had to be disowned.
All this was very discouraging.
Indeed, the enemy of all righteousness seemed bent upon rending this little company,
and thus frustrating their testimony.
But the Lord sustained it,
and even these sorrowful occurrences afforded evidence of the vitality of the body,
in that it was enabled to cast off the diseased or dead branches,
instead of weakly allowing them to remain--for the sake
of a hollow peace--and bring forth unwholesome fruit.
The latter class above mentioned, we shall meet with in a portion of the ensuing chapter.

It is not within the scope of this work to trace particularly the further transactions
of this branch of the Smaller Bodies of Friends (holding its General Meeting in Pennsylvania),
since its establishment as an organized body independent
of the lapsed Yearly Meeting of Philadelphia.
Thus much it seemed needful to say, to show its true position.
But it may be safely acknowledged, with thankfulness to the Great Head of the church,
that it has from time to time, through all its trials,
felt the sustaining help of divine love and condescension.
It has had various comfortable additions to its numbers; and is believed to be,
since the cessation of the disturbing elements which have just been alluded
to (and which ought to have been reasonably expected to arise for a time),
in a more encouraging state of unity and of consistency generally with our profession,
than those looking upon it from an outside point of view may be aware of.
Gifts and qualifications for service in the church have not been withheld from its members,
but graciously entrusted to brethren and sisters with an evidence of the true life,
for the edification of the body,
and for the invitation of others to taste and see
for themselves the goodness of the Shepherd of Israel;
and this greatly beyond desert.

With nothing to boast of individually or collectively--a small and weak remnant
of a backsliding generation--they are striving as it were against wind and tide,
to hold up the standard of the ancient faith, which was, until recent times,
so faithfully sustained by Philadelphia Yearly Meeting.
But while the departures from this standard have been constantly increasing,
the Yearly Meetings of Philadelphia and Ohio have stood mournfully gazing at the desolations,
with their hands tied by the fallacious dogmas of the middle policy;
so that for a quarter of a century past they have absolutely done
nothing effectually to stay the flood overflowing the whole land,
or to encourage in the least degree those who were concerned to
be found standing openly and unmistakably against its inroads.
