== Chapter XVII.

[.chapter-synopsis]
* Opposition in England to the New Doctrines Meetings Organized There, Independent of the Lapsed Yearly Meeting of London.

Now at length we turn back to Great Britain,
which we left about the time of the disastrous liberation of Joseph John Gurney, in 1837,
to visit America.
We have seen that London Yearly Meeting had officially adopted
and promulgated at least one of his erroneous sentiments,
and that a very important one, in its epistle of 1836.
During his absence from England, and after his return,
the new principles which his writings had been the
chief means of developing in the Society,
found plenty of advocates,
and almost everywhere took the place of the ancient principles of Friends,
producing a corresponding change in life and conduct.
There were, however,
many Friends who saw their contrariety to the views of those who had always
been considered as the instruments employed in founding the Society,
and some of them failed not to testify against them as productive of schism.^
footnote:[Notwithstanding the false step taken by London Yearly Meeting in 1836,
in its declaration regarding the Scriptures,
it was not yet prepared to allow of all manner of open attacks
on its ancient testimonies in its own presence.
In 1838, William Dilworth Crewdson, of Kendal,
who had formerly been clerk of the Yearly Meeting,
undertook to defend before the Yearly Meeting the
conduct of some members in submitting to water-baptism,
endeavoring to show that Friends had all along been mistaken
in their views of the non-necessity of this rite.
He was soon checked by George Stacey, the clerk of that year,
and informed that he could not be permitted, in that meeting,
to call in question the principles of the Society.
After this, however, W. D. C. again rose to pursue the same subject;
whereupon he was peremptorily requested by the clerk to take his seat,
as it was clearly out of order.]

Among the most faithful of these advocates of our ancient principles in that day,
were George and Ann Jones, of Stockport.
They had witnessed the devastations produced by a former schism, in America,
and had faithfully testified against the false doctrines of Elias Hicks;
and now they plainly perceived the approach of a storm from an opposite quarter,
and warned their friends to beware of it.
George Jones being affected with serious illness in 1839,
and apparently near his dissolution (though he subsequently revived,
and did not depart this life until the year 1841),
issued in manuscript an address to the members of
the Yearly Meeting of Ministers and Elders,
as his conscientious testimony and warning against the novel views.
This testimony is as follows:

[.embedded-content-document.testimony]
--

[.salutation]
Dear Friends:

In the feelings, as I apprehend, of the pure love of the truth,
it seems with me to express my fervent desire that
those things which tend to promote our peace,
and things whereby we may edify one another, may prevail in our minds.
Some of you know that I manifested my concern on account of the "`Morning Meeting.`"^
footnote:[The body then having the oversight of intended
publications relative to our religious principles.]
This concern still remaining on my mind,
I believe it right to communicate something further on the subject.
It feels trying to me to have thus to plead with my friends respecting the "`Morning
Meeting;`" but I believe I must say it has been a great trouble,
both to me and to many other Friends who love the truth,
that the members of that meeting should have passed such
things as they have done in J. J. Gurney`'s writings,
in his work entitled Religious Peculiarities, etc.,
but more particularly in the revised edition with additions.

In these publications there is much that I consider very
contrary to the principles and doctrines which we,
as a people, make profession of,
and which we fully believe to be consistent with the Scriptures of truth.
Also in his Essays on Christianity, which I suppose did not pass the Morning Meeting,
there is much that is objectionable.
In this publication there is held forth that which Friends
and many others have declared against as unsafe,
dangerous, and unauthorized by the Scriptures.
I mean the speaking of the Father as a Person, of the Son as a Person,
and of the Holy Spirit as a Person.
There are several extracts from Friends`' writings,
in the first chapter of Thomas Evans`'s Exposition of the Faith of Friends,
showing the inconsistency and unscriptural mode of so speaking.
Richard Claridge has also written a tract, giving not only his own views upon it,
but the views of many Friends and learned authors of different religious denominations,
such, for instance, as Bishop Burnett, Calvin, Luther, Jeremy Taylor,
Archbishops Tillotson and Usher, with many others,
whose sentiments are well worthy of our attention.

The injury J. J. Gurney`'s writings have done, and are still likely to do,
to our Society, and to the cause of truth, seems to me to be very great,
and I cannot but conclude that the affectionate part, and the wisdom of man,
must have prevailed in the minds of the members,
or they would not have suffered what they did to pass.
And as respects the Essays,
did not that work require the attention of the Meeting for Sufferings,
to whom is entrusted a general care of whatever may
arise during the interval of the Yearly Meeting,
affecting our religious Society, and requiring its immediate attention?
And should a work like this, so opposed to what the Society has always maintained,
be permitted to be printed and published, and spread extensively, as this has been,
by any member, more especially by one in the station of a minister,
without that meeting`'s declaring against it?--seeing, moreover,
that works coming from such an one may, by those not acquainted with our principles,
be thought consistent with them, whilst they are quite the reverse.
It is my fervent desire, that Friends who have in any way been improperly influenced,
may be favored to submit to the renewed baptism of the Holy Spirit,
that so the Divine Anointing, which alone gives clearness of vision,
may be afforded them, and truth, without mixture, supported and propagated.

For much mixture, and consequently much weakness, has got in,
and has for some years prevailed among us.
Otherwise John Wilkinson, Elisha Bates,
and Anna Braithwaite would not have been allowed to travel together,
to hold such meetings, and to propagate such sentiments among the young people,
as they have done,
to the occasioning of a great burden and deep concern in the minds of the living members,
where such meetings have been held.
Neither would the Yearly Meeting of Ministers and Elders have given
a certificate of approval of Elisha Bates`'s preaching;^
footnote:[Mentioned in Vol.
I of this work.]
which act was also a grievous burden to many well concerned Friends.

These things have rested much on my mind, particularly during my present illness;
and it must be very evident that J. J. Gurney`'s interpretations of the
Scripture are so contrary to those of the Society from its first commencement,
that if his interpretations are to prevail, then the Society must change its ground,
and become an inconsistent mixture of Quakerism and Episcopalianism.
This I believe the great Head of the church will never permit;
but those who are unfaithful and turn aside,
and prove themselves altogether unworthy to support
the standard and testimonies of truth,
will be rejected and scattered, whilst others will be brought in, and prepared,
and qualified to unite in maintaining pure, primitive Christianity,
and in showing forth the Lord`'s praise among the nations.

These things deeply impressed and afflicted the minds of our dear friends,
Thomas Shillitoe and John Barclay, who are in mercy gathered to their everlasting rest.
And now, in thus relieving my mind, I have a hope I shall,
through the unmerited mercy of God in Christ Jesus, be favored to die in peace,
and to enter one of those mansions which our blessed Lord
declared he went before to prepare for his followers;
for those who not only believe in his outward appearance,
but in the fulfilling of his promise, that he would come again,
and that he who was with them should be in them; without which second appearance,
and faithful following of Him in spirit, and submitting to his purifying power,
how can we be prepared for acceptance with him?

In looking over the foregoing address, you, my friends,
are afresh brought very near to me, with feelings of fervent desire,
that we may not be of the number of the "`wise and prudent,`" from
whom our Lord said the things whereof he spake were hid;
but rather that we may be of the babes, unto whom they are revealed;
having our dependence on our Almighty Father, for guidance, preservation, and support,
in the way to the kingdom of eternal rest and peace.

[.signed-section-closing]
I remain your sincere friend,

[.signed-section-signature]
George Jones.

[.signed-section-context-close]
Stockport, 9th of fifth mo., 1839.

--

After his decease, B. Seebohm spread a report, which was widely circulated,
that George Jones had subsequently expressed regret at having given forth this testimony;
whereupon his widow, that valiant minister of the gospel, Ann Jones,
in order to contradict so false a statement,
gave forth in manuscript the following testimony for the truth:

[.embedded-content-document]
--

[.signed-section-context-open]
Stockport, 25th of twelfth mo., 1845.

It is very painful and grievous to me to find that there is in circulation,
and widely spread, a report, a false report, respecting my dear husband;
and also respecting our dear aged friend, Thomas Shillitoe,
that they both retracted and regretted the plain unequivocal
testimony which they separately gave forth,
for the clearing of their own minds or spirits,
and also as their testimony for the Truth as it is in Jesus--stating that
J+++.+++ J. G.`'s writings are not in accordance with those of our early Friends.
Any one who reads and compares them must know this,
and what but an aversion to receive the Truth in the simplicity and love of it
can occasion such a stir and attempt to make a thing appear what it is not?
Let those who cry out about the harmony and peace of the Society being disturbed
or broken take care that they are not found among the sowers of discord.
My dear husband was very ill in the beginning of 1839;
neither himself nor those who saw him expected his recovery.

On looking towards the final close, his spirit became increasingly oppressed,
in considering the desolated, backsliding, worldly-minded state of many among us,
which he believed to be very much owing to the attempts made and making
to modify or modernize the principles and practices of the Society.
In this state he could not get any rest or peace of mind until
he had employed an attendant to put down from his dictation,
his plain unequivocal testimony to the Truth against J. J. G.`'s writings;
this done he was easy and quiet, and said he did not feel anything in his way.
From that time, unexpectedly to all around him, he recovered;
took a lively interest in the affairs and welfare of the Society;
attended the Yearly Meeting in 1840.

George Jones lived till twelfth month, 1841.
In the time he had many opportunities of reading and reflecting upon what he had written,
which was invariably satisfactory and relieving to him.
I am not afraid to say and give it under my hand,
that he never wavered or expressed to any one a syllable like retracting or regretting
having written and circulated as he did that testimony to the Truth;
so far from that, it continued and remained to be a relief to him until his last illness,
when he had nothing to do but peacefully lay down his head and sleep in Jesus.
May my last end be like his!

[.signed-section-signature]
Ann Jones.

--

After this was circulated, B. Seebohm acknowledged that the report had been a mistake.

In 1840, William Gauntley also, a friend of Bakewell in Derbyshire,^
footnote:[William Gauntley was a worthy elder of Rakewell,
who came into the Society through convincement,
giving up many outward advantages for the sake of a conscience void of offence,
he died in 1860, at the age of 80 years.
"`He was zealously concerned to hold forth the doctrine
of the Holy Spirit`'s direct teaching;
being very jealous of any sentiments that tended
to obscure a belief in this paramount Christian privilege;
yet he truly and highly esteemed the Holy Scriptures,
believing them to be given for our instruction, edification, and comfort,
and that they are able to make wise unto salvation,
through faith which is in Christ Jesus.`"
He "`deeply lamented the many specious innovations witnessed
amongst us in this day of ease and outward prosperity;
and was frequently engaged, publicly and privately, in faithful testimony against them.
His labors in this respect were blessed,
and contributed to sustain the faithfulness of others.`"]
addressed the following letter to the Meeting for Sufferings, of London,
respecting the unsound doctrine enunciated by the
Yearly Meeting in its General Epistle of 1836,
in relation to the Holy Scriptures.^
footnote:[See Vol.
I.]
But it was not even read by that body,
though the subject was of vital moment to the integrity of the Society.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Meeting for Sufferings

[.salutation]
Dear Friends:

I address you upon a very important subject.
It is on two points of doctrine,
contained in a paragraph of the Yearly Meeting Epistle of 1836,
relating to the Scriptures.
The first part of that paragraph is worded thus:
"`Often as our religious Society has declared its
belief in the divine authority of the Holy Scriptures,
and upheld the sacred volume as the only divinely authorized
record of the doctrines of true religion.`"

Now, friends, I apprehend this passage in the paragraph contains a word which, there,
is not only contrary to the truth itself, but contrary to fact: for,
with regard to the fact, I do not believe that the Society has often,
or even once before upheld the sacred volume as "`the
only divinely authorized record,`" etc.
It is possible that such a thing may have happened without observation by myself;
but I am fully persuaded that it is not so.
I have been a member of the Society more than thirty years.
I have, I believe, read every Yearly Meeting Epistle given forth in that time.
I have also read works of those ancient worthy friends, Fox, Penn, Barclay, and others;
and I have heard testimonies of many ministers of the gospel amongst us;
but in all that time, and from all those sources,
I have no recollection of seeing or hearing anything of
the like import as that which is conveyed by the word "`only`"
in connection with the rest of the passage where it occurred,
neither did I expect ever to see or hear anything of the kind from the Society;
because I am fully convinced the doctrine is unsound.
I am not the only one of this opinion; for there are several with whom I am acquainted,
who take the same view, believing the assertion to be groundless.

Again, further on, in the same paragraph, we find these words:
"`and there can be no appeal from them to any other authority whatsoever;`" and again,
"`They are the only divinely authorized record of the doctrines
which we are bound as Christians to believe,
and of the moral principles which are to regulate our actions;
that no doctrine which is not contained in them can be required
of any one to be believed as an article of faith.`"

Before making any other remark, let me state what I understand by the word, "`Record.`"
It is this, "`An authentic written testimony.`"
Now let us consider the soundness,
or rather the unsoundness of the doctrine contained in the aforesaid paragraph.
And, first, it may be asked.
What grounds have the Friends,
for entertaining and promulgating such an opinion as is there expressed?
Is it Divine Revelation?
That is, Do Friends know this matter by divine revelation, and write by that guidance?
If it were so, then the paragraph itself would be a divinely authorized Record,
and that would be strikingly inconsistent with the contents of the paragraph,
and a thing impossible.
Well then.
Friends cannot take that ground.

We have next the Scriptures.
Can such a doctrine be found in them?
Undoubtedly not.
Ages passed away from beginning to end, whilst the Scriptures were by parts,
from time to time, written by the prophets and apostles, or ministers of the gospel;
and it is plain that none of all these could declare, in their respective days,
that there would be no more divinely authorized records written after
they had written (unless we might suppose it of the last of them);
for,
a full contradiction of any such prediction or declaration must have been the consequence,
in the writing of every successive inspired penman.
They might indeed, if it had been the divine will,
have foretold and fixed the period when divine writing should cease;
but have they done so?
Who ever saw in the Scripture a prophecy or declaration to the effect,
that from and after such a time,
the Almighty would no longer authorize any writing
in relation to the "`doctrines of true religion?`"
Nobody.
It is not there.
And if not there, then, according to the rule laid down in the aforesaid paragraph,
we are not bound as Christians to believe the doctrine, but rather to disbelieve it.
The Scripture then, it appears, is not a ground which will support what I shall call,
The New Opinion of Friends.

Having shown that the New Opinion of Friends cannot be sustained
on either of the two distinct grounds before mentioned,
it maybe next asked, On what ground, then, can such New Opinion be supported?
I cannot see anything else for it but this, Their own understanding.
I shall, therefore, assume that to be the case, and write as if it were actually so.
I say, then, Friends have, in effect,
stated upon the authority merely of their own opinion,
that there positively is not in existence, any writing of divine authority,
except what is at present bound up in the Bible.
Is this not too much to say upon such limited knowledge?
Have those Friends visited every nook and corner of the world?
Have they searched every library, closet, and shelf?
Have they turned over the pages of every book and examined every paper?
All this, I apprehend, ought to be done, before stating the matter as a fact,
if the truth of it be to rest upon the evidence of their understanding,
unaided by divine revelation.

The Friends have, indeed, quoted some passages of Scripture,
seemingly for the purpose of confirming their view; that is,
that the Scriptures are the only divinely authorized record, etc.,
and that there can be no appeal from them, etc.; but those passages do nothing like that.
The first of those quotations is this:
"`The prophecy came not in old time by the will of man;
but holy men of God spake as they were moved by the Holy Ghost.`"
This was the declaration of the apostle Peter, and we believe in the truth of it.
Well, but does this declaration of Peter regarding "`old time`"
shut the mouths of "`holy men of God`" in after time?
Nay, surely; for Peter himself, as well as others,
did afterwards write those things which the Friends say are of divine authority.

The next of those quotations is from the apostle John.
It is this: "`These are written that ye might believe that Jesus is the Christ,
the Son of God; and that believing ye might have life through his name.`"
Well, then, John declared he wrote that they might believe;
but he did not say that no more should be written for the like purpose.
He had just before written thus:
"`And many other signs truly did Jesus in the presence of his disciples,
which are not written in this book,`" and then follows that before recited,
"`but these are written,`" etc.
And again, we find he wrote (21:25),
"`And there are also many other things which Jesus did, the which,
if they should be written every one,
I suppose that even the world itself could not contain the books that should be written.`"
It appears by this, that John had no idea of any limitation to divine writing,
but the want of room to contain the books; so we may go to the next quotation.
It is from the epistle of Paul to Timothy:
"`From a child thou hast known the Holy Scriptures,
which are able to make thee wise unto salvation through faith which is in Christ Jesus.
All Scripture is given by inspiration of God, and is profitable for doctrine,
for reproof, for correction, for instruction in righteousness;
that the man of God may be perfect, thoroughly furnished unto all good works.
Whatsoever things were written aforetime were written for our learning, that we,
through patience and comfort of the Scriptures, might have hope.`"

By these texts we understand that the apostle Paul
wrote to Timothy,
saying in effect, that the Scriptures, extant when Timothy was a child (which did not,
in all probability, include any part of the New Testament,
and certainly not the epistle Paul was writing),
were able to make him wise unto salvation through faith,
and were for perfecting the man of God.
Well, then, if those Scriptures could do so much, why did Paul write any more?
No doubt he wrote as a minister of the Gospel, to promote the spreading of the truth;
not superfluously;
and he has not written anything from which we can infer
that other ministers of the gospel might not do the like.
Then, if his writings as a minister of the gospel are considered of divine authority,
why shall not the writings of any other minister of the gospel, as such,
be considered the same?^
footnote:[Not that we would by any means put our
own writings on an equality with the Holy Scriptures,
but as some of them possessing a degree of the same authority.]
I am convinced that hitherto nothing is found to favor the New Opinion of Friends.

The last quotation from Scripture on this subject is the words of our Blessed Lord,
"`The Scripture cannot be broken!`"
True; but what then?
Can there be, therefore, no more divine writings?
The contrary is obviously the fact:
for this saying of our Blessed Lord related exclusively to the Scriptures then extant;
and the Friends allow that more Scripture was afterwards written by divine authority.
And now,
having recited and considered all the scriptural
quotations made by the Friends upon this subject,
and having found they do not, in the least degree,
sustain the expressed opinion of the Friends relating thereto; which opinion is,
in substance, that there were no other,
and were to be no more divinely authorized records
besides those now bound up together in the Bible;
I purpose next to point out something that has been said of a contrary
tendency by him who was first of all called "`Quaker.`"
(See George Fox`'s Journal, page 212.) He (George Fox) says he "`was sent,
in the name and power of the Lord Jesus, to preach again the everlasting gospel.`"
Page 88, he says, "`I wrote also to William Lampitt, the priest of Ulverstone, thus:
'`The word of the Lord to thee, O Lampitt! a deceiver,
surfeited and drunk with the earthly spirit, rambling up and down in the Scriptures,
and blending thy spirit amongst the saints`' conditions.`'`"
George Fox afterwards said in the same letter,
twice, "`To thee this is the word of God`"--and once after again,
"`When the eternal condemnation is stretched over thee,
thou shalt witness this to be the word of the Lord God unto thee.`"

Besides the above, George Fox wrote another epistle to the followers of Lampitt,
which epistle he begins with,
"`The word of the Lord God to all the people that follow Priest Lampitt,
who is a blind guide.`"
There are several other like instances in George Fox`'s Journal;
but these are enough for our present purpose.
First, then, I say that George Fox`'s Journal is a Record; that is to say,
an authentic written testimony: next,
that it contains "`doctrines of true religion,`" and nothing from him contrary thereto.
Moreover, he says that what he wrote as above referred to was of "`the word of the Lord.`"
The word of the Lord is Divine.
It is +++[+++of]
the Holy Spirit.
Now, then, I say, that which George Fox wrote then, and which has been handed down to us,
is a divinely authorized record of doctrines of true religion,
or else George Fox was an impostor;
but I believe him to have been truly an eminent apostle.

Having, perhaps,
dwelt sufficiently long on the first of the two points of doctrine before adverted to,
I now come to the second, which is this:
"`And there can be no appeal from them to any other authority whatsoever.`"
I have recollected reading aforetime,
and have now read in the fifteenth chapter of the Acts of the Apostles,
an account of a dispute on a certain point of doctrine.
I find not there that the Scripture only was the authority appealed to;
but that in the first place it was determined by
some of the disputants to go up to Jerusalem,
unto the apostles and elders, about the question.
And the apostles and elders came together for to consider the matter.
After there had been much disputing (notwithstanding
they had the Scriptures of that day),
they, that is, the apostles, and elders, and brethren, came to this conclusion:
to write letters to the Gentile brethren; which in substance were this:
That it seemed good to the Holy Ghost and to them,
to lay upon the Gentile brethren no greater burden
than certain things named in those letters.
I find, then, from this account, that the appeal came to,
and was decided ultimately by the Holy Ghost.

And now I would ask Friends this question,
"`What is that which assures you the Scriptures are true?`"
To answer, Paul himself said so, and the other apostles said so, will not do;
for the false prophets would vouch for their falsehoods in that way.
Jesus said (John 5:31-32), "`If I bear witness of myself, my witness is not true.
There is another that beareth witness of me;
and I know that the witness which he witnesseth of me is true.`"
Now if it were necessary that Jesus himself should have another witness,
it surely cannot be surprising that Paul and other writers
should need also another witness for what they have written;
and that that witness is the Holy Spirit.
I do not desire to enlarge upon the subject, but wish to leave it here;
only desiring that if possible, this blot in the records of the Society may be erased,
or otherwise so dealt with as to cause the least possible damage.

[.signed-section-signature]
W+++.+++ G.

--

Of similar tenor was a testimony left by James N. Richardson, an elder of Glenmore,
in Ireland, written in the year 1846,
but placed by him in the hands of two of his friends, three days before his decease,
in 1847.
In the course of his remarks on the afflicting condition of the Society, he says:

[.embedded-content-document.testimony]
--

There seems arranged so much talent, so much wealth, and so much worldly influence,
combined with holding high stations in the Church, that things are likely, for a time,
to be carried in a wrong course.
These new views are agreeable to the people, who like an easy, worldly religion.
Patient waiting exercise is irksome--does not suit the itching ears--so,
instead of this right qualification,
waiting to be baptized into a sense of the state of meetings,
and concerned to feel the renewal of divine power,
the people are fed with the mere recital of the truths of the gospel,
and given to rest in an assent or belief in the ever blessed sacrifice,
and what our dear Lord has done for mankind without us.
By this belief they are taught to think they are safe,
without leading to deep searching of heart, and continued watching unto prayer,
which will produce good works or fruits, and progress to sanctification,
which must be attained before we are in a capacity to witness justification.
Hence we hear (especially in England) long, lifeless sermons,
calculated to fill the head, but never reach the heart.
Oh, how have I been tried with these communications, like words of course,
all the same from time to time, till the mind is wearied,
and the heart that is panting for living bread is sick!

--

After this, he proceeds to give his view of the heterodox writings of Gurney and Ash,
as likely to be of temporary ascendency only--(would
that it had resulted so!)--and his belief,

[.embedded-content-document.testimony]
--

That the testimonies of truth, and the Christian doctrines given to this people to bear,
will not be allowed to fall to the ground, but that an honest, humble-minded,
simple people will be enabled again to raise the standard of truth,
and to promulgate the same, and carry on the work designed,
thus marred by zeal and creaturely activity.

--

But all these warnings were of no avail with the leaders of the people.
In 1845, John Wilbur,
having published in America A Narrative and Exposition of
the Proceedings of New England Yearly Meeting in his case,
in which the ground of his dissatisfaction with J.
J+++.+++ Gurney`'s writings was clearly developed,
the latter addressed a communication to the editors
of the London "`Friend`" dated twelfth month,
17th, of that year (which they published),
announcing his position in regard to the very serious
charges of unsound doctrine in his writings,
contained in John Wilbur`'s book.
But strange to say,
in this communication J. J. Gurney acknowledged that he had not read John Wilbur`'s book,
and did not entertain any intention of replying to it,
as he should consider that he was "`travelling entirely out of
his record,`" having long had reason to believe that he +++[+++John Wilbur]
was indulging a wrong spirit,
and having often witnessed the verification of the old proverb,
"`whoso toucheth pitch shall be defiled thereby.`'`" After this exhibition
of supercilious contempt--as if aware that the covering was too short,
and too transparent, for him to take safe refuge under it--he further announced,
that "`if any Friend of weight and consistency`" would furnish him, in writing,
with "`such passages as may be deemed unsatisfactory,`" he would
lay such communication before the Morning Meeting in London,
and in case of their not being satisfied with his explanations, he would "`modify them,
strike them out, or even publicly renounce them, in whole or in part,
as the meeting may think proper to advise;`" adding, however,
that his sentiments on essential points were "`in no degree
changed`" since the date of his earliest publications;
and "`nothing, I trust,
would induce me to sacrifice one particle of the truth as it is in Jesus,
to please or satisfy any man or body of men whatsoever.`"

In saying this,
he well knew that an abundance of passages proving the "`unsatisfactory`"
tendency of his writings had been already adduced.
He well knew, too, that he and his adherents held the helm of the Morning Meeting,
and that they would by no means condemn any doctrine which he earnestly advocated.
He knew also full well, that with the tacit connivance of that Morning Meeting,
he had charged the early authors in the Society with "`serious
errors`" in their interpretation of "`the truth as it is in Jesus.`"
But as to John Wilbur`'s book,
and the exposures therein contained of his own palpable errors,
and of the gross outrages committed by his followers in New England in his defence,
it is probable that he prudently thought, the less said the better.

About the same time, or shortly after,
John Wilbur`'s Narrative and Exposition was attacked
in a pamphlet entitled Calumny Refuted,
or a Glance at John Wilbur`'s Book; said to have been prepared in Burlington, N. J.,
by three of J. J. Gurney`'s female admirers, but sent over to England to be published.
As the main point of attack was the contrast of doctrines,
contained in the Narrative and Exposition,
the original writer of that contrast replied to this attack in a tract of 47 pages,
also first published in England, in 1846, and afterwards in Philadelphia, entitled,
Is it Calumny, or is it Truth?
in which the false positions of the authors of Calumny Refuted were exposed,
the contrast was reprinted in full, and defended from their animadversions,
and fresh proof was given of the fundamental unsoundness of Gurney`'s writings.
The next year, as we have already noticed in the ninth chapter, J. J. Gurney,
partly to serve a legal purpose in America--where unhappily a suit was pending,
respecting some property, in one of the courts of New England--and partly,
it is supposed,
in consequence of representations of the necessity of doing
something to satisfy many even among his own adherents,
issued a declaration of faith,
signed by himself and attested by the mayor of Norwich and two justices of the peace.
This document, however flimsy a veil, was eagerly seized,
widely circulated over America,
and implicitly believed to be sufficient proof of his soundness in the faith.^
footnote:[Of its deficiency herein, see chapter 9 of this volume.]

Joseph John Gurney died in 1847, in the fifty-ninth year of his age.
The Yearly Meeting of London afterwards approved and adopted for publication
the testimony of Norwich Monthly Meeting concerning him,
in which the statement was made, that from his twenty-fourth year,
"`he maintained with holy boldness the principles and testimonies of the Society,
through the remainder of his life;`" and their belief was expressed,
in reference to his published writings, "`that in these undertakings, as in every other,
he was actuated by a sincere desire to promote the glory of God,
and the welfare of his fellow-men; and at the same time to maintain,
with unflinching integrity, '`the truth as it is in Jesus.`'`" In regard to his ministry,
their testimony was,
that "`he evinced a firm attachment to the principles of our religious Society,
and a deep concern for the upholding of all its testimonies!`"
Surely these were emphatic expressions, made in deliberate and chosen language;
and the Yearly Meeting of London,
in endorsing such declarations without qualification or abatement, became,
without room for question,
equally accountable for his doctrines--equally involved in an acknowledgment of unity
with them--as was the Green Street Yearly Meeting of the disciples of Elias Hicks,
in regard to his infidel views, when they recorded his presence in their assembly,
with an expression of unity with him as a minister.
We know that in this instance the record made on the occasion was considered by Friends
generally as unquestionable proof of their fellowship with him in his well-known doctrines.

London Yearly Meeting continued to liberate for visiting the United States,
ministers who fraternized with the advocates of innovation,
and thus encouraged the revolution which had spread from
within its own borders over the whole surface of the Society.
And in all cases of separation which occurred as a result of this revolution,
from that of New England downward,
the avowed sympathies of London Yearly Meeting were with the promoters of innovation.
The plea made use of at first, was,
that they must acknowledge the main body with the old clerks, correspondents, etc.;
but when the separation occurred in Ohio in 1854, this plea did not suit;
as the party attached to J. J. Gurney, who made that separation,
were greatly and obviously in the minority, and had, in an irregular manner,
appointed another clerk; so that London Yearly Meeting disregarded their former plea,
and acknowledged even the Smaller Body in this case,
because this body was composed of their real brethren,
advocating the same new principles and practices.

One year rolled over another,
adding to the mass of change in the character of the Society.
In some of the large meetings in England,
very few indeed could be recognized by their appearance as professing to be Friends.
Large numbers, not only of the private members, but also of the ministers, elders,
and overseers, had ceased to appear in the plain, simple garb of Friends,
and could not be distinguished from the people of the world, either in their dress,
their language, or their manners.
The "`offence of the cross`" seemed also to have ceased,
in regard to the adornment of their habitations.
Simplicity and self-denial herein had become obsolete terms with the great bulk of those
who had the means of gratifying "`the lust of the eye and the pride of life.`"
Indeed, the endeavor seemed to be, with very many,
to advance as near to the rest of the world as could possibly
be done with any decent degree of decorum.

And not only had the self-activity, inculcated by the new system,
piled up a vast amount of work to be done,
under the guise of "`doing God service,`" "`working for Jesus,`" and "`leading
souls to Christ,`" in the way of meetings and associations of young and inexperienced
persons for this or for that (yet with little qualification for the Lord`'s work),
in imitation of high professors of other names and other systems of action;^
footnote:[In mentioning these things,
it is by no means the author`'s intention to discourage good works,
which have always characterized or accompanied a living faith.
Much good, much alleviation of the evils attending unregenerate mankind,
and much increase of true knowledge of the wonders of nature and art,
have been the result of human intelligence and industry.
The objection is not to works of charity or benevolence,
or to a watchful union with our fellow citizens in such efforts as tend
to the amelioration or substantial improvement of the condition of man;
but to the substitution of a system of will-worship, and self-activity, and excitement,
instead of the thorough heart-searching, and heart-cleansing,
and humiliating work of the Holy Spirit, which is the characteristic of true Quakerism,
or true and pure Christianity, the result of truly bearing the cross of Christ,
and the groundwork of all good works available for our own salvation.]
but the same spirit invaded the meetings for worship,
with a mushroom growth of spurious ministry,
from parties who had never fully submitted to the fire of the Lord`'s jealousy,
thoroughly to purge the floor of their souls,
nor were at all prepared to advocate his precious cause,
and speak of the mysteries of his kingdom to the people.
The stream was as shallow as its source was superficial,
and could be no other than burdensome to the living and panting soul, longing to be led,
fed, and taught by Him who now teacheth his people himself.

The ministry of even many who had once been rightly qualified and anointed for the work,
now descended to a lower level, and became dry and lifeless,
in their attempts to accommodate themselves to the new state of things;
or flowery and fulsome, with an eye to catch the natural affections of the unregenerate,
and attach them to the speaker,
rather than laboring to lead them to that "`baptism which now saveth,`" or to the "`washing
of regeneration`" and "`fuel of fire,`" which would indeed purify the soul.
Was the real welfare of the flock in any way promoted by such a change?
It may safely be answered that this was not the case, but sadly the reverse.
With many of the young and inexperienced, and even some of riper years,
the natural result was, that superficialness and flippant talkativeness,
self-confidence and self-activity,
were substituted for that true humility and lowly dependence
of spirit on the Lord for every supply of strength,
which had given so marked a character to the members of our Society in former days,
that their general demeanor plainly testified that "`they had been with Jesus.`"

William Penn said that "`by the power and Spirit of the Lord Jesus,
they became very fruitful...were diligent to plant and to water,
and the Lord blessed their labors with an exceeding
great increase...bringing people to a weighty,
serious, and godlike conversation.`"
But as it had now become very easy to assume the office of a minister,
and much of the ministry, whether in preaching or prayer, had become thus lifeless,
wordy, and burdensome to the souls of the living; so, on the other hand,
the new views had in many places invaded the seat of judgment,
and produced so great a lack of inwardness of spirit among the Elders,
that little qualification was manifested for a right discernment
between true gospel ministry and that which was spurious.
The consequence was,
that almost any one with fluency of speech and an educational knowledge of the Bible,
taking care to preach the popular doctrines, could be recognized as a minister,
and sent forth abroad as such, to the increasing delusion and bewilderment of the youth,
and the stumbling of honest-hearted inquirers and seekers after the Truth.

Floods of books and pamphlets were likewise issued from year to year,
the tendency of which was to alienate from a due esteem of the principles
and testimonies of truth as held and professed by our forefathers.
In many of these, false doctrines were boldly asserted,
and yet no check was applied by those whose station in the body laid the duty upon them
of guarding the members from being turned aside by insidious and unsound publications.
The increase of such books and pamphlets for a long series
of years after the general spread of J. J. Gurney`'s publications,
was truly astonishing.
Their flow, indeed, was so overwhelming in its extent,
and they were put forth so confidently,
that it seemed as if their authors could afford to ignore the few
attempts made from time to time by honest-hearted Friends,
to contradict them or counteract their influence.
And one thing that made them additionally insidious was,
that while they undermined the ancient profession of our faith,
they were careful to build the sepulchers of the righteous,
keeping up a constant strain of laudation of our ancient
worthies as zealous and almost heroic reformers,
while pulling down their most cherished Christian principles.

Their chief specific aim was to procure a repudiation of Robert Barclay`'s Apology.
This great work,
which had been freely acknowledged by the Society for nearly two hundred years,
as embodying a correct development of the doctrines of the Christian religion,
was now an object of continual attack, both by ministers and private members,
in high-flown but vapid and superficial publications, very pleasing to the popular ear;
yet no disciplinary check was placed upon these attacks,
nor any official attempt made by the body to sustain the standing
which had hitherto been accorded to that sound and eminent author.
Edward Ash, Robert Charleton, Robert Alsop,
and other assailants of the views expressed so clearly in Robert Barclay`'s Apology,
at length succeeded in their attempts to promote a practical
repudiation of it by the authorities of London Yearly Meeting.

This repudiation of Barclay was to have been expected,
from the changes which were taking place,
not only in doctrines but in practice also to a very wide extent.
It would be a wearisome task to go over all the departures from
our Christian testimonies which have obtained prevalence within
the thirty-five years following J. J. Gurney`'s visit to America;
changes whereby the cross of Christ is effectually evaded,
and the spirit of the world and of uncrucified self installed in authority in its stead,
through most of the meetings in England, and consequently in America also.
The departures from our ancient simplicity in manners, dress, and language,
and from the restraints of the cross in daily life and conversation, and in the houses,
furniture, and general style of living of many thousands of the members;
departures from a constant waiting at Wisdom`'s gate
for daily spiritual instruction and guidance,
whereby the soul is seasoned and tendered,
and kept susceptible to the secret monitions of divine grace;
departures from our well-known simple style of building and furnishing
meetinghouses (in some instances introducing even the embellishment
of towers or an approach to the form of steeples outside,
and various ornamental work inside);
departures into the incitements of false devotion by the encouragement
given to reading the Scriptures and singing hymns in meetings for worship,
and a vast array of self-active ministry,
and even partaking of the practices of popular revival
meetings and other artificial excitements,
in the place of a real breathing of the soul unto God,
and humble waiting and watching unto prayer at His footstool;
all these and many more such changes are far too numerous to be here particularized,
but are sorrowfully apparent to the world.^
footnote:[A remarkable instance of the extent to
which some of the Gurney bodies have already gone,
in adopting a system of excitement of feeling as a substitute
for that worship which is in Spirit and in Truth,
accompanied by real abasedness of self,
is to be seen described in a communication signed W. T. P., and headed,
"`Glorious Work at Richmond,`" in the [.book-title]#Christian Standard and Home Journal,#
of tenth month 16th, 1875, published in Philadelphia.
The writer of it,
who was present at the First-day morning meeting during the Yearly Meeting of Indiana,
at Richmond,
asserts that "`nearly or quite three hundred individual testimonies were given in the
space of ninety minutes!`"--mostly to the power of the outward blood alone for sanctification;
adding,
"`It was a hallowed time.... an elaborate box of fragrant perfume`"--and
that "`this meeting was a type of all those held at the morning hour.`"
It struck the writer of the communication as resembling
"`one of our best love-feasts at a National Camp Meeting.`"
A writer in another paper mentions the frequent singing and reading of
the Bible which took place during the meetings for worship on that occasion.]
They were, however, not the primary departures, or main characteristics of the apostasy,
as they have sometimes of late been treated by temporizers,
but were the legitimate fruits of the fundamental
departure from the primitive doctrines of Friends;
and the unsound doctrines of J. J. Gurney, etc., were their motive power.

In the autumn of 1853, John Wilbur, of Rhode Island,
crossed the ocean on a second religious visit to Great Britain,
with certificates of the unity of his Monthly, Quarterly, and Select Yearly Meetings.
These, however,
being from the "`Smaller Body,`" were not likely to be accepted
by the authorities of the Society in England;
and accordingly, on his arrival in that land,
he was promptly confronted by a prohibition, on the part of the Meeting for Sufferings,
of his proceeding in the prosecution of his service.
Indeed he soon found (what he had probably anticipated) that nearly all the leaders
of the people had joined in with the advocates of the new views,
and were inclined to oppose him openly.
Yet in various places throughout that country he
met with quite a number of sympathizing Friends,
who were glad to welcome him among them, and to extend the hand of fellowship,
in a mutual sense of the oppression of the seed of life by the hands of false brethren.
At Manchester, on his way to London, that valiant woman for the truth, Lydia Ann Barclay,
sister of John Barclay (who had deceased on the 11th of fifth month, 1838), met him,
and greatly encouraged him by her counsel and help, having travelled from Aberdeen,
in Scotland, for the satisfaction of meeting with him and cheering him on his way.

A number of other Friends also here showed their unity with him,
and "`appeared resolved to hold fast to sound doctrines.`"
In a letter written shortly afterwards,
describing the precious opportunities they had with him at Manchester,
Lydia A. Barclay said:
"`There was a feeling of the dear Master`'s presence and power over and among us,
that cemented and strengthened us together;`" adding,
that "`Friends must have been quite unprepared (by the many evil reports
spread latterly against him) to see such a sweet placid-looking old patriarch,
so humble and unobtrusive.`"
The day after his arrival in London,
he was called upon by two members of the Meeting for Sufferings,
to dissuade him from prosecuting his concern;
letting him know that if he attempted to speak in any of their meetings,
the audience would be informed, at the close, that he was not a member of the Society.
To this he replied, that according to their Discipline as well as that of New England,
if a person has been dealt with and disowned contrary to the Discipline,
his right of membership is not annulled or prejudiced thereby;
and that Philadelphia Yearly Meeting had clearly shown that
his disownment was palpably at variance with the Discipline.
But this, and other plain reasoning laid before them, was of no avail.
On their asking him what was his prospect of service in that land,
he replied that it was "`to visit the meetings of Friends,
and to appoint some among other people; not with any view to stir up strife, but,
if required by his Divine Master, to preach the doctrines of true Christianity,
believed and practised by our first Friends,
and demonstrated in their writings to be the true
Christian doctrines as set forth in the New Testament.`"

Two days afterwards, by their request,
he met a committee of eight members of the Meeting for Sufferings in London.
This interview was of the same character as the previous one,
but afforded John Wilbur an enlarged opportunity of clearly advocating
his right to be considered and treated as a member of the Society of Friends;
but all to no purpose.
He plainly told the committee, that if they carried out the conclusion come to,
of publicly saying in the meetings that he was not a member of the Society,
he should be under the necessity of explaining, in some way or other,
to Friends in that country, the whole affair of his pretended disownment.
Subsequently, he travelled through various parts of England,
attending the meetings as they came in course,
and in many places having an open time and good service in the ministry.
At some of these opportunities the people were told
that he was not a member of the Society;
but in many places no such open opposition was manifested.
On the 4th of the eleventh month, the Meeting for Sufferings met in London,
and issued a minute to Friends in different parts of the nation,
informing them that John Wilbur was not a member,
and cautioning them to "`carefully refrain from admitting
him into their meetings for discipline,
or accepting him, either in meetings or in their families,
in the character of a minister.`"^
footnote:[For this document, see The Journal and Correspondence of John Wilbur,
Providence, 1859, page 525.]

After this,
John Wilbur was engaged for several days in attending
meetings and visiting Friends in and about London;
and then went into various parts of the kingdom, attending the meetings for worship,
and holding some public appointed meetings.
In the twelfth month, he issued from Manchester a printed Circular,
in form of a letter addressed to the members in most parts of the nation,
as a reply to the false representations under which the Meeting for Sufferings
had prohibited his being received as a member of the Society,
and showing the fallacy of the grounds on which they were proceeding.
After developing the unjust and defective character of the
judgment of London Yearly Meeting in regard to New England,
and showing that it was because of a unity in doctrine with the Seceders of New England,
that they had fraternized with them without any examination into the merits of the case,
and condemned those holding to the ancient principles, as Separatists, he went on to say:

[.embedded-content-document]
--

Under present circumstances it is more easy to my mind not to attend any
meetings for discipline under the control of those holding unsound views;
my concern here rather is, to inculcate the doctrines of Friends,
and to impress them upon the minds of those I meet with;
because there has never been any other root,
producing so good fruit as that of Christ in man,
a doctrine proved by more than twenty testimonies, from Christ and his apostles;
it being the work of Christ within us, as well as the work of Christ without us,
that brings salvation.
And I find a seed in this nation that is not ashamed of the cross of Christ,
nor of his doctrines, which shone forth so conspicuously in George Fox.
And, notwithstanding the document that has been issued against me,
I still do not feel as though I should be clear in the sight of my divine Master,
without endeavoring to visit that suffering seed in this land,
such as may be willing to receive me, having been impressively reminded,
with reference to the before-mentioned paper, of the reply of Peter and John,
when commanded not to speak at all, nor teach in the name of Jesus: Whether it be right,
in the sight of God, to hearken unto you more than unto God, judge ye.
If a man be prepared honestly to adopt the sublime language of Job: "`Behold,
my witness is in heaven,
and my record is on high,`" he will be enabled to stand fast in the Lord;
but if he vindicate the wrong, and refuse to condemn it,
all his professions of the right will avail him nothing.`"

--

[.offset]
And further on,

[.embedded-content-document]
--

Therefore, let not my dear fellow-probationers chide me,
for I have come here in the fear of the Lord,
and in my small measure for the upholding of his testimonies.

--

The rest of the document is mainly devoted to showing the
judgment of Philadelphia Yearly Meeting in the case,
which was so opposite to that of London;
and finally he concluded with the following remark:

[.embedded-content-document]
--

In conclusion, let me add that,
believing controversy for the sake of controversy to be wrong, and ever to be avoided,
this paper is not intended to lead to unavailing disputation;
but I would remind such as are fearful of anything which they think may tend to "`divide
in Jacob and scatter in Israel,`" that from the fall of man to this very day,
the Lord has had a controversy against evil, and his chosen ones must have the same;
and this controversy, far from tending to scatter the faithful,
unites them in the great work of maintaining that
holy faith once delivered unto the saints.^
footnote:[The Circular at large is in [.book-title]#J. W.`'s Journal and Correspondence,#
page 531 to 535.]

--

After issuing this Circular,
J+++.+++ Wilbur travelled during the winter in the north of England and in Scotland.
At Glasgow he again met with his faithful friend, Lydia A. Barclay,
who though weak in bodily health, came thither from her home at Aberdeen,
once more to commune with a beloved elder brother in bonds for the gospel.
Thence he passed over the Channel to Ireland,
visited various meetings and some families in that island,
and then returned to England--went a third time to London--thence to Birmingham,
etc.--and soon afterwards took passage from Liverpool on his return to his native land.
He was then about eighty years of age.
His decease took place about two years afterwards, viz., on the 1st of fifth month, 1856,
attended with a clear and sensible evidence of that peace which,
through the mercy of God in Christ Jesus,
is the reward of obedience to the Divine Witness for truth in the soul.

Some years afterwards, W. Robinson, a professed minister from England, and his companion,
travelling in America, met with a woman whose mind was in an unsound condition,
who told them that she had lived in John Wilbur`'s family during his last sickness,
that he was brought into great distress in reflecting on his past course,
and recanted some of his expressed sentiments in opposition to those of J. J. Gurney,
and was then favored to find peace.
This account, regardless of the condition of their informant,
or possibly not troubling themselves to inquire into it, they transmitted to England,
where it was promptly circulated in a periodical paper.
It was false from beginning to end.
The family of J. Wilbur had no knowledge of such a woman;
and on afterwards being questioned in regard to the statement, she candidly acknowledged,
both verbally and in writing, that she had never seen John Wilbur,
and that she had made that statement when her mind was in
such a state that she was not accountable for what she said.
This is a tolerably fair sample of the eagerness which was manifested
by certain parties to find occasion of false representation against
that worthy man and his associates in religious fellowship.
The author may add,
that he was himself a witness of the sweet peace which attended J. Wilbur`'s latter days,
having been with him for several days,
only about a week before he was taken with his last sickness,
and about three weeks before his death.
At this time he was struck with the sweet savour of J. Wilbur`'s spirit,
as well as with his still living concern manifestly prevalent,
for the promotion of the truth to which he had so long borne testimony.
As we parted, he remarked placidly and humbly,
that he was not looking now for much more service being required of him,
and he felt as one quietly waiting for his dismissal.
This dismissal soon came, and was welcomed as by a good soldier of Jesus Christ.

In the course of but a few years the Society in England was,
in the inscrutable counsels of the Most High,
stripped of many faithful advocates of the pure truth.
Thomas Shillitoe, Sarah L. Grubb, Daniel Wheeler, John Barclay, George and Ann Jones,
John Harrison, and others, had been called to their eternal rest;
and now they were followed by Lydia Ann Barclay, who deceased on the 31st of first month,
1855.
Her beloved friend, Priscilla Rickman, of Wellingham, in Sussex,
a sister in the truth and in the testimony of Jesus,
was likewise added to the number of the missing ones;
being called away in great peace on the 30th of the tenth month, 1859; dying,
as she had lived, in the faith of the gospel, and in sweet fellowship with the few,
both in England and America, who were endeavoring to stand firm to the ancient landmarks.
Thus those who were left to uphold the standard of the primitive faith,
felt that they were but a feeble remnant,
and were often discouraged in their endeavors to testify to the truth,
and against the novelties that were now overwhelming the Society.

The Yearly Meeting appeared to be entirely under the control of the innovators, who,
in the same spirit of restless self-activity and desire for an easy popular religion,
which had led to the changes in doctrine and practice,
soon began to tamper with the Discipline.
From the year 1850 to 1861, great changes were thus introduced,
some of which discarded several of the most characteristic testimonies of Friends.
About the year 1850 the Yearly Meeting officially allowed the erection
of gravestones in places of burial--in 1855 the payment of "`lay
impropriate tithes`" was permitted--and two or three years afterwards,
marriages were allowed with persons not members, but only "`professing`" with Friends.
In 1858 the 4th Query, respecting "`plainness of speech, behavior,
and apparel,`" became the object of attack.
This led to a general revision, in 1860, of the Queries and Advices,
and indeed to an entire remodelling of the whole of the Discipline,
which was at length accomplished in 1861.

[.numbered-group]
====

[.numbered]
In the _1st Query,_ all mention of meetings for discipline was omitted,
and all inquiry as to unbecoming behavior in meetings for worship.

[.numbered]
The _2nd Query,_ as to "`growth in the truth,`" was totally expunged.

[.numbered]
_4th Query,_ all allusion to plainness was omitted.

[.numbered]
_8th Query,_ respecting tithes, was much modified,
so as to generalize the query into payment of "`all ecclesiastical demands;`"
thus permitting the payment of "`lay impropriate tithes,`" as agreed in 1855.

[.numbered]
_13th Query,_ respecting the due care in admonishing against marrying those not Friends,
and dealing with such as persist in refusing to take counsel--omitted.

====

Various other queries were altered in important features, or entirely omitted,
and several were placed in an anomalous position--to be read, but not answered.^
footnote:[In 1875 the queries to be answered (which
had formerly been seventeen) were reduced to two,
and that only once a year.]
The advices were now ordered to be read "`after the close of a First-day
morning meeting for worship,`"--that is--to the mixed company then in
attendance--instead of in meetings for discipline as formerly.
Besides the above, and an almost incredible amount of other omissions and changes,^
footnote:[It has been asserted that "`more than fifty rules of discipline
or specific advices`" were "`abrogated and removed by the late revision.`"
See page 46 of [.book-title]#D. Pickard`'s Expostulation on Doctrine, Discipline, and Practice,# London,
1864;
which contains a clear development of these sweeping
changes and of the insidious nature of them,
if not also of the spirit by which they were prompted.]
the following weighty minute of 1795 was now expunged from the Book of Discipline:

[.embedded-content-document.minute]
--

A concern hath been spread amongst us,
that the management of our Christian discipline be not committed to hands unclean;
particularly that such should not be active therein, who allow, or connive at,
undue liberties in their own children or families.
"`If a man,`" said the Apostle, "`know not how to rule his own house,
how shall he take care of the church of God?`"
And we particularly desire that those, who, from their experience and stations,
ought to lead such to greater circumspection, do not encourage their remissness,
by putting them improperly forward into service.

--

One of the most popular changes now officially sanctioned was in
regard to the constitution of the Yearly Meeting itself.
Whereas, in former times, this Assembly, strictly considered,
was composed of Representatives from the Quarterly or General Meetings,
and from the Half-Yearly or Yearly Meeting in Ireland,
together with "`such ministering friends as may be in town,
and the correspondents or members of the Meeting for Sufferings;`" and other friends,
religiously concerned to attend its sittings,
had of latter time contributed largely to swell its numbers,
and were conceded to be rightly and acceptably there;
now all guard or limitation of this nature (which
had still offered some check on disorderly walkers),
was entirely abrogated, and a wide door was opened for every birthright member,
consistent or inconsistent with the principles of the Society (the latter far preponderating),
to claim to have his voice heard, and attended to, on an equality with any other.
The following brief minute proclaimed the new constitution of London Yearly Meeting:

[.embedded-content-document.minute]
--

It is concluded that this Meeting consist of all the members
of the Quarterly and General Meetings in Great Britain,
and of Representatives from the Yearly Meeting in Ireland.

--

A true church of Christ is an assembly of the faithful.
By this new constitution, unqualified as it was,
the Yearly Meeting of London virtually abandoned
its claim to be in reality a pure church of Christ;
for it was well known that "`all the members`" were
by no means to be classed among the faithful,
but that a very large proportion were unregenerate and of the world.
"`From the beginning it was not so.`"
If the Yearly Meeting,
instead of including "`all the members,`" had declared that "`all the living and faithful,`"
or even "`all the religiously concerned and consistent members,`" should be considered,
when congregated, as constituting that assembly,
without excluding the mere attendance of the others, it would have been safe ground,
and would probably have effectually foreclosed any
further pressure of the non-birthright agitation,
by satisfying the main objections to birthright membership.
On the above new profession of constitution, the Yearly Meeting is one thing,
while the church of Christ is obviously another thing.

The control exercised by the innovators had now become
so overwhelming in the Yearly Meeting,
that the few testimony-bearers for the truth became more and more discouraged,
and it seemed as if the ancient standard might fall in the streets and be lost.
There were still, however, one or two here and there preserved,
like the few berries on the outmost branches of the olive tree; who mourned in secret,
or at times mutually, over the laying waste of the Lord`'s heritage,
and who could not bow down to this gilded image set
up by the great ones with all kinds of music;
though they saw as yet no way of escape from the bonds which were closing around them.
There were a few others, who seemed valiant for the ancient landmarks,
as long as no personal danger should be incurred,
or risk of losing their membership or stations,
or appearing in the view of some as separatists from that Body, which,
though confessed by them to be lapsed,
had yet many elements of outward attraction and influence.
There were also quite a number throughout the land,
who could talk in favor of sound doctrine, and lament departures,
and make a show of not wishing to join any innovating or revolutionary movement,
but who were by no means willing to "`lose caste`" for the blessed Truth`'s sake.
Indeed the reliably faithful opponents of the new measures--mournful as
it is to say it--were becoming hardly discernible in the great mass,
and in imminent danger of being swept away by the flood
of novelty and popularity which attached to the new system.

In the fourth month, 1860, John G. Sargent, then residing at Cockermouth, in Cumberland,
issued a Circular, in manuscript,
to such Friends as he believed were prepared to unite with him in sentiment
in regard to the great danger which threatened the Society.
This Circular tenderly and weightily pressed the subject on the attention of those addressed,
and showed the obligation such were under, to be faithful to the manifestations of duty,
for the safety of the present and of future generations,
as well as for their own clearness before the Most High.
"`Unless,`" said he, "`the fathers and the mothers be faithful and stand fast,
where shall the children be?
And does not Wisdom now lift up her voice in our streets,
and open unto us that which is of the Father?
And will we not endeavor, with the ability which God giveth,
to strengthen the things that remain--so that we and our children,
those who are young and tender under the Lord`'s visiting power,
wherewith He is pleased to visit, may gather strength for the fight,
and still maintain and continue to uphold those precious testimonies to His truth,
revealed in our inward parts to be truth and no lie--and
which our dear and honored predecessors,
so many of them, boldly stood in, and sealed their testimony thereto with their blood!`"
He then suggested the propriety and benefit of such
as saw these things and mourned over the desolations,
meeting together at times, as a General Meeting,
first for divine worship and seeking together for the Lord`'s blessing,
and then to encourage one another in a firm adherence to the ancient faith.

But no time or place was designated as yet for such a meeting,
and it was thus quietly left on the minds of those addressed, for mature consideration.
Nothing appeared as a result of this proposal until two years afterward.
During the summer of 1862 it was thought by several Friends that the time had
arrived for endeavoring to carry into effect something of the kind thus suggested.
Accordingly, a meeting of Conference was held in London on the 17th of the tenth month,
which was attended by fifteen men and two women friends,
who mourned over the changed condition of the Society.
No prearrangement of business had been made,
or of the proceedings or subjects to be entered upon, but an engagement of mind was felt,
to wait in patience for best direction.
The meeting was thus characterized by considerable silence,
though interspersed with testimonies in the ministry,
and the expression of views by various Friends relative to the
innovations on the ancient principles and practices of the Society,
and the difficulties thereby brought upon those who were
conscientiously bound to walk in the primitive path.

After a sitting of more than three hours, they adjourned to the afternoon;
at which time a clerk was appointed for the meeting;
but it was ultimately concluded that no record of
their proceedings should be made at present.
Various subjects connected with the difficulties attending
Friends of sound views in their association with the others,
were weightily considered,
and it was thought that both the sittings were favored opportunities.
Nevertheless, although it was truly urged by some,
that they who promote new doctrines are themselves the Separatists,
not those who resist their introduction;
yet a feeling prevailed that the way did not open at present for taking
any steps that might be considered as acts tending toward a separation.
The next Conference meeting was agreed to be held at Leeds, in the ensuing third month;
when eighteen Friends assembled; and, amongst other business,
the Queries and Advices of the old Discipline of 1802, unmodified,
were read and considered.

The third Conference meeting was held in London, in the ninth month of 1863;
and these meetings continued to be held about once in four months, either in London,
Birmingham, Leeds, Chesterfield, or Manchester, for a period of seven years;
attended generally by an average of twenty-five friends, or thereabouts,
representing perhaps double that number who felt a deep interest in attending them,
when it was practicable for them to do so.
But Friends of sound views were now scattered here
and there in different parts of the country,
and many of them were not in circumstances to warrant long and frequent journeyings.
A number of others, who had sympathy with the object aimed at by the Conference meetings,
were deterred by the trammels of "`station`" (either as ministers, elders, overseers,
or members of the Meeting for Sufferings) from taking so
open a step as would be the attendance of those meetings.
Such as these generally dropped away gradually into lukewarmness or blind submissiveness,
as a reward for their unfaithfulness to conviction.

At this third Conference, held, as above mentioned, in London, in the ninth month, 1863,
it was plainly manifest that a few Friends were already prepared
to discontinue all attendance of the meetings for discipline held
under the lapsed authority of the Yearly Meeting,
but that others were not so prepared;
so that all the advice on that subject that could be given by the Conference collectively,
was to the effect that Friends, in attending such meetings,
should endeavor to be faithful in clearing their hands of the defection,
and abstain from all contact with matters connected with innovation.
The next year,
two of the Conference Meetings were largely occupied in
examining the manuscripts of An Expostulation on Doctrine,
Discipline, and Practice, written by Daniel Pickard, one of their number;
and "`in the solid persuasion that the cause of Truth required
it,`" he "`was cordially encouraged`" to publish it.^
footnote:[[.book-title]#Expostulation,# etc.
London, A. W. Bennett, 1864; page 7 of preface.]
This work was a direct attack upon London Yearly Meeting,
in regard to soundness of doctrine and ecclesiastical authority, showing clearly,
from its own acts, its lapse from first principles.
Yet it was never answered.

At the Conference held in London in the tenth month, 1864,
an Epistle of encouragement and brotherly greeting
was presented from New York Yearly Meeting,
held at Poplar Ridge,
addressed "`to the Remnant of Friends in England;`" but the reasoning
part (essentially of the same spirit that had interfered so disastrously
in America to compromise the testimony) now showed itself openly,
and even prevailed to the rejection of that epistle.
Here was an advantage gained by the cunning adversary;
and weakness henceforth increased in their deliberations,
as well as a spirit of activity of self in some,
setting itself to work at plausible things not called for by the pure truth.
All, however, did not yield to this,
and there was still a savor of life to be felt among them, though with some mixture.
The Conference held in London, in the eighth month, 1866,
united with the prospect of some friends engaged in the ministry,
to pay a religious visit to Wales and the adjacent counties,
and encouraged them to proceed therein,
but did not see its way to give them any minute or certificate.
This visit was accomplished in the autumn.

The Conference which met in London on the 2nd and 3rd of the fourth month, 1868,
is described by one present as being "`a time of favor,
wherein many living testimonies were heard, to the comforting and contriting of +++[+++their]
spirits, and tending to encourage to patience in the path of tribulation.`"
At this meeting, three friends in the ministry, John G. Sargent, Matilda Rickman,
and Louisa E. Gilkes, were set at liberty,
and encouraged to proceed in the weighty undertaking of a visit
in gospel love to the "`Smaller Bodies`" of Friends in America,
yet still without any written credentials.
These three Friends arrived in America in time to proceed to Scipio,
and attend the Yearly Meeting at Poplar Ridge,
which occurred toward the close of the fifth month.
They afterwards returned to Philadelphia, attended the General Meeting at Fallsington,
and then went to New England, attending the Annual Meeting at Newport, on Rhode Island,
and subsequently passing over to the island of Nantucket.
Returning from New England they travelled into Ohio,
visiting the little company of Friends at Salem in that State;
and returning by way of Ulysses and Bath (the friends of which
places compose Hector Monthly Meeting within Scipio Quarter),
they visited the meeting and families of Friends of Elkland, on the Alleghany Mountains,
and returned to Philadelphia.

They also visited Friends of Nottingham Quarterly Meeting, in Maryland,
and sundry places in Pennsylvania.
After thus paying a very diligent and rapid, though pretty general,
visit to Friends of the "`Smaller Bodies`" hereaway,
they found themselves free to return home;
having travelled among Friends in the fellowship of true disciples,
and to the comfort and edification of the living in Israel, and having received,
on the other hand,
much clearer views of the situation and circumstances of the little companies
composing the Smaller Bodies or isolated remnants of the Society,
than they could otherwise have obtained.
They had found (to some degree unlooked for by them), that,
notwithstanding the "`divisions and subdivisions`" which had taken some from among them,
and had been much bruited abroad to the reproach of the cause,
these small companies of Friends were in reality
not merely disintegrated and scattered fragments,
but were as a whole a compact body, united together in the fellowship of the gospel,
and in one mutual concern for the maintenance, as far as they might be enabled,
of the doctrines of the unchangeable truth,
and a life and conversation consistent therewith.

They had been sensible of evidences of true life,
vouchsafed in the abounding mercy of the Great Shepherd of the sheep,
while going in and out among this people;
and great had been their comfort in feeling the overshadowing of the wing
of Ancient Goodness in their meetings up and down the land.
So that while their visit was greatly to the refreshment of those whom they visited,
and instrumental to the binding of them together still more firmly into one,
the visitors themselves returned home confirmed and strengthened
to go forward in the way cast up before them,
without consulting with flesh and blood.
They had also felt drawn to have opportunities, on different occasions,
of interviews with some of the dissentients who had latterly
given Friends so much trouble and gone off from them,
and were entirely satisfied of the scattering and
disorderly spirit which had actuated those movements.
During their voyage homeward, and after their arrival in England,
they were impressed with the belief that it would not be right for them again to unite
in meetings for divine worship or discipline under the control of London Yearly Meeting,
hopelessly lapsed as it was into fundamental error.
Soon afterwards the two female friends went to reside at Fritchley, in Derbyshire,
where John G. Sargent and his family were then living,
and where a meeting for divine worship was already settled;
and that meeting became established, and increased in numbers.

But these Friends soon found, to their sorrow,
that the halfway compromising spirit among some members in the Conference meetings,
was becoming very busy to thwart any decided measures, and to throw censure upon them,
for having, during their visit to America,
abstained from giving countenance to those actuated by the same middle spirit there,
or to those who had struck off from Friends under various pretexts.
These alleged that all should have been visited alike by the three Friends,
without showing what they deemed partiality to those who
had stood firm and united together through these great trials,
and opposed to every disorder.
This party threw obstacles in the way of all attempts to open or establish
meetings for worship distinct from those subordinate to the Yearly Meeting,
or anything like owning fellowship with Friends of the General Meeting held at Fallsington,
or the Yearly Meeting at Poplar Ridge.

This spirit was particularly developed at the Conference Meeting at Birmingham,
held in the first month, 1869.
A letter from one of the friends who had visited America the previous summer, says:

[.embedded-content-document.letter]
--

Yes, it is a day of sore affliction,
because those who have walked with us rise up against what
we believe to be for their and our peace and joy,
and we cannot convince them of its being to their loss.
The Conference sittings (four in number) at Birmingham,
have more fully developed this fact The purifying fire is, I apprehend,
hotter than the rebellious nature is willing to endure;
and yet it was mercifully to be noted that the Beloved
Messenger of the covenant came to the temple,
that He might purify the sons of Levi, and make them clean vessels unto Himself.
He came to search Jerusalem with candles, that every secret corner might be discovered,
and holiness inscribed upon every thought, word, and deed.

It was a time in which we hoped Truth made some way--but
if there is a turning away from that operation,
instead of a submission to the suffering, then there comes a hardness,
which prevents a co-working in the precious cause of righteousness, and an attempt,
too often successful, to hinder its increase; to the distress of the little ones,
who are desirous of being wholly formed by the counsels of Wisdom into a compact body,
through which Life may flow uninterruptedly We are afflicted, but not in despair;
for we believe the Lord is on our side, and that we need not fear;
that He is our light and salvation, and will be so, if we cleave unto Him,
and cease from man.
May you be comforted in knowing that His arm is revealed unto us,
and our confidence steadfast in the God of Jacob.

--

[.offset]
A letter from another Friend says:

[.embedded-content-document.letter]
--

We had to partake, at this Conference, of that cup which has never, I think,
been quite so bitter to the taste before,
at any of these meetings--arising from a more full and open exposure of what was in man,
even in some attending these sittings.
But the Lord was near to help,
and preserve from answering again in that spirit which never can build,
but must lay waste, as it is cherished or given way to.
Our first sitting (the meeting for worship) I can say, felt to be a favored time,
which the Master owned with his presence, to a feeling of gratitude and praise,
and strength was renewed.
But matters in our Conference did not move on as would have been a comfort to us.

The subject of answering the Epistles from our dear Friends on your side,
came again before us,
and it was plain that there existed the same impediment to its being done, as before;
and this with comparatively a few; nevertheless,
these were of the most active ones amongst us What may yet appear, we do not know;
but if faithful and low in our minds,
I trust and believe we shall know that peace which makes up for
all that we have gone through and may have yet to go through.
We are feeling, I think, more than hitherto we have done,
how few we are who are walking in this way--of withdrawing from the multitude--but
I trust we may be accounted worthy to hold up the standard;
and it may be, others will join us; but whether or no,
if peace and the owning Power accompany, we need not fear;
but until tried we do not know the degree of our faith;
and we need indeed to be prayerful, that it fail not.

--

About this time, the Friends at Fritchley, and a few from elsewhere,
drawn in spirit to unite with them, began to meet once a month collectively,
in addition to their usual meetings for worship twice a week in the village.
These collective meetings were held alternately at Fritchley, Bakewell, and Monsaldale,
in Derbyshire; and were afterwards enlarged in their scope,
so as to have something of the character of regular
Monthly Meetings for the business of the church,
as well as for mutual encouragement in waiting on
the Lord for the strengthening of their faith.
Some Friends also, in different places up and down the land (though very few in number),
were gradually drawn to meet for divine worship apart from the lapsed bodies,
and in unison with those at Fritchley.
Thus small meetings were opened at Birmingham, London, Bakewell, Monsaldale,
and some other places,
though greatly discountenanced and discouraged by those of the "`middle`" spirit,
as well as by the open advocates of the new views.

It was necessary that this halfway spirit should
clear itself out from among that little company,
before any advancement of the testimony could be made.
Meantime, in the summer of 1869, Daniel Koll, of Salem, Ohio,
with certificates of the unity of his Monthly Meeting,
and of the General Meeting of Ministers and Elders held at Fallsington, went to England,
on a visit of gospel love to the remnant of Friends there, and to the Society in Norway,
accompanied by Mahlon S. Kirkbride, of Bucks County, Pennsylvania.
After spending a short time among Friends in various parts of England,
they sailed for Stavanger, attended nearly all the meetings of Friends in Norway,
and visited many of the families, scattered along the coast as far north as Bergen.
They found an open door among this honest-hearted and tender-spirited people.
Many of them were then sensible of the difference
between the primitive doctrines and the new views,
and to some degree aware of the lapse of the main body of the Society in England, who,
however,
were diligent in endeavoring to draw them over to
a closer union with London Yearly Meeting.

After travelling in Norway for about a month, they sailed for Denmark,
to visit some professing with Friends in Jutland,
and then proceeded through northern Germany, on their return to England.
Remaining a few weeks longer in various parts of England,
they attended the Conference meeting held at Birmingham, in the tenth month.
This was a proving time to the right-minded, from the continuance,
and more openly manifested prevalence of the spirit of opposition.
The sad conviction was renewedly impressed upon the members,
that the meeting was now composed of incongruous materials,
which prevented its progress in a pure testimony for the Truth.
Much time was occupied in a consideration of the
question of continuing to hold meetings of this kind,
and finally a minute was adopted, by which the Conferences were discontinued.
It was as follows:

[.embedded-content-document.minute]
--

The question of holding another meeting for Conference
lies weightily engaged our serious deliberation,
and we feel that there is not sufficient clearness
to appoint a time to meet together again;
leaving it to rightly concerned Friends in this nation to move
in the way of calling their brethren and sisters together,
as the Lord may be pleased to open the way; whose guidance, through mercy,
during past gatherings of this kind, we desire thankfully to acknowledge and record.

--

Thus terminated the Conference meetings,
after being held about three times a year for a period of seven years.
It may be asked, What good was the result of their existence?
Much--in raising even the standard they did, against the flood of defection,
and encouraging those engaged in them, and some others, to stand firm in a very dark day^
footnote:[To the existence of these Conference meetings
and their favorable influence and encouragement,
we may ascribe in great measure the publication of the [.book-title]#Expostulation on Doctrine,
Discipline, and Practice,# by Daniel Pickard,
and the printing and circulation of W. Irwin`'s edition
of 10,000 copies of [.book-title]#Barclay`'s Apology,#
after the Meeting for Sufferings had declined to reprint it.
If nothing more had been effected than these two undertakings,
the Conference meetings would not have been in vain.]--though
not as much as might have been,
had those who took part in them been of one mind, all thoroughly baptized for the work,
and all prepared to "`endure hardness as good soldiers of
Jesus Christ,`" in bearing a clear and unequivocal testimony,
not only against the new doctrines,
but likewise against the lapsed authority of London Yearly Meeting,
which was propagating those doctrines.
Instead of this, some of them, as we have seen,
were possessed with a morbid fear of any procedure looking like separation,
even from what they had been convinced was a dead body;
and this fear continually checked and thwarted such testimony as,
in their collective capacity, they might otherwise have been enabled to maintain,
for the increase of their own strength,
and the information and encouragement of others throughout the Society.

One of the friends present, in writing of it afterwards, remarked:
"`We had reached a point in our travels,
where two roads meet--the one leading to the setting up
of a separate organization in this country--the other,
to remain in the beaten track, being disinclined to leave the old Society in England.
These two roads lead in different directions.
No one can travel upon both at the same time.
Hence, if both sides remained firm, a separation was sure to come.`"
The Conference meetings were therefore seasonably discontinued,
as their strength was gone, through want of unanimity in aim,
and their prolonged existence could only have afforded unsatisfactory
opportunities of the development of disunity among the members.
But was the standard which had thus been a little raised in England,
now to be utterly cast down and trodden in the dust?
Not so.
The Conference Meetings, which had failed of the mark,
through the fearfulness of certain active and influential members, were,
in the ordering of Divine Wisdom,
to give way for the holding up of a more clear and efficient testimony,
through instruments few indeed and feeble of themselves,
but more fully prepared for such a work, and trusting not in themselves,
but in the help of Him whose servants alone they desired to be.

After the conclusion of the meeting, as above mentioned, some friends,
who could not feel satisfied with the anticipation of an entire abandonment of all hope
of organization for the honor of the Truth and the maintenance of the ancient faith,
continued together, to wait on the Great Shepherd for his counsel and direction;
holding two sittings,
in which it was ultimately concluded for such friends as
might feel prepared to unite with them in their testimony,
to meet at Fritchley, in Derbyshire, in the first month of 1870, if so permitted,
in the capacity of a General Meeting,
in connection with the little meetings for worship
already held in different places in England,
and the monthly gatherings then held at Fritchley, Bakewell, and Monsaldale.

About one-half of the usual attenders at the Conference
Meetings united in forming these General and Monthly Meetings,
with the rules of Discipline as they stood in 1802;
and others afterwards gradually joined them.
Most of the other half, or midway men,
fell back into the large body of the Yearly Meeting,
notwithstanding the exposures which they had themselves made,
of its apostasy from the genuine principles, practice, and discipline of the Society.
These small companies of Friends,
united together in a testimony for the ancient faith of the Society,
were afterwards visited at different times by several Friends
in the ministry from the Smaller Bodies in America;
of which visits it is only necessary here to say,
that they were to the comfort of the few struggling ones,
who were often much discouraged when looking at their
own weakness and the greatness of the cause;
but who still relied upon the Arm of all-availing strength,
knowing their fresh springs to be in Him,
and were sustained by the incomes of his love and the overshadowing of his wing.

The General Meeting held at Fritchley as proposed, in the early part of the first month,
1870, was attended by about twenty-five Friends,
and was believed by those present to be a time of divine owning and help.
Thenceforward these meetings have been regularly held at that place,
and their establishment was promptly recognized, through epistolary correspondence,
by the Yearly Meeting of Friends of New York held at Poplar Ridge,
the General Meeting for Pennsylvania, etc., held at Fallsington,
and the Annual Meeting for New England, held at Newport.
The Yearly Meeting held at Nottingham, in Maryland, for Baltimore, had,
at its own suggestion, been merged in the General Meeting for Pennsylvania, etc.,
as one of its Monthly Meetings.
During the spring of 1871, Thomas Drewry, of Fleetwood, in Lancashire,
under an apprehension of religious duty, drew up a document,
in the nature of a protest against the claims of the London Yearly Meeting to
be considered any longer as a legitimate meeting of the Society of Friends;
declaring that it had encouraged new doctrines, and was thus become a schismatic body,
and no longer entitled to hold the trust properties of various
kinds which had from time to time been left to its charge,
for the purposes of the true Society,
and for the promotion of the cause of truth as always held by faithful Friends.

A copy of this document was sent to the Yearly Meeting of London in the fifth month,
addressed to the clerk, but was not suffered to be read therein.
A copy was also sent (duly attested by a magistrate) to the Government
Board of "`Commissioners of Charitable Trusts,`" in London--a Board having
the power of inspecting into the faithful management of all such Trusts.
This procedure was intended by him for the relief of his own mind, so far as it went;
but was not expected or intended to be followed up
on his part by any further legal proceedings.
Its receipt by this Board was duly acknowledged.
The protest was as follows:

[.embedded-content-document.]
--

[.letter-heading]
To All Whom it May Concern

I, Thomas Drewry, of Fleetwood, in the County of Lancaster, Grocer, do solemnly,
sincerely, and truly declare and affirm as follows:
That I am a member of the Religious Society of Friends, commonly called Quakers;
that I belong to Preston Monthly Meeting,
which is a constituent part of the Quarterly Meeting of Lancashire and Cheshire,
and within the bounds of the Yearly Meeting of London;
that I am entitled to all the rights and privileges
of membership in the Society of Friends,
which rights and privileges have not to this day been called in
question by any of the constituted meetings of said Society.

[.numbered-group]
====

[.numbered]
2.--I declare that the adoption of, or acquiescence in new principles and new usages,
at variance with the fundamental principles originally established in the Society,
is a departure from the original compact,
and a lowering of the ancient standard of faith,
and that the Meeting so departing becomes an alien body,
and is thereby divested of all rightful claim to be regarded
as a Meeting in communion with the true Society of Friends.

[.numbered]
3.--I assert that great and fundamental changes have taken
place within what is called the Society of Friends,
in recent years, in reference to Faith and Doctrine.

[.numbered]
4.--I declare that the Yearly Meeting of London, as it is called by the said Society,
has officially embraced new Doctrines,
and to a great extent discarded those views of primitive Christianity, which,
through the ordering of Infinite Goodness, were revived, proclaimed,
published to the world, lived up to, and suffered for, by Friends at the beginning

[.numbered]
5.--I affirm that evidences of this defection abound and are almost everywhere apparent.

[.numbered]
6.--I assert, and am able and willing to offer clear and ample proof,
that the changes in Doctrine referred to,
have been pointed out by well-concerned Friends again and again;
and I also assert that for upwards of thirty years at least,
true Friends have been exercised in their minds and distressed thereby,
that these have availed themselves of the opportunities
which the various Meetings for Discipline afforded,
to speak of the hurtful tendency of the changes in question, but that entreaty,
expostulation, remonstrance, and warning, have been alike disregarded.

[.numbered]
7.--I affirm that nothing convincing to the true Friend
has been put forth in defence of these innovations in Doctrine,
nor has it been shown by official documents, or otherwise proved,
wherein the Early Friends were mistaken in their views or apprehensions of the Truth.

[.numbered]
8.--I assert that it is not in the power,
or within the competency or constitutional functions,
of any of the Meetings for Church Affairs of the Society of Friends,
called and known by the name of Meetings for Discipline, to alter, abrogate,
or abolish the religious principles or doctrines of Truth, which were held, set forth,
maintained, and promulgated by the Founders of this People; or to rescind, abandon,
or annul the religious testimonies, practices, and usages,
which it was the care and concern of our predecessors in the Truth,
in the fear of the Lord, to maintain.

[.numbered]
9.--I affirm that not even a Yearly Meeting,
the highest court as regards faith and practice amongst Friends,
can change the fundamental Principles of the Society,
or the Testimonies which have ever uniformly flowed from them,
and which have been left to us in trust for succeeding generations.

[.numbered]
10.--I maintain that the abandonment of said principles is an act of separation.

[.numbered]
11.--I affirm, in accordance with the doctrine of our ancient Friends,
that all who desert the Religious Principles,
which first drew together and distinguished the Society, be they few or many,
are truly Separatists, and that those who adhere to the original faith,
have the power to say to the dissentients, You have changed your views,
we can no longer acknowledge you to be in fellowship with us.

[.numbered]
12.--I declare that London Yearly Meeting, as it is termed,
has separated itself from the sound part of the Society;
and I affirm that the taint of Separation necessarily reaches and attaches to all Meetings,
of whatever kind, that remain subordinate thereto, whether they be Quarterly, Monthly,
or Preparative, together with the subsidiary Meetings thereunto belonging.

[.numbered]
13.--Seeing that London Yearly Meeting, so called,
has sanctioned and introduced into its midst,
changes and innovations in Doctrine of a very important character,--seeing
that it has done that which it had no constitutional authority to do,--seeing
that it has broken the compact which bound the Society into one body,
for the support and maintenance of the Principles and Testimonies of Truth,--I
maintain that it has become the Yearly Meeting of a body of Separatists,
and, consequently, has no lawful right, title, or authority to assume the name,
or to exercise the functions, of a Yearly Meeting of the Society of Friends.

[.numbered]
14.--I, therefore, under a sense of apprehended duty,
protest against the claim or prescriptive right, set up by this Meeting of Separatists,
either by itself, or by any of its subordinate Meetings, to have, hold,
retain possession of, deal with, or administer Trust Property, which belongs not to it,
but belongs to those who adhere to the original faith of the Society of Friends,
for whose sole use and benefit the several Trusts were created,
by their predecessors in religious profession.

====

[.signed-section-signature]
(Signed) Thomas Drewry.

Declared and affirmed at Fleetwood, in the County of Lancaster,
this Twentieth day of May, one thousand eight hundred and seventy-one, before me,

[.signed-section-signature]
(Signed) F. Kemp, Justice of the Peace, acting in and for the County of Lancaster.

--

This protest, direct as the attack was on the Yearly Meeting,
never elicited any reply to its unanswerable charges,
as would have become a people conscious of walking in the footsteps
of the flock of Christ`'s companions under a false accusation;
nor was any official notice whatever taken of it; but,
like most other testimonies against the great defection,
it was consigned to a silent reception as the easiest
method of quickly getting it out of sight,
and keeping it from becoming known abroad or among the members.

In the year 1873 the Yearly Meeting of London appointed
a large committee to visit its constituent meetings.
This committee, of course,
was principally composed of adherents to the new order of things in doctrine and practice,
and the tendency of its labors was to encourage much
merely intellectual activity in religious undertakings.
It resolved itself into sections for visiting the various portions of the Society there,
and being continued for another year,
made a plausible report of its engagements to the Yearly Meeting, in 1875;
in which the prevalent novelties were carefully kept out of view,
except the open avowal of satisfaction with the hopeful
condition which they thought the Society was in,
"`attributable,`" as they believed, "`in no small degree, to First-day Schools,
Mission Meetings, and other similar agencies.`"
What these "`similar agencies`" were,
may be easily understood by those who have watched the course of General, protracted,
or "`revival`" meetings;^
footnote:[The Philadelphia _Friends`' Review_ of first mo.
8th, 1876,
has copied from the London Friend some directions for holding these revival meetings, or,
as they at present style them, General Meetings.
These directions seem to have been suggested in the London paper by Henry S. Newman,
and their publication in the Review appears to indicate
an approval of the same arrangements taking place in America.
From these directions it is very evident that the ministers are
expected to do just what is arranged by others for them to do--when,
where, how much,
or how little--for "`brotherly guidance will be much needed`"--the workers and the committee
should "`understand one another`"--the "`eldership must be in lively exercise,`" particularly
"`when there is the stimulus of novelty or numbers`"--so that the committee maybe able
to "`give advice to a minister,`" and "`good soldiers`" may "`keep rank,`" and not give
rambling addresses that the people cannot follow,`" but must take care lest "`a whole
meeting be burdened because some one wishes to relieve his mind.`"
"`Meetings for preaching the gospel may be held every night,`" and a "`conference
every morning for Scripture study and prayer,`" and one or two Friends
should be appointed to "`introduce the subject for the day,`" etc.]
meetings purposely appointed for "`prayer`" in man`'s will and time;
meetings occupied more or less in hymn-singing,
and other such excitements of the natural feelings;
meetings held for the "`study`" of the Bible by merely intellectual and literary means,
and discarding or overlooking the light of Christ in the
soul as the primary instructor and true interpreter;
with an inordinate dependence also upon the circulation of superficial tracts, leaflets,
and hymns, and an indulgence in ornamentally embellished texts and even crosses,
and other religious toys and triflings,
which have prevailed so greatly since the introduction of the modern doctrines,
and seem like byways back to Babylon.^
footnote:[Respecting the consistency of the labors of this committee,
there was doubtless some divergence of sentiment among the members visited.
A letter to a friend from Samuel Evan,
an aged and well-esteemed member of Lancashire Quarterly Meeting,
who has long mourned over the lapsed condition of things, but who, in his 86th year,
still adheres to "`the body,`" makes the following remarks in
alluding to the visit of a section of the committee at Warrington:
"`It was not to me a satisfactory opportunity, as I could not while it lasted,
nor have I been able since,
to get over the great inconsistency of representatives of the Yearly
Meeting going through the length and breadth of the land,
preaching doctrines not only not in accordance with those of the Society of Friends,
but subversive of them; and yet no one makes an effort, either with pen or tongue,
to lay open the iniquity of such practice.`"
And in reference to the subsequent Quarterly Meeting,
he says he "`found no comfort there,`" adding,
"`I cannot say that I have been edified by my attendance,
but have returned under a load of discouragement, from seeing those Friends, who,
from their station, ought to be the leaders of the flock Zionward,
associating with and aiding such as cause the people to err;
who run before they are sent.`"
Doubtless many more would have been able to bear a similar testimony,
had they with a single eye consulted their own best feelings in the light of Truth,
instead of putting confidence in man.]

We must now recur briefly, but a little more particularly,
to the attacks on Robert Barclay`'s Apology, and the doctrine of Immediate Revelation,
already alluded to.
Doubtless they had (kept up as they were from year to year with no rebuke
from the body) a powerful influence in aid of J. J. Gurney`'s writings,
in turning aside the faith of many in England from the ancient principles of the Society.
The most prominent of the assailants was Dr. Edward Ash, of Bristol,
occupying the station of a minister,
and the last survivor of the Committee of the Yearly Meeting on the Beacon difficulty.
As early as 1849 he had expressed, in a printed tract,
decided objections to the republication of the Apology by the Society;
and three years afterwards,
finding that the Meeting for Sufferings still continued to offer the work for sale,
he resigned his membership in a letter to his Monthly Meeting.
In this letter he mentioned that the parts of the Apology to which he
objected "`embrace a large portion of the doctrinal part of the work,
and have reference to subjects of primary and vital concern to the church,`"
and "`to some prominent parts of our system of discipline.`"

In the appendix to his letter, which he put in circulation,
he gave a brief specification of his objections;
which may be summed up as referring to the doctrines of
Immediate Revelation and the Universal and Saving Light,
the Holy Scriptures, Justification,
many interpretations of Scripture considered by him as incorrect, and a prevalency,
throughout the work (the Apology) of what is "`defective and erroneous.`"
The latter clause also of the statement of the Proposition on Worship, he said,
"`furnished of itself an insuperable objection,`" in his view,
"`to the adoption and circulation of the work.`"^
footnote:[Some of the Gurney party in America may perhaps allege that they do
not follow E. Ash in his denunciations of these doctrines of Fox and Barclay,
knowing that they lie at the very foundation of our profession;
but we must remember that E. Ash was a disciple of J. J. Gurney,
having lived at Norwich in his earlier career,
and been for many years in close intimacy with him,
and that I. Crewdson and J. J. Gurney inculcated the very same errors,
though the latter perhaps not quite so unreservedly and openly,
except in his tract on _Misinterpretation of Scripture,_ etc.
Some of them in Philadelphia are also of late attempting to induce
the absurd belief that even George Fox`'s writings can be made
to countenance their inroads upon the true spiritual worship,
as always held and practised by Friends.]
It was an evidence of great defection, that the Monthly Meeting,
instead of treating with Edward Ash as a manifest and open transgressor
in issuing so palpable an attack upon its well-known principles,
and disowning him on the failure of due efforts to reclaim him,
permitted him quietly to depart without bearing any open testimony against his errors.
He remained outside of the Society for some years, and then, believing, as he said,
"`that the Society had come round to his views,`" he was
received by the Monthly Meeting again into membership,
without any change of his sentiments respecting Barclay`'s Apology,
or any condemnation of his denial of some of the fundamental doctrines of the Society;
the Monthly Meeting considering, as was afterwards said on their behalf,
"`that the Society had virtually disowned the Apology as
a correct exposition of its views at that time.`"

Accordingly, in 1873, he published another pamphlet,
this time aimed ostensibly against George Fox,
but really and obviously against the doctrine of
Immediate Revelation and Universal and Saving Light,
so powerfully promulgated by that enlightened and truly wise man,
and by Robert Barclay and hundreds of others of our first Friends.
In this pamphlet,
though he confessed (p. 34) to a very limited knowledge of G. Fox`'s writings,
of the character of which he says,
"`I know nothing beyond such as are included in the Journal,`"
which comprises less than one fourth of the whole;
yet he had the audacity to labor to show that eminently gifted
man to have been a mere enthusiast in some of his most cherished
convictions and most prominently important principles,
very credulous and self-opinionated;
and to assert that "`mischiefs resulted from his mistakes of faith and teaching.`"
And at the same time that Ash speaks many times over in this attack,
with remarkable egotism and self-confidence,
of his "`own conviction`" of many things which he asserts
as boldly as if they were thereby alone rendered invulnerable,
he inveighs against G. Fox`'s "`facility of belief, vagueness of statement,
and absence of adduced evidence,`" as a conspicuous fault in his
writings--says that "`he himself and not a few of his brethren
more or less frequently mistook the workings of their own imagination,
or other natural faculties,
for divine communication or commands`"--that there were "`elements in his mental character,
which, had they not been counteracted by others,
might have generated a real fanaticism`"--and alleges that he was "`of small mental
acquirements,`" and fell into mistakes through "`his belief that he was the recipient
of immediate revelations of divine truth`"--boldly asserting that he was altogether
mistaken in supposing himself commissioned to teach as he did.

The main drift, indeed, of the tract is to inculcate, by bold but unsupported assertions,
the belief that the doctrine of Immediate Revelation and Universal and Saving Light,
as taught by George Fox and our other early Friends,
and always owned by true Friends from that day to this, was a mischievous mistake,
a mere delusion, in accordance with his attack, many years before, on Robert Barclay;
and he clinches his argument (to his own great exultation) by the assertion
(p. 40)--alas! too true in itself--that though this doctrine has never
been officially or directly disowned "`by the collective body,`" yet it
has "`virtually disappeared from among us in this country +++[+++England],
and I believe from the larger portion of our community in America.`"
Soon after issuing this publication, viz., on the 23rd of twelfth month, 1873,
Edward Ash was taken away by death.

After all this self-evident departure from and even
opposition to the very groundwork of our profession,
the Monthly Meeting of Bristol and Frenchay sent forth a
Testimony of their unity with him as a member and minister,
full of praise of his virtues;
in which they designated him as "`a faithful and loving minister of the
gospel of Christ,`" and spoke of "`his extreme conscientiousness,
and his sensitiveness with regard to anything which he considered erroneous
or defective in Christian doctrine;`" and with regard to his ministry,
that "`as a minister of the gospel,
he was deservedly honored amongst us`" that he "`was largely engaged in declaring,
in a clear, instructive, and comprehensive manner, the unsearchable riches of Christ.`"
This Testimony concerning him was adopted by London Yearly Meeting in 1874,
though with some totally ineffectual objection, for publication among its records;
the meeting being exultingly informed by members of that Monthly Meeting,
that "`he never withdrew a single statement he had made in condemnation of Barclay`'s
Apology,`" and that "`the Monthly Meeting was well aware that his views were unchanged.`"
The clerk of the Yearly Meeting (J. Storrs Fry) corroborated this statement.
Who can doubt that, by the adoption and approval of such a document,
London Yearly Meeting publicly and knowingly sanctioned
Edward Ash`'s course of repudiation of that great work,
the Apology for the True Christian Divinity, by Robert Barclay?

Another minister (so-called), Robert Charleton,
had also come forth in the same line as Edward Ash,
in assailing the principles of Robert Barclay; and likewise Robert Alsop,
then of Stoke Newington, near London, who, early in 1873,
printed "`for private circulation`" (a mere subterfuge), but spread widely abroad,
a tract entitled What is the Gospel?--devoted to showing
what he supposed to be some of Barclay`'s mistakes.
It seemed as if some of the members--nay,
of the ministers!--of a Society in whose arising and early progress George Fox
and Robert Barclay had been instruments so conspicuously made use of by the Almighty,
could now never have enough, or settle down in their beds,
until they had destroyed all confidence in those ancient
worthies as exponents of that Society`'s true principles!

These insidious but superficial attacks were promptly replied to by several writers,
some of whom had been attenders of the English Conference meetings before mentioned;
who more or less ably defended the doctrine of Immediate Revelation as held by Friends,
and clearly demonstrated the fallacy of those specious arguments,
and futile attempts to prove Barclay mistaken;
refuting also all pretension to consistency in men holding such views as Ash, Charleton,
and Alsop had put forth,
still professing to be members and even ministers of the Society of Friends.
Yet, strange to say,
most of the writers of these defenses of Barclay still continued
to cling to the lapsed body of London Yearly Meeting.
