== Chapter XVIII.

Concluding Remarks--The Identity of the Society of Friends.

On a retrospect of the foregoing sad development of departure from first principles,
what do we now see in applying it to the present state of
the heterogeneous body popularly called the Society of Friends?
The nominal Society probably never was much more numerous than at this day.
How many and opposite soever are the divisions, they all claim to be Friends.
But are all to be owned as Friends, who claim the name?
Schism necessarily vitiates the claim of one or the other party therein,
to be the original body.
What has been the result of the schisms we have been considering, in this respect?

The early and local schismatic bodies--the Barnardites, in Ireland--the New Lights,
of New England--the Beaconites, of England--as well as the Anti-Slavery Friends,
of Indiana--have all passed out of existence as distinct or visible religious associations.
It is true,
there are yet subsisting three very small companies of dissentients
from the "`Smaller Bodies;`"--the King party,
of New York--the Lamborn party, of Ohio--and the Middle party,
of New England;--but neither of these companies has any apparent probability of a continuance.
No body of Friends elsewhere, large or small, owns them, or corresponds with them.
Each one of them appears totally isolated from the others,
and nursing the seeds of dissolution.
Leaving these then out of view, as we necessarily must, what do we see?
In the first place,
there is the large Society of "`Hicksites,`" and their adherents
through local circumstances or family ties.
Next, there is the much larger and more influential Society
of "`Gurneyites,`" and their adherents through fear,
favor, affection, or views of interest.
And lastly, there are the "`Smaller Bodies,`" scattered in Pennsylvania, New Jersey,
Maryland, New York, Ohio, Iowa, Indiana, New England, and Old England,
and even a few in Norway;
though the bulk of the members in the latter have recently placed
themselves in connection with the lapsed Yearly Meeting of London.

It may be thought by some, that a fourth class should be here enumerated, viz.,
the middle party, which at present controls the Yearly Meeting of Philadelphia.
But as this class has from the first practically promoted
the success of the Gurneyan system by its connivances,
though sometimes in words uttering weak and unavailing lamentations over it,
and has never given the least support (but always the contrary) to the
Smaller Bodies which have become the only consistent and earnest testimony
bearers against the doctrinal innovations of Gurneyism,
and as this middle party seems most likely to succumb eventually
to the gradual but continued pressure of the innovators,
whom it has had no courage effectually to withstand,
the Gurneyites and the Middle party must in reality be considered as of one class.
We may indeed query, in case the middle party should continue many years longer,
whether they will not become "`hewers of wood and drawers of water`"
for the great majority still owned by them as the Society of Friends.
Why have they not taken a more decided, consistent, and effective stand against Gurneyism?
Is it not manifestly because they do not, after all, truly realize for themselves,
nor appreciate to the full, and consequently dare not acknowledge to the world,
and act consistently with that acknowledgment, that the new system of doctrines is,
equally with the Hicksian system, a fundamental departure from Quakerism,
or the pure faith of the gospel,
and therefore ought to be testified against with equal faithfulness?^
footnote:[If there is life in the body,
and an earnest concern to avoid the inroads of error,
how is it that they suffer the Twelfth Street Meeting
in Philadelphia to go on year after year,
openly fraternizing with the schism and promoting the glaring
departures from the principles and practices of Friends?
Why does not Philadelphia Quarterly Meeting,
if it really wishes to stand for the ancient faith,
call that Meeting to account for its long-continued course herein?
Yet their periodical paper,
"`The Friend,`" still constantly speaks of the Gurneyites as "`Friends,`"
and of their Yearly Meetings as "`Sister Churches,`" and "`Sister Yearly
Meetings;`" thus manifestly owning them as one people with themselves.]

It is well known that these three claimants to the once despised and persecuted,
but now flattered name of Quakerism, have no mutual fellowship one with the other,
but are fundamentally opposed in principle.
Yet the true Society of Friends is and must be but one, the world over.
It came forth originally founded on a pure faith in Christ,
the divine Head and Bridegroom;
professing and aiming (without arrogating to itself to exclude other seeking
souls purely depending on the same Lord) to be the visibly gathered representation
of the militant church--the spouse of Christ.
This was a high profession; but thus it was.
Alas! alas! how has the mighty fallen!
Has it, since those days, maintained that eminent and favored position?
Is Christ divided?
Are his members divided?
Can any be called members of his body, or members of the church or spouse of Christ,
who are denying him, either in regard to what he did for us, in that prepared body,
or in what he is doing for us within us, by his blessed Spirit,
as he is the Word nigh in the heart, the Light within or inward Light,
the baptizer with fire and with the Holy Ghost,
the great purifier and sanctifier and leader of his people?

But to come down to the question of our own day,
even of the identity of the true Society of Friends.
It was the doctrine of Robert Barclay and all our early Friends, and has indeed become,
as it were,
an acknowledged axiom among most serious professing Christians of the present day,
that they who faithfully maintain the original fundamental
doctrines and testimonies of a religious Society,
have alone a rightful claim to be that Society--not those who introduce
or promote innovations inconsistent with the original foundation.
Would any of us be willing to acknowledge as Episcopalians,
a body who should arise among them, holding and teaching Unitarian doctrines?
Or as Presbyterians,
such as should teach among them the doctrines and practices of the Romish church?
Or could a Moravian congregation,
for some reason or other claiming to belong to the great Roman "`Catholic`" body,
be by any possibility acknowledged by that body,
or considered by others as having a valid claim to assume its name,
in order to open its way among the people?

With respect to the Hicksian Society,
it has been abundantly proved that they came forth
on the avowed ground of a difference of doctrine,
and in support of Elias Hicks against those who condemned his doctrinal errors.
What these were, we have already seen in the first volume of this work.
Suffice it here to say, that they were destructive of the original tenets of the Society.
It cannot be alleged that he did not hold or teach these errors;
for he openly avowed to the stenographer his approval of the printed Sermons in which,
as well as in his Letters, these errors were characteristically abundant.
Neither can it be said that his followers were not aware of them;
for notwithstanding the free public animadversions upon them,
they published them abroad over the land in his Sermons and otherwise,
and many of them taught the very same things,
and earnestly contended for their correctness.
And to this day,
large numbers of their preachers and influential members are well
known to be equally unsound as to the Christian faith.

It is true that at the present day there are on the other
hand some estimable members of the Hicksian body,
who would not wish to be supposed, as individuals,
to hold the gross errors of principle for which Elias
Hicks was condemned on the one hand,
while he was supported on the other.
These may be said mainly to take a negative position as to doctrine,
having really no living effective testimony to sound doctrine, nor any against the false.
Thus they remain attached to a Society which, to say the least,
is tainted with a denial of "`the Lord that bought them,`"
by the public teaching of very many of its prominent teachers,
as well as by the utterances of Elias Hicks--a Society which has never cleared
its hands by any official disavowal of the palpable errors of these leaders;
and which, indeed,
notoriously has been and still is without the power to purify itself from this taint,
by testifying distinctly against them and their false principles,
and effectually checking their influence within its borders.

Doubtless, some of their members (for whom, as individuals,
I have a true respect and solicitude) lament the
teachings of such evil doctrines among them;
but there it ends.
Why are they without the power to remove the taint?
Because the poison has taken too deep a hold of the body at large--too many are
concerned in it--they have too long connived at it--the bulk of their people
love to have it so--and they could not now clear it out from among them,
in their collective capacity, for they are greatly in the minority.
There are indeed but few among them who are totally
clear from the influence of this poison,
and qualified distinctly to perceive and act upon
the difference between sound doctrine and unsound,
or even to appreciate and acknowledge the baleful
influence of the latter in religious association.
This is an undeniable characteristic of most even of the honest-hearted among that people,
and many of them are openly favorable to great latitude of belief.
Such, alas, is the benumbing result of unsafe association in religious profession.

One of their prominent, talented, and moderate men, Samuel M. Janney,
has lately published a work in four volumes, 12mo, entitled,
A History of the Society of Friends.
The fourth volume exemplifies the truth of the remarks made in the last paragraph.
It is largely characterized by a dissertation (from
its author`'s standpoint) on the Hicksian separation.
In the prior portion of the volume (page 144),
the author makes a sort of apology for some of E. Hicks`'s written sentiments,
implying that the letters written by him during the last year of his life (1829),
should be considered as expressing the settled opinions of that period,
when he was 81 years of age,
rather than some of "`an earlier date,`" which he
thinks were written "`without due consideration.`"
Yet he appears very careful not to specify what sentiments these were,
to which he alludes as "`much to be regretted.`"`' But a little after this (on page 147),
he says: "`This much-abused minister of Christ, as we shall prove in the sequel,
uniformly asserted his belief in the Scriptural testimony
concerning the divinity and mission of Jesus Christ,
and gave assurance of his sincerity by a holy life.`"
Did he not know that the public have access to E. Hicks`'s printed Sermons,
affording abundant proof to the contrary?

In a subsequent part of the same volume,^
footnote:[Page 53 of his Treatise on the Separation.]
S+++.+++ M. Janney makes the acknowledgment, that,
"`Those who are familiar with the writings of the early Friends,
must have observed the deep reverence with which they speak of the blessed Jesus,
as the immaculate Son of God, and Saviour of men.`"
And on page 61, he quotes George Whitehead as saying,
"`And in the same love the Son freely gave his life, yea, even himself, a ransom for all,
for a testimony in due time.`"
But he does not state how different this is from the style
in which Elias Hicks always spoke of the Lord Jesus.
Yet, notwithstanding these admissions,
the same volume is partly occupied by a superficial account of the schism in Ireland,^
footnote:[For an account of which, see the first volume of this work, Chapter II.]
in which Hannah Barnard was so conspicuous,
with an obvious endeavor to screen her and others from the serious
charges brought against them respecting unsound doctrines,
and to make it appear that she was treated with harshness and irregularity.
In the same manner, but with apparently greater care,
the attempt is likewise made to cover up and keep out of view the
principal evidences of error on the part of Elias Hicks,
and to represent him as promulgating the doctrines of ancient Quakerism.

But in endeavoring to do this,
we shall soon see that he unintentionally proves him to have been unsound in the faith,
even in the passages brought forward to show him as sound.
Janney here quotes certain parts of printed Letters of E. Hicks,
wherein he seems to approach sound doctrine; but keeps out of view other Letters,
and very numerous passages in his Sermons,
wherein his extremely erroneous sentiments are particularly prominent.
Yet even in the parts selected carefully by S. M. Janney,
we find such expressions as the following (page 142):
that "`the light within`" is "`our only standard principle from
the beginning,`" and "`the only rule of faith and practice`"--thus
shutting out the Scriptures as even a "`secondary rule.`"
The apostle Paul was not of this mind when he said
that they are "`able to make wise unto salvation,
through faith in Christ Jesus,`" and are "`profitable for doctrine, for reproof,
for correction, for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works.`"
On page 143, he quotes E. Hicks as saying that "`all parts of them +++[+++the Scriptures]
that could not be known but by revelation,
were written by holy men as they were inspired by the Holy Ghost`"--but
adding that "`when the Scriptures have directed us to this light within,
there they must stop`"--as if they were of no further use.^
footnote:[William Penn,
after declaring how the Scriptures had been "`ever blessed to him,
and charging his children "`to read them daily,`" says:
"`For they were given forth by holy men of God in divers ages,
as they were moved of the Holy Spirit;
and are the declared and revealed mind and will of
the Holy God to mankind under divers dispensations;
and they are certainly able to make the man of God perfect, through faith,
unto salvation; being such a clear testimony to the salvation that is of God,
through Christ the second Adam, the Light of the world, the quickening Spirit,
who is full of grace and truth (whose light, grace, Spirit, and truth,
bear witness to them in every sensible soul), as they frequently, plainly,
and solemnly bear testimony to the Light, Spirit, Grace, and Truth, both in himself,
and in and to his people, to their sanctification, justification, redemption,
and consolation, and in all men to their visitation, reproof,
and conviction in their evil ways.`"--Penn`'s Advice to his Children.]

And (page 145) that "`the Book called the Scriptures`" appears "`to have
been the cause of fourfold more harm than good to Christendom since the
apostles`' days`"--and (page 146) that "`it is clear they +++[+++the Scriptures]
were not in any wise accessory to this infant beginning
of reformation`" under Luther and his fellows.
These latter expressions occur in what Janney admits
to have been an "`ill-digested letter.`"
Of the same tendency is a passage quoted by Janney (at page 148),
in which E. Hicks appears as querying thus with regard to the Bible:
"`Yet at the same time, may it not be one of the best books,
if rightly used under the guidance of the Holy Spirit?`"--but adding immediately,
that "`if abused, like every other blessing, it becomes a curse,`'`"^
footnote:[These expressions are in a letter of E. Hicks, in 1825, to Moses Brown,
of Providence, R. I., in reply to one from the latter,
tenderly and faithfully laboring with him on account of his errors.
See The Friend, Philadelphia, Vol.
III, page 333.]
On page 155, we find him quoted by Janney, as saying of Jesus Christ,
that "`he came to be a Saviour to that nation,
and was limited to that nation`"--and (p. 158) that he healed them
"`of all their legal sins`"--(p. 159) that by John`'s baptism Jesus
received "`a more full effusion`" of the Holy Spirit,
"`which qualified him for his gospel mission.`"

On p. 160, Hicks, as quoted by Janney, places "`the miraculous conception of Jesus,
and of Isaac,
and of John the Baptist`" on an equality--and (p. 162) says that
Jesus did not arrive "`at a full state of sonship,`" "`until he
had gone through the last institute of the law dispensation,
viz.,
John`'s watery baptism`"--thus not only making the mistake of including John`'s baptism
as a part of the dispensation of the law (whereas it was altogether intermediate),
but alleging that Christ Jesus was not fully the
Son of God until after he had partaken of it.
Immediately he adds, "`he then witnessed the fulness of the second birth,
being now born into the nature, spirit, and fulness of the heavenly Father.`"
So that the blessed Jesus, according to Hicks, and his advocate, S. M. Janney,
stood in need of regeneration--"`the second birth!`"
And we may here understand how much E. Hicks meant, when he avowed, as he did sometimes,
a belief in the Divinity of Christ.
Did S. M. Janney see this,
when he endorsed him as uniformly advocating the sound views of primitive Friends?
On page 165,
he is quoted by Janney as denying that the crucifixion "`was an atonement
for any sins but the legal sins of the Jews,`" and adding his belief that
it "`was a full type of the inward sacrifice that every sinner must make,
in giving up that sinful life of his own will, etc.`"--only a type, after all!

Would any man, sound in the faith of Christ, express himself after this manner,
or would any man, sound in the faith of Christ, sanction such expressions?
That our primitive Friends held any such sentiments as these,
we may safely and totally deny.
Indeed, it has been over and again publicly demonstrated,
that such allegations are only a revival of the old oft-refuted slanders put forth against
Friends by their persecutors and by apostates and enemies of the Truth.
As to what S. M. Janney says of the great latitude of doctrine
which he thinks was allowed in the early times of the Society,
it has no solid foundation.
The genuine teachings and guidance of the Spirit
of the Lord Jesus never led to such latitudinarianism,
or to such confusion of tongues as would have been the result.
The spouse of Christ was never intended--nor was the Society of the People
called Quakers--to be a heterogeneous mixture of all sorts of opinions.
The early Friends,
notwithstanding all the attempts of the disciples of Elias Hicks to assert the contrary,
had a firm faith--and that a sound one too--in the great truths of Christian doctrine.^
footnote:[This is developed with great clearness in the
Defence of the Christian Doctrines of the Society of Friends,
compiled by Thomas Evans, Edward Bettle, and Joseph Roberts, Philadelphia, 1825.]
And there is ample material in the history of the Society, to prove,
not only that they were no Socinians,
but that they were alive to all attempts to pervert
or misrepresent their faith in the Son of God,
his miraculous birth, his divine life, his propitiatory death,
his resurrection and ascension to the right hand of the Father,
where he now sitteth as our great high Priest, our Mediator and Intercessor.

Thomas Ellwood, in replying to George Keith`'s book,
accusing William Penn and his brethren of Deism,
says that George Keith well knew that neither he himself while he was a Friend,
"`nor William Penn, nor any of the Quakers, were ever deists--ever did deny, disown,
or disbelieve the coming, incarnation, sufferings,
and death of Christ as man outwardly in the flesh, his resurrection, ascension,
and mediatorship--and he +++[+++G. K.]
himself has undesignedly acquitted W. Penn from his present charge of deism,
by a story he told in his first Narrative, page 38,
that upon some one urging him to give an instance of one
English Quaker that he ever heard pray to Christ;
W+++.+++ Penn being present said, '`I am an Englishman, and a Quaker,
and I own I have oft prayed to Christ Jesus--even
him that was crucified.`' This he +++[+++G. K.]
says was in the year 1678.`"^
footnote:[Life, etc., of T. Ellwood, London, 1714, p. 442.]

In those days the denial of these doctrines was not
a prevalent or prominent error in professing Christendom;
but when such denial did occur among those belonging to the Society,
means were decidedly taken to clear the body from such a reproach.
A very plain evidence of this may be cited in the case of Jeffrey Bullock,
who denied the divinity and atonement of Christ, and was disowned,^
footnote:[Historical Memoirs of the Society of Friends, by W. H., 2nd edition,
Philadelphia, p. 247.]
so early as 1675, fifteen years before the death of George Fox.
We must no less emphatically deny the allegation of this author,
that the controversy previous to the Separation of 1827 was between ancient Quakerism,
as represented by Hicks, and modern error, as represented by Gurney.
The views of J. J. Gurney were scarcely known at all in this land
at the date when the opposition to E. Hicks`'s errors became developed;
and those who prominently opposed him, with few exceptions,
were then sound in the ancient faith of the Society,
and brought forward boldly and copiously the ever acknowledged
writings of our early Friends (and not the modern ones),
to prove E. Hicks`'s departure from the faith of the gospel.
And the evidence they thus brought forward was cumulative and overwhelming,
and clearly proved that the Hicks party had shamefully garbled and falsified the statements
of ancient Friends in endeavoring to make them say what they never meant to say.
This has been thrown before the world abundantly in print,
and how can such a writer as S. M. Janney be ignorant of it?

But we here see the most approved author of the present day among the Hicksites,
and one of the most moderate in the expression of their views,
sanctioning several of the unsound sentiments of Elias Hicks,
under the erroneous plea that he was advocating the principles held by the early Friends.
Can, therefore,
any one reasonably doubt that the body of these people
are still clinging to the same views,
so far at least as they really have any characteristic doctrines?
That they are not, and never were, the doctrines of true Friends,
has already been sufficiently insisted upon.
It is true, as they say,
that the great distinguishing principle of the Society of Friends has
always been their faith in the Holy Spirit as the primary leader,
and guide into all truth.
But this faith never could lead any to deny the plain testimony of Holy
Scripture to the Lord Jesus Christ as the Son and Sent of the Father,
born of the Virgin Mary, and one with Him to all eternity,
or to discard his death on the cross as an atonement for our sins.
Therefore,
their denial or evasion of these precious truths must conclusively prove that their
professed faith in the Holy Spirit is not a true and living and experimental faith therein,
being contrary to the plain testimony of the Spirit itself.
And therefore the party holding those false doctrines,
or permitting them to be held and taught among them,
cannot be the true Society of Friends.
It behooves the honest-hearted among them, to see to it.

With respect to the Gurney party, and their adherents through fear, favor, affection,
or views of interest--large and influential as it is--its claims to be the true
Society of Friends are no less hollow than those of the Hicks party.
We have seen in a previous chapter,
how London Yearly Meeting clearly committed itself to a fellowship
with the doctrines contained in the publications of J. J. Gurney,
not only by frequently sending him forth as a minister in unity,
but by endorsing the eulogy of his soundness contained
in the official Memorial of him after his decease.
We have seen, too, how that previously, in 1836,
they had taken upon themselves the enunciation of one of his favorite
dogmas--that the Bible is "`the appointed means of making known to us
the blessed truths of Christianity`"--"`the only divinely authorized record
of the doctrines which we are bound as Christians to believe,
and of the moral principles which are to regulate our actions`"--a
dogma which opened the door wide for all the subsequent innovations.
We have also seen how, afterwards,
they promptly acknowledged fellowship with all the bodies in America which separated
on the ground of opposition to any check being put upon the spread of his doctrines,
as well as with those who went bodily, without separation among themselves,
in the same direction.
And they who have watched subsequent events have observed
how largely and how rapidly not only London Yearly Meeting,
but all the others involved in the same views,
have gone into either actual or conniving sanction of successive practical innovations,
entirely foreign to the character of Friends,
but the genuine fruit of the self-activity and worldly
religion cherished and promoted by the new doctrines.

It may perhaps be said, on behalf of Philadelphia and Ohio Yearly Meetings,
controlled as they have been of late by the middle party,
that they have never officially sanctioned the departures in doctrine, but testified,
years ago, against them, and may therefore now rest upon that testimony;
and that many of their members still continue to
lament the defection in principle and practice,
and occasionally a document is put forth,
deprecating certain features of its development,
particularly pressing upon their attention for the time.
But do not they, likewise, practically connive at the heresy,
and join in with its advocates--to a degree which the pure truth could never sanction--in
withholding now for many years any clear and open testimony against it as a whole,
or any recognition of those who are openly standing against it--in refraining
from putting the plain requisitions of the Discipline in practice against it--and,
so far at least as Philadelphia Yearly Meeting is concerned,
in constantly amalgamating themselves with it,
and thus sanctioning the assumed position of those engaged in it,
by receiving the ministers from all parts of the Gurney body,
and joining their members continually thereto through
the medium of certificates of membership,
on removal?

"`We recommend this family to your Christian care and oversight.`"
Who can hear these words read, without knowing that it is an acknowledgment of fellowship?
What act could be a more practical or emphatic acknowledgment of it?
On the other hand,
no certificates are thought of as admissible to the "`Smaller Bodies,`"
or their meetings for worship to be attended by any of their members,
but those who join any of these are generally promptly disowned.
Well, but, it is said,
the members of these large Yearly Meetings are still members of the Society,
and we cannot cast them off: if we did, we should entirely isolate ourselves,
sanction the separations which have already taken place,
and promote one within our own borders, which we cannot bear to think of.
Does such reasoning justify a continuing to sanction the standing of those
who are known to be engaged in revolutionizing the Society?

Is it not doing evil that good may come?
Do they argue thus in regard to the Hicksites?
Then why persist in such a course with those whose doctrines are
no less a departure--but a far more insidious departure--from the
fundamental principles of Quakerism--of primitive Christianity?
It has become notorious that J. J. Gurney`'s system
was antagonistic to the spirit of true Quakerism;
but not only is it adhered to by the great body of
the Yearly Meetings formerly called Orthodox,
to distinguish them from the followers of Elias Hicks;
but advances are made by the members, of latter years,
and either tacitly or openly allowed by all those bodies,
practically far beyond what was the limit of the
inconsistencies during the lifetime of J. J. Gurney.
These are too well known to need more than an incidental mention here.

Philadelphia Yearly Meeting, it is true,
has avoided any official sanction of the obvious departures from
many of our testimonies prevalent among the other Yearly Meetings,
and to a considerable extent known also to be existing within her own limits; yet,
as we have already seen,
the avowed partisans of Gurneyism among its members are
continued by it in places of great trust and influence,
and the same class coming from other parts are received
as if they were unquestionably members,
and the fundamental nature of the departure on the part
of the Gurney meetings is almost lost sight of,
or merely alluded to as some cause of uneasiness.
This was rendered particularly and renewedly evident
in the action of Philadelphia Yearly Meeting of 1875,
on the occasion of a bequest of money (about $10,000) left to it,
and a like sum to three other Yearly Meetings, on the condition,
twice expressed in the will, of "`unity with London Yearly Meeting.`"
After considerable discussion of so insidious a proposition,
it was concluded to accept the legacy, and a Trustee was appointed to receive the money,
when offered by the executors, and apply it according to the wishes of the testator!

Thus the Yearly Meeting of Philadelphia not only placed
itself once more on a footing of brotherhood with the three
Gurneyan Yearly Meetings mentioned in the will as its co-recipients,
but bartered away for a sum of money and a hollow peace with the Gurney party,
what little remained of its own testimony against the course of London Yearly Meeting.
It did not dare to say whether it was or was not in unity with that meeting,
whose certificates for ministers it had been for years past rejecting;
but allowed the world to take it for granted that it had no testimony against it,
by concluding to receive the money,
which it was twice told in the will was to be given
to a body "`in unity with the London Yearly Meeting!`"
All the sophistical reasoning (in The Friend and elsewhere) about the
application of the money to the publication of the writings of early Friends,
cannot change the fact that Philadelphia Yearly Meeting has,
by its conclusion to accept money left under such a proviso, ranged itself,
quietly but undeniably,
beside the other bodies which fraternize with London in its apostasy.

The word "`apostasy`" is here used deliberately, and in its full sense,
under the conviction that the Gurney system, with its results and concomitants,
is fully as much an apostasy from the original and
fundamental principles of the Society of Friends,
as was the early Roman church from the Christianity of primitive times.
Can the Yearly Meeting of Philadelphia be fairly supposed to bear
a living and faithful testimony against this great revolution,
under such circumstances?
Has she not already fallen from her high estate into
the snares laid for her by the great enemy of truth;
and will she not be swallowed up of the vortex on whose
margin she has been so long dallying with the danger,
and in which so many have been carried away?
A living church must not consort with dead bodies.
But when we take as it were a bird`'s-eye view of the condition of London Yearly Meeting,
who can doubt that it has lost its vitality as a portion of the true Society of Friends?

In the first place, it has sanctioned, in one way or other repeatedly,
the errors of J. J. Gurney, Edward Ash, and others,
amounting to an abandonment of the Society`'s long-established
and well-known principles respecting the universal and saving
light of Christ as the primary rule of faith and practice,
and the Scriptures as secondary to it,
and a substitution for it of the Scriptures as the first guide,
the only divinely authorized record and appointed means of a knowledge
of divine truth--a substitution of justification by a mere belief
and confession of Christ`'s work without us,
instead of a being made really just and holy by living faith in him,
and in all that he has done and is doing for us,
and obedience to him as the true light within the soul--a substitution
of the activity of self in the unregenerate mind,
instead of a true and humble waiting of the soul on God alone for all its fresh springs,
for all its ability to do anything to His honor or its own
salvation--a practical discarding of the doctrine of perfection,
or the possibility and necessity of freedom from sin--a cherishing of the idea
that prayer and praise are at the command of the creaturely powers of man.

And in the second place,
these changes in doctrine have been followed by their genuine fruits,
in a practical abandonment, by the body,
of the testimony against tithes--an absolute discarding, by the Meeting for Sufferings,
of Barclay`'s Apology as an exponent of our principles--a
suppression of almost all the ancient Queries,
leaving only two mutilated ones to be answered once a year only,
with many other changes in the Discipline--an allowance for, and a frequent practice of,
the reading of the Bible in meetings for divine worship,
and even singing of hymns therein^
footnote:[A series of "`Special Meetings,`" authorized by the Bedford Friends`' Institute,
were held in several of the Friends`' meetinghouses, etc., in London,
from the 26th of the ninth month to the 3rd of tenth month, 1875,
including a "`Devotional Meeting of Workers`" (so styled in the call for the meetings),
held at the Institute, and a "`daily meeting for prayer,
and to make arrangements for the evening meetings.`"
Ministers who contemplated attending the evening meetings were informed that it was
"`essential for them to be acquainted with the arrangements made from day to day.`"
At these "`special meetings,`" Moody and Sankey`'s hymns were sung,
and on one occasion an overseer of one of the meetings in
London gave out one of them to be sung in the congregation.
In the evening of Second-day of the following week,
a "`Meeting for religious and social fellowship`" was held at Devonshire House
meetinghouse (where the Yearly Meeting is held) by appointment of Jonathan Grubb
(a son of the late Sarah L. Grubb!) In the Circular calling the meeting,
all were invited, members or not,
but especially the younger members of the Quarterly Meeting,
and they were informed that the "`special object`" was "`mutual Christian
encouragement and communion in the spirit of the words--'`Then they that
feared the Lord spake often one to the other.`'`" Similar meetings were,
during the autumn, held in different places in England, including one at Bolton,
in the "`Friends`' meetinghouse,`" which was originated by five
members of a committee of Lancashire and Cheshire Quarterly Meeting;
on which occasion "`ministers and Christians of all denominations`" were,
in the printed handbills, "`invited to join in the work.`"
In the "`Friends`' meetinghouse at Leeds five such meetings were held,
the handbills announcing, in large type,
"`Gospel Meetings--Society Of Friends--A Series Of
Meetings&hellip;Several Ministers expected&hellip;to be held&hellip;Sunday,
Nov. 14th, etc. A Bible Reading (for united study of Holy Scriptures,
and for Prayer)&hellip;on Monday, Tuesday,
and Wednesday,`" etc.]--meetings appointed for prayer,
and prearrangement for the proceedings therein--music
practised and taught in families and schools,
and even proposed in meetings for worship--an anomalous Missionary Association,
as a wheel within a wheel,
but incompatible with the Society`'s uniform principle and practice hitherto
in regard to the ministry--the indiscriminate wholesale admission of members
very questionably convinced of our religious faith--the lapse of meetings
for discipline into mere debating assemblies,
including even the Yearly Meeting itself--the allowance
of marriages in meetings between members and nonmembers,
and even when neither party is in membership^
footnote:[The number of marriages in 1874, in which one or both were non-members,
was reported to the Yearly Meeting in 1875, as more than one-third of the whole, viz.,
17 out of 47 or 48.]--the very general discarding of plainness in dress, language,
and deportment, and of simplicity in houses and furniture,
so conspicuous a testimony of our forefathers against the follies and extravagance of
the worldly spirit--the erection of monuments or gravestones in burial-grounds--the
allowance of all sorts of attacks on our ancient principles to be published by members
with impunity--meetings for studying the Bible by means of human learning and self-reliance,
these meetings being adopted by the Yearly Meeting,
and inserted on its List of Meetings--the substitution of such meetings
in many places for the meetings for divine worship--a prevalent disposition
to undervalue the important doctrinal stand taken by the Society,
and to place it on a level with the platforms of other denominations,
under a fallacious plea for charity and no judging,
and that controversy must be shunned by all means--a cowardly
evasiveness and equivocal roundabout way of speaking,
even in the issues of the Yearly Meeting itself, and its committees,
when called by necessity to speak of our distinctive principles--and many other departures,
too numerous and too rapidly accumulating to be specified
here--which plainly evince to the candid mind,
that the change is a fundamental one, and that London Yearly Meeting,
which once stood so faithful to the ancient standard of Truth,
is no longer a true representation of Quakerism,
but that its present pretence of being still a Yearly
Meeting of the religious Society of Friends,
is a palpable deception and imposition on those ignorant of the state of the case.

These facts are well known to the members of the Yearly Meeting of Philadelphia;
yet that meeting could not, in 1875, attempt to condemn London Yearly Meeting,
but was willing to appear to the world as if in unity with it!
Was this from a desire to secure the money so conditionally bequeathed,
or was it from fear of offending the open advocates of J. J. Gurney?
If the former, how humiliating its position!
Or if the latter,
does it not show the hopeless subserviency of that Yearly
Meeting to the revolutionary majority in the Society?
Should any attempt be made on the part of the advanced Gurneyites,
as has lately been somewhat ostentatiously threatened,^
footnote:[The Friend, Philadelphia, tenth month, 16th and 30th, 1875.]
to gain possession of the property of Philadelphia Yearly Meeting by legal proceedings,
there will then be no safety in the halfway course, pursued by the middle party in Ohio,
by which they lost their suit;^
footnote:[See chapter 14 of this volume.]
but the almost inevitable result will be a loss of some at least of their valuable property,
and consequently of their standing or prestige before the community at large,
unless an open and unmistakable stand is taken on the primitive principles of the Society,
with as open and candid a declaration that London
Yearly Meeting has departed from those principles,
and is no longer the "`London Yearly Meeting of Friends,`" but a schismatic body,
palming itself falsely on the world as the true Society.
Rome is no longer the Christian church, profess it as highly as she may.
And is not the apostasy as obvious in the one case as in the other?

Within London Yearly Meeting, and by some of its prominent members, attacks,
as we have already seen, have for years been continually made on Barclay`'s Apology;
and it is now openly repudiated by the Society there,
and given up to the reproach of being no longer acceptable
as an exponent of the doctrines of Friends.
The doctrinal writings of others of our ancient worthies are equally obnoxious;
but this being the one most prominently acknowledged for the last two hundred years,
is the chief object of attack.
If that falls,
the doctrines of which it is an exponent and advocate are got out of the way.
How is it possible for any candid person to avow
the belief that those engaged in such a course,
or those quietly conniving at it by continuing in religious connection with them,
can have a valid claim to be considered the true Society of Friends?
This becomes still more obviously inconsistent,
when we consider their action toward the "`Smaller Bodies`"--those who "`are
everywhere spoken against,`" by the members of the class just mentioned,
and especially by those of the "`middle`" party.
It was proved in the plainest manner that what these
"`Smaller Bodies`" were contending for,
was the continued maintenance of our ancient faith and principles,
which they believed were being laid aside,
and a plausible substitute established in their stead.
Yet the Gurney party never would meet them on this ground;
but always contrived side issues or evasions,
and charged the "`Smaller Bodies`" with disregard of the Discipline,
when they stood firmly aloof from them,
as a last resort for safety against their schismatic
and palpably irregular and revolutionary measures.

The position of these "`Smaller Bodies`" was by no means one of factious opposition,
nor of a desire or choice to stand aloof.
They were, after a long course of testifying against the innovations,
with clear and unanswered proof of the facts,
but without success in stemming the current,
compelled to take the isolated stand which they now occupy,
by a conscientious conviction,
and in submission to the manifestations of the light of truth to their minds,
that their spiritual safety depended on clearing themselves from
the influence of and connection with that insidious spirit,
which was bringing revolution over the nominal Society,
and threatening the total devastation of our ancient testimonies.
In taking this course,
they knew that they were giving up many outward advantages
appertaining to association with large and established bodies,
possessing fine meetinghouses, school-houses, and funds,
and abundance of other property,
as well as the general good esteem of the community at large,
many of whom were not qualified to judge, nor much disposed to care,
whether the original principles of Friends were abandoned or not.
Yet what was all this,
to put in comparison with the consciousness of a faithful endeavor to maintain
the purity of the principles of our forefathers in the ever-blessed truth,
and a belief of the approval of the Most High,
testifying to their spirits that their course herein was right in His holy sight?

It is true that they found themselves deserted in the hour
of trial by many who had professed to hold the same views,
and even by some who had been rightly "`armed and carried bows`" for this warfare,
but who, as we have seen,
"`turned back in the day of battle,`" and "`cast away the shield`" of faith;
and that consequently they were reduced to a very small number,
compared with those who took the popular track.
Yet even so was it with the primitive church, soon after our Lord`'s ascension;
when we are told that "`the number of the names together was about one hundred and twenty.`"
Numbers, we know, furnish no criterion of truth or righteousness.
Else would the worldly spirit be the standard of truth, the world over.
But the great Head of the church can work by few or by many;
and he "`hath chosen the weak things of the world to confound the things that are mighty;
and base things of the world, and things which are despised, hath God chosen,
yea and things which are not, to bring to naught things that are;
that no flesh should glory in his presence.`"

It is necessary to remember that the separations
which resulted in the isolation of the Smaller Bodies,
began in New England with the outrageous attempts
of the followers of J. J. Gurney to sustain his cause,
and to put down all opposition to the spread of his influence and views.
The resulting isolation of the Smaller Body there,
brought an additional responsibility upon faithful
Friends elsewhere (especially in Ohio and Pennsylvania,
where it might almost be said that they had been promised effective aid and encouragement),
inasmuch as,
besides the necessity pressing upon these to sustain their
own standing in the pure truth and against the new ways,
they now felt that it was also their incumbent duty to own, and aid,
and unite with their brethren who had already taken the stand,
and whose names were "`cast out as evil, for the Son of man`'s sake.`"

This circumstance likewise took away the validity of the excuse so gladly
seized by some of those caught in the net of the middle system,
that "`no way opened to take any course;`" for thus a way had opened,
by the sustaining of a Yearly Meeting in New England on the ancient ground;
and it was their duty to rally to this standard for the truth, and encourage those who,
in much weakness, were endeavoring to uphold it,
by evincing their brotherhood with them therein,
instead of standing coldly aloof from them "`in the day of their distress.`"^
footnote:[Obad+++.+++, 11 and 12.]
But choosing, as many did in that dark day,
to stand aloof from them and from all those who took the same position,
and to "`pass them by on the other side,`" such became merged in
the great and overwhelming flood of the adherents of innovation,
and are now without power to effectually withstand it.
"`Inasmuch as ye did it not to one of the least of these my brethren,
ye did it not to me.`"

Far be it from the writer to undertake to eulogize the "`Smaller Bodies,`" or to arrogate
for the members thereof any extraordinary experience in the way and work of the Lord,
or any, the least ability of themselves, without his assistance,
to take one step in his service, or in the working out of their souls`' salvation.
But they are entitled to their due,
and to be judged without prejudice by their genuine fruits,
fairly and not captiously taken,
and not by the fruits of dead branches which have fallen off from them.
They have never yet been even accused of a departure
from the original principles of the Society;
while both the others, the Hicksites and the Gurneyites,
have had it plainly proved upon them.
Their very position, as may be seen by a perusal of the foregoing chapters,
is owing to their maintenance of these original principles
against determined defection and change,
or against a pusillanimous connivance at such defection.

As a body, they have not assumed a profession of lofty attainments,
or any disposition to say, I am holier than thou; but rather,
I am bound to the ancient landmarks, which ye are tearing away.
Neither can they be fairly charged with a spirit of vituperation; for though,
during the period of the controversy,
they earnestly and firmly contended for the faith once delivered to the saints,
and sustained their own ground in proving the fallacy of the positions of their opponents;
yet since that has passed over, and they are apart,
they have chiefly evinced a desire to "`mind their own business,`" in an earnest
endeavor to walk worthy of the vocation wherewith they are called.
The property question, or any claim for the meetinghouses, school-houses, etc.,
they have entirely let go; preferring to have to start as it were afresh,
as to outward circumstances,
rather than enter into contention with their former
brethren for the things of this world.

As to their fruits, it is not for them to speak; neither is it for those to judge,
whose principle is the activity of self in an unregenerate mind,
which can always be doing something for self to feed upon.
But this they leave to the Lord.
It may be safely said that a living ministry has been raised up and sustained among them,
to the refreshment of the heritage,
and the convincement of serious inquirers after truth;
and that a concern is maintained for the right administration of the Discipline.
Should any good result come of their position,
in the gathering once more of a people to the Lord`'s praise and glory, as,
we confidently believe,
will come in his own time unless this remnant also
should prove unfaithful to its holy calling,
it is felt among them that such good result will be all of and from Him,
and to his honor alone.
But it is not for the servant to ask what will be the result.
It is his duty to do whatever is clearly called for by the Master,
leaving the results to Him who alone can foresee them or control them.

Much reproach has been openly and persistently cast upon the Smaller Bodies,
on account of the "`divisions and subdivisions`"
which have unhappily occurred among them,
the origin and nature of which have been somewhat sketched in this volume;
and some advantage has been taken against them on account
of sundry individuals who were at first among them,
now walking with them no more.
It is hoped, however,
that in the first class of cases the candid reader may have perceived that the
stand taken by the Smaller Bodies was not accountable for these divisions,
though their weakness in some degree may have been so;
but that they were mainly brought about by the half-way system,
which was so busy with its insidious work of picking off their weak or unwary members,
and thus thinning their ranks.

As to the individual cases of desertion of the cause,
they were only what might have been looked for,
in a consideration that the weakness of human nature would doubtless be eagerly seized,
and gladly and artfully made use of by the adversary of Truth in a stormy day,
in his disintegrating attempts against a small company everywhere spoken against,
and composed of individuals in various stages of religious experience,
some of whom were particularly open to his insinuations "`as an angel of light.`"
And it is some evidence of life in these Small Bodies,
that they were able to stand firmly notwithstanding
the defection of certain of their brethren,
instead of allowing the standard to be shaken or obscured
by illusory attempts to retain them in a false position.

The Smaller Bodies generally have from the first been fully
sensible of their apparently insignificant numbers,
and their weakness and inexperience in the work of the Lord;
and have by no means desired to set themselves up as examples for others to follow,
any further than as they might be plainly seen, by those walking in the light of Truth,
to be following in the footsteps of the flock of Christ`'s companions.
Their concern, as already intimated,
has been to clear themselves and their families from entanglement in palpable error,
to "`seek a right way for themselves and their little ones,`" to be found walking
in the good old paths of their forefathers--whoever else might depart from them,
or connive at such departure; and they have had comfort, and now have peace,
in this endeavor, though by no means upholding their own course as faultless,
or desiring to deny that they are in themselves a poor, and weak, and afflicted people,
sustained alone by the helping hand of Him who, as they confidently believe,
has led them hitherto, and who seeth not as man seeth.

These "`Smaller Bodies`" thus spoken of,
are at present (1876) composed of the remnants of
the Society described in the previous pages,
as the Annual Meeting of Friends for New England--the Yearly Meeting of New York,
held at Poplar Ridge--the General Meeting for Pennsylvania, New Jersey, etc.,
including now a Monthly Meeting in Maryland, and one in Ohio,
and a small meeting of Friends in Iowa--and the General Meeting of Friends for England,
now held at Fritchley in Derbyshire.
These small companies of Friends are in union and fellowship with each other,
and are avowedly and undeniably endeavoring to maintain
the ancient faith and discipline of the Society,
without compromise with modernization and though very few,
compared with their former brethren, and at times under a feeling of great weakness,
they are often sweetly sustained by a sense of the owning, and help,
and care of the Great Shepherd.
In this renewed sense of his mercy, they can set up their Ebenezer,
knowing his faithfulness; and desire not to be too anxious in regard to results,
or for an increase of mere numbers, without conviction of principle and duty.

Though often thus feeling the greatness of the cause,
and their own unfitness and inability of themselves to sustain it,
nevertheless they remain bound to the testimonies of Truth as held by our forefathers,
and fully convinced of the rectitude of the stand taken in the fear of the Lord,
and of its necessity as a means of preservation from the ensnaring downward
tendency and lapse of the great body of professors of the name of Friends,
from their original and characteristic principles.
There are many here and there among the various professors of the name of Friends,
who lament and mourn over the departures from primitive simplicity and purity;
but who have not hitherto made use of the little strength that might be afforded them,
to come forth in a clear, and practical,
and unmistakable testimony for the ancient and unchangeable truth,
against this fearful and fundamental departure.

The great body of what is popularly called the Society is in a remarkable state of unsettlement;
novelties, one after another in rapid succession, are being pressed upon it;
and it is impossible to foresee what may be the result of the next ten years`' agitation.
But "`a city divided against itself cannot stand`"
against the continued assaults of the enemy.
The atmosphere is gathering dark and windy storm-clouds over the heads of those
who have been abiding in the unstable tents of a temporizing policy.
It may be,
that a future writer may be enabled to add a third volume of momentous changes,
to this History.
For, we may rely upon it,
the Lord will yet have a people to hold up the standard
of his pure truth before the nations;
and he is looking for holy and faithful deeds and life, rather than empty words.

How greatly is it to be desired, that before it be too late for their own safety,
all the honest-hearted ones might be enabled to see eye to eye, and,
taking up the resolution of that valiant servant of Jehovah, formerly,
who "`was full of the Spirit of Wisdom`"--"`as for me and my house,
we will serve the Lord`"--might be faithful to that attractive power which
would draw into oneness all the lowly followers of the Lord Jesus,
and would again grant them the unspeakable benefits of unity and communion
one with another in a visible gathered church of one heart and one mind,
making of a scattered remnant "`a strong nation,`" even
"`an army with banners`" for the Lord`'s blessed cause.
These, abiding in faithful obedience to the Light of Christ,
would not only more and more feel the inestimable
value of the pure principles of the gospel,
but would likewise be enabled livingly to witness
to the truth of John Fothergill`'s words,
in an epistle written in 1705: "`It is the Life of Truth which quickens the soul to God;
if ever we become of His people indeed,
it is by retaining a thirst after the renewed springings up thereof in the soul;
and this alone can keep us to be of His people;
and whoever loseth this true thirst after Life--humbling,
bowing Life--they lose their access to God,
and that wherein alone is acceptance with the Father.`"
For the apostle Paul told the Colossians,
that Christ is "`our Life,`" and his appearance among the saints their glory.

[.the-end]
The End
