== Chapter X.

[.chapter-synopsis]
* The Gurney Schism Continued
* Rise of the Temporizing Party in Philadelphia and Ohio Yearly Meetings.

The Separation, begun, as we have seen, by the modernizers in New England,
necessarily brought before all the other Yearly Meetings the important question:
Which of these two bodies shall we recognize, by the usual epistolary correspondence,
and otherwise, as the true Society of Friends?
Both the bodies in New England addressed epistles to the other Yearly Meetings,
claiming this recognition, and explaining the grounds of their position.
Three of the six other American Yearly Meetings at that time existing, that is,
those of Indiana, North Carolina, and Baltimore,
which occurred during the autumn of 1845, hastily joined in with the larger body,
or Gurney party,
prompted thereto by the great prevalence of the new views within their borders,
by the popularity which J. J. Gurney had gained among them,
and by the outside pressure and bold assumptions of the
leaders of the party in New England and elsewhere,
whose emissaries promptly and zealously went all round,
endeavoring to influence the whole Society by their one-sided representations.

Ohio Yearly Meeting also occurred in the autumn,
but not being so much under the control of the new party,
and many of its members being like-minded with some
in Philadelphia who had no faith in the new system,
and were aware that a grievous wrong had been done in New England,
took time to consider the subject.
Philadelphia Yearly Meeting, occurring in the ensuing spring,
was looked to by these as likely to give the whole
matter a careful examination and clear development.
But this Yearly Meeting itself was becoming more and more divided
in sentiment and weakened in its testimony against the schism,
by incipient defection on the part of some of its
prominent members hitherto advocates of sound doctrine.
Various English ministers had visited the United
States since J. J. Gurney`'s departure from America,
the main tendency of whose labors here had been,
either covertly to promote the new views,
or openly to encourage a temporizing spirit and policy, so as to smooth everything over.
This was eminently the case with John Pease, who at first professed a sort of neutrality,
but going to New England, was present at the separation,
gave the innovators his countenance,
and joined heartily from that time with the Gurney party,
carrying many halfway people with him.
Benjamin Seebohm, coming afterwards, and remaining here between four and five years,
promoted the same cause, though perhaps not with so powerful an influence.

When B. Seebohm, with his companion R. Lindsay,
was about commencing to visit Bucks Quarterly Meeting in Pennsylvania,
the ministers and elders, after the close of the Select Quarterly Meeting,
on a consideration of the circumstance, deputed two of their number, namely,
James Moon and Benjamin Cadwallader, to inform them that, on conferring together,
way did not open in the minds of Friends for appointing
meetings for them within the limits of that quarter;
though they were at liberty, if they inclined,
to sit with Friends in their regular meetings,
without any public invitations being given to the neighbors.^
footnote:[[.book-title]#B. Seebohm`'s Journal,# as printed by his sons,
makes no mention of this occurrence.]
Benjamin Seebohm, soon afterwards, in a private interview with Christopher Healy,
at the house of Ruth Ely, a faithful elder of that meeting, alluded to the subject,
saying that the message which he had received was a sore trial to him,
and that he was desirous of knowing what Friends meant by it.
The conversation which ensued,
which Christopher Healy subsequently related to a Friend
who took down the substance of it afterwards from memory,
is interesting and worthy of record here,
as showing the plain and honest manner in which such advocates of novelty
coming among us were at times dealt with privately by faithful watchmen.

Christopher, in answer to his remark, said to him: "`I need not tell you, Benjamin,
of the troubles and sad divisions which now exist in our once united and peaceful Society;
neither is it needful for me to inform you of the causes
which have produced this sorrowful condition of things,
for I believe you know them as well as I do.
And you know also where these troubles commenced, and that it was in your land,
and not on our side of the ocean, that these things had their origin.
And you no doubt remember that our Meeting for Sufferings did, time and again,
express our uneasiness with the unsound doctrines that were published among you;
and you knew that your meeting would do nothing to remove our uneasiness.`"
Here Benjamin said: "`You only expressed a vague and general uneasiness;
you brought no specific charges;
and you did not even name the individual to whom you may be supposed to have referred.`"
"`It was not necessary,`" replied Christopher, "`for us to mention any name,
because you knew as well as we did who it was, and what it was,
that had caused all these difficulties in the Society.
Besides, if you did not know, it was your bounden duty to make inquiry,
and investigate the causes of our concern;
and then it would have become your duty to take measures
for removing the causes of offence.
But your meeting was too closely united with J. J. Gurney,
in friendship if not in sentiment, to take any step in the matter.
And you may remember that your Yearly Meeting received and read,
just before they set you at liberty to come to this country, an epistle from us,
in which the subject of our uneasiness was brought
freshly and directly before your meeting;
and I must say, that I cannot see how any rightly constituted meeting could set you,
or any other of its members, at liberty to visit us,
before taking the proper steps for removing our uneasiness;
neither can I understand how any consistent Friend and truly anointed
minister of the gospel would be willing to come among us,
knowing, as you did, how much concern and uneasiness you had given us.
I believe such a minister would have borne his burden silently,
until his meeting had given us satisfaction,
or at least until he himself had cleared his hands of the wrong,
by bearing a faithful and public testimony against
those things which had grieved Friends here.
But you have chosen to come among us,
when the peace and unity of the Society has been broken by your Friends,
not as a healer of breaches and a restorer of the old paths to dwell in,
but you have cast yourself and all your influence
into the scale with Joseph J. Gurney and his friends,
who have long been engaged in trying to change the doctrines and
some of the fundamental principles of our religious Society.`"

Benjamin here interrupted Christopher, saying:
"`You do not understand J. J. Gurney`'s views; for if you did,
you would see that they are sound.`"
Christopher then exclaimed: "`Benjamin!
Benjamin!
I am too old a soldier to be turned by such a device as this is.
I have now been fighting nearly or quite sixty years,
under the banner of my heavenly Captain,
and am I to be told that I don`'t understand these
things--that I don`'t know what true doctrine is,
or what is unsound and spurious?
I believe I know what the real principles and doctrines of the Society of Friends are,
though I was not born a member, but came in by convincement.
I was bred among the Presbyterians,
and have seen a good deal of the Baptists and Methodists,
and I think I know what an Episcopalian is,
and I believe that Thomas Shillitoe told the truth, when, in his dying testimony,
he declared that J. J. Gurney was an Episcopalian and not a Quaker.`"
Here the conversation turned aside for awhile to some remarks
on the above mentioned testimony of T. Shillitoe,
which, it seems, some had represented as a fabrication;
but Benjamin acknowledged that T. S. had left such a dying testimony.

Christopher, however,
resumed the subject of the inconsistency of Benjamin`'s coming among us as he did,
which was not in that unity which would make his visit either
agreeable to himself or profitable to us.
"`This was the reason,`" added he,
"`why Friends of Philadelphia could not receive your proposed family visits;
and this is the reason why Friends of Bucks Quarter cannot appoint meetings for you.
We feel towards you as we did towards J. J. Gurney himself when he was in this land,
and we came to the same conclusion then, in his case, as we have now in yours;
and he consequently never came among us in Bucks Quarter, to trouble us.`"
But now came the rise of a party resolved on compromise,
so as at all events to avoid a separation,
which was threatened by the more ardent among the Gurneyites.
This became particularly marked, and gradually more and more apparent,
from the time of the appearance here of the delegation from London Yearly Meeting,
appointed to visit Indiana on account of the anti-slavery
separation which had taken place there.

This delegation consisted, as we have seen, of William Forster, Josiah Forster,
George Stacey, and John Allen,
three of whom had been on the Beacon Committee of London Yearly Meeting, in 1835; and,
as might be supposed,
their influence with many well-disposed Friends who did not see very clearly,
or who dreaded to launch into stormy waters, was very great,
in frittering away an adequate sense of the importance
of the doctrinal questions at issue,
or overshadowing this with the plausible idea of the paramount
necessity of Friends maintaining unity one with another,
and likewise the dreadful consequences of a breach
with so powerful a body as London Yearly Meeting.
The most influential promoter of this compromising system and middle party, in America,
was Samuel Bettle, who had for many years been clerk of Philadelphia Yearly Meeting.
He was soon joined, though not at first publicly or very openly,
by William Evans and his wife Elizabeth Evans,
both of whom had long been acceptable and well-esteemed ministers,
the former then and for many years occupying the
station of clerk to the Yearly Meeting of Philadelphia.
Friends had greatly confided in these two eminent persons,
they having shown much zeal for the ancient testimonies of the Society,
and for a time some warmth in support of John Wilbur,
and denunciation of his persecutors.^
footnote:[Some time after the separation in New England,
William Evans said to the author, with great earnestness,
that if Philadelphia Yearly Meeting should ever sanction
the position of the "`Larger Body`" in New England,
in claiming to he the true Yearly Meeting,
he should feel inclined to retire from all further
participation in the affairs of the Society.
This was a resolution of questionable propriety for
one who stood as a delegated shepherd over the flock.
But the sequel showed how far men may go (by giving way little by little to the
insinuations of the enemy) in a track which they would once have shuddered at.
For only a few years afterwards,
when the compromising system had taken full hold of his mind,
he and his wife were found strenuously urging their Monthly Meeting to grant a certificate
of removal for one of their members to a meeting of this very same "`Larger Body`" of
New England (thus sanctioning its claims to be a meeting of Friends),
even though the measure was zealously opposed by several of their most substantial fellow-members.
And at length by perseverance they gained their point
in carrying the certificate through the meeting.]

The enunciation of these compromising or temporizing views soon attracted
secret or more open concurrence on the part of many of the members,
who thought they saw therein a much more easy and agreeable way of settling the difficulties,
than by the more stern and unattractive but straightforward course
prescribed by the Discipline and former procedure of the Society,
in cases of defection from its acknowledged principles.
Samuel Bettle was neither slow nor unskillful in taking advantage of this turn of affairs,
and managing it for the success of his own purposes;
gradually gaining over most of the members to the policy of doing nothing to stem the
popular current--but "`standing still until they could act in the unity`"--in order
to conciliate the original supporters of J. J. Gurney,
and prevent the separation which these threatened in case
the "`Smaller Body`" of New England should be recognized.
Of course the success of this temporizing scheme would frustrate
the efficacy of all the warnings which Philadelphia Yearly Meeting
had issued against the innovating doctrines afloat in the Society.
But this seemed to be of less importance in their eyes than the
preservation of a superficial and fallacious appearance of unity,
keeping the Society together, however heterogeneous in feeling and purpose.

Time, however, was required, for the full development of such purposes,
and meanwhile Philadelphia Yearly Meeting had the appearance of
a body desiring to maintain the ancient principles of the Society.
But Samuel Bettle was constantly at work with open or underhand contrivances
to establish the supremacy of this compromising or "`middle`" party;
and the strength and clearness which had characterized Philadelphia Yearly
Meeting were gradually frittered away before this plausible breeze;
so that the wrong things making rapid headway in the Society received no effectual check,
and an open and practical testimony against them was more and more discouraged.
He had herein the success attending constant vigilance and industry,
united with great fixedness of purpose,
and the power and art of controlling the Yearly Meeting by his machinery;
for though William Evans, who had succeeded him as clerk,
often inveighed against his schemes in private,
yet gradually it became from time to time more and more manifest,
that in the proceedings of the church he shaped his
course so as to suit Samuel Bettle`'s views,
and incite others to do the same.

Both William Evans and his wife,
in reply to suggestions that a more firm opposition to the new measures was called for,
would take the ground, that "`we must wait till Samuel Bettle was deceased,
and then they would come out!`"
Alas, they foresaw not how short their own day might be after that event,
nor how they might themselves, if unfaithful to present duty,
be afterwards unable to choose their own time for faithful action in the church!^
footnote:[Much more could be said to this important point,
but the author wishes to treat it as softly as may be consistent
with truth and duty--the duty of clearly developing the
mischievous policy and responsibility of the halfway system.]
Thomas Evans, a man of fine intellect and amiable disposition,
likewise had considerable influence,
in promoting the success of this halfway system and party.
For though he had, from the very first of J. J. Gurney`'s appearance in this country,
been one of the most efficient promoters of his cause,
and would have accompanied him on his travels,
had not his father (Jonathan Evans) firmly withstood it, yet when, some years afterwards,
laid on a sick-bed,
and brought to a sense of the great uncertainty of his continuance here,
he was to some degree made sensible that he had gone too far,
and that at least he had given occasion for concern and
uneasiness on the part of Friends whose esteem he valued.
But instead of going to the root of the matter,
and candidly and fully condemning the whole thing,
he endeavored apparently to please one side without displeasing the other,
and at the same time sought to allay the uneasiness of his own conscience,
by publishing in [.book-title]#The Friend# an address to the Society,
containing a general declaration of adherence to the ancient doctrines.

This was good, so far as it went.
But it is an old and true saying,
that "`actions speak louder than words;`" and this paper by no means covered the ground,
either of J. J. Gurney`'s doctrinal errors, or of his own erroneous action,
by which the cause of innovation had been so greatly and so manifestly encouraged.
Yet it sufficed to make an impression on the minds of many
that he was "`coming round`" to the views of true Friends;
and some who had known better, went so far in sympathy with him,
and in hopes of thus having his influence,
as materially to endanger their own safety and weaken their standing in the truth.
Charles Evans had hitherto stood apparently firm for the ancient ways.
In the early part of the year 1846, he published in Philadelphia a pamphlet of 86 pages,
entitled _Considerations Addressed to the Members
of the Yearly Meeting of Friends of Philadelphia,_
with the words of the wise author of the Proverbs for a motto on
its title-page--"`He that answers a matter before he hears it,
it is folly and a shame unto him.`"
The work was designed for the information of the members of Philadelphia Yearly
Meeting in regard to the real facts and circumstances of the New England schism,
and the great importance of coming to a right conclusion.
Indeed it presented a lucid view of the transactions which had resulted in that separation,
and concluded with an earnest appeal to Friends of Philadelphia Yearly Meeting,
to give the question that calm and serious examination,
which its importance and the welfare of the whole Society so clearly demanded.
A few detached extracts may serve to show the tenor of the whole.

The Yearly Meeting of the "`Larger Body`" in New England
had issued an epistle to their Quarterly and Monthly Meetings,
and to the individual members of the Society, respecting the separation,
in which they said:

[.embedded-content-document.epistle]
--

It has been deeply affecting to us to learn that under the
influence of that delusive spirit to which we have referred,
some have accepted such books +++[+++as they chose to consider pernicious,
because they developed the unsoundness of the new views
and the irregular practices of those who sustained them],
and received written or verbal statements from interested parties,
as of almost equal validity with those contained in publications
issued by regularly constituted bodies of valuable Friends,
a description of document to which implicit credence has
heretofore been given--and under such false impressions,
have imbibed and urged individual sentiments,
against the solid judgment of the body--proceedings totally
at variance with that into which the Truth leads.^
footnote:[_Epistle,_ 1815, page 6.]

--

In noticing this arrogant claim to implicit credence for its documents in preference
to those of the "`Smaller Body,`" the author of the _Considerations_ remarks:

[quote]
____

We believe this is the first and only instance in which any meeting in
our Society has ventured the opinion that the validity of a statement
of facts is to be tested by the source from where it emanates.
Such statements, whether the contents of books, written or, verbal,
from interested persons,
or contained in publications issued by regularly constituted bodies of valuable friends,
depend altogether upon truth for their validity;
and we trust our Society will never see the day,
when such constituted bodies shall be considered so far infallible,
as that their documents will be received with any other
implicit credence than that which their truth demands.
If the imbibing or urging of individual sentiments against the solid judgment of the
body must always be totally at variance with that proceeding into which the Truth leads,
then is the right of private judgment not merely a delusion,
but its exercise a crime of the deepest dye.
Were this assertion based upon truth, how, let us ask,
could Luther have stood up against the iniquities of Rome?
How could George Fox and his fellow-laborers have
come out from the lifeless professors of their day?
Or, are we to understand that the body, if made up of professing Friends, is infallible?
Alas! we have had mournful evidence in our day of declension and revolt,
that such bodies, out-numbering by far even that which has put forth this sentiment,
have, by their solid judgment,
sanctioned and joined hands with those who denied the Lord that bought them,
and counted the blood of the covenant an unholy thing.
(P. 16.)
____

At page 22, after saying that any attempt to change or lay waste our settled faith,
"`is treason against the whole Society,`" and showing the obligation which
rests on superior meetings to see that the subordinate meetings do their
duty in guarding the church from any violation of its principles,
the author of the _Considerations_ observed, that,

[quote]
____

If, through weakness or revolt, or from whatever cause,
the Yearly Meeting allows the defection to go on unchecked, then the whole Society,
unless prepared to undergo a change, must adopt such measures as circumstances dictate,
to defend its faith,
and to protect those within such a meeting who may continue loyal thereto,
from being deprived of the rights they possess as its members,
by the perverted use of the Discipline in the hands
of men who have departed from the faith.
____

After succinctly narrating the series of measures which resulted
in the separation in New England Yearly Meeting of 1845,
and distinctly recognizing the Swanzey Monthly Meeting and the Rhode Island Quarterly
Meeting belonging to the "`Smaller Body,`" as the only true meetings of those designations,
the author of the _Considerations_ held the following language in
relation to what passed in New England Yearly Meeting itself,
at that momentous crisis:

[quote]
____

Some may think it would have been better for those who now constitute the Smaller Body,
to have patiently waited until the Yearly Meeting had adopted the
report which it was well known the representatives would make before
they made an effort to maintain the meeting on its original foundation;
but they acted in accordance with what appeared to
them at the time required at their hands,
and to be consistent with the Discipline, in the appointment of clerk and assistant,
and thus continuing what they believed to be New England Yearly Meeting.
The Larger Body acknowledged the representatives of the
Quarterly Meeting set up in the manner which has been described,
and thus identified itself with the meeting of the Separatists,
and with all the extraordinary measures pursued by the Yearly Meeting`'s committee.

Three of the Yearly Meetings which occurred during the last autumn, respectively,
concluded,
upon the report of committees appointed to examine the epistle sent by the Smaller Body,
to decline receiving it, and, so far as that conclusion goes,
have condemned some hundreds of their fellow-members,
and cut them off from communion with them,
without inquiry and without any official examination into the causes which have
led to the deplorable state of things in New England At each of these meetings,
deputations from the Larger Body were present, who,
without attributing any sinister motive to them,
we may believe exerted whatever influence they possessed,
to portray the doings of the body they represented in the fairest,
and those of their dissenting brethren in the darkest
light they could cast over them The Smaller Body,
relying on the goodness of its cause, and the omnipotence of an overruling Providence,
have sent forth none to plead in their behalf.
____

Such were the salutary sentiments expressed in 1846, by the author of the _Considerations._
Would that they had been in subsequent times carried out in practice!
A few years afterwards,
application was made on behalf of the Meeting for
Sufferings of the Smaller Body of New England,
for permission to publish a second edition of this pamphlet;
but they could not obtain it.
Philadelphia Yearly Meeting, or its Meeting for Sufferings,
for some years repeatedly warned the Society in England (through epistolary
correspondence) of the danger to be apprehended from the unsoundness of
the new doctrines so freely circulating both in Europe and America.
And at length, apprehending that these communications,
made to the Meeting for Sufferings in London,
had been withheld from the knowledge of the members in general in England (through the
practice of only reading in the Yearly Meeting a selection from the minutes of its transactions),
Philadelphia Yearly Meeting, in 1846,
concluded to refer to the subject in its Epistle to the Yearly Meeting of London,
so that the epistle to the Meeting for Sufferings last received
had to be produced to the meeting at large.
In replying to that Epistle,
the Yearly Meeting of London barely alluded to this momentous subject,
acknowledging the "`strength, instruction,
and comfort`" to be derived from the epistolary correspondence when "`carried
on in Christian love and condescension,`" but adding this significant hint:
"`We doubt whether these objects will be promoted by entering, in this correspondence,
into the particular consideration of cases, which, whenever they arise,
are the proper subjects of our Discipline in our respective meetings.`"

No satisfaction was received by Friends of Philadelphia Yearly Meeting,
in reply to their brotherly admonitions,
nor any action taken on the part of the Yearly Meeting of London
to avert the danger of which they were thus renewedly warned.
They quietly let the subject drop, as the easiest way of getting rid of it;
though many of their members were sorely grieved at this evidence
that no check could be put to the progress of the new views.^
footnote:[Even so late as 1833,
the Meeting for Sufferings of Philadelphia uttered this
salutary caution to the corresponding Meeting in London:
"`By yielding to this compromising spirit,
weakness and faltering in the faithful support of the Discipline,
in cases of the obvious violation of our Christian testimonies,
are introduced into meetings, to the grief of the rightly concerned members,
and the increase of apathy and lukewarmness.
We fear the influence of this state of things as regards the Society in this land,`" etc.]
Philadelphia Yearly Meeting convened in the fourth month of 1846,
with the serious prospect before its members,
of having to meet the momentous question of the recognition
of one or other of the two bodies in New England.
But it soon appeared that Samuel Bettle and William Evans, the clerk,
were resolved that no recognition of the "`Smaller Body`" should
take place if they could by any means frustrate it or put it by.
Several strangers, of the Gurney party, were present,
exerting their influence among the members.
The London deputation to Indiana was also present, and had, no doubt,
much influence with some of those inclining toward the compromising system,
if not even to settle some entirely among the Gurney party.

The clerk, at an early period in the meeting,
stated that there were two epistles and other papers
purporting to come from New England Yearly Meeting,
and queried whether they had not better be all referred to the Meeting for Sufferings,
that they might carefully examine them, and report their judgment next year.
Much discussion followed this proposition.
Most Friends present had by this time had opportunities
for obtaining a knowledge of the circumstances of the separation,
and of the grounds and causes out of which it sprang.
A large number of the most substantial and weighty members were at that time prepared
to have the claims of the "`Smaller Body "`acknowledged by receiving its Epistle.
But of course the advocates of the new views came out warmly and numerously against this,
and very decidedly urged the reading of the document from the "`Larger Body.`"
Their opposition to the Smaller Body`'s Epistle was greatly aided by the efforts
made by the clerk and Samuel Bettle to put by the reading of either for the present;
in which they were joined by a number of those who under their influence were
already sliding into the fallacious track of the party of compromise.

Most of the sitting was consumed in the discussion of the subject,
and it was evident that the solid sense of the Yearly Meeting,
as expressed by its most weighty and experienced members,
was then in favor of the claims of the "`Smaller Body.`"
Many, though not all, of those who spoke on the side of the Gurney party,
were young persons, or others of but slender religious experience,
and some of them not of consistent life and conduct.
But the clerk (with Samuel Bettle at his side) was determined
that no such result as was then indicated should take place,
as it would be to the dire offence of the Gurney party;
and he finally made a minute referring the whole subject, with all the papers,
to the next Yearly Meeting.^
footnote:[The clerk, on going home, after that memorable sitting, was heard,
by a friend at his table, to remark that at one time that day,
it was clearly the sense of the meeting,
to acknowledge the "`Smaller Body`" of Friends in New England,
and that it was in his power to have done so.
This is important,
as proving that at that time he knew what the solid
sense and judgment of the meeting indicated,
but pursued his own course.]
The Yearly Meeting of New York occurred in the fifth month,
and having a large preponderance of advocates of the new views,
with the clerk also decidedly on that side,
the question of the division in New England was,
without any pretence of examination into its circumstances,
promptly decided in favor of the "`Larger Body,`" or modernizing seceders.
A small portion of the members present demurred,
but their voice was of no avail against the multitude.

Ohio Yearly Meeting, occurring in the autumn of this year,
again had the same important question before it.
There had been for years among the members of that Yearly Meeting
a considerable prevalency of opposition to the new doctrines.
But Benjamin Hoyle, who possessed great influence there,
and had been for a long time clerk of that Yearly Meeting,
placed an undue confidence in certain leading members of Philadelphia Yearly Meeting,
and when they began to temporize, he was soon drawn into full cooperation with them;
and of course many more, who followed in his and their track,
with the same implicit reliance upon the leadership of man,
instead of an individual waiting for the mind of Christ.
The result was that Ohio Yearly Meeting was kept
for years in a state of great disturbance of feeling;
the Gurney party not being able to accomplish a recognition
of their brethren the "`Larger Body`" in New England,
while Benjamin Hoyle was repeatedly appointed clerk;
and he on the other hand was following the example of those in Philadelphia who
were parrying off and baffling all attempts to acknowledge the "`Smaller Body.`"
Thus the "`middle party`" obtained, though the clerks,
a stormy and unsatisfactory control in both these meetings,
at the expense of a straightforward upholding of
their own previous testimony for the Truth,
and in violation of the conscientious convictions of a large portion of the members.

Notwithstanding the formidable defection which was thus
taking place from the ranks of Friends sound in doctrine,
through the example and influence of certain leaders of the people,
yet there was still an evidence of true life existing
among many of the members of these two Yearly Meetings,
both of the older and the younger classes;
and great was the solicitude of these that the Society might
not drift altogether into the vortex of modernized Quakerism,
which had now swallowed up whole Yearly Meetings,
and was evidently bent on revolutionizing the Society.
The Yearly Meeting of Philadelphia had failed to
take any decisive step with regard to New England;
yet most of the members of the Meeting for Sufferings felt the necessity of something
being done to show the grounds on which we stood opposed to the new doctrines and practices.
This it was thought could be done without at once interfering
with the difficult question of the New England secession.
Indeed,
some thought it a necessary preliminary step to any conclusion in regard to the latter,
and hoped that it might open a way by which that could eventually be settled.

A committee was accordingly, at length, appointed in the Meeting for Sufferings,
representing pretty fairly the different shades of sentiment in that body; namely,
Daniel B. Smith, William Hodgson, Charles Evans, Henry Cope, Samuel Bettle,
William Evans, Ezra Comfort, William Hilles, Hinchman Haines, David Cope,
Abraham Gibbons, Thomas Evans, Henry Warrington, and Enoch Lewis.
This committee was industriously,
and some of its number laboriously occupied during the winter,
in a comparison of the novel views,
characterizing the publications of J. J. Gurney and Edward Ash,
with the ancient and established doctrines of the Society as declared by our early writers.
Several of its members being desirous of avoiding
a full development of the doctrinal defection,
much incongruity of sentiment was painfully developed during their deliberations;
and on various occasions so strong was the opposition to a clear
elucidation of the unsoundness of the authors above named,
that it might be said the battle was gained by inches.
But there were some men in that committee who had not yet bowed the knee to Baal,
and who then saw the necessity of a firm contending
for the faith once delivered to the saints;
and the result was the adoption towards spring of a document clearly showing
the incompatibility of the new doctrines with our ancient faith,
and the sorrowful effects which must ensue to the Society,
if the innovations should be permitted to prevail.

This document was presented to the consideration
of the Yearly Meeting in the fourth month,
1847, and was, by a very large expression of approval,
though also with strong opposition on the part of those favoring innovation,
adopted by the Yearly Meeting, and ordered to be published,
entitled _An Appeal for the Ancient Doctrines._
It formed a pamphlet of 68 pages, containing many quotations,
fairly and very carefully selected from an abundance of other passages of the same tenor,
in the works of the two modern writers alluded to;
with ample extracts on the other hand from the ancient standard writings of the Society;
showing their incongruity,
and warning the members against the devastating effects which must ensue
from the prevalency of that system of self-activity and "`lettered divinity,`"
which it was the tendency of the recent publications to promote.
A very large edition was printed and circulated.
Ohio Yearly Meeting afterwards adopted this _Appeal,_
instead of undertaking to prepare anything special of their own on the subject.

But the question of recognition of one or other of the two
bodies in New England as the true Yearly Meeting there,
was still pressing upon Philadelphia,
and many on both sides were anxious for a settlement of it.
The decision had hitherto been warded off by those who feared the consequences
of a conclusion in accordance with the manifest solid sense of the Yearly Meeting.
But at length, in the Yearly Meeting of 1848,
the subject claimed very serious and general attention during several sittings,
having taken a deep hold of the minds of many Friends.
On Third-day morning, soon after the meeting opened, Hinchman Haines arose,
and after making some weighty remarks on the state of things, concluded by saying,
"`I am now ready to receive the epistle from what is called
the '`Smaller Body.`'`" Christopher Healy next said,
"`I was ready when the subject first came before
us;`" and many now followed in the same direction;
so that it seemed as if the cloud had risen from the tabernacle,
and the people might go forward.
But at this juncture Samuel Bettle arose, and said, "`Friends,
you may have strength to carry it through--you may
be able to carry it over our heads--but if you do,
it will be a triumph of the adversary.
I will make a proposition--to refer the subject either to a committee now to be appointed,
or to the Meeting for Sufferings.`"

The latter proposal was immediately responded to by many,
and the Meeting for Sufferings was accordingly directed to make a careful
examination into the circumstances and causes of the separation,
so that the Yearly Meeting on receiving their report might be enabled
to come to a right judgment in this very serious matter.
Toward the close of this Yearly Meeting,
our aged friends Hinchman Haines and Christopher Healy requested
that the meeting might be allowed to close in silence.
The latter was accosted, on his way home, on the steamboat, by Richard Mott,
who with a number of other active advocates of the new views
had attended the meeting from New York and elsewhere.
Richard Mott said to him: "`Christopher, you took too much upon yourself,
and more than any man has a right to do,
when you prevented Friends who were in attendance of your Yearly Meeting with credentials,
from spreading their concerns before their brethren.`"
Christopher replied:
"`I thought all these people had amply sufficient time for unburdening their minds,
and I think they took, at the very least, their full share of our time,
and gave us opportunity enough for the exercise of forbearance toward them.`"
"`I allude,`" said Richard, "`to the closing sitting of your Yearly Meeting,
when you so improperly, as I think, closed the door against them,
and prohibited them from relieving their minds.`"

[.discourse-part]
_Christopher._--It was my friend Hinchman Haines
who made the remark to which you have alluded,
and which was, to the best of my recollection,
to this purpose--that it was very desirable that in these our annual
assemblies we should be permitted to sit together in solemn silence,
to seek after the influence of ancient goodness,
that we might feel its power to sweeten and harmonize our hearts; adding,
that our Yearly Meeting had often been favored to
separate under a solemn covering of reverential silence,
and he hoped it would be so on the present occasion.
It is true that I endorsed his sentiments, for I had full unity with them;
and I added the expression of my desire to his,
that we might be permitted to get into stillness before the Lord,
that the meeting might close under a solemn covering of good.
Our Yearly Meeting certainly has the right, under divine authority,
to say when and how its sittings shall terminate;
and I trust we shall continue to exercise that right and authority which the Truth gives.

[.discourse-part]
_R+++.+++ M._--I have been told that on Fifth-day at the North
Meetinghouse you took Benjamin Seebohm to task,
publicly in the meetinghouse, for preaching too long,
as you were pleased to consider it.

[.discourse-part]
_C+++.+++ H._--Well, Richard, if I did rebuke Benjamin for his too much speaking,
he at least deserved it.
He certainly preached long--much too long,
as I believe--and without any unction or life about it, as I could discover.
It was words, mere words.
And I did by him what I hope my friends will do by me,
if they find me preaching without life and authority, as Benjamin was doing.

[.discourse-part]
_R+++.+++ M._--Your Yearly Meeting is taking too much upon itself,
in presuming to judge another Yearly Meeting,
over whom you have no right to exercise any authority whatever,
because it is as independent a body as your Yearly Meeting is.

[.discourse-part]
_C+++.+++ H._--Our Yearly Meeting has just the same right, under divine authority,
to express its uneasiness, or even to deal with another Yearly Meeting,
as one individual has to deal with another individual,
under the feelings of religious concern.
And one Yearly Meeting may, if needs be,
set the judgment of Truth over another Yearly Meeting;
for it has always been the privilege--no, the duty--of those who are in the Truth,
to judge those who are out of it.

[.discourse-part]
_R+++.+++ M._--But how do you know that these friends in New England are out of the Truth?

[.discourse-part]
_C+++.+++ H._--We know that J. J. Gurney was out of the Truth,
because his own writings prove it.
His doctrines are not those of the religious Society
of Friends--they are spurious and unsound.
And we know this '`large body`' in New England has endorsed him and his unsoundness,
and disowned John Wilbur because he testified against
Gurney`'s unsound doctrines and principles;
and they thus separated themselves from the Society,
and went out from us because they were not of us.

[.discourse-part]
_R+++.+++ M._--Christopher, there is a shyness between you and me,
which was not felt in old times, and for which I cannot account.
I do not believe the cause of it is in me.

[.discourse-part]
_C+++.+++ H._--Indeed, Richard, it is very plain that there is such a shyness,
but do you see any change in me?
Am I not what I always was since you first knew me, the same in sentiment,
the same in doctrine, the same in love and zeal for the Truth?

[.discourse-part]
_R+++.+++ M._--I do not accuse you of having changed.

[.discourse-part]
_C+++.+++ H._--Well then, Richard, if I have not changed, you must have done so,
for we are evidently far asunder now.

[.small-break]
'''

The steamboat arriving now at a landing-place, they separated,
with an expression by R. M. that he was sorry to part so,
as he wished for more conversation with his old friend.
The above conversation was afterwards related by C. H. to a friend,
who wrote down the substance of it as above from a retentive memory.

The Meeting for Sufferings, in pursuance of the direction of the Yearly Meeting,
appointed a committee of fifteen of its members, namely, Christopher Healy,
Hinchman Haines, Ebenezer Roberts, William Evans, Daniel B. Smith, Israel W. Morris,
Enoch Lewis, Samuel Hilles, William Hilles, Abraham Gibbons, Henry Cope, Morris Cope,
Charles Evans, Joseph Scattergood, and William Hodgson,
to make a careful investigation into the facts and circumstances
connected with the origin and progress of the New England Separation,
and report.
The great importance of the subject thus committed to them,
and the circumstance that the committee was composed of men of
all shades of opinion on the state of the Society at this crisis,
will warrant our going into more detail in respect
to its proceedings than would otherwise be necessary,
or perhaps desirable.
I believe it right indeed here to place on record a succinct statement
of what occurred at the first sittings of the committee,
inasmuch as the successive remarks unfold so clearly the
different phases of opinion and bias of the respective members,
which were further developed as events passed on,
and which are important to be rightly understood.

The subject was felt to be highly important,
and the responsibility of a right treatment of it very weighty.
Several Friends expressed desires that it might be faithfully and honestly gone into.
Our aged friend Hinchman Haines expressed his sense of the great importance of the occasion,
and its intimate connection with the welfare of the Society at large,
and warned against the spirit, so prevalent in some, to compromise.
Christopher Healy (who, in his seventy-fifth year,
had come to the city to attend the committee, through much bodily weakness and suffering,
having within a few days fallen from the top of a
loaded farm wagon) united with these remarks,
exhorting to a faithful honest discharge of the important trust devolved on the committee.
The Gurney members of the committee, however,
wished to limit the examination to the written Epistles of the two bodies,
addressed to us;
but this was shown to be entirely inadequate to enable the
committee to fulfill the injunction of the Yearly Meeting,
to examine into the circumstances and causes of the separation.
Henry Cope said that the committee ought to be governed
by the same rule that governs judicial examinations,
namely, "`the truth, the whole truth,
and nothing but the truth,`" with an openness to receive
all evidence necessary for an arrival at the truth.
Daniel B. Smith wished all to approach the investigation
with minds divested of any preconceived opinions,
and willing to judge, as jurymen, according to the evidence.

Ebenezer Roberts followed him,
with a testimony to the need of the wisdom of man being laid low,
and of our humbly seeking to be enlightened by the Holy Spirit,
in order to be qualified to judge righteous judgment--reviving the saying
of Christ to Peter,--"`Flesh and blood has not revealed this unto you,
but my Father which is in heaven;`" and exhorting all to gather
to that Spirit of judgment which alone could rightly qualify,
so that whatever the church should bind on earth might be bound in heaven.
Samuel Hilles said that having been present with John Pease at
the time of the separation in New England Yearly Meeting itself,
he was entirely settled in his own mind;
and believing in the entire accuracy and authority of the documents issued by
the "`Larger Body,`" and knowing them to have been properly signed by "`the regular
clerk,`" he as an individual did not wish to hear any other statements than those
issued by the body with whom we had always corresponded.
He would not, however, throw any difficulty in the way of others,
being willing that Friends should get "`once more
into the track,`" so that we might "`get along.`"
He was answered by D. B. Smith,
that the matter which he had represented as being entirely settled in his own mind,
was the very question at issue.

At this sitting and one the next day,
the various documents prominently bearing on the subject were read before the committee;
and after much discussion in regard to future modes of proceeding,
a sub-committee of five was named, to digest the whole subject and prepare a report.
During this discussion,
Enoch Lewis and Israel W. Morris objected to any examination
of the disciplinary proceedings of another Yearly Meeting;
but Henry Cope urged the necessity of such examination,
in order to develop the origin of the separation;
and declared that it was evident from the [.book-title]#Narrative#
put forth by the "`Larger Body`" itself,
that they had been guilty of acts not only at variance
with their own Discipline and the usages of the Society,
but of such an outrageous character as to be disgraceful to any body of men.
William Evans said that we could only collect the facts,
and state what each party had done--that it might perhaps appear that both parties
had acted wrong--and he should sincerely rejoice if they could,
in that case, be convinced of the wrong,
and become reconciled to each other--that it would be a happy thing if
this Yearly Meeting could be instrumental in bringing such a thing about--he
lamented this so frequent example of separation.

Daniel B. Smith,
apparently aware of the weakness characterizing these remarks under existing circumstances,
said that no reconciliation could be effectual,
but such as should go to the bottom of the evil--that a wound, before it could be healed,
must be probed to the bottom--else we should only be plastering it over,
and making it worse instead of better.
Morris Cope said that Truth was never afraid of investigation,
but it was he that did evil that hated the light, lest his deeds should be reproved.
Enoch Lewis felt wounded at this, taking it as a personal allusion.
But Christopher Healy hoped Friends would keep low and sweet in their spirits,
looking to the Master,
and keeping the Lord at their right hand--that as soon as he awoke that morning,
his mind was impressed with the saying of David,
"`I will place the Lord always before my eyes; because he is at my right hand,
I shall not be moved`"--and he believed that as we kept our own spirits down,
and kept the Lord on our right hand, we should be preserved,
and the great Master would yet be known to be a "`spirit
of judgment to them that sit in judgment,
and for strength to them that turn the battle to the gate.`"
And then portraying the fruits of faithfulness,
he exhorted Friends to submit to have their own wills brought down,
and faithfully to obey the dictates of Best Wisdom.
Deep silence followed;
till Israel W. Morris expressed that he did think
he was willing to submit to divine direction;
but urgently objected to proceeding as proposed,
or meddling with another Yearly Meeting`'s disciplinary transactions.

A younger Friend then said,
"`that he believed that if Friends would be faithful to the pointings of Truth,
we need not fear the consequences--that indeed the only safe way appeared to him to be,
for us to endeavor to know the mind of Truth, and then firmly to pursue that course,
leaving results to Him who can control all to the welfare of his church--that
he believed this committee would be greatly lacking in its duty,
if they neglected to avail themselves of all the important evidence necessary
to a correct knowledge of the case--that the originators of this difficulty in
New England had taken the ground that doctrines were not to be investigated,
and now we were told that discipline was not to be investigated--and if
we followed such advice there could of course be no investigation at all.`"
After some further discussion, the sub-committee was appointed; namely, William Evans,
Henry Cope, Charles Evans, Daniel B. Smith, and William Hodgson.
This sub-committee was diligently engaged through the winter and early spring,
and had many laborious and exercising opportunities together,
before the proposed report was fully matured.
But at length,
after struggling through many difficulties and obstacles thrown in the
way by those who desired to deprive it of its efficacy and clearness,
and submitting to some very undesirable changes in
order to save it from falling through altogether,
the committee at large was able to present it to the Meeting for Sufferings.
That meeting fully adopted it,
though with strong opposition on the part of the Gurney portion of the members,
and directed it to the ensuing Yearly Meeting.

In this report was a detailed statement, gathered mainly, as to the facts,
from the [.book-title]#Narrative# of the "`Larger Body;`" their own account,
when compared with the statement of the same facts by the "`Smaller
Body,`" appearing sufficient to prove all that was really essential
to a development of the causes and progress of the actual schism.
It contained also a statement of the manner in which those
facts were viewed or attempted to be justified by each party;
and concluded with the expression of the committee`'s own judgment,
which it submitted to the Yearly Meeting,
in relation to the character of these transactions, their bearing on the separation,
and the responsibility of those concerned in them,
for the breach of unity which was thus so sorrowfully brought about.
The following is their judgment on the case, as expressed in the Report.
Its great importance will justify the length of the quotation.

[quote]
____

Such is a concise statement of the facts contained
in the Documents which have been submitted to us,
and of the light in which the two parties respectively view them.
Two sets of epistles have been presented to the Yearly Meeting,
both from bodies which assert that they maintain, in their original purity,
the doctrines, testimonies, and discipline of the Society.
The subject is therefore placed before us for consideration without any agency of ours,
and common Justice and the cause of Truth demand
that the claims of each should be impartially examined.

Although each Yearly Meeting is the judge of its own discipline,
there is an understood and implied necessity of conforming in its
decisions to principles of religious duty and Christian doctrine,
of civil liberty and constitutional right, common to us all,
and always acknowledged and held as inviolable by us.
For we are one people the world over.
The right of membership in one Yearly Meeting,
is a right of membership--when duly conveyed by certificate--in all.
A member, let him belong where he may,
has the right of attending meetings for transacting the ordinary affairs of the Society,
wherever they are held.
When, therefore, as in the present case, two bodies come before a Yearly Meeting,
both under the same title,
and each claiming to be the co-ordinate branch of the Society bearing that name,
it becomes its duty, under the guidance of Divine Wisdom,
to inquire into the circumstances of the case,
so that it may not withhold from those to whom they belong,
the precious rights and privileges which membership in our Society confers.

From the statements put forth by both bodies,
it appears clear to us that important principles and usages of the Society,
as well as private rights,
have been disregarded in the progress of the transactions therein recorded.
Some of the more prominent points, in which this has been done,
appear to us to be the following:

[.numbered-group]
====

[.numbered]
_First._
In the attempt to procure the disownment of a minister in the Society +++[+++John Wilbur],
upon an accusation of detraction, and upon other charges,
based upon or growing out of his endeavors,
in accordance with what he believed to be his religious duty,
to prevent the reception and spread of sentiments contained in printed doctrinal works,
written and published by a Friend from England +++[+++J. J. Gurney], then in this country;
which sentiments, in common with many other Friends,
he believed to be opposed to the acknowledged doctrines of the Society.
Every man has the natural and religious right to express his honest opinions,
in a proper spirit and manner,
upon any public sentiment which he approves or disapproves.
If he spreads opinions in opposition to the principles
of the religious society to which he belongs,
he is liable to excommunication for a departure from its faith.
But to attempt to bring a man under censure for defending the Society against error,
by warning the members against the unsoundness of certain published works,
not only violates a plain unquestionable right,
but would be censuring him for the faithful discharge of his religious duty as a watchman,
and giving support to opinions which as a body the Society entirely disapproves.

The object of our Christian compact is to bear testimony to the truth and against error;
to comfort and strengthen one another in a faithful adherence to the truth,
through the power of the Holy Spirit,
that by sound doctrine and a consistent example we may convince gainsayers,
and that the kingdom of Christ may prevail over darkness and error in the earth.
In a work on church government, written by Robert Barclay,
and owned by the Society everywhere, these views are held forth.
He says:
"`We being gathered together into the belief of certain principles and doctrines,
without any constraint or worldly respect,
but by the mere force of truth upon our understandings,
and its power and influence upon our hearts; these principles and doctrines,
and the practices necessarily depending upon them,
are as it were the terms that have drawn us together,
and the bond by which we became centered into one body and fellowship,
and distinguished from others.
Now if anyone or more, so engaged with us,
should arise to teach any doctrine or doctrines contrary
to those which were the ground of our being one,
who can deny but the body has power in such a case to declare,
this is not according to the truth we profess, and we, therefore,
pronounce such and such doctrines to be wrong, with which we can have no unity,
nor any more spiritual fellowship with those that hold them,
and so cut themselves off from being members,
by dissolving the very bond by which we were linked together.`"

This is a plain declaration of the powers of the Society,
and of the reasonableness of exercising these powers,
and that a departure in doctrine breaks the bond which had united the party to the Society.
After expressing the same sentiments on the next page,
Barclay contends that it is the duty of all the members
to protest against every departure from its faith.
He says: "`Have not such as stand, good right to cast such a one out from among them,
and to pronounce positively, this is contrary to the truth we profess and own,
and ought therefore to be rejected and not received, nor yet he that asserts it,
as one of us.
And is not this obligatory upon all the members,
seeing all are concerned in the like care, as to themselves,
to hold the right and shut out the wrong?
I cannot tell if any man of reason can well deny this.`"
Again he says: "`In short,
if we must preserve and keep those that are come to own the truth,
by the same means they were gathered and brought into it,
we must not cease to be plain with them, and tell them when they are wrong,
and by sound doctrine both exhort and convince gainsayers.`"

If unsound doctrines are not to be testified against,
and the flock warned of their pernicious influence,
but the consistent exercised members are to be accused of detraction,
when they declare their dissent from published errors,
then farewell to the maintenance of any sound doctrine in the Church of Christ.
This would be an inlet to the greatest innovations,
and in time might overturn the Society.
How would it be possible for ministers of the gospel,
and other religiously concerned members, to discharge their duty as watchmen,
if they are forbidden to warn the flock of surrounding danger,
arising from erroneous doctrinal works?
The most substantial Friends in this land nobly and
firmly testified against the errors of Elias Hicks,
both publicly and privately, even while he travelled with certificates as a minister;
and they were instrumental in guarding many from imbibing his unsound sentiments.

[.numbered]
_Second._
In a committee of the Yearly Meeting summoning a member +++[+++J. W.]
before it to answer certain charges made by it, dealing with him as an offender,
and requiring him to make concessions to them,
and endeavoring to induce him to sign a written acknowledgment,
drawn up by a part of their own body.

The right to treat with their members,
and to disown or to accept acknowledgments from them for their errors,
belongs exclusively to the Monthly Meetings,
under certain rules prescribed by the Discipline.
Even when a Quarterly Meeting appoints a committee to be incorporated
with a weak Monthly Meeting for the support of the discipline,
the members of the committee, when named in the latter meeting to treat with offenders,
do not serve as a committee of the Quarterly, but of the Monthly Meeting,
having no more power than any other members of it.
And it is, we think,
altogether incompatible with the station which a Yearly Meeting holds in the Society,
and with universal practice, for that body, either itself or through its committees,
to attempt to deal with a member as an offender.
For as it is the highest body to which an appeal can be
made against the decisions of inferior meetings,
the application to it for redress must be in vain,
if it has already made itself a party and prejudged the case.

[.numbered]
_Third._
In the same committee`'s drawing up a charge against a member,
bringing it immediately before his Monthly Meeting,
and insisting upon its being recorded on the minutes,
against the urgent request of the accused that it should be previously investigated;
thereby assuming to itself functions which rightfully belong
to the overseers and to the Preparative Meeting.

The right of an accused person to have a charge against
him brought before the overseers or the Preparative Meeting,
is of essential importance.
There he has the liberty of attending and of meeting
the charge before it is permanently recorded,
and if he should convince the overseers or the meeting that it is unfounded,
or if it can be settled without going to the Monthly Meeting,
the matter would end without any record to hand his name down to posterity with discredit.
Whereas his rights as a member are virtually suspended,
so long as a charge against him remains unsettled on the records of the Monthly Meeting.
We should regard such a proceeding in our own Yearly
Meeting as an unconstitutional exercise of power,
dangerous to the peace and subversive of the established order of the Society.

[.numbered]
_Fourth._
In the same committee`'s bringing the power and authority
of the Yearly Meeting to bear upon the Monthly Meeting,
by claiming the right to join the committee of the
latter in treating with the Friend +++[+++J. W.]
find refusing to him the right of opening and explaining what he alleged to be
the ground on which he had acted in the discharge of an apprehended duty.
The members of the Yearly Meeting`'s committee had neither been incorporated
with the Monthly Meeting nor appointed to deal with the member.
Their presenting themselves in this anomalous manner,
seemed to show a determination to carry a purpose respecting the Friend,
without regard to the usages and order of the Society or the rights of the Meeting.
Where a member`'s character and privileges are at stake,
the spirit and uniform practice of our Discipline require the greatest
liberality to be shown in allowing him time and any arguments or
explanations he thinks necessary to his defence.
Were he denied the opportunity of producing evidence to clear himself,
such denial would quash the proceedings against him,
in an appeal before an impartial tribunal;
for the great object in the administration of Church Discipline is,
not to criminate but to convince and reclaim those who have erred;
and if that cannot be done,
to leave no ground for charging the church with harshness or injustice

[.numbered]
_Fifth._
In the same committee`'s objecting at a subsequent Monthly Meeting to the reception
and adoption of a report signed by seven of the committee who had investigated
the case and declared that the charges had not been sustained;
while they advised the reading of a report of an opposite
character signed by two of the Monthly Meeting`'s committee,
although it was strongly objected to in the meeting.

Such a proceeding in treating with offenders is, we think,
contrary to any practice in the Society that we have ever been acquainted with;
the principle governing in such cases, being,
that of leaning to the side of mercy and forbearance.

[.numbered]
_Sixth._
In the attempt made first, by the Quarterly Meeting`'s committee,
and afterwards by the Quarterly Meeting itself,
to render null and void the minute of South Kingston Monthly Meeting
which accepted the report in the case of the Friend alluded to,
dismissed the charge against him,
and restored him to all his rights as a member and minister;
and in afterwards taking up his case by another Monthly Meeting on the same charge,
and there disowning him without even going through
the regular course prescribed by the Discipline.

It is a great maxim of law and justice, that where a man has been tried and acquitted,
he cannot be again tried for the same offence.
When, therefore,
Rhode Island Quarterly Meeting set aside the minute in the case alluded to,
and directed a new trial,
it violated what must ever be held to be a fundamental
principle in the administration of justice.
The only reasons assigned for this decision,
were certain appointments made in the Monthly Meeting,
which it was clearly within the power of that meeting to make,
which appointments had been recognized as valid by
the Yearly and Quarterly Meetings`' committees,
and for which the individual was in no way responsible.

South Kingston Monthly Meeting being laid down,
and its members joined to Greenwich Monthly Meeting,
contrary to the course prescribed by the Discipline of New England Yearly Meeting;
the latter Monthly meeting, five months after the case had been closed,
and the member fully acquitted by his own Monthly Meeting, and thereby,
according to the admission of both parties,
"`restored to membership,`" took his case upon its minutes,
called for a report from the committee originally
appointed in South Kingston Monthly Meeting,
and at the next meeting received a report signed by two of that committee,
similar in all respects to that made five months before to South Kingston
Monthly Meeting by the same two members of the committee of nine,
and which was rejected by it;
and in a summary manner immediately disowned the
individual without his having met the committee again,
or the whole committee having been together.

The Society of Friends has always guarded with scrupulous care, the rights of its members.
It has carefully avoided seeking to make a man an offender;
and even when a Friend has directly violated the Discipline,
if he has not been treated with and disowned in strict
conformity with its provisions and order,
he is, where justice is done to him,
reinstated on his appeal It is an acknowledged principle among Friends,
that it is better an offender should escape disownment, than that his rights,
guaranteed by the Discipline, should be disregarded.
For if meetings and committees do not keep to the Discipline themselves,
under the direction of the Head of the Church,
on what right ground can an individual be disowned for his error?
We therefore __regard the whole proceeding as at variance
with the organization and discipline of the Society.__^
footnote:[These, and most of the subsequent words in italics in this quotation,
are put so by the present writer.]

[.numbered]
_Seventh._
In disregarding the provisions of the Discipline of New England Yearly Meeting,
in the manner of laying down South Kingston Monthly Meeting, by Rhode Island Quarter,
and attaching its members to Greenwich Monthly Meeting.

That Discipline prescribes the following course to be pursued in such a case:
When a Quarterly Meeting has come to a judgment respecting any difference,
relative to any Monthly Meeting belonging to them,
and notified the same in writing to such Monthly Meeting,
the said Monthly Meeting ought to submit to the judgment of the Quarterly Meeting;
but if such Monthly Meeting shall not be satisfied therewith,
then the Monthly Meeting may appeal to the Yearly Meeting,
against the judgment and determination of the Quarterly Meeting.
And if a Monthly Meeting shall _refuse_ to take the advice and submit
to the judgment of the Quarterly Meeting and notwithstanding _will
not appeal_ against the determination of the said meeting,
to the Yearly Meeting; _in such case,_
the Quarterly Meeting shall be at liberty either to dissolve such Monthly Meeting,
or bring the affair before the next or succeeding Yearly Meeting.

And in case a Quarterly Meeting shall dissolve a Monthly Meeting,
the dissolved Monthly Meeting, or any part thereof, in the name of the said meeting,
shall be at liberty to appeal to the next or succeeding Yearly Meeting,
against such dissolution; but if the dissolved Monthly Meeting,
or a part thereof in its behalf, _shall not appeal_ to the Yearly Meeting,
the Quarterly Meeting shall join the members of the said late Monthly Meeting,
to such other Monthly Meeting as they may think most convenient; and until such time,
shall take care that no inconvenience does thereby
ensue to the members of such dissolved meeting,
respecting any branch of our Discipline.
[.book-title]#Rules of Discipline,# etc., 1826, pp.
118, 119.

This, to us, appears clear and explicit,
rendering it necessary for the Quarterly Meeting,
first to come to a judgment in relation to the difficulty existing in the Monthly Meeting,
proposed to be laid down, and to communicate that judgment to it in writing;
and then to ascertain whether the meeting, or any portion of its members,
intend to appeal from that judgment,
prior to proceeding to dissolve that meeting and
to attach the members of the Monthly Meeting to another.
Now unless we admit the assumption that the advice of a committee,
or of a small part of a committee,
is equivalent to the recorded judgment of the meeting which appoints it (an assumption
which would totally change the long-established practice of the Society),
we think it clear that this portion of Discipline was disregarded in the dissolution
of South Kingston Monthly Meeting and the disposal of its members;
for that meeting had received no written judgment from the Quarterly Meeting in the case,
until it received the minute by which it was declared to be dissolved;
and at the same time,
before the Quarterly Meeting could have known whether the Monthly Meeting,
or any part of the members, would appeal from that judgment,
they were joined to Greenwich Monthly Meeting;
and the latter meeting forthwith proceeded to exercise jurisdiction over them,
in direct violation of their rights, as guaranteed by the Discipline.

[.numbered]
_Eighth._
In the manner in which the members of the Quarterly Meeting`'s committee
interfered to produce a separation in Swanzey Monthly Meeting.
The accounts given by both parties of the Monthly Meeting of Swanzey,
at which the separation took place, agree in stating,
that although the clerk of the meeting (whom both acknowledge to have been in that station,
when the meeting adjourned the month before) had taken his seat at the table,
the whole transaction of proposing a new clerk by one who was not a member of the meeting,
his being united with by a part of the members and by others who were not members,
and the Friend proposed proceeding to act as clerk,
was consummated before any minute opening the meeting had been made,
or any minute from the Quarterly Meeting read.
Now we think it undeniable, that no portion of the members of a Monthly Meeting,
even supposing them to be a greater number,
which in this instance does not appear to have been the case,
could be justified in thus acting; but that they must by such an act,
subject themselves to all the consequences of separating from their Monthly
Meeting and setting up a meeting unauthorized by the Discipline

And those members who thus separated from Swanzey Monthly Meeting,
cannot plead the authority of the Quarterly Meeting for the course they pursued,
inasmuch as those who proposed it and assisted therein,
had exhibited no minute from that meeting,
directing the Monthly Meeting to be reorganized,
and clothing them with power to act in the case.
To us, therefore, it appears clear, that the meeting which,
with its old clerk at the table,
proceeded in the transaction of its business after the others had adjourned,
in no way lost its standing as Swanzey Monthly Meeting,
and that _the others separated from it;_ and that those who,
in Rhode Island Quarterly Meeting, received the report from the latter,
and rejected that from the former, _identified themselves with the separate meeting._

The Discipline points out the course to be pursued where a Monthly Meeting
is refractory and unwilling to take the advice of its superior meeting,
regularly conveyed to it,
but it nowhere clothes a Quarterly Meeting with the power
to select clerks and overseers for its subordinate meetings,
and to oblige these meetings to accept and appoint them.
The acts to which we have now referred,
we believe to be the most prominent among the causes that produced
the separation in New England Yearly Meeting in 1845.
The manner in which that separation was effected is, we presume, known by most,
if not all our members.
Many of those who now constitute the Smaller Body in New England,
thought that the Yearly Meeting was not authorized suddenly to suspend the important
rule of Discipline which requires the representatives to meet at the conclusion
of the first sitting and agree upon a clerk for the year,
and report the same to the adjournment.
Four of the representatives thus thinking,
together with those appointed by one of the bodies
claiming to be Rhode Island Quarterly Meeting,
met and agreed upon Friends to be nominated for clerk and assistant.
Upon these names being proposed in the afternoon sitting,
and being united with by some and disapproved by more, the separation which now exists,
immediately followed.

Although the manner in which this separation was effected was not such as, we think,
affords a precedent safe to be followed in the _organization of a Yearly Meeting,_
yet inasmuch as those Friends who compose the Smaller Body appear to have acted
from a sincere desire to maintain the doctrines and discipline of the Society,
and the rights secured by it to all its members;
and had been subjected to proceedings oppressive in their character,
and in violation of the acknowledged principles of our church government,
we believe that they continue to be entitled to the rights of membership,
and to such acknowledgment by their brethren as may be necessary
for securing the enjoyment of those rights.

The obstruction which exists in our Yearly Meeting,
to the holding of a correspondence with _that body_ in New England _which
has authorized or sustained the proceedings_ upon which we have animadverted,
does not arise from any feelings of hostility to them, _nor from partiality to any man,_
but from a conscientious belief that whatever may have been "`the motive,
_their acts_ have gone to condemn many who have been standing for
the ancient faith of Friends and against the introduction of error;
that, in so doing, wrong opinions have received support,
and the discipline and rights of members have been violated;
and that it was the course pursued by them in these transactions which led to the separation.
Until, therefore, _those proceedings_ shall be rectified or annulled,
we see not how unity is to be restored.

====

____

The reader of this Report will observe the full and lucid statement given of
the circumstances attending the separations of the Monthly and Quarterly Meetings,
and that the judgment of the committee was unmistakably in favor of the claims of the
Monthly and Quarterly Meetings of the "`Smaller Body,`" to be the true meetings of Friends.
All the irregular transactions commented upon were
the deeds of the larger or Gurney portion,
and clearly amounted to a departure from the true order and standing of the Society,
notwithstanding their majority of numbers.
The report openly brands those meetings as separate meetings.
How then was it,
that a similar clear judgment was not sent forward in regard
to the separation in the Yearly Meeting itself,
which was the necessary result of the others?
It was the doing of the party of compromise.
When the report came to be read in Philadelphia Yearly Meeting, it was found,
to the astonishment of some Friends,
that the circumstances of the separation in the Yearly
Meeting of New England were almost left out of view,
being summarily disposed of in a single passage of about a dozen lines;
and the judgment of the committee on this momentous subject was frittered
down to such an ambiguous expression as is the last paragraph but one,
of those above quoted.
This passage appears to have been intended, by its instigators, to muddle the whole,
and blind the judgment of the Yearly Meeting.

It might have been expected that the same careful and candid consideration would have
been given to these latter transactions that was given to those on which they were founded.
But what does this passage say?
Not that the Friends belonging to the Smaller Body,
who were acknowledged and proved to have been subjected to irregular
and oppressive proceedings on account of their desire to maintain
inviolate the doctrines and testimonies and discipline of the Society,
were entitled to our sympathy and encouragement and recognition,
as brethren and sisters engaged in the same precious cause--the cause
so dear to our forefathers--no! but a cold acknowledgment of belief,
that although the manner of the separation was not a safe
precedent in the organization of a Yearly Meeting,
yet as they had been thus irregularly oppressed for their testimony to the Truth,
it was believed they were still entitled to the rights of membership.
And here was the dark and vague charge,
that they appeared to have done something not considered safe as a precedent.
What had they done?
They were not engaged in "`organizing a Yearly Meeting.`"
They were endeavoring to sustain New England Yearly Meeting on its original ground,
against the contrivances of a powerful band of men engaged in perverting
the ancient doctrines and revolutionizing the Society.

The committee here made no attempt to explain in what respect
their proceedings had been unsafe as a precedent,
or how their rights of membership were to be protected
without owning them as the Yearly Meeting;
but left this blind charge as a stain upon their position,
not capable of contradiction from its very vagueness.
With respect to the Monthly and Quarterly Meetings,
they had as strictly followed the evidence adduced,
as if the matter were in a court of justice,
and had declared the meetings of the Smaller Body the true ones, and the others spurious.
But when it came to the separation in the Yearly Meeting--that
all-important matter essentially resulting from the former--there
was no such desire manifested to enter into particulars;
nothing but a vague, one-sided, and very unfair intimation of opinion,
unsupported by the smallest appearance of proof, or even of specification.
The passage bears the appearance of a blot upon the whole report;
of being the production of men who were suddenly arrested
with alarm at the tendency of their own deductions,
and resolved upon contriving something at last to neutralize their force,
and evade the necessary result.
How could this occur?

The paragraph was prepared, aside from the committee, after a very painful discussion,
and afterwards was not proposed for interpolation into the Report,
until near the close of the deliberations;
it was firmly and persistently opposed by some of the committee
who saw in measure its bearing and intent;
and was only submitted to, as it were, at the last moment,
when but about half an hour remained before the whole would
have to be submitted to those who appointed them,
and under the compulsory declaration on the part of its proposers,
that if this passage were not admitted into the report,
the rest could not be sanctioned by them;
and thus the labor of the winter on this momentous subject must have fallen to the ground!
Had the committee been untrammeled by opposing views,
and unanimously taken complete and comprehensive ground, and maintained it throughout,
as men in earnest above all things for the maintenance
and preservation of the pure truth,
without fear of man, or calculating dread of probable consequences,
which were not in their hands, but in those of the Great Head of the church,
they would moreover not have confined themselves to a mere disciplinary
examination and judgment--flagrantly oppressive and despotic as had been
the measures resorted to--but they would likewise have felt it their duty
to show the connection of these outrages in discipline,
with the attempts made to introduce those new and
unsound principles which had been proved,
in the _Appeal for the Ancient Doctrines,_
to be circulating in the Society and threatening its life.

For the absence of any repressive measures on the part of those
in power in New England to prevent the spread of the disease,
and still more their determined opposition to the adducing of any evidence on doctrines,
and their persistent oppression of those who were conscientiously
concerned to expose the nature of the danger,
and warn their fellow-members against its inroads, if fully developed,
would surely have been conclusive proof of their doctrinal defection;
and would thus have furnished (we might say unquestionable)
ground for a prompt and decided judgment,
on the part of Philadelphia Yearly Meeting, that the "`Larger Body`" in New England,
which had thus departed, had left the original basis of the Society,
and was no longer to be recognized as belonging to the same household of faith.
But this, which was proposed in an early stage of the proceedings, but rejected,
would have defeated the plans of those who,
having embraced the views of the party of compromise,
were for promoting a "`peace at all costs`"--a "`peace where there
was no peace,`" nor could be any without a loss of true sight and
sense to those who would thus sacrifice principle to expediency.

At the Yearly Meeting in the fourth month of 1849, this _Report,_
after much stormy opposition to it, was, notwithstanding these deficiencies,
fully adopted by a very large expression of the solid sense and judgment of the meeting;
and a copy of it was directed to be sent to each of the two Bodies in New England
which had claimed our recognition by sending epistles and documents.
By the "`Smaller Body,`" the report was read, cheerfully approved,
and printed for circulation among the members and others.
By the "`Larger Body,`" it was not read, nor accepted, nor of course approved,
nor allowed to circulate among their members any further than they could not prevent;
but a reply thereto was three years afterwards (in 1852) published by them,
entitled _A Vindication of the Disciplinary Proceedings,_
etc.--showing their entire disapproval of the Philadelphia document,
and their resolution to maintain their own course.
The advocates of half-way measures in and about Philadelphia
now raised a cry against the "`Smaller Body`" of New England,
on account of their having printed the Report of Philadelphia on the Separation,
which had been sent to their Yearly Meeting.
This publication of it was sorely distasteful to the leaders of that party,
because it made known, in a way not to be evaded,
the sense and judgment of Philadelphia Yearly Meeting respecting those transactions.
They saw that it would thus be more difficult to repress the recognition
of the "`Smaller Body,`" which the Gurneyites so strongly deprecated;
and accordingly they endeavored to prejudice the minds of Friends,
and were unsparing of their blame on that "`Smaller
Body`" for thus presuming to print the Report.

The Yearly Meeting of Philadelphia convened as usual in the fourth month, 1850.
A document acknowledging the reception of the Report on the Separation,
and their unity with its development of the various transactions
leading to and producing that sorrowful crisis,
had been sent by the Yearly Meeting of the Smaller Body
of New England addressed to Philadelphia Yearly Meeting,
as well as an Epistle from the Larger Body.
The subject was mentioned by the clerk in connection with the Epistles,
after the others had been read; but it soon plainly appeared that he and Samuel Bettle,
and some others, had made up their minds to stop, as far as possible,
all deliberation looking to a recognition of either of the two bodies.
Nevertheless, a great discussion ensued.
Many solid, experienced,
and influential Friends were anxious to have the document from the Smaller Body read,
and expressed themselves plainly and fully to that purpose.
But the Gurney party were decidedly opposed to it,
and Isaac Lloyd warned the meeting that "`the crisis had come,`"
and if they did read the document from the Smaller Body,
it would "`convulse the whole Society.`"

After a time, Samuel Bettle said, "`that from what had transpired,
it was evident to him that no conclusion could be come to with that degree
of unity that should be manifested on so important a subject,`" and proposed
the postponement of the whole matter to another year.
With this the Gurney party generally united,
and a considerable number of others who had confidence in Samuel Bettle`'s contrivances.
Many other Friends, however, objected,
seeing no prospect of benefit in deferring it year after year.
At length a proposal was made by some of the latter,
to postpone the consideration of the question to a future sitting; but the clerk,
who wished to quash it altogether,
informed the meeting that there would be nothing on the minutes to call it up subsequently,
and, along with S. B.,
strongly urged the meeting to cease from any further agitation of the matter.
Very soon, without allowing further opportunity for a general expression,
he arbitrarily proceeded with other business.
Many Friends`' minds were grievously burdened,
and on Fourth-day the subject was again opened.
Friends of much experience and long standing in the Truth expressed their feelings
decidedly in favor of at least reading what our Friends of New England had addressed
to us in acknowledgment of our communication to them.
It was urged that common fairness and civility, as well as the plainest justice,
required us to hear what they had to say in reply.

But all this, and the sentiments emphatically expressed by many Friends, availed nothing.
The clerk remarked that he thought this Yearly Meeting had done its duty,
in reference to the two bodies in New England.
It had, through the Meeting for Sufferings, examined their statements respectively,
and in the document issued last year it had given the views of each,
had endeavored to show wherein important principles had been disregarded,
and had come to the conclusion that the members of the Smaller
Body were to be recognized as members--that they were so recognized,
as they were allowed to attend the meeting!--but that a difficulty
was felt in reference to the organization of the Yearly Meeting,
owing to its being indispensable to maintain the subordination of meetings,
etc.,--adding,
that we had exhorted them to become reconciled--we did not know what way
might open for the restoration of harmony among them--and on that account
he desired the postponement of the whole subject for another year.
He recommended Friends to turn their attention to our own condition as a Yearly Meeting,
and endeavor to build up our own waste places, etc., and then,
having the power to foreclose the discussion, went on with other business.
This result was to the grief of many substantial members,
and to the great exultation of the Gurney faction,
who had worked with the middle party in setting aside the clear judgment of the meeting.
They derived much encouragement from this unexpected success,
and the Yearly Meeting seemed to lose from that time all power to come
to any decision whatever in regard to the New England question.
The darkness that ensued over the meeting was very
sensibly felt during the remaining sittings.
The life of the assembly appeared to be gone.

Towards the close of the Yearly Meeting, on Sixth-day, Samuel Cope,
a minister from Cain Quarterly Meeting, in a weighty and impressive manner,
from a burdened mind, declared his unity with the "`Smaller Body`" of New England,
in substance as follows:

[quote]
____

The foundation of God stands sure, having this seal, "`The Lord knows them that are his.`"
I have never felt a stronger necessity laid upon me to speak than upon the present occasion;
and I must say, that my mind has been bowed down and burdened,
through the various sittings of this Yearly Meeting,
under a painful sense of the low state of things among us.
And this remark applies both to individuals and to meetings;
and I have borne it till I can bear it no longer in silence.

While thinking of these things,
I have remembered the remarkable account which is left us concerning Mordecai the Jew,
who sat at the king`'s gate.
It is recorded of this humble and watchful servant of the king,
that he discovered the wicked conspiracy of Bigthana
and Teresh against their lord and master,
and was thus made instrumental in saving the king`'s life.
Although for a time his important services seemed to be overlooked and forgotten,
yet they were recorded in the book of remembrance, and laid up before the king.
This same Mordecai, although he could sit in deep humility at the king`'s gate,
yet he would not bow down to proud Haman,
who was so full of wrath that he determined to destroy not Mordecai only,
but all the people of Mordecai also.
For this purpose he caused a decree to be sent forth,
and sealed it with the king`'s ring,
that all the Jews within the kingdom should be put to the sword,
vainly imagining that he could thus root out and destroy the servants of the living God.
But at a very critical juncture,
when it seemed to all human apprehension that the
destruction of the poor feeble Jews was inevitable,
the king`'s mind was troubled,
and he commanded that the book of the chronicles
of his kingdom should be read before him,
and in it was found written that Mordecai had done what he could for the king`'s cause.

You may read in the Bible the sad history of those who took part in this wicked conspiracy,
which was waged not against one faithful individual only,
but against all the people of God;
and there learn the awful fate of those who had thus
wickedly conspired against the Lord`'s people.
The application which I feel myself constrained to make of the history thereof is this:
John Wilbur is the Mordecai of our day, who,
while waiting and watching at the king`'s gate, was enabled to detect a conspiracy,
which some of the Lord`'s professed servants had entered into,
against the doctrines and testimonies and inward appearance of his Lord and King.
And he was not only able to detect this conspiracy, but he was faithful in exposing it,
and he was strengthened to bear a clear and faithful
testimony against it in his Master`'s name.
A record of these his honest and faithful services
has been written in the Lord`'s book of remembrance;
and it was because of his unflinching integrity and faithfulness therein,
and because he could not be brought to bow down to the will of those who were banded
together for the purpose of changing the doctrines and principles of our religious Society,
that a decree has gone forth against John Wilbur
and his faithful and suffering Friends in New England,
to root them out of the Lord`'s heritage.

And mind, Friends, this decree was sealed by what purports to be the King`'s own ring,
and bears all the outward appearances of having been done
in accordance with the rules of Discipline under right authority;
and it has also been sent forth and hastened to all parts of our Society,
for the purpose of uniting all together against those persecuted and faithful ones.
And they are even now calling upon Friends everywhere to aid them in their cruel purposes.
And there are those in our Yearly Meeting, professing to sympathize with these sufferers,
who think they will be clear of John Wilbur`'s blood,
although they will not stir a finger to save him,
but are saying in the expressive language of conduct, "`Let not our hands be upon him,
but let us leave him to perish in that pit,`" into which, like the patriarch Joseph,
the malice of his brethren had cast him!
Dear Friends,
such is the conspiracy which has been entered into
against some of the Lord`'s faithful people.
But all this consulting and contriving in the will and wisdom of
the creature will be rebuked to the confusion of its authors.
Yes, I am persuaded,
that it will result in the downfall of those who think to
overturn the doctrines and principles of our religious Society.

We ought surely to have read the minute from our suffering Friends in New England.
We were bound to do so by the common courtesy of life,
by the usage of our religious Society, by sympathy for our Friends,
by our love for the truth, and by our faithfulness to the cause of our Lord and Master.
I have thus endeavored to clear my hands of this evil; and I must add,
that I am fully convinced that the Lord owns John Wilbur,
and because my Divine Master owns him, I own him too;
and I also own his and our suffering Friends in New
England as brethren in the fellowship of the gospel.
And this is the testimony which I have felt bound to bear publicly this day.
I could not permit this meeting to separate without making an effort to relieve my tried
and burdened mind of some part of that painful load which has rested upon it;
and, having done so,
I am strengthened with a renewal of belief that "`the foundation of God stands sure,
having this seal--The Lord knows them that are his.`"^
footnote:[It is remarkable that the only notice of this memorable Yearly Meeting,
to be found in the printed [.book-title]#Journal of William Evans,# who was its clerk,
and whose journal contains more than 700 closely printed 8vo. pages,
is in the following ten words: "`Our Yearly Meeting was opened today,
and was very large`" (see page 471).]
____

The control now assumed by the middle party over
the transactions of Philadelphia Yearly Meeting,
prevented that meeting from taking firm and consistent ground in
its subsequent treatment of various matters growing out of the
sad condition of disunity to which the Society was now reduced.
Under the timid and half-way system of measures to which it henceforth resorted,
it refrained from anything tending toward the disownment of those
who were openly identifying themselves with the schism,
and even from any clear and unmistakable course with regard to
the Yearly Meetings which had plunged themselves into it.
It was thus brought into palpable inconsistencies
in its attempts to retain its position in some degree;
and some of these inconsistencies the Gurney party
did not fail from time to time to expose in print.
A periodical entitled the _Friends`' Review_ was issued weekly
by some of the members of that party in Philadelphia,
and in its columns the proceedings of the Yearly Meeting were often freely handled.

It cannot be controverted that in several respects
the Yearly Meeting laid itself open to much animadversion,
for its timid course led it repeatedly to transgress the
provisions of organic law contained in its own discipline.
When it declined the usual epistolary communications with other Yearly Meetings,
which had joined in the schism, it was bound by its fraternal duty to them,
and by the usage of the Society,
to give some plain reason for its dissatisfaction with them and suspension of the correspondence.
But this it dared not do.
When their ministers came to attend its sittings, they were allowed to do so,
and to go all through the meetings within its limits, both for worship and discipline,
but their credentials were not permitted to be read or noticed;
whereas the Discipline explicitly declares,^
footnote:[[.book-title]#Discipline of Philadelphia Yearly Meeting,# page 160 of old edition.]
that certificates of Friends attending the meeting from other parts
under religious concern "`are to be read therein.`"

This measure opened a wide door for ministers from all parts of the lapsed portions
of the Society to travel and preach and insinuate their principles within its limits;
whereas the true and honest course would have been to take the open ground,
that such came from meetings which had joined the secession,
and therefore they could not be recognized as Friends.
Such a course, no doubt,
might have provoked opposition at first from those favoring the seceders;
but the anticipation of this should have been no reason for so
irregular a proceeding as the palpable and persistent violation,
by the Yearly Meeting itself, of one of the plain rules of its Discipline.
But still more important was the fact that,
while it suspended the usual epistolary correspondence with other Yearly Meetings,
it left open the far more vital correspondence through certificates of removal,
by which the members were being constantly recommended "`to the
Christian care and oversight`" of meetings which were known to
have departed from the sound principles and practices of the Society,
and were in intimate union with those engaged in the schism,
and promoting the spread of the new doctrines.

In the seventh month, 1849, assembled in Baltimore a joint Conference Committee,
composed of committees appointed by the Yearly Meetings of New York, Baltimore,
North Carolina, and Indiana, and the "`Larger Body`" of New England.
The ostensible object of their assembling was "`to take
into consideration the present tried state of our Society,
and to labor for its restoration to that unity and
fellowship that formerly characterized it;`" or,
in other words, to endeavor to bring about, in Ohio and Philadelphia Yearly Meetings,
a union with them in owning the Gurney party of New England as the true Yearly Meeting.
The Yearly Meetings of Ohio and Philadelphia had declined to participate in the conference,
and,
from the fact that the "`Larger Body`" New England was admitted as a constituent
party in its deliberations on the same footing as the four other Yearly Meetings,
it was plainly seen from the first that its conclusions
would be altogether one-sided and pro-schismatic.

This joint committee, as the result of their deliberations,
issued an address to the Society, in which a profession was made, in general terms,
of adhering to the important testimonies connected with our Christian profession;
and a declaration was rather ostentatiously put forth,
of the subordination due from inferior to superior meetings in the order of the Discipline.
Independence was claimed for the respective Yearly Meetings,
and an attempt was made to show them to be irresponsible to each other,
except in case of any great departure from the distinguishing doctrines of the Society,
in which case they might be admonished through the annual epistolary correspondence.
But any interference with them by another, in the administration of their own discipline,
was denounced as an infraction of our established order,
and fraught with perilous consequences.
The refusal to receive credentials issued by meetings
of another Yearly Meeting was also objected to,
as well as "`any attempt to confer upon individuals
privileges forfeited in their own meetings,
or to sustain them in assumed rights to which they are not entitled.`"

These things were evidently thrown out against Philadelphia Yearly Meeting;
and the committee expressed their judgment in a somewhat threatening manner,
that "`it is not to be expected that the great body of Friends can long remain passive,
if important and vital practices and usages of our Society,
which are essential to our prosperity as a people, are neglected or violated.`"
But they made no attempt to bring forward any specific charge of such violation or neglect,
nor did they in the least degree clear themselves
from complicity with the "`Larger Body`" of New England,
in the gross violations of the fundamental requisitions of gospel order and discipline,
which Philadelphia Yearly Meeting had proved to have
taken place there for the sustaining of the new views.
This address was ably answered in 1850, and shown to be entirely _ex parte,_ futile,
and illusory, in a lucid pamphlet published anonymously,
supposed to be by the author of the _Considerations_ of 1846.

Although Philadelphia and Ohio Yearly Meetings had declined to appoint committees,
or take any part in this conference,
a deputation of several of the members of it attended
Philadelphia Yearly Meeting in 1852 with the address,
and with minutes of North Carolina and Baltimore Yearly Meetings,
expressive of their authority to present it to that of Philadelphia,
doubtless in the hope of inducing it to sanction their positions.
The minutes of those two Yearly Meetings were read, out of courtesy to those bodies,
but the Yearly Meeting decided not to read or accept
the address of the Committee of Conference,
in whose deliberations they had previously declined to participate.
This, however,
left the question of New England still unsettled in Philadelphia Yearly Meeting,
and weakness on that point was increasing year by year.
