== Chapter XI.

[.chapter-synopsis]
* Progress of the Gurney Schism Within New York Yearly Meeting

In the Yearly Meeting of New York the modernizing party, who had the control,
assumed great activity upon the occurrence of the separation in New England,
and by their preponderating numbers and influence were too successful
in procuring a prompt acknowledgment of their brethren the "`Larger
Body,`" as the Yearly Meeting for New England,
regardless of their many gross departures from justice and from the order of the Society,
for the promotion of the defection from its true principles.
This "`Larger Body`" had appointed "`correspondents`" to countersign, or attest,
all documents to be sent beyond their borders, such as certificates of removal,
minutes of ministers travelling, epistles, etc., as a sign of their genuineness,
and to thereby give them currency as if coming from
the true meetings of Friends in New England.
Their purpose was to get beforehand with the idea,
and spread it all over the land at once, that they were not the seceders,
but that the "`Smaller Body`" were so.
A list of these correspondents was sent to the different Yearly Meetings,
or to their Meetings for Sufferings which met in the interims,
and were consequently more to be relied on for promptness;
so that the members in their respective subordinate meetings might be informed,
and their action regulated accordingly in such a way as to insure,
without further inquiry,
the recognition of all documents signed by their "`correspondents,`"
and the refusal of all those not so signed,
and thereby sanction their claim to be the true Society.

Among the rest, these lists were sent to Philadelphia and to New York.
In the Meeting for Sufferings of Philadelphia the list was promptly and decidedly rejected,
as coming from a body not recognized by the Yearly Meeting.
I well remember the laconic and emphatic language of Henry Cope on that occasion:
"`I would as soon consent that we should receive a document from a meeting of Hicksites.`"
Indeed there were in that meeting, at that time,
but few to advocate openly the reception of such a paper.
But in New York it was cordially accepted,
sent down to the meetings for discipline by the Meeting for Sufferings,
with injunctions to those meetings to conform their actions thereto,
and afterwards sanctioned by the Yearly Meeting.
This measure had the intended effect of fixing the various meetings for
discipline at once in a recognition of the "`Larger Body`" of New England,
to a very great extent.
It was an insidious device,
shutting out examination or any calm deliberation on the question,
wherever it was admitted.
Of course, all the meetings which, with or without a knowledge of the circumstances,
accepted such a list, and conformed their official action thereto,
identified themselves with the meeting in New England which had issued it.
But in various parts of New York Yearly Meeting,
dissatisfaction was felt with the measure, and in some this was freely expressed.
In Stanford Quarterly Meeting,
it is said that the direction of the Meeting for Sufferings was not acceded to,
but that the subject was dropped, or its enforcement quietly suspended.
But this, being a sort of compromise, left it open to be renewed, or tacitly acted up to,
at any future time.

In Scipio Quarterly Meeting there was decided opposition to it;
many Friends being convinced that the body issuing this list had,
by its proceedings in promotion of schism,
forfeited its claim to be considered a Yearly Meeting of Friends,
and that it was their indispensable duty to refrain from doing
anything whereby that claim might have strength given to it,
and the claim of their brethren suffering for the ancient faith might be shut out.
The conscientious objections of these Friends were, however,
opposed by their fellow-members favorable to the "`Larger
Body,`" in several successive Quarterly Meetings,
until, in the fourth month, 1847, a minute was made,
and sent up to the ensuing Yearly Meeting in the city of New York,
to the effect that the subject had produced much exercise among them,
but that they did not unite in acceding to the measure as requested.
When this minute was presented to the Yearly Meeting,
such was the determination of the leaders there to compass their purpose,
and such was the extraordinary submissiveness of other prominent
characters for the sake of a superficial appearance of peace,
that a committee was appointed to visit Scipio Quarterly Meeting,
clothed with authority to form a component part of that Quarterly Meeting,
and specially directed to see that the desire of the Yearly Meeting
for the recognition of those lists should be carried out.

At the succeeding Quarterly Meeting of Scipio this committee attended,
and a clerk being at the table who favored their views,
facilitated the success of their mission.
The list from New England was accordingly carried through
the meeting by their and his influence and exertions,
though firmly and weightily objected to by many Friends; and was minuted by the clerk,
and sent down for the acceptance of the Monthly Meetings.
The Monthly Meeting of Scipio having also a clerk favorable to these new measures,
accepted the document, thus identifying itself with the Separatists in New England,
and with the adherents of that party within their own Yearly Meeting.
This brought many Friends there,
who desired to continue to support the ancient principles of the Society,
into a great strait.
Some of them now felt constrained to decline the attendance of meetings
for discipline held under a subordination so schismatic and irregular,
believing them to be supporting that which was out of the Truth,
and denying fellowship with those few who were suffering for their testimony to it,
and against error.

A number of these Friends, previous to the Preparative Meeting of Scipio,
preceding the Quarterly Meeting in the ninth month, 1847,
met together to consider the trying position in which they were now placed.
They agreed in judgment,
that if they should participate in the business of the meetings in their present position,
they would render themselves accessory to the schism;
and they were led to believe that the time had come for them to endeavor, with best help,
to take a united and open stand in testimony against these innovations.
Accordingly they drew up a short document,
expressive of their conscientious objections to the
course pursued by those in apparent authority.
As they had already taken the ground that they could have no part in the
proceedings of the meetings for discipline in their new position,
the only way which seemed open for them to present the paper to the other members
of the Preparative Meeting was at the conclusion of the meeting for worship,
immediately before the closing of the partition shutters
between the men`'s and the women`'s meetings.

At the time proposed,
the members assembled were accordingly informed of the character
of the paper which it was proposed to read.
But so clamorous an opposition to it at once arose from a number of those present,
that the Friend who had risen for the purpose of reading it was unable to proceed;
and while Friends were calmly endeavoring to allay the opposition,
efforts were made by some present, in an abrupt and uncivil manner,
to close the shutters.
There seemed, therefore, to be no way left for Friends, but to withdraw;
and it was accordingly proposed,
that those who were concerned to support our ancient
principles should retire to a dwelling-house adjacent.
About half the meeting (as it was supposed) repaired there,
Friends walking silently to the house,
under a sense of the solemnity and importance of the occasion,
and believing that nothing short of being driven to the last extremity could have induced
them to take this step for the preservation of a conscience void of offence.
"`And sitting down together, at this time of deep exercise and trial,
looking to the Fountain of all our sure mercies,
they had thankfully to acknowledge the tendering and contriting
influence of Israel`'s unslumbering Shepherd,
cementing their hearts together and melting many present into tears.`"

It appeared to be right to proceed with the usual business of the Preparative Meeting,
as far as practicable;
and as a number of Friends were present from North Street
(another Preparative Meeting of the same Monthly Meeting),
it was concluded to hold the Monthly Meeting also, in its usual course,
the following week,
regardless of an adjournment made by the opposing party
for the accommodation of the Yearly Meeting`'s committee.
A committee was now appointed to prepare a document
explanatory of the proceedings of Friends,
and of the extraordinary circumstances which had led to the present crisis.
This document was subsequently produced to the Monthly Meeting,
where it was approved and placed on record.
The following extract from it will show the position
taken by these Friends to be one of vital principle,
and not of mere notions or technicalities:

[.embedded-content-document]
--

A lamentable schism has lately taken place among Friends in New England,
which we believe was occasioned by a defection in principle,
that led to the disownment of a sound minister,
in a manner very much at variance with the spirit of Christian love; who, we believe,
was conscientiously, and in accordance with the Discipline of his own Yearly Meeting,
bearing a testimony against unsound doctrines published
by conspicuous members of our Society,
which have been for a considerable time in circulation all the Yearly Meetings,
and have caused much pain and uneasiness to many honest Friends.
This, together with the arbitrary and high-handed course taken against several other Friends,
who appeared to be honestly and conscientiously contending
for the maintenance of our Christian faith and discipline,
we believe,
produced the separation--many Friends justly believing that
if concerned individuals for the prosperity of the Truth,
were not permitted to hold forth the voice of warning
against the spoiler of the Lord`'s people,
by bearing a testimony against unsound doctrine,
which appeared to be undermining our holy profession,
without eliciting unprecedented and undisciplinary proceedings against them,
the ground of our profession must be inevitably changed.

Under this view, we believe,
a faithful remnant in New England rallied to the standard of ancient principle,
and as their last and only resort, were obliged to come out from among their opponents,
so that they might bear an unfettered and efficient
testimony in support of the unchangeable Truth,
and against those unsound principles which were evidently increasing among us,
and which seemed to be working a revolution in the doctrines of our Society,
and insidiously drawing many from the true place of rest and safety.
This part, although embracing the smaller number,
we consider the true Society of Friends;
who are not even charged with holding or promoting unsound doctrine.
But their opponents, although embracing the larger number, we believe, by their actions,
have forfeited their claim as the true Society,
from their disownment of sound and sincere Friends,
for the cause and in the manner to which we have alluded;
thus unavoidably implicating themselves with unsoundness,
and are seceders from the Society.

--

The Scipio Monthly Meeting of Friends of the ancient faith, held at the usual time,
appointed representatives to be in attendance at
the time and place of holding the Quarterly Meeting.
Thus was Scipio Monthly Meeting rescued from the hands of those who were
perverting an assumed authority in the church to purposes destructive
of the essential characteristics of our religious compact--who were prostituting
to party purposes that beautiful order and discipline established in divine
wisdom for the government of the flock in the life and sweetness of Truth.
In Hector Monthly Meeting, west of Cayuga Lake,
sound Friends had sufficient influence to prevent
the acceptance of the list from New England.
They also declined to recognize the authority of the Yearly Meeting`'s committee,
taking the ground that it was an unprecedented circumstance,
unauthorized by the Discipline, and at variance with the spirit of the gospel,
for such a committee to be made by the Yearly Meeting
a component part of an inferior meeting,
for the special purpose of obliging a compliance
with its direction to adopt a particular course,
contrary to the conscientious convictions of the members;
and especially as this committee was appointed by a meeting which
had identified itself with the supporters of unsound doctrines,
and ought not to be regarded as really having the authority which it claimed.
A few of the members took an opposite view,
and the Yearly Meeting`'s committee attempted to displace the clerk of the Monthly Meeting,
and appoint one subservient to their own wishes.
At length,
perceiving that they could not prevail to frustrate
the steady procedure of the Monthly Meeting,
they desired their own partisans to refrain from participating in the business;
and when the Monthly Meeting adjourned,
they and the few members sympathizing with them remained together,
instituted a separate meeting of their own, and adjourned to the following day.
Hector Monthly Meeting appointed representatives as usual to the Quarterly Meeting.

The Monthly Meeting of De Ruyter had likewise declined
to receive the list from New England;
and one of the representatives,
who had in charge the report from that meeting for the Quarterly Meeting,
was with the Friends of sound doctrine.
Friends of these three Monthly Meetings,
being thus freed from the schismatic proceedings
and control of the committee and its adherents,
held the Quarterly Meeting of Scipio at the usual time.
As the meetinghouse was occupied by their opponents,
there seemed to them to be no other way but to hold
their meeting in a school-house adjacent,
rather than to go in and contend for the occupancy of their meetinghouse.
It was thought that the Quarterly Meeting as now held embraced
about one-half the members of the former Quarterly Meeting.
They had a favored and solemn meeting,
wherein the wing of Ancient Goodness was felt to be mercifully spread over them,
and his compassionate regard experienced to their great comfort.
The mouths of some of their ministers were opened in a remarkable manner,
and a sweet evidence was felt,
that to those who are endeavoring to walk in the simplicity of the Truth,
he is a God near at hand, with whom is no variableness, neither shadow of turning;
the same beneficent Preserver of his truly dedicated people, yesterday, today,
and forever.

Scipio Quarterly Meeting, thus liberated, continued to hold on its way,
in a straightforward course, consistently with our ancient profession and practice.
In an Address to Friends, published by it in 1848,
(from which some of the above particulars are taken,)
they used the following impressive language,
respecting the backsliding which had overtaken the Society:

[.embedded-content-document.address]
--

For many years past,
the true burden-bearers among us have been pained
to observe the relapsing condition of our Society,
gradually assimilating, in their apprehension, with a worldly spirit;
which appears to have dimmed that clear perception of the Truth,
and the things appertaining thereto, with which our worthy predecessors were favored,
and to have made way for multitudinous weaknesses to creep into the church;
among which may be noted,
the declension of attending meetings in consequence of the pressure of domestic concerns;
too easily giving way to drowsiness when assembled
for the solemn purpose of divine worship;
the facility with which almost every request for membership was acceded to,
and almost every acknowledgment received,
when the applicants evinced very little conformity to the Discipline,
either by their behavior or outward appearance;
the great difficulty with which the Discipline could
be brought to bear against some individuals;
and the reluctance manifested in testifying against offenders by timely disownments.
These departures from original faithfulness by imbibing the spirit of the world,
appeared to make way for a more serious and obvious declension,
that of a disaffection to some of the most important
and characterizing doctrines of our Society,
as exemplified in the preceding relation of the state
of things in this Quarterly Meeting.

And thus, dear Friends, through a measure of suffering,
have we been favored to move forward,
without having any cause to look back with regret at the course we have taken;
and although our meetings are smaller since we have met in our present select capacity,
yet have we great cause, though often under a humbling sense of our shortcomings,
to look with confidence to him whose tender mercies are over all his works,
and whose overshadowing presence we have found, time after time,
crowning our little assemblies with the issues of life.
And being thus owned, as we humbly trust, in our procedure,
by the great Head of the church,
we feel encouraged to extend the language of invitation to all sincere and honest Friends,
desiring that they may, as ability is afforded,
endeavor to support the precious doctrines, principles,
and testimonies that our honored predecessors felt bound to do amid great opposition,
and not shrink from the path of suffering.

--

And in a pamphlet published in the autumn of 1848,
containing strictures on the report of the above-mentioned Yearly Meeting`'s committee,
etc., they express the following salutary and discriminating sentiments,
in reference to the necessity of a right subordination of inferior to superior meeting:

[.embedded-content-document]
--

We readily admit that,
except in cases where superior meetings have changed their ground of faith,
or have compromised their principles,
all inferior meetings are very properly accountable to them;
and a due deference from subordinate to higher meetings,
while they continue to adhere to the same unchangeable
principles of truth from which all right order proceeded,
and by which alone it can be healthily sustained,
is quite indispensable for the harmony and safety of Society.
But a moment`'s reflection must show us the impropriety of sacrificing principle,
merely for the sake of sustaining an empty form of order.
We believe the design and end of all wholesome order to
be the preservation of the church in its primeval purity.
But if the head become corrupt and alienated from the true faith,
it is very obvious that the Discipline might, in many instances,
be converted to the suppression of what it was originally designed to preserve.

When the Reformers protested against the heresies which had beclouded the Romish Church,
would not the same claim of subordination to the rules and ordinances of Romanism,
if they had been yielded to, have completely crushed their successful efforts?
And so at that time of glorious gospel light and liberty,
when our beloved predecessors in the truth were called to
expose those corruptions which still clung to the church,
had they yielded to the appeals of order and submission to the
legally authorized and prevailing religion of their day,
how could they have brought out, and handed to succeeding generations,
those bright and clear gospel truths,
the benign effects of which appear to have pervaded Christendom?
But they firmly and patiently bore the sufferings consequent upon their faithfulness,
or they could not have obtained that standing as lights in the world.
And now it seems equally important to testify against corruptions
and defections which have crept into the Church,
as at that time; and though it lead into proportionate suffering,
we trust there is ground for the belief that the same happy results may be realized.

If Friends had neglected to withdraw in 1828,
when the ruling part of the Yearly Meeting of New York had
identified itself with the Separatists +++[+++Hicksites]
of Philadelphia, and some Quarterly Meetings could not have conscientiously submitted,
it is very clear that the Yearly Meeting could have imposed
the peculiar doctrines of the Separatists upon them,
under as fair a plea of order and subordination as it could now force
upon us doctrines that the Seceders in New England have upheld.

--

Thus far in relation to the Quarterly Meeting of Scipio.
We may now briefly advert to the separation in Ferrisburgh Quarterly Meeting,
another branch of New York Yearly Meeting, which occurred in the year 1851.
Starksborough Monthly Meeting, a branch of Ferrisburgh Quarterly Meeting, had, in 1849,
accepted a certificate on account of marriage,
issued by the Monthly Meeting of Nantucket,
belonging to the "`Smaller Body`" of Friends of New England,
and had allowed the marriage to take place with the sanction of the meeting,
in the regular order of the Discipline, as between fellow-members.
This produced dissatisfaction among those whose feelings
were in unison with the "`Larger Body.`"
They accordingly carried up a complaint against the
Monthly Meeting to the Quarterly Meeting,
in the second month, 1850,
alleging that the individual so permitted to marry (belonging to the "`Smaller
Body`" of New England) was "`not a member`" of the Society.
The Quarterly Meeting appointed a committee to attend to the case.
This committee, being of the same complexion of sentiment as the complainants,
reported to the next Quarter, sustaining the complaint.

The case was then, in accordance with their suggestion, referred to the Yearly Meeting.
Meantime, however, notwithstanding this reference,
the Quarterly Meeting continued its committee, to visit Starksborough Monthly Meeting,
and render such advice and assistance "`as they may think proper, and way open for.`"
In pursuance of this strange and oppressive direction, vague as it was,
the committee proceeded to interfere, in an officious manner,
with the proceedings of the Monthly Meeting,
attempting to control the choice of its clerk,
and to intimidate and set at variance the members.
The Monthly Meeting, therefore, in its own justification,
sent up to the Quarterly Meeting a statement of the grounds on which they had acted;
the separation in New England,
in connection with the unsoundness of J. J. Gurney`'s doctrines,
being shown to be the primary cause of the difficulty.
They also requested that the whole cause of the trouble now in the Society
might be laid before the Yearly Meeting for a thorough investigation.
This, however, was not acceded to by the Quarterly Meeting,
but the Monthly Meeting of Starksborough was forthwith directed to be dissolved,
three individuals being deputed to attend its next sitting,
and to read the minute of dissolution at the close thereof.

When the Monthly Meeting next occurred (on the 29th of eleventh month, 1850),
strong efforts were made by the party in power in the Quarter,
to read the minute of dissolution before the business of the Monthly Meeting was transacted;
and so bent were they on carrying out their purpose, that the Monthly Meeting,
after appointing a committee to take into consideration
the tried condition in which they were placed,
deemed it most prudent to do no further business at that time,
and adjourned to the 3rd of the first month ensuing.
The minute of dissolution was then read by one of the Quarterly
Meeting`'s committee after the adjournment of the Monthly Meeting.
At the next Quarterly Meeting (in the second month, 1851),
Starksborough Monthly Meeting again interceded for a hearing,
and that the decision come to in its case might be rescinded.
But a disposition prevailed to shut out all investigation,
and to proceed summarily against the Monthly Meeting.
A portion of the Quarterly Meeting,
including many of its most upright and consistent members,
were now convinced that the time had come when it was necessary to withstand
the further encroachments of that spirit of schism and misrule which was
disposed to put down all opposition to the spread of the new views;
and a proposal was made,
and acceded to by those who were concerned to maintain
the ancient principles and discipline of the Society,
to adjourn the Quarterly Meeting to six o`'clock in the evening.

The clerk was requested to enter the adjournment on the records, but he refused to comply.
But the meeting convened in accordance therewith in the evening--the clerk
and many others opposed to the measure not attending--and thus was Ferrisburgh
Quarterly Meeting relieved from the control of those who had lately taken
upon themselves to pervert justice within its borders,
for the promotion of the power and authority of the
adherents of J. J. Gurney and the New England separatists.
After thus tracing the successive steps by which these two Quarterly Meetings
were sustained as a remnant on the ancient ground of faith and practice,
and considering their uniform declaration throughout,
that they could not identify themselves any longer with a body
which in their estimation had abandoned that ancient ground,
it can hardly be surprising to find that they declined to enter the Yearly
Meeting in the city of New York by representatives or otherwise.

Some have supposed that they should have waived their objections,
and tried their success in the ensuing Yearly Meeting; others,
that they ought to have remained quietly "`in the body,`" by which it might be
that some of their fellow-members in other portions of that Yearly Meeting would
have been eventually helped to come forth against such palpable error,
and that thus their influence for good might have been greater
than by isolating themselves as they did.
Yet we are not informed by what means they could thus have remained "`in the body,`"
without abandoning their testimony and shutting the door against future escape,
or how they would have avoided being all disowned before the lapse of another year,
if they maintained their testimony.
But these Friends believed they were driven into the position which they now occupied.
The Yearly Meeting,
notwithstanding their repeated solicitation of a thorough examination of the subject,
had summarily rejected their cause, condemned their position,
trampled upon their rights and privileges as members,
turned a deaf ear to their earnest desire to be instructed in what consisted their error,
if error they were in,
and had gone on in a succession of measures calculated
to show its lapse from genuine Quakerism,
in doctrine and practice.
They thus felt that they were driven away from it by its own schismatic course,
and believed that with a clear conscience they could no longer do anything by
which its authority as a church should be promoted or apparently sanctioned.
They were thus left without a Yearly Meeting.

Nearly a year after the separation in Ferrisburgh,
that Quarterly Meeting entered into correspondence with Scipio
Quarterly Meeting respecting the propriety of convening together,
to take into consideration the tried condition of Friends sound
in doctrine within the limits of New York Yearly Meeting.
They also proposed a place of meeting, to which Scipio Quarter agreed,
and requested them to propose a time.
Ferrisburgh, in the second month, 1852,
replied that the cooperation of Scipio Friends was comforting to them;
but that they desired to move no faster in this important
concern than way should clearly open.
They reminded their brethren of Scipio,
that when the cloud rested on the tabernacle of old, Israel were to abide in their tents;
but to journey forward when it was taken up and moved before them--that so it ought
to be with them--that they desired neither to lag behind nor to go before their Guide,
but to be obedient to his heavenly teaching--and they invited Friends of Scipio,
if Truth should clearly open the way, to communicate further with them on the subject,
either by writing, or by the personal aid of a committee.

The same disposition to wait for clear evidence of divine approval of the measure proposed,
and of the mode of bringing it about,
prevailed in their Quarterly Meeting in the fifth month,
and they communicated this to Scipio by minute;
at the same time desiring them to take such further
steps in communicating with them thereon,
as they might be enabled clearly to see to be right.
Scipio Quarterly Meeting accordingly appointed a
committee to correspond with Ferrisburgh Friends,
and personally to unite with them in deliberation,
and in preparing an address to Friends, if,
"`on endeavoring after right direction,`" way should open to issue one.
In the eighth month,
an "`Address to Friends within the limits of New York Yearly Meeting`" was produced,
and adopted by Ferrisburgh Quarter, and forwarded to Scipio,
proposing to meet in the Poplar Ridge meetinghouse, in Cayuga County,
"`on Second-day after the fourth First-day in fifth month next (1853),
at 10 o`'clock in the morning; that +++[+++as they said]
we may unitedly take into consideration our peculiar situation,
and the trials by which we are surrounded,
and under the guidance of Best Wisdom endeavor to move forward to the
upholding of the standard of Truth in that simplicity in which,
in former days, it was upheld by the Yearly Meeting of New York, but which,
of latter time, has been so deplorably laid waste.`"
This proposal was laid before Scipio Quarterly Meeting in the ninth month,
the men`'s and women`'s meetings being held jointly for its consideration, and,
"`after endeavoring for right direction in so important a concern,`" was united with.

The meeting was accordingly held, in 1853, at the time and place proposed;
and thus the Yearly Meeting of Friends of New York holding the ancient doctrines,
was sustained,
apart from the schismatic influence and control of those
adhering to the meeting in the city of New York,
which had identified itself with the innovating party.
It was a small body, but it was on the ancient ground.
The Yearly Meeting thus held at Poplar Ridge was drawn in brotherly love and sympathy
to address an epistle to the Yearly Meeting of New England ("`Smaller Body`"),
which that meeting, after examination into the circumstances,
accepted as coming from New York Yearly Meeting of Friends,
and issued an epistle to them in return, acknowledging its acceptance,
and encouraging their brethren to faithfulness.

Satan is ever ready with stepping-stones,
to lay them in convenient places for those who want an excuse
for crossing the boundary between truth and error.
This recognition of the little company in New York,
meeting as a Yearly Meeting at Poplar Ridge,
was soon made a ground of blame in Pennsylvania and
elsewhere against the "`Smaller Body`" of New England,
by some who were about to range themselves with the temporizing party,
and who probably had not duly considered--and presently did not
wish to consider or to acknowledge--how inconsistent and defective
it would have been for that body to take any other course.
It is true that the "`Smaller Body`" of New York had not the apparent
advantage of the formal or established outward organization (through numbers,
representatives, clerks, committees, etc.) in its favor, in the crisis of the separation.
But a very little reflection might satisfy the candid unbiased mind that this is,
in such a crisis, a merely technical advantage,
affording no criterion at all of rectitude,
and by no means to be placed in competition with the preservation
of the soundness of our profession of Christian faith,
and the life of Truth in the body.
That which would otherwise be true order and authority
becomes no longer true order or authority,
but a dangerous imitation of it,
when applied by a combination of leading men holding the control,
to the perversion of fundamental truth,
and to the promotion of the spread of innovation as an overflowing
stream over the whole Society.

And notwithstanding the efforts made by the compromisers
to inculcate the idea that "`no greater or more desolating
evil can afflict the Society than the occurrence of separations,`"^
footnote:[[.book-title]#Remarks on Appointment of Clerks in Ohio Yearly Meeting,# by T. Evans,
Philadelphia, 1834, page 15.]
it must be manifest to those who desire, above all things,
the maintenance of our holy profession on its primitive Christian ground,
that the disownment of faithful members for their testimony and warning against error,
and the authoritative permission for heresy to stalk abroad throughout our borders,
unmolested and unrebuked, is tenfold more to be dreaded than a separation,
in which the two who cannot agree, no longer attempt to walk together,
and the unsound and dead branches, being dissevered,
no longer corrupt and benumb with their mildew the
fruit-bearing portions of the living tree.
The circumstance, too, of the possession, by a meeting,
of the same clerk as before the separation, has been greatly overrated and perverted,
in regard to the influence it should have in determining the question,
Which is the true Yearly, Quarterly, or Monthly Meeting?
However desirable it may be, and undoubtedly is,
to have the clerk of a meeting faithful to his duty in gathering
the solid sense and judgment of the meeting,
yet it would be a most dangerous mistake,
to hold the assent of the clerk as an indispensable evidence and criterion,
under all circumstances, of the validity of a meeting`'s conclusion,
and thus to place the church under the hand of any one man, whose dictate, or opinion,
or determinate bias, shall control it beyond remedy,
as being the only orderly expression of its legitimate judgment.

The power of decision is with the church--is indeed its inalienable prerogative and duty,
so long as it is a living church, an assembly of the faithful,
waiting on Christ its head.
The clerk is the member appointed to gather and record its decisions and conclusions,
its writer, and not its president in any sense.
So our forefathers undoubtedly looked upon it.
It would, indeed,
be altogether foreign to our principles to look upon
a clerk as in any degree a presiding officer,
or "`moderator,`" in our meetings; and if the clerk, and all other officers of a meeting,
depart from the principles and essential practices of our profession,
they must be withstood.
The faithful members, be they few or many, in or out of office,
are bound to resist the innovation, as they value their own integrity,
and the safety of the church.
The outcry to be raised about charity and unity, and obedience to authority,
would here be altogether misplaced.
And should the whole authority of a body, assuming to be a Yearly Meeting,
be brought to bear against the original essential principles of the Society,
or against any one of them,
the subordinate meetings are by that act absolved from their
allegiance to the body so lapsed from the Truth,
and must take care of themselves as best they may be enabled,
in pure dependence on divine wisdom.
When so lamentable a crisis comes upon the church,
it is no longer a question to be decided by numbers,
or by what would otherwise be the usual and authoritative practice of the organization;
but we have to fall back upon the first principles of our compact.
And in looking at the records of our forefathers,
we shall nowhere see that to any one man, as to a presiding officer,
was given the power of controlling the judgment of the church;
nor that any assembly can be entitled to claim the authority of the Church
any longer than it retains its allegiance to Christ our Holy Head.

We may learn from some of the expressions of Robert Barclay,
in his Anarchy of the Ranters, or Treatise on Church Government,
what were the views which our early Friends would have entertained
against the inroads of heresy in the church,
and their sense of the right and duty of withstanding it.
In Section VI of that work he says:

[quote]
____

If the apostles of Christ of old,
and the preachers of the everlasting gospel in this day, had told all people,
however wrong they found them in their faith and principles,
our charity and love is such we dare not judge you, nor separate from you,
but let us all live in love together, and everyone enjoy his own opinion,
and all will be well; how should the nations have been?
Would not the devil love this doctrine well, by which darkness and ignorance,
error and confusion, might still continue in the earth unreproved and uncondemned?
If it was needful then for the apostles of Christ in the days of old to reprove,
without sparing to tell the high priests and great professors
among the Jews that they were stubborn and stiff-necked,
and always resisted the Holy Spirit, without being guilty of imposition or oppression,
or lack of true love and charity;
and also for those messengers the Lord raised up in this day,
to reprove and cry out against the hireling priests, and to tell the world openly,
both professors and profane, that they were in darkness and ignorance, out of the truth,
strangers and aliens from the commonwealth of Israel;
if God has gathered a people by this means into the belief of one and the same truth,
must not they, if they turn and depart from it, be admonished, reproved,
and condemned (yes, rather than those that are not yet come to the truth),
because they crucify afresh unto themselves the Lord of glory, and put him to open shame?
It seems the apostle judged it very needful they should be so dealt with (Titus 1:10),
when he says: "`There are many unruly and vain talkers and deceivers,
especially they of the circumcision, whose mouths must be stopped,`" etc.

Were such a principle to be received or believed,
that in the church of Christ no man should be separated from, no man condemned,
or excluded the fellowship and communion of the body,
for his judgment or opinion in matter of faith, then what blasphemies so horrid,
what heresies so damnable, what doctrine of devils,
but might harbor itself in the church of Christ?
What need, then, of sound doctrine, if no doctrine make unsound?
What need of convincing and exhorting gainsayers, if to gainsay be no crime?
Where should the unity of the faithful be?
Were not this an inlet to all manner of abomination,
and to make void the whole tendency of Christ and his apostles`' doctrine,
and render the gospel of none effect,
and give a liberty to the inconstant and giddy will of man to innovate, alter,
and overturn it at his pleasure?

So that from all that is above mentioned we do safely conclude,
that where a people are gathered together into the belief
of the principles and doctrines of the gospel of Christ,
if any of that people shall go from their principles and assert
things false and contrary to what they have already received,
such as stand and abide firm in the faith have power by the Spirit of God,
after they have used Christian endeavors to convince or reclaim them,
upon their obstinacy, to separate from such,
and to exclude them from their spiritual fellowship and communion; for other ways,
if this be denied, farewell to all Christianity,
or to the maintaining of any sound doctrine in the church of Christ.
____

And concerning the power of decision resting in the
testimony of the Holy Spirit through the living members,
he says, in Section VII:

[quote]
____

To give a short and yet clear and plain answer to this proposition,
the only proper judge of controversies in the church is the Spirit of God,
and the power of deciding solely lies in it, as having the only unerring, infallible,
and certain judgment belonging to it;
which infallibility is not necessarily annexed to any persons, person,
or places whatsoever, by virtue of any office, place, or station, anyone may have,
or have had, in the body of Christ.
That is to say, that any have ground to reason thus,
"`because I am or have been such an eminent member,
therefore my judgment is infallible;`" or, "`because we are the greatest number; or,
that we live in such a noted or famous place,`" or the like;
though some of these reasons may and ought to have their true weight
in case of contradictory assertions (as shall hereafter be observed),
yet not so as upon which either mainly or only the infallible judgment is to be placed,
but upon the Spirit, as that which is the firm and unmovable foundation.
____

[.offset]
And a little further he says:

[quote]
____

Nor yet do I understand by the Church every gathering or
assembly of people who may hold sound and true principles,
or have a form of truth; for some may lose the life and power of godliness,
who notwithstanding may retain the form or notions of things,
but yet are to be turned away from;
because in so far (as I observed before) as sanctification, that is,
those that are sanctified in Christ Jesus, make up the Church,
and give the right definition to it; where that is wholly lacking,
the church of Christ ceases to be,
and there remains nothing but a shadow without substance.
Such assemblies, then, are like the dead body when the soul is departed,
which is no more fit to be conversed with,
because it corrupts and proves noisome to the living.
____

On a serious consideration of the above extracts from this work of Robert Barclay`'s,
always acknowledged by the Society as conveying its own principles on these subjects,
and especially if we take into view the whole scope of his argument, we may,
if candid to our own best feelings,
meet with no difficulty in perceiving that the ground
on which our Friends of the "`Smaller Bodies`" acted,
both in New England and in New York,
was consistent with the primary and vital principles of the Society,
as applied against the inroads of fundamental error;
although contemned by "`the wisdom of the wise`" of this world for its apparent weakness,
and for the comparatively small number of those engaged therein.
For the words of the apostle still hold good,
that "`God has chosen the foolish things of the world to confound the wise;
and God has chosen the weak things of the world to confound the things which are mighty;
and base things of the world, and things which are despised, has God chosen,
and things which are not, to bring to nothing things that are,
that no flesh should glory in his presence.`"
