== Chapter XIV.

Progress of the Middle System--One of its Fruits,
The "`King`" Separation in New York--Another, the Loss of the Lawsuit in Ohio

For several years, especially since the decease of the first editor in 1851,
the weekly paper called The Friend, published in Philadelphia,
had been gradually but obviously sliding more and more into
a support of the views and ways of the party of compromise,
called for distinction the "`middle party.`"
That periodical had now several of the most active and influential leaders
of that party very much controlling its course and the tenor of its columns.
While the first editor was living,
favorable allusions to the "`Smaller Body`" of New England,
and statements of the occurrence of its Yearly Meetings, were at times inserted,
for the satisfaction of those interested,
or for information to other Friends that those meetings were still continued to be held.

But soon after his decease came a gradual hushing up of the main subject of the controversy;
comparative silence as to its essential features, as affecting the unity of the Society;
and at length a systematic rejection of all papers tending to advocate
the position taken by the "`smaller bodies`" of New England,
New York, or Maryland, or even mentioning their existence as meetings;
while pieces were frequently published,
reflecting on those who withstood the temporizing system
now prevalent in Philadelphia and Ohio Yearly Meetings;
and any distinct allusion to the fundamental unsoundness
of principle promoted by J. J. Gurney,
and sanctioned by London Yearly Meeting,
and by several Yearly Meetings on this continent, appeared to be cautiously avoided,
or softened down into occasional vague lamentations over the worldly-mindedness
and inconsistency which had overtaken the Society.
But, on the other hand,
a carefulness appeared still to recognize these lapsed bodies as meetings of Friends;
their members being frequently spoken of as such,
while those small remnants that were endeavoring (through much
obloquy and false accusation) to stand for the ancient cause,
were ignored, as if their existence were no longer worth mentioning.

Many Friends had seen and sorrowfully felt this tendency in the paper;
and various endeavors had been made by some among the managers
or "`contributors,`" and by others from without,
to arouse those concerned to a due appreciation of the need of taking
a more distinct and firm stand against the fearful innovations,
and in support of those Friends who were engaged in a conscientious
concern and endeavor to maintain the ancient faith.
But this was without avail.
In the summer of 1857, the feeling that some change ought to take place,
for the security and welfare of the Society, became so prevalent with many Friends,
chiefly in Pennsylvania, New Jersey, Ohio, and New York,
that it resulted in the sending of a Remonstrance to the
"`Contributors`" against the lapsed course of the paper.
The substance of this Remonstrance was as follows:

Esteemed Friends:

We respectfully request your serious attention to the following
brief statement of our sentiments in regard to the position
occupied of late years by the paper under your control,
called The Friend,
in respect to the sorrowful state of things now existing in our Religious Society;
and we earnestly desire your prompt and effective
action in accordance with the views herewith presented.

The original intention of Friends in promoting the establishment of the paper,
was to furnish a vehicle for the defence of the Truth
against the assaults and misrepresentations of gainsayers,
whether backsliders professing to be Friends, or others who never were of us;
and likewise for the conveyance of correct information of facts
calculated to affect the interests and welfare of the Society.
In the Prospectus (Vol.
I, page 1), is the following language: "`Nor shall we shrink,
when we think the cause of justice requires it,
from the free examination of the public conduct of individuals,
and a defence of the course pursued by Friends,
where we believe it to be misrepresented and calumniated,`" etc.
A similar intention and aim, we think, prevailed among those who conducted the paper,
in the early stages of our present troubles.

With such views,
Friends throughout the Society were constantly encouraged to stand
their ground against the encroachments of the innovating spirit
which has made such devastation within the camp.
But for a considerable time past we have been greatly
disappointed in finding a course taken by the paper,
which seems like abandoning the original intent and ground,
leaving the defence of the truth in great measure unattempted,
numerous attacks of its opponents not exposed or repelled, or even noticed,
and correct information of important and deeply interesting circumstances,
entirely withheld.
It is notorious that frequent publications have been issued
and widely spread within the last two or three years,
which are calculated to give to the inexperienced and to the youth,
very erroneous views in regard to the cause and nature
of the difficulties now distracting the Society,
and have proved a great stumbling-block in their way;
and yet but little attempt has appeared in The Friend,
to counteract their delusive tendency and effects, or even to warn Friends against them.

It is also known that accounts of the proceedings of sound Friends in
the remnants of Yearly Meetings preserved from the general defection,
have been entirely refused admission into the paper.
To such a degree has information of this kind been withheld,
that Friends ignorant of the circumstances would
not be able to gather from the columns of The Friend,
any knowledge of the existence, at this day,
of yearly or other meetings of Friends in various parts,
endeavoring to stand firm in their testimony for the Truth and against error,
and clear of the desolating spirit which has carried such
multitudes into disunity with the true Society of Friends.
Besides this, there have been from time to time published in the paper,
essays reflecting darkly, by implication, on sound Friends,
as if they were transgressors of the Discipline,
and out of true order in their movements,
insinuating if not actually charging them with "`unsanctified zeal,`" etc.;
yet in so vague and general a manner--without proof
or specification--as to evade being called to account,
or having such insinuations disproved.

These invectives still continue to be at times published,
sometimes with open charges of a wrong spirit against a certain class, not named,
but aimed at in such a manner as to make it obvious what class was intended;
and sometimes by extracts from ancient Friends`' writings with certain passages italicized,
in order to convey the same charge in a covert way.
Yet it has been well understood,
that no replies to such invectives would obtain the editorial sanction,
or be permitted to appear.
Such articles, and such a course of the paper,
are well calculated to bewilder the minds of our youth,
and lead them to fear that genuine Quakerism has become extinct--that
there is in reality no Society of Friends now to be found in a
consistent maintenance of our original principles and practices;
whereas they might have been instructed that, although greatly scattered and peeled,
yet a large number of Friends (in the aggregate) is still preserved,
whose concern is to maintain the ancient standard of faith and practice unchanged,
and who will doubtless be sustained by the great Head of the church,
in their earnest endeavors to serve Him.
At the same time, these honest and faithful,
but down-trodden and defamed ones might have been encouraged
and strengthened to stand steadfastly through all,
on the alone sure foundation.
It is also understood,
that the dissatisfaction of Friends with the above-described
course of the paper is not unknown to the Contributors,
but that it has hitherto failed to elicit from them
any efficient action to remedy the evil.

Under these circumstances, it is the painful conviction of many Friends, that The Friend,
as at present conducted, has failed to answer the design of its publication,
or to fulfill the wants and needs of the Society and the just expectations of Friends;
and that unless a very decided and speedy change takes place,
a large number of its subscribers will withdraw their support from the paper.
Still, as many Friends feel the need at present existing,
of having some channel through which the cause of Truth may be defended,
and for the spread of correct information of facts,
we may acknowledge a preference that this vehicle may again be The Friend.
We therefore respectfully and earnestly request that prompt measures may
be taken to carry out the necessary change in the course of the paper,
and that such evidence may be given of your intention to make The
Friend conformable to the needs of the present crisis,
that it may be unnecessary for Friends to resort to other means for their relief.

We are respectfully your friends.

The above document was signed by nearly two hundred
of the subscribers and readers of The Friend;
many of them ministers, elders, overseers,
or other deeply concerned and consistent members.
But when presented for the consideration of those to whom it was addressed,
it was treated in a slighting manner,
as if it were the production of disaffected persons; and no satisfaction was given,
nor any perceptible change made in the course of the paper.
Some allusion to this transaction has appeared to be necessary here,
inasmuch as that periodical became a very effective instrument in fastening
the mischievous system of the "`middle party`" on the Society,
especially within the Yearly Meetings of Pennsylvania and Ohio.

In the year 1858, Morris Cope, a minister residing in Chester County, Pennsylvania,
published a pamphlet entitled Authentic Extracts, etc.,
designed to show the utter incongruity of the new system, in doctrine, practice,
and discipline,
with what Friends had ever before been accustomed
to recognize as compatible with their profession,
and the great necessity of firmly withstanding its inroads.
This pamphlet was published with the printed sanction of
thirteen Friends residing in or about the same vicinity,
namely, David Cope, Samuel Cope, Moses Bailey, William N. Scarlet, Solomon Lukens,
Joseph Chambers, William Walter, Joshua Sharpless, Levi Wickersham, Daniel Thompson,
Abiah Cope, Benjamin Maule, and Joshua B. Pusey; whose sentiments, at that time,
it may fairly be supposed, were represented in the work.
Its strictures were very sharp against the Gurney system,
taking the ground that it was fully as "`derogatory`" from the true principles of Quakerism,
as the system of Elias Hicks.
Respecting the New England question,
it took a clear and decided position in favor of the "`Smaller Body,`" saying (p. 25):

If those Friends who compose the "`Smaller Body`"
continue to be entitled to the rights of membership,
and to such acknowledgment by their brethren as may be necessary
for securing the enjoyment of those rights,
certainly they have not seceded from the Society; and if so,
do they not still continue to hold New England Yearly Meeting as a superior,
in unity with, and to which the true Quarterly Meeting of Rhode Island,
and Monthly Meeting of Swanzey, are subordinate and constituent branches?
That the precedent would not be safe to be followed
in the organization of a (new) Yearly Meeting,
does not appear to apply to the sustaining of a Yearly
Meeting on its original organization or ground;
and particularly so,
when the maintenance of the doctrines and discipline of the Society
are acknowledged to have been the alone ground of action.
Does it not follow, that if there is but one true Monthly Meeting of Swanzey, and that,
of the "`Smaller Body,`" that as certainly,
there can be but one true Yearly Meeting of New England;
and can that be in unity with the separate Monthly Meeting of Swanzey?

Equally decided was its language in relation to the position of the "`Smaller
Body`" of Baltimore Yearly Meeting in the separation of 1854;
showing that the same principles of decision ought to be the criterion in this case,
that were the ground of judgment respecting the separation
of the Hicksites in Baltimore Yearly Meeting in 1828;
the ground of decision then being not one founded on the relative numbers,
or the identity of clerks,
but on adherence to the original sound doctrines of the Society.

In reference to the increasing tendency of many in Philadelphia
Yearly Meeting to give way to weakness and indecision,
this pamphlet says (p. 27):

Then upon what ground (with any degree of consistency)
can Philadelphia Yearly Meeting relax,
in carrying out its testimony against the fruits resulting from
either the adoption or encouragement of J. J. Gurney`'s sentiments?

And in conclusion (p. 31):

If in those primitive days there was no concord between light and darkness,
between truth and error, why should there now be?
Has the foundation been changed?
Or does there still remain but the Rock and the sand, to build upon?
Should any assume a medium ground, whereon to erect a structure?
Was it not so with the church of the Laodiceans?
To whom this language was addressed: "`I know your works,
that you are neither cold nor hot.
I wish you were cold or hot.
So then, because you are lukewarm, and neither cold nor hot,
I will spew you out of my mouth!`"

But this pamphlet, and others issued before and after it,
had no more effect in changing the course of those who controlled the Yearly Meeting,
than the Remonstrance of 1857 to the "`Contributors`" of The Friend had
towards inducing a change in the course of that periodical.

It might have been less needful to make so frequent and prominent allusion here
to the compromising or middle party of Philadelphia and Ohio Yearly Meetings,
were it not for the fixed persuasion,
that on the heads of that party rested an awful responsibility,
for the weakness that so rapidly increased in the
hitherto sound portion of the members there,
since the year 1846, and which soon spread its paralyzing influence elsewhere.
Would that the truthfulness of history had not required it.
But its development was and is an essential requisite,
both as to the past and what we have yet to contemplate.
We have seen some of the internal results of this spirit--truly a Laodicean spirit--tending
to a practical nullification of the standard which had begun to be raised by
Philadelphia Yearly Meeting against the innovations of the Gurney system.
We shall now have to consider the mischievous effects which ensued elsewhere,
from its course of discouraging and discountenancing, year after year,
even those "`Smaller Bodies`" which had been fostered and
encouraged in the stand they had taken for the Truth,
by the open and clear testimonies against the innovations in doctrine,
at first borne by Philadelphia and Ohio Yearly Meetings:
but whose isolated position may be truly traced to their faithfulness
to the testimonies then so ably advocated by those Yearly Meetings.

It might indeed be said of those two bodies: I have nourished and brought up children,
and then cast them adrift before the enemy!
And the assertion is a very safe one,
that but for the betrayal of the cause on the part of the leaders
of the middle system in Philadelphia and Ohio Yearly Meetings,
the "`divisions and subdivisions`" which were made so much
of by them as a reproach against the Smaller Bodies,
would in all probability never have occurred;
but a large body of Friends might have been preserved,
to bear a clear and clean and efficacious testimony
against the modern system of doctrine and practice.
Under the plausible representations of that compromising system, it is a sorrowful fact,
and one of the saddest pages in the history of our Society,
that many within those Yearly Meetings,
who had appeared indeed valiant for the Truth for some years, eventually gave way,
and thought that nothing more could be done than
to submit to the half-way temporizing measures presented,
in the vain hope of a conciliation of elements essentially antagonistic.
And when once they thus submitted, their strength was gone.

Thus the course of Philadelphia Yearly Meeting was for the future neutralized,
and its former noble testimonies rendered of no practical
efficacy (except as monuments of what it once was),
by the determination adopted, to keep all together,
and at all hazards to prevent a separation of the Gurney or popular party.
Can we then wonder, that such a change in its course, so unexpected,
and so unwarranted by its former faithfulness in the advocacy of the Truth,
should have had a powerfully discouraging influence
upon the small remnants of Yearly Meetings,
which had hopefully looked, in their weak condition,
for support and fellowship from Ohio and Pennsylvania?
Those small companies could not reasonably be supposed to
be exclusively composed of such as were truly baptized for
the work of suffering all things for the Truth and its testimonies,
and "`enduring hardness as good soldiers of Jesus Christ.`"
They had of course among them members of a considerable
variety of degrees of experience and strength;
and the sense that after awhile came over them,
that they were likely to be left to themselves,
and not owned by those to whom they had almost looked up as fathers,
fell like a storm upon many,
against which they were not rooted deep enough to stand steadily;
and some of these gave way to an idea that the views of those controlling
Philadelphia and Ohio Yearly Meetings must be met,
as far as practicable;
for that it would not do to be too stiff in a course which would certainly
alienate those important bodies of Friends entirely from them.

Then came weakness.
Human reasoning usurped, with some, the place of a patient waiting on Divine Wisdom;
and the proceedings of their small gatherings for the affairs of the church,
which before had been characterized by great sweetness and harmony,
began to be interfered with by unsettled and contentious spirits--the
very tools for forcibly verifying the predictions of the "`middle
party,`" that the "`smaller bodies`" would fall to pieces.
It is on this account,
and because the resulting "`divisions and subdivisions`"
have been greatly misunderstood and grossly misrepresented,
that it seems important to spend some time in endeavoring to develop their real nature,
and to trace the responsibility to its true source in the spirit of temporizing
which had taken possession of Philadelphia and Ohio Yearly Meetings.
The disastrous effects produced by this spirit,
outside of the limits of those two Yearly Meetings,
first became apparent in the company of Friends holding
New York Yearly Meeting (Smaller Body) at Poplar Ridge,
in Cayuga County.

This Yearly Meeting was then composed of remnants of the Quarterly Meetings of Scipio,
Farmington, and Ferrisburgh, with a very few members in Canada,
who were attached to Farmington Quarter.
One of their valuable members was Job Otis, formerly of New Bedford,
who had removed with his family to the neighborhood of Scipio, in 1833.
His account of incipient Hicksism in New England about 1822,
we have already alluded to in the first volume.
True to the ancient faith, he and his wife, while residing at New Bedford,
had taken very decided ground against the attempts
of William Almy and other influential members,
about the year 1830,
to introduce some of the modern views and ways promoted in the writings of J. J. Gurney,
but little known at that time on this side of the Atlantic.

By their firm testimony against the spirit then threatening
the welfare of the Society in New England,
some check was perhaps put to its inroads for the time;
but they brought upon themselves much obloquy and enmity,
and the standing of some of their opponents was such as enabled
them to circulate widely abroad prejudices against Job Otis,
and charges of inordinate zeal, which continued to assail him as long as he lived,
fanned of late years by the known antipathy to him of certain leading men in Philadelphia,
who were sensible that they could derive no help
from him to their temporizing policy and schemes.
He was ardent in his feelings, and bold in the expression of them,
and the prejudice against him had spread to his new place of abode,
and worked among some who were already leaning toward the middle system,
and looking to Philadelphia for help.

This feeling may perhaps also have been more or less partaken of by some others,
both there and previously in New England, of honest intentions, but who saw not as yet,
so clearly and promptly as he did,
"`the depths of Satan`" in the incipient departures and practical unsoundness,
and therefore were not prepared entirely to approve of his zeal and uncompromising earnestness.
Some of these, however,
are well understood to have had good unity with him at a subsequent period,
when the innovations had become more openly developed.
The result of this opposition to him was,
that although he was better qualified for usefulness
than many others among them at that crisis,
yet care was taken to prevent him, and some united in sentiment with him,
from being appointed to important services or stations in that Yearly Meeting.
Thus, that small body of Friends suffered the loss of some instrumental help in these respects,
and there seemed to be an increasing danger of drifting
into the course of the middle system.

After the decease of Job Otis, which occurred in 1856,
the antipathy of the disaffected ones against him settled upon those who were concerned,
as ability was afforded, to follow his example and walk in his footsteps.
Jealousies arose against certain Friends, with a determination not to be ruled by them;
and party spirit soon eating out the good and tender plant which
some of them had once known springing up in their hearts,
they appeared regardless both of the injury to their own souls and the
reproach that would be brought upon the cause they were engaged in,
by their contentions.
They made high professions of being subject to the Holy Spirit;
yet it was evident that many of them were very unwatchful
against the enemy`'s insidious presentations;
and the prominent ones too much actuated by exalted notions of their own righteousness,
and a corresponding desire to have and keep the control of affairs.
The sequel showed that they (like the middle party elsewhere) were disposed
to disregard or pervert the plain requisitions of the Discipline,
in order to carry their own measures.

The manuscript journal of that faithful servant of Christ, Joseph Hoag,
having been carefully left by him to the care of Friends sound in the faith,
and being proposed for publication,
furnished a handle for this contentious spirit to take hold of.
The papers,
after being for some time in the hands of a committee of their Meeting for Sufferings,
were sent by them to a friend in Philadelphia, for his care in revising them,
and preparing them for being put to the press.
He had full liberty to exercise his judgment in regard
to what should be proposed to be curtailed,
and what retained,
as the manuscript was seen to be somewhat unnecessarily voluminous for publication.
In the course of the revision,
he found a passage relative to the troubles about New Bedford of 1831,^
footnote:[For some allusion to which, see chap.
14.]
which appeared to him not to have been written with Joseph
Hoag`'s customary clearness from external bias,
but seemed to indicate that his mind might just then
have been influenced by one-sided information,
received from some with whom he was then mingling socially,
to take an erroneous view of the state of the case, and, under this view,
to write in a manner calculated to lead his readers to suppose that certain members,
not named (but evidently including such as Job Otis and his wife),
had been disposed to "`drive furiously`" with a "`false zeal.`"
It appeared to the friend having the revision in charge,
that this worthy man had not understood, at the time,
the efforts then making to introduce some of the very same views
and ways that have since characterized the Gurney system,
views which he faithfully withstood when fully developed at a subsequent period.
It did not seem desirable therefore, in justice to Joseph Hoag`'s memory,
or with a due regard to the position conscientiously
taken by Job Otis and others at that juncture,
to perpetuate the passage, and it was accordingly proposed to be omitted.

But, when the papers were returned to Scipio,
the erasure of this passage was soon noticed,
and gave great umbrage to the disaffected party,
who were much disappointed at not being sustained in their hope of retaining what they
looked upon as a confirmation of their sentiments in regard to Job Otis.
They were by no means satisfied that it should be omitted.
Angry letters were sent to the friend in Philadelphia, and much stir was made about it.
Job Otis had meantime been taken away by death,
but this made no difference with them in regard to the passage in question.
So determined were they to have it restored,
that it was found best to suspend the whole matter,
and the work was not published till after the separation
of the malcontents from Friends in the year 1859.

The disaffection began to manifest itself openly in 1857, and from that time,
till it culminated in a separation in the Yearly Meeting in 1859,
it gave sore trouble and exercise to the honest-hearted,
who were endeavoring to wade through their difficulties
and maintain the faith and discipline of the Society,
trusting in the protection of the Head of the church,
and relying upon the incomes of heavenly instruction graciously
vouchsafed to them at times in their great need.
The efforts of the disaffected party soon took the form of opposition
to the right administration of the discipline in treating with offenders,
and many unfounded and frivolous allegations were
made against those concerned to sustain it.
A female minister had, on one or two occasions,
made use of a somewhat ambiguous mode of expression.
This they took hold of to her disadvantage,
and attempted to make her "`an offender for a word;`" and although she manifested her
innocence of any unsound or even defective view of doctrine in what she had said,
yet they succeeded in preventing her from being liberated
by the Monthly Meeting soon afterwards,
for the accomplishment of a concern which she opened to it,
under a feeling of religious duty,
to attend Baltimore Yearly Meeting to be held at Nottingham.
They also took occasion to make her case an exception in
answering the Queries in the Select Preparative Meeting.

Two cases occurred in 1858, which still more strongly developed the party spirit,
and which indeed furnished, as it were,
the pivot on which the disorderly acts which led to the separation turned.
It would be very unprofitable to follow up all the details of these cases,
or to go into all the frivolous things which the party brought forward
to help them to frustrate the regular course of the discipline.
Suffice it to say that two female friends, caught by this party spirit,
were successively visited by the overseers on account of
defamation of the character of one of their fellow-members.
The Discipline of that Yearly Meeting is very clear in its injunction
that persons guilty of defamation and detraction must be faithfully
dealt with to convince them of their error,
and if the efforts of Friends are not successful, they must be disowned.
In these cases repeated obstacles were thrown in the way, first,
against their being reclaimed, by encouraging them to hold to their position,
and then against every step taken by the overseers and the Preparative
and Monthly Meetings in the further treatment of them respectively.

After considerable forbearance and patient labor with them, receiving no satisfaction,
Scipio Monthly Meeting disowned each of them.
The individuals declined to recognize the acts of the Monthly Meeting,
but nevertheless would take no steps to have their
regularity tested by the authorized method,
an appeal to the Quarterly, and then, if needful, to the Yearly Meeting.
The propriety and necessity of an appeal in these cases was very different
from what was apparent in the case of the separation in Iowa (see page
232). Here there was every prospect of a favorable hearing of such appeals.
One of their own party was the clerk of the Yearly Meeting,
and might probably have continued so, at least during the next year or two,
had he not joined in these disorderly measures.
The clerk of the Quarterly Meeting also was favorable to them.
But in Indiana Yearly Meeting the whole body, as such,
had already committed itself by joining the separatists, and therefore an appeal to it,
even if successful, would have been an acknowledgment of it in its schismatic position.
One of these females defied the action of the Monthly Meeting,
and set at naught the order of the Society,
by persisting in keeping her seat in the meeting
for discipline while she was under dealing;
and was encouraged in this disorder by prominent individuals of the disaffected class.
The overseers consequently felt it to be their duty to extend labor to some of
those who had thus encouraged her in conduct so contrary to the Discipline.

Throughout these transactions the dissentients complained bitterly of supposed grievances,
and afterwards put some of their complaints in print,
to their own disadvantage in the exposure of the weakness of their position.
Such of their allegations as were of any apparent
force were explained or refuted by Friends;
and on examination they appear indeed exceedingly weak.
Most of what they considered grievances,
such as the rejection of their voices in meetings for discipline
after they had joined in these disorderly acts,
were, in the true course of gospel order and church government,
the unavoidable results of their contumacious course,
which placed them in the attitude of defying the
well-known usages and regulations of the Society.
And their desire and attempts to embroil the superior meetings, in an irregular manner,
with their supposed grievances,
without having recourse to the methods prescribed by the Discipline,
furnished another instance of their disposition to carry
things in a high-handed manner in their own way.

In saying this, it is not intended to assert that there were no mistakes made,
in this time of uncommon and constantly pressing trials,
by those who were endeavoring to the best of their
ability to sustain the correct line of gospel order.
Undoubtedly there occurred some errors of judgment,
which furnished a handle to the disadvantage of Friends.
Yet these were all minor mistakes, made perhaps through inexperience,
in a zeal for the truth, and by no means vitiating the main issue.
For there was a great right and a great wrong which ran through all these transactions;
and the candid mind of the true disciple,
who should take the pains to wade through the mass of details in the printed statements,
with his inward eye directed to the light of Truth,
would probably not find much difficulty in deciding on which
side respectively the right and the wrong lay.^
footnote:[For detailed information on the subject,
the reader might refer to an address from New York Yearly
Meeting of Friends +++[+++King party+++]+++,
1859; also, Some Things Set Forth for the Clearing of Truth,
By Way of Reply to the Former, Auburn, 1859; An Exposition, etc.,
By the King party in Support of their Address, Auburn, 1859;
and Some Further Remarks for the Clearing of Truth, in Reply to the Exposition, Auburn, 1860.]

The leaders of these disorders,
seeing that they were now coming under the care of
the overseers as offenders against the discipline,
began to take measures for a separation.
After objecting to the appointment of a fresh overseer of the men`'s meeting,
and to the reappointment of overseers in the women`'s,
both of which measures appear to have been entirely regular, and legitimately effected,
and also opposing the reappointment of the clerk of Scipio Monthly Meeting, one of them,
at the ensuing Monthly Meeting in the second month, 1859,
renewed the expression of their objections to the clerk,
alleging that he had declined to take the names of their friends when proposed on appointments,
on the ground of disorder;
and on the same ground had refused to recognize their sentiments when offered;
that he had ignored their services in the Society;
and had refused to permit any application for advice or
assistance to be made to the superior meetings.

On these accounts he proposed the appointment of another clerk,
who would comply with their desires.
In regard to this charge of the clerk having rejected certain names on appointments,
it may be mentioned that this was after it had been expressed
by other friends that it would not be consistent with the
Discipline to take the names of such as had acted disorderly.
And as to the bringing of these matters before the superior meetings,
it was well known that there was a plain course of procedure marked out in the Discipline,
for cases of supposed individual grievance, which was the privilege of appeal;
to say nothing of the defective answers to the queries,
which would be a means whereby the superior meetings
could take measures for ascertaining the truth,
and eventually for endeavoring in a legitimate manner to remedy the disorders that existed.
But the dissentients wanted something more summary,
and would not avail themselves of either of these regular modes for relief.

An individual was then nominated to serve them as clerk
instead of the one reappointed the previous month,
and who was now acting;
and after waiting until the business was finished and the meeting concluded,
they continued in the house,
and went on with their separate Monthly Meeting with their newly appointed clerk.
John King, the clerk of the last Yearly Meeting, was one of this disorderly company,
and acted as its clerk.
Thus recklessly was a separation effected from the Monthly Meeting of Scipio,
by a party apparently utterly regardless of the reproach
thereby brought upon the cause of truth.
They certainly had no just ground for such a course,
and those whom they opposed were endeavoring to sustain
the gospel order of the church to the best of their ability.
Scipio Quarterly Meeting had a clerk favorable to the dissentients.
He therefore declined to recognize the report and representatives
sent up to the Quarter from the regular Monthly Meeting of Scipio;
but placing both reports as doubtful,
made a minute referring the case to the Yearly Meeting.
Friends urged the inconsistency of this course,
giving countenance as it did to proceedings so disorderly
as had characterized the measures of the Separatists,
but without avail.
They, therefore,
felt themselves under a necessity to sustain the Quarterly
Meeting in connection with the true order of the Discipline,
by appointing a new clerk.
Thus was a separation brought about also in Scipio Quarterly Meeting,
merely on points of discipline,
but actuated by a deep root of bitterness and jealousy on one part,
altogether unworthy of our religious profession,
notwithstanding the high and illusory pretensions of those who originated it.

The Yearly Meeting assembled in usual course, in the fifth month,
at the meetinghouse on Poplar Ridge.
John King, who had been clerk the foregoing year,
went to the table to act in that capacity as usual for the first sitting.
But as he had fully identified himself with all those disorderly measures,
and been indeed a prominent leader in them, and was now under dealing on that account,
it was obviously unfit for him to act,
and Friends could do no other than object to his assuming the position,
even for opening the meeting.
It was therefore mentioned that the previous clerk
had disqualified himself for acting in that capacity,
and James D. Otis was named to open the Yearly Meeting for business in his stead.
Several friends united with this nomination,
but a number of the Separatists and a few members
of Farmington Quarterly Meeting objected.

After some time, however,
James D. Otis was again requested to go to the table and open the meeting;
and no other friend being named for it, he did so.
After various remarks had been made, Mead Attwater, a minister from Farmington Quarter,
avowed his willingness "`to acknowledge the meeting as now opened.`"
But he then proceeded to propose a very singular measure,
being no less than the suspending of the Yearly Meeting,
in order to go into an investigation of the situation of subordinate meetings!
Such a proposal was somewhat similar to one made by John Comly for the Hicksites,
in the troubles of 1827,^
footnote:[Vol.
i, chap.
4.]
and was at best entirely premature and out of order,
as the names of the representatives had not been called over,
nor the reports from the Quarterly Meetings read,
and therefore the Yearly Meeting was not yet duly constituted
for transacting business or taking any regular action.
And if so suspended,
how could they in that condition have undertaken any regular business?

It was now stated that a person was present who had been disowned,
and two who were under dealing, and they were requested to withdraw,
that the meeting might be select and able to proceed with its business, and then,
at a suitable time, Friends might go into an investigation.
But the parties so obviously intruding on the rights of the Yearly Meeting,
by attending its sittings when disqualified by the plain rules of Discipline,
though repeatedly requested, were not willing to withdraw.
Mead Attwater continued to press his proposition to suspend
the Yearly Meeting and go into an investigation,
and several others promoted it.
Friends again requested those who were disqualified from attendance to leave the meeting,
so that they might proceed to business, and then, at a suitable time,
the subject of difficulty might claim attention.
But these requests being all unavailing, it was at length proposed,
as the only way left for making the meeting free from irregular intrusion,
to adjourn until 3 o`'clock; which being approved, the meeting adjourned accordingly,
and afterwards proceeded with its business in the regular manner.
As might have been expected, the Separatists remained,
and professed to hold the Yearly Meeting, with John King as clerk.

It soon appeared that their affinities were with
the half-way or "`middle`" party of Philadelphia;
but this sorrowful occurrence was the occasion of much reproach on the cause of truth.
The middle party exulted in it, as an evidence of the truth of their great dogma,
that "`separations were no remedy,`" tending, as they said it was evident they did,
to reproduce themselves--"`division and subdivision`"--and
the contemptuous cry of the party thenceforth was,
"`Look at Poplar Ridge!`"
But if perfect candor and uprightness had been their governing motive,
they might have seen that this separation at Poplar Ridge was a
result for which they were themselves accountable in great measure,
in discouraging and scattering weak brethren by their halfway course.
It was but the completion of what had been somewhat
imperfectly effected in the year 1848;
one of those "`sittings as from sieve to sieve,`" so often foretold.
For many of these separatists had never been truly and fully prepared,
by deep baptism of spirit and a thorough submission to the cross of Christ,
for the position in which they had, through more or less superficial motives,
been carried along with the others for a time.
They were, in short,
of too shallow root to endure the storm of a full consciousness
that they must either be content to abide with a despised few,
"`everywhere spoken against,`" and lose their hold on Philadelphia,
or so shape their measures as to please the middle party there,
from whom they vainly hoped for recognition.

Although, since the time of their secession, as above,
this company has remained entirely isolated, and become much reduced in numbers,
yet they still continue, in 1875, to hold meetings for worship in two places,
and a half-yearly meeting for discipline.
The separation from Ohio Yearly Meeting, narrated in the twelfth chapter,
gave rise to a suit at law, instituted by the Binns party, which,
not occurring till several years after the division, may be alluded to here.
The result might have been easily anticipated,
from the weakness of the course taken by the defendants (or middle party),
who ought (if they entered such a contest at all) to have stood openly
and firmly in testimony against the introduction of unsound doctrines,
which at least some of them well knew to have caused the separation.
But evading as they did, by a cowardly compliance with the opposite party,
that great characteristic feature of the whole secession (which may be said to have
mainly gained the cause for Friends in the famous Hicksian suit in New Jersey),
and instead of this, confining themselves to matters of technical order,
and easily made debatable,
they were quite as much to be blamed as pitied when they lost their case,
however erroneous the judgment of the Court.

In the year 1868, the original Gurney party in Ohio, who had separated, in 1854,
as the "`Binns`" Yearly Meeting,
from the Yearly Meeting of which Benjamin Hoyle was clerk,
entered suit against those of the latter, to recover, or rather to obtain,
possession of the boarding-school property of Ohio Yearly Meeting,
situated at Mount Pleasant.
The case was commenced in the District Court of Common Pleas of Jefferson County,
at Steubenville, and directed by that Court up to the Supreme Court of the State,
as involving important and difficult questions of law.
A considerable number of witnesses were examined on both sides,
and their evidence reduced to writing and subsequently printed.
But the subject of diversity of doctrines--the main life of the whole matter,
and without which the controversy dwindles to the
low position of a mere party dispute about clerks,
unworthy of sincere Christians,
and especially reproachful to the character of the Society of Friends--was,
by common consent, as appears by the evidence and by the pleadings of the counsel,
carefully excluded.

If the defendants (Benjamin Hoyle and others) had not belonged
to the "`middle party,`" which has done so much mischief to the
cause of Truth by wrapping up the very ground of the trouble,
even at the most critical times, and under the most critical circumstances,
this exclusion could scarcely have happened.
Benjamin Hoyle, of Ohio, and Charles Evans,
the editor of the Philadelphia "`Friend`" were among
the principal witnesses for this party,
and some of their testimony is remarkable indeed,
showing the pitiable evasions and contradictions,
and the flat formality to which they were compelled to resort
by their efforts to avoid the vital question of doctrines.
The main portion of the evidence related to small points of fact and order,
at the time of the conflict respecting clerks; as if that question,
in itself and of itself,
could have been of sufficient importance (with nothing to base it upon but these
points of order) to warrant such a schism in any professedly Christian church.
Some of the testimony, however, was worthy of note,
showing the flimsy character of the evidence on which they based their case.

George K. Jenkins, on the part of the plaintiffs, is recorded as declaring,
in reference to what occurred during the Yearly Meeting,
"`My conscience has nothing to do with this question;`" and he designated
a connection of Ohio Yearly Meeting with the troubles in New England,
as "`getting into a broil with regard to some difficulty away off.`"
William J. Harrison, another of the plaintiffs`' witnesses,
stated the numbers of those attached to the Binns Yearly Meeting as 2100 at that time,
including the Quarterly Meeting of Alum Creek,
transferred to it by Indiana Yearly Meeting.
He also stated the numbers in the last-named Yearly Meeting to be about 14,000,
Western about 12,000, and Iowa from 10 to 14,000;
but what authority he had for these numbers does not appear.
William S. Bates, who had left the Society altogether soon after the separation,
was much clearer in his statements respecting the usages of the Society,
and particularly as to the mutual connection and responsibility of Yearly Meetings,
than any other of the plaintiffs`' witnesses.
He distinctly recognized the truth, that a Yearly Meeting,
departing from the faith and fundamental doctrines of the Society,
"`ceased to be Friends,
of course,`" and that such departure gave other Yearly Meetings "`the right to interfere.`"^
footnote:[See the printed testimony in the case, p. 93.]
Yet even this opportunity was not taken by the Hoyle party,
to show how the ancient faith had been laid waste by the measures of the Gurneyites.

George Gilbert, for the defendants, testified:
"`I think B. Hoyle always stood on the ground,
that it was not best to have anything to do with either
body in New England until the matter was settled there.`"
Jesse Cope, also a witness for the Hoyle party,
being cross-examined by plaintiffs`' counsel, said,
in regard to what was the matter with the Yearly Meetings
with which they (the Hoyle party) did not correspond:
"`That would be a matter of doctrine, which I think is not to be admitted here.`"
Soon afterwards, the Court having decided that a certain question was objectionable,
and that plaintiffs "`had no right to ask what the departure in doctrine was,`"
the counsel for plaintiffs took exception to the ruling of the Court;
which seems at least to indicate an inclination on their part to
challenge the opposite party on the question of doctrines,
as if they knew well that they would not dare to touch it.
Benjamin Hoyle, being questioned:^
footnote:[See the printed testimony in the case of Harrison, etc., v. Hoyle, etc.,
in the Supreme Court of Ohio, page 120, etc.]
"`Then if the old clerk is at the table, there is no power to remove him?`"
answered: "`It was according to the settled order of the meeting that I acted,
on the ground that the meeting had no power to appoint
a new clerk when the representatives disagree.`"

Question by the Court.--"`Suppose that at the next Yearly Meeting
you should discover that your clerk had become a Hicksite,
and that a majority of your representatives present had embraced Hicksite doctrines,
and therefore would not be able to agree upon a clerk,
and the members of the representative body who had not embraced
those doctrines should report the name of a candidate for clerk,
would the meeting be compelled to keep the Hicksite clerk for another year?`"

Answer.--"`There is no means of removing a person for such a cause,
except by the action of the Monthly Meeting of which he is a member,
according to the rules of discipline.
There is a prescribed way, and it would be unsafe to displace any clerk,
whether Hicksite or what else.
If he becomes unsound,
it is for his Monthly Meeting to take away his right of membership,
if he cannot be restored.
I think the meeting would have to retain him, notwithstanding he was a Hicksite.
The Monthly Meeting takes away his right of membership,
and their action must be dealt with by the Quarterly Meeting.
He must retain his position as clerk until these proceedings can be gone through with.`"

Question.--"`Suppose a clerk comes to the table in liquor,
are you bound to keep a clerk at the table who is drunk every time he goes there?`"

Answer.--"`I have never known such a case.
If he is appointed clerk, he is appointed for the ensuing year,
unless displaced by the Monthly Meeting, and his right of membership is taken away;
and then, if his right of membership is taken away, or he is removed by death,
it is for the representatives to report another clerk.`"

Question.--"`But suppose they could not agree?`"

Answer.--"`That is a case that cannot occur.`"

Question.--"`Do you regard the Society of Friends as a unity +++[+++unit]?`"

Answer.--"`I do.
There is but one Society of Friends throughout the world.
I expect there is a considerable number of bodies that claim to be Yearly Meetings,
the same as we do.
We have not taken away the right of any Yearly Meeting claiming to be so;
though Indiana claims to take away the right of Ohio Yearly Meeting,
we have never taken action to take away their right.^
footnote:[Why then invade its jurisdiction by setting up Monthly Meetings within it?]
There is a regular Yearly Meeting of the Society of Friends
claiming that character in Indiana and Iowa.`"

Question.--"`Are there not two separate organizations
calling themselves the Society of Friends?`"

Answer.--`"Yes; there is in Ohio Yearly Meeting, and there are two in New England.`"

Question.--"`Is there a portion of your organization in Iowa?`"

Answer.--"`Yes; there is a Quarterly Meeting there.`"^
footnote:[Alluding to a Monthly (and afterwards a
Quarterly) Meeting set up by Ohio in Iowa,
as mentioned in the last chapter.]

Question.--"`And there is a Yearly Meeting in Iowa
that does not recognize that Quarterly Meeting?`"

Answer.--"`Yes.`"

Question.--"`There are two then in Iowa?`"

Answer.--"`Yes.`"

Question.--"`If your Meeting and this Quarterly Meeting
are the genuine legitimate Society of Friends,
then the Yearly Meetings of Indiana and Western, which recognized Binns,
are not meetings of the Society of Friends?`"

Answer.--"`I do not understand the question.`"

Question.--"`I mean, if yours is the only legitimate Society of Friends in the world,
then the Binns meeting and those which affiliate with it,
do not belong to the Society of Friends?`"

Answer.--"`I have not disfranchised any particular Society.
They do not recognize us; we have no communication with them whatever.
They were established as legitimate,
but so far as they have identified themselves with the Binns party,
we do not recognize them.`"

On Reexamination.--"`I do not expect that Ohio Yearly Meeting could decide upon the
question as to whether Indiana Yearly Meeting is or is not what it claims to be.`"

Charles Evans, of Philadelphia, testified, among other things, as follows:^
footnote:[Testimony, Supreme Court of Ohio, Harrison, etc. v. Hoyle, etc., p. 130, etc.]

Question.--"`What is the practice of the Yearly Meetings
on receiving ministers and members of other Yearly Meetings?`"

Answer.--"`It is usual in Yearly Meetings, when ministers come,
that they present their credentials, and they are heard in the meeting.
That is the usual practice.
Philadelphia has suspended that for many years,
and it does not hold itself called upon to read certificates
of members which come among them,
but receive them nevertheless, and they enjoy their rights as ministers.`"^
footnote:[But he omitted to say that this "`suspension`"
was a violation of their own Discipline.
The rule remained intact, but was evaded.]

Question.--"`What appeal is there from the action of the Yearly Meeting to a higher body,
on questions of a disciplinary, judicial, or legislative character,
or on questions that in any way affect the property of the Yearly Meeting?`"

Answer.--"`There is no authority in the Society of Friends superior to the Yearly Meeting.
Every Yearly Meeting is an independent body--independent in itself--connected
with the Society of Friends at large through the medium of a common faith,
but holding no relation of subordination to any part of the Society,
except that which it constitutes itself.
The union is one of Christian fellowship, simply.`"

Question (in cross-examination).--"`Why has your
correspondence with the Hoyle meeting not been continued?`"

Answer.--"`There has been in the Society of Friends within the last thirty years,
a considerable contrariety of opinion upon points of doctrine.
Philadelphia Yearly Meeting took its stand upon what
it believed to be the doctrines of Friends,
and endeavored, as far as it could, to maintain those doctrines and support them,
while there were others who, it believed,
were endeavoring to disseminate their doctrines.
These of course held it disunited,
and in the course of the correspondence which took place,
there was found a great contrariety of sentiment
making itself manifest in the Yearly Meeting.
And it was finally concluded that,
inasmuch as the correspondence was not necessary for the meeting to keep up,
it would be better that it should be all laid to one side,
and at the time it was concluded to hold no correspondence with any other Yearly Meeting.
The Yearly Meeting of Ohio was included in that conclusion.`"

Question.--"`I understand you hold the Yearly Meetings to be entirely independent?`"

Answer.--"`Yes.`"

Question +++[+++the counsel having referred to New England].--"`Then
you do take cognizance of other Yearly Meetings?`"

Answer.--"`We take cognizance so far as this,
that when the question was presented to Philadelphia Yearly Meeting as to whether
it would cut off a large number of persons from the Society of Friends,
it inquired into the position they then occupied, and in its investigation,
finding there had been, as it believed,
a violation of the discipline of New England Yearly Meeting, they pointed that out,
and sent these documents that I speak of,
and then granted the rights of membership to both
those bodies to attend Philadelphia Yearly Meeting.`"

Question.--"`Do you now in Philadelphia Yearly Meeting receive ministers
accredited by the subordinate meetings in the Binns Yearly Meeting?`"

Answer.--"`We never have had one present himself, or I have no recollection of it.`"

Question.--"`Do you receive members of those meetings, and recognize them?`"

Answer.--"`Since this has been mentioned to me, I do recollect one, a woman friend,
that had escaped my memory, who presented her certificate.
That was, like all others, not received.
We received none from any Yearly Meeting, from neither of the bodies in Ohio,
and from no other Yearly Meeting.`"

Question.--"`You said something about her, nevertheless,
being permitted to enter the meeting as a Friend?`"

Answer.--"`Certainly, she was.`"

Question.--"`That is what I want to know,
whether any who belong to the Binns meeting in Ohio are recognized?`"

Answer.--'`The Binns party was recognized in that instance, I have understood.
I was not cognizant of the facts,
but heard of her having been at different meetings within our limits,
and speaking as a minister.`"

Question.--"`Do you regard that as the practice of your meeting in that particular,
that they will so receive them?`"

Answer.--"`They will receive them as members of Ohio Yearly Meeting,
when they would not receive certificates which the meeting granted to those individuals,
as coming from Ohio Yearly Meeting.`"

Question.--"`They would, nevertheless,
recognize them as ministers of the Society of Friends?`"

Answer.--"`Unless they had certain knowledge that they had been disowned from the Society.`"

Question.--"`Don`'t you deal with the ministers of
the Hoyle meetings in much the same way?`"

Answer.--"`We take no cognizance of their credentials,
but allow them to exercise their functions.`"

Question.--"`If I understand you,
you say that the connection between those Yearly Meetings is simply a Christian brotherhood,
without any power over each other`'s standing in that brotherhood.`"

Answer.--"`Yes.`"

The Court.--"`You said, a moment ago,
that if a minister or member from Binns`'s party should come into your jurisdiction,
you would allow him to exercise his gifts, unless you knew he had been disowned.
Suppose you knew that Mr. Hoyle`'s meeting had disowned him,
would it not prevent your recognizing him?`"

Answer.--"`I cannot say whether it would or not.`"

The Court.--^
footnote:[Testimony, p. 138.]
"`Do you recognize the right in one Yearly Meeting to erect or
establish a Quarterly Meeting in the jurisdiction of another?`"

Question.--"`Not under ordinary circumstances.
There may a condition of things occur in which the Yearly Meeting would
be obliged to go beyond the ordinary usage of the Society in doing that.`"

Question.--"`Is there, or can there be, more than one Society of Friends?`"

Answer.--"`There is but one Society of Friends.`"

Question.--"`Then, in the recognition of one Ohio Meeting,
you necessarily exclude the recognition of the other?`"

Answer.--"`Yes, as a Yearly Meeting.`"

Question.--"`Then,
do you recognize Yearly Meetings of the Society elsewhere
which are in correspondence with the Binns meeting?`"

Answer.--"`Under peculiar circumstances it might be so.`"

Question.--"`Would the Yearly Meeting of the Society of Friends in Ohio be justifiable,
or have a right to establish Quarterly Meetings within the
limits of other Yearly Meetings of the Society of Friends?`"

Answer.--"`That would depend upon the action of the other Yearly Meetings.
If Ohio maintained its integrity as a Yearly Meeting of the Society of Friends,
and the other Yearly Meetings refused to allow it
to avail itself of the privileges of the Yearly Meetings;
if they refuse to recognize its members,
so that they cannot become incorporated into the Yearly
Meetings within the limits of which they reside,
when they have gone out of the limits of Ohio Yearly Meeting,
then it would become necessary for the Yearly Meeting of Ohio,
in order to keep up its care over its members, to create meetings for that purpose.`"

Question.--"`Does not that simply result, if it is extended,
in the organization of two religious Societies of Friends?`"

Answer.--"`No.`"

Question.--"`Suppose that the Yearly Meeting of Ohio should find
members desiring to belong to its meetings all over the country,
and should organize Quarterly Meetings in New England, Maryland, Iowa, Kansas,
wherever there were Yearly Meetings of the Society,
would it not appear to be the organization of two Societies of Friends?`"

Answer.--"`No. Allow me to explain.
The Society of Friends is a body which professes certain doctrines and testimonies.
While it maintains these doctrines and testimonies,
it is the Society of Friends under all circumstances.
It makes no difference as regards the position in which
members are placed in relation to any other body,
if it maintains these doctrines it is the Society of Friends.
In the organization of the Society of Friends,
for the purpose of exercising disciplinary care over its members,
and acquiring and holding property,
and the other things which Yearly Meetings can perform,
it is divided into a certain number of Yearly Meetings.
These Yearly Meetings are independent of each other,
so far that they exist without the assent of the others,^
footnote:[The defectiveness of these assertions must be manifest to the reader.]
and having once been established,
the others cannot take from them the character of a religious Society of Friends.
They may take from them participation in the organization which previously
existed in the Society of Friends before the difficulty occurred.`"

Question.--"`Suppose that instead of one Quarterly Meeting in the State of Iowa,
that the Hoyle Meeting should organize three,
and that these three shall organize a separate Yearly Meeting,
would there not then be two Yearly Meetings in Iowa?
Then if it extends its jurisdiction throughout the
territorial limits of the Society in the United States,
creating additional subordinate and Yearly Meetings,
have you not then two Societies of Friends in the United States?`"

Answer.--"`No. We have one Society of Friends, with two organizations.
We have but one Society of Friends, because the Society of Friends depends,
not upon the organization of its meetings, which may be altered from time to time,
but depends on the maintenance of certain doctrines and principles.`"

Question.--"`Well, now, then,
what objection have you to corresponding with the Binns Meeting?`"

Answer.--"`It is not set up in the order of Society.`"

Question.--"`Are these Iowa Meetings, set up by the Hoyle Yearly Meeting,
in the order of Society?`"

Answer.--"`Yes.
They are in the order, under the circumstances in which they are placed.`"

Question.--"`What will you do, then, with the two Meetings in Iowa?
They will both be Yearly Meetings of Friends,
but not both Yearly Meetings in the order of Society, will they?`"

Answer.--"`I do not see why they are not.`"

Question.--"`Have they unity?`"

Answer.--"`They may not have that unity which ought to exist.`"

Question.--"`You would recognize them both?`"

Answer.--"`Yes, if they maintained the doctrines of the Society,
and had been regularly set up and established.`"

Question.--"`How could such a state of things exist without leading to abuses,
and to great confusion in all their arrangements?`"

Answer.--"`It would undoubtedly lead to confusion--to a great deal of confusion.`"

Question.--"`Is it not impracticable?`"

Answer.--"`It is not impracticable, because it is in existence at the present time.
We see two bodies in Ohio calling themselves Yearly Meetings.`"

Question.--^
footnote:[Testimony, p. 144, etc.]
"`He +++[+++Thomas Evans]
was a brother of yours?`"

Answer.--"`He was.`"

Question.--"`Do you know what his opinion was on
the question of the Ohio Yearly Meeting separation?`"

Answer.--"`I do not.`"

Question.--"`Was he the author of a pamphlet on the subject of the Ohio separation?`"

Answer.--"`I do not know.`"

Question.--"`I find the 24th interrogatory (referring to the printed
testimony of the witness in the Swanzey +++[+++N. E.,
1848]
case), to be as follows: '`Suppose the larger part of a Yearly Meeting,
when assembled in that capacity, should be, together with their clerk, palpably unsound,
as evinced by their having promulgated or spread in the Society published works
containing doctrines decidedly adverse to the doctrines of the Society of Friends,
'`and knowingly recommending, aiding,
and defending the author or authors who have essayed to engraft
into and fasten upon the Society the said adverse doctrines;
would it or not,
be incumbent upon the other members of the Yearly Meeting to endeavor
to maintain and uphold the same upon its original Christian doctrines
to the honor of Truth?`' And this is published as your answer:
'`Such a Yearly Meeting,
constituted and sustained upon the original doctrines and testimonies of Friends,
let their numbers be as few as they might be,
could be recognized by the other Yearly Meetings of Friends,
although it might be necessary, in order to sustain it,
to enter into a new appointment of officers.`'^
footnote:[Depositions of Defendants in Fall River Suit, p. 308.]
Do you concur in this now?`"

Answer.--"`I do.
So far as I see, I believe these interrogatories and answers are mine,
but I cannot recollect.
As far as I see, I concur in them.
That was a question of doctrine.`"

This closed the examination.
Here was an emphatic implication--almost a direct declaration--that
doctrines were not involved in the dispute in Ohio!
Had not Charles Evans known clearly to the contrary?
Did he not know that the Gurney doctrines were at the very basis of the dispute?
Let his various publications, extending over a long series of years, testify to this,
yes or no.

There was a similar evasiveness in Benjamin Hoyle`'s testimony
in regard to doctrines being involved in this case.
But both he and Charles Evans did certainly know that the same
essential animus gave vitality to the contention in Ohio,
which had enkindled and characterized the contest in New England;
even the strife for prevalency between the doctrinal
innovations of Gurneyism on the one hand,
and the primitive doctrines of Friends on the other.
How could they then, by such evasion, put aside the true and all-important issue,
and thus place the Yearly Meeting of Ohio in the disgraceful
attitude of a mere wrangling about two men for its clerk?
It appears clear from the testimony of witnesses on both sides,
and from the pleadings of counsel on both sides,
that this exclusion of all development of the true cause
of the difficulty had been mutually agreed on;
but there are indications which seem to show at least a probability
that it was originally at the suggestion of the Hoyle party.
The plaintiffs`' counsel several times seemed to open the way for
alluding to doctrines in their questions to the defendants`' witnesses,
but it was always evaded.

D+++.+++ D. T. Cowen, of counsel for the Hoyle party, said,
in the course of his argument (p. 26):

During the progress of the trial of this case in the District Court,
it was decided in effect by the Court, and I think properly decided,
that this question +++[+++respecting the propriety of allowing
Thomas B. Gould to sit in the Yearly Meeting of Ohio]
had no bearing on the case,
and it was incompetent to introduce testimony in relation to it.
The plaintiffs`' counsel +++[+++Binns`'s]
put to their witness, Elwood Ratcliff, the question:
"`Was T. B. Gould in attendance at Ohio Yearly Meeting, in 1854,
bearing a certificate from the Yearly Meeting of New England, of which he was clerk?`"
This question was objected to +++[+++of course by the opposite counsel of the Hoyle party],
and the objection was sustained.
The plaintiffs`' counsel +++[+++Binns`'s]
excepted to the ruling of the Court.
(Pp. 44-5.)

In a subsequent part of his pleading the same counsel (Cowen) further says:

The questions before this Court are questions of discipline, and not of doctrine.
There is no dispute about that, and the case has been tried with that understanding.

In the printed argument of Benjamin Stanton, of counsel for the Binns party,
he says (p. 21):

Was it a question of mere personal aggrandizement,
and a struggle for place and power on the part of the candidate?
It was clear that there was something more than this.
The parties named as clerks were the representatives of parties in the Society,
and each was the representative of the sentiments of those by whom he was supported.
Was it a difference about doctrine?
If it was, then clearly we may inquire,
which of the parties held the approved doctrines of the Society?
But it is agreed on all hands that there is no dispute about doctrine--that
both held the approved doctrines of the ancient Society of Friends.
Then what was the dispute about?

He follows this up by a very superficial and partisan reference
to the opposition made in New England to J. J. Gurney,
and the separation there, charging J. Wilbur, T. B. Gould, and their associates,
with being "`malcontents and seceders;`" and then says (p. 32):

If it was a dispute about doctrines, the Court would go into their creeds,
to see which held the ancient doctrines of the Society.
But it is a question of submission to, or departure from, the government of the Church, etc.

And toward the close of his plea he makes the following remarkable assertion:

A religious society has as much right to change its doctrine,
as it has to change its discipline and government.

On a retrospective glance at some of the above quoted evidence,
it is obvious that Benjamin Hoyle endeavored to show that under no circumstances
could a Yearly Meeting disengage itself from a regularly chosen clerk,
unless he had been superseded by an agreement of the representatives,
or had been disowned by his own Monthly Meeting.
Thus a Yearly Meeting might be subjected to the necessity
of keeping in service a "`drunken`" clerk,
or "`a Hicksite,`" or one guilty of reproachful conduct,
if the representatives could not agree on his successor,
or there had not been timely knowledge of his faults for his own
Monthly Meeting to act in the usual exercise of the discipline.
A new doctrine, surely, in the Society of Friends,
and only consistent with a state of lifeless formality!

The entanglement of this witness, and also of Dr. Charles Evans,
in their attempts to justify the action of Ohio Yearly
Meeting in setting up a Monthly Meeting in Iowa,
within the limits of another Yearly Meeting,
while endeavoring to avoid the only justification of such action, namely,
the honest declaration of their belief, accompanied with proof,
that this other Yearly Meeting had departed from the essential groundwork of the Society,
and could, therefore, be no longer recognized as a meeting of Friends,
was indeed hardly to be expected from their character as sensible men.
Charles Evans, too (see page 269),
must have known that a Yearly Meeting is in very deed no more independent
of its brotherhood of Yearly Meetings abiding in the Truth,
than an individual member is independent of his brother members;
and that if a Yearly Meeting breaks the compact by sanctioning a fundamental
departure from the great characteristics of the family of Yearly Meetings,
it is equally liable to be called to account by those who remain faithful,
as in individual cases.
Else, as the Society "`is a unit,`" what becomes of Robert Barclay`'s doctrine,
as stated in his work, The Anarchy of the Ranters,
etc.? And what becomes of C. Evans`'s own declaration in the Considerations,
pages 21 and 22? And what becomes of Samuel Bettle`'s
testimony in the Hicksian suit in 1830?^
footnote:[See Vol.
1 of this work.]

Both B. Hoyle and C. Evans endeavored to make it appear that the reason for setting
up an Ohio Monthly Meeting within the limits of Indiana Yearly Meeting in Iowa,
was that Indiana Yearly Meeting had refused to grant privileges
of membership to those emigrating from the Hoyle meeting;
but such was known well enough not to have been the
true reason at the time of that event.
Many of the members removing to Iowa were not willing to
be brought under the jurisdiction of Indiana Yearly Meeting,
and the Hoyle Yearly Meeting desired to protect them from this,
and at the same time to extinguish the hopes of a small remnant who had already,
as a Quarterly Meeting, separated in Iowa from the lapsed Indiana Yearly Meeting,
and were in correspondence with the small body of Friends in New England.
The idea of Charles Evans in regard to "`one Society of Friends with two
organizations,`" is too preposterous to be soberly entertained by anyone,
who considers that two organizations in one place must necessarily be antagonistic,
and cannot, therefore, be of one and the same body.
"`Confusion,`" indeed, would be, and was, the inevitable result of such reasoning.

The Supreme Court of Ohio consisted of five Judges.
This Court, after long delay, decided, by a decree dated sixth month 20th, 1871,
in favor of the plaintiffs, the Binns party.
In coming to this judgment, the vote was,
two in favor of giving the property to the Hoyle party, who already occupied it,
and three to the Binns party.
The property was accordingly delivered over to the plaintiffs--the original Gurney party
represented by Jonathan Binns as clerk--on the 1st of the eighth month of the same year.
It would not be worth while now to quibble about
mistakes made by the Court in coming to this decision,
in a case which they had so defectively set before them.
They seemed to have a very imperfect acquaintance with the road on which they were travelling,
and stumbled like men passing over a swamp in the dark.
But not more so than might have been looked for, and, right or wrong,
their judgment is now the law of the State of Ohio.
The principal grounds of their opinion appear to have been, first,
that J. Binns was in some way (regularly or irregularly,
as Judge Shaw said in the Fall River suit) named
and appointed as clerk in the Yearly Meeting;
and, secondly, but mainly,
that the standing of the body for which he acted had been afterwards
sanctioned by all the other Yearly Meetings except Philadelphia,
leaving out of view the "`Smaller Bodies,`" which the Hoyle
party had not dared to appear to reckon as brethren.
Whether this claim will be further pursued by the Binns party taking
measures to obtain the meetinghouses and other property of the
Yearly Meeting on the strength of such a decision,
remains to be seen.
The school building at Mount Pleasant has since been destroyed by fire.
