== Chapter XVI.

[.chapter-synopsis]
* Subdivision in New England, in 1863
* Rise and Failure of a General Meeting of the Smaller Body in Ohio.

There was still to be experienced a low and somewhat
sifting period in the progress of the "`Smaller Bodies.`"
Abundantly clear was the evidence from time to time afforded by the events which
followed the development of the half-way or compromising policy in Pennsylvania,
New Jersey, and Ohio, that the Smaller Bodies,
as originally isolated from the modernized meetings,
contained a mixture of that same half-way element,
which was not prepared to stand firm in the day of trial.
We have already seen it exemplified in the separation of the King
party from the Yearly Meeting of New York at Poplar Ridge,
and we have now to witness a similar feature in New England.
Alas! it is a grievous and a dismal thing to trace the further progress of the "`divisions
and subdivisions`" thus fomented by the enemy of the Lord`'s truth and people.
But a sense of religious duty requires that these transactions be faithfully recorded,
so far at least as to demonstrate their true bearing,
and place the responsibility where it rightly belongs;
that the cause of Truth itself may not suffer,
through the weakness and failure of some of its unwatchful advocates,
or the misrepresentations of its opponents.

In contemplating the evidences of this weakness,
we ought to remember that the members of the Smaller Bodies did not profess to
have taken their isolated position because they were wiser or better than other
men--far from it indeed--but because they were favored to see clearly the fundamental
changes which the great body of the Society was drifting into,
and they could not conscientiously unite with it therein,
and thereby plunge themselves and their families into the same obvious and vital changes.
They were not generally individuals of long experience or large attainment,
and some of them had at first joined the movement, doubtless,
from motives more or less defective.

The separation of what was called "`the King party,`" of New York,
caused not only a great reproach to be cast upon all the small remnants,
but also tended in a particular manner to weaken that of New England,
and thereby gave the adversary a plea to raise a special cry of exultation.
This company of Friends had, since the separation made by the disciples of J. J. Gurney,
in 1845, lost, many of its most experienced and faithful members by death;
including Seth and Mary Davis, Prince Gardner, Francis Taber, Thomas Foster, John Wilbur,
and Thomas B. Gould; whose absence from their deliberations was very sensibly felt,
as well as the absence of the continued example of their steady and upright walk.
Some of those now left upon the scene of action had depended perhaps
too much on the large experience and right authority of these,
and not being of equally solid religious attainments, and, it may be,
trusting too much to their own intellectual abilities or to the
prestige of their rightly qualified elders and relatives,
were not equally endowed as counsellors in the affairs
of the church during perilous or critical times.
Some of these also, looking too much outward,
had unhappily imbibed more or less of the middle policy,
which induced them constantly to encourage a hope
of eventual recognition by Philadelphia Yearly Meeting,
and to shape their measures in accordance with that vain hope.^
footnote:[This clinging to a hope of eventual recognition
has continued to be manifested in a frequent attendance,
even of late years, of Philadelphia Yearly Meeting by some of their prominent members,
and also by the tenor of an Epistle issued by them in 1870.]
These, of course,
also partook of the ill-founded repugnance mentioned in a former chapter
as entertained by certain leaders of the middle party in Philadelphia,
against the memory of Job Otis, and even against those who had unity with him.

Representations were made,
calculated to prejudice the minds of honest Friends in New England,
who knew not all the circumstances,
against the course taken by those Friends of Poplar Ridge who had stood firm
in resisting the disorderly and disorganizing measures of the King party;
and an opinion was now advanced and strongly urged,
that no separations were justifiable except on the
ground of attempts to introduce unsound doctrines;
its advocates apparently forgetting how recently some of them had
encouraged by their presence a few in New York in setting up an
entirely unauthorized separate meeting for worship,
with no other alleged cause for it than what was merely personal in its nature;
forgetting also that every disownment of a delinquent
member is a separation of the Church from that member,
differing from the other in the numbers involved, and in the moving cause.
Thus, much disunity and difficulty were produced in the Smaller Body of New England.
A pamphlet was published by one of the objectors in 1860,
founded on the same untenable sentiment,
and harshly censuring the sound Friends of New York Yearly Meeting,
as if they had been the cause of the King separation;
but by no means sustaining the charges with anything
worthy of being looked upon as evidence of it.^
footnote:[This very weak pamphlet elicited a reply from David Heston,
then a resident at Poplar Ridge,
and a member of the "`Smaller Body,`" briefly defending the course pursued by our Friends,
as having been in true gospel order,
and for the sustaining of the discipline of the Society.]

Under such influences, aided by great unwatchfulness on the part of some,
a party soon appeared in New England,
whose efforts were bent to obstruct the recognition
of what was styled "`the Otis party`" of New York,
in the hope, apparently,
of thus facilitating their own recognition by Philadelphia Yearly Meeting.
To accomplish this purpose they persisted for four years in a course which
sorrowfully rent the bonds of fellowship that had existed among them,
and carried grief and sore discouragement into the hearts of many of their Friends abroad.
When their Yearly Meeting, in 1859, received information of the events at Poplar Ridge,
through epistles addressed to it by each of the parties,
that meeting was so much divided in sentiment on the subject,
that it failed to come to any conclusion,
but referred the question to the care of the Meeting for Sufferings.
This meeting, after much discussion and difficulty, adopted, in the fourth month, 1860,
a report to the ensuing Yearly Meeting,
to the effect that they were not united in recommending
the recognition of either of the two bodies at Poplar Ridge.
The Yearly Meeting, in the sixth month, after a very painful deliberation on the subject,
came to the same conclusion.
It was therefore left without decision to another year.

The longer the question was left undecided, the weaker the Yearly Meeting became.
Those dissenting from correspondence with Friends of Poplar Ridge
attempted to sustain their opposition by pressing the idea,
that because doctrines were not the basis of the controversy in New York,
but questions of discipline, the separation was not only not to be countenanced,
but both parties were to be rejected;
although they fully admitted that the separation
had been begun by the King party in the Monthly Meeting,
and they were not able to fasten upon the others the charge
of having acted essentially or fundamentally wrong,
so as to vitiate their position as standing against disorder.
It was not necessary to spend time in refuting their opinion
that doctrines were the only ground for separations.
Neither had those Friends for whom James D. Otis acted as clerk,
attempted to justify the separation;
but they had satisfactorily cleared themselves from
the responsibility of having caused it.
Friends of that Yearly Meeting had been acknowledged
as brethren for several years by those of New England,
and it was now a very serious thing to deprive them all of that character,
by breaking the connection with both parties,
without discrimination as to where the responsibility lay.

At the Yearly Meeting of 1861, a continuance of the same opposition prevented any action;
and in 1862 this opposition was extended also to the reception of an Epistle
and a Minute from the General Meeting of Friends held at Fallsington in Pennsylvania.
Nevertheless, after a painful discussion of the matter for three hours,
the latter were both read.
But the dissenting party would by no means permit anything further
to be recorded on minute respecting the meeting at Fallsington,
than a bare notice of the reception and reading of the documents.^
footnote:[Their aversion to the General Meeting at Fallsington
can only be accounted for by its having united with those
Friends of New York from whom the King party had separated,
and by the fact that it bore a clear testimony against Philadelphia Yearly Meeting,
whose favor these dissenting ones manifested an anxiety to secure.]
The recognition of the New York Yearly Meeting was still successfully resisted by them.
They also showed their oneness of practice with the middle party of Philadelphia,
by objecting, at this and previous Yearly Meetings,
to correspond with the Smaller Body of Baltimore; though they alleged,
as their reason for this,
that they also had recognized one of the meetings
in New York having James D. Otis for clerk.
Thus the success of their plan would have isolated the "`Smaller
Body`" of New England from all the others now existing.

The Yearly Meeting convened at Newport, as usual, on the 15th of sixth month, 1863.
Several friends were present from within the limits of New York Yearly Meeting,
and the General Meeting held at Fallsington,
and one member of the "`King`" meeting of New York.
After attending to the usual preliminary business,
the Epistle from Baltimore Yearly Meeting, held at Nottingham, was read and minuted,
though with some opposition.
The clerk then informed the meeting that there was on the
table an Epistle from the General Meeting held at Fallsington,
in Pennsylvania, and suggested that,
as one from that meeting had been read among them the previous year,
this might be read at the present time.
A letter, now before the writer, from one who was present,
declares that the solid sense of the meeting was to have it read.
But quite a number strongly opposed it,
several of them proposing to refer it to a committee.
The other Friends could not consent to this,
being convinced that the General Meeting held at Fallsington was composed of Friends
who were endeavoring to do the best they could to stand for the cause of truth,
and knowing, too, that the Epistle from that meeting had last year been read and minuted.

After a painful discussion of about two hours and a half,
the clerk at length stood up to read the Epistle,
intimating that he believed the prevailing sense of the
livingly exercised members was to have it read.
The principle had always been maintained, in the healthy days of the Society,
that the clerk`'s duty is to act according to the mind of Truth,
as expressed in the meeting under a living concern
and exercise of mind by the consistent members.
On no other principle than this can our meetings
for discipline be sustained on the primitive ground;
but its abandonment must lead (and has led) to confusion and defection.
As the clerk was about to read the document,
he was interrupted by one of those dissenting, and sat down; but, after a little time,
arose again and read the Epistle, and some Friends expressing satisfaction with it,
he made a minute accordingly.
Two of the members wished the expression of satisfaction stricken from the minute,
but this was not done.
The meeting then adjourned to the afternoon.
At the adjourned sitting,
the representatives reporting that they had not been
able to agree on any name to propose as clerk,
the clerk of the previous year, according to former usage, was continued in the service.
He then proposed the reading of the New York Epistle;
which was united with by a number of friends,
but strenuously opposed by the dissenting portion of the members.
After a great deal had been said, of a very painful character,
it was concluded to adjourn to the next morning at nine o`'clock.

On Third-day morning, the 16th,
the meeting resumed the deliberation respecting the New York Epistle.
Much opposition was again expressed to its being read; and,
after various harsh expressions had been uttered,
a friend of considerable influence rose and expressed his sense
of the sorrowful condition to which the meeting was brought;
adding that, in reflecting upon their situation,
he was impressed with the belief that they were not able, in their present condition,
to hold a Yearly Meeting any longer to the honor of the Head of the church.^
footnote:[It would appear that there was not sufficient ground for so sweeping a declaration,
even in the weak condition of the Yearly Meeting at that time;
and its inconsiderate expression must have greatly
discouraged the friends of right order,
and promoted disintegration.]
He said he had some weeks ago laid this subject before
the Meeting for Sufferings for consideration.
Several now, who had objected to the reading of the Epistle,
perceiving to what the friend`'s proposition tended,
expressed a willingness to submit to hear the document
read (though they could not unite with it),
rather than proceed to such an extremity.
These were told, however, by this same friend,
that the reading of that Epistle now would not make things any better;
they had been contending for four years about the correspondence,
and were the Epistle now read,
the same difficulty must recur every time such reading was renewed.

This sentiment,
questionable and injudicious as its utterance at that time appears to have been,
had a very discouraging effect on the meeting.
The clerk, being called on to proceed with the business, arose,
and after alluding to the sorrowful disunity which was so manifest among them,
declined further service as clerk for that meeting, in the condition it was then in.
Several of the members now expressed views somewhat similar in
tenor to the sentiments expressed by the other friend above mentioned.
A deep silence then spread over the assembly.
After this, one of the dissenting members remarked, that the clerk having now resigned,
it would be necessary to appoint another;
which being united with by those of similar sentiments,
and other friends taking no further part, they appointed Valentine Header,
the assistant clerk, to act as clerk for them.
He soon made a minute of adjournment, and all left the meetinghouse,
even the books being left in his possession.

It is known to the author that the clerk,
who had declined serving the meeting any longer, had no prospect of any further measures,
nor had he any other expectation when leaving the meetinghouse,
than that of returning to it for the afternoon session,
or until some way should open for relief.^
footnote:[This shows that he was not engaged in any preconcerted plan.]
This feeling was participated by some other friends with him.
But early in the afternoon Friends were requested to meet together at a friend`'s house,
where many of them were staying;
and on deliberating on the disunity so manifest in the Yearly Meeting,
the same friend above mentioned expressed his belief that "`it
would be unsafe for them to return to the meetinghouse.`"
The influence of what he said was such, that other friends fell in with this view,
and under feelings of great trial, but with a trust in divine mercy and help,
this little stripped company, consisting, as it was thought, of about forty friends,
concluded to continue the sittings,
apart from those who had opposed their fellowship with the other smaller bodies.

It is undeniable that this was a very summary procedure.
Whether it was the best that might have been done under all the circumstances,
is a question which perhaps can scarcely be judged clearly by those who were not present.
I have given those circumstances as impartially as, so far as I can see,
the truth will allow.
Those Friends who were in fellowship with the other small bodies thought, at the time,
that the step was called for and essential for their safety, and believed that,
however sorrowful, they were graciously sustained by divine approval.
A living though crippled remnant survived,
which was now enabled to join hand to hand with their brethren in other parts,
concerned to maintain the ancient faith of the Society,
untrammeled by the illusory pleas of a half-way policy.
There was a spirit of opposition to the other small bodies
manifested among those from whom they had retired,
similar to that which had shown itself in much larger assemblies, a few years previously,
and which seemed at this time to preclude much hope of harmonious
labor together for the cause of truth.

Yet, as we have seen above,
the dissenting portion of the meeting had now expressed some submission
to the views of others (though a late and reluctant one),
and if the advocates of fellowship with the rest of the
small bodies had then firmly but temperately and tenderly,
in the fear of the Lord, held their ground (which they had the right and power to do),
those dissenting, or at least some of them,
might have gradually submitted more entirely to the convictions of truth,
and harmony might perhaps have been restored.
The Annual Meeting, however, was in this manner and to this extent sustained,
and appointing Peleg Mitchell as clerk, requested him to prepare a suitable minute,
to set forth the cause of their peculiarly trying situation,
for attention at a future sitting; and then adjourned to ten o`'clock the next morning.
The meeting next morning is described by one who was present as a tendering season,
in which prayer and supplication ascended.
The minute prepared by the clerk was read, considered, and adopted,
and the meeting adjourned to the afternoon.
They had again a comfortable season, at which some business was attended to,
including the reading of the New York Epistle,
and the appointment of a committee to prepare a reply thereto,
and likewise epistles to Baltimore Yearly Meeting and the General Meeting at Fallsington,
if way should open for it.

In the sitting on Fifth-day, the essays of Epistles to the Meetings held at Poplar Ridge,
Nottingham, and Fallsington, were read and adopted;
and the minute describing the causes leading to their present
tried situation was directed to accompany each of the epistles.
This minute is chiefly a brief narration of the circumstances
which have been above described.
A time of quiet solemnity ensued,
and the clerk finally read the concluding minute--to
meet again at the usual time the next year,
at Newport, if the Lord permit.
These Annual Meetings of Friends for New England,
in fellowship with Friends in other parts concerned
to withstand the defection in principle and practice,
have since continued to be regularly held at Newport, Rhode Island; and,
though much reduced in numbers,
they have been attended with a comfortable evidence of the merciful care and
help of the Great Shepherd extended toward his tribulated "`little flock.`"
Their correspondence was promptly received and reciprocated
by the meetings of the smaller bodies in other places,
excepting, of course,
those who had joined in with the separation from Friends in the State of New York,
with John King for clerk.
These latter became entirely isolated from all other remnants of the Society;
as was also the case with the meeting held by those in New
England who left the fellowship of the other small bodies;
and this isolation still continues;
neither of these two latter meetings being recognized or
corresponded with by any other meeting of the Society whatever,
nor even by each other.
In view of the inadequacy of the cause and dubious
circumstances of the separation just described,
it is greatly to be desired, that through the softening influences of divine love,
melting down all that is of self and tends to alienation,
the way may open for a right reunion of brethren and sisters having one object in view,
even the sustaining of the precious testimonies of
the gospel committed to our primitive Friends.

Nearly all the men of Israel who came out of Egypt, of an age to be equipped for war,
perished before ever reaching the promised land.
Because of their murmuring and lack of faith, their "`carcasses fell in the wilderness.`"
Yet their failure did not invalidate or in any degree
make void the gracious purposes of the Most High,
in bringing them forth,
that He might conduct his church through the wilderness
unto a land of favor and of promise,
a land flowing with milk and honey.
We have never heard it said that the action of the Israelites
in leaving Egypt could not have been a right one,
because so many of them rebelled and died on the way.
Neither has it been alleged, except it might be by unbelievers,
that David`'s course was unjustifiable, when he fled for his life to the cave of Adullam,
and was joined by a few followers, some of whom were, indeed,
of no honor to his reputation among princes.
The Lord works by whom he will,
and his choice of instruments--perhaps in order to bring to nothing the pride of man--is
sometimes such as would not seem likely to the judgment of the human intellect.
And even should some such instruments prove rebellious,
and turn aside before their work is accomplished,
this does not vitiate his choice of them,
or frustrate the fulfilling of his will in his own time;
for he can and does call in others, and qualify them to carry on his purposes,
so that his word may not return unto him void,
but may accomplish that whereunto he sent it, and prove to rebellious man,
that He is God over all, overruling all things to the honor of his great name,
that the pride of man may be laid in the dust.

We have now to move westward,
and contemplate the sad devastation effected within Ohio Yearly Meeting,
through the laying waste of the testimony by the "`middle party`" there,
even after the departure from them, in 1854,
of the more open advocates of the Gurney schism.
Benjamin Hoyle, for many years the clerk of Ohio Yearly Meeting,
soon after the separation there of 1854,
led the way in a very determined manner for the temporizing party,
in imitation of the same class in Philadelphia, and, as it would seem,
at the dictation of their leaders, to repudiate all the "`smaller bodies.`"
In the Yearly Meeting of 1857,
he is said to have been the first to oppose the reception
of the credentials of a minister from one of these bodies,
after there had been a deliberate and large expression
favorable to their being received and read.
He also objected to recognizing the Yearly Meeting for Baltimore, held at Nottingham,
because, as he said,
they had corresponded with New York and New England (smaller bodies).
And on one occasion he went so far as to assert,
that "`doctrines had nothing to do with the separation in
New England--it was a mere matter of discipline!`"

It was also, about this time, mainly through his influence,
that a series of irregular measures was taken,
resulting in the establishment of meetings in Iowa (which
was then within the limits of Indiana Yearly Meeting),
subordinate to Stillwater Quarterly Meeting, Ohio, of which he was a member;
by which the sound Friends there were, as we have already seen,
so greatly interfered with, and their meetings diminished and discouraged,
instead of being cherished as they should have been by Ohio Yearly Meeting.
The meetings thus established in Iowa by Ohio Yearly Meeting,
and made branches of the Quarterly Meeting of Stillwater, it must be remembered,
were directly within the limits of Salem Quarterly Meeting of Friends
of the "`smaller body,`" already established and apparently settled;
so that this hitherto unheard of measure was in itself
a manifest invasion and intrusion upon them,
and could not have been undertaken but with a hostile
intent against that Quarterly Meeting,
which had never belonged to Ohio, but to Indiana Yearly Meeting.
It was evidently designed to prevent the growth, and, if possible,
the continued existence of that little company of Friends,
which had come forth in unity with the "`smaller bodies`"
in their testimony against the modern innovations in doctrine.
We have seen how it was attended with the expected result.

In Ohio Yearly Meeting of 1861,
the certificates of two ministers from within New York Yearly Meeting,
held at Poplar Ridge, were refused reception,
notwithstanding a large expression in favor of their being read.
The epistle from Fallsington General Meeting was also rejected,
by the prevalence of the middle party`'s influence.
Much unity was expressed with that General Meeting by many solid substantial Friends,
who desired that the epistle might be read, but it was not done.
Many friends, deeply concerned for the welfare of the Society,
and who had earnestly hoped that a way would be made
for decided action by that Yearly Meeting,
through which their fellowship with faithful Friends elsewhere might be fully manifested,
went home with sorrowful hearts.
During one sitting,
Benjamin Hoyle strongly opposed a minute being sent to the Monthly Meetings,
encouraging them to put the Discipline in practice
against the Gurney separatists of 1854;
he and his party alleging that these people ought not to be dealt
with as offenders--that they were as sound as they were themselves.
In this, however, he did not then succeed.
He inveighed bitterly against the two ministers and their companions,
then present from New York, designating that Yearly Meeting,
and the General Meeting at Fallsington, as separatists.
He went so far in some of his remarks as to be rebuked by the assistant clerk;
but his influence nevertheless continued to control the middle
party there (even after he was released from the clerkship),
through the submissiveness of many who allowed their faith to fail in time of need.

The direction to the Monthly Meetings to put the Discipline
in practice in regard to the separatists of 1854,
which had passed the Yearly Meeting of 1861 with some difficulty,
was so distasteful to B. Hoyle and many of that party,
that very few of the meetings acted in accordance therewith.
Shortcreek was the only Quarterly Meeting which sustained it,
and this was not in all its branches.
The Yearly Meeting of 1862 was characterized by the sorrowful submission
of many--who had hitherto seen clearly the errors of the middle
party--to be carried along with them in their measures,
for the sake of peace.
Among other evidences of lapse, a minute was made,
modifying the Discipline so far as regarded the treatment
of the Gurney separatists of 1854,
in such a way as to authorize Monthly Meetings to disown them in a wholesale manner,
without any efforts for their convincement of error.
Many friends mourned over the condition of the Yearly Meeting,
which had isolated itself from all the small remnants of the Society,
as well as from the Gurney meetings,
and was now tampering with the most important features of the Discipline.

Some of these friends, as before,
lost their faith in regard to taking a firm stand against such proceedings; while others,
who felt discouraged in regard to attending another Yearly Meeting under such circumstances,
nevertheless did not see that this was the time to make an open stand.
These went to their homes under much discouragement,
feeling that the power of the defection, if not its spirit,
was paralyzing not a few who had previously walked with them,
and stood valiantly for the Lord`'s cause,
but who now seemed willing to submit to one measure after another,
by which the efficacy of their testimony was defeated and its vitality taken away.
Thus, with many friends,
all hope of the Yearly Meeting being brought to a willingness practically and
firmly to sustain the ancient faith and consort with the advocates of it,
was now entirely lost.
Some of the controlling party even seemed to exult in the
power they had gained by the submission of others,
and openly declared that they "`never would own`" the Smaller Bodies.^
footnote:[The General Meeting`'s printed [.book-title]#Address,# 1863, page 16.]

Now, in their great discouragement and weakness, came a procedure,
the ultimate event of which seems to indicate it to have been beyond
the ability of those concerned in it to carry it out through all
besetting difficulties to the honor of Truth,
and raises the question, whether the movement was well matured,
or whether it would not have been more in accordance with divine
wisdom to have abode awhile longer in suffering and patience,
and in the hope that a way might still be opened for their relief,
with more clear evidence of the leading of the great Shepherd of Israel, who,
when he puts forth, will go before,
and sustain those who look with a single eye to the pointings
of his cloud by day and pillar of fire by night.
Considering the condition, at that time, of Ohio Yearly Meeting,
the writer has been ready to query whether,
when the stand for the ancient truth was taken there, it should not have been made,
or at least suggested, during the sittings of the ensuing Yearly Meeting itself,
when there might have been a more general concurrence
of sentiment among Friends sound in faith and doctrine,
and deploring the departures equally with those who inaugurated
the movement in a very detached manner and form.

Was it judicious to act so exclusively of many other Friends of at least equal experience,
and equally interested and deeply grieved with the control
assumed over the Yearly Meeting by the middle men?
Did it not shut out needlessly and hurtfully a source of strength by which they
might have otherwise been helped to maintain their standing on the true foundation?
Many Friends to the eastward of Ohio were taken by
surprise on hearing of the mode of this procedure;
but were induced to own the organization,
in a hope and trust that it was in right ordering,
and in a consideration of the fact that it was the
only body in Ohio acknowledging fellowship with them.
It appears that in several parts of Ohio a few friends,
acting under this despair of the Yearly Meeting,
and a belief that the time had come for them to testify against its retaining,
as a lapsed body, any rightful authority, began to meet, during the autumn of 1862,
for divine worship, apart from the usual meetings,
which were held subordinate to the Yearly Meeting.
This, perhaps, was well.

But without waiting for the Yearly Meeting of 1863,
in which they might have been strengthened by the
fellowship of other friends very dear to them,
a General or Conference Meeting of these isolated ones convened at Chesterfield,
in Morgan County, on the 20th of the sixth month of that year.
They could no longer countenance the irregular,
compromising course of the Yearly Meeting of Ohio, and believed it to be their duty,
in its present condition,
to disown and condemn the Laodicean spirit by which it was controlled;
which had led it to discountenance all those small bodies
of Friends who had unfurled the banner of the ancient faith,
and whom it had at one time acknowledged as brethren and sisters
"`endeavoring to support the same testimonies`" with itself.
About fifty individuals, of both sexes, were thought to be in attendance.
A considerable portion of the first sitting was occupied in silent waiting,
with desires to be rightly qualified to enter upon such services as might present.
The meeting held two sittings that day, and adjourned to Second-day morning,
the 22nd. Various matters were then brought before their attention,
which were harmoniously resulted;
including the appointment of Friends to needful services;
and the meeting concluded to meet again on the 26th of the ninth month, at Harrisville,
if the Lord should permit.
In a view of the help which it was believed had been mercifully granted in their deliberations,
the hearts of many were tendered, and made thankful to Him who cares for his children,
and who had condescended to comfort them in their low and stripped condition.

The General Meeting again convened, according to previous arrangement,
in the ninth month, at Harrisville.
The sittings, as before, were on Seventh and Second days,
with a meeting for public worship on the intermediate First-day.
At this time a document was presented for consideration,
by a committee appointed at the previous meeting,
explanatory of the causes which had led Friends to meet as they were now doing,
apart from the Yearly Meeting of Ohio.
This document was read, and adopted by the meeting,
and directed to be printed for circulation.
The meeting ended comfortably.
It was a season of humbling instruction to many minds,
and of thankfulness to our Heavenly Father for his
condescending mercy and goodness to his poor,
weak, unworthy creatures.
The document adopted on this occasion, and afterwards published in pamphlet form,
entitled, An Address to the Members of the Society of Friends in Ohio and Elsewhere,
clearly showed the positions taken by the meeting issuing it,
and the causes which had so sorrowfully led to the separation;
the facts therein brought into view being chiefly such as have been here described,
manifesting with somewhat more detail the inconsistent position
into which the Yearly Meeting of Ohio had been induced to slide,
by the illusory devices of the middle party there and in Pennsylvania.

Friends in other places, belonging to the smaller bodies,
were now for a time comforted in the contemplation of a
standard for the ancient faith being raised in Ohio.
But their congratulations were brief; for the enemy was,
alas! soon at work to undermine the fellowship of
the General Meeting of Ohio with their brethren,
and to level their standard to the ground!
There were some truly concerned and honest-hearted friends among them, who had been,
according to their ability, valiant for the ancient faith.
But even some of these, not abiding in true humility and watchfulness,
laid themselves open in an evil day to the wiles of the cruel deceiver,
and fell into his snares.
Oh, the darkness of that day, when the bonds of fellowship were found to be broken up,
and some who had been felt as brothers suddenly went off into bitterness and alienation!
No pen can describe the grief that came like a flood upon many,
and this without knowing any just cause for the change in their feelings.
But there was a cause--and a sad one too--and we must now endeavor briefly to trace it.

If all had closely obeyed the injunction, "`Be not high-minded,
but fear,`" the catastrophe which soon assailed this little
company could never have swept them away as it did.
One or two of their prominent members had unhappily become exalted,
not only in their own self-estimation, very different from their former state,
but also in the feelings of many brethren and sisters who were
placing an undue reliance upon their judgment and stability,
to the partial neglect of the Witness for Truth within their own souls.
Indeed,
there had been from the first an unsafe degree of
confidence in these on the part of some,
which had interfered with their own growth in true wisdom and discernment,
at the same time that it facilitated the fall of those whom
they had thus contributed to lift up beyond their true measure,
and above the safe place of waiting, in deep humility before the Lord,
for every fresh supply of strength or qualification.
Thus the body was weakened, and a door opened for the inroads of the spirit of deceit.
While a testimony was still maintained for the ancient doctrines of the Society,
the ground of genuine Quakerism was in measure practically lost sight of,
by the neglect of the essential duty of each one to be individually concerned, to seek,
in deep humility and singleness of heart,
and with "`senses exercised by reason of use,`" to
know the inshinings of the light of truth for himself,
and not merely by another,
and thus to have the understanding enlightened to "`discern between good and evil.`"

Thomas Lamborn,
who had been recently acknowledged as a minister in Nottingham Quarterly Meeting,
and had removed in the year 1860, to reside near Scipio, New York,
was frequently engaged in the ministry, both at home and among Friends in other parts,
and generally, it is believed, to the satisfaction of sound friends.
There was manifest, however, at times, a degree of strong will and self-confidence,
not wholly subdued by the fire of the Lord`'s jealousy, which,
operating fully in his soul,
might have accomplished the work of making him a "`pillar
in the Lord`'s house that should go no more out.`"
Yet meantime he appeared to be zealous for the spreading of truth,
and indefatigable in travelling as a minister in various places.
In some parts where he went, particularly towards 1864 and 1865,
some few Friends became secretly uneasy in perceiving
indications of the strong will above mentioned;
but a disposition was cherished to hope for the best, and to avoid dwelling on,
or exaggerating foibles which might be corrected by a little further experience.

In the spring of 1865,
T+++.+++ Lamborn opened to his Monthly Meeting a prospect
of visiting Great Britain in the work of the ministry.
This very serious concern was approved in the Monthly Meeting,
and afterwards in the Quarterly Meeting of Scipio;
though on the latter occasion some friends were not quite satisfied of
the clearness of feeling that it was right at that time to sanction it.
But these did not venture to express their dissent,
from a fear of stopping what might be a right concern.
It therefore proceeded in due course to the Yearly
Meeting of Ministers and Elders at Poplar Ridge,
in the fifth month.
But Thomas had been, during the previous winter and early spring,
travelling extensively in Ohio and Pennsylvania,
and had imprudently talked about his prospect to
a considerable variety of individuals here and there,
even previous to spreading it before his friends at home for their judgment;
and had indeed, thus early,
gone so far as to involve an influential member of the Ohio
General Meeting in a strong desire to accompany him.

Friends went to the Yearly Meeting of Ministers and Elders with no other
expectation than that his concern would be sanctioned by that body;
but when the meeting came solidly to consider it, there was felt to be,
very unexpectedly, so heavy a cloud resting upon the tabernacle,
that they dared not move one step towards liberating
him for so very weighty and arduous a service.
Only one voice was heard in favor of his liberation for it,
and that was from a friend not a member of that Yearly Meeting,
and only recently appointed to the Select Meeting in Ohio, where she resided.
The meeting thus not being able to move in the matter,
the concern was necessarily suspended.
There was a tender feeling of sympathy for him on the part of many friends,
accompanied with a hope that this unlooked-for suspension of his prospect,
painful as it might be to him, might prove a profitable lesson,
and tend to his furtherance in solid instruction and humility;
and thus might open the way, perhaps, to a different result, at a future time,
if he should be rightly prompted to reopen his concern.

There was at first some reason to hope that he would
thus quietly settle down under his disappointment,
and endeavor to profit by it.
But several of his too ardent admirers became at once exceedingly
excited at what they deemed a wrong decision,
and spread far and near their disapprobation of the action, or non-action,
of the Select Yearly Meeting at Scipio;
endeavoring to provoke a morbid sympathy for him whom they supposed
to have been so improperly impeded in his religious services.
Thomas, giving way to further unwatchfulness and willfulness,
appears to have been roused by this sympathy into
a feeling of resentment against his friends,
which he manifested in some public communications.
At the same time, the clerk of the Ohio General Meeting,
who had fixed his mind on accompanying him in his visit to England,
became so disappointed and grieved,
that he also gave way to a spirit of sharp and bitter
alienation against those Friends with whom,
but a very short time before, he had apparently walked in harmony and fellowship.
This bitter feeling, strange to say, immediately extended,
not merely against those in New York who had been
concerned in the suspension of T. L.`'s concern,
but even against those also in Pennsylvania and other places who
were not prepared to unite with him in censuring the former.

He had at that time an undue influence among some
of the members of the little company in Ohio;
so that his alienation of feeling at once spread among these,
and woeful indeed were the results of their implicit confidence in him.
T+++.+++ Lamborn, who had been advised on behalf of the elders of his meeting,
in his present unsettled state of mind and disunity with his friends,
to refrain from offerings in the line of the ministry,
nevertheless addressed a ministerial epistle to the ensuing General Meeting of Ohio,
apparently for the purpose of enlisting their sympathy.
This epistle was affectionately accepted,
notwithstanding the information which was given to them that the
writer of it was not now in unity with his friends at home.
And not only did they accept this epistle, but refused to accept, or record,
the credentials of several friends in the ministry from Scipio,
then travelling among them, and with whom they had previously united.
Two of T. Lamborn`'s sympathizers, belonging to the General Meeting held at Fallsington,
had become restive and much excited on his account,
and in this condition had attempted to impose their unsavory
and denunciatory offerings in the way of ministry,
upon their friends in Philadelphia; on account of which,
and their persistence therein after earnest and tender admonition,
they had been dealt with as offenders, and one of them had been disowned.

But these, moving about this time to reside in Ohio,
were at once taken by the hand by the adherents of T. Lamborn,
and treated as members in full unity, although they were informed to the contrary.
One of these two was even permitted to pay religious visits to their families,
as if he had been a recommended minister,
when they knew that his friends in Philadelphia had
not only never acknowledged his ministry,
but had disowned him for his persisting in a disregard of the advice given him
to desist from his denunciatory disturbance of their meetings for divine worship.
The General Meeting for Pennsylvania, etc.,
was brought under deep sorrow on account of these unlooked for breaches of gospel order,
and of the brotherly unity which had before existed,
and in 1866 addressed an affectionate epistle of caution and warning
to their brethren and sisters in Ohio on the subject;
but received no reply, nor anything to show why they had been induced so to act.

After waiting more than a year, without receiving any reply to their epistle,
or any notice of the reasons for their alienation,
the General Meeting held at Fallsington, in the sixth month, 1867,
again addressed them in an epistle of tender and serious expostulation
on the inconsistency and irregularity of their course;
showing also their deep solicitude,
"`that the enemy of all true unity in Christ Jesus may be frustrated
in his attempts to sow discord in the camp of Israel;
whereby he would overthrow the faith of some,
and raise a stumbling-block and occasion to fall, in the way of the weak,
and give to the opponents of the testimony of truth,
a plea for glorying over the afflicted remnants of the Lord`'s people.`"
In this epistle they plainly demonstrated to them how inconsistent their present
course was with their own previously declared testimony for gospel order,
and how it would, if persisted in,
tend to the subversion of all church government and Christian fellowship.^
footnote:[_An Epistle to Ohio General Meeting, on Church Government and Gospel Order,
etc.,_ 1867; printed in Philadelphia, 1868, page 5.]

This brotherly appeal and expostulation was sent to the clerk,
addressed to the General Meeting of Ohio; but was not even opened by him,
being returned by direction of that meeting, with the seal unbroken,
accompanied by a minute,
expressing that "`a paper purporting to be an epistle from the General Meeting
of Fallsington,`" had been brought before the view of their meeting--that they
had declined to read it--and that they desired the writers thereof to "`retract
and condemn`" their "`action:`" but offering no explanation,
what "`action`" was to be condemned, or what was the cause of their dissatisfaction.
The distress that was brought upon friends of the General Meeting for Pennsylvania, etc.,
is not to be described in words.
It seemed as if an infatuation of no common character had suddenly
seized upon their beloved brethren and sisters in Ohio,
which had led them, without any cause given,
into a course of conduct altogether unaccountable,
and inconsistent with their previously expressed sentiments.

Six months after issuing the above mentioned expostulatory epistle,
the General Meeting held at Fallsington received it back into their hands unopened.
There did not appear to be anything more now to be done,
in the way of endeavoring to reclaim those who had so grievously gone astray,
except to leave them to the Lord.
But a duty appeared to rest upon the church,
to clear itself and the small companies with which it was united,
from the reproach that might attach to such a course of disorder,
if no testimony were issued against such irregularities.
Whereupon,
after sorrowful deliberation on this sad condition of those who had been
formerly looked upon as brethren and sisters in a testimony for the truth,
it was concluded needful to place on record a brief
statement of the attempts made for their restoration,
and, seeing these had now proved ineffectual,
a testimony of denial of further fellowship with them.
The latter is thus expressed:

[.embedded-content-document]
--

In consideration of these sorrowful departures from the uniform
practice of meetings of Friends in their fellowship one with another,
which strike at the foundations of all church government and gospel order,
we are constrained to testify our disunity with their proceedings,
and that the meeting which still claims the name
of the General Meeting of Friends of Ohio,
can no longer be acknowledged by us as of the same household of faith.
Yet we earnestly desire the preservation of the honest-hearted within its borders,
on the true foundation, on which alone Christ will build his Church.

--

The Monthly Meeting of Salem, in Columbiana County,
had not gone as a body with these disaffected persons,
though a portion of its members were among the most prominent of them.
The rest of them stood their ground against this disorder,
besides a few scattered individuals in other parts of Ohio.

The following copies of minutes made successively by that Monthly Meeting^
footnote:[[.book-title]#Record Book of Salem Monthly Meeting of Friends,# Ohio, page 17, etc.]
show the tried situation into which they were brought,
in their concern to sustain the true gospel order
of the Society against deluded and erring brethren;
the disorganizing party eventually separating from them,
and carrying up that separation to their General Meeting, which,
in owning the party of disorder,
opened the way for the release of the sound portion of the Monthly Meeting of Salem,
with a few in other parts of the General Meeting.

[.embedded-content-document.minute]
--

_Minute of fifth mo., 9th,
1867._--On account of the disorderly proceedings of a disorganizing party in this meeting,
Friends remained after those persons had withdrawn.
The clerk having gone out with them,
the assistant clerk was requested to proceed with the business of the Monthly Meeting;
and this minute being read and united with, the meeting adjourned,
to meet again on Fourth-day, the fifteenth of the month.

_Minute of fifth mo.,
15th._--Friends have been brought into deep trials on account of a disorganizing
spirit which has for some time prevailed among us,
and of late to such an extent as to produce disunity with all those meetings of Friends,
which, when this meeting was established,
the General Meeting of Ohio was in correspondence with; and with whom,
in a testimony issued by said meeting, in 1865, it is stated,
"`we were closely united in the fellowship of the gospel;`" but now, instead thereof,
all fellowship and correspondence with them is withdrawn,
the disciplinary action of their meetings disregarded,
persons who have been disowned by them being allowed
and encouraged to sit in our meetings for discipline.
One of those persons, having been an approved minister,
but recently disowned by the Monthly Meeting of which he was a member,
was not only encouraged to sit in our meetings for discipline,
but was furnished with a minute acknowledging him
as acceptable and his services edifying.

Another disowned person, who never had been a member of a select meeting,
was liberated by minute of two of our Monthly Meetings,
to pay a religious visit to the families constituting them;
and at this Monthly Meeting disowned persons attempted
and were encouraged to sit in our meeting for discipline,
and also requested to have their names recorded as members on our books,
which was united with by those in unity with them.
Such gross and repeated violations of the order and discipline of our Society,
Friends bore their testimony against;
and seeing no other way to maintain that order and discipline,
and also the unity and fellowship with those meetings which we were in
correspondence with when this Monthly Meeting was established,
but to endeavor to sustain it on the original ground,
after the disorganizing party had withdrawn,
Friends proceeded with the business of the Monthly Meeting so far as to
make a minute showing the condition in which this meeting was placed,
and then adjourned to the fifteenth of the month,
when the foregoing minute was read and adopted.

_Minute of ninth month,
12th._--The Representatives to the General Meeting made the following Report,
which is approved and accepted by this meeting: '`We,
the representatives to the General Meeting,
were all in attendance agreeably to appointment,
and presented to that meeting the Reports and Statement issued by this as directed;
but that meeting, under a profession of being led and guided by the Spirit of Truth,
without an investigation, rejected them as coming from a spurious meeting,
and received and acted upon the Reports of the separate
meeting set up and held at New Garden.
Being thus cut off by the General Meeting, we,
with other friends in unity with the action of this Monthly Meeting,
met together to endeavor to feel after what was right
for us to do under these painful circumstances.
The result thereof was, that it was our duty as a portion of the General Meeting,
to inform those meetings with whom we have been in correspondence,
that our number is too small to sustain that meeting to the honor of Truth.
A brief account of the transactions of the General Meeting was written,
a copy of which we offer this Monthly Meeting; which,
together with the statement before mentioned,
was placed in the hands of a few friends to copy and forward
to the several meetings with which we were in correspondence, etc.
This meeting, taking into consideration the isolated condition in which it is now placed,
as set forth in the report of the representatives,
believed it right at this time to appoint a committee,
to take the subject into consideration,
and endeavor to feel after the propriety of taking some preparatory steps towards a
recognition of this by one of those superior meetings with whom we have fellowship.
Accordingly the following friends were appointed, etc.

_Minute of eleventh month, 13th._--The committee appointed in ninth month last,
to take into consideration the propriety of taking some preparatory
steps towards a recognition of this Monthly Meeting by one of those
superior meetings with whom we have fellowship,
reported that after solid deliberation on the subject,
they believed the time had come to propose to the Monthly Meeting the propriety
of applying to the General Meeting of Fallsington for their recognition thereof;
which being approved,
this meeting came to a united judgment to request the General Meeting of Fallsington
to acknowledge this Monthly Meeting as a branch of that body;
and for the causes which have placed us in our present position,
we refer that meeting to a statement of this Monthly Meeting which was
directed by a portion of the General Meeting of Ohio to be transmitted
to the several meetings with which we were in correspondence.

--

The above application was received and solidly considered
in the General Meeting held at Fallsington,
in the twelfth month, 1867.
Much sympathy was felt and expressed, and the meeting came to the following conclusion;
a conclusion warranted and made obligatory upon them as brethren,
by the apostatizing action of the Ohio General Meeting,
whereby they had broken off from fellowship with all the other Smaller Bodies,
and left in an isolated state the members of Salem Monthly Meeting,
and a few in other parts of Ohio,
who could not unite with them in their disorderly course:

[.embedded-content-document]
--

Much sympathy has been expressed in this meeting
with our dear friends in Ohio thus situated,
and we greatly desire their encouragement in an honest and faithful
discharge of the responsibilities now resting upon them,
for the sustaining of the testimonies of Truth in that portion of the heritage.
And in view of the extraordinary circumstances of the case,
this meeting unites with the proposal of Salem Monthly Meeting,
and hereby acknowledges it as a component part of this General Meeting.

--

As to the rest of that company forming the General Meeting of Ohio,
though they still professed to hold the meeting,
they gradually became more and more confused and estranged from Friends,
and even from each other; some of them soon discarded all discipline;
and several of the most prominent of them became dissatisfied even with T. Lamborn himself,
in sympathy for whom they had plunged at first into this disorder;
and at length a number of them went so far as to decline
attending their own meetings for worship or discipline.
They appear indeed at present like sheep having no shepherd,
and scattered here and there upon the dark mountains.
Yet there has been a gathering back of some few of them, of latter time;
and it is much to be desired that still others may, through Divine favor and help,
be enabled to see the nature of their wandering, and be willing to retrace their steps.
